Repository pantsbuild/pants, pull requests merged in 2018-07, with the labels that each got.

#5943 Introduce libc subsystem to find crti.o on linux hosts and unskip the native backend subsystem tests
  build-support/bin/ci.sh
  contrib/node/src/python/pants/contrib/node/subsystems/command.py
  src/python/pants/backend/native/config/environment.py
  src/python/pants/backend/native/subsystems/BUILD
  src/python/pants/backend/native/subsystems/binaries/BUILD
  src/python/pants/backend/native/subsystems/binaries/binutils.py
  src/python/pants/backend/native/subsystems/binaries/gcc.py
  src/python/pants/backend/native/subsystems/binaries/llvm.py
  src/python/pants/backend/native/subsystems/libc_dev.py
  src/python/pants/backend/native/subsystems/native_toolchain.py
  src/python/pants/backend/native/subsystems/products/BUILD
  src/python/pants/backend/native/subsystems/utils/BUILD
  src/python/pants/backend/native/subsystems/utils/__init__.py
  src/python/pants/backend/native/subsystems/utils/parse_search_dirs.py
  src/python/pants/backend/native/subsystems/xcode_cli_tools.py
  src/python/pants/backend/native/tasks/BUILD
  src/python/pants/backend/native/tasks/link_shared_libraries.py
  src/python/pants/backend/native/tasks/native_compile.py
  src/python/pants/backend/python/tasks/setup_py.py
  src/python/pants/engine/scheduler.py
  src/python/pants/releases/BUILD
  src/python/pants/util/contextutil.py
  src/python/pants/util/dirutil.py
  src/python/pants/util/strutil.py
  tests/python/pants_test/backend/native/subsystems/BUILD
  tests/python/pants_test/backend/native/subsystems/test_native_toolchain.py
  tests/python/pants_test/engine/scheduler_test_base.py
Labels: native

#6217 Associate cli arguments with executables and refactor llvm/gcc c/c++ toolchain selection
  src/python/pants/backend/native/config/environment.py
  src/python/pants/backend/native/subsystems/binaries/binutils.py
  src/python/pants/backend/native/subsystems/binaries/gcc.py
  src/python/pants/backend/native/subsystems/binaries/llvm.py
  src/python/pants/backend/native/subsystems/native_toolchain.py
  src/python/pants/backend/native/subsystems/utils/BUILD
  src/python/pants/backend/native/subsystems/utils/archive_file_mapper.py
  src/python/pants/backend/native/subsystems/utils/parse_search_dirs.py
  src/python/pants/backend/native/subsystems/xcode_cli_tools.py
  src/python/pants/backend/native/tasks/c_compile.py
  src/python/pants/backend/native/tasks/cpp_compile.py
  src/python/pants/backend/native/tasks/link_shared_libraries.py
  src/python/pants/backend/native/tasks/native_compile.py
  src/python/pants/backend/python/register.py
  src/python/pants/backend/python/subsystems/python_native_code.py
  src/python/pants/backend/python/tasks/build_local_python_distributions.py
  src/python/pants/backend/python/tasks/setup_py.py
  tests/python/pants_test/backend/native/subsystems/test_libc_resolution.py
  tests/python/pants_test/backend/native/subsystems/test_native_toolchain.py
  tests/python/pants_test/backend/python/tasks/test_build_local_python_distributions.py
Labels: native, needs-cherrypick

#6237 Fix spurious deprecation warning for fatal_warnings
  src/python/pants/backend/jvm/subsystems/zinc_language_mixin.py
Labels: needs-cherrypick

#6179 Add basic native task unit tests.
  src/python/pants/backend/native/tasks/link_shared_libraries.py
  src/python/pants/backend/native/tasks/native_compile.py
  src/python/pants/init/engine_initializer.py
  tests/python/pants_test/backend/native/tasks/BUILD
  tests/python/pants_test/backend/native/tasks/native_task_test_base.py
  tests/python/pants_test/backend/native/tasks/test_c_compile.py
  tests/python/pants_test/backend/native/tasks/test_cpp_compile.py
  tests/python/pants_test/backend/native/tasks/test_link_shared_libraries.py
  tests/python/pants_test/engine/test_isolated_process.py
  tests/python/pants_test/test_base.py
Labels: needs-cherrypick

#6205 Fix pydist native sources selection
  src/python/pants/backend/native/tasks/c_compile.py
  src/python/pants/backend/native/tasks/cpp_compile.py
  src/python/pants/backend/native/tasks/link_shared_libraries.py
  src/python/pants/backend/native/tasks/native_compile.py
  src/python/pants/backend/native/tasks/native_external_library_fetch.py
  src/python/pants/backend/python/subsystems/python_native_code.py
  testprojects/src/python/python_distribution/ctypes/BUILD
  tests/python/pants_test/backend/python/tasks/BUILD
  tests/python/pants_test/backend/python/tasks/test_build_local_python_distributions.py
  tests/python/pants_test/backend/python/tasks/test_ctypes.py
  tests/python/pants_test/backend/python/tasks/test_ctypes_integration.py
  tests/python/pants_test/backend/python/tasks/test_python_distribution_integration.py
  tests/python/pants_test/backend/python/tasks/util/BUILD
  tests/python/pants_test/backend/python/tasks/util/__init__.py
  tests/python/pants_test/backend/python/tasks/util/build_local_dists_test_base.py
Labels: needs-cherrypick
