Repository pantsbuild/pants, pull requests merged in 2018-12, with the labels that each got.

#6846 don't redundantly call environment_as() to avoid an encoding error for mysterious env var value
  tests/python/pants_test/backend/native/subsystems/test_native_toolchain.py
Labels: flaky-test, needs-cherrypick

#6857 add `scala_jar` to the docsite
  examples/src/java/org/pantsbuild/example/3rdparty_jvm.md
  examples/src/scala/org/pantsbuild/example/README.md
Labels: documentation

#6961 Add support for deprecating scoped SubsystemDependencies
  src/python/pants/option/optionable.py
  src/python/pants/option/options.py
  src/python/pants/option/scope.py
  src/python/pants/subsystem/subsystem.py
  src/python/pants/subsystem/subsystem_client_mixin.py
  tests/python/pants_test/option/test_options.py
Labels: P3 - M1
