Repository pantsbuild/pants, pull requests merged in 2019-05, with the labels that each got.

#7655 Short-circuit primitive encoding on CoercingEncoder
  src/python/pants/base/hash_utils.py
Labels: needs-cherrypick

#7683 Fix ordering of args from compiler_option_sets and add test for scalac profiling
  src/python/pants/backend/jvm/tasks/jvm_compile/jvm_compile.py
  src/python/pants/option/compiler_option_sets_mixin.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/zinc/zinc_compile_integration_base.py
  tests/python/pants_test/pants_run_integration_test.py
Labels: needs-cherrypick

#7731 bump pex version to 1.6.7
  3rdparty/python/requirements.txt
Labels: needs-cherrypick

#7723 [v2] Pipe LineOriented through the Console
  src/python/pants/engine/console.py
  src/python/pants/engine/goal.py
Labels: UX, options

#7687 Fix 'current' platform check for python_dist() targets with C/C++ sources
  src/python/pants/backend/python/subsystems/pex_build_util.py
  src/python/pants/backend/python/subsystems/python_native_code.py
  src/python/pants/backend/python/targets/python_distribution.py
  src/python/pants/backend/python/tasks/build_local_python_distributions.py
  src/python/pants/backend/python/tasks/resolve_requirements_task_base.py
  testprojects/3rdparty/python/BUILD
  testprojects/src/python/python_distribution/ctypes/BUILD
  tests/python/pants_test/backend/python/tasks/native/test_ctypes.py
  tests/python/pants_test/backend/python/tasks/python_task_test_base.py
  tests/python/pants_test/backend/python/tasks/test_build_local_python_distributions.py
  tests/python/pants_test/backend/python/tasks/test_python_binary_integration.py
  tests/python/pants_test/backend/python/tasks/test_resolve_requirements.py
  tests/python/pants_test/backend/python/tasks/util/build_local_dists_test_base.py
Labels: needs-cherrypick

#7746 Confluence publishing uses correct text types
  contrib/confluence/src/python/pants/contrib/confluence/tasks/confluence_publish.py
Labels: needs-cherrypick

#7758 Memoize graph walks on Context
  src/python/pants/build_graph/build_graph.py
  src/python/pants/build_graph/mutable_build_graph.py
  src/python/pants/engine/legacy/graph.py
  src/python/pants/goal/context.py
  tests/python/pants_test/build_graph/BUILD
  tests/python/pants_test/build_graph/test_build_file_aliases.py
Labels: needs-cherrypick

#7773 Revert v2 zipkin support due to #7415.
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/engine/native.py
  src/python/pants/engine/scheduler.py
  src/python/pants/goal/context.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/pantsd/service/scheduler_service.py
  src/python/pants/reporting/report.py
  src/python/pants/reporting/reporter.py
  src/python/pants/reporting/reporting.py
  src/python/pants/reporting/zipkin_reporter.py
  src/rust/engine/src/context.rs
  src/rust/engine/src/lib.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/scheduler.rs
  tests/python/pants_test/engine/scheduler_test_base.py
  tests/python/pants_test/reporting/test_reporting_integration.py
  tests/python/pants_test/test_base.py
Labels: needs-cherrypick

#7801 Always use the global interpreter for PythonExecutionTaskBase.
  src/python/pants/backend/python/tasks/pytest_prep.py
  src/python/pants/backend/python/tasks/pytest_run.py
  src/python/pants/backend/python/tasks/python_execution_task_base.py
  src/python/pants/backend/python/tasks/python_repl.py
  src/python/pants/backend/python/tasks/python_run.py
  testprojects/src/python/interpreter_selection/python_3_selection_testing/BUILD
  tests/python/pants_test/backend/python/tasks/test_python_run_integration.py
Labels: needs-cherrypick

#7742 Rsc compile task fixes
  src/python/pants/backend/jvm/targets/scala_library.py
  src/python/pants/backend/jvm/tasks/jvm_compile/jvm_compile.py
  src/python/pants/backend/jvm/tasks/jvm_compile/rsc/rsc_compile.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/rsc/test_rsc_compile.py
Labels: needs-cherrypick

#7809 Rsc native image support
  src/python/pants/backend/jvm/subsystems/BUILD
  src/python/pants/backend/jvm/subsystems/rsc.py
  src/python/pants/backend/jvm/tasks/jvm_compile/rsc/BUILD
  src/python/pants/backend/jvm/tasks/jvm_compile/rsc/rsc_compile.py
  src/python/pants/backend/jvm/tasks/jvm_compile/zinc/zinc_compile.py
Labels: needs-cherrypick

#7781 Force sequential runs under pantsd
  src/python/pants/bin/remote_pants_runner.py
  src/python/pants/option/global_options.py
  src/python/pants/pantsd/pailgun_server.py
  src/python/pants/pantsd/pants_daemon.py
  tests/python/pants_test/pantsd/test_pailgun_server.py
Labels: needs-cherrypick, pantsd
