Repository pantsbuild/pants, pull requests merged in 2019-06, with the labels that each got.

#7829 Avoid redundant work while hackily_snapshot()ing.
  src/python/pants/binaries/binary_tool.py
  tests/python/pants_test/binaries/test_binary_tool.py
Labels: needs-cherrypick

#7825 Fix rsc compile transitive dep bug introduced in #7742
  src/python/pants/backend/jvm/subsystems/resolve_subsystem.py
  src/python/pants/backend/jvm/tasks/jvm_compile/jvm_compile.py
  src/python/pants/backend/jvm/tasks/jvm_compile/rsc/rsc_compile.py
  src/python/pants/util/objects.py
  testprojects/src/scala/org/pantsbuild/testproject/javadepsonscalatransitive/BUILD
  testprojects/src/scala/org/pantsbuild/testproject/javadepsonscalatransitive/Java.java
  testprojects/src/scala/org/pantsbuild/testproject/javadepsonscalatransitive/ScalaInDifferentPackage.scala
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/rsc/test_rsc_compile.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/rsc/test_rsc_compile_integration.py
  tests/python/pants_test/pants_run_integration_test.py
Labels: needs-cherrypick

#7794 Use `--no-enabled-shared` for Linux wheel-builder interpreter so that the released PEX works with statically built interpreters
  .travis.yml
  build-support/docker/centos6/Dockerfile
  build-support/travis/travis.yml.mustache
Labels: needs-cherrypick

#7848 Re-instate PosixFS Threadpool
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/brfs/Cargo.toml
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/fs_util/Cargo.toml
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/src/pool.rs
  src/rust/engine/fs/src/snapshot.rs
  src/rust/engine/fs/src/store.rs
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_executor/Cargo.toml
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/serverset/Cargo.toml
  src/rust/engine/serverset/src/lib.rs
  src/rust/engine/serverset/src/retry.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/lib.rs
  src/rust/engine/src/nodes.rs
Labels: needs-cherrypick

#7853 Locate the classes directory in zinc in order to relativize classnames
  src/scala/org/pantsbuild/zinc/analysis/AnalysisMap.scala
Labels: needs-cherrypick

#7840 add java_sources to scala_library() snapshot
  src/python/pants/backend/jvm/tasks/jvm_compile/zinc/zinc_compile.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/rsc/test_rsc_compile_integration.py
Labels: needs-cherrypick

#7864 Fix `py-thrift-namespace-clash-check` type issue when logging with `--no-strict` mode
  src/python/pants/backend/codegen/thrift/python/py_thrift_namespace_clash_check.py
  src/python/pants/reporting/report.py
Labels: needs-cherrypick

#7854 Bump to latest zinc in order to consume zinc analysis fix
  src/python/pants/backend/jvm/subsystems/zinc.py
  tests/python/pants_test/backend/jvm/tasks/test_jvm_dependency_usage_integration.py
Labels: needs-cherrypick

#7877 Fix Junit runner failing when `--extra-jvm-options` provided
  src/python/pants/backend/jvm/tasks/junit_run.py
Labels: needs-cherrypick

#7878 Fix Nailgun failure when the port is not specified
  src/python/pants/bin/remote_pants_runner.py
  src/python/pants/java/nailgun_client.py
  src/python/pants/java/nailgun_executor.py
Labels: needs-cherrypick

#7890 Update python_repl to use ignoring_sigint to... ignore SIGINT
  src/python/pants/backend/python/tasks/python_repl.py
Labels: pantsd

#7944 Add `--concurrent` flag, which overrides `--enable-pantsd`
  src/python/pants/bin/pants_runner.py
  src/python/pants/option/global_options.py
  tests/python/pants_test/pantsd/test_pantsd_integration.py
Labels: needs-cherrypick, pantsd

#7924 Crash pailgun client on SIGINT if we haven't received the pid yet
  src/python/pants/bin/remote_pants_runner.py
  src/python/pants/java/nailgun_client.py
  src/python/pants/option/global_options.py
  src/python/pants/pantsd/pailgun_server.py
  tests/python/pants_test/pantsd/test_pantsd_integration.py
Labels: needs-cherrypick, pantsd

#7958 Add some of the wording from #7913 that wasn't merged in #7924
  src/python/pants/pantsd/pailgun_server.py
Labels: needs-cherrypick
