Repository pantsbuild/pants, pull requests merged in 2019-07, with the labels that each got.

#8011 relativize path for scalac classpath entry
  src/python/pants/backend/jvm/tasks/jvm_compile/zinc/zinc_compile.py
Labels: needs-cherrypick

#7990 Set up pants.remote.ini for remoting Python unit tests
  pants.remote.ini
Labels: remoting

#7994 Make precomputing fail more usefully
  src/python/pants/bin/daemon_pants_runner.py
  tests/python/pants_test/bin/BUILD
  tests/python/pants_test/bin/test_daemon_pants_runner.py
Labels: needs-cherrypick

#8006 Fix performance regression introduced by #7898
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/brfs/Cargo.toml
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/fs_util/Cargo.toml
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/snapshot.rs
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_executor/Cargo.toml
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/sharded_lmdb/Cargo.toml
  src/rust/engine/sharded_lmdb/src/lib.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/lib.rs
  src/rust/engine/src/scheduler.rs
  src/rust/engine/task_executor/Cargo.toml
  src/rust/engine/task_executor/src/lib.rs
Labels: needs-cherrypick

#8083 Remove unused unit-test.sh script
  build-support/bin/unit-test.sh
  src/docs/howto_develop.md
Labels: documentation

#8047 Deprecate ZincCompile task in favor of RscCompile
  contrib/scalajs/src/python/pants/contrib/scalajs/tasks/scala_js_zinc_compile.py
  pants.ini
  src/docs/options.md
  src/docs/orgs.md
  src/python/pants/backend/jvm/register.py
  src/python/pants/backend/jvm/subsystems/jvm_platform.py
  src/python/pants/backend/jvm/tasks/jvm_compile/jvm_compile.py
  src/python/pants/backend/jvm/tasks/jvm_compile/rsc/rsc_compile.py
  src/python/pants/backend/jvm/tasks/jvm_compile/zinc/zinc_compile.py
  testprojects/src/scala/org/pantsbuild/testproject/javadepsonscalatransitive/BUILD
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/java/jvm_platform_integration_mixin.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/java/test_cache_compile_integration.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/java/test_java_compile_integration.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/java/test_java_compile_settings_partitioning.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/java/test_zinc_compile_integration.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/rsc/test_rsc_compile.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/rsc/test_rsc_compile_integration.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/test_dep_exports_integration.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/zinc/zinc_compile_integration_base.py
  tests/python/pants_test/backend/jvm/tasks/test_jvm_dependency_usage_integration.py
  tests/python/pants_test/backend/python/rules/test_python_test_runner_integration.py
  tests/python/pants_test/bin/test_runner_integration.py
  tests/python/pants_test/cache/test_cache_cleanup_integration.py
  tests/python/pants_test/engine/legacy/test_graph_integration.py
  tests/python/pants_test/java/test_nailgun_integration.py
  tests/python/pants_test/option/test_options_integration.py
  tests/python/pants_test/pantsd/test_pantsd_integration.py
  tests/python/pants_test/reporting/test_reporting_integration.py
  tests/python/pants_test/rules/test_filedeps_integration.py
  tests/python/pants_test/tasks/test_changed_target_integration.py
Labels: needs-cherrypick

#8123 Remove --resolve-jvm-capture-snapshots and --pytest-run-options
  src/python/pants/VERSION
  src/python/pants/backend/jvm/tasks/resolve_shared.py
  src/python/pants/backend/python/tasks/pytest_run.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/rsc/test_rsc_compile_integration.py
  tests/python/pants_test/backend/python/tasks/test_pytest_run.py
Labels: needs-cherrypick

#8126 Remove redundant tests and expand timeouts.
  tests/python/pants_test/backend/jvm/subsystems/BUILD
  tests/python/pants_test/backend/jvm/tasks/BUILD
  tests/python/pants_test/goal/BUILD
  tests/python/pants_test/targets/BUILD
  tests/python/pants_test/targets/test_scala_library_integration.py
  tests/python/pants_test/tasks/BUILD
Labels: needs-cherrypick

#8125 Unrevert #8093 and fix bug.
  src/python/pants/backend/jvm/tasks/analysis_extraction.py
  src/python/pants/backend/jvm/tasks/jvm_dependency_check.py
  src/python/pants/backend/jvm/tasks/jvm_dependency_usage.py
  tests/python/pants_test/backend/jvm/tasks/test_jvm_dependency_usage.py
  tests/python/pants_test/backend/jvm/tasks/test_jvm_dependency_usage_integration.py
Labels: needs-cherrypick
