Repository pantsbuild/pants, pull requests merged in 2019-04, with the labels that each got.

#7469 No longer pin `pants_runtime_python_version` with `./pants generate-pants-ini`
  src/python/pants/core_tasks/generate_pants_ini.py
  tests/python/pants_test/core_tasks/test_generate_pants_ini.py
Labels: needs-cherrypick

#7471 Fix issues with deploy shards not properly setting Python version
  .travis.yml
  build-support/travis/travis.yml.mustache
Labels: needs-cherrypick

#7511 Pass interpreter constraint when building the release PEX
  build-support/bin/release.sh
Labels: needs-cherrypick

#7533 fix TestPantsDaemonIntegration.test_signal_pailgun_stream_timeout flakiness
  tests/python/pants_test/pantsd/test_pantsd_integration.py
Labels: flaky-test

#6880 Add support for v2-only goals, and replace list with a @console_rule
  build-support/bin/release.sh
  pants-plugins/src/python/internal_backend/rules_for_testing/register.py
  pants.ini
  src/python/pants/backend/graph_info/register.py
  src/python/pants/backend/graph_info/tasks/list_targets.py
  src/python/pants/backend/project_info/rules/source_file_validator.py
  src/python/pants/bin/daemon_pants_runner.py
  src/python/pants/bin/goal_runner.py
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/core_tasks/register.py
  src/python/pants/engine/BUILD
  src/python/pants/engine/console.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/legacy/graph.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/scheduler.py
  src/python/pants/help/help_printer.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/init/target_roots_calculator.py
  src/python/pants/option/options.py
  src/python/pants/option/scope.py
  src/python/pants/pantsd/service/scheduler_service.py
  src/python/pants/rules/core/exceptions.py
  src/python/pants/rules/core/filedeps.py
  src/python/pants/rules/core/list_targets.py
  src/python/pants/rules/core/register.py
  src/python/pants/rules/core/test.py
  src/python/pants/task/goal_options_mixin.py
  tests/python/pants_test/BUILD
  tests/python/pants_test/backend/graph_info/tasks/BUILD
  tests/python/pants_test/backend/graph_info/tasks/test_list_targets.py
  tests/python/pants_test/base/test_exception_sink_integration.py
  tests/python/pants_test/console_rule_test_base.py
  tests/python/pants_test/engine/legacy/BUILD
  tests/python/pants_test/engine/legacy/test_build_ignore_integration.py
  tests/python/pants_test/engine/legacy/test_console_rule_integration.py
  tests/python/pants_test/engine/legacy/test_graph_integration.py
  tests/python/pants_test/engine/legacy/test_pants_engine_integration.py
  tests/python/pants_test/engine/test_rules.py
  tests/python/pants_test/pantsd/pantsd_integration_test_base.py
  tests/python/pants_test/rules/BUILD
  tests/python/pants_test/rules/test_filedeps.py
  tests/python/pants_test/rules/test_filedeps_integration.py
  tests/python/pants_test/rules/test_test.py
  tests/python/pants_test/rules/test_test_integration.py
Labels: P3 - M1
