Repository pantsbuild/pants, pull requests merged in 2020-05, with the labels that each got.

#9673 Fix crash when V2 goals like `repl` have no specified targets
  src/python/pants/backend/python/rules/pex.py
  src/python/pants/backend/python/rules/pex_test.py
Labels: needs-cherrypick

#9636 Move file invalidation handling to rust
  pants.toml
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/init/options_initializer.py
  src/python/pants/option/global_options.py
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/pantsd/service/fs_event_service.py
  src/python/pants/pantsd/service/scheduler_service.py
  src/rust/engine/Cargo.lock
  src/rust/engine/engine_cffi/src/lib.rs
  src/rust/engine/graph/Cargo.toml
  src/rust/engine/graph/src/entry.rs
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/graph/src/node.rs
  src/rust/engine/graph/src/tests.rs
  src/rust/engine/logging/src/logger.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/lib.rs
  src/rust/engine/src/scheduler.rs
  src/rust/engine/watch/Cargo.toml
  src/rust/engine/watch/src/lib.rs
  src/rust/engine/watch/src/tests.rs
  tests/python/pants_test/core_tasks/test_deferred_sources_mapper_integration.py
  tests/python/pants_test/core_tasks/test_prep_command_integration.py
  tests/python/pants_test/integration/goal_rule_integration_test.py
  tests/python/pants_test/pantsd/pantsd_integration_test_base.py
  tests/python/pants_test/pantsd/service/test_fs_event_service.py
  tests/python/pants_test/pantsd/test_pantsd_integration.py
Labels: needs-cherrypick

#9752 Deprecate, instead of error, when Python targets have non-Python sources
  src/python/pants/backend/python/target_types.py
Labels: needs-cherrypick

#9754 Move away from the debounced notify watcher
  contrib/go/src/python/pants/contrib/go/tasks/go_buildgen.py
  src/python/pants/engine/internals/mapper_test.py
  src/rust/engine/Cargo.lock
  src/rust/engine/watch/Cargo.toml
  src/rust/engine/watch/src/lib.rs
Labels: needs-cherrypick

#9770 Mention --owners-not-found-behavior option when owners are not found
  src/python/pants/engine/internals/graph.py
Labels: needs-cherrypick

#9773 Refine the workaround that allows pantsd to watch its pid file
  src/python/pants/init/options_initializer.py
Labels: needs-cherrypick

#9774 Standardized workunit names
  src/rust/engine/graph/src/node.rs
  src/rust/engine/graph/src/tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/src/nodes.rs
  tests/python/pants_test/reporting/test_reporting_integration.py
Labels: needs-cherrypick

#9796 Omit `m` suffix for awslambda dependencies in python38 (#9778)
  src/python/pants/backend/awslambda/python/awslambda_python_rules.py
Labels: needs-cherrypick

#8665 Slightly update the documentation about pantsd
  src/docs/architecture_pantsd.md
Labels: stale?

#9813 Fix several typos in source code
  build-support/bin/get_ci_bootstrapped_pants_pex.sh
  build-support/bin/native/calculate_engine_hash.sh
  contrib/go/src/python/pants/contrib/go/subsystems/fetcher.py
  contrib/go/src/python/pants/contrib/go/subsystems/fetcher_factory.py
  contrib/go/src/python/pants/contrib/go/targets/go_target.py
  contrib/node/tests/python/pants_test/contrib/node/tasks/test_node_build.py
  contrib/python/src/python/pants/contrib/python/checks/tasks/python_eval.py
  examples/src/java/org/pantsbuild/example/publish.md
  src/docs/architecture_pantsd.md
  src/docs/export.md
  src/java/org/pantsbuild/tools/junit/impl/AntJunitXmlReportListener.java
  src/java/org/pantsbuild/tools/junit/impl/CompositeRequestRunner.java
  src/python/pants/backend/jvm/subsystems/zinc.py
  src/python/pants/backend/jvm/tasks/jvm_compile/rsc/rsc_compile.py
  src/python/pants/backend/project_info/tasks/idea_plugin_gen.py
  src/python/pants/backend/python/rules/pex_test.py
  src/python/pants/backend/python/rules/util.py
  src/python/pants/backend/python/tasks/pytest_run.py
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/engine_test.py
  src/python/pants/engine/legacy/round_engine_test.py
  src/python/pants/engine/rules_test.py
  src/python/pants/goal/run_tracker.py
  src/python/pants/notes/1.24.x.rst
  src/python/pants/notes/1.28.x.rst
  src/python/pants/option/config.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/python/pex_build_util.py
  src/python/pants/task/testrunner_task_mixin.py
  src/python/pants/testutil/base/context_utils.py
  src/rust/engine/fs/store/src/local_tests.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/process_execution/src/nailgun/tests.rs
  src/rust/engine/testutil/src/data.rs
  tests/java/org/pantsbuild/tools/junit/impl/UtilTest.java
  tests/python/pants_test/backend/jvm/targets/test_jvm_app.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/test_jvm_compile.py
  tests/python/pants_test/backend/jvm/tasks/jvm_compile/zinc/test_zinc_compile.py
  tests/python/pants_test/backend/jvm/tasks/test_checkstyle_integration.py
  tests/python/pants_test/backend/jvm/tasks/test_classpath_products.py
  tests/python/pants_test/backend/jvm/tasks/test_ivy_utils.py
  tests/python/pants_test/backend/project_info/tasks/test_export_dep_as_jar_integration.py
Labels: release:documentation

#9820 Remove unused variants experiment
  src/python/pants/build_graph/address.py
  src/python/pants/engine/internals/addressable.py
Labels: release:refactoring

#9832 Remove GitHub action failing due to improper permission setup
  .github/workflows/pr-labels.yaml
Labels: release:testing

#9828 Fix harmless error rendered when stdin is closed under pantsd
  src/python/pants/java/nailgun_io.py
  tests/python/pants_test/java/test_nailgun_io.py
Labels: needs-cherrypick

#9819 Remove several uses of soon-to-be-deprecated `BuildFile`
  src/python/pants/base/build_file.py
  src/python/pants/build_graph/address.py
  src/python/pants/engine/legacy/address_mapper.py
  src/python/pants/reporting/BUILD
  src/python/pants/reporting/linkify.py
  src/python/pants/testutil/pants_run_integration_test.py
Labels: release:refactoring

#9812 Fix console UI redraw issues
  src/python/pants/engine/console.py
  src/python/pants/engine/internals/native.py
  src/python/pants/engine/internals/scheduler.py
  src/rust/engine/engine_cffi/src/lib.rs
  src/rust/engine/src/scheduler.rs
  src/rust/engine/ui/src/console_ui.rs
Labels: needs-cherrypick, release:bugfixes

#9841 Make the `Dependencies` field an AsyncField
  src/python/pants/backend/project_info/dependees.py
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/python/lint/pylint/plugin_target_type.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/rules/run_setup_py.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: release:refactoring

#9830 Upgrade to Pex 2.1.11.
  3rdparty/python/requirements.txt
  src/python/pants/backend/python/rules/download_pex_bin.py
Labels: release:api-changes

#9856 Add sugar to getting values from `UnionMembership`
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/repl.py
  src/python/pants/core/goals/test.py
  src/python/pants/engine/target.py
  src/python/pants/engine/unions.py
Labels: release:refactoring

#9839 Move contribution guide to new doc site
  COMMITTERS.md
  CONTRIBUTING.md
  src/docs/committers.md
  src/docs/community.md
  src/docs/deprecation_policy.md
  src/docs/dev.md
  src/docs/howto_contribute.md
  src/docs/howto_develop.md
  src/docs/release_strategy.md
  src/docs/styleguide.md
  src/rust/engine/README.md
Labels: release:documentation

#9857 Add generic mechanism for dependency inference
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: release:refactoring

#9862 Move release pre-req checks to Python
  build-support/bin/release.sh
  src/python/pants/releases/packages.py
Labels: release:refactoring

#9870 Support V2 linters running on Python 2 and Python 3 targets at the same time
  src/python/pants/backend/python/lint/bandit/rules.py
  src/python/pants/backend/python/lint/bandit/rules_integration_test.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/docformatter/rules_integration_test.py
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/isort/rules_integration_test.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/rules/pex.py
  src/python/pants/backend/python/rules/pex_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: release:features

#9871 Decouple wheel building jobs from CI's `pants.pex`
  .travis.yml
  build-support/bin/BUILD
  build-support/bin/check_header.py
  build-support/bin/check_pants_pex_abi.py
  build-support/bin/generate_travis_yml.py
  build-support/bin/get_ci_bootstrapped_pants_pex.sh
  build-support/githooks/prepare-commit-msg
Labels: release:refactoring

#9908 Fix ABI string when building pants.pex
  build-support/bin/release.sh
Labels: needs-cherrypick

#9923 Improve pantsd waiting message
  src/python/pants/pantsd/process_manager.py
  tests/python/pants_test/pantsd/pantsd_integration_test_base.py
  tests/python/pants_test/pantsd/test_process_manager.py
Labels: needs-cherrypick

#9920 Graph::get backs off on filesystem invalidation
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/graph/src/tests.rs
  src/rust/engine/src/nodes.rs
Labels: needs-cherrypick
