Repository pantsbuild/pants, pull requests merged in 2020-07, with the labels that each got.

#10319 Hotfix Bandit breaking from stevedore 3.0 release
  src/python/pants/backend/python/lint/bandit/subsystem.py
Labels: needs-cherrypick

#10337 Fix tests that relied on the docsite CNAME file.
  src/python/pants/engine/fs_test.py
Labels: needs-cherrypick

#10395 close write stream for CAS writes via ByteStream API
  src/rust/engine/fs/store/src/remote.rs
Labels: bug, remoting

#10451 Fix `--print-exception-stacktrace` not invalidating pantsd
  src/python/pants/option/global_options.py
Labels: needs-cherrypick

#10453 Fix Protobuf when using source roots
  src/python/pants/backend/codegen/protobuf/python/rules.py
  src/python/pants/backend/codegen/protobuf/python/rules_integration_test.py
  src/python/pants/backend/python/rules/python_sources.py
  src/python/pants/backend/python/rules/python_sources_test.py
Labels: needs-cherrypick, release:bugfixes

#10509 Fix bug that caused setup-py to hang if src root==buildroot.
  src/python/pants/backend/python/rules/run_setup_py.py
  src/python/pants/backend/python/rules/run_setup_py_test.py
  src/python/pants/source/source_root.py
Labels: needs-cherrypick
