Repository pantsbuild/pants, pull requests merged in 2020-10, with the labels that each got.

#10906 print stacktraces during import errors
  src/python/pants/base/exception_sink.py
Labels: bug, error handling

#10907 use libCST to parse imports from python 3 code
  3rdparty/python/constraints.txt
  3rdparty/python/requirements.txt
  src/python/pants/backend/python/dependency_inference/import_parser.py
  src/python/pants/backend/python/dependency_inference/import_parser_test.py
Labels: release:features

#10947 Use `package` to build Pants's wheels, rather than `setup-py`
  build-support/bin/packages.py
  src/python/pants/BUILD
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/testutil/BUILD
Labels: needs-cherrypick

#10950 Fix config validation not erroring on global options in wrong scope
  src/python/pants/option/options.py
Labels: needs-cherrypick
