Repository pantsbuild/pants, pull requests merged in 2021-07, with the labels that each got.

#12283 Add JavacSubsystem and JavacBinary, allowing user-configurable JVM selection
  src/python/pants/backend/java/compile/javac.py
  src/python/pants/backend/java/compile/javac_binary.py
  src/python/pants/backend/java/compile/javac_binary_test.py
  src/python/pants/backend/java/compile/javac_subsystem.py
  src/python/pants/backend/java/compile/javac_test.py
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: lang-java, lang-jvm

#12279 Refactor BUILD file parsing.
  src/python/pants/base/parse_context.py
  src/python/pants/engine/internals/parser.py
Labels: needs-cherrypick

#12280 Fix poetry_requirements: ignore internal projects.
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
  src/python/pants/base/parse_context.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
  src/python/pants/init/engine_initializer.py
Labels: needs-cherrypick

#12340 Fix anonymous telemetry logging.
  src/python/pants/goal/anonymous_telemetry.py
  src/python/pants/goal/anonymous_telemetry_integration_test.py
Labels: needs-cherrypick

#12368 use `go list` to analyze stdlib imports
  3rdparty/python/lockfile.txt
  3rdparty/python/requirements.txt
  src/python/pants/backend/experimental/go/register.py
  src/python/pants/backend/go/build.py
  src/python/pants/backend/go/build_integration_test.py
  src/python/pants/backend/go/import_analysis.py
  src/python/pants/backend/go/import_analysis_integration_test.py
Labels: lang-go

#12369 Mark workunits blocked, and skip rendering completed workunits
  src/python/pants/engine/internals/engine_test.py
  src/rust/engine/async_semaphore/src/lib.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/session.rs
  src/rust/engine/workunit_store/src/lib.rs
  src/rust/engine/workunit_store/src/tests.rs
Labels: needs-cherrypick

#12323 More robust support for Poetry dependency attributes (`markers`, and`extras`)
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
Labels: needs-cherrypick

#12391 Fix the content type for Pants' wheel long_descriptions.
  pants-plugins/internal_plugins/releases/register.py
Labels: needs-cherrypick

#12392 Add option for async completion of StreamingWorkunitHandlers, disable by default in containers
  src/python/pants/base/build_environment.py
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/engine/internals/engine_test.py
  src/python/pants/engine/streaming_workunit_handler.py
  src/python/pants/option/global_options.py
Labels: needs-cherrypick

#12396 Skip preparation of workunit log messages which will never be rendered.
  src/rust/engine/workunit_store/src/lib.rs
Labels: needs-cherrypick

#12435 Clarify when we are subsetting the lockfile for 3rdparty dependencies
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: needs-cherrypick

#12443 Do not upload Action inputs for remote cache writes.
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: needs-cherrypick

#12469 Add cache and runtime metadata to Process workunits
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/named_caches.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/tests.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/workunit_store/src/lib.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: needs-cherrypick

#12471 add counters for blob bytes uploaded/downloaded to/from CAS
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: needs-cherrypick
