Repository pantsbuild/pants, pull requests merged in 2021-09, with the labels that each got.

#12177 Add proof-of-concept Java junit test rule
  src/python/pants/backend/java/test/BUILD
  src/python/pants/backend/java/test/__init__.py
  src/python/pants/backend/java/test/junit.py
  src/python/pants/backend/java/test/junit_test.py
Labels: lang-java, lang-jvm

#12736 Improve descriptions of the process executions for PEX_PATH composition.
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: needs-cherrypick

#12738 Error, don't warn, when `--generate-lockfiles-resolve` is set to a disabled tool lockfile
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
Labels: needs-cherrypick

#12769 [internal] bump timeout for docker tests to 120s (cherrypick of #12747)
  src/python/pants/backend/docker/BUILD
Labels: needs-cherrypick

#12758 docker: include file dependencies in docker build context properly.
  src/python/pants/backend/docker/docker_binary.py
  src/python/pants/backend/docker/docker_binary_test.py
  src/python/pants/backend/docker/docker_build.py
  src/python/pants/backend/docker/docker_build_context.py
  src/python/pants/backend/docker/docker_build_context_test.py
  src/python/pants/backend/docker/docker_build_test.py
  src/python/pants/backend/docker/target_types.py
Labels: needs-cherrypick

#12791 [internal] Test that default IPython lockfile works for all Python interpreters and macOS
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/goals/repl_integration_test.py
  src/python/pants/core/goals/repl_test.py
Labels: needs-cherrypick

#12823 Properly include file dependencies in docker build context (cherrypick of #12758)
  src/python/pants/backend/docker/docker_binary.py
  src/python/pants/backend/docker/docker_binary_test.py
  src/python/pants/backend/docker/docker_build.py
  src/python/pants/backend/docker/docker_build_context.py
  src/python/pants/backend/docker/docker_build_context_test.py
  src/python/pants/backend/docker/docker_build_test.py
  src/python/pants/backend/docker/target_types.py
Labels: needs-cherrypick

#12808 Upgrade to Pex 2.1.48 and leverage packed layout.
  3rdparty/python/lockfiles/pytest.txt
  3rdparty/python/lockfiles/user_reqs.txt
  3rdparty/python/requirements.txt
  build-support/bin/_release_helper.py
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/goals/run_pex_binary.py
  src/python/pants/backend/python/goals/run_pex_binary_integration_test.py
  src/python/pants/backend/python/lint/bandit/lockfile.txt
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/subsystems/ipython_lockfile.txt
  src/python/pants/backend/python/subsystems/lambdex_lockfile.txt
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/bin/BUILD
  src/python/pants/init/plugin_resolver.py
  tests/python/pants_test/init/test_plugin_resolver.py
Labels: needs-cherrypick

#12807 Improve cache reuse for `./pants package` when using a constraints file or lockfile
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: needs-cherrypick

#12842 Issue/10944 pep561 py typed 2
  src/python/pants/BUILD
  src/python/pants/py.typed
  src/python/pants/testutil/BUILD
  src/python/pants/testutil/py.typed
  tests/python/pants_test/integration/BUILD
  tests/python/pants_test/integration/pep_561_integration_test.py
Labels: needs-cherrypick

#12899 [internal] Fix MyPy Protobuf test failing due to missing dependency
  src/python/pants/backend/awslambda/python/BUILD
  src/python/pants/backend/codegen/protobuf/python/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/BUILD
Labels: needs-cherrypick

#12961 [internal] Fix pep561_integration_test.py to be resilient to new Pants releases
  tests/python/pants_test/integration/BUILD
  tests/python/pants_test/integration/pep561_integration_test.py
  tests/python/pants_test/integration/pep_561_integration_test.py
Labels: needs-cherrypick

#12964 Add PackageRootedDependencyMap for mapping inferred Java dependencies
  src/python/pants/backend/java/dependency_inference/BUILD
  src/python/pants/backend/java/dependency_inference/package_prefix_tree.py
  src/python/pants/backend/java/dependency_inference/package_prefix_tree_test.py
Labels: lang-jvm

#12890 Add Java dependency analysis types and launcher using javaparser library.
  src/python/pants/backend/java/dependency_inference/BUILD
  src/python/pants/backend/java/dependency_inference/PantsJavaParserLauncher.java
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/backend/java/dependency_inference/java_parser_launcher.py
  src/python/pants/backend/java/dependency_inference/java_parser_test.py
  src/python/pants/backend/java/dependency_inference/types.py
Labels: lang-jvm

#12981 Fix case sensitivity of `module_mapping` for `python_requirements` and `poetry_requirements` (Cherry-pick of #12980)
  src/python/pants/backend/python/dependency_inference/module_mapper.py
  src/python/pants/backend/python/macros/pipenv_requirements.py
  src/python/pants/backend/python/macros/pipenv_requirements_test.py
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/macros/python_requirements_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
Labels: needs-cherrypick

#12978 Implement Java dep inference mapper and rules
  src/python/pants/backend/java/dependency_inference/import_parser.py
  src/python/pants/backend/java/dependency_inference/import_parser_test.py
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/backend/java/dependency_inference/package_mapper.py
  src/python/pants/backend/java/dependency_inference/rules.py
  src/python/pants/backend/java/dependency_inference/rules_test.py
  src/python/pants/backend/java/target_types.py
Labels: lang-jvm

#13008 Ensure that Tree contents are uploaded after creation.
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
Labels: needs-cherrypick

#13028 Don't invalidate the scheduler when piping output
  src/python/pants/option/global_options.py
  src/python/pants/testutil/rule_runner.py
Labels: needs-cherrypick
