Repository pantsbuild/pants, pull requests merged in 2022-04, with the labels that each got.

#14916 Prepare 2.11.0rc1
  src/python/pants/notes/2.11.x.md
Labels: category:internal

#14979 add go protobuf backend to init/BUILD
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/init/BUILD
Labels: needs-cherrypick, lang-go, category:internal

#14978 [internal] Upgrade coursier
  src/python/pants/backend/java/dependency_inference/java_parser.lockfile
  src/python/pants/backend/scala/dependency_inference/scala_parser.lockfile
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: category:user api change

#14984 [internal] Pass `prior_formatter_result` in `lint`to `FmtRequest`
  src/python/pants/backend/terraform/style.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/style_request.py
Labels: category:internal

#14989 [internal] softwrap pants.jvm
  src/python/pants/jvm/resolve/coursier_setup.py
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/jvm/subsystems.py
  src/python/pants/jvm/target_types.py
Labels: category:internal

#14992 Upgrade Pex to 2.1.76.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#14943 [internal] BSP: use seperate config file for defining groups for BSP build targets
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/bsp/goal.py
  src/python/pants/bsp/util_rules/BUILD
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/bsp/util_rules/targets_test.py
Labels: lang-jvm, category:internal

#14993 Upgrade Pex to 2.1.76. (Cherry-pick of #14992)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#14987 Refactor `prior_formatter_result` and its usage
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules_integration_test.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/gofmt/rules_integration_test.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules_integration_test.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/autoflake/rules_integration_test.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/docformatter/rules_integration_test.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/isort/rules_integration_test.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules_integration_test.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/python/lint/yapf/rules_integration_test.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules_integration_test.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt_integration_test.py
  src/python/pants/backend/terraform/style.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
Labels: category:plugin api change

#14904 Don't WARN when a spec matches no relevant targets.
  src/python/pants/base/specs.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/init/specs_calculator.py
Labels: category:documentation

#15001 [internal] Add Helm chart name to lint partition description
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/goals/lint_test.py
Labels: category:internal

#14985 Support restricting specific dists to just wheels or just sdists.
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:new feature

#14997 Pin pytest 7.0.1
  3rdparty/python/pytest.lock
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/pytest.lock
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/setup.py
Labels: needs-cherrypick, category:bugfix

#15009 Change JVM defaults to use Temurin JDK distribution
  src/python/pants/jvm/subsystems.py
Labels: category:user api change

#14999 Fix presented provider backend for rules/subsystems.
  src/python/pants/help/help_info_extracter.py
Labels: category:documentation

#15015 Upgrade to Pex 2.1.77.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#15016 Upgrade to Pex 2.1.77. (Cherry-pick of #15015)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15029 Upgrade Pex to 2.1.73. (Cherry-pick of #14875)
  3rdparty/python/lockfiles/user_reqs.txt
  3rdparty/python/requirements.txt
  src/python/pants/backend/python/subsystems/lambdex_lockfile.txt
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15028 Upgrade Pex to 2.1.73. (Cherry-pick of #14875)
  3rdparty/python/lockfiles/user_reqs.txt
  3rdparty/python/requirements.txt
  src/python/pants/backend/python/subsystems/lambdex_lockfile.txt
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15014 Fix default layout and use of PEX-repositories for legacy lockfiles
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/util_rules/dists.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/backend/python/util_rules/pex_test_utils.py
Labels: needs-cherrypick, category:bugfix

#15031 Do not use a repository-PEX if a PEX has platforms specified
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
Labels: needs-cherrypick, category:bugfix

#15032 Fix default layout and use of PEX-repositories for legacy lockfiles (cherrypick of #15014)
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/util_rules/dists.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/backend/python/util_rules/pex_test_utils.py
Labels: category:bugfix

#15044 [internal] Another softwrap wave
  src/python/pants/core/goals/package.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/util_rules/external_tool.py
  src/python/pants/core/util_rules/subprocess_environment.py
  src/python/pants/engine/target.py
  src/python/pants/goal/anonymous_telemetry.py
  src/python/pants/goal/stats_aggregator.py
  src/python/pants/option/alias.py
  src/python/pants/vcs/changed.py
Labels: category:internal

#15046 Text in angle brackets needs to be escaped for the docsite.
  src/python/pants/backend/codegen/thrift/apache/subsystem.py
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/backend/shell/shell_setup.py
Labels: category:documentation

#15034 Do not use a repository-PEX if a PEX has platforms specified (cherrypick of #15031)
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
Labels: category:bugfix

#15039 [internal] terraform: delete unused lock file
  src/python/pants/backend/terraform/hcl2_lockfile.txt
Labels: category:internal

#15033 Do not use a repository-PEX if a PEX has platforms specified (cherrypick of #15031)
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: category:bugfix

#15041 [internal] add helper for finding jvm_artifact targets for dep inference
  src/python/pants/backend/codegen/protobuf/scala/dependency_inference.py
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/jvm/dependency_inference/artifact_mapper.py
Labels: category:internal

#14994 [internal] error in CI if tests skipped
  BUILD
  conftest.py
  pants.ci.toml
  pants.toml
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/shell/shunit2_test_runner_integration_test.py
  src/python/pants/core/goals/publish_test.py
  src/python/pants/core/goals/run_integration_test.py
  src/python/pants/engine/rules_test.py
  src/python/pants/jvm/jdk_rules_test.py
  src/python/pants/jvm/test/junit_test.py
  src/python/pants/testutil/pants_integration_test.py
  src/python/pants/vcs/changed_integration_test.py
  tests/python/pants_test/integration/goal_rule_integration_test.py
  tests/python/pants_test/integration/graph_integration_test.py
  tests/python/pants_test/pantsd/pantsd_integration_test.py
  tests/python/pants_test/pantsd/test_process_manager.py
Labels: category:internal

#15036 Add some codegen and terraform backends to docs generator
  build-support/bin/generate_docs.py
Labels: category:documentation

#15048 Add a helpful hint to `lint` if a formatter fails
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: category:new feature

#15035 terraform: remove `terraform_modules` generator target type
  src/python/pants/backend/experimental/terraform/register.py
  src/python/pants/backend/terraform/goals/tailor.py
  src/python/pants/backend/terraform/goals/tailor_test.py
  src/python/pants/backend/terraform/tailor.py
  src/python/pants/backend/terraform/tailor_test.py
  src/python/pants/backend/terraform/target_gen.py
  src/python/pants/backend/terraform/target_gen_test.py
  src/python/pants/backend/terraform/target_types.py
Labels: needs-cherrypick, category:user api change

#15045 Refactor peek `TargetData.to_json()` method for re-usability.
  src/python/pants/backend/project_info/peek.py
Labels: category:internal

#15052 Prepare the 2.9.2rc0 release.
  src/python/pants/notes/2.9.x.md
Labels: category:internal

#15053 Prepare the 2.10.1rc0 release.
  src/python/pants/notes/2.10.x.md
Labels: category:internal

#15056 Text in angle brackets needs to be escaped for the docsite. (Cherry pick of #15046)
  src/python/pants/backend/codegen/thrift/apache/subsystem.py
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/backend/shell/shell_setup.py
Labels: category:documentation

#15027 Tweak deprecation messages.
  src/python/pants/base/deprecated.py
  src/python/pants/base/deprecated_test.py
  src/python/pants/option/options_integration_test.py
  src/python/pants/option/options_test.py
  src/python/pants/option/subsystem_test.py
Labels: category:documentation

#14988 [internal] Skip go tests if go is not present
  src/python/pants/backend/go/BUILD
  src/python/pants/backend/go/conftest.py
Labels: category:internal

#14986 [internal] Add test skipping to all_major_minor_python_versions
  src/python/pants/testutil/python_interpreter_selection.py
Labels: category:internal

#15064 Filter BSP targets using the configured `group` `resolve`.
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/bsp/util_rules/compile.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/bsp/util_rules/targets_test.py
Labels: category:internal

#15000 Support for finer control over which Docker images to push.
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/goals/publish.py
  src/python/pants/backend/docker/goals/publish_test.py
  src/python/pants/backend/docker/registries.py
  src/python/pants/backend/docker/registries_test.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_binary_test.py
Labels: category:new feature

#15025 Add `@rule_helper` decorator, which participates in awaitable collection
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/internals/rule_visitor_test.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/rules_test.py
Labels: category:plugin api change

#15038 [internal] use DEBUG level for parsing Terraform sources
  src/python/pants/backend/terraform/dependency_inference.py
Labels: category:internal

#15068 Clean the export dir under dist/ before populating it.
  src/python/pants/core/goals/export.py
Labels: needs-cherrypick, category:bugfix

#15072 rule_helpers dont need to be static
  src/python/pants/engine/rules.py
Labels: category:internal

#15076 [internal] Upgrade toolchain pants plugin
  pants.toml
Labels: category:internal

#15075 Clean the export dir under dist/ before populating it. (cherrypick #15068)
  src/python/pants/core/goals/export.py
Labels: category:bugfix

#15078 Upgrade Pex to 2.1.78.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#15067 [internal] BSP: set base directory from definition if provided in config
  src/python/pants/bsp/util_rules/targets.py
Labels: category:internal, bsp

#15079 Upgrade Pex to 2.1.78. (Cherry-pick of #15078)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15081 Prepare the 2.11.0rc2 release.
  src/python/pants/notes/2.11.x.md
Labels: category:internal

#15074 Default `[python].lockfile_generator` to Pex
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:user api change

#15089 Upgrade Rust to 1.60.0.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
Labels: category:internal

#15071 Propagate the interpreter constraints to the python distribution Requires-Python metadata.
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/goals/setup_py_test.py
  src/python/pants/testutil/BUILD
Labels: category:new feature

#15086 Clean PID-specific exception file if empty on process exit
  src/python/pants/base/exception_sink.py
Labels: category:bugfix

#15090 Remove deprecated `register_options` support.
  src/python/pants/option/subsystem.py
  src/python/pants/option/subsystem_test.py
Labels: category:plugin api change

#15087 Support for env var interpolation in config files.
  src/python/pants/option/config.py
  src/python/pants/option/config_test.py
  src/python/pants/option/options_bootstrapper.py
Labels: category:new feature

#15088 Preserve tombstones for workunits which complete while they still have children
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/src/externs/engine_aware.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/workunit_store/src/lib.rs
  src/rust/engine/workunit_store/src/tests.rs
Labels: needs-cherrypick, category:bugfix

#15100 Enable codegen on relocated files
  src/python/pants/core/target_types.py
  src/python/pants/core/target_types_test.py
Labels: needs-cherrypick, category:bugfix

#15040 [internal] search resolve for libthrift artifact
  src/python/pants/backend/codegen/thrift/apache/java/rules.py
  src/python/pants/backend/codegen/thrift/apache/java/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/apache/java/subsystem.py
Labels: category:internal

#15091 Remove deprecated target generator API affordances.
  src/python/pants/backend/project_info/peek_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/target.py
Labels: category:plugin api change

#15101 files/dirs swapped in Snapshot's repr
  src/rust/engine/src/externs/fs.rs
Labels: needs-cherrypick, category:documentation

#15083 [internal] add ktlint formatter for Kotlin
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/experimental/kotlin/BUILD
  src/python/pants/backend/experimental/kotlin/__init__.py
  src/python/pants/backend/experimental/kotlin/lint/ktlint/BUILD
  src/python/pants/backend/experimental/kotlin/lint/ktlint/__init__.py
  src/python/pants/backend/experimental/kotlin/lint/ktlint/register.py
  src/python/pants/backend/experimental/kotlin/register.py
  src/python/pants/backend/kotlin/lint/ktlint/BUILD
  src/python/pants/backend/kotlin/lint/ktlint/__init__.py
  src/python/pants/backend/kotlin/lint/ktlint/ktlint.lock
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules_integration_test.py
  src/python/pants/backend/kotlin/lint/ktlint/skip_field.py
  src/python/pants/backend/kotlin/lint/ktlint/subsystem.py
Labels: category:internal

#15099 Prepare the 2.12.0.dev2 release.
  build-support/bin/changelog.py
  src/python/pants/VERSION
  src/python/pants/backend/scala/subsystems/scalac.py
  src/python/pants/notes/2.12.x.md
Labels: category:internal

#15097 Support pip-style VCS requirements.
  src/python/pants/backend/python/macros/python_requirements_test.py
  src/python/pants/backend/python/pip_requirement.py
  src/python/pants/backend/python/pip_requirement_test.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
Labels: category:new feature

#15104 [internal] cleanup linters to remove separate "setup" rules
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/java/lint/google_java_format/skip_field.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
Labels: category:internal

#15105 fix missing field check in go protobuf rules
  src/python/pants/backend/codegen/protobuf/go/rules.py
Labels: needs-cherrypick, category:bugfix

#15119 Add missing ")" to docstring
  src/python/pants/engine/target.py
Labels: category:internal

#15112 Clean PID-specific exception file if empty on process exit (Cherry pick of #15086)
  src/python/pants/base/exception_sink.py
Labels: category:bugfix

#15106 Ban `terraform_module` referring to subdirectories
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/terraform/target_types.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: needs-cherrypick, category:user api change

#15122 Ban `terraform_module` referring to subdirectories (Cherry-pick of #15106)
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/terraform/target_types.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:user api change

#15113 Clean PID-specific exception file if empty on process exit (Cherry pick of #15086)
  src/python/pants/base/exception_sink.py
Labels: category:bugfix

#15030 Expose Git as a @rule
  pants.toml
  src/python/pants/base/build_environment.py
  src/python/pants/core/register.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/vcs/changed.py
  src/python/pants/vcs/changed_integration_test.py
  src/python/pants/vcs/git.py
  src/python/pants/vcs/git_test.py
Labels: category:plugin api change

#15109 add experimental kotlin backend to distribution
  src/python/pants/backend/experimental/java/register.py
  src/python/pants/backend/experimental/kotlin/register.py
  src/python/pants/init/BUILD
Labels: category:new feature

#15077 [internal] kotlin: add kotlin parser for eventual dependency inference
  src/python/pants/backend/experimental/kotlin/register.py
  src/python/pants/backend/kotlin/dependency_inference/BUILD
  src/python/pants/backend/kotlin/dependency_inference/KotlinParser.kt
  src/python/pants/backend/kotlin/dependency_inference/__init__.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser_test.py
  src/python/pants/backend/kotlin/dependency_inference/rules.py
Labels: category:internal

#15121 Fix when the same `python_requirement` defines both type stub and implementation
  src/python/pants/backend/python/dependency_inference/module_mapper.py
  src/python/pants/backend/python/dependency_inference/module_mapper_test.py
Labels: needs-cherrypick, category:bugfix

#15125 Upgrade Pex to 2.1.79.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#15123 Allow dashes in inferred asset strings
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
  src/python/pants/backend/python/dependency_inference/scripts/dependency_parser.py
Labels: needs-cherrypick, category:bugfix

#15129 Upgrade Pex to 2.1.79. (Cherry-pick of #15125)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15132 [internal] remove non-existent backend name in docs generator
  build-support/bin/generate_docs.py
Labels: category:internal

#15137 softwrap python backend help strings
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/publish.py
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/macros/common_fields.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/mixed_interpreter_constraints/py_constraints.py
  src/python/pants/backend/python/packaging/pyoxidizer/subsystem.py
  src/python/pants/backend/python/packaging/pyoxidizer/target_types.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/repos.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/twine.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: category:documentation

#15138 Softwrapping a few more files
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/backend/scala/subsystems/scala.py
  src/python/pants/backend/scala/subsystems/scala_infer.py
  src/python/pants/backend/scala/subsystems/scalac.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/backend/shell/lint/shellcheck/subsystem.py
  src/python/pants/backend/shell/lint/shfmt/subsystem.py
  src/python/pants/backend/shell/shell_setup.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/terraform/target_types.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/target_types.py
  src/python/pants/option/global_options.py
Labels: category:documentation

#15042 Implement `publish` goal for Helm charts
  src/python/pants/backend/experimental/helm/register.py
  src/python/pants/backend/helm/goals/package.py
  src/python/pants/backend/helm/goals/package_test.py
  src/python/pants/backend/helm/goals/publish.py
  src/python/pants/backend/helm/goals/publish_test.py
  src/python/pants/backend/helm/resolve/remotes.py
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/helm/target_types.py
Labels: category:new feature

#15126 Address specs for parametrized target templates expand to their created targets
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
Labels: needs-cherrypick, category:new feature

#15149 Fix Requires-Python for pantsbuild.pants wheel.
  pants.toml
  src/python/pants/BUILD
  src/python/pants/testutil/BUILD
Labels: category:bugfix

#15133 [internal] kotlin: parse named declarations and infer deps based on imports
  src/python/pants/backend/kotlin/dependency_inference/KotlinParser.kt
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser_test.py
  src/python/pants/backend/kotlin/dependency_inference/rules.py
  src/python/pants/backend/kotlin/dependency_inference/rules_test.py
  src/python/pants/backend/kotlin/dependency_inference/symbol_mapper.py
  src/python/pants/backend/kotlin/subsystems/kotlin_infer.py
Labels: category:internal

#15073 Throw a `DuplicateRuleError` when there are conflicting rules in a module.
  src/python/pants/engine/internals/engine_test.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/rules_test.py
  src/python/pants/help/help_info_extracter_test.py
Labels: category:new feature

#15150 Rename .ignored_revisions to .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: category:internal

#15142 Last round of softwrapping help strings
  src/python/pants/backend/codegen/protobuf/protoc.py
  src/python/pants/backend/codegen/thrift/subsystem.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/java/lint/google_java_format/subsystem.py
  src/python/pants/backend/java/subsystems/java_infer.py
  src/python/pants/backend/kotlin/subsystems/kotlin.py
  src/python/pants/backend/plugin_development/pants_requirements.py
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/filedeps.py
  src/python/pants/backend/project_info/filter_targets.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/bsp/goal.py
  src/python/pants/jvm/target_types.py
  src/python/pants/option/option_types.py
Labels: category:documentation

#15117 Add cherry-pick script
  build-support/bin/cherry_pick.sh
Labels: category:internal

#15160 Remove deprecated global scalac plugins.
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/scala/compile/scalac.py
  src/python/pants/backend/scala/compile/scalac_plugins.py
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/subsystems/scalac.py
Labels: category:internal

#15162 Prepare `2.11.0rc3`.
  src/python/pants/notes/2.11.x.md
Labels: category:internal

#15161 Prepare `2.12.0.dev3`.
  src/python/pants/VERSION
  src/python/pants/notes/2.12.x.md
Labels: category:internal

#15159 Cherry-pick script improvements
  build-support/bin/cherry_pick.sh
Labels: category:internal

#15163 [internal] kotlin: add dependency inference based on consumed symbols
  src/python/pants/backend/kotlin/dependency_inference/KotlinParser.kt
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser_test.py
  src/python/pants/backend/kotlin/dependency_inference/rules.py
  src/python/pants/backend/kotlin/dependency_inference/rules_test.py
  src/python/pants/backend/kotlin/subsystems/kotlin_infer.py
Labels: category:internal

#15164 [internal] kotlin: infer dependencies on Kotlin runtime jars
  src/python/pants/backend/kotlin/dependency_inference/rules.py
  src/python/pants/backend/kotlin/target_types.py
Labels: category:internal

#15170 [internal] kotlin: add goal to dump source analysis
  src/python/pants/backend/experimental/kotlin/debug_goals/BUILD
  src/python/pants/backend/experimental/kotlin/debug_goals/__init__.py
  src/python/pants/backend/experimental/kotlin/debug_goals/register.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/kotlin/goals/debug_goals.py
  src/python/pants/init/BUILD
Labels: category:internal

#15169 [internal] jvm: move prefixed `resolve` and `jdk` fields to jvm package
  src/python/pants/backend/codegen/avro/java/rules.py
  src/python/pants/backend/codegen/protobuf/java/rules.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/codegen/soap/java/rules.py
  src/python/pants/backend/codegen/thrift/apache/java/rules.py
  src/python/pants/backend/codegen/thrift/apache/java/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/scrooge/java/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/rules.py
  src/python/pants/jvm/target_types.py
Labels: needs-cherrypick, category:internal

#15173 Work around Git CVE-2022-24765 related failures.
  .github/workflows/audit.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#15174 Work around Git CVE-2022-24765 related failures. (Cherry-pick of #15173)
  .github/workflows/audit.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15175 Work around Git CVE-2022-24765 related failures. (Cherry-pick of #15173)
  .github/workflows/audit.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15176 Work around Git CVE-2022-24765 related failures. (Cherry-pick of #15173)
  .github/workflows/audit.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15177 Work around Git CVE-2022-24765 related failures. (Cherry-pick of #14670 & #15173)
  .github/workflows/audit.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15178 Kill now-unused global scalac plugins lock file.
  3rdparty/jvm/global_scalac_plugins.lock
Labels: category:internal

#15179 Upgrade Pex to 2.1.80.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#15172 Mention resolve when partitioning Mypy and Pylint
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
Labels: needs-cherrypick, category:documentation

#15180 Upgrade Pex to 2.1.80. (Cherry-pick of #15179)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15183 Add a workflow for comparing remote cache performance across builds
  .github/workflows/cache_comparison.yaml
  build-support/bin/BUILD
  build-support/bin/cache_comparison.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15185 Cache comparison job fixes: round 1
  .github/workflows/cache_comparison.yaml
  build-support/bin/cache_comparison.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15098 Write virtualenvs for python tools as part of `export`
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/backend/python/lint/autoflake/subsystem.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/docformatter/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/isort/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pyupgrade/subsystem.py
  src/python/pants/backend/python/lint/yapf/subsystem.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: category:new feature

#15200 Upgrade Pex to 2.1.82.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15191 Implement `tailor` goal for Helm charts
  src/python/pants/backend/experimental/helm/register.py
  src/python/pants/backend/helm/goals/tailor.py
  src/python/pants/backend/helm/goals/tailor_test.py
Labels: category:new feature

#15203 Don't log set up of binary shims
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: needs-cherrypick, category:documentation

#15205 golang: add more cache keys based on tool IDs
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/link.py
Labels: needs-cherrypick, category:bugfix

#15206 Don't log set up of binary shims (Cherry-pick of #15203)
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:documentation

#15207 [internal] kotlin: switch to "embeddable" compiler and Kotlin v1.6.20
  src/python/pants/backend/kotlin/compile/kotlinc.py
  src/python/pants/backend/kotlin/compile/kotlinc_test.py
  src/python/pants/backend/kotlin/subsystems/kotlin.py
Labels: category:internal

#15208 [internal] bsp: show experimental-bsp goal in help
  src/python/pants/bsp/goal.py
Labels: category:internal

#15202 [internal] improve error message to be less confusing
  src/rust/engine/process_execution/src/remote.rs
Labels: category:internal

#15213 Support poetry wildcard requirements.
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
Labels: category:bugfix

#15216 Fix commit hooks script for rename of `.git-blame-ignore-revs`.
  build-support/bin/install_git_hooks.sh
Labels: category:internal

#15210 Prepare 2.11.0rc4
  src/python/pants/notes/2.11.x.md
Labels: category:internal

#15219 Fix lockfile generation for duplicate `jvm_artifact` targets with `jar` fields.
  src/python/pants/backend/scala/resolve/lockfile_test.py
  src/python/pants/jvm/goals/lockfile.py
  src/python/pants/jvm/goals/lockfile_test.py
  src/python/pants/jvm/resolve/common.py
Labels: needs-cherrypick, category:bugfix

#15226 Fix use of `@` in path names
  src/python/pants/build_graph/address_test.py
  src/rust/engine/address/src/lib.rs
Labels: category:bugfix

#15227 [internal] kotlin: add kotlin and ktlint backends to docs
  build-support/bin/generate_docs.py
Labels: category:internal

#15229 [internal] kotlin: add `--kotlinc-args` option
  src/python/pants/backend/kotlin/compile/kotlinc.py
  src/python/pants/backend/kotlin/subsystems/kotlinc.py
Labels: category:internal

#15221 [internal] kotlin: use lockfile for dependency inference parser
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/kotlin/dependency_inference/BUILD
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.lock
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
Labels: category:internal

#15237 Simplify test for Go Protobuf
  src/python/pants/backend/codegen/protobuf/go/rules_integration_test.py
Labels: category:internal

#15235 Cache comparison job fixes: round 2
  .github/workflows/cache_comparison.yaml
  build-support/bin/cache_comparison.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15141 `MyPy` and `Pylint` partition inputs via `CoarsenedTarget`
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/target.py
  src/python/pants/jvm/resolve/coursier_fetch.py
Labels: category:performance

#15242 [internal] jvm: split lockfile access into read and write paths
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/jvm_tool.py
Labels: category:internal

#15236 [internal] kotlin: do not expose kotlin parser's lockfile to users
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
Labels: category:internal

#15228 Update `help` for python resolves with recent improvements
  src/python/pants/backend/python/subsystems/setup.py
Labels: needs-cherrypick, category:documentation

#15222 [internal] scala: use lockfile for dependency inference parser
  3rdparty/jvm/io/circe/BUILD
  3rdparty/jvm/org/scalameta/BUILD
  pants.toml
  src/python/pants/backend/scala/dependency_inference/BUILD
  src/python/pants/backend/scala/dependency_inference/scala_parser.lock
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
Labels: category:internal

#15223 [internal] java: use lockfile for dependency inference parser
  3rdparty/jvm/com/fasterxml/jackson/core/BUILD
  3rdparty/jvm/com/fasterxml/jackson/datatype/BUILD
  3rdparty/jvm/com/github/javaparser/BUILD
  pants.toml
  src/python/pants/backend/experimental/java/register.py
  src/python/pants/backend/java/dependency_inference/BUILD
  src/python/pants/backend/java/dependency_inference/__init__.py
  src/python/pants/backend/java/dependency_inference/java_parser.lock
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/backend/java/dependency_inference/java_parser_launcher.py
  src/python/pants/backend/java/dependency_inference/java_parser_test.py
Labels: category:internal

#15184 [internal] kotlin: add support for `kotlinc` compiler plugins
  src/python/pants/backend/experimental/kotlin/register.py
  src/python/pants/backend/kotlin/compile/kotlinc.py
  src/python/pants/backend/kotlin/compile/kotlinc_plugins.py
  src/python/pants/backend/kotlin/compile/kotlinc_test.py
  src/python/pants/backend/kotlin/lint/ktlint/rules_integration_test.py
  src/python/pants/backend/kotlin/subsystems/kotlinc.py
  src/python/pants/backend/kotlin/target_types.py
Labels: category:internal

#15243 Fix the placement of the pex verbosity args.
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:bugfix

#15248 Add more 2.11.0rc4 changes
  src/python/pants/notes/2.11.x.md
Labels: category:internal

#15256 [internal] remove non-existent backend name in docs generator (Cherry-pick of #15132)
  build-support/bin/generate_docs.py
Labels: category:internal

#15254 Do not lowercase Docker image tags.
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/testutil/pytest_util.py
Labels: needs-cherrypick, category:bugfix

#15255 Fix issue with Docker publish when using `[docker] tools`.
  src/python/pants/backend/docker/goals/publish.py
Labels: needs-cherrypick, category:bugfix

#15190 [internal] add mark and fixture for lockfile generation
  pants-plugins/internal_plugins/test_lockfile_fixtures/BUILD
  pants-plugins/internal_plugins/test_lockfile_fixtures/__init__.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/register.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/rules.py
  pants.toml
  src/python/pants/backend/scala/BUILD
  src/python/pants/backend/scala/compile/BUILD
  src/python/pants/backend/scala/compile/scala-library.test.lock
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/conftest.py
  src/python/pants/testutil/lockfile_fixture.py
Labels: category:internal

#15257 Allow for arbitrary suffixes when extracting
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/archive_test.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:plugin api change

#15259 Do not lowercase Docker image tags. (Cherry pick of #15254)
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/testutil/pytest_util.py
Labels: category:bugfix

#15260 Do not lowercase Docker image tags. (Cherry pick of #15254)
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/testutil/pytest_util.py
Labels: category:bugfix

#15261 Fix issue with Docker publish when using `[docker] tools`. (Cherry pick of #15255)
  src/python/pants/backend/docker/goals/publish.py
Labels: category:bugfix

#15267 Revert "[internal] add mark and fixture for lockfile generation (#15190)"
  pants-plugins/internal_plugins/test_lockfile_fixtures/BUILD
  pants-plugins/internal_plugins/test_lockfile_fixtures/__init__.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/register.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/rules.py
  pants.toml
  src/python/pants/backend/scala/BUILD
  src/python/pants/backend/scala/compile/BUILD
  src/python/pants/backend/scala/compile/scala-library.test.lock
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/conftest.py
  src/python/pants/testutil/lockfile_fixture.py
Labels: category:internal

#15264 Prepare 2.11.0rc5
  src/python/pants/notes/2.11.x.md
Labels: category:internal

#15263 Merge the JVM first and third party mappings
  src/python/pants/backend/java/dependency_inference/rules.py
  src/python/pants/backend/java/dependency_inference/symbol_mapper.py
  src/python/pants/backend/java/goals/debug_goals.py
  src/python/pants/backend/java/subsystems/java_infer.py
  src/python/pants/backend/kotlin/dependency_inference/rules.py
  src/python/pants/backend/kotlin/dependency_inference/symbol_mapper.py
  src/python/pants/backend/kotlin/goals/debug_goals.py
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/backend/scala/dependency_inference/symbol_mapper.py
  src/python/pants/backend/scala/goals/debug_goals.py
  src/python/pants/jvm/dependency_inference/artifact_mapper.py
  src/python/pants/jvm/dependency_inference/artifact_mapper_test.py
  src/python/pants/jvm/dependency_inference/symbol_mapper.py
  src/python/pants/jvm/goals/debug_goals.py
Labels: category:internal

#15265 Fix ambiguity of Scala package objects with class or object definitions
  src/python/pants/backend/java/dependency_inference/rules.py
  src/python/pants/backend/java/goals/debug_goals.py
  src/python/pants/backend/kotlin/dependency_inference/rules.py
  src/python/pants/backend/kotlin/goals/debug_goals.py
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/backend/scala/dependency_inference/rules_test.py
  src/python/pants/backend/scala/dependency_inference/symbol_mapper.py
  src/python/pants/backend/scala/goals/debug_goals.py
  src/python/pants/jvm/dependency_inference/artifact_mapper.py
  src/python/pants/jvm/dependency_inference/artifact_mapper_test.py
  src/python/pants/jvm/dependency_inference/symbol_mapper.py
  src/python/pants/jvm/goals/debug_goals.py
Labels: category:bugfix

#15272 Fix ProtobufSourcesOverridesField help message
  src/python/pants/backend/codegen/protobuf/target_types.py
Labels: category:documentation
