Repository pantsbuild/pants, pull requests merged in 2022-12, with the labels that each got.

#17661 Fix bug in Go test result exit code interpretation.
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
Labels: backend: Go, category:bugfix

#17005 Allow JVM source to depend on relocated_files target
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/compile_test.py
Labels: category:bugfix

#17683 go: add `compiler_flags` field for adding arbitrary extra compiler flags
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/build_opts.py
  src/python/pants/backend/go/util_rules/build_opts_test.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
Labels: backend: Go, category:new feature

#17697 go: add `linker_flags` field to `go_mod` and `go_binary` target types
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/build_opts.py
  src/python/pants/backend/go/util_rules/build_opts_test.py
  src/python/pants/backend/go/util_rules/link.py
Labels: backend: Go, category:new feature

#17655 Update docker docs to clarify dependency handling.
  docs/markdown/Docker/docker.md
  src/python/pants/backend/docker/target_types.py
Labels: category:documentation

#17699 Flip how we execute debugpy in `run`
  src/python/pants/backend/python/goals/run_helper.py
Labels: category:internal

#17701 go: support code coverage over multiple packages during single test
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/backend/go/util_rules/build_opts.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/coverage.py
  src/python/pants/backend/go/util_rules/coverage_test.py
  src/python/pants/backend/go/util_rules/pkg_pattern.py
  src/python/pants/backend/go/util_rules/pkg_pattern_test.py
Labels: backend: Go, category:new feature

#17669 Visibility rules: error if more than one declaration per BUILD file.
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
  src/python/pants/engine/internals/mapper.py
Labels: category:bugfix

#17594 Include transitive 3rd party deps as requirements for `python_distribution`.
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/goals/setup_py_test.py
Labels: category:user api change

#17704 Makes `tools` optional for `experimental_shell_command`
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
Labels: category:internal

#17709 A banner stating that v1 is unmaintained, and linking to v2 docs.
  src/docs/docsite.css
  src/docs/docsite.html.mustache
Labels: category:documentation

#17707 Delete cruft from previous PR
  pubring.kbx
Labels: category:internal

#17705 Don't strip the input of a `DictOption` file config
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
Labels: category:bugfix

#17710 docs: tidy up Writing plugins : rules-api directory files
  docs/markdown/Writing Plugins/rules-api/rules-api-and-target-api.md
  docs/markdown/Writing Plugins/rules-api/rules-api-concepts.md
  docs/markdown/Writing Plugins/rules-api/rules-api-file-system.md
  docs/markdown/Writing Plugins/rules-api/rules-api-goal-rules.md
  docs/markdown/Writing Plugins/rules-api/rules-api-installing-tools.md
  docs/markdown/Writing Plugins/rules-api/rules-api-process.md
  docs/markdown/Writing Plugins/rules-api/rules-api-testing.md
  docs/markdown/Writing Plugins/rules-api/rules-api-tips.md
Labels: category:documentation

#17700 Run python sources with a VenvPex
  src/python/pants/backend/codegen/protobuf/python/rules.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:performance

#17682 Add a new "preamble" plugin
  build-support/bin/generate_docs.py
  src/python/pants/backend/tools/BUILD
  src/python/pants/backend/tools/__init__.py
  src/python/pants/backend/tools/preamble/BUILD
  src/python/pants/backend/tools/preamble/__init__.py
  src/python/pants/backend/tools/preamble/register.py
  src/python/pants/backend/tools/preamble/rules.py
  src/python/pants/backend/tools/preamble/rules_integration_test.py
  src/python/pants/backend/tools/preamble/subsystem.py
  src/python/pants/bin/BUILD
Labels: category:new feature

#17649 Expose target field defaults in BUILD files.
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
  src/python/pants/init/engine_initializer.py
Labels: category:new feature

#17725 More precise running workunit for processes executing remotely (Cherry-pick of #17719)
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/workunit_store/src/lib.rs
Labels: category:bugfix

#17722 chdir in `rule_runner.run_interactive_process`
  src/python/pants/testutil/rule_runner.py
Labels: category:bugfix

#17724 Switch our usage of `regex-lint` to `preamble`
  build-support/preambles/config.yaml
  build-support/regexes/config.yaml
  pants.toml
  src/rust/engine/async_latch/src/tests.rs
  src/rust/engine/async_value/src/tests.rs
  src/rust/engine/concrete_time/src/tests.rs
  src/rust/engine/fs/brfs/src/syscall_tests.rs
  src/rust/engine/fs/brfs/src/tests.rs
  src/rust/engine/fs/src/posixfs_tests.rs
  src/rust/engine/fs/src/tests.rs
  src/rust/engine/fs/store/src/immutable_inputs.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/fs/store/src/local_tests.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/snapshot_ops_tests.rs
  src/rust/engine/fs/store/src/snapshot_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/graph/src/entry.rs
  src/rust/engine/graph/src/tests.rs
  src/rust/engine/grpc_util/src/hyper.rs
  src/rust/engine/grpc_util/src/tls.rs
  src/rust/engine/hashing/src/digest_tests.rs
  src/rust/engine/hashing/src/fingerprint_tests.rs
  src/rust/engine/hashing/src/hasher_tests.rs
  src/rust/engine/nailgun/src/tests.rs
  src/rust/engine/process_execution/src/bounded.rs
  src/rust/engine/process_execution/src/bounded_tests.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/children.rs
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/process_execution/src/nailgun/parsed_jvm_command_lines.rs
  src/rust/engine/process_execution/src/nailgun/parsed_jvm_command_lines_tests.rs
  src/rust/engine/process_execution/src/nailgun/tests.rs
  src/rust/engine/process_execution/src/named_caches.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/protos/src/conversions.rs
  src/rust/engine/protos/src/conversions_tests.rs
  src/rust/engine/protos/src/verification.rs
  src/rust/engine/protos/src/verification_tests.rs
  src/rust/engine/rule_graph/src/tests.rs
  src/rust/engine/sharded_lmdb/src/tests.rs
  src/rust/engine/src/externs/interface_tests.rs
  src/rust/engine/stdio/src/term.rs
  src/rust/engine/testutil/mock/src/cas.rs
  src/rust/engine/testutil/mock/src/cas_service.rs
  src/rust/engine/testutil/mock/src/execution_server.rs
  src/rust/engine/testutil/src/data.rs
  src/rust/engine/testutil/src/file.rs
  src/rust/engine/testutil/src/path.rs
  src/rust/engine/watch/src/tests.rs
  src/rust/engine/workunit_store/src/tests.rs
Labels: category:internal

#17741 Disable lazy fetch in pantsbuild CI
  pants.toml
Labels: category:internal

#17708 Doc fixes and updates:
  docs/markdown/Python/python/python-interpreter-compatibility.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-lint-goal.md
  docs/markdown/Writing Plugins/rules-api/rules-api-and-target-api.md
Labels: category:documentation

#17742 Streamline local dist handling when running python sources.
  src/python/pants/backend/python/goals/run_helper.py
Labels: category:internal

#17731 go: add `assembler_flags` field for adding arbitrary extra assembler flags
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/build_opts.py
  src/python/pants/backend/go/util_rules/build_opts_test.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
Labels: backend: Go, category:new feature

#17734 go: use target spec for coverage output directories plus support import path
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/backend/go/util_rules/coverage.py
  src/python/pants/backend/go/util_rules/coverage_output.py
Labels: backend: Go, category:new feature

#17678 Test DebugAdapter requests, and fix issues
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/goals/conftest.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/subsystems/debugpy.lock
  src/python/pants/backend/python/subsystems/debugpy.py
Labels: needs-cherrypick, category:bugfix

#17755 Disables hardlinking feature for the time being. See #17754
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/tests.rs
Labels: category:internal

#17728 go: use module sources digest for each of its packages
  src/python/pants/backend/go/util_rules/third_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg_test.py
Labels: backend: Go, category:bugfix

#16196 [internal] add network-level gRPC timeouts
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/grpc_util/src/lib.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: category:internal

#17757 Prepare 2.15.0rc0
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#17756 Prepare 2.16.0.dev2
  src/python/pants/VERSION
  src/python/pants/notes/2.16.x.md
  src/python/pants/option/global_options.py
Labels: category:internal

#17744 Renames `output_files` and `output_directories` fields for `experimental_shell_command`
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:internal

#17750 Properly set pex_root when running python sources in-sandbox.
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
Labels: category:internal

#17743 Adds `execution_dependencies` for `experimental_shell_command`
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
  src/python/pants/backend/shell/goals/test_test.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  testprojects/src/python/BUILD
Labels: category:user api change

#17760 Visibility: fix rules path for generated targets.
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:bugfix

#17761 Run python sources with a VenvPex (Cherry-pick of #17700)
  src/python/pants/backend/codegen/protobuf/python/rules.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:performance

#17765 chdir in `rule_runner.run_interactive_process` (Cherry-pick of #17722)
  src/python/pants/testutil/rule_runner.py
Labels: category:bugfix

#17767 Add overloads to `RuleRunner.write_files` to make it more caller-friendly (Cherry-pick of #17687)
  src/python/pants/backend/go/util_rules/first_party_pkg_test.py
  src/python/pants/backend/helm/util_rules/renderer_test.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/subsystem_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/terraform/goals/check_test.py
  src/python/pants/testutil/rule_runner.py
Labels: category:internal

#17766 Refactor `run_python_source_integration_test.py` to use `RuleRunner` (Cherry-pick of #17723)
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
Labels: category:internal

#17681 [Visibility] `**/..` globs can match root level files
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
Labels: category:bugfix

#17770 go: allow exporting cgo codegen for third party packages
  src/python/pants/backend/go/goals/debug_goals.py
  src/python/pants/backend/go/util_rules/cgo.py
Labels: backend: Go, category:internal

#17763 Visibility: empty selector should match no target.
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:bugfix

#17768 Test DebugAdapter requests, and fix issues (Cherry-pick of #17678)
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/goals/conftest.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/subsystems/debugpy.lock
  src/python/pants/backend/python/subsystems/debugpy.py
Labels: category:bugfix

#17775 go: remove notion of separate `__obj__` directory
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/cgo.py
Labels: backend: Go, category:bugfix

#17773 Add export-codegen goal to more backends
  src/python/pants/backend/codegen/thrift/apache/python/register.py
  src/python/pants/backend/experimental/openapi/codegen/java/register.py
  src/python/pants/backend/shell/register.py
Labels: category:user api change

#17779 Restore support for :all: in only_binary/no_binary.
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/setup_test.py
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/lockfile_metadata_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
Labels: needs-cherrypick, category:bugfix

#17783 Do not clear the `pantsd` log while restarting
  src/python/pants/pantsd/pants_daemon.py
Labels: category:bugfix

#17782 Unconditionally register export-codegen goal in pants.core
  src/python/pants/backend/codegen/protobuf/python/register.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/codegen/thrift/apache/python/register.py
  src/python/pants/backend/docker/register.py
  src/python/pants/backend/experimental/codegen/avro/java/register.py
  src/python/pants/backend/experimental/codegen/protobuf/go/register.py
  src/python/pants/backend/experimental/codegen/protobuf/java/register.py
  src/python/pants/backend/experimental/codegen/protobuf/scala/register.py
  src/python/pants/backend/experimental/codegen/thrift/apache/java/register.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/java/register.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/scala/register.py
  src/python/pants/backend/experimental/openapi/codegen/java/register.py
  src/python/pants/backend/experimental/python/register.py
  src/python/pants/backend/shell/register.py
  src/python/pants/core/register.py
Labels: category:internal

#17730 Doc: update `Get` docstring for multiple inputs.
  src/python/pants/engine/internals/selectors.py
Labels: category:documentation

#17785 Fix validation of release PEXes.
  build-support/bin/_release_helper.py
Labels: needs-cherrypick, category:internal

#17738 [internal] Expanding `cc` dependency inference to support `include_directories`
  src/python/pants/backend/cc/dependency_inference/rules.py
  src/python/pants/backend/cc/dependency_inference/rules_integration_test.py
  src/python/pants/backend/cc/subsystems/cc_infer.py
Labels: category:internal, backend: CC

#17786 Upgrade to newest remote execution proto
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/protos/protos/bazelbuild_remote-apis/build/bazel/remote/execution/v2/remote_execution.proto
  src/rust/engine/testutil/mock/src/cas_service.rs
  src/rust/engine/testutil/mock/src/execution_server.rs
Labels: category:internal

#17788 A stub page for dep validation docs.
  docs/markdown/Using Pants/validating-dependencies.md
Labels: category:internal

#17787 Explicitly use "python" ijson backend
  pyproject.toml
  src/python/pants/backend/go/util_rules/import_analysis.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
Labels: needs-cherrypick, backend: Go, category:bugfix

#17793 Add Doctrine to user list
  build-support/bin/generate_user_list.py
Labels: category:documentation

#17795 go: rename option to --go-test-coverage-packages
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/backend/go/util_rules/coverage_test.py
Labels: backend: Go, category:internal

#17796 go: improve options passed to assembler invocations
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/assembly_integration_test.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
Labels: backend: Go, category:bugfix

#17799 go: set missing `Goal.environment_behavior` on a debug goal
  src/python/pants/backend/go/goals/debug_goals.py
Labels: backend: Go, category:internal

#17797 go: set replace_sandbox_root_in_args=True since replacement is used
  src/python/pants/backend/go/util_rules/assembly.py
Labels: backend: Go, category:internal

#17798 go: fix path lookup for copied header files
  src/python/pants/backend/go/util_rules/build_pkg.py
Labels: backend: Go, category:internal

#17801 Set up release tag mapping workflow.
  .github/workflows/release.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17806 Add a release tag backfill script.
  .github/workflows/release.yaml
  build-support/bin/backfill_s3_release_tag_mappings.py
  build-support/bin/deploy_to_s3.py
  build-support/bin/generate_github_workflows.py
  build-support/bin/install_aws_cli.sh
Labels: category:internal

#17800 An enum of Python export formats.
  docs/markdown/Using Pants/setting-up-an-ide.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/goals/export_test.py
Labels: category:user api change

#17808 Document the release tag back-fill script.
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#17804 Upgrade setproctitle to 1.3.2
  3rdparty/python/flake8.lock
  3rdparty/python/mypy.lock
  3rdparty/python/pytest.lock
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  pyproject.toml
  src/python/pants/backend/helm/subsystems/k8s_parser.lock
  src/python/pants/backend/helm/subsystems/post_renderer.lock
Labels: category:internal

#17814 Set up release tag mapping workflow. (Cherry-pick of #17801, #17806 & #17808)
  .github/workflows/release.yaml
  build-support/bin/backfill_s3_release_tag_mappings.py
  build-support/bin/deploy_to_s3.py
  build-support/bin/generate_github_workflows.py
  build-support/bin/install_aws_cli.sh
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#17815 Set up release tag mapping workflow. (Cherry-pick of #17801, #17806 & #17808)
  .github/workflows/release.yaml
  build-support/bin/backfill_s3_release_tag_mappings.py
  build-support/bin/deploy_to_s3.py
  build-support/bin/generate_github_workflows.py
  build-support/bin/install_aws_cli.sh
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#17818 Fix build-support/bin/deploy_to_s3.py.
  build-support/bin/deploy_to_s3.py
Labels: needs-cherrypick, category:internal

#17819 Fix build-support/bin/deploy_to_s3.py. (Cherry-pick of #17818)
  build-support/bin/deploy_to_s3.py
Labels: category:internal

#17820 Fix build-support/bin/deploy_to_s3.py. (Cherry-pick of #17818)
  build-support/bin/deploy_to_s3.py
Labels: category:internal

#17812 Add Astranis to user list.
  build-support/bin/generate_user_list.py
Labels: category:documentation

#17810 Add Doctrine's eng blog post to resource hub.
  docs/markdown/Introduction/media.md
Labels: category:documentation

#17777 Bump default version of shfmt from 3.2.4 to 3.6.0
  build-support/bin/rust/bootstrap_code.sh
  src/python/pants/backend/shell/lint/shfmt/subsystem.py
Labels: category:user api change

#17716 Allow targets that implement `RunFieldSet` to be executed in the sandbox for side-effects
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  src/python/pants/backend/docker/goals/run_image.py
  src/python/pants/backend/go/goals/package_binary.py
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/shell/register.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/jvm/package/deploy_jar.py
Labels: category:new feature

#17811 go: detect when `go.sum` needs additional entries filled in
  src/python/pants/backend/go/goals/debug_goals.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/cgo_test.py
  src/python/pants/backend/go/util_rules/embed_integration_test.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg_test.py
Labels: needs-cherrypick, backend: Go, category:bugfix

#17823 Get rid of _ToolLockfileMixin.
  docs/markdown/Python/python/python-third-party-dependencies.md
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
Labels: category:internal

#17632 Documentation for the new visibility rules
  docs/markdown/Using Pants/concepts/enabling-backends.md
  docs/markdown/Using Pants/validating-dependencies.md
  src/python/pants/backend/docker/target_types.py
  src/python/pants/explorer/server/BUILD
Labels: category:documentation

#17830 Remove deprecated remote-auth-plugin option.
  src/python/pants/option/global_options.py
  src/python/pants/option/global_options_test.py
  src/python/pants/util/dirutil.py
  tests/python/pants_test/pantsd/pantsd_integration_test.py
Labels: category:internal

#17771 Add support for discovering and patching `pyright` config files
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
Labels: category:new feature, backend: Python

#17832 Remove stray `--remote-auth-plugin` reference.
  build-support/bin/generate_docs.py
Labels: category:internal

#17825 go: split production of test binary from actually running it
  src/python/pants/backend/go/goals/test.py
Labels: backend: Go, category:internal

#17833 Detect Pants-generated lockfiles before attempting to validate.
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/core/util_rules/lockfile_metadata.py
Labels: category:user api change

#17835 go: pass coverage setup config into `prepare_go_test_binary` rule
  src/python/pants/backend/go/goals/test.py
Labels: backend: Go, category:internal

#17834 Unify validation of tool and user lockfile metadata.
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/lockfile_metadata_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
Labels: category:user api change

#17829 Tweak the docs about __defaults__.
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#17836 go: support the `go test` profiling options
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/core/goals/test.py
Labels: backend: Go, category:new feature

#17842 Unify the messages for lockfile validation errors.
  docs/markdown/Writing Plugins/target-api/target-api-concepts.md
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
Labels: category:user api change

#17843 Remove the ToolCustomLockfile/ToolDefaultLockfile classes.
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
Labels: category:plugin api change

#17838 Tweak the docs about __defaults__. (Cherry-pick of #17829)
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#17827 Support `experimental_run_in_sandbox`/`./pants run` for `jvm_artifact` targets
  src/python/pants/backend/experimental/java/register.py
  src/python/pants/backend/experimental/kotlin/register.py
  src/python/pants/backend/experimental/scala/register.py
  src/python/pants/jvm/antlr.test.lock
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/run.py
  src/python/pants/jvm/run_integration_test.py
  src/python/pants/jvm/target_types.py
Labels: category:new feature

#17845 Document batched `pytest` execution.
  docs/markdown/Python/python-goals/python-test-goal.md
Labels: needs-cherrypick, category:documentation

#17853 Document batched `pytest` execution. (Cherry-pick of #17845)
  docs/markdown/Python/python-goals/python-test-goal.md
Labels: category:documentation

#17849 Make export cleanup a subset of `dist/export`, not the whole thing
  src/python/pants/core/goals/export.py
Labels: category:user api change

#17859 DRYs up JVM subsystem registration code
  src/python/pants/backend/experimental/java/register.py
  src/python/pants/backend/experimental/kotlin/register.py
  src/python/pants/backend/experimental/scala/register.py
  src/python/pants/jvm/jvm_common.py
Labels: category:internal

#17861 fix a bunch of missing JVM `rules()` dependencies
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/core/target_types.py
  src/python/pants/jvm/classpath.py
  src/python/pants/jvm/jar_tool/jar_tool.py
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/run.py
Labels: category:internal

#17732 docs: add tutorial to get started writing plugins
  docs/markdown/Writing Plugins/tutorials/01-create-new-goal-with-a-custom-target.md
Labels: category:documentation

#17837 Choose distinct debug adapter ports in different tests.
  pants.toml
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/testutil/debug_adapter_util.py
Labels: category:internal

#17855 scala: support scala v3 which has different compiler/library artifacts
  src/python/pants/backend/scala/compile/scala-library-3.test.lock
  src/python/pants/backend/scala/compile/scalac.py
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/backend/scala/resolve/lockfile.py
  src/python/pants/backend/scala/test/scalatest.test.lock
  src/python/pants/backend/scala/util_rules/BUILD
  src/python/pants/backend/scala/util_rules/__init__.py
  src/python/pants/backend/scala/util_rules/versions.py
Labels: backend: JVM, category:bugfix

#17864 Support `python_requirement` as a `run`/`experimental_run_in_sandbox` target
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/run_python_requirement.py
  src/python/pants/backend/python/goals/run_python_requirement_integration_test.py
  src/python/pants/backend/python/register.py
  src/python/pants/backend/python/target_types.py
Labels: category:new feature

#17867 scala: support scala v3 which has different compiler/library artifacts (Cherry pick of #17855)
  src/python/pants/backend/scala/compile/scala-library-3.test.lock
  src/python/pants/backend/scala/compile/scalac.py
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/backend/scala/resolve/lockfile.py
  src/python/pants/backend/scala/test/scalatest.test.lock
  src/python/pants/backend/scala/util_rules/BUILD
  src/python/pants/backend/scala/util_rules/__init__.py
  src/python/pants/backend/scala/util_rules/versions.py
Labels: backend: JVM, category:bugfix

#17866 scala: support scala v3 which has different compiler/library artifacts (Cherry pick of #17855)
  src/python/pants/backend/scala/compile/scala-library-3.test.lock
  src/python/pants/backend/scala/compile/scalac.py
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/backend/scala/resolve/lockfile.py
  src/python/pants/backend/scala/test/scalatest.test.lock
  src/python/pants/backend/scala/util_rules/BUILD
  src/python/pants/backend/scala/util_rules/__init__.py
  src/python/pants/backend/scala/util_rules/versions.py
Labels: backend: JVM, category:bugfix

#17870 Split out different entry point fields, and revert `PexBinaryFieldSet`
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/run_python_requirement.py
  src/python/pants/backend/python/target_types.py
Labels: category:internal

#17847 Make JVM sources runnable
  src/python/pants/backend/java/target_types.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/scala/compile/scalac.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/core/goals/run.py
  src/python/pants/jvm/jvm_common.py
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/run.py
  src/python/pants/jvm/run_deploy_jar.py
  src/python/pants/jvm/run_integration_test.py
  src/python/pants/jvm/target_types.py
Labels: category:new feature

#17874 Default `use_pantsd` to `False` in `run_pants`
  src/python/pants/explorer/server/integration_test.py
  src/python/pants/goal/anonymous_telemetry_integration_test.py
  src/python/pants/testutil/pants_integration_test.py
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: category:plugin api change

#17876 Disable coverage in CI
  pants.ci.toml
Labels: category:internal

#17875 Don't invalidate watched files if non-perms metadata changed
  src/rust/engine/watch/src/lib.rs
Labels: category:performance

#17879 More default Python module mappings.
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:user api change

#17711 allow each resolve to be exported for multiple python interpreters
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/goals/export_test.py
Labels: category:user api change, backend: Python

#17881 Make pants work when the uid doesn't map to a user.
  src/python/pants/goal/run_tracker.py
  src/python/pants/goal/run_tracker_test.py
  src/python/pants/option/config.py
  src/python/pants/util/osutil.py
Labels: category:new feature

#17882 Use GITHUB_PATH to modify paths between CI steps.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17883 Prepare 2.15.0rc1.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#17878 Bring back hardlinking big files
  src/rust/engine/fs/store/src/lib.rs
Labels: category:performance

#17844 [internal] Subsystems, Options, and a Process for the `cc` backend
  src/python/pants/backend/cc/subsystems/compiler.py
  src/python/pants/backend/cc/target_types.py
  src/python/pants/backend/cc/util_rules/BUILD
  src/python/pants/backend/cc/util_rules/__init__.py
  src/python/pants/backend/cc/util_rules/toolchain.py
  src/python/pants/backend/cc/util_rules/toolchain_test.py
  src/python/pants/backend/experimental/cc/register.py
Labels: category:internal, backend: CC

#17880 Refactor generate_github_workflows.py to prep for aarch64 support
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17886 Remove `immutable_input_digests` from shell code
  src/python/pants/backend/shell/util_rules/shell_command.py
Labels: category:plugin api change

#17891 Remove Eric from Rust dependabot config
  .github/dependabot.yml
Labels: category:internal

#17893 upgrade to Rust v1.66.0
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/src/externs/stdio.rs
  src/rust/engine/testutil/mock/src/cas_service.rs
  src/rust/engine/workunit_store/src/lib.rs
Labels: category:internal

#17600 New help topic: `backends`.
  src/python/pants/build_graph/build_configuration.py
  src/python/pants/goal/builtins.py
  src/python/pants/help/BUILD
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_printer.py
  testprojects/src/python/plugin/BUILD
  testprojects/src/python/plugin/dist.py
Labels: category:new feature

#17887 Upgrade default mypy-protobuf version to 3.4
  src/python/pants/backend/codegen/protobuf/python/mypy_protobuf.lock
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
Labels: category:user api change

#17901 Always stop on `StopIteration` in `rule_runner.run_rule_with_mocks`
  src/python/pants/testutil/rule_runner.py
Labels: category:internal

#17885 Add [buf] config and config_discovery options
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/subsystem.py
Labels: category:new feature, backend: Protobuf

#17904 Prepare 2.14.1rc0
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#17899 docs: mention name clashing between custom goals and options when writing plugins
  docs/markdown/Writing Plugins/rules-api/rules-api-goal-rules.md
  docs/markdown/Writing Plugins/rules-api/rules-api-subsystems.md
Labels: category:documentation

#17894 docs: extend python test goal with info on collecting tests
  docs/markdown/Python/python-goals/python-test-goal.md
Labels: category:documentation

#17909 Log process stdout/stderr on deploy_to_s3.py failures.
  build-support/bin/deploy_to_s3.py
Labels: category:internal

#17841 Add output_path field to python_distribution.
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/goals/setup_py_integration_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/dists.py
Labels: category:new feature
