Repository pantsbuild/pants, pull requests merged in 2022-07, with the labels that each got.

#15962 Deprecate not setting `tailor_pex_binary_targets` explictly
  docs/markdown/Python/python/python-backend.md
  src/python/pants/backend/python/subsystems/setup.py
Labels: needs-cherrypick, category:user api change

#16022 Add ability to `run` any `PythonSourceField` (Cherry-pick of #15849)
  docs/markdown/Python/python-goals/python-run-goal.md
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_pex_binary.py
  src/python/pants/backend/python/goals/run_pex_binary_integration_test.py
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/register.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/engine/internals/options_parsing.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/option/global_options.py
  testprojects/src/python/print_env/BUILD
  tests/python/pants_test/pantsd/pantsd_integration_test.py
Labels: category:new feature

#16023 Deprecate not setting `tailor_pex_binary_targets` explictly (Cherry-pick of #15962)
  docs/markdown/Python/python/python-backend.md
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:user api change

#16024 Update 2.13.x changelog with recent cherry-picks for `2.13.0a1`
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#16020 Document Docker registries configuration options for `skip_push` and `extra_image_tags`. (Cherry-pick of #16015)
  docs/markdown/Docker/docker.md
  docs/markdown/Docker/tagging-docker-images.md
Labels: category:documentation

#16035 Default `python` `tailor_pex_binary_targets` to `False`.
  src/python/pants/backend/python/goals/tailor_test.py
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:user api change

#16034 Default `--use-deprecated-pex-binary-run-semantics` to `False`.
  src/python/pants/backend/python/goals/run_pex_binary_integration_test.py
  src/python/pants/core/goals/run_integration_test.py
  src/python/pants/core/target_types_test.py
  src/python/pants/option/global_options.py
Labels: category:user api change

#16039 Upgrade Rust to 1.62.0.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
Labels: category:internal

#16038 Fix pantsd TTY handling.
  src/rust/engine/nailgun/src/server.rs
Labels: category:bugfix

#16032 Remove the `filter` goal.
  build-support/bin/_release_helper.py
  docs/markdown/Getting Started/getting-started/existing-repositories.md
  docs/markdown/Using Pants/advanced-target-selection.md
  docs/markdown/Using Pants/project-introspection.md
  docs/markdown/Using Pants/troubleshooting.md
  src/python/pants/backend/project_info/filter_targets.py
  src/python/pants/backend/project_info/filter_targets_test.py
  src/python/pants/backend/project_info/register.py
  src/python/pants/goal/run_tracker.py
Labels: category:user api change

#16033 Remove `golang` `expected_version` option.
  src/python/pants/backend/go/subsystems/golang.py
Labels: category:user api change

#16036 Remove `python-infer` `inits` option.
  src/python/pants/backend/python/dependency_inference/rules.py
Labels: category:user api change

#16046 Fix pantsd TTY handling. (Cherry-pick of #16038)
  src/rust/engine/nailgun/src/server.rs
Labels: category:bugfix

#16047 Fix pantsd TTY handling. (Cherry-pick of #16038)
  src/rust/engine/nailgun/src/server.rs
Labels: category:bugfix

#16048 Fix pantsd TTY handling. (Cherry-pick of #16038)
  src/rust/engine/nailgun/src/server.rs
Labels: category:bugfix

#16041 Skip CI checks on docs-only PRs.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16053 A better solution for skipping CI steps for docs-only changes.
  .github/workflows/audit.yaml
  .github/workflows/cancel.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16045 Upgrade Pex to 2.1.94. (Cherry-pick of #16029)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  build-support/bin/BUILD
  build-support/bin/reversion_test.py
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#16027 Fix alpha release email template typo.
  docs/markdown/Contributions/releases/release-process.md
Labels: category:documentation

#16025 Remove unnecessary pex_binary targets
  build-support/bin/BUILD
Labels: category:internal

#16051 Fix CI provider table rendering.
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#16061 Fix CI provider table rendering. (#16051)
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#16062 Fix CI provider table rendering. (#16051)
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#16059 Update docs with 2.12 changes: default Pex lockfile generator, `pantstoml` env var interpolation, pip VCS requirements, and Python interpreter constraints (Cherry-pick of #16000)
  docs/markdown/Python/python/python-interpreter-compatibility.md
  docs/markdown/Python/python/python-third-party-dependencies.md
  docs/markdown/Using Pants/concepts/options.md
  docs/markdown/Using Pants/setting-up-an-ide.md
  src/python/pants/notes/2.12.x.md
Labels: category:documentation

#16058 Update docs with 2.12 changes: default Pex lockfile generator, `pants.toml` env var interpolation, pip VCS requirements, and Python interpreter constraints (Cherry-pick of #16000)
  docs/markdown/Python/python/python-interpreter-compatibility.md
  docs/markdown/Python/python/python-third-party-dependencies.md
  docs/markdown/Using Pants/concepts/options.md
  docs/markdown/Using Pants/setting-up-an-ide.md
  src/python/pants/notes/2.12.x.md
  src/python/pants/notes/2.13.x.md
Labels: category:documentation

#16037 Pants internally uses dedicated Sources and Dependencies fields
  src/python/pants/backend/cc/target_types.py
  src/python/pants/backend/codegen/avro/target_types.py
  src/python/pants/backend/codegen/protobuf/target_types.py
  src/python/pants/backend/codegen/thrift/target_types.py
  src/python/pants/backend/java/target_types.py
  src/python/pants/backend/javascript/target_types.py
  src/python/pants/backend/project_info/dependees_test.py
  src/python/pants/backend/project_info/filedeps_test.py
  src/python/pants/backend/project_info/filter_targets_test.py
  src/python/pants/backend/project_info/paths_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/python_sources_test.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/swift/target_types.py
  src/python/pants/backend/terraform/target_types.py
  src/python/pants/conftest.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/stripped_source_files_test.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/defaults_test.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/target_types.py
  src/python/pants/jvm/test/junit.py
Labels: category:plugin api change

#16064 Staunch CI bleeding from #15995.
  pants.toml
Labels: category:internal

#16013 Add support for extra env variables in go tests
  src/python/pants/backend/codegen/protobuf/go/rules_integration_test.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/embed_integration_test.py
Labels: needs-cherrypick, category:new feature

#15846 `fmt` plugins can add new files
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
Labels: category:plugin api change

#16066 Fix `--changed-since` with `tailor` and `update-build-files` when no changes
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/update_build_files.py
Labels: category:bugfix

#16067 Add support for extra env variables in go tests (Cherry-pick of #16013)
  src/python/pants/backend/codegen/protobuf/go/rules_integration_test.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/embed_integration_test.py
Labels: category:new feature

#16069 Fix JVM symbol mapping debug output.
  src/python/pants/jvm/dependency_inference/artifact_mapper.py
Labels: category:internal

#16052 Prepare the 2.14.0.dev1 release.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16068 Fix typo in warning for `[python].resolve_all_constraints`
  src/python/pants/backend/python/util_rules/pex_from_targets.py
Labels: needs-cherrypick, category:documentation

#16075 Record ongoing backtrack attempts
  pants.toml
  src/rust/engine/src/context.rs
Labels: needs-cherrypick, category:bugfix

#16078 Write to caches during backtracking
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/src/context.rs
Labels: needs-cherrypick, category:bugfix

#16081 Write to caches during backtracking (Cherry-pick of #16078)
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/src/context.rs
Labels: category:bugfix

#16080 Record ongoing backtrack attempts (Cherry-pick of #16075)
  src/rust/engine/src/context.rs
Labels: category:bugfix

#16094 Revert "Bump serde from 1.0.136 to 1.0.138 in /src/rust/engine (#16070)"
  src/rust/engine/Cargo.lock
  src/rust/engine/concrete_time/Cargo.toml
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/process_execution/Cargo.toml
Labels: category:internal

#16097 Re-enable `remote_cache_eager_fetch`.
  pants.toml
Labels: category:internal

#16102 New doc explaining vcs_version. (#16092)
  docs/markdown/Using Pants/generating-version-tags.md
Labels: category:documentation

#16112 Fix poetry locks missing hashes.
  src/python/pants/backend/python/subsystems/poetry.py
Labels: needs-cherrypick, category:user api change

#16114 Fix poetry locks missing hashes. (Cherry-pick of #16112)
  src/python/pants/backend/python/subsystems/poetry.py
Labels: category:user api change

#16115 Fix poetry locks missing hashes. (Cherry-pick of #16112)
  src/python/pants/backend/python/subsystems/poetry.py
Labels: category:user api change

#16117 Add a lock for the Poetry tool.
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/subsystems/poetry.lock
  src/python/pants/backend/python/subsystems/poetry.py
Labels: category:user api change

#16113 Fix poetry locks missing hashes. (Cherry-pick of #16112)
  src/python/pants/backend/python/subsystems/poetry.py
Labels: category:user api change

#16118 Re-enable `remote_cache_eager_fetch`. (Cherry-pick of #16097)
  pants.toml
Labels: category:internal

#15951 Allow debugging Pants itself!
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/markdown/Contributions/development/contributions-debugging.md
  pants
  src/rust/engine/fs/store/benches/store.rs
  src/rust/engine/src/externs/scheduler.rs
  src/rust/engine/task_executor/src/lib.rs
Labels: category:internal

#16089 Fix issue with `__defaults__` not propagating over gaps in the tree of BUILD files.
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: category:bugfix

#16095 Make the "Merge OK" CI check work properly
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16124 Prepare the 2.14.0.dev2 release.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16106 Optimize `get_expanded_specs` for `StreamingWorkunit` plugins
  src/python/pants/backend/codegen/avro/java/rules_integration_test.py
  src/python/pants/bsp/protocol.py
  src/python/pants/build_graph/address.py
  src/python/pants/engine/collection.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/streaming_workunit_handler.py
  src/python/pants/jvm/testutil.py
Labels: needs-cherrypick, category:bugfix

#16128 Revert "Upgrade Pex to 2.1.95 and default version of black to 22.6.0."
  3rdparty/python/flake8.lock
  3rdparty/python/mypy.lock
  3rdparty/python/pytest.lock
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/cc/lint/clangformat/clangformat.lock
  src/python/pants/backend/codegen/protobuf/python/mypy_protobuf.lock
  src/python/pants/backend/codegen/protobuf/python/mypy_protobuf_lockfile.txt
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/docker/subsystems/dockerfile.lock
  src/python/pants/backend/docker/subsystems/dockerfile_lockfile.txt
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/lint/autoflake/autoflake.lock
  src/python/pants/backend/python/lint/bandit/bandit.lock
  src/python/pants/backend/python/lint/black/black.lock
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/docformatter/docformatter.lock
  src/python/pants/backend/python/lint/flake8/flake8.lock
  src/python/pants/backend/python/lint/isort/isort.lock
  src/python/pants/backend/python/lint/pylint/pylint.lock
  src/python/pants/backend/python/lint/pyupgrade/pyupgrade.lock
  src/python/pants/backend/python/lint/yapf/yapf.lock
  src/python/pants/backend/python/subsystems/coverage_py.lock
  src/python/pants/backend/python/subsystems/debugpy.lock
  src/python/pants/backend/python/subsystems/ipython.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/pytest.lock
  src/python/pants/backend/python/subsystems/setuptools.lock
  src/python/pants/backend/python/subsystems/setuptools_scm.lock
  src/python/pants/backend/python/subsystems/twine.lock
  src/python/pants/backend/python/typecheck/mypy/mypy.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/terraform/hcl2.lock
Labels: category:user api change

#16123 Make the "Merge OK" CI check work properly (#16095)
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16136 Add 2.12 changelog to docsite
  docs/markdown/Releases/changelog.md
Labels: needs-cherrypick, category:documentation

#16139 Add 2.12 changelog to docsite (cherrypick #16136)
  docs/markdown/Releases/changelog.md
Labels: category:documentation

#16137 Upgrade Pex to 2.1.96.
  3rdparty/python/flake8.lock
  3rdparty/python/mypy.lock
  3rdparty/python/pytest.lock
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/cc/lint/clangformat/clangformat.lock
  src/python/pants/backend/codegen/protobuf/python/mypy_protobuf.lock
  src/python/pants/backend/codegen/protobuf/python/mypy_protobuf_lockfile.txt
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/docker/subsystems/dockerfile.lock
  src/python/pants/backend/docker/subsystems/dockerfile_lockfile.txt
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/lint/autoflake/autoflake.lock
  src/python/pants/backend/python/lint/bandit/bandit.lock
  src/python/pants/backend/python/lint/black/black.lock
  src/python/pants/backend/python/lint/docformatter/docformatter.lock
  src/python/pants/backend/python/lint/flake8/flake8.lock
  src/python/pants/backend/python/lint/isort/isort.lock
  src/python/pants/backend/python/lint/pylint/pylint.lock
  src/python/pants/backend/python/lint/pyupgrade/pyupgrade.lock
  src/python/pants/backend/python/lint/yapf/yapf.lock
  src/python/pants/backend/python/subsystems/coverage_py.lock
  src/python/pants/backend/python/subsystems/debugpy.lock
  src/python/pants/backend/python/subsystems/ipython.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/poetry.lock
  src/python/pants/backend/python/subsystems/pytest.lock
  src/python/pants/backend/python/subsystems/setuptools.lock
  src/python/pants/backend/python/subsystems/setuptools_scm.lock
  src/python/pants/backend/python/subsystems/twine.lock
  src/python/pants/backend/python/typecheck/mypy/mypy.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/terraform/hcl2.lock
Labels: needs-cherrypick, category:user api change

#16138 Add 2.12 changelog to docsite (cherrypick #16136)
  docs/markdown/Releases/changelog.md
Labels: category:documentation

#15947 Add support for strict and color flags in Helm unittest
  src/python/pants/backend/helm/subsystems/unittest.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/test/unittest.py
Labels: category:new feature

#16107 Fold dep injection into inference, and use FieldSet
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/awslambda/python/target_types_test.py
  src/python/pants/backend/cc/dependency_inference/rules.py
  src/python/pants/backend/cc/dependency_inference/rules_integration_test.py
  src/python/pants/backend/codegen/avro/java/rules.py
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/codegen/protobuf/java/dependency_inference.py
  src/python/pants/backend/codegen/protobuf/protobuf_dependency_inference.py
  src/python/pants/backend/codegen/protobuf/protobuf_dependency_inference_test.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem_test.py
  src/python/pants/backend/codegen/protobuf/scala/dependency_inference.py
  src/python/pants/backend/codegen/thrift/apache/java/rules.py
  src/python/pants/backend/codegen/thrift/apache/python/rules.py
  src/python/pants/backend/codegen/thrift/apache/python/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/dependency_inference.py
  src/python/pants/backend/codegen/thrift/dependency_inference_test.py
  src/python/pants/backend/codegen/thrift/scrooge/java/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/scala/rules.py
  src/python/pants/backend/docker/util_rules/dependencies.py
  src/python/pants/backend/docker/util_rules/dependencies_test.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/target_type_rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types_test.py
  src/python/pants/backend/helm/dependency_inference/chart.py
  src/python/pants/backend/helm/dependency_inference/chart_test.py
  src/python/pants/backend/helm/dependency_inference/unittest.py
  src/python/pants/backend/helm/dependency_inference/unittest_test.py
  src/python/pants/backend/java/dependency_inference/rules.py
  src/python/pants/backend/java/dependency_inference/rules_test.py
  src/python/pants/backend/kotlin/dependency_inference/rules.py
  src/python/pants/backend/kotlin/dependency_inference/rules_test.py
  src/python/pants/backend/kotlin/test/junit.py
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/backend/scala/dependency_inference/rules_test.py
  src/python/pants/backend/shell/dependency_inference.py
  src/python/pants/backend/shell/dependency_inference_test.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/dependency_inference_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/target.py
  src/rust/engine/rule_graph/src/tests.rs
Labels: category:plugin api change

#16142 [internal] CI: add :: to update-build-files invocation
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16141 Improve memoization of interpreter constraints, Python parsing, and request classes
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/goal/anonymous_telemetry.py
  src/python/pants/goal/stats_aggregator.py
Labels: needs-cherrypick, category:bugfix

#16133 [internal] scala: add compilation test for ScalaPB
  src/python/pants/backend/codegen/protobuf/scala/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/scala/scalapb.test.lock
Labels: category:internal

#16140 [internal] refactor `find_jvm_artifacts_or_raise` to make its exceptions usable to show users
  src/python/pants/backend/codegen/avro/java/rules.py
  src/python/pants/backend/codegen/protobuf/java/dependency_inference.py
  src/python/pants/backend/codegen/protobuf/scala/dependency_inference.py
  src/python/pants/backend/codegen/thrift/apache/java/rules.py
  src/python/pants/backend/kotlin/dependency_inference/rules.py
  src/python/pants/backend/kotlin/test/junit.py
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/jvm/dependency_inference/artifact_mapper.py
Labels: category:internal

#16147 Optimize `get_expanded_specs` for `StreamingWorkunit` plugins (Cherry-pick of #16106)
  src/python/pants/backend/codegen/avro/java/rules_integration_test.py
  src/python/pants/bsp/protocol.py
  src/python/pants/build_graph/address.py
  src/python/pants/engine/collection.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/streaming_workunit_handler.py
  src/python/pants/jvm/testutil.py
Labels: category:bugfix

#16152 Fix a test compilation failure due to bad skip flag in #16093.
  src/rust/engine/process_execution/src/local_tests.rs
Labels: category:internal

#16149 Updates installation docs to refer to the 1-step setup script
  docs/markdown/Getting Started/getting-started/installation.md
  docs/markdown/Getting Started/getting-started/manual-installation.md
Labels: needs-cherrypick, category:documentation

#16157 Updates installation docs to refer to the 1-step setup script (Cherry-picks of #16149)
  docs/markdown/Getting Started/getting-started/installation.md
  docs/markdown/Getting Started/getting-started/manual-installation.md
Labels: category:documentation

#16135 Initial cleanup and simplification of DynamicRemoteOptions.from_options
  src/python/pants/option/global_options.py
Labels: category:internal

#16148 Add support for `InteractiveProcess` consuming inputs while `run_in_workspace=True` (Cherry-pick of #16093)
  src/python/pants/backend/docker/goals/publish_test.py
  src/python/pants/backend/helm/goals/publish_test.py
  src/python/pants/backend/python/goals/publish_test.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/goals/run_pex_binary_integration_test.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/scala/goals/repl.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/repl.py
  src/python/pants/core/goals/run.py
  src/python/pants/engine/process.py
  src/python/pants/engine/process_test.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/run_deploy_jar.py
  src/python/pants/testutil/process_util.py
  src/rust/engine/process_execution/src/immutable_inputs.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
Labels: category:bugfix

#16153 Improve memoization of interpreter constraints, Python parsing, and request classes (Cherry-pick of #16141)
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/goal/anonymous_telemetry.py
  src/python/pants/goal/stats_aggregator.py
Labels: category:bugfix

#16154 Improve memoization of interpreter constraints, Python parsing, and request classes (Cherry-pick of #16141)
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/goal/anonymous_telemetry.py
  src/python/pants/goal/stats_aggregator.py
Labels: category:bugfix

#16150 Fix "dependency" pluralization
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: category:bugfix

#16151 Move some remote cache & remote execution validation to post init
  src/python/pants/option/global_options.py
  tests/python/pants_test/init/test_options_initializer.py
Labels: category:internal

#16155 Allow for dependency inference plugins to provide excludes
  src/python/pants/backend/go/target_type_rules_test.py
  src/python/pants/backend/helm/dependency_inference/chart_test.py
  src/python/pants/backend/helm/dependency_inference/unittest_test.py
  src/python/pants/backend/java/dependency_inference/rules.py
  src/python/pants/backend/java/dependency_inference/rules_test.py
  src/python/pants/backend/kotlin/dependency_inference/rules_test.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/python/pants/backend/scala/dependency_inference/rules_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/target.py
Labels: category:new feature

#16130 java: add proper inference of Scrooge Java Thrift dependencies
  src/python/pants/backend/codegen/thrift/scrooge/java/BUILD
  src/python/pants/backend/codegen/thrift/scrooge/java/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/java/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/scrooge/java/scrooge.test.lock
Labels: category:bugfix

#16156 [internal] scala/thrift: update scrooge scala thift codegen to properly inject deps
  src/python/pants/backend/codegen/thrift/scrooge/scala/BUILD
  src/python/pants/backend/codegen/thrift/scrooge/scala/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/scala/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/scrooge/scala/scrooge.test.lock
Labels: category:internal

#16160 Port `@rule` `Get`s to rust
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/internals/selectors_test.py
  src/rust/engine/src/externs/mod.rs
Labels: category:performance

#16159 [internal] protobuf/java: add compilation test
  src/python/pants/backend/codegen/protobuf/java/rules_integration_test.py
Labels: category:internal

#16126 Add test timeouts to JUnit and Scalatest targets.
  pants.toml
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/java/target_types.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/jvm/target_types.py
  src/python/pants/jvm/test/junit.py
Labels: category:user api change

#16168 Upgrade python reqs, upgrade default setuptools to 63.1.0
  3rdparty/python/flake8.lock
  3rdparty/python/mypy.lock
  3rdparty/python/pytest.lock
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/setuptools.lock
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/option/config.py
Labels: category:user api change

#16169 [internal] add compile test for Apache Thrift Java codegen
  src/python/pants/backend/codegen/thrift/apache/java/rules_integration_test.py
Labels: category:internal

#16176 Fix defaulting of parameters in explicitly specified deps on `parametrize`d targets for AsyncFieldMixin
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: needs-cherrypick, category:bugfix

#16178 Upgrade Pex to 2.1.98. (#16173)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#16170 [internal] add compile test for WSDL Java codegen backend
  src/python/pants/backend/codegen/soap/java/BUILD
  src/python/pants/backend/codegen/soap/java/rules_integration_test.py
  src/python/pants/backend/codegen/soap/java/wdsl.test.lock
Labels: category:internal

#16180 Fix defaulting of parameters in explicitly specified deps on `parametrize`d targets for AsyncFieldMixin (Cherry-pick of #16176)
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: category:bugfix

#16179 Fix defaulting of parameters in explicitly specified deps on `parametrize`d targets for AsyncFieldMixin (Cherry-pick of #16176)
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: category:bugfix

#16177 Port `@rule` `Get`s to rust (Cherry-pick of #16160)
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/internals/selectors_test.py
  src/rust/engine/src/externs/mod.rs
Labels: category:performance

#16181 Support timeouts in Helm unittest targets
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/util_rules/tool.py
  src/python/pants/backend/helm/util_rules/tool_test.py
Labels: category:new feature

#16174 Allow macros to raise builtin Errors
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: category:bugfix

#16182 Prepare `2.12.1rc0`.
  src/python/pants/notes/2.12.x.md
Labels: category:internal

#16184 Upgrade Pex to 2.1.99.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#16183 Use filelists to make archive creation tasks more reliable
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:bugfix

#16186 Use filelists to make archive creation tasks more reliable (Cherry-pick of #16183)
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:bugfix

#16134 Optionally strip metadata and timestamps from JVM jars
  pants.toml
  src/python/pants/backend/codegen/avro/java/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/scala/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/apache/java/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/scrooge/java/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/scrooge/scala/rules_integration_test.py
  src/python/pants/backend/experimental/codegen/protobuf/scala/register.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/java/register.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/scala/register.py
  src/python/pants/backend/experimental/java/register.py
  src/python/pants/backend/experimental/kotlin/register.py
  src/python/pants/backend/experimental/scala/register.py
  src/python/pants/backend/java/compile/javac.py
  src/python/pants/backend/java/compile/javac_test.py
  src/python/pants/backend/java/dependency_inference/rules_test.py
  src/python/pants/backend/java/lint/google_java_format/rules_integration_test.py
  src/python/pants/backend/kotlin/compile/kotlinc.py
  src/python/pants/backend/kotlin/lint/ktlint/rules_integration_test.py
  src/python/pants/backend/kotlin/test/junit_test.py
  src/python/pants/backend/scala/compile/scalac.py
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/scala/test/scalatest_test.py
  src/python/pants/bsp/protocol_test.py
  src/python/pants/bsp/util_rules/targets_test.py
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/compile_test.py
  src/python/pants/jvm/dependency_inference/artifact_mapper_test.py
  src/python/pants/jvm/dependency_inference/java_scala_interop_test.py
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/package/deploy_jar_test.py
  src/python/pants/jvm/package/war_test.py
  src/python/pants/jvm/resources.py
  src/python/pants/jvm/resources_test.py
  src/python/pants/jvm/strip_jar/BUILD
  src/python/pants/jvm/strip_jar/StripJar.java
  src/python/pants/jvm/strip_jar/__init__.py
  src/python/pants/jvm/strip_jar/strip_jar.lock
  src/python/pants/jvm/strip_jar/strip_jar.py
  src/python/pants/jvm/strip_jar/strip_jar_test.py
  src/python/pants/jvm/subsystems.py
  src/python/pants/jvm/test/junit_test.py
Labels: category:new feature

#16198 Fill address parameters in all cases, rather than only when a consumer is `parametrize`d.
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
Labels: needs-cherrypick, category:bugfix

#16165 Warn users if they set remote cache and or/execution via config while the values are provided by the auth plugin.
  src/python/pants/option/global_options.py
Labels: category:user api change

#16201 Add MacStadium logo to README
  README.md
Labels: category:internal

#16204 add overrides field to scala targets
  src/python/pants/backend/scala/target_types.py
Labels: category:bugfix

#16205 Document the "fromfile" feature.
  docs/markdown/Using Pants/concepts/options.md
Labels: category:documentation

#16208 Document the "fromfile" feature. (cherrypick of #16205)
  docs/markdown/Using Pants/concepts/options.md
Labels: category:documentation

#16207 Document the "fromfile" feature. (cherrypick of #16205)
  docs/markdown/Using Pants/concepts/options.md
Labels: category:documentation

#16171 Add support for auth plugin name and refactor option names in log messages
  src/python/pants/option/global_options.py
Labels: category:plugin api change

#16197 Fix explicit dependencies of `parametrize`d targets not working for some target types
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
Labels: needs-cherrypick, category:bugfix

#16211 Fill address parameters in all cases, rather than only when a consumer is `parametrize`d. (Cherry-pick of #16198)
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
Labels: category:bugfix

#16213 Fix explicit dependencies of `parametrize`d targets not working for some target types (Cherry-pick of #16197)
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
Labels: category:bugfix

#16206 Generically compute dynamic defaults for `Field`s
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/java/target_types.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/bsp/util_rules/targets_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
  src/python/pants/engine/target.py
  src/python/pants/jvm/target_types.py
Labels: category:plugin api change

#16214 Fix explicit dependencies of `parametrize`d targets not working for some target types (#16197)
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
Labels: category:bugfix

#16221 Add Vicara Solutions to the users page.
  build-support/bin/generate_user_list.py
Labels: category:documentation

#16220 Generically compute dynamic defaults for `Field`s (Cherry-pick of #16206)
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/java/target_types.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/bsp/util_rules/targets_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
  src/python/pants/engine/target.py
  src/python/pants/jvm/target_types.py
Labels: category:plugin api change

#16225 Upgrade Pex to 2.1.99. (Cherry-pick of #16184)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#16226 Remove `PANTS(C)_PROFILE` in favor of recommending `py-spy`.
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/bin/pants_env_vars.py
  src/python/pants/bin/pants_loader.py
  src/python/pants/testutil/pants_integration_test.py
  src/python/pants/util/contextutil.py
  src/python/pants/util/contextutil_test.py
Labels: category:internal

#16203 allow JVM sources to have files dependencies
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/compile_test.py
Labels: category:new feature

#16228 fix scala plugins args order causing cache issues
  src/python/pants/backend/scala/compile/scalac_plugins.py
Labels: needs-cherrypick, category:bugfix

#16227 Ban `../` in `source` and `sources` fields
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: needs-cherrypick, category:user api change

#16235 add overrides field to scala targets (Cherry-pick of #16204)
  src/python/pants/backend/scala/target_types.py
Labels: category:bugfix

#16234 fix scala plugins args order causing cache issues (Cherry-pick of #16228)
  src/python/pants/backend/scala/compile/scalac_plugins.py
Labels: category:bugfix

#16237 Ban `../` in `source` and `sources` fields (Cherry-pick of #16227)
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:user api change

#16233 fix scala plugins args order causing cache issues (Cherry-pick of #16228)
  src/python/pants/backend/scala/compile/scalac_plugins.py
Labels: category:bugfix

#16215 Add `include_sources` to `pex_binary` target
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: category:new feature

#16248 [internal] Refactors `output_field` to default to something that disambiguates on parametrized fields (cherry-pick of #16232)
  src/python/pants/build_graph/address.py
  src/python/pants/core/goals/package.py
Labels: category:bugfix

#16249 Apply parameter filling for `parametrize`d dependencies to excludes, and fix accommodation for file-addressed atom targets
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: needs-cherrypick, category:bugfix

#16252 Add `include_sources` to `pex_binary` target (Cherry-pick of #16215)
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: category:new feature

#16253 Add [python].default_run_goal_use_sandbox (Cherry-pick of #16239)
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/target_types.py
Labels: category:new feature

#16255 Copy the category label when cherry-picking
  build-support/bin/cherry_pick.sh
Labels: category:internal

#16256 Prepare `2.12.1rc2`.
  src/python/pants/notes/2.12.x.md
Labels: category:internal

#16236 allow JVM sources to have files dependencies (Cherry-pick of #16203)
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/compile_test.py
Labels: category:new feature

#16250 Apply parameter filling for `parametrize`d dependencies to excludes, and fix accommodation for file-addressed atom targets (Cherry-pick of #16249)
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: category:bugfix

#16254 Refactors `output_field` to default to something that disambiguates on paramtrized fields (Cherry-pick of #16232)
  src/python/pants/build_graph/address.py
  src/python/pants/core/goals/package.py
Labels: category:bugfix

#16246 add Go ASDF support
  src/python/pants/backend/experimental/go/register.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/subsystems/BUILD
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/go_bootstrap.py
  src/python/pants/backend/go/util_rules/go_bootstrap_test.py
  src/python/pants/backend/go/util_rules/goroot.py
  src/python/pants/backend/go/util_rules/goroot_test.py
  src/python/pants/backend/go/util_rules/pkg_analyzer.py
  src/python/pants/backend/go/util_rules/sdk.py
  src/python/pants/core/subsystems/python_bootstrap_test.py
  src/python/pants/core/util_rules/asdf.py
  src/python/pants/core/util_rules/asdf_test.py
Labels: lang-go, category:new feature

#16257 Prepare `2.13.0rc0`.
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#16273 [Internal] `run_deploy_jar` no longer needs to re-download the JDK
  src/python/pants/core/goals/run.py
  src/python/pants/jvm/run_deploy_jar.py
Labels: category:internal

#16172 Split logic into DynamicRemoteOptions.from_option into different code paths
  src/python/pants/option/global_options.py
  src/python/pants/option/global_options_test.py
Labels: category:internal

#16192 Allow using `--import` option with Autoflake
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/autoflake/subsystem.py
  src/python/pants/option/option_types.py
Labels: needs-cherrypick, category:bugfix

#16267 Dont use PEX as an API to fix `ModuleNotFoundError` for `--debug-adapter` (Cherry-pick of #16263)
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/subsystems/debugpy.lock
  src/python/pants/backend/python/subsystems/debugpy.py
Labels: category:bugfix

#16275 Allow using `--import` option with Autoflake (Cherry-pick of #16192)
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/autoflake/subsystem.py
  src/python/pants/option/option_types.py
Labels: category:bugfix

#16278 Prepare `2.14.0.dev3`.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16277 Add debug output to help to differentiate retry cases
  pants.toml
  src/rust/engine/src/context.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#16276 Improve mypy runs by adding the "incremental" mypy cache
  src/python/pants/backend/codegen/protobuf/python/rules.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:performance

#16285 Upgrade Pex to 2.1.100.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#16287 Upgrade Pex to 2.1.100. (Cherry-pick of #16285)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#16284 Fix GCF Handler documentation.
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
Labels: category:documentation

#16200 [internal] Shell completion support
  build-support/bin/generate_completions.py
Labels: category:internal

#16264 Explicitly add directory entries to resources JARs
  src/python/pants/jvm/resources.py
  src/python/pants/jvm/resources_test.py
Labels: category:bugfix

#16296 Explicitly add directory entries to resources JARs (Cherry-pick of #16264)
  src/python/pants/jvm/resources.py
  src/python/pants/jvm/resources_test.py
Labels: category:bugfix

#16297 Upgrade Pex to 2.1.101.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#16281 Enable `[python-infer].unowned_dependency_behavior="warning"` by default.
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
Labels: category:user api change

#16295 Explicitly add directory entries to resources JARs (Cherry-pick of #16264)
  src/python/pants/jvm/resources.py
  src/python/pants/jvm/resources_test.py
Labels: category:bugfix

#16282 consume inits part of package object within the inner scope
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: category:bugfix

#16294 Don't break builds when pants.log upload fails
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal
