Repository pantsbuild/pants, pull requests merged in 2022-09, with the labels that each got.

#16734 go: check that main packages are actually called `main`
  src/python/pants/backend/go/goals/package_binary.py
Labels: category:internal

#16726 Minor performance optimizations in `rule_graph` and `graph`
  src/rust/engine/Cargo.lock
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/rule_graph/Cargo.toml
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/rule_graph/src/rules.rs
Labels: category:internal

#16732 Prepare 2.13.0rc3
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#16731 Prepare 2.12.1
  src/python/pants/notes/2.12.x.md
Labels: category:internal

#16725 Add support for inferring dependencies used in type context bounds (Cherry-pick of #16709)
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: category:bugfix

#16736 Optimize struct sizes to reduce allocation overhead
  src/rust/engine/Cargo.toml
  src/rust/engine/rule_graph/Cargo.toml
  src/rust/engine/workunit_store/Cargo.toml
Labels: category:internal

#16706 List commercial Pants services that optionally supplement community's extensive free tier
  docs/markdown/Getting Help/service-providers.md
Labels: needs-cherrypick, category:documentation

#16747 remove docker containers after execution finishes
  src/rust/engine/process_execution/src/docker.rs
Labels: category:internal

#16746 Replace union hierarchy tricks with direct class traversal (Cherry-pick of #16657)
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/engine/unions.py
  src/python/pants/engine/unions_test.py
Labels: category:internal

#16745 Welcome community members to consider joining team (Cherry-pick of #16681)
  docs/markdown/Getting Help/the-pants-community.md
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#16744 Welcome community members to consider joining team (Cherry-pick of #16681)
  docs/markdown/Getting Help/the-pants-community.md
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#16743 Welcome community members to consider joining team (Cherry-pick of #16681)
  docs/markdown/Getting Help/the-pants-community.md
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#16742 List commercial Pants services that optionally supplement community's extensive free tier (Cherry-pick of #16706)
  docs/markdown/Getting Help/service-providers.md
Labels: category:documentation

#16741 List commercial Pants services that optionally supplement community's extensive free tier (Cherry-pick of #16706)
  docs/markdown/Getting Help/service-providers.md
Labels: category:documentation

#16740 List commercial Pants services that optionally supplement community's extensive free tier (Cherry-pick of #16706)
  docs/markdown/Getting Help/service-providers.md
Labels: category:documentation

#16750 mark another flaky docker test
  src/rust/engine/process_execution/src/docker_tests.rs
Labels: category:internal

#16752 Add `docker_environment` target
  BUILD
  pants.toml
  src/python/pants/core/register.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: category:internal

#16753 Prepare 2.14.0a1
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16757 Don't error when environment targets use plugin fields
  src/python/pants/core/util_rules/environments_integration_test.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/init/engine_initializer.py
Labels: category:internal

#16758 `docker_image` comes from `Process` struct, rather than the `CommandRunner`
  src/python/pants/engine/process.py
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#16717 Allow `@union`s to declare additional types which are provided to implementers
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/internals/scheduler_test.py
  src/python/pants/engine/unions.py
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/rule_graph/src/rules.rs
  src/rust/engine/rule_graph/src/tests.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/python.rs
  src/rust/engine/src/tasks.rs
Labels: category:plugin api change

#16762 Set a docker_image in all docker tests.
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/lib.rs
Labels: category:internal

#16765 Deprecate `Platform.current` in favor of requesting an injected `Platform`
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-codegen.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-lint-goal.md
  docs/markdown/Writing Plugins/rules-api/rules-api-installing-tools.md
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/codegen/protobuf/java/rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/codegen/protobuf/python/rules.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/helm/subsystems/unittest.py
  src/python/pants/backend/helm/util_rules/tool.py
  src/python/pants/backend/helm/util_rules/tool_test.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/project_info/count_loc.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/shell/dependency_inference.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/terraform/tool.py
  src/python/pants/base/deprecated.py
  src/python/pants/base/exception_sink_test.py
  src/python/pants/core/util_rules/external_tool.py
  src/python/pants/engine/platform.py
  src/python/pants/engine/platform_test.py
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: category:plugin api change

#16721 The environment to use becomes a context-specific parameter
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/explorer/graphql/rules.py
  src/python/pants/backend/explorer/server/uvicorn.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/helm/util_rules/tool.py
  src/python/pants/backend/python/dependency_inference/module_mapper.py
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/bsp/protocol.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/deploy.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/package.py
  src/python/pants/core/goals/publish.py
  src/python/pants/core/goals/repl.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/engine/environment.py
  src/python/pants/engine/explorer.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/platform.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/streaming_workunit_handler.py
  src/python/pants/engine/target.py
  src/python/pants/engine/unions.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/init/plugin_resolver.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/dependency_inference/symbol_mapper.py
  src/python/pants/jvm/goals/lockfile.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/python.rs
  src/rust/engine/src/tasks.rs
Labels: category:plugin api change

#16768 2.15.0.dev1 prep - deprecation removal
  src/python/pants/backend/docker/goals/publish.py
  src/python/pants/backend/python/goals/run_pex_binary.py
  src/python/pants/backend/python/goals/run_pex_binary_integration_test.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/base/specs_integration_test.py
  src/python/pants/core/goals/run_integration_test.py
  src/python/pants/core/target_types_test.py
  src/python/pants/engine/internals/options_parsing.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/process.py
  src/python/pants/jvm/test/junit.py
  src/python/pants/option/global_options.py
Labels: category:internal

#16775 Prep release 2.15.0.dev1
  src/python/pants/VERSION
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#16779 docker: lazily initialize docker connection
  src/rust/engine/process_execution/src/docker.rs
Labels: category:bugfix

#16784 Rename `[environments-preview].aliases` to `[environments-preview].names`
  pants.toml
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_integration_test.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/environment.py
Labels: category:internal

#16783 docker: capture output once after container exits
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
Labels: category:bugfix

#16781 docker: support pulling images before execution
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/nailgun/mod.rs
Labels: category:internal

#16761 Fix `PylintPartition` and `MyPyPartition` to not store the transitive closure
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/partition.py
Labels: category:internal

#16764 Wire up Docker command runner
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/src/context.rs
Labels: category:internal

#16789 Prepare 2.13.0
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#16786 Pass the `__local__` environment target to all goals
  src/python/pants/backend/codegen/avro/java/BUILD
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_integration_test.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/environment.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/streaming_workunit_handler.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/init/plugin_resolver.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/testutil/rule_runner.py
Labels: category:internal

#16792 "switched" command runner
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/switched.rs
  src/rust/engine/src/context.rs
Labels: category:internal

#16791 Automatically set `docker_image` for every Process based on current Environment
  src/python/pants/backend/explorer/browser.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/process.py
  src/python/pants/engine/process_test.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/types.rs
Labels: category:internal

#16797 use switched command runner for nailgun
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/src/context.rs
Labels: category:internal

#16796 Skip CI for user list changes
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16793 Add Brand24 to user list.
  build-support/bin/generate_user_list.py
Labels: category:documentation

#16199 Add OpenAPI backend
  src/python/pants/backend/experimental/openapi/BUILD
  src/python/pants/backend/experimental/openapi/__init__.py
  src/python/pants/backend/experimental/openapi/register.py
  src/python/pants/backend/openapi/BUILD
  src/python/pants/backend/openapi/__init__.py
  src/python/pants/backend/openapi/dependency_inference.py
  src/python/pants/backend/openapi/dependency_inference_test.py
  src/python/pants/backend/openapi/goals/BUILD
  src/python/pants/backend/openapi/goals/__init__.py
  src/python/pants/backend/openapi/goals/tailor.py
  src/python/pants/backend/openapi/goals/tailor_test.py
  src/python/pants/backend/openapi/subsystems/BUILD
  src/python/pants/backend/openapi/subsystems/openapi.py
  src/python/pants/backend/openapi/target_types.py
Labels: category:new feature

#16586 Force colors from mypy always, strip in pants when --no-colors
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/check_test.py
Labels: needs-cherrypick, category:new feature

#16804 fix broken shortlinks that invoked "docs:" instead of "doc:"
  docs/markdown/Getting Help/the-pants-community/team.md
  docs/markdown/Writing Plugins/rules-api/rules-api-process.md
Labels: needs-cherrypick, category:documentation

#16802 Add OpenAPI backend as a dependency to the Pants bin
  build-support/bin/generate_docs.py
  src/python/pants/backend/openapi/target_types.py
  src/python/pants/bin/BUILD
Labels: category:internal

#16805 Add IBM, Coinbase, and Astranis case studies
  docs/markdown/Introduction/media.md
Labels: category:documentation

#16808 Force colors from mypy always, strip in pants when --no-colors (Cherry-pick of #16586)
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/check_test.py
Labels: category:new feature

#16815 Prepare `2.15.0.dev2`
  src/python/pants/VERSION
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#16816 Prepare `2.14.0rc0`
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16819 Drop unused `protobuf` dep in `brfs`.
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/brfs/Cargo.toml
Labels: category:internal

#16799 go: analyze imports paths by module to enable multiple go_mod targets (Cherry pick of #16386)
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/experimental/go/register.py
  src/python/pants/backend/go/dependency_inference.py
  src/python/pants/backend/go/dependency_inference_test.py
  src/python/pants/backend/go/goals/debug_goals.py
  src/python/pants/backend/go/goals/package_binary.py
  src/python/pants/backend/go/goals/tailor.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/target_type_rules_test.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/binary.py
  src/python/pants/backend/go/util_rules/go_mod.py
  src/python/pants/engine/target.py
Labels: category:bugfix

#16801 docker: cache containers for re-use by subsequent build actions
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
Labels: category:internal

#16776 Add support for add-trailing-comma tool
  build-support/bin/_generate_all_lockfiles_helper.py
  build-support/bin/generate_docs.py
  src/python/pants/backend/experimental/python/lint/add_trailing_comma/BUILD
  src/python/pants/backend/experimental/python/lint/add_trailing_comma/__init__.py
  src/python/pants/backend/experimental/python/lint/add_trailing_comma/register.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/lint/add_trailing_comma/BUILD
  src/python/pants/backend/python/lint/add_trailing_comma/__init__.py
  src/python/pants/backend/python/lint/add_trailing_comma/add_trailing_comma.lock
  src/python/pants/backend/python/lint/add_trailing_comma/rules.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules_integration_test.py
  src/python/pants/backend/python/lint/add_trailing_comma/skip_field.py
  src/python/pants/backend/python/lint/add_trailing_comma/subsystem.py
  src/python/pants/bin/BUILD
Labels: category:new feature

#16811 fix broken shortlinks that invoked "docs:" instead of "doc:" (Cherry-pick of #16804)
  docs/markdown/Getting Help/the-pants-community/team.md
  docs/markdown/Writing Plugins/rules-api/rules-api-process.md
Labels: category:documentation

#16810 fix broken shortlinks that invoked "docs:" instead of "doc:" (Cherry-pick of #16804)
  docs/markdown/Getting Help/the-pants-community/team.md
  docs/markdown/Writing Plugins/rules-api/rules-api-process.md
Labels: category:documentation

#16809 fix broken shortlinks that invoked "docs:" instead of "doc:" (Cherry-pick of #16804)
  docs/markdown/Getting Help/the-pants-community/team.md
  docs/markdown/Writing Plugins/rules-api/rules-api-process.md
Labels: category:documentation

#16814 Add IBM, Coinbase, and Astranis case studies (Cherry-pick of #16805)
  docs/markdown/Introduction/media.md
Labels: category:documentation

#16813 Add IBM, Coinbase, and Astranis case studies (Cherry-pick of #16805)
  docs/markdown/Introduction/media.md
Labels: category:documentation

#16812 Add IBM, Coinbase, and Astranis case studies (Cherry-pick of #16805)
  docs/markdown/Introduction/media.md
Labels: category:documentation

#16806 Allow the `check_labels` CI job to run concurrently with other jobs
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16413 go: add basic support for cgo
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/experimental/go/register.py
  src/python/pants/backend/go/goals/debug_goals.py
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/cgo.py
  src/python/pants/backend/go/util_rules/cgo_binaries.py
  src/python/pants/backend/go/util_rules/cgo_pkgconfig.py
  src/python/pants/backend/go/util_rules/cgo_pkgconfig_test.py
  src/python/pants/backend/go/util_rules/cgo_security.py
  src/python/pants/backend/go/util_rules/cgo_security_test.py
  src/python/pants/backend/go/util_rules/cgo_test.py
  src/python/pants/backend/go/util_rules/coverage.py
  src/python/pants/backend/go/util_rules/first_party_pkg.py
  src/python/pants/backend/go/util_rules/first_party_pkg_test.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
Labels: backend: Go, category:new feature

#16839 `MockGet` expects `input_types` kwarg, not `input_type`
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  docs/markdown/Writing Plugins/rules-api/rules-api-testing.md
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/go/goals/BUILD
  src/python/pants/backend/project_info/list_targets_test.py
  src/python/pants/backend/python/goals/coverage_py_test.py
  src/python/pants/backend/python/util_rules/BUILD
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/core/goals/update_build_files_test.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/rules_test.py
  src/python/pants/source/source_root_test.py
  src/python/pants/testutil/rule_runner.py
Labels: category:plugin api change

#16841 Preserve stdio when a local process times out.
  src/python/pants/engine/process_test.py
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
Labels: needs-cherrypick, category:bugfix

#16798 Add retries to NetDownload intrinsic.
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/downloads.rs
Labels: needs-cherrypick, category:new feature

#16834 Allow for `./pants help _underscored_target`
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_integration_test.py
  src/python/pants/help/help_printer.py
Labels: category:internal

#16845 Simplify rule graph setup for the Python and core backends
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/goals/repl_integration_test.py
  src/python/pants/backend/python/register.py
  src/python/pants/backend/python/subsystems/python_native_code.py
  src/python/pants/backend/python/util_rules/dists.py
  src/python/pants/core/goals/package.py
  src/python/pants/core/goals/publish_test.py
  src/python/pants/core/register.py
Labels: category:internal

#16795 Add `_environment` field to `python_test`
  src/python/pants/backend/go/util_rules/coverage_test.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: category:internal

#16774 `run` now filters secondary owners, instead of `specs_rules` erroring
  src/python/pants/backend/python/target_types.py
  src/python/pants/base/specs_integration_test.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/engine/target.py
  tests/python/pants_test/integration/prelude_integration_test.py
Labels: category:internal

#16850 docker: upgrade bollard crate for bug fix
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/src/docker.rs
Labels: category:bugfix

#16863 [internal] Add context manager to handle temporary unfreezing of `frozen_after_init` objects
  src/python/pants/util/meta.py
Labels: category:internal

#16864 Increase the timeout for the docker timeout test.
  src/rust/engine/process_execution/src/docker_tests.rs
Labels: category:internal

#16861 Fix equality implementation in ordered_set
  src/python/pants/util/ordered_set.py
  src/python/pants/util/ordered_set_test.py
Labels: category:internal

#16851 `Environment`, `EnvironmentRequest`, and `CompleteEnvironment` now include `Vars` in the name
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  docs/markdown/Writing Plugins/rules-api/rules-api-process.md
  pants.toml
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/codegen/thrift/apache/rules.py
  src/python/pants/backend/codegen/thrift/apache/subsystem.py
  src/python/pants/backend/docker/goals/publish.py
  src/python/pants/backend/docker/goals/run_image.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_build_env.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/go/util_rules/cgo.py
  src/python/pants/backend/go/util_rules/cgo_binaries.py
  src/python/pants/backend/go/util_rules/go_bootstrap.py
  src/python/pants/backend/go/util_rules/go_bootstrap_test.py
  src/python/pants/backend/go/util_rules/sdk.py
  src/python/pants/backend/helm/util_rules/renderer.py
  src/python/pants/backend/helm/util_rules/tool.py
  src/python/pants/backend/python/goals/publish.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/backend/shell/shell_command.py
  src/python/pants/backend/shell/shell_setup.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/bin/daemon_pants_runner.py
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/bin/pants_runner.py
  src/python/pants/bsp/goal.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/repl.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/subsystems/python_bootstrap_test.py
  src/python/pants/core/util_rules/asdf.py
  src/python/pants/core/util_rules/asdf_test.py
  src/python/pants/core/util_rules/subprocess_environment.py
  src/python/pants/engine/desktop.py
  src/python/pants/engine/env_vars.py
  src/python/pants/engine/environment.py
  src/python/pants/engine/environment_test.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/init/options_initializer.py
  src/python/pants/init/plugin_resolver.py
  src/python/pants/jvm/test/junit.py
  src/python/pants/option/global_options.py
  src/python/pants/option/global_options_test.py
  src/python/pants/pantsd/pants_daemon_core.py
  src/python/pants/testutil/rule_runner.py
  tests/python/pants_test/init/test_options_initializer.py
  tests/python/pants_test/init/test_plugin_resolver.py
  tests/python/pants_test/pantsd/test_pants_daemon_core.py
Labels: category:plugin api change

#16735 Introduce new schema for lint plugins
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules_integration_test.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/docker/lint/hadolint/rules_integration_test.py
  src/python/pants/backend/go/lint/vet/rules.py
  src/python/pants/backend/go/lint/vet/rules_integration_test.py
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/goals/lint_test.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/backend/python/lint/bandit/rules.py
  src/python/pants/backend/python/lint/bandit/rules_integration_test.py
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shellcheck/rules_integration_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/util/meta.py
Labels: category:plugin api change

#16840 Environment sensitive options
  BUILD
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_integration_test.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/option/option_types.py
  src/python/pants/option/parser.py
Labels: category:new feature

#16871 [internal] remove `_unfreeze_instance` and replace with `with x._unfrozen()`
  src/python/pants/engine/target.py
  src/python/pants/util/meta.py
  src/python/pants/util/meta_test.py
Labels: category:internal

#16849 docker: log image pulls
  src/rust/engine/process_execution/src/docker.rs
Labels: category:internal

#16870 docker: set platform when pulling images
  src/rust/engine/process_execution/src/docker.rs
Labels: category:internal

#16874 Every `Process` is now platform-specific (impacts remote caching)
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/go/util_rules/sdk.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/process.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#16867 Add `platform` field for Docker environment targets
  src/python/pants/base/BUILD
  src/python/pants/core/util_rules/environments.py
  src/python/pants/engine/internals/platform_rules.py
  src/python/pants/engine/platform.py
  src/python/pants/init/engine_initializer.py
Labels: category:internal

#16875 Coerce `FmtResult` to `LintResult` in a rule
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: category:internal

#16881 Bump test timeouts
  src/python/pants/backend/codegen/thrift/scrooge/java/BUILD
  src/python/pants/backend/helm/util_rules/BUILD
Labels: category:internal

#16880 Preserve stdio when a local process times out. (Cherry-pick of #16841)
  src/python/pants/engine/process_test.py
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
Labels: category:bugfix

#16879 Add retries to NetDownload intrinsic. (Cherry-pick of #16798)
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/downloads.rs
Labels: category:new feature

#16885 Preserve stdio when a local process times out. (Cherry-pick of #16841)
  src/python/pants/engine/process_test.py
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
Labels: category:bugfix

#16888 Don't mention a specific version in the manual install instructions.
  docs/markdown/Contributions/releases/release-process.md
  docs/markdown/Getting Started/getting-started/manual-installation.md
Labels: needs-cherrypick, category:documentation

#16889 Don't mention a specific version in the manual install instructions. (Cherry-pick of #16888)
  docs/markdown/Contributions/releases/release-process.md
  docs/markdown/Getting Started/getting-started/manual-installation.md
Labels: category:documentation

#16884 Add retries to NetDownload intrinsic. (Cherry-pick of #16798)
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/downloads.rs
Labels: category:new feature

#16872 Prefactor `directory.rs` for symlink plumbing
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/src/posixfs_tests.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/snapshot.rs
  src/rust/engine/fs/store/src/snapshot_ops.rs
  src/rust/engine/fs/store/src/snapshot_tests.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:internal

#16876 Load environment variables from Docker image
  src/python/pants/engine/env_vars.py
  src/python/pants/engine/internals/platform_rules.py
  src/python/pants/engine/internals/platform_rules_test.py
  src/python/pants/init/engine_initializer.py
Labels: category:internal

#16890 Remote execution platform properties come from each `Process`
  src/python/pants/backend/codegen/protobuf/java/BUILD
  src/python/pants/backend/helm/dependency_inference/BUILD
  src/python/pants/core/util_rules/environments.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/option/global_options.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#16886 docker: set platform when creating containers
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
Labels: category:internal

#16893 Rust `Process` struct always sets `Platform`
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#16892 Remote execution can be toggled per Environment / `Process`
  src/python/pants/core/util_rules/environments.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#16896 Upgrade `javaparser`, and use a permissive language level to support parsing more code
  3rdparty/jvm/com/github/javaparser/BUILD
  src/python/pants/backend/java/dependency_inference/PantsJavaParserLauncher.java
  src/python/pants/backend/java/dependency_inference/java_parser.lock
  src/python/pants/backend/java/dependency_inference/java_parser.py
Labels: needs-cherrypick, category:bugfix

#16899 docker: mount points were reversed ...
  src/rust/engine/process_execution/src/docker.rs
Labels: category:internal

#16898 Platform for remote execution and caching comes from Python
  src/python/pants/engine/internals/platform_rules.py
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
Labels: category:internal

#16904 Upgrade `javaparser`, and use a permissive language level to support parsing more code (Cherry-pick of #16896)
  3rdparty/jvm/com/github/javaparser/BUILD
  src/python/pants/backend/java/dependency_inference/PantsJavaParserLauncher.java
  src/python/pants/backend/java/dependency_inference/java_parser.lock
  src/python/pants/backend/java/dependency_inference/java_parser.py
Labels: category:bugfix

#16906 Add `_remote_environment` target for remote execution
  src/python/pants/core/register.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/internals/BUILD
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/platform_rules.py
  src/python/pants/engine/internals/platform_rules_test.py
  src/rust/engine/src/externs/process.rs
Labels: category:internal

#16883 Prepare 2.14.0rc1
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16903 Only request source roots for PEP-517 deps that belong on the syspath
  src/python/pants/backend/python/goals/setup_py.py
Labels: needs-cherrypick, category:bugfix

#16917 Only request source roots for PEP-517 deps that belong on the syspath (Cherry-pick of #16903)
  src/python/pants/backend/python/goals/setup_py.py
Labels: category:bugfix

#16919 remove override of register_plugin_field
  src/python/pants/engine/target.py
Labels: needs-cherrypick, category:bugfix

#16923 remove override of register_plugin_field (Cherry pick of #16919)
  src/python/pants/engine/target.py
Labels: category:bugfix

#16914 add "nailgun" to some nailgun error messages
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
Labels: category:internal

#16924 `wait` for killed nailgun processes.
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
Labels: needs-cherrypick, category:bugfix

#16908 Add `extra_platform_properties` field to remote execution environment
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/option/global_options.py
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#16931 Fix venv re-population race.
  src/python/pants/backend/python/util_rules/pex.py
Labels: needs-cherrypick, category:bugfix

#16935 Fix venv re-population race. (Cherry-pick of #16931)
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:bugfix

#16936 Fix venv re-population race. (Cherry-pick of #16931)
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:bugfix

#16938 `wait` for killed nailgun processes. (Cherry-pick of #16924)
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
Labels: category:bugfix

#16826 Add Marcelo to team page, move Josh Reed to Maintainer
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: needs-cherrypick, category:documentation

#16940 A few refactors of `lint.py`
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules_integration_test.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/docker/lint/hadolint/rules_integration_test.py
  src/python/pants/backend/go/lint/vet/rules.py
  src/python/pants/backend/go/lint/vet/rules_integration_test.py
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/goals/lint_test.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/backend/python/lint/bandit/rules.py
  src/python/pants/backend/python/lint/bandit/rules_integration_test.py
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shellcheck/rules_integration_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: category:internal

#16920 Only use remote cache when cache scope is Always or Successful
  src/rust/engine/process_execution/src/remote_cache.rs
  testprojects/src/jvm/BUILD
  tests/python/pants_test/integration/BUILD
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: category:performance

#16930 add `shutdown` method to CommandRunner
  src/rust/engine/process_execution/src/bounded.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/switched.rs
  src/rust/engine/src/context.rs
Labels: category:internal

#16922 Add an optional speculation delay when using a remote cache
  src/python/pants/engine/process.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/subsystems.py
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/nodes.rs
Labels: needs-cherrypick, category:performance

#16951 skip shutting down container cache if Docker was never used
  src/rust/engine/process_execution/src/docker.rs
Labels: category:internal

#16939 `wait` for killed nailgun processes. (Cherry-pick of #16924)
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
Labels: category:bugfix

#16918 Update changelog on docsite with 2.13, 2.14 links
  docs/markdown/Releases/changelog.md
  src/python/pants/notes/2.14.x.md
Labels: needs-cherrypick, category:documentation

#16957 Update changelog on docsite with 2.13 links (cherrypick of #16918)
  docs/markdown/Releases/changelog.md
Labels: category:documentation

#16911 Fix invalid field error message for parametrized fields.
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: needs-cherrypick, category:bugfix

#16944 Allow public `rule_helpers`
  src/python/pants/engine/rules.py
  src/python/pants/engine/rules_test.py
Labels: category:internal

#16954 Renames `SubsystemRule()` to `Subsystem.rules()`
  docs/markdown/Writing Plugins/rules-api/rules-api-subsystems.md
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/engine/rules.py
  src/python/pants/option/subsystem.py
Labels: category:plugin api change

#16956 Add an optional speculation delay when using a remote cache (Cherry-pick of #16922)
  src/python/pants/engine/process.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/subsystems.py
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/nodes.rs
Labels: category:performance

#16948 Allow for attribute lookup in rule parsing
  src/python/pants/core/goals/lint.py
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/internals/rule_visitor_test.py
Labels: category:internal

#16929 Support overriding param types for rule code
  src/python/pants/engine/rules.py
  src/python/pants/engine/rules_test.py
Labels: category:internal

#16955 Add `fallback_environment` for `remote_environment`
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: category:internal

#16970 Fix for hang with redirected stdio.
  src/rust/engine/Cargo.lock
  src/rust/engine/nailgun/Cargo.toml
  src/rust/engine/nailgun/src/server.rs
Labels: needs-cherrypick, category:bugfix

#16973 Fix for hang with redirected stdio. (Cherry-pick of #16970)
  src/rust/engine/Cargo.lock
  src/rust/engine/nailgun/Cargo.toml
  src/rust/engine/nailgun/src/server.rs
Labels: category:bugfix

#16971 Add `fallback_environment` field to `docker_environment` and `local_environment`
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: category:internal

#16972 Fix for hang with redirected stdio. (Cherry-pick of #16970)
  src/rust/engine/Cargo.lock
  src/rust/engine/nailgun/Cargo.toml
  src/rust/engine/nailgun/src/server.rs
Labels: category:bugfix

#16965 Environment-aware subsystems
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/engine/rules.py
  src/python/pants/option/option_types.py
  src/python/pants/option/parser.py
  src/python/pants/option/subsystem.py
Labels: category:new feature

#16966 Prefactor `tffmt` to be friendlier to upcoming changes
  src/python/pants/backend/experimental/terraform/register.py
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/goals/check_test.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt_integration_test.py
  src/python/pants/backend/terraform/partition.py
  src/python/pants/backend/terraform/style.py
Labels: category:internal

#16964 Prefactor lint for upcoming fmt changes
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/style_request.py
  src/python/pants/core/goals/style_request_test.py
Labels: category:internal

#16958 Update changelog on docsite with 2.13, 2.14 links (Cherry-pick of #16918)
  docs/markdown/Releases/changelog.md
  src/python/pants/notes/2.14.x.md
Labels: category:documentation

#16976 Remove bad linebreaks from python-run-goal page.
  docs/markdown/Python/python-goals/python-run-goal.md
Labels: needs-cherrypick, category:documentation

#16981 Remove bad linebreaks from python-run-goal page. (Cherry-pick of #16976)
  docs/markdown/Python/python-goals/python-run-goal.md
Labels: category:documentation

#16982 Remove bad linebreaks from python-run-goal page. (Cherry-pick of #16976)
  docs/markdown/Python/python-goals/python-run-goal.md
Labels: category:documentation

#16975 improve remote cache logging for hit or miss
  src/rust/engine/process_execution/src/remote_cache.rs
Labels: needs-cherrypick, category:documentation, logging

#16993 go: prepend $GOROOT/bin to PATH for tests
  src/python/pants/backend/go/goals/test.py
Labels: needs-cherrypick, backend: Go, category:bugfix

#16997 go: prepend $GOROOT/bin to PATH for tests (Cherry pick of #16993)
  src/python/pants/backend/go/goals/test.py
Labels: backend: Go, category:bugfix

#16984 Make more option values environment-sensitive
  src/python/pants/backend/codegen/thrift/apache/rules.py
  src/python/pants/backend/codegen/thrift/apache/subsystem.py
  src/python/pants/backend/docker/goals/publish.py
  src/python/pants/backend/docker/goals/run_image.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_build_env.py
  src/python/pants/backend/python/goals/publish.py
  src/python/pants/backend/python/subsystems/python_native_code.py
  src/python/pants/backend/python/subsystems/twine.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/backend/shell/shell_command.py
  src/python/pants/backend/shell/shell_setup.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/subprocess_environment.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/subsystems.py
Labels: category:internal

#17001 go/cgo: support compiling C, C++, ObjC, and Fortran sources
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/cgo.py
  src/python/pants/backend/go/util_rules/cgo_test.py
  src/python/pants/backend/go/util_rules/first_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg_test.py
Labels: backend: Go, category:internal

#16977 Add `parametrize()` support for `__defaults__`.
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/defaults_test.py
Labels: needs-cherrypick, category:bugfix

#16986 Improve remote cache logging for hit or miss (Cherry-pick of #16975)
  src/rust/engine/process_execution/src/remote_cache.rs
Labels: category:documentation

#17003 [2.14.x branch] Upgrade Toolchain Pants Plugin to 0.23.0
  pants.toml
Labels: category:internal

#17002 Upgrade Toolchain Pants Plugin to 0.23.0
  pants.toml
Labels: category:internal

#16983 Don't require a `local_environment` target for each platform
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: category:internal

#17006 Fix invalid field error message for parametrized fields. (Cherry-pick of #16911)
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: category:documentation

#17008 Add `parametrize()` support for `__defaults__`. (Cherry-pick of #16977)
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/defaults_test.py
Labels: category:bugfix

#17009 Fix Pantsd not properly invalidating when `CPPFLAGS` and `LDFLAGS` change
  src/python/pants/backend/python/subsystems/python_native_code.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:bugfix

#17010 Fix invalid field error message for parametrized fields. (Cherry-pick of #16911)
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: category:bugfix
