Repository pantsbuild/pants, pull requests merged in 2022-06, with the labels that each got.

#15712 Prepare 2.12.0rc2
  src/python/pants/notes/2.12.x.md
Labels: category:internal

#15714 Fix `--changed-since` with directories unknown to Pants
  src/python/pants/engine/internals/graph.py
  src/python/pants/vcs/changed_integration_test.py
Labels: category:bugfix

#15692 Refactor Dockerfile parsing to be more ergonomic.
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_wrapper_script.py
  src/python/pants/backend/docker/util_rules/dependencies.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: category:internal

#15695 Add `experimental-explorer` builtin goal.
  src/python/pants/engine/explorer.py
  src/python/pants/goal/builtins.py
  src/python/pants/goal/explorer.py
Labels: category:new feature

#15720 Fix `--changed-since` with directories unknown to Pants when `--changed-dependees` is used
  src/python/pants/engine/internals/graph.py
  src/python/pants/vcs/changed_integration_test.py
Labels: category:internal

#15729 Deprecate `--exclude-target-regexp` in favor of `--filter-address-regex`
  src/python/pants/option/global_options.py
Labels: category:user api change

#15725 Revert "Go can use both `file` and `resource` targets (#15663)"
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/util_rules/first_party_pkg.py
Labels: category:user api change

#15733 Fix help for `--process-total-child-memory-usage` and `--process-per-child-memory-usage`
  src/python/pants/option/global_options.py
Labels: needs-cherrypick, category:bugfix

#15732 A dummy GHA job to test our M1 self-hosted runner.
  .github/workflows/m1.yaml
Labels: category:internal

#15730 Correctly describe the origin of invalid specs, e.g. `--paths-from`
  src/python/pants/backend/go/goals/tailor.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/util_rules/go_mod.py
  src/python/pants/backend/project_info/paths.py
  src/python/pants/backend/project_info/peek_test.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/base/specs.py
  src/python/pants/base/specs_parser.py
  src/python/pants/base/specs_test.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
  src/python/pants/engine/internals/engine_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
  src/python/pants/testutil/rule_runner.py
Labels: category:documentation

#15739 Tweak m1 GHA dummy workflow
  .github/workflows/m1.yaml
Labels: category:internal

#15737 Fix help for `--process-total-child-memory-usage` and `--process-per-child-memory-usage` (Cherry-pick of #15733)
  src/python/pants/option/global_options.py
Labels: category:bugfix

#15741 Require keyword arguments for `AddressInput`
  src/python/pants/backend/kotlin/compile/kotlinc_plugins.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/scala/compile/scalac_plugins.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/build_graph/address.py
  src/python/pants/build_graph/address_test.py
  src/python/pants/engine/addresses.py
  src/python/pants/engine/internals/specs_rules.py
Labels: category:plugin api change

#15742 Add `extra_env_vars` field to `experimental_shell_command` target.
  src/python/pants/backend/shell/shell_command.py
  src/python/pants/backend/shell/shell_command_test.py
  src/python/pants/backend/shell/target_types.py
Labels: category:new feature

#15743 Require setting `description_of_origin` with `AddressInput` and `UnparsedAddressInputs`
  src/python/pants/backend/codegen/thrift/scrooge/java/subsystem.py
  src/python/pants/backend/codegen/thrift/scrooge/scala/subsystem.py
  src/python/pants/backend/docker/util_rules/dependencies.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/kotlin/compile/kotlinc_plugins.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/scala/compile/scalac_plugins.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/bsp/spec/base.py
  src/python/pants/build_graph/address.py
  src/python/pants/build_graph/address_test.py
  src/python/pants/engine/addresses.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/target.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/jvm_tool.py
Labels: category:plugin api change

#15745 Change the default `remote_cache_warnings` warnings behavior to `backoff`.
  pants.ci.toml
  src/python/pants/option/global_options.py
Labels: needs-cherrypick, category:user api change

#15744 Record metrics for remote cache store errors
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
Labels: needs-cherrypick, category:bugfix

#15746 Change the default `remote_cache_warnings` warnings behavior to `backoff`. (Cherry-pick of #15745)
  pants.ci.toml
  src/python/pants/option/global_options.py
Labels: category:user api change

#15747 Record metrics for remote cache store errors (Cherry-pick of #15744)
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
Labels: category:bugfix

#15738 Add support for m1 wheel builds in CI.
  .github/workflows/m1.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/_release_helper.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15748 Update release helper to handle the new MacOS ARM64 wheel.
  build-support/bin/_release_helper.py
Labels: category:internal

#15751 Improve error messages for invalid addresses
  src/python/pants/build_graph/address.py
  src/python/pants/build_graph/address_test.py
  src/python/pants/engine/internals/build_files.py
Labels: category:documentation

#15754 Upgrade the Toolchain Pants Plugin to 0.20.0
  pants.toml
Labels: category:internal

#15753 [internal] Upgrade the Toolchain Pants Plugin to 0.20.0
  pants.toml
Labels: category:internal

#15758 Revert "Add initial Sphinx support with `sphinx_project` target (#15512)"
  build-support/bin/_generate_all_lockfiles_helper.py
  build-support/bin/generate_docs.py
  pants.toml
  src/python/pants/backend/experimental/python/docs/__init__.py
  src/python/pants/backend/experimental/python/docs/sphinx/BUILD
  src/python/pants/backend/experimental/python/docs/sphinx/__init__.py
  src/python/pants/backend/experimental/python/docs/sphinx/register.py
  src/python/pants/backend/python/docs/__init__.py
  src/python/pants/backend/python/docs/sphinx/BUILD
  src/python/pants/backend/python/docs/sphinx/__init__.py
  src/python/pants/backend/python/docs/sphinx/rules.py
  src/python/pants/backend/python/docs/sphinx/rules_integration_test.py
  src/python/pants/backend/python/docs/sphinx/sphinx.lock
  src/python/pants/backend/python/docs/sphinx/sphinx_subsystem.py
  src/python/pants/backend/python/docs/sphinx/target_types.py
  src/python/pants/backend/python/docs/sphinx/target_types_test.py
  src/python/pants/bin/BUILD
Labels: category:internal

#15757 Clarify wildcard AddressInput error
  src/python/pants/build_graph/address.py
Labels: category:internal

#15752 [internal] Upgrade the Toolchain Pants Plugin to 0.20.0
  pants.toml
Labels: category:internal

#14227 Add API types and rules to cli help info
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_printer.py
Labels: category:user api change

#15763 Switch `use_nailgun` to use a `BTreeSet`
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#15773 Always ignore paths which are not files, directories, or links.
  src/python/pants/engine/fs_test.py
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/src/posixfs_tests.rs
Labels: needs-cherrypick, category:user api change

#15697 Explorer backend api
  3rdparty/python/BUILD
  3rdparty/python/mypy.lock
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  build-support/bin/_release_helper.py
  pants.toml
  pyproject.toml
  src/python/pants/backend/explorer/BUILD
  src/python/pants/backend/explorer/browser.py
  src/python/pants/backend/explorer/graphql/BUILD
  src/python/pants/backend/explorer/graphql/context.py
  src/python/pants/backend/explorer/graphql/field_types.py
  src/python/pants/backend/explorer/graphql/query/BUILD
  src/python/pants/backend/explorer/graphql/query/root.py
  src/python/pants/backend/explorer/graphql/query/rules.py
  src/python/pants/backend/explorer/graphql/query/targets.py
  src/python/pants/backend/explorer/graphql/rules.py
  src/python/pants/backend/explorer/graphql/setup.py
  src/python/pants/backend/explorer/graphql/subsystem.py
  src/python/pants/backend/explorer/integration_test.py
  src/python/pants/backend/explorer/register.py
  src/python/pants/backend/explorer/rules.py
  src/python/pants/backend/explorer/server/BUILD
  src/python/pants/backend/explorer/server/uvicorn.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:new feature

#15774 Prepare `2.13.0.dev5`.
  src/python/pants/VERSION
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#15767 Add option for max wait before terminating interactive process
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/option/global_options.py
  src/rust/engine/process_execution/src/children.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:new feature

#15782 Update `crossbeam-utils` to `0.8.8`.
  src/rust/engine/Cargo.lock
Labels: needs-cherrypick, category:internal

#15760 `BuildFileAddress` now requires `BuildFileAddressRequest`
  src/python/pants/backend/project_info/filedeps.py
  src/python/pants/build_graph/address.py
  src/python/pants/engine/addresses.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/graph.py
Labels: category:plugin api change

#15759 `_TargetParametrizations` now requires `_TargetParametrizationsRequest`
  src/python/pants/backend/codegen/avro/target_types_test.py
  src/python/pants/backend/codegen/protobuf/target_types_test.py
  src/python/pants/backend/codegen/soap/target_types_test.py
  src/python/pants/backend/codegen/thrift/target_types_test.py
  src/python/pants/backend/go/target_type_rules_test.py
  src/python/pants/backend/helm/target_types_test.py
  src/python/pants/backend/plugin_development/pants_requirements_test.py
  src/python/pants/backend/python/macros/pipenv_requirements_test.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
  src/python/pants/backend/python/macros/python_requirements_test.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/shell/target_types_test.py
  src/python/pants/core/target_types_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/specs_rules.py
Labels: category:plugin api change

#15785 Update `crossbeam-utils` to `0.8.8`. (Cherry-pick of #15782)
  src/rust/engine/Cargo.lock
Labels: category:internal

#15786 Update `crossbeam-utils` to `0.8.8`. (Cherry-pick of #15782)
  src/rust/engine/Cargo.lock
Labels: category:internal

#15787 Fix `[python-infer].inits` and `[python-infer].conftests` to consider `resolve` field
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
Labels: needs-cherrypick, category:bugfix

#15783 Update the `notify` crate to `5.0.0-pre.15`.
  src/rust/engine/Cargo.lock
  src/rust/engine/watch/Cargo.toml
  src/rust/engine/watch/src/lib.rs
Labels: category:internal

#15701 Handle venv path special chars in coursier fetch
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: category:bugfix

#15790 Move `ResolveError` from `pants.base.exceptions` to `pants.build_graph.address`
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/target_type_rules_test.py
  src/python/pants/base/exceptions.py
  src/python/pants/build_graph/address.py
  src/python/pants/engine/addresses.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/specs_rules_test.py
Labels: category:plugin api change

#15789 `WrappedTarget` now requires `WrappedTargetRequest`
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/cc/dependency_inference/rules.py
  src/python/pants/backend/codegen/protobuf/java/dependency_inference.py
  src/python/pants/backend/codegen/protobuf/protobuf_dependency_inference.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/scala/dependency_inference.py
  src/python/pants/backend/codegen/thrift/apache/java/rules.py
  src/python/pants/backend/codegen/thrift/apache/python/rules.py
  src/python/pants/backend/codegen/thrift/dependency_inference.py
  src/python/pants/backend/codegen/thrift/scrooge/rules.py
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/first_party_pkg.py
  src/python/pants/backend/go/util_rules/go_mod.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/helm/dependency_inference/chart.py
  src/python/pants/backend/java/dependency_inference/rules.py
  src/python/pants/backend/kotlin/dependency_inference/rules.py
  src/python/pants/backend/kotlin/test/junit.py
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/util_rules/local_dists.py
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/shell/dependency_inference.py
  src/python/pants/backend/shell/shell_command.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/target.py
  src/python/pants/testutil/rule_runner.py
Labels: category:plugin api change

#12679 [internal] Register `platform_specific_behavior` marker with Pytest
  pyproject.toml
Labels: category:internal

#15794 Fix `[python-infer].inits` and `[python-infer].conftests` to consider `resolve` field (Cherry-pick of #15787)
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
Labels: category:bugfix

#15793 Fix `[python-infer].inits` and `[python-infer].conftests` to consider `resolve` field (Cherry-pick of #15787)
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
Labels: category:bugfix

#15797 Add `description_of_origin` for several places finding Addresses
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/bsp/spec/base.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/jvm/resolve/coursier_fetch.py
Labels: category:internal

#15807 Add Lablup to users list.
  build-support/bin/generate_user_list.py
Labels: category:internal

#15812 Handle anchors in doc_url() correctly.
  build-support/bin/generate_docs.py
  build-support/bin/generate_docs_test.py
Labels: needs-cherrypick, category:internal

#15684 Add optional StringSequenceField.valid_choices
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:plugin api change

#15813 Remove unnecessary `WrappedNode` method indirection
  src/rust/engine/src/nodes.rs
Labels: category:internal

#15799 Add `--debug-adapter` flag to `test` goal
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/register.py
  src/python/pants/backend/python/subsystems/debugpy.lock
  src/python/pants/backend/python/subsystems/debugpy.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/jvm/test/junit.py
Labels: category:user api change

#15823 Handle anchors in doc_url() correctly. (#15812)
  build-support/bin/generate_docs.py
  build-support/bin/generate_docs_test.py
Labels: category:internal

#15828 Move `gshuflin` to Maintainers Emeritus
  MAINTAINERS.md
Labels: category:internal

#15830 Remove flake8-pantsbuild plugin
  3rdparty/python/flake8.lock
  build-support/flake8/.flake8
  pants.toml
Labels: category:internal

#15816 Update docs for redesign of CLI arguments
  docs/markdown/Docker/docker.md
  docs/markdown/Getting Started/getting-started/existing-repositories.md
  docs/markdown/Getting Started/getting-started/initial-configuration.md
  docs/markdown/Getting Started/getting-started/installation.md
  docs/markdown/Go/go-integrations/protobuf-go.md
  docs/markdown/Go/go.md
  docs/markdown/Helm/helm-overview.md
  docs/markdown/Java and Scala/jvm-overview.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Python/python-integrations/awslambda-python.md
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
  docs/markdown/Python/python-integrations/protobuf-python.md
  docs/markdown/Python/python-integrations/thrift-python.md
  docs/markdown/Python/python/python-backend.md
  docs/markdown/Releases/upgrade-tips.md
  docs/markdown/Shell/shell.md
  docs/markdown/Using Pants/advanced-target-selection.md
  docs/markdown/Using Pants/concepts/goals.md
  docs/markdown/Using Pants/concepts/targets.md
  docs/markdown/Using Pants/project-introspection.md
  docs/markdown/Using Pants/troubleshooting.md
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#15837 Switch from warn to warning
  src/python/pants/backend/python/goals/pytest_runner.py
Labels: category:internal

#15838 Use `MultiGet` in Go rule
  src/python/pants/backend/go/util_rules/first_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
Labels: category:internal

#15814 Add `description_of_origin` for Docker address parsing
  src/python/pants/backend/docker/util_rules/dependencies.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
Labels: category:internal

#15818 Fix broken `engine_error` testutil decorator.
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/go/util_rules/third_party_pkg_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
  src/python/pants/testutil/rule_runner.py
Labels: category:internal

#15804 [internal] better align test JVM lockfile support with pytest concepts
  pants-plugins/internal_plugins/test_lockfile_fixtures/collect_fixtures.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/lockfile_fixture.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/rules.py
  src/python/pants/backend/kotlin/BUILD
  src/python/pants/backend/kotlin/compile/kotlinc_test.py
  src/python/pants/backend/kotlin/conftest.py
  src/python/pants/backend/kotlin/test/junit_test.py
  src/python/pants/backend/scala/BUILD
  src/python/pants/backend/scala/compile/scala-library-2.12.test.lock
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/conftest.py
  src/python/pants/bsp/BUILD
  src/python/pants/bsp/conftest.py
  src/python/pants/bsp/protocol_test.py
Labels: category:internal

#15842 Fix broken links to `tailor` documentation
  docs/markdown/Docker/docker.md
  docs/markdown/Getting Started/getting-started/existing-repositories.md
  docs/markdown/Getting Started/getting-started/initial-configuration.md
  docs/markdown/Go/go-integrations/protobuf-go.md
  docs/markdown/Go/go.md
  docs/markdown/Helm/helm-overview.md
  docs/markdown/Java and Scala/jvm-overview.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Python/python-integrations/awslambda-python.md
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
  docs/markdown/Python/python-integrations/protobuf-python.md
  docs/markdown/Python/python-integrations/thrift-python.md
  docs/markdown/Python/python/python-backend.md
  docs/markdown/Shell/shell.md
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#15843 Fix broken links to `tailor` documentation
  docs/markdown/Docker/docker.md
  docs/markdown/Getting Started/getting-started/existing-repositories.md
  docs/markdown/Getting Started/getting-started/initial-configuration.md
  docs/markdown/Go/go-integrations/protobuf-go.md
  docs/markdown/Go/go.md
  docs/markdown/Helm/helm-overview.md
  docs/markdown/Java and Scala/jvm-overview.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Python/python-integrations/awslambda-python.md
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
  docs/markdown/Python/python-integrations/protobuf-python.md
  docs/markdown/Python/python-integrations/thrift-python.md
  docs/markdown/Python/python/python-backend.md
  docs/markdown/Shell/shell.md
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#15852 Update Media page with Pycon
  docs/markdown/Introduction/media.md
Labels: category:internal

#15853 Update Media page with Pycon
  docs/markdown/Introduction/media.md
Labels: category:internal

#15841 add scala option to disable add_dependencies_on_all_siblings
  src/python/pants/backend/scala/subsystems/scala_infer.py
  src/python/pants/backend/scala/target_types.py
Labels: category:user api change

#15854 Remove synchronous remote cache lookup from remote execution
  src/rust/engine/process_execution/src/bounded.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/nodes.rs
Labels: category:performance

#15863 Add `MaybeAddress` for infallible evaluation of `AddressInput`
  src/python/pants/build_graph/address.py
  src/python/pants/engine/addresses.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: category:plugin api change

#15861 Refactor valid field aliases calculation for targets into a classmethod for easier re-use.
  src/python/pants/engine/target.py
Labels: category:internal

#15844 Fix broken links to `tailor` documentation
  docs/markdown/Docker/docker.md
  docs/markdown/Getting Started/getting-started/existing-repositories.md
  docs/markdown/Getting Started/getting-started/initial-configuration.md
  docs/markdown/Go/go-integrations/protobuf-go.md
  docs/markdown/Go/go.md
  docs/markdown/Java and Scala/jvm-overview.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Python/python-integrations/awslambda-python.md
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
  docs/markdown/Python/python-integrations/protobuf-python.md
  docs/markdown/Python/python-integrations/thrift-python.md
  docs/markdown/Python/python/python-backend.md
  docs/markdown/Shell/shell.md
  docs/markdown/Using Pants/concepts/targets.md
  src/python/pants/engine/internals/graph.py
Labels: category:documentation

#15864 Add `skip_invalid_addresses` field to `UnparsedAddressInputs`
  src/python/pants/backend/docker/util_rules/dependencies.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/build_graph/address.py
  src/python/pants/build_graph/address_test.py
  src/python/pants/engine/addresses.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
Labels: category:plugin api change

#15839 Scala parser improvements
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
  src/python/pants/backend/scala/subsystems/scala_infer.py
Labels: category:internal

#15869 Add `@alonsodomin` to maintainers
  MAINTAINERS.md
Labels: category:internal

#15850 Backtrack execution for missing digests to make `eager_fetch=false` more resilient
  pants.toml
  src/python/pants/engine/internals/native_engine.pyi
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/testutil.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/testutil/Cargo.toml
  src/rust/engine/testutil/mock/Cargo.toml
  src/rust/engine/testutil/mock/src/action_cache_service.rs
  src/rust/engine/testutil/mock/src/cas.rs
  src/rust/engine/testutil/mock/src/cas_service.rs
  src/rust/engine/testutil/mock/src/lib.rs
  src/rust/engine/workunit_store/src/metrics.rs
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: category:performance

#15871 Bump to 2.13.0a0
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#15873 Fix reporting of time spent downloading files
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/downloads.rs
  src/rust/engine/src/nodes.rs
Labels: needs-cherrypick, category:bugfix

#15870 [internal] jvm: port remaining tests to use test lockfiles
  pants-plugins/internal_plugins/test_lockfile_fixtures/collect_fixtures.py
  src/python/pants/backend/codegen/protobuf/java/BUILD
  src/python/pants/backend/codegen/protobuf/java/protobuf-java.test.lock
  src/python/pants/backend/codegen/protobuf/java/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/scala/BUILD
  src/python/pants/backend/codegen/protobuf/scala/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/scala/scalapb.test.lock
  src/python/pants/backend/codegen/thrift/apache/java/BUILD
  src/python/pants/backend/codegen/thrift/apache/java/libthrift.test.lock
  src/python/pants/backend/codegen/thrift/apache/java/rules_integration_test.py
  src/python/pants/backend/java/compile/BUILD
  src/python/pants/backend/java/compile/javac_test.py
  src/python/pants/backend/java/compile/joda.test.lock
  src/python/pants/jvm/BUILD
  src/python/pants/jvm/compile_test.py
  src/python/pants/jvm/package/BUILD
  src/python/pants/jvm/package/servlet.test.lock
  src/python/pants/jvm/package/war_test.py
  src/python/pants/jvm/run_deploy_jar_intergration_test.py
  src/python/pants/jvm/scala-library-2.13.test.lock
  src/python/pants/jvm/test/BUILD
  src/python/pants/jvm/test/junit4.test.lock
  src/python/pants/jvm/test/junit5.test.lock
  src/python/pants/jvm/test/junit_test.py
Labels: category:internal

#15875 Release script fixups
  build-support/bin/_release_helper.py
Labels: needs-cherrypick, category:internal

#15880 Scala: should visit ctor args of base type
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: needs-cherrypick, category:bugfix

#15889 Increment the missing-digest backtracking level once per attempt
  src/rust/engine/src/context.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
Labels: needs-cherrypick, category:bugfix

#15891 Scala: mark an object that extends another type as recursive (Cherry pick of #15865)
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/rules_test.py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
  src/python/pants/backend/scala/dependency_inference/symbol_mapper.py
Labels: category:bugfix

#15792 Add unit tests to GraphQL queries
  3rdparty/python/pytest.lock
  pants.toml
  pyproject.toml
  src/python/pants/backend/explorer/graphql/context.py
  src/python/pants/backend/explorer/graphql/query/BUILD
  src/python/pants/backend/explorer/graphql/query/conftest.py
  src/python/pants/backend/explorer/graphql/query/rules.py
  src/python/pants/backend/explorer/graphql/query/rules_test.py
  src/python/pants/backend/explorer/graphql/query/targets.py
  src/python/pants/backend/explorer/graphql/query/targets_test.py
  src/python/pants/backend/explorer/graphql/setup.py
Labels: category:internal

#15898 Silence `[scala-infer].force_add_siblings_as_dependencies` deprecation.
  pants.toml
Labels: needs-cherrypick, category:internal

#15900 Deprecate implicit setting of `--remote-cache-{read,write,eager-fetch}` with `--remote-execution`
  src/python/pants/option/global_options.py
  src/rust/engine/src/context.rs
Labels: category:user api change

#15901 Dedupe `load_bytes_with` calls to a remote Store
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/snapshot_ops.rs
Labels: needs-cherrypick, category:performance

#15903 Allow JVM memory controls to bound the process pool size to less than the process parallelism
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
Labels: needs-cherrypick, category:bugfix

#15836 Add `__defaults__` BUILD file symbol
  docs/markdown/Using Pants/concepts/targets.md
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/defaults_test.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
Labels: category:new feature

#15905 Allow JVM memory controls to bound the process pool size to less than the process parallelism (Cherry-pick of #15903)
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
Labels: category:bugfix

#15906 Upgrade to `nails` `0.13.0` to pick up support for `JDK >=13`. (Cherry-pick of #15899)
  src/rust/engine/Cargo.lock
  src/rust/engine/nailgun/Cargo.toml
  src/rust/engine/process_execution/Cargo.toml
Labels: category:bugfix

#15886 Upgrade default mypy to 0.961 and default pylint to v2.13.9
  3rdparty/python/mypy.lock
  src/python/pants/backend/python/lint/pylint/pylint.lock
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/typecheck/mypy/mypy.lock
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: category:internal

#15912 Prepare `2.11.1rc3`.
  src/python/pants/notes/2.11.x.md
Labels: category:internal

#15913 Prepare `2.12.0rc3`.
  src/python/pants/notes/2.12.x.md
Labels: category:internal

#15920 Release script fixups (Cherry-pick of #15875)
  build-support/bin/_release_helper.py
Labels: category:internal

#15918 Upgrade to `nails` `0.13.0` to pick up support for `JDK >=13`. (Cherry-pick of #15899)
  src/rust/engine/Cargo.lock
  src/rust/engine/nailgun/Cargo.toml
  src/rust/engine/process_execution/Cargo.toml
Labels: category:bugfix

#15919 Silence `[scala-infer].force_add_siblings_as_dependencies` deprecation. (Cherry-pick of #15898)
  pants.toml
Labels: category:internal

#15926 Remove retired releaser(s) from release checks
  build-support/bin/_release_helper.py
Labels: category:internal

#15927 Remove retired releaser(s) from release checks
  build-support/bin/_release_helper.py
Labels: category:internal

#15859 Fix bad "<infallible>" description in invalid addresses error messages
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
Labels: needs-cherrypick, category:bugfix

#15928 Move generic debug adapter settings to dedicated subsystem
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/subsystems/debugpy.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/core/subsystems/debug_adapter.py
Labels: needs-cherrypick, category:internal

#15929 Remove deprecated `--excluded-target-regexp`, `--files-not-found-behavior`, and `--owners-not-found-behavior` global options
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/option/global_options.py
Labels: category:user api change

#15931 Improve performance of file arguments when `--owners-not-found-behavior` not used
  src/python/pants/engine/internals/specs_rules.py
Labels: category:performance

#15932 Clarify deprecation messages for `tailor` and `update-build-files` requiring CLI arguments
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/update_build_files.py
Labels: needs-cherrypick, category:documentation

#15934 Upgrade default iPython to 7.34, which drops Python 3.6
  docs/markdown/Python/python-goals/python-repl-goal.md
  src/python/pants/backend/python/subsystems/ipython.lock
  src/python/pants/backend/python/subsystems/ipython.py
Labels: category:user api change

#15923 Fix outstanding todo for moved fields defaults support.
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/defaults_test.py
Labels: category:internal

#15874 Tests for Docker from arg not a upstream target
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_wrapper_script.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: category:internal

#15876 Plugin fields should propagate to subclassed target types.
  src/python/pants/build_graph/build_configuration.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/engine/unions.py
Labels: category:plugin api change

#15938 Upgrade default iPython to 7.34, which drops Python 3.6 (Cherry-pick of #15934)
  docs/markdown/Python/python-goals/python-repl-goal.md
  src/python/pants/backend/python/subsystems/ipython.lock
  src/python/pants/backend/python/subsystems/ipython.py
Labels: category:user api change

#15936 Fix bad "<infallible>" description in invalid addresses error messages (Cherry-pick of #15859)
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
Labels: category:bugfix

#15937 Clarify deprecation messages for `tailor` and `update-build-files` requiring CLI arguments (Cherry-pick of #15932)
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/update_build_files.py
Labels: category:documentation

#15942 Remove deprecated `[golang].expected_version` in favor of `[golang].minimum_expected_version`
  src/python/pants/backend/go/subsystems/golang.py
Labels: category:user api change

#15943 Update certificate environment variable advice for #14808.
  docs/markdown/Using Pants/restricted-internet-access.md
Labels: needs-cherrypick, category:documentation

#15939 Deprecate `--use-deprecated-directory-cli-args-semantics` and default to false
  pants.toml
  src/python/pants/core/goals/tailor.py
  src/python/pants/engine/internals/scheduler_integration_test.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/option/global_options.py
  tests/python/pants_test/integration/build_ignore_integration_test.py
Labels: category:user api change

#15884 Add repository config option to Docker registries.
  docs/markdown/Docker/tagging-docker-images.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/registries.py
  src/python/pants/backend/docker/registries_test.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/docker/value_interpolation.py
  src/python/pants/option/parser.py
Labels: category:new feature

#15948 Add test debugging doc
  docs/markdown/Python/python-goals/python-test-goal.md
Labels: category:documentation

#15944 Prepare 2.14.0.dev0
  pants.toml
  src/python/pants/VERSION
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/project_info/filter_targets.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#15946 Improve debugpy's capabilities
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/subsystems/debugpy.py
Labels: needs-cherrypick, category:internal

#15952 Add repository config option to Docker registries. (Cherry pick of #15884)
  docs/markdown/Docker/tagging-docker-images.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/registries.py
  src/python/pants/backend/docker/registries_test.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/docker/value_interpolation.py
  src/python/pants/option/parser.py
Labels: category:new feature

#15950 Add codec for ExternalTool known version field
  pants-plugins/internal_plugins/releases/register.py
  src/python/pants/backend/terraform/tool.py
  src/python/pants/core/util_rules/external_tool.py
Labels: category:internal

#15829 Add `--debug-adapter` flag to `run`
  docs/markdown/Python/python-goals/python-run-goal.md
  docs/markdown/Python/python-goals/python-test-goal.md
  src/python/pants/backend/docker/goals/run_image.py
  src/python/pants/backend/go/goals/run_binary.py
  src/python/pants/backend/python/goals/run_pex_binary.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/shell/shell_command.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/jvm/run_deploy_jar.py
Labels: needs-cherrypick, category:new feature

#15956 Upgrade default version of pyupgrade to 2.34.0
  src/python/pants/backend/python/lint/pyupgrade/pyupgrade.lock
  src/python/pants/backend/python/lint/pyupgrade/subsystem.py
Labels: category:user api change

#15955 Remove 2.13.0a0 entries from 2.14.0.dev0 release notes
  src/python/pants/notes/2.14.x.md
Labels: needs-cherrypick, category:internal

#15957 Direct people to a quick form before they join Slack.
  .github/ISSUE_TEMPLATE/config.yml
  docs/markdown/Getting Help/getting-help.md
  docs/markdown/Introduction/testimonials.md
  pants-plugins/internal_plugins/releases/register.py
Labels: category:documentation

#15960 Upgrade default version of black to 22.6.0
  src/python/pants/backend/python/lint/black/black.lock
  src/python/pants/backend/python/lint/black/subsystem.py
Labels: category:user api change

#15967 [internal] add observation metric for REAPI GetActionResult calls
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: category:internal

#15968 Update the docs for `fmt` and test report changes
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
Labels: needs-cherrypick, category:documentation

#15975 [internal] add observation metric for REAPI GetActionResult calls (Cherry pick of #15967)
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: category:internal

#15969 [internal] use CAS BatchReadBlobs API for small blob reads
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/protos/src/conversions.rs
  src/rust/engine/testutil/mock/src/cas_service.rs
Labels: category:internal

#15970 Update the docs for `fmt` and test report changes (Cherry-pick of #15968)
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
Labels: category:documentation

#15971 Update the docs for `fmt` and test report changes (Cherry-pick of #15968)
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
Labels: category:documentation

#15972 Update certificate environment variable advice for #14808. (Cherry-pick of #15943)
  docs/markdown/Using Pants/restricted-internet-access.md
Labels: category:documentation

#15973 Update certificate environment variable advice for #14808. (Cherry-pick of #15943)
  docs/markdown/Using Pants/restricted-internet-access.md
Labels: category:documentation

#15974 Update certificate environment variable advice for #14808. (Cherry-pick of #15943)
  docs/markdown/Using Pants/restricted-internet-access.md
Labels: category:documentation

#15976 Assorted remote metrics fixes. (Cherry-pick of #15914)
  src/python/pants/goal/stats_aggregator.py
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: category:bugfix

#15977 Move generic debug adapter settings to dedicated subsystem (Cherry-pick of #15928)
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/subsystems/debugpy.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/core/subsystems/debug_adapter.py
Labels: category:internal

#15857 Update Python documentation with 2.11 changes
  docs/markdown/Python/python-goals/python-package-goal.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Python/python-integrations/protobuf-python.md
  docs/markdown/Python/python-integrations/pyoxidizer.md
  docs/markdown/Python/python-integrations/thrift-python.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-lint-goal.md
  docs/markdown/Writing Plugins/rules-api/rules-api-installing-tools.md
Labels: needs-cherrypick, category:documentation

#15941 `tailor` and `update-build-files` require specifying CLI arguments
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
  src/python/pants/core/goals/update_build_files.py
Labels: category:user api change

#15980 Improve debugpy's capabilities (Cherry-pick of #15946)
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/subsystems/debugpy.py
Labels: category:internal

#15979 Backtrack through calls from `@rules` to synchronous engine methods
  src/python/pants/base/exceptions.py
  src/python/pants/engine/internals/native_engine.pyi
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/testutil.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/python.rs
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: needs-cherrypick, category:bugfix

#15985 Prepare `2.11.1`.
  src/python/pants/notes/2.11.x.md
Labels: category:internal

#15984 Update Python documentation with 2.11 changes (#15857)
  docs/markdown/Python/python-goals/python-package-goal.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Python/python-integrations/protobuf-python.md
  docs/markdown/Python/python-integrations/pyoxidizer.md
  docs/markdown/Python/python-integrations/thrift-python.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-lint-goal.md
  docs/markdown/Writing Plugins/rules-api/rules-api-installing-tools.md
Labels: category:documentation

#15983 Update Python documentation with 2.11 changes (#15857)
  docs/markdown/Python/python-goals/python-package-goal.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Python/python-integrations/protobuf-python.md
  docs/markdown/Python/python-integrations/pyoxidizer.md
  docs/markdown/Python/python-integrations/thrift-python.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-lint-goal.md
  docs/markdown/Writing Plugins/rules-api/rules-api-installing-tools.md
Labels: category:documentation

#15981 Update Python documentation with 2.11 changes (#15857)
  docs/markdown/Python/python-goals/python-package-goal.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Python/python-integrations/protobuf-python.md
  docs/markdown/Python/python-integrations/pyoxidizer.md
  docs/markdown/Python/python-integrations/thrift-python.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-lint-goal.md
  docs/markdown/Writing Plugins/rules-api/rules-api-installing-tools.md
Labels: category:documentation

#15978 [internal] grpc_util: add layer to capture network-level timing data
  src/rust/engine/Cargo.lock
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/grpc_util/src/lib.rs
  src/rust/engine/grpc_util/src/metrics.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: category:internal

#15988 Add `--debug-adapter` flag to `run` (Cherry-pick of #15829)
  docs/markdown/Python/python-goals/python-run-goal.md
  docs/markdown/Python/python-goals/python-test-goal.md
  src/python/pants/backend/docker/goals/run_image.py
  src/python/pants/backend/go/goals/run_binary.py
  src/python/pants/backend/python/goals/run_pex_binary.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/shell/shell_command.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/jvm/run_deploy_jar.py
Labels: category:new feature

#15037 [internal] terraform: use immutable input for Terraform tool
  src/python/pants/backend/terraform/tool.py
Labels: category:internal

#16002 Bump 2.12 install version
  docs/markdown/Getting Started/getting-started/installation.md
Labels: category:documentation

#15999 [internal] grpc_util: add layer to capture network-level timing data (Cherry-pick of #15978)
  src/rust/engine/Cargo.lock
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/grpc_util/src/lib.rs
  src/rust/engine/grpc_util/src/metrics.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: category:internal

#15998 [internal] terraform: use immutable input for Terraform tool (Cherry-pick of #15037)
  src/python/pants/backend/terraform/tool.py
Labels: category:performance

#16005 Direct people to a quick form before they join Slack. (cherrypick of #15957)
  .github/ISSUE_TEMPLATE/config.yml
  docs/markdown/Getting Help/getting-help.md
  docs/markdown/Introduction/testimonials.md
  pants-plugins/internal_plugins/releases/register.py
Labels: category:internal

#16006 Direct people to a quick form before they join Slack. (cherrypick of #15957)
  .github/ISSUE_TEMPLATE/config.yml
  docs/markdown/Getting Help/getting-help.md
  docs/markdown/Introduction/testimonials.md
  pants-plugins/internal_plugins/releases/register.py
Labels: category:internal
