Repository pantsbuild/pants, pull requests merged in 2022-05, with the labels that each got.

#15292 Fix non-determinism of `package_data` in generated `setup.py` files
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/goals/setup_py_integration_test.py
Labels: category:bugfix

#15224 [internal] Add Memory controls to JVM processes
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/jdk_rules_test.py
  src/python/pants/jvm/subsystems.py
  src/python/pants/option/global_options.py
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
Labels: category:internal

#15294 Fix a bug in the python venv export logic.
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:bugfix

#15298 Prepare 2.11.0.
  src/python/pants/notes/2.11.x.md
Labels: category:internal

#15297 Fix a bug in the python venv export logic. (cherrypick #15294)
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:bugfix

#15299 Fix non-determinism of `package_data` in generated `setup.py` files (Cherry-pick of #15292)
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/goals/setup_py_integration_test.py
Labels: category:bugfix

#15300 Fix non-determinism of `package_data` in generated `setup.py` files (Cherry-pick of #15292)
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/goals/setup_py_integration_test.py
Labels: category:bugfix

#15303 Don't strip source roots when building dists with an existing setup.py
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/goals/setup_py_test.py
Labels: category:bugfix

#15307 Fix a bug in the python venv export logic. (cherrypick of #15294)
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:bugfix

#15304 Eagerly skip tools with default lockfiles in `export-lockfiles` goal
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/subsystems/ipython.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: needs-cherrypick, category:performance

#15306 Deprecate `[golang].expected_version` in favor of more flexible `[golang].minimum_expected_version`
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/go/subsystems/golang_test.py
Labels: category:user api change

#15324 Work around poisoned cache for macOS CI
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15308 Eagerly skip tools with default lockfiles in `export-lockfiles` goal (#15304)
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/subsystems/ipython.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: category:performance

#15329 Work around poisoned cache for macOS CI (#15324)
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15328 Work around poisoned cache for macOS CI (#15324)
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15327 Work around poisoned cache for macOS CI (#15324)
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15320 Remove deprecated traceback formatting argument
  src/rust/engine/src/python.rs
Labels: category:internal

#15331 Error on unowned internal Python dependencies
  pants.toml
  src/python/pants/backend/docker/subsystems/dockerfile_wrapper_script.py
  src/python/pants/backend/terraform/hcl2_parser.py
  src/python/pants/goal/stats_aggregator.py
  testprojects/src/python/native/name.py
Labels: category:internal

#15311 Remove `[test].xml_dir`, `[update-build-files].fix_python_macros`, and `[java-infer].third_party_imports`
  pants.ci.toml
  src/python/pants/backend/java/subsystems/java_infer.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/update_build_files.py
Labels: category:user api change

#15314 Improve error message for resolves x interpreter constraints issues
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
Labels: needs-cherrypick, category:documentation

#15342 Stop caching venv in CI due to poisoned cache
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15317 Upgrade hadolint to 2.10.0 and add linux arm64 support
  src/python/pants/backend/docker/lint/hadolint/rules_integration_test.py
  src/python/pants/backend/docker/lint/hadolint/subsystem.py
Labels: category:user api change

#15343 Stop caching venv in CI due to poisoned cache (#15342)
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15345 Stop caching venv in CI due to poisoned cache (#15342)
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15340 Add `update_env` to `process_execution::local`.
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
Labels: needs-cherrypick, category:plugin api change

#15339 Fix error output of parametrize()
  src/python/pants/engine/internals/parametrize.py
Labels: needs-cherrypick, category:bugfix

#15344 Stop caching venv in CI due to poisoned cache (#15342)
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15335 Add options to turn off `tailor` on a per-language basis
  src/python/pants/backend/codegen/avro/avro_subsystem.py
  src/python/pants/backend/codegen/avro/tailor.py
  src/python/pants/backend/codegen/protobuf/protoc.py
  src/python/pants/backend/codegen/protobuf/tailor.py
  src/python/pants/backend/codegen/soap/soap_subsystem.py
  src/python/pants/backend/codegen/soap/tailor.py
  src/python/pants/backend/codegen/thrift/subsystem.py
  src/python/pants/backend/codegen/thrift/tailor.py
  src/python/pants/backend/docker/goals/tailor.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/go/goals/tailor.py
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/helm/goals/tailor.py
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/java/goals/tailor.py
  src/python/pants/backend/java/subsystems/javac.py
  src/python/pants/backend/kotlin/goals/tailor.py
  src/python/pants/backend/kotlin/subsystems/kotlin.py
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/scala/goals/tailor.py
  src/python/pants/backend/scala/subsystems/scala.py
  src/python/pants/backend/shell/shell_setup.py
  src/python/pants/backend/shell/tailor.py
  src/python/pants/backend/terraform/goals/tailor.py
  src/python/pants/backend/terraform/tool.py
Labels: category:new feature

#15347 BSP compile exposes loose classfiles to allow IntelliJ to invoke tests
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/backend/scala/compile/scalac.py
  src/python/pants/bsp/util_rules/compile.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/jvm/bsp/compile.py
  src/python/pants/jvm/classpath.py
Labels: category:new feature

#15338 Prepare 2.13.0.dev0
  pants.toml
  src/python/pants/VERSION
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#15346 Add `update_env` to `process_execution::local`. (#15340)
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
Labels: category:internal

#15355 softwrap improvements
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: category:internal

#15351 Add `update_env` to `process_execution::local`. (#15340)
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
Labels: category:internal

#15341 Use abspath to sandbox in PATH for docker tool shims.
  src/python/pants/backend/docker/util_rules/docker_binary.py
Labels: needs-cherrypick, category:bugfix

#15349 Fix error output of `parametrize()` (Cherry-pick of #15339)
  src/python/pants/engine/internals/parametrize.py
Labels: category:documentation

#15348 Fix error output of `parametrize()` (Cherry-pick of #15339)
  src/python/pants/engine/internals/parametrize.py
Labels: category:documentation

#15356 Use abspath to sandbox in PATH for docker tool shims. (#15341)
  src/python/pants/backend/docker/util_rules/docker_binary.py
Labels: category:bugfix

#15357 Use abspath to sandbox in PATH for docker tool shims. (#15341)
  src/python/pants/backend/docker/util_rules/docker_binary.py
Labels: category:bugfix

#15309 Eagerly skip tools with default lockfiles in `export-lockfiles` goal (#15304)
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/subsystems/ipython.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: category:performance

#15362 Add the "named args explanation" to other relevant `parametrize` error messages.
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
Labels: needs-cherrypick, category:bugfix

#15361 Add default mapping for pygithub
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:user api change

#15366 Disallow `!` patterns in `build_ignore`.
  src/python/pants/option/global_options.py
Labels: needs-cherrypick, category:documentation

#15363 Fix `tailor` detection of existing `python_requirements` targets
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/goals/tailor_test.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
Labels: needs-cherrypick, category:bugfix

#15364 Improve error message for resolves x interpreter constraints issues (Cherry-pick of #15314)
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
Labels: category:documentation

#15365 Improve error message for resolves x interpreter constraints issues (Cherry-pick of #15314)
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
Labels: category:documentation

#15368 Disallow `!` patterns in `build_ignore`. (Cherry-pick of #15366)
  src/python/pants/option/global_options.py
Labels: category:documentation

#15367 Disallow `!` patterns in `build_ignore`. (Cherry-pick of #15366)
  src/python/pants/option/global_options.py
Labels: category:documentation

#15370 Add the "named args explanation" to other relevant `parametrize` error messages. (Cherry-pick of #15362)
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
Labels: category:bugfix

#15369 Add the "named args explanation" to other relevant `parametrize` error messages. (Cherry-pick of #15362)
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
Labels: category:bugfix

#15372 Fix `tailor` detection of existing `python_requirements` targets (Cherry-pick of #15363)
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/goals/tailor_test.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
Labels: category:bugfix

#15353 Softwrap build-support
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/_generate_all_lockfiles_helper.py
  build-support/bin/_release_helper.py
  build-support/bin/generate_docs.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15352 Add `tailor` for `poetry_requirements` and `pipenv_requirements`
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/goals/tailor_test.py
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:new feature

#15092 [internal] start of cc backend with target types, tailor, and dependency inference
  src/python/pants/backend/cc/BUILD
  src/python/pants/backend/cc/__init__.py
  src/python/pants/backend/cc/dependency_inference/BUILD
  src/python/pants/backend/cc/dependency_inference/__init__.py
  src/python/pants/backend/cc/dependency_inference/rules.py
  src/python/pants/backend/cc/dependency_inference/rules_integration_test.py
  src/python/pants/backend/cc/goals/BUILD
  src/python/pants/backend/cc/goals/__init__.py
  src/python/pants/backend/cc/goals/tailor.py
  src/python/pants/backend/cc/goals/tailor_test.py
  src/python/pants/backend/cc/subsystems/BUILD
  src/python/pants/backend/cc/subsystems/__init__.py
  src/python/pants/backend/cc/subsystems/cc_infer.py
  src/python/pants/backend/cc/target_types.py
  src/python/pants/backend/experimental/cc/BUILD
  src/python/pants/backend/experimental/cc/__init__.py
  src/python/pants/backend/experimental/cc/register.py
Labels: category:internal

#15271 [internal] add mark and fixture for lockfile generation, take #2
  build-support/bin/_release_helper.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/BUILD
  pants-plugins/internal_plugins/test_lockfile_fixtures/__init__.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/lockfile_fixture.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/register.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/rules.py
  pants.toml
  src/python/pants/backend/scala/BUILD
  src/python/pants/backend/scala/compile/BUILD
  src/python/pants/backend/scala/compile/scala-library.test.lock
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/conftest.py
Labels: category:internal

#15374 Support for getting a version string from git.
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/experimental/python/register.py
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/register.py
  src/python/pants/backend/python/subsystems/setuptools_scm.lock
  src/python/pants/backend/python/subsystems/setuptools_scm.py
  src/python/pants/backend/python/subsystems/twine.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/vcs_versioning.py
  src/python/pants/backend/python/util_rules/vcs_versioning_test.py
Labels: category:new feature

#15266 [internal] kotlin: use test lockfiles for kotlinc_test
  pants-plugins/internal_plugins/test_lockfile_fixtures/lockfile_fixture.py
  src/python/pants/backend/kotlin/BUILD
  src/python/pants/backend/kotlin/compile/BUILD
  src/python/pants/backend/kotlin/compile/kotlin-stdlib-with-joda.test.lock
  src/python/pants/backend/kotlin/compile/kotlin-stdlib.test.lock
  src/python/pants/backend/kotlin/compile/kotlinc-allopen.test.lock
  src/python/pants/backend/kotlin/compile/kotlinc_test.py
  src/python/pants/backend/kotlin/conftest.py
Labels: category:internal

#15375 Generalize Docker dep inference for all packageables.
  src/python/pants/backend/docker/goals/package_image_integration_test.py
  src/python/pants/backend/docker/lint/hadolint/rules_integration_test.py
  src/python/pants/backend/docker/register.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_wrapper_script.py
  src/python/pants/backend/docker/subsystems/dockerfile_wrapper_script_test.py
  src/python/pants/backend/docker/util_rules/dependencies.py
  src/python/pants/backend/docker/util_rules/dependencies_test.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
  src/python/pants/core/goals/package.py
Labels: category:bugfix

#15385 Support dependency inference on vcs_version targets.
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/vcs_versioning.py
Labels: category:new feature

#15371 Fix `tailor` detection of existing `python_requirements` targets (Cherry-pick of #15363)
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/goals/tailor_test.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
Labels: category:bugfix

#15389 Improve `help` and error message for `[python-infer].unowned_dependency_behavior` (Cherry-pick of #15334)
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: category:documentation

#15380 Initial support for building dists using mypyc.
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/goals/setup_py_integration_test.py
  src/python/pants/backend/python/subsystems/setuptools_test.py
  src/python/pants/backend/python/typecheck/mypy/BUILD
  src/python/pants/backend/python/typecheck/mypy/mypyc.py
  src/python/pants/backend/python/typecheck/mypy/mypyc_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/register.py
  src/python/pants/backend/python/util_rules/dists.py
  testprojects/src/python/BUILD
  testprojects/src/python/mypyc_fib/BUILD
  testprojects/src/python/mypyc_fib/mypyc_fib/__init__.py
  testprojects/src/python/mypyc_fib/mypyc_fib/fib.py
  testprojects/src/python/mypyc_fib/pyproject.toml
  testprojects/src/python/mypyc_fib/setup.py
Labels: category:new feature

#15390 Index resources in BSP, and expose transitive dependencies in `compile` to allow tests to consume them
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/bsp/rules.py
  src/python/pants/bsp/spec/resources.py
  src/python/pants/bsp/util_rules/lifecycle.py
  src/python/pants/bsp/util_rules/resources.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/jvm/bsp/compile.py
  src/python/pants/jvm/bsp/resources.py
  src/python/pants/jvm/classpath.py
Labels: category:internal

#15391 Improve `help` and error message for `[python-infer].unowned_dependency_behavior` (#15334)
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
Labels: category:documentation

#15393 Prepare the 2.13.0.dev1 release.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#15397 Add `[python-infer].init_files` as more intuitive replacement for `[python-infer].inits`
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/python/pants/backend/python/typecheck/mypy/BUILD
  src/python/pants/backend/python/util_rules/ancestor_files.py
  src/python/pants/backend/python/util_rules/ancestor_files_test.py
Labels: category:user api change

#15383 escape globs in `generate_file_targets`
  src/python/pants/core/target_types_test.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/target.py
Labels: needs-cherrypick, category:bugfix

#15401 Support the `{chroot}` env placeholder for all interactive processes that are not executed in the workspace.
  src/python/pants/core/goals/publish.py
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:bugfix

#15402 Fix `[]` in file names with target generators (#15383)
  src/python/pants/core/target_types_test.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/target.py
Labels: category:bugfix

#15403 Fix `[]` in file names with target generators (#15383)
  src/python/pants/core/target_types_test.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/target.py
Labels: category:bugfix

#15404 Support the `{chroot}` env placeholder for all interactive processes that are not executed in the workspace. (Cherry-pick of #15401)
  src/python/pants/core/goals/publish.py
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#15405 Support the `{chroot}` env placeholder for all interactive processes that are not executed in the workspace. (Cherry-pick of #15401)
  src/python/pants/core/goals/publish.py
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#15373 Require that a target's `interpreter_constraints` are a subset of their dependencies'
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/typecheck/mypy/subsystem_test.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/backend/python/util_rules/interpreter_constraints_test.py
  src/python/pants/backend/python/util_rules/partition.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/target.py
Labels: needs-cherrypick, category:user api change

#15394 Fix `tags` to work with filesystem arguments, `overrides` field, and `python_tests`
  src/python/pants/backend/codegen/export_codegen_goal.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/repl.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/target.py
  src/python/pants/vcs/changed.py
Labels: needs-cherrypick, category:bugfix

#15407 Require that a target's `interpreter_constraints` are a subset of their dependencies' (Cherry-pick of #15373)
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/typecheck/mypy/subsystem_test.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/backend/python/util_rules/interpreter_constraints_test.py
  src/python/pants/backend/python/util_rules/partition.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/target.py
Labels: category:user api change

#15413 Fix `tags` to work with filesystem arguments, `overrides` field, and `python_tests` (Cherry-pick of #15394)
  src/python/pants/backend/codegen/export_codegen_goal.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/repl.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/target.py
  src/python/pants/vcs/changed.py
Labels: category:bugfix

#15412 Fix `tags` to work with filesystem arguments, `overrides` field, and `python_tests` (Cherry-pick of #15394)
  src/python/pants/backend/codegen/export_codegen_goal.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/repl.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/target.py
  src/python/pants/vcs/changed.py
Labels: category:bugfix

#15414 Fix boolean logic when merging interpreter constraints.
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/subsystems/setuptools_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/backend/python/util_rules/interpreter_constraints_test.py
Labels: category:bugfix

#15424 Upgrade default Protoc version to 3.20.1 (native Apple Silicon support)
  src/python/pants/backend/codegen/protobuf/protoc.py
Labels: category:user api change

#15395 Add clang-format support for the experimental c/cpp plugin
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/cc/lint/BUILD
  src/python/pants/backend/cc/lint/__init__.py
  src/python/pants/backend/cc/lint/clangformat/BUILD
  src/python/pants/backend/cc/lint/clangformat/__init__.py
  src/python/pants/backend/cc/lint/clangformat/clangformat.lock
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/cc/lint/clangformat/rules_integration_test.py
  src/python/pants/backend/cc/lint/clangformat/skip_field.py
  src/python/pants/backend/cc/lint/clangformat/subsystem.py
  src/python/pants/backend/experimental/cc/lint/BUILD
  src/python/pants/backend/experimental/cc/lint/__init__.py
  src/python/pants/backend/experimental/cc/lint/clangformat/BUILD
  src/python/pants/backend/experimental/cc/lint/clangformat/__init__.py
  src/python/pants/backend/experimental/cc/lint/clangformat/register.py
  src/python/pants/backend/python/lint/black/rules.py
Labels: category:new feature

#15417 Support for sharding tests.
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:new feature

#15427 Add `lint --skip-formatters` option
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: category:new feature

#15423 Move `get_git` deprecation to start in `2.14.0.dev0`
  src/python/pants/base/build_environment.py
Labels: needs-cherrypick, category:plugin api change

#15415 Render compile task progress for BSP
  src/python/pants/bsp/context.py
  src/python/pants/bsp/protocol.py
  src/python/pants/bsp/spec/log.py
  src/python/pants/bsp/spec/notification.py
  src/python/pants/bsp/spec/task.py
  src/python/pants/bsp/util_rules/compile.py
  src/python/pants/bsp/util_rules/resources.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/jvm/bsp/compile.py
Labels: category:internal

#15437 Move `get_git` deprecation to start in `2.14.0.dev0` (Cherry-pick of #15423)
  src/python/pants/base/build_environment.py
Labels: category:plugin api change

#15408 Adds JDK autoconfiguration support to scala BSP metadata setup
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/jvm/jdk_rules.py
Labels: category:new feature, bsp

#15416 Improve error message for `dependencies` on incompatible Python resolves
  src/python/pants/backend/kotlin/test/BUILD
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/goals/repl_integration_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/generate_lockfiles_test.py
Labels: needs-cherrypick, category:documentation

#15434 Split our Linux Python test job into 3 shards.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#15438 Rewrite `changed_integration_test.py`
  BUILD
  src/python/pants/vcs/BUILD
  src/python/pants/vcs/changed_integration_test.py
  testprojects/src/python/BUILD
  testprojects/src/python/python_targets/BUILD
  testprojects/src/python/python_targets/test_binary.py
  testprojects/src/python/python_targets/test_direct_dependee.py
  testprojects/src/python/python_targets/test_library.py
  testprojects/src/python/python_targets/test_library_transitive_dependee.py
  testprojects/src/python/python_targets/test_library_transitive_dependee_2.py
  testprojects/src/python/python_targets/test_unclaimed_src.py
Labels: category:internal

#15447 Prepare `2.9.2`.
  src/python/pants/notes/2.9.x.md
Labels: category:internal

#15446 Prepare `2.8.1`
  src/python/pants/notes/2.8.x.md
Labels: category:internal

#15440 Improve error message for `dependencies` on incompatible Python resolves (Cherry-pick of #15416)
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/goals/repl_integration_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/generate_lockfiles_test.py
Labels: category:documentation

#15441 Upgrade default Protoc version to 3.20.1 (native Apple Silicon support) (Cherry-pick of #15424)
  src/python/pants/backend/codegen/protobuf/protoc.py
Labels: category:user api change

#15442 [internal] Start of JS backend for target types and tailor goal
  src/python/pants/backend/experimental/javascript/BUILD
  src/python/pants/backend/experimental/javascript/__init__.py
  src/python/pants/backend/experimental/javascript/register.py
  src/python/pants/backend/javascript/BUILD
  src/python/pants/backend/javascript/__init__.py
  src/python/pants/backend/javascript/goals/BUILD
  src/python/pants/backend/javascript/goals/__init__.py
  src/python/pants/backend/javascript/goals/tailor.py
  src/python/pants/backend/javascript/goals/tailor_test.py
  src/python/pants/backend/javascript/target_types.py
Labels: category:internal

#15449 Prepare `2.11.1rc0`.
  src/python/pants/notes/2.11.x.md
Labels: category:internal

#15453 Fix lockfile generation for Docker, Terraform, and Clang-format to not require Python backend
  src/python/pants/backend/cc/lint/clangformat/BUILD
  src/python/pants/backend/cc/lint/clangformat/subsystem_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser_test.py
  src/python/pants/backend/experimental/cc/lint/clangformat/register.py
  src/python/pants/backend/experimental/terraform/register.py
  src/python/pants/backend/terraform/dependency_inference_test.py
  src/python/pants/init/BUILD
Labels: needs-cherrypick, category:bugfix

#15450 Prepare `2.12.0rc0`.
  src/python/pants/notes/2.12.x.md
Labels: category:internal

#15462 support relative address syntax for JVM compiler plugin artifacts
  src/python/pants/backend/kotlin/compile/kotlinc_plugins.py
  src/python/pants/backend/kotlin/compile/kotlinc_test.py
  src/python/pants/backend/scala/compile/scalac_plugins.py
  src/python/pants/backend/scala/compile/scalac_test.py
Labels: category:bugfix

#15459 kotlin: the `plugin_id` field on `kotlinc_plugin` target is optional
  src/python/pants/backend/kotlin/target_types.py
Labels: needs-cherrypick, lang-jvm, category:bugfix

#15461 kotlin: remove stray scala references
  src/python/pants/backend/experimental/kotlin/lint/ktlint/register.py
  src/python/pants/backend/kotlin/goals/check.py
Labels: needs-cherrypick, category:internal

#15469 Deprecate `[python].tailor_ignore_solitary_init_files` in favor of more useful `[python].tailor_ignore_empty_init_files`
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/goals/tailor_test.py
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:user api change

#15471 Only infer an __init__.py dep on a python_sources-generated target.
  src/python/pants/backend/python/dependency_inference/rules.py
Labels: category:bugfix

#15472 Upgrade Pex to 2.1.87.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#15474 Upgrade Pex to 2.1.87. (Cherry-pick of #15472)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15473 Upgrade Pex to 2.1.87. (Cherry-pick of #15472)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15476 Prepare the 2.13.0.dev2 release.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#15477 Fix the 2.13.x release notes title.
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#15465 kotlin: remove stray scala references (Cherry-pick of #15461)
  src/python/pants/backend/experimental/kotlin/lint/ktlint/register.py
  src/python/pants/backend/kotlin/goals/check.py
Labels: category:bugfix

#15468 support relative address syntax for JVM compiler plugin artifacts (Cherry-pick of #15462)
  src/python/pants/backend/kotlin/compile/kotlinc_plugins.py
  src/python/pants/backend/kotlin/compile/kotlinc_test.py
  src/python/pants/backend/scala/compile/scalac_plugins.py
  src/python/pants/backend/scala/compile/scalac_test.py
Labels: category:user api change

#15457 Adding file downloading support to asset targets
  src/python/pants/core/register.py
  src/python/pants/core/target_types.py
  src/python/pants/core/target_types_test.py
  src/python/pants/engine/target.py
Labels: category:user api change

#15483 Don't give a subsequent formatter an empty snapshot after skipping
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
Labels: needs-cherrypick, category:bugfix

#15484 Upgrade Pex to 2.1.88.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#15466 kotlin: the `plugin_id` field on `kotlinc_plugin` target is optional (Cherry-pick of #15459)
  src/python/pants/backend/kotlin/target_types.py
Labels: category:bugfix

#15485 Upgrade Pex to 2.1.88. (Cherry-pick of #15484)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15486 Upgrade Pex to 2.1.88. (Cherry-pick of #15484)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#15487 Upgrade internal mypy to 950
  3rdparty/python/mypy.lock
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_module_mapper.py
  src/python/pants/backend/python/typecheck/mypy/mypy.lock
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/publish.py
  src/python/pants/core/goals/style_request.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/target_types.py
  src/python/pants/engine/collection.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/streaming_workunit_handler.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/init/logging.py
  src/python/pants/jvm/test/junit.py
  src/python/pants/option/config_test.py
  src/python/pants/option/option_types.py
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/util/ordered_set.py
  src/python/pants/util/ordered_set_test.py
Labels: category:internal

#15492 Revert "Deprecate `[python].tailor_ignore_solitary_init_files` in favor of more useful `[python].tailor_ignore_empty_init_files` (#15469)"
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/goals/tailor_test.py
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:internal

#15494 jvm: fix incorrect check for root-only `ClasspathEntryRequest` implementations
  src/python/pants/jvm/compile.py
Labels: needs-cherrypick, category:bugfix

#15497 jvm: fix incorrect check for root-only `ClasspathEntryRequest` implementations (Cherry pick of #15494)
  src/python/pants/jvm/compile.py
Labels: category:bugfix

#15496 jvm: fix incorrect check for root-only `ClasspathEntryRequest` implementations (Cherry pick of #15494)
  src/python/pants/jvm/compile.py
Labels: category:bugfix

#15488 don't generate default tool lockfiles
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/jvm/resolve/jvm_tool_test.py
Labels: needs-cherrypick, category:bugfix

#15464 Remove `AbstractTestGenerator` from `pantsbuild.pants.testutil`
  src/python/pants/testutil/test_base.py
Labels: category:plugin api change

#15475 Change `_generator_sources_helper` to use `source: str` rather than `sources: list[str]`
  src/python/pants/backend/python/macros/pipenv_requirements.py
  src/python/pants/backend/python/macros/pipenv_requirements_test.py
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/macros/python_requirements_test.py
  src/python/pants/core/target_types.py
Labels: category:user api change

#15396 `--changed-dependees` no longer runs on sibling targets from same target generator
  src/python/pants/vcs/BUILD
  src/python/pants/vcs/changed.py
  src/python/pants/vcs/changed_integration_test.py
Labels: category:user api change

#15498 don't generate default tool lockfiles (Cherry pick of #15488)
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/jvm/resolve/jvm_tool_test.py
Labels: category:bugfix

#15504 Remove `addressable=` kwarg from `tailor`
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
  src/python/pants/option/BUILD
Labels: category:plugin api change

#15509 Allow turning off `export` of Python tools like `black`
  src/python/pants/backend/cc/lint/clangformat/subsystem.py
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/lint/autoflake/subsystem.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/docformatter/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/isort/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pyupgrade/subsystem.py
  src/python/pants/backend/python/lint/yapf/subsystem.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: category:new feature

#15511 Allow turning off `export` of Python tools like `black` (Cherry-pick of #15509)
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/lint/autoflake/subsystem.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/docformatter/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/isort/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pyupgrade/subsystem.py
  src/python/pants/backend/python/lint/yapf/subsystem.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: category:new feature

#15507 Improve `name=` used for Python requirement target generators with `tailor`
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/goals/tailor_test.py
Labels: needs-cherrypick, category:bugfix

#15521 `go_third_party_package` targets now depend on their `go.mod` and `go.sum`
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/target_type_rules_test.py
Labels: category:user api change

#15523 Don't support generated address syntax with `_generate_file_level_targets`
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/engine/target.py
Labels: category:internal

#15535 Move rules for Specs -> FieldSets to specs_rules.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/specs_rules_test.py
Labels: category:internal

#15534 Remove undocumented CLI file arguments ignore syntax
  src/python/pants/base/specs.py
  src/python/pants/base/specs_parser.py
  src/python/pants/base/specs_parser_test.py
  src/python/pants/build_graph/address.py
  src/python/pants/build_graph/address_test.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/engine/internals/native_engine.pyi
  src/rust/engine/address/src/lib.rs
  src/rust/engine/src/externs/address.rs
Labels: category:user api change

#15547 Tweak docs to include `no-infer-dep` in a few more places
  src/python/pants/backend/python/dependency_inference/rules.py
Labels: category:documentation

#15542 fix not deterministic order of excludes
  src/python/pants/jvm/resolve/common.py
Labels: needs-cherrypick, category:bugfix

#15538 Rename classes in `specs.py` for unification of specs semantics
  src/python/pants/backend/go/goals/tailor.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/util_rules/go_mod.py
  src/python/pants/backend/project_info/peek_test.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/base/specs.py
  src/python/pants/base/specs_parser.py
  src/python/pants/base/specs_parser_test.py
  src/python/pants/base/specs_test.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
  src/python/pants/engine/internals/engine_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
  tests/python/pants_test/integration/graph_integration_test.py
Labels: category:plugin api change

#15546 Fix `tag` filtering with `--changed-dependees`
  src/python/pants/engine/internals/mapper.py
  src/python/pants/vcs/changed.py
  src/python/pants/vcs/changed_integration_test.py
Labels: needs-cherrypick, category:bugfix

#15548 upgrade to Rust v1.61.0
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
  src/rust/engine/src/session.rs
Labels: category:internal

#15556 Add `--unmatched-cli-globs`, which before was controlled by `--owners-not-found-behavior`
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/option/global_options.py
Labels: category:user api change

#15560 Deprecate `--owners-not-found-behavior` and set default to `ignore`
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/option/global_options.py
Labels: category:user api change

#15550 Suggest a UUID when erroring about missing UUID
  src/python/pants/goal/anonymous_telemetry.py
Labels: category:documentation

#15554 Refactor `run_pants()` and `changed_integration_test.py`
  pants
  src/python/pants/base/exception_sink_integration_test.py
  src/python/pants/core/goals/fmt_integration_test.py
  src/python/pants/testutil/BUILD
  src/python/pants/testutil/_process_handler.py
  src/python/pants/testutil/_process_handler_test.py
  src/python/pants/testutil/pants_integration_test.py
  src/python/pants/vcs/changed_integration_test.py
Labels: category:internal

#15552 Rewrite `changed_integration_test.py` (Cherry-pick of #15438)
  BUILD
  src/python/pants/vcs/BUILD
  src/python/pants/vcs/changed_integration_test.py
  testprojects/src/python/BUILD
  testprojects/src/python/python_targets/BUILD
  testprojects/src/python/python_targets/test_binary.py
  testprojects/src/python/python_targets/test_direct_dependee.py
  testprojects/src/python/python_targets/test_library.py
  testprojects/src/python/python_targets/test_library_transitive_dependee.py
  testprojects/src/python/python_targets/test_library_transitive_dependee_2.py
  testprojects/src/python/python_targets/test_unclaimed_src.py
Labels: category:internal

#15505 Support JVM options per tool
  src/python/pants/backend/codegen/avro/java/rules.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/codegen/soap/java/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/jvm/test/junit.py
Labels: category:new feature

#15553 Revert `tags` changes, except for the `python_tests` bug fix
  src/python/pants/backend/codegen/export_codegen_goal.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/repl.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/target.py
  src/python/pants/vcs/changed.py
Labels: category:user api change

#15559 scala: use test lockfiles for most scalac tests
  pants-plugins/internal_plugins/test_lockfile_fixtures/lockfile_fixture.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/rules.py
  src/python/pants/backend/kotlin/compile/kotlinc_test.py
  src/python/pants/backend/scala/compile/acyclic.test.lock
  src/python/pants/backend/scala/compile/joda-time.test.lock
  src/python/pants/backend/scala/compile/multiple-scalac-plugins.test.lock
  src/python/pants/backend/scala/compile/scala-library-2.13.test.lock
  src/python/pants/backend/scala/compile/scalac_test.py
Labels: category:internal

#15479 Apply `--tag` filtering to target-less goals like `count-loc`
  src/python/pants/base/specs.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/specs_rules_test.py
Labels: category:bugfix

#15564 Fix `tag` filtering with `--changed-dependees` (Cherry-pick of #15546)
  src/python/pants/engine/internals/mapper.py
  src/python/pants/vcs/changed.py
  src/python/pants/vcs/changed_integration_test.py
Labels: category:bugfix

#15531 Remove transitive `InterpreterConstraint` merging deprecation
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem_test.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/backend/python/util_rules/interpreter_constraints_test.py
  src/python/pants/backend/python/util_rules/partition.py
  testprojects/src/python/native/BUILD
Labels: category:internal

#15566 Ignore `__pycache__` by default with `--pants-ignore`
  src/python/pants/option/global_options.py
Labels: category:internal

#15567 Fix JVM resource classification and artifact grouping
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resources.py
  src/python/pants/jvm/resources_test.py
Labels: needs-cherrypick, category:bugfix
