Repository pantsbuild/pants, pull requests merged in 2022-11, with the labels that each got.

#17410 Fix various tests that failed on macOS ARM.
  src/python/pants/backend/go/lint/vet/rules_integration_test.py
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
  src/python/pants/backend/python/util_rules/pex_test_utils.py
  src/python/pants/core/util_rules/system_binaries.py
  tests/python/pants_test/integration/pep561_integration_test.py
Labels: category:internal

#17415 Fix `EnvironmentName` used in `test` runs (Cherry-pick of #17412)
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: category:bugfix

#17290 create append-only caches in remote execution
  src/python/pants/option/global_options.py
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
  src/rust/engine/process_execution/src/named_caches.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
Labels: needs-cherrypick, category:internal

#17420 create append-only caches in remote execution (Cherry-pick of #17290)
  src/python/pants/option/global_options.py
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
  src/rust/engine/process_execution/src/named_caches.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
Labels: category:internal

#17417 Fix dep inference from shuint2_tests targets.
  src/python/pants/backend/shell/dependency_inference_test.py
  src/python/pants/backend/shell/target_types.py
Labels: needs-cherrypick, category:bugfix

#17421 Fix dep inference from shuint2_tests targets. (Cherry-pick of #17417)
  src/python/pants/backend/shell/dependency_inference_test.py
  src/python/pants/backend/shell/target_types.py
Labels: category:bugfix

#17423 Fix version templating in `vcs_version` docs
  docs/markdown/Using Pants/generating-version-tags.md
Labels: needs-cherrypick, category:documentation

#17422 Fix dep inference from shuint2_tests targets. (Cherry-pick of #17417)
  src/python/pants/backend/shell/dependency_inference_test.py
  src/python/pants/backend/shell/target_types.py
Labels: category:bugfix

#17425 Fix version templating in `vcs_version` docs (Cherry-pick of #17423)
  docs/markdown/Using Pants/generating-version-tags.md
Labels: category:documentation

#17424 Fix version templating in `vcs_version` docs (Cherry-pick of #17423)
  docs/markdown/Using Pants/generating-version-tags.md
Labels: category:documentation

#17429 Update nuke_if_too_big documentation
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#17430 Update nuke_if_too_big documentation (Cherry-pick of #17429)
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#16614 Merge pytest addopts
  docs/markdown/Python/python-goals/python-test-goal.md
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
Labels: category:bugfix

#17419 Handle duplicate JAR entries in `deploy_jar`
  src/python/pants/backend/experimental/java/register.py
  src/python/pants/backend/experimental/kotlin/register.py
  src/python/pants/backend/experimental/scala/register.py
  src/python/pants/jvm/jar_tool/BUILD
  src/python/pants/jvm/jar_tool/__init__.py
  src/python/pants/jvm/jar_tool/jar_tool.default.lockfile.txt
  src/python/pants/jvm/jar_tool/jar_tool.py
  src/python/pants/jvm/jar_tool/jar_tool_test.py
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/package/deploy_jar_test.py
  src/python/pants/jvm/strip_jar/BUILD
  src/python/pants/jvm/strip_jar/strip_jar.lock
  src/python/pants/jvm/strip_jar/strip_jar.py
  src/python/pants/jvm/target_types.py
Labels: backend: JVM, category:new feature

#17452 Fix typo in docs: debug-adaptor should be debug-adapter
  docs/markdown/Python/python-goals/python-run-goal.md
  docs/markdown/Python/python-goals/python-test-goal.md
Labels: category:documentation

#17453 Fix typo in docs: debug-adaptor should be debug-adapter (Cherry-pick of #17452)
  docs/markdown/Python/python-goals/python-run-goal.md
  docs/markdown/Python/python-goals/python-test-goal.md
Labels: category:documentation

#17457 adds `EnvironmentField` to `pex_binary` and related generators (Cherry-pick of #17435)
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/target_types.py
Labels: category:internal

#17436 [internal] Update toolchain pants plugin to v0.25.0
  pants.toml
Labels: category:internal

#17459 Flip the default for `pull` on `docker_image` to `False`
  src/python/pants/backend/docker/goals/package_image_integration_test.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/target_types.py
Labels: needs-cherrypick, category:bugfix

#17416 A --resolve flag, to specify the resolves to export.
  docs/markdown/Using Pants/setting-up-an-ide.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/generate_lockfiles.py
Labels: category:new feature

#17463 fix pex tests on 2.14.x
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
Labels: category:internal

#17455 [internal][2.15.x branch] Update toolchain pants plugin to v0.25.0
  pants.toml
Labels: category:internal

#17454 [internal][2.14.x branch] Update toolchain pants plugin to v0.25.0
  pants.toml
Labels: category:internal

#17464 upgrade to Rust v1.65.0
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
  src/rust/engine/protos/build.rs
  src/rust/engine/sharded_lmdb/src/lib.rs
  src/rust/engine/testutil/src/lib.rs
Labels: category:internal

#17461 A --resolve flag, to specify the resolves to export. (Cherry-pick of #17416)
  docs/markdown/Using Pants/setting-up-an-ide.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/generate_lockfiles.py
Labels: category:new feature

#17465 Deprecate the old export semantics.
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
Labels: category:user api change

#16844 Plumb symlink support through the Pants engine
  src/python/pants/engine/fs.py
  src/python/pants/engine/fs_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/fs/src/directory_tests.rs
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/snapshot.rs
  src/rust/engine/fs/store/src/snapshot_ops.rs
  src/rust/engine/fs/store/src/snapshot_tests.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/types.rs
Labels: category:bugfix

#17467 Add flake8 plugin to check `textwrap.dedent` usage.
  build-support/flake8/.flake8
  build-support/flake8/dedent_use_checker.py
  src/python/pants/backend/explorer/graphql/query/conftest.py
  src/python/pants/backend/helm/subsystems/post_renderer.py
  src/python/pants/backend/helm/testutil.py
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/backend/shell/shell_command.py
  src/python/pants/bin/pants_loader.py
  src/python/pants/bsp/goal.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/target.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/resolve/coursier_setup.py
  src/python/pants/util/eval.py
Labels: category:internal

#17251 Proposal for supporting Jar shading rules
  src/python/pants/backend/experimental/java/register.py
  src/python/pants/backend/experimental/kotlin/register.py
  src/python/pants/backend/experimental/scala/register.py
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/package/deploy_jar_test.py
  src/python/pants/jvm/package/war.py
  src/python/pants/jvm/package/war_test.py
  src/python/pants/jvm/shading/BUILD
  src/python/pants/jvm/shading/__init__.py
  src/python/pants/jvm/shading/jarjar.default.lockfile.txt
  src/python/pants/jvm/shading/jarjar.py
  src/python/pants/jvm/shading/jarjar.test.lock
  src/python/pants/jvm/shading/rules.py
  src/python/pants/jvm/shading/rules_integration_test.py
  src/python/pants/jvm/shading/rules_test.py
  src/python/pants/jvm/target_types.py
Labels: backend: JVM, category:new feature

#17235 Pyright should grab non-transitive dependencies and make them available in the sandbox
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
Labels: category:bugfix, backend: Python

#17469 Fix propagation of the remote-execution-append-only-caches path
  src/python/pants/engine/internals/scheduler.py
Labels: needs-cherrypick, category:bugfix

#17472 Fix propagation of the remote-execution-append-only-caches path (Cherry-pick of #17469)
  src/python/pants/engine/internals/scheduler.py
Labels: category:bugfix

#17471 Fix poorly understood stdout redirection issue.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/src/snapshot_ops.rs
Labels: needs-cherrypick, category:bugfix

#17473 Fix poorly understood stdout redirection issue. (Cherry-pick of #17471)
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/src/snapshot_ops.rs
Labels: category:bugfix

#17474 Isolate config seed values from the DEFAULT section.
  src/python/pants/option/config.py
  src/python/pants/option/config_test.py
Labels: category:bugfix

#17485 Isolate config seed values from the DEFAULT section. (Cherry-pick of #17474)
  src/python/pants/option/config.py
  src/python/pants/option/config_test.py
Labels: category:bugfix

#17265 Add Docker registries `use_local_alias` configuration option.
  .gitignore
  docs/markdown/Docker/tagging-docker-images.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_integration_test.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/goals/publish.py
  src/python/pants/backend/docker/goals/publish_test.py
  src/python/pants/backend/docker/goals/run_image.py
  src/python/pants/backend/docker/registries.py
  src/python/pants/backend/helm/goals/deploy.py
  src/python/pants/backend/helm/util_rules/post_renderer.py
Labels: category:new feature, backend: Docker

#17460 Flip the default for `pull` on `docker_image` to `False` (Cherry-pick of #17459)
  src/python/pants/backend/docker/goals/package_image_integration_test.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/target_types.py
Labels: category:bugfix

#17487 Filter coarsened targets to only those that are relevant in `pylint` runner rule
  src/python/pants/backend/python/lint/pylint/rules.py
Labels: needs-cherrypick, category:performance

#17479 go: support ".syso" prebuilt object files
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/assembly_integration_test.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/first_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
Labels: backend: Go, category:new feature

#17490 Filter coarsened targets to only those that are relevant in `pylint` runner rule (Cherry-pick of #17487)
  src/python/pants/backend/python/lint/pylint/rules.py
Labels: category:performance

#17488 Symlink site-packages into `pylint` venvs when possible.
  src/python/pants/backend/python/lint/pylint/rules.py
Labels: needs-cherrypick, category:performance

#17484 Ensure correct eq/hash semantics for PythonArtifact.
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/macros/python_artifact.py
  src/python/pants/backend/python/macros/python_artifact_test.py
Labels: category:bugfix

#17493 Clarify how `__defaults__` apply to target generators.
  docs/markdown/Using Pants/concepts/targets.md
Labels: needs-cherrypick, category:documentation

#17498 Clarify how `__defaults__` apply to target generators. (Cherry-pick of #17493)
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#17499 Clarify how `__defaults__` apply to target generators. (Cherry-pick of #17493)
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#17492 Ensure correct eq/hash semantics for PythonArtifact. (Cherry-pick of #17484)
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/macros/python_artifact.py
  src/python/pants/backend/python/macros/python_artifact_test.py
Labels: category:bugfix

#17489 Disambiguate Python module providers by level of ancestry.
  src/python/pants/backend/codegen/utils.py
  src/python/pants/backend/python/dependency_inference/module_mapper.py
  src/python/pants/backend/python/dependency_inference/module_mapper_test.py
Labels: category:new feature

#17500 Add Ponder to list of Pants users.
  build-support/bin/generate_user_list.py
Labels: category:internal

#17365 Ensure lockfile target exists before injecting a dependency to it.
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/macros/common_requirements_rule.py
  src/python/pants/backend/python/macros/pipenv_requirements.py
  src/python/pants/backend/python/macros/pipenv_requirements_test.py
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/macros/python_requirements_test.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/engine/internals/synthetic_targets_test.py
Labels: needs-cherrypick, category:bugfix

#17475 go: introduce `GoBuildOptions` and `cgo_enabled` field
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/experimental/go/register.py
  src/python/pants/backend/go/go_sources/load_go_binary.py
  src/python/pants/backend/go/goals/check.py
  src/python/pants/backend/go/goals/debug_goals.py
  src/python/pants/backend/go/goals/generate.py
  src/python/pants/backend/go/goals/package_binary.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/assembly_integration_test.py
  src/python/pants/backend/go/util_rules/build_opts.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/build_pkg_target_test.py
  src/python/pants/backend/go/util_rules/build_pkg_test.py
  src/python/pants/backend/go/util_rules/cgo_test.py
  src/python/pants/backend/go/util_rules/first_party_pkg.py
  src/python/pants/backend/go/util_rules/first_party_pkg_test.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg_test.py
Labels: backend: Go, category:new feature

#17505 Ensure lockfile target exists before injecting a dependency to it. (Cherry-pick of #17365)
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/macros/common_requirements_rule.py
  src/python/pants/backend/python/macros/pipenv_requirements.py
  src/python/pants/backend/python/macros/pipenv_requirements_test.py
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/macros/python_requirements_test.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/engine/internals/synthetic_targets_test.py
Labels: category:bugfix

#17496 Process output capturing is symlink-aware
  src/python/pants/engine/process_test.py
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/src/posixfs_tests.rs
  src/rust/engine/fs/store/src/snapshot.rs
  src/rust/engine/fs/store/src/snapshot_ops.rs
  src/rust/engine/fs/store/src/snapshot_tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/nodes.rs
Labels: category:new feature

#17334 Add `per_platform` object
  src/python/pants/core/register.py
  src/python/pants/core/target_types.py
  src/python/pants/core/target_types_test.py
Labels: category:new feature

#17491 Symlink site-packages into `pylint` venvs when possible. (Cherry-pick of #17488)
  src/python/pants/backend/python/lint/pylint/rules.py
Labels: category:performance

#17451 Support parsing targets from additional paths not containing BUILD files.
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem_test.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/base/specs.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/synthetic_targets.py
  src/python/pants/engine/internals/synthetic_targets_test.py
Labels: needs-cherrypick, category:bugfix

#17516 Fix memoization of `CoarsenedTarget.closure`
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: needs-cherrypick, category:bugfix

#17513 Support parsing targets from additional paths not containing BUILD files. (Cherry-pick of #17451)
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem_test.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/base/specs.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/synthetic_targets.py
  src/python/pants/engine/internals/synthetic_targets_test.py
Labels: category:bugfix

#17518 Fix memoization of `CoarsenedTarget.closure` (Cherry-pick of #17516)
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:bugfix

#17522 Don't require hardcoded name in python_distribution.provides
  src/python/pants/backend/python/goals/setup_py_test.py
  src/python/pants/backend/python/macros/python_artifact.py
  src/python/pants/backend/python/macros/python_artifact_test.py
  src/python/pants/backend/python/target_types.py
Labels: category:new feature

#17514 Rescue Jar tool source code
  3rdparty/jvm/args4j/BUILD
  3rdparty/jvm/com/google/code/findbugs/BUILD
  3rdparty/jvm/com/google/guava/BUILD
  pants.toml
  src/java/org/pantsbuild/args4j/ArgfileOptionHandler.java
  src/java/org/pantsbuild/args4j/BUILD
  src/java/org/pantsbuild/args4j/BooleanOptionHandler.java
  src/java/org/pantsbuild/args4j/CollectionOptionHandler.java
  src/java/org/pantsbuild/args4j/InvalidCmdLineArgumentException.java
  src/java/org/pantsbuild/args4j/Parser.java
  src/java/org/pantsbuild/args4j/StringArgumentsHandler.java
  src/java/org/pantsbuild/tools/jar/BUILD
  src/java/org/pantsbuild/tools/jar/JarBuilder.java
  src/java/org/pantsbuild/tools/jar/JarEntryCopier.java
  src/java/org/pantsbuild/tools/jar/JarFileUtil.java
  src/java/org/pantsbuild/tools/jar/Main.java
  src/python/pants/jvm/jar_tool/BUILD
  src/python/pants/jvm/jar_tool/jar_tool.default.lockfile.txt
  src/python/pants/jvm/jar_tool/jar_tool.lock
  src/python/pants/jvm/jar_tool/jar_tool.py
Labels: backend: JVM, category:internal

#17495 Skip loading of local cache data when possible
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/src/lib.rs
Labels: category:performance

#17524 Skip loading of local cache data when possible (Cherry-pick of #17495)
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/src/lib.rs
Labels: category:performance

#17525 Persist digests before emitting them in `fs_util`
  src/rust/engine/fs/fs_util/src/main.rs
Labels: category:bugfix

#17527 Fix line breaks in a docs page.
  docs/markdown/Python/python/python-third-party-dependencies.md
  docs/markdown/Using Pants/restricted-internet-access.md
Labels: category:documentation

#17528 Fix line breaks in a docs page. (Cherry-pick of #17527)
  docs/markdown/Python/python/python-third-party-dependencies.md
  docs/markdown/Using Pants/restricted-internet-access.md
Labels: category:documentation

#17529 Fix line breaks in a docs page. (Cherry-pick of #17527)
  docs/markdown/Python/python/python-third-party-dependencies.md
  docs/markdown/Using Pants/restricted-internet-access.md
Labels: category:documentation

#17523 Fix leftover `todo!()`
  src/python/pants/engine/fs.py
  src/rust/engine/fs/store/src/snapshot_ops.rs
Labels: category:internal

#17535 Prepare `2.15.0a1`.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#17534 Update team pages for SJ and Dan!
  MAINTAINERS.md
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: needs-cherrypick, category:documentation

#17544 Adds workunit for interactive processes.
  src/rust/engine/src/intrinsics.rs
Labels: category:internal

#17538 Do not try to create `""` output directory in `CreateArchive`
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/archive_test.py
Labels: needs-cherrypick, category:bugfix

#17546 Fix an unactionable `InteractiveProcessRequest` deprecation
  src/python/pants/backend/docker/goals/publish.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/jvm/test/junit.py
Labels: category:bugfix

#17549 Fix loading of `SymlinkNodes` from the `Store`.
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/tests.rs
Labels: category:bugfix

#17547 Do not try to create `""` output directory in `CreateArchive` (Cherry-pick of #17538)
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/archive_test.py
Labels: category:bugfix

#17548 Do not try to create `""` output directory in `CreateArchive` (Cherry-pick of #17538)
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/archive_test.py
Labels: category:bugfix

#17299 Export metadata about a packaged docker image
  docs/markdown/Docker/tagging-docker-images.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/goals/publish_test.py
  src/python/pants/backend/docker/package_types.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
  src/python/pants/backend/helm/util_rules/post_renderer.py
Labels: category:new feature

#17555 Support newer pip versions.
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_cli_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/core/goals/generate_lockfiles.py
Labels: category:new feature

#17560 Add Whisper to Pants user list
  build-support/bin/generate_user_list.py
Labels: category:internal

#17532 Emit a __run.sh into InteractiveProcess sandboxes.
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:new feature

#17561 correct docs: direnv can't save ulimit
  docs/markdown/Using Pants/troubleshooting.md
Labels: category:documentation

#17530 Fix some unused function args in run.py and its test.
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
Labels: category:internal

#17401 Target visibility rules
  pants
  src/python/pants/backend/experimental/visibility/BUILD
  src/python/pants/backend/experimental/visibility/__init__.py
  src/python/pants/backend/experimental/visibility/register.py
  src/python/pants/backend/visibility/BUILD
  src/python/pants/backend/visibility/__init__.py
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
  src/python/pants/backend/visibility/rules.py
  src/python/pants/testutil/pytest_util.py
Labels: category:new feature

#17057 Add debug goals to python
  src/python/pants/backend/experimental/python/register.py
  src/python/pants/backend/project_info/peek.py
  src/python/pants/backend/python/dependency_inference/module_mapper.py
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/python/pants/backend/python/goals/debug_goals.py
  src/python/pants/backend/python/goals/debug_goals_test.py
Labels: category:new feature

#17570 [internal] include experimental visibility backend
  src/python/pants/bin/BUILD
Labels: category:internal

#17567 Created an `NpxToolBase` as an inheritable Subsystem for `nodejs` tools
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/javascript/lint/prettier/subsystem.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/npx_tool.py
  src/python/pants/backend/javascript/subsystems/npx_tool_test.py
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
Labels: category:bugfix, backend: JavaScript

#17572 Support PurePath values in visibility rules.
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:internal

#17568 Update team pages for SJ and Dan! (Cherry-pick of #17534)
  MAINTAINERS.md
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#17566 Allow for `run --debug-adapter` to match breakpoints when source is running in a sandbox
  src/python/pants/backend/python/goals/run_helper.py
Labels: needs-cherrypick, category:bugfix

#17575 Add `environment=` to `experimental_shell_command`.
  src/python/pants/backend/shell/shell_command.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/core/util_rules/environments.py
Labels: needs-cherrypick, category:new feature

#17574 Upgrade default version of golangci-lint to 1.50.1
  src/python/pants/backend/go/lint/golangci_lint/subsystem.py
Labels: category:user api change

#17580 [internal] Ignore empty rule sets.
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:internal

#17579 Add Shantanu Kumar to Contributors list
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:internal

#17586 Add Shantanu Kumar to Contributors list (Cherry-pick of #17579)
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:internal

#17587 Add Shantanu Kumar to Contributors list (Cherry-pick of #17579)
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:internal

#17584 Allow for `run --debug-adapter` to match breakpoints when source is running in a sandbox (Cherry-pick of #17566)
  src/python/pants/backend/python/goals/run_helper.py
Labels: category:bugfix

#17583 Allow for `run --debug-adapter` to match breakpoints when source is running in a sandbox (Cherry-pick of #17566)
  src/python/pants/backend/python/goals/run_helper.py
Labels: category:bugfix

#17591 Fix pex request description for python resolve export.
  src/python/pants/backend/python/goals/export.py
Labels: category:internal

#17595 Prepare `2.16.0.dev0`
  CONTRIBUTORS.md
  pants.toml
  src/python/pants/VERSION
  src/python/pants/backend/python/subsystems/poetry.py
  src/python/pants/base/specs.py
  src/python/pants/base/specs_parser.py
  src/python/pants/engine/process.py
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#17506 Docs: improve docs on handling option values in cli
  docs/markdown/Using Pants/concepts/options.md
Labels: category:documentation

#17588 Visibility rule glob tweaks for `*` and `**`
  src/python/pants/backend/explorer/BUILD
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:bugfix

#17577 Add `Field.use_no_value` bool class var option.
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:new feature

#17510 support Go data race detector
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/build_opts.py
  src/python/pants/backend/go/util_rules/build_opts_test.py
  src/python/pants/backend/go/util_rules/build_pkg.py
Labels: backend: Go, category:new feature

#17582 Move version info/handling to a subdirectory
  pants.toml
  src/python/pants/BUILD
  src/python/pants/_version/BUILD
  src/python/pants/_version/README.md
  src/python/pants/_version/VERSION
  src/python/pants/_version/__init__.py
  src/python/pants/version.py
Labels: category:internal

#17606 go: use debug log level when checking C compiler option support
  src/python/pants/backend/go/util_rules/cgo.py
Labels: backend: Go, category:internal

#17608 Fix broken docs links to manual build instructions
  docs/markdown/Getting Started/getting-started/prerequisites.md
Labels: category:documentation

#17609 Fix broken docs links to manual build instructions (Cherry-pick of #17608)
  docs/markdown/Getting Started/getting-started/prerequisites.md
Labels: category:documentation

#17610 Fix broken docs links to manual build instructions (Cherry-pick of #17608)
  docs/markdown/Getting Started/getting-started/prerequisites.md
Labels: category:documentation

#17563 Mark `pants` as an explicit namespace package (rather than implicit)
  pants.toml
  src/python/pants/__init__.py
  src/python/pants/conftest.py
Labels: needs-cherrypick, category:internal

#17612 Dep rules: improve error messages. report all failures for a target not just one.
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
  src/python/pants/backend/visibility/rules.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/dep_rules.py
  src/python/pants/engine/target.py
Labels: category:internal

#17611 go: allow use of `go_asm.h` assembly header in assembly files
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/assembly_integration_test.py
  src/python/pants/backend/go/util_rules/build_pkg.py
Labels: backend: Go, category:bugfix

#17603 specify local environment for python source analysis goal
  src/python/pants/backend/python/goals/debug_goals.py
Labels: category:bugfix

#17602 Move `pants.backend.explorer` -> `pants.explorer.server` due to being in a dedicated distribution.
  build-support/bin/_release_helper.py
  pants.toml
  src/python/pants/backend/explorer/server/BUILD
  src/python/pants/explorer/server/BUILD
  src/python/pants/explorer/server/browser.py
  src/python/pants/explorer/server/graphql/BUILD
  src/python/pants/explorer/server/graphql/context.py
  src/python/pants/explorer/server/graphql/field_types.py
  src/python/pants/explorer/server/graphql/query/BUILD
  src/python/pants/explorer/server/graphql/query/conftest.py
  src/python/pants/explorer/server/graphql/query/root.py
  src/python/pants/explorer/server/graphql/query/rules.py
  src/python/pants/explorer/server/graphql/query/rules_test.py
  src/python/pants/explorer/server/graphql/query/targets.py
  src/python/pants/explorer/server/graphql/query/targets_test.py
  src/python/pants/explorer/server/graphql/rules.py
  src/python/pants/explorer/server/graphql/setup.py
  src/python/pants/explorer/server/graphql/subsystem.py
  src/python/pants/explorer/server/integration_test.py
  src/python/pants/explorer/server/register.py
  src/python/pants/explorer/server/uvicorn.py
Labels: category:internal

#17620 Dep rules: support for generated targets, such as python requirements.
  build-support/bin/check_inits.py
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:internal

#17623 Dep rules selection bug
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:internal

#17627 Dep rules spec selector syntax
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:internal

#17636 Dep rules glob path fixes
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
  src/python/pants/backend/visibility/rule_types_test.py
  src/python/pants/util/memo.py
  src/python/pants/util/memo_test.py
Labels: category:internal

#17637 Upgrade Pex to 2.1.116.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#17638 go: link with race detector variant of standard library
  src/python/pants/backend/go/go_sources/load_go_binary.py
  src/python/pants/backend/go/goals/package_binary.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/util_rules/build_opts_test.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/import_analysis.py
  src/python/pants/backend/go/util_rules/import_analysis_test.py
  src/python/pants/backend/go/util_rules/link.py
Labels: backend: Go, category:internal

#17635 go: check whether the race detector is supported on the platform
  src/python/pants/backend/go/util_rules/build_opts.py
Labels: backend: Go, category:internal

#17640 shell: add `experimental_test_shell_command` for arbitrary shell-driven tests
  src/python/pants/backend/shell/goals/BUILD
  src/python/pants/backend/shell/goals/test.py
  src/python/pants/backend/shell/goals/test_test.py
  src/python/pants/backend/shell/register.py
  src/python/pants/backend/shell/shell_command_test.py
  src/python/pants/backend/shell/subsystems/BUILD
  src/python/pants/backend/shell/subsystems/shell_test_subsys.py
  src/python/pants/backend/shell/target_types.py
Labels: category:new feature, backend: Shell

#17643 shell: move `tailor` goal into `goals` package
  src/python/pants/backend/shell/goals/__init__.py
  src/python/pants/backend/shell/goals/tailor.py
  src/python/pants/backend/shell/goals/tailor_test.py
  src/python/pants/backend/shell/register.py
Labels: category:internal, backend: Shell

#17644 go: add support for C/C++ memory sanitizer
  src/python/pants/backend/go/goals/debug_goals.py
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/build_opts.py
  src/python/pants/backend/go/util_rules/build_opts_test.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/cgo.py
  src/python/pants/backend/go/util_rules/cgo_test.py
  src/python/pants/backend/go/util_rules/link.py
Labels: backend: Go, category:new feature

#17651 go: address sanitizer support
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/build_opts.py
  src/python/pants/backend/go/util_rules/build_opts_test.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/cgo.py
  src/python/pants/backend/go/util_rules/link.py
Labels: backend: Go, category:new feature

#17646 Remove deprecated Platform.current.
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/core/target_types_test.py
  src/python/pants/engine/platform.py
Labels: category:plugin api change

#17647 Remove deprecated `run --cleanup` option.
  src/python/pants/core/goals/run.py
Labels: category:user api change

#17578 Support `source=None` for `docker_image` targets.
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: category:bugfix

#17650 Fix twine env vars propagation for `publish` goal.
  build-support/bin/check_inits.py
  src/python/pants/backend/python/goals/publish.py
  src/python/pants/backend/python/goals/publish_test.py
  src/python/pants/testutil/__init__.py
Labels: needs-cherrypick, category:bugfix

#17629 Dep rules: fix address mixup for matching with rulesets selector.
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:internal

#17656 [internal] remove lingering `print`
  src/python/pants/backend/python/goals/publish.py
Labels: category:internal

#17648 Prepare the 2.16.0.dev1 release.
  src/python/pants/VERSION
  src/python/pants/notes/2.16.x.md
  src/python/pants/option/global_options.py
Labels: category:internal

#17654 Extend default module mapping for Python 3rd-party dependency inference: pysocks and atlassian-python-api
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:user api change

#17666 Fix wheel reversioning
  build-support/bin/_release_helper.py
Labels: category:internal

#17667 shell: refactor `shell_command.py` to new util_rules subpackage
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
  src/python/pants/backend/shell/goals/test.py
  src/python/pants/backend/shell/register.py
  src/python/pants/backend/shell/util_rules/BUILD
  src/python/pants/backend/shell/util_rules/__init__.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:internal, backend: Shell

#17537 peek: add serialization of PythonArtifact object
  src/python/pants/backend/project_info/peek.py
  src/python/pants/backend/python/macros/python_artifact.py
Labels: category:internal

#17668 shell: refactor `builtin.py` to util_rules
  src/python/pants/backend/shell/util_rules/builtin.py
  src/python/pants/backend/shell/util_rules/shell_command.py
Labels: category:internal, backend: Shell

#17670 shell: move `shell_setup.py` to subsystems
  src/python/pants/backend/shell/dependency_inference.py
  src/python/pants/backend/shell/goals/tailor.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/backend/shell/subsystems/__init__.py
  src/python/pants/backend/shell/subsystems/shell_setup.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
Labels: category:internal, backend: Shell

#17645 Get all tests passing on linux arm64
  build-support/bin/terraform_tool_versions.py
  pubring.kbx
  src/python/pants/backend/experimental/openapi/lint/spectral/register.py
  src/python/pants/backend/openapi/lint/spectral/rules.py
  src/python/pants/backend/openapi/lint/spectral/rules_integration_test.py
  src/python/pants/backend/openapi/lint/spectral/subsystem.py
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules_integration_test.py
  src/python/pants/backend/terraform/tool.py
  src/python/pants/engine/internals/platform_rules_test.py
  src/python/pants/engine/platform.py
Labels: category:internal

#17676 shell: refactor shunit2 subsystem into subsystems package
  src/python/pants/backend/shell/register.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/backend/shell/subsystems/shunit2.py
Labels: category:internal, backend: Shell

#17687 Add overloads to `RuleRunner.write_files` to make it more caller-friendly
  src/python/pants/backend/go/util_rules/first_party_pkg_test.py
  src/python/pants/backend/helm/util_rules/renderer_test.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/subsystem_test.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/terraform/goals/check_test.py
  src/python/pants/testutil/rule_runner.py
Labels: category:internal

#17680 Splits `experimental_shell_command` rules to allow for use by other targets
  src/python/pants/backend/shell/goals/test.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:internal

#17659 Fix twine env vars propagation for `publish` goal. (Cherry-pick of #17650)
  src/python/pants/backend/python/goals/publish.py
  src/python/pants/backend/python/goals/publish_test.py
Labels: category:bugfix

#17658 Fix twine env vars propagation for publish goal (Cherry-pick of #17650)
  src/python/pants/backend/python/goals/publish.py
  src/python/pants/backend/python/goals/publish_test.py
Labels: category:bugfix
