Repository pantsbuild/pants, pull requests merged in 2022-03, with the labels that each got.

#14656 Don't show no-op regex-lint output.
  src/python/pants/core/goals/lint.py
Labels: needs-cherrypick

#13985 [internal] Add Go Protobuf compiler
  src/python/pants/backend/codegen/protobuf/go/BUILD
  src/python/pants/backend/codegen/protobuf/go/__init__.py
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/codegen/protobuf/go/rules_integration_test.py
  src/python/pants/backend/go/util_rules/sdk.py
Labels: 2022-idea

#14683 Reduce memory usage by interning Tasks and RuleGraph entries.
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/concrete_time/Cargo.toml
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/hashing/Cargo.toml
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/rule_graph/Cargo.toml
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/rule_graph/src/rules.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/tasks.rs
  src/rust/engine/workunit_store/Cargo.toml
Labels: needs-cherrypick

#14253 [internal] Add debug output for intermittent abort in `poll_workunits`
  src/rust/engine/src/externs/interface.rs
Labels: needs-cherrypick

#14700 Upgrade Pex to 2.1.70.
  3rdparty/python/lockfiles/user_reqs.txt
  3rdparty/python/requirements.txt
  src/python/pants/backend/python/subsystems/lambdex_lockfile.txt
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick

#14768 Upgrade Pex to 2.1.71.
  3rdparty/python/lockfiles/user_reqs.txt
  3rdparty/python/requirements.txt
  src/python/pants/backend/python/subsystems/lambdex_lockfile.txt
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick

#14778 Improve REPL multiple resolves error to mention `[python].default_resolve`
  src/python/pants/backend/python/goals/repl.py
Labels: needs-cherrypick

#14812 Fix exclusive spawn mechanism for relative paths and working directories
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
Labels: needs-cherrypick

#14819 Fix empty `sys.path` entries causing an error during invalidation glob calculation.
  src/python/pants/option/global_options.py
  src/python/pants/option/global_options_test.py
Labels: needs-cherrypick

#14852 Remove redundancy in how we apply DEFAULTs in config.
  src/python/pants/option/config.py
  src/python/pants/option/config_test.py
  src/python/pants/option/parser.py
Labels: category:internal

#14853 [internal] Softwrapping global options
  src/python/pants/option/global_options.py
Labels: category:internal

#14851 [internal] Second round of softwrapping user-visible strings
  src/python/pants/backend/codegen/avro/target_types.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/target_types.py
  src/python/pants/backend/codegen/thrift/target_types.py
  src/python/pants/backend/debian/target_types.py
  src/python/pants/backend/docker/lint/hadolint/subsystem.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: category:internal

#14855 Ensure in CI that every PR has a category label.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#14862 gitignore Pyenv's .python-version file.
  .gitignore
Labels: category:internal

#14861 [internal] Rename build wheels steps to include architecture
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#14860 [internal] BSP: get third-party deps working for Scala
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/bsp/spec/targets.py
  src/python/pants/bsp/util_rules/targets.py
Labels: category:internal

#14407 [internal] restore experimental codegen backends disabled for 2.10 release
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/experimental/codegen/avro/java/BUILD
  src/python/pants/backend/experimental/codegen/avro/java/__init__.py
  src/python/pants/backend/experimental/codegen/avro/java/register.py
  src/python/pants/backend/experimental/codegen/protobuf/java/BUILD
  src/python/pants/backend/experimental/codegen/protobuf/java/__init__.py
  src/python/pants/backend/experimental/codegen/protobuf/java/register.py
  src/python/pants/backend/experimental/codegen/protobuf/scala/BUILD
  src/python/pants/backend/experimental/codegen/protobuf/scala/__init__.py
  src/python/pants/backend/experimental/codegen/protobuf/scala/register.py
  src/python/pants/backend/experimental/codegen/thrift/apache/java/BUILD
  src/python/pants/backend/experimental/codegen/thrift/apache/java/__init__.py
  src/python/pants/backend/experimental/codegen/thrift/apache/java/register.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/java/BUILD
  src/python/pants/backend/experimental/codegen/thrift/scrooge/java/__init__.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/java/register.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/scala/BUILD
  src/python/pants/backend/experimental/codegen/thrift/scrooge/scala/__init__.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/scala/register.py
  src/python/pants/init/BUILD
Labels: category:internal

#14865 FmtResult now operates on Snapshots
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/gofmt/rules_integration_test.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules_integration_test.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/autoflake/rules_integration_test.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/docformatter/rules_integration_test.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/isort/rules_integration_test.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules_integration_test.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/python/lint/yapf/rules_integration_test.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules_integration_test.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt_integration_test.py
  src/python/pants/backend/terraform/style.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
Labels: category:plugin api change

#14866 [internal] delete non-experimental java protobuf backend
  src/python/pants/backend/codegen/protobuf/java/register.py
Labels: category:internal

#14870 [internal] BSP: stub out remaining scala RPCs
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/backend/scala/bsp/spec.py
Labels: category:internal

#14875 Upgrade Pex to 2.1.73.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#14880 Upgrade Pex to 2.1.73. (Cherry-pick of #14875)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#14871 [internal] BSP: cleanup target resolve and source roots computation
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/bsp/util_rules/targets.py
Labels: category:internal

#14872 Adding DigestTrie/Snapshot diffing
  src/python/pants/engine/fs.py
  src/python/pants/engine/fs_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/src/externs/fs.rs
Labels: category:internal

#14887 Prepare 2.10.0.
  src/python/pants/notes/2.10.x.md
Labels: category:documentation

#14891 Adds `jvm_jdk` field to protobufs when the Scala backend is enabled
  src/python/pants/backend/codegen/protobuf/scala/rules.py
Labels: bug, category:bugfix

#14878 hcl parser 3.0.5
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/hcl2.lock
Labels: category:user api change

#14893 Adds `ClasspathEntryRequest` classification for codegen target generators
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/compile_test.py
Labels: needs-cherrypick, category:bugfix

#14889 Unify glob-matching implementations to fix malformed snapshot created by subsetting
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/src/posixfs_tests.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/snapshot_ops.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
Labels: needs-cherrypick, category:bugfix

#14897 add cache key for all Go SDK invocations
  src/python/pants/backend/go/util_rules/sdk.py
Labels: needs-cherrypick, lang-go, category:bugfix

#14874 add registration for the Go Protobuf backend
  src/python/pants/backend/experimental/codegen/protobuf/go/BUILD
  src/python/pants/backend/experimental/codegen/protobuf/go/__init__.py
  src/python/pants/backend/experimental/codegen/protobuf/go/register.py
Labels: needs-cherrypick, lang-go, category:new feature

#14895 Adds `ClasspathEntryRequest` classification for codegen target generators (Cherry-pick of #14893)
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/compile_test.py
Labels: category:bugfix

#14898 [internal] inject ScalaPB runtime dependency
  src/python/pants/backend/codegen/protobuf/scala/dependency_inference.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/codegen/protobuf/scala/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/scala/subsystem.py
Labels: category:internal

#14906 [internal] BSP: update compile rules to work again
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/bsp/util_rules/compile.py
  src/python/pants/bsp/util_rules/targets.py
Labels: category:internal

#14899 [internal] small codegen backend cleanups
  src/python/pants/backend/codegen/protobuf/scala/register.py
  src/python/pants/backend/experimental/codegen/avro/java/register.py
  src/python/pants/backend/experimental/codegen/protobuf/java/register.py
  src/python/pants/backend/experimental/codegen/protobuf/scala/register.py
  src/python/pants/backend/experimental/codegen/thrift/apache/java/register.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/java/register.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/scala/register.py
Labels: needs-cherrypick, category:internal

#14911 Upgrade Pex to 2.1.74.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#14907 Add Protobuf formatting using buf format
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/register.py
  src/python/pants/backend/codegen/protobuf/lint/buf/skip_field.py
  src/python/pants/backend/codegen/protobuf/lint/buf/subsystem.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/option/option_types.py
Labels: category:new feature

#14915 Revert "Upgrade Pex to 2.1.74. (#14911)"
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:internal

#14914 Prepare 2.9.1
  src/python/pants/notes/2.9.x.md
Labels: category:internal

#14917 Add Protobuf formatting using buf format (Cherry pick of #14907)
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/register.py
  src/python/pants/backend/codegen/protobuf/lint/buf/skip_field.py
  src/python/pants/backend/codegen/protobuf/lint/buf/subsystem.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/option/option_types.py
Labels: category:new feature

#14842 Remove `--use-deprecated-python-macros` in favor of always using target generators
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/goals/tailor_test.py
  src/python/pants/backend/python/macros/caof_utils.py
  src/python/pants/backend/python/macros/caof_utils_test.py
  src/python/pants/backend/python/macros/deprecation_fixers.py
  src/python/pants/backend/python/macros/deprecation_fixers_test.py
  src/python/pants/backend/python/macros/pipenv_requirements_caof.py
  src/python/pants/backend/python/macros/pipenv_requirements_caof_test.py
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_caof.py
  src/python/pants/backend/python/macros/poetry_requirements_caof_test.py
  src/python/pants/backend/python/macros/python_requirements_caof.py
  src/python/pants/backend/python/macros/python_requirements_caof_test.py
  src/python/pants/backend/python/register.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/option/global_options.py
  src/python/pants/testutil/rule_runner.py
Labels: category:user api change

#14919 Prepare 2.12.0.dev0.
  CONTRIBUTORS.md
  pants.toml
  src/python/pants/VERSION
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/scala/subsystems/scalac.py
  src/python/pants/engine/target.py
  src/python/pants/notes/2.12.x.md
  src/python/pants/option/subsystem.py
Labels: category:internal

#14920 Prevent ambiguous LintFilesRequest and LintTargetsRequest names
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: category:internal

#14922 Fix a breakage in building release pexes.
  .github/workflows/test.yaml
  build-support/bin/deploy_to_s3.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#14847 Fix unrecognized field error and `update-build-files` to handle target generator moved fields
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/goals/update_build_files_test.py
  src/python/pants/engine/target.py
Labels: needs-cherrypick, category:bugfix

#14933 Bump timeout for backends integration test
  src/python/pants/init/BUILD
Labels: category:internal

#14929 Write test reports to a standard location under the distdir.
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
Labels: category:user api change

#14850 Merge list values across config files.
  src/python/pants/option/config.py
  src/python/pants/option/config_test.py
  src/python/pants/option/custom_types_test.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
Labels: category:user api change

#14856 Store workunits as a DAG rather than a tree
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/workunit_store/Cargo.toml
  src/rust/engine/workunit_store/src/lib.rs
Labels: category:internal

#14935 Frontload PR label checks to occur before any other jobs.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#14918 [internal] add start of a Kotlin backend
  src/python/pants/backend/kotlin/BUILD
  src/python/pants/backend/kotlin/__init__.py
  src/python/pants/backend/kotlin/goals/BUILD
  src/python/pants/backend/kotlin/goals/__init__.py
  src/python/pants/backend/kotlin/goals/tailor.py
  src/python/pants/backend/kotlin/goals/tailor_test.py
  src/python/pants/backend/kotlin/target_types.py
Labels: category:internal

#14934 Fix missing `check` output by allowing disabled workunits to re-enable themselves
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/src/externs/engine_aware.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/workunit_store/Cargo.toml
  src/rust/engine/workunit_store/src/lib.rs
  src/rust/engine/workunit_store/src/tests.rs
Labels: needs-cherrypick, category:bugfix

#14942 Fix missing `check` output by allowing disabled workunits to re-enable themselves (cherrypick of #14854, #14856, #14934)
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/src/bounded.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
  src/rust/engine/process_execution/src/nailgun/tests.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/externs/engine_aware.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/python.rs
  src/rust/engine/src/scheduler.rs
  src/rust/engine/workunit_store/Cargo.toml
  src/rust/engine/workunit_store/src/lib.rs
  src/rust/engine/workunit_store/src/tests.rs
Labels: category:bugfix

#14946 Fix Pylint config check strings
  src/python/pants/backend/python/lint/pylint/subsystem.py
Labels: needs-cherrypick, category:internal

#14939 [internal] kotlin: add compilation rules
  src/python/pants/backend/kotlin/compile/BUILD
  src/python/pants/backend/kotlin/compile/__init__.py
  src/python/pants/backend/kotlin/compile/kotlinc.py
  src/python/pants/backend/kotlin/compile/kotlinc_test.py
  src/python/pants/backend/kotlin/goals/check.py
  src/python/pants/backend/kotlin/subsystems/BUILD
  src/python/pants/backend/kotlin/subsystems/__init__.py
  src/python/pants/backend/kotlin/subsystems/kotlin.py
Labels: lang-jvm, category:internal

#14930 Fix unrecognized field error and `update-build-files` to handle target generator moved fields (Cherry-pick of #14847)
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/goals/update_build_files_test.py
  src/python/pants/engine/target.py
Labels: category:bugfix

#14947 Fix Pylint config check strings (Cherry-pick of #14946)
  src/python/pants/backend/python/lint/pylint/subsystem.py
Labels: category:bugfix

#14945 Fix typo
  src/python/pants/backend/python/lint/pylint/rules.py
Labels: needs-cherrypick, category:internal

#14944 Make PEX lockfile subsetting incremental
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
Labels: needs-cherrypick, category:performance

#14903 "Unify" `fmt` and `lint` rules for formatters
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules_integration_test.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/gofmt/rules_integration_test.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules_integration_test.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/autoflake/rules_integration_test.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/docformatter/rules_integration_test.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/isort/rules_integration_test.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules_integration_test.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/python/lint/yapf/rules_integration_test.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules_integration_test.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt_integration_test.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: category:plugin api change

#14949 Add support for parsing address parameters to CLI specs parsing
  src/python/pants/base/specs.py
  src/python/pants/base/specs_parser.py
  src/python/pants/base/specs_parser_test.py
  src/python/pants/build_graph/address.py
  src/python/pants/build_graph/address_test.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/init/specs_calculator.py
  src/rust/engine/address/src/lib.rs
  src/rust/engine/src/externs/address.rs
Labels: needs-cherrypick, category:new feature

#14958 Remove dead kotlin glob, and fail for unmatched globs.
  pants.toml
  src/python/pants/backend/kotlin/subsystems/BUILD
Labels: category:internal

#14932 [internal] restore experimental codegen backends disabled for 2.10 release (Cherry-pick of #14407)
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/experimental/codegen/avro/java/BUILD
  src/python/pants/backend/experimental/codegen/avro/java/__init__.py
  src/python/pants/backend/experimental/codegen/avro/java/register.py
  src/python/pants/backend/experimental/codegen/protobuf/java/BUILD
  src/python/pants/backend/experimental/codegen/protobuf/java/__init__.py
  src/python/pants/backend/experimental/codegen/protobuf/java/register.py
  src/python/pants/backend/experimental/codegen/protobuf/scala/BUILD
  src/python/pants/backend/experimental/codegen/protobuf/scala/__init__.py
  src/python/pants/backend/experimental/codegen/protobuf/scala/register.py
  src/python/pants/backend/experimental/codegen/thrift/apache/java/BUILD
  src/python/pants/backend/experimental/codegen/thrift/apache/java/__init__.py
  src/python/pants/backend/experimental/codegen/thrift/apache/java/register.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/java/BUILD
  src/python/pants/backend/experimental/codegen/thrift/scrooge/java/__init__.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/java/register.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/scala/BUILD
  src/python/pants/backend/experimental/codegen/thrift/scrooge/scala/__init__.py
  src/python/pants/backend/experimental/codegen/thrift/scrooge/scala/register.py
  src/python/pants/init/BUILD
Labels: category:internal

#14959 Deprecate not implementing `TargetGenerator` in `GenerateTargetsRequest` implementors.
  src/python/pants/backend/docker/util_rules/dockerfile_test.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/plugin_development/pants_requirements.py
  src/python/pants/backend/python/macros/pipenv_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/terraform/target_gen.py
  src/python/pants/backend/terraform/target_types.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/target.py
Labels: needs-cherrypick, category:plugin api change

#14608 upgrade to Rust v1.59.0
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
  src/rust/engine/address/src/lib.rs
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/graph/src/entry.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/src/externs/engine_aware.rs
  src/rust/engine/src/session.rs
Labels: category:internal

#14963 Fix `./pants --version` for `pantsbuild.pants` PEX
  build-support/bin/_release_helper.py
Labels: needs-cherrypick, category:bugfix

#14970 Upgrade to Pex 2.1.75 for VCS lock support and deadlock fix
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change
