Repository pantsbuild/pants, pull requests merged in 2022-08, with the labels that each got.

#16352 Show advanced options with `help` if there are no basic options
  src/python/pants/help/help_formatter.py
  src/python/pants/help/help_formatter_test.py
Labels: category:documentation

#16361 remove spurious quote mark
  src/python/pants/jvm/dependency_inference/artifact_mapper.py
Labels: category:internal

#16344 [2.12.x branch] Upgrade Toolchain Pants Plugin to 0.21.0
  pants.toml
Labels: category:internal

#16363 Fix source roots docs.
  docs/markdown/Using Pants/concepts/source-roots.md
Labels: needs-cherrypick, category:documentation

#16365 Fix source roots docs. (Cherry-pick of #16363)
  docs/markdown/Using Pants/concepts/source-roots.md
Labels: category:documentation

#16364 Fix source roots docs. (Cherry-pick of #16363)
  docs/markdown/Using Pants/concepts/source-roots.md
Labels: category:documentation

#16366 Fix source roots docs. (Cherry-pick of #16363)
  docs/markdown/Using Pants/concepts/source-roots.md
Labels: category:documentation

#16368 Include Helm chart dependency inference rules
  src/python/pants/backend/helm/goals/lint_test.py
  src/python/pants/backend/helm/goals/package_test.py
  src/python/pants/backend/helm/util_rules/chart.py
  src/python/pants/backend/helm/util_rules/chart_test.py
Labels: category:bugfix

#16343 [2.11.x branch] Upgrade Toolchain Pants Plugin to 0.21.0
  pants.toml
Labels: category:internal

#16314 [internal] Add missing timeout field to target generators
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/java/target_types.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/scala/target_types.py
Labels: needs-cherrypick, category:bugfix

#16372 Add a newline at the end of `paths` output (Cherry-pick of #16302)
  src/python/pants/backend/project_info/paths.py
Labels: category:bugfix

#16370 [Internal] `run_deploy_jar` no longer needs to re-download the JDK (Cherry-pick of #16273)
  src/python/pants/core/goals/run.py
  src/python/pants/jvm/run_deploy_jar.py
Labels: category:internal

#16371 consume inits part of package object within the inner scope (Cherry-pick of #16282)
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: category:bugfix

#16374 Include Chris Livingston in Maintainers Emeritus
  MAINTAINERS.md
Labels: category:internal

#16358 jvm: fix fetching artifacts with non-jar packaging
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
  src/python/pants/jvm/resolve/jvm_tool.py
Labels: category:bugfix

#16350 java/protobuf: add support for grpc-java codegen
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/codegen/protobuf/java/BUILD
  src/python/pants/backend/codegen/protobuf/java/dependency_inference.py
  src/python/pants/backend/codegen/protobuf/java/grpc-java.default.lockfile.txt
  src/python/pants/backend/codegen/protobuf/java/protobuf-grpc-java.test.lock
  src/python/pants/backend/codegen/protobuf/java/rules.py
  src/python/pants/backend/codegen/protobuf/java/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/java/subsystem.py
  src/python/pants/backend/experimental/codegen/protobuf/java/register.py
Labels: category:new feature

#16335 Provide foundations for a deploy goal
  src/python/pants/core/goals/deploy.py
  src/python/pants/core/goals/deploy_test.py
  src/python/pants/core/register.py
Labels: category:user api change

#16381 go: pass -p option to `go tool asm` on Go v1.19+
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/build_pkg.py
Labels: needs-cherrypick, category:bugfix

#16383 Move Nora Howard to Maintainers Emeritus
  MAINTAINERS.md
Labels: category:internal

#16385 Set immutable_input_digests on a docker RunRequest.
  src/python/pants/backend/docker/goals/run_image.py
Labels: needs-cherrypick, category:bugfix

#16384 Clarify limited logo usage rights granted by orgs
  .github/ISSUE_TEMPLATE/user_registration.yml
Labels: category:internal

#16395 go: pass -p option to `go tool asm` on Go v1.19+ (Cherry pick of #16381)
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/build_pkg.py
Labels: category:bugfix

#16382 Add Borja Lorente to Maintainers Emeritus
  MAINTAINERS.md
Labels: category:internal

#16396 Set immutable_input_digests on a docker RunRequest. (Cherry-pick of #16385)
  src/python/pants/backend/docker/goals/run_image.py
Labels: category:bugfix

#16401 Fix incorrect alpha sorting of a maintainer name
  MAINTAINERS.md
Labels: category:internal

#16398 Implement a `validate` mode to reduce network usage for remote caches
  pants.toml
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/option/global_options.py
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: needs-cherrypick, category:performance

#16409 Implement a `validate` mode to reduce network usage for remote caches (Cherry-pick of #16398)
  pants.toml
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/option/global_options.py
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: category:performance

#16399 Document how to use Pylint reports
  docs/markdown/Python/python/python-linters-and-formatters.md
Labels: category:documentation

#16403 Add missing `help` message to experimental backends
  src/python/pants/backend/codegen/soap/target_types.py
  src/python/pants/backend/javascript/target_types.py
  src/python/pants/backend/swift/target_types.py
Labels: needs-cherrypick, category:bugfix

#16379 [internal] Replace `pkgutil.get_data` with new `read_resource` API
  src/python/pants/BUILD
  src/python/pants/_version/BUILD
  src/python/pants/_version/VERSION
  src/python/pants/_version/__init__.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/go/go_sources/load_go_binary.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/python/dependency_inference/BUILD
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/scripts/BUILD
  src/python/pants/backend/python/dependency_inference/scripts/__init__.py
  src/python/pants/backend/python/dependency_inference/scripts/dependency_parser_py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/util/resources.py
  src/python/pants/version.py
Labels: category:internal

#16415 Replace `--[no-]process-cleanup` with `--keep-sandboxes={always,never,on_failure}`
  docs/markdown/Using Pants/troubleshooting.md
  docs/markdown/Writing Plugins/rules-api/rules-api-process.md
  docs/markdown/Writing Plugins/rules-api/rules-api-tips.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/engine/internals/options_parsing.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/process.py
  src/python/pants/jvm/strip_jar/strip_jar.py
  src/python/pants/option/global_options.py
  src/python/pants/option/option_types.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:user api change

#16417 Replace `--[no-]process-cleanup` with `--keep-sandboxes={always,never,on_failure}` (Cherry-pick of #16415)
  docs/markdown/Using Pants/troubleshooting.md
  docs/markdown/Writing Plugins/rules-api/rules-api-process.md
  docs/markdown/Writing Plugins/rules-api/rules-api-tips.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/engine/internals/options_parsing.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/process.py
  src/python/pants/option/global_options.py
  src/python/pants/option/option_types.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:user api change

#16418 Deprecate `[python].lockfile_generator`
  docs/markdown/Python/python/python-third-party-dependencies.md
  pants.toml
  src/python/pants/backend/python/subsystems/poetry.py
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:user api change

#16423 Add [pytest].config
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/subsystems/pytest.py
Labels: category:new feature

#16419 Fix docker invalidation bug.
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/package_types.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: needs-cherrypick, category:bugfix

#16428 Fix process_executor
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/externs/interface.rs
Labels: category:internal

#16427 Prep for 2.14.0.dev4
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16426 Upgrade Pex to 2.1.103.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#16433 Revert "Replace `pkgutil.get_data` with new `read_resource` API (#16379)"
  src/python/pants/BUILD
  src/python/pants/_version/BUILD
  src/python/pants/_version/VERSION
  src/python/pants/_version/__init__.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/go/go_sources/load_go_binary.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/python/dependency_inference/BUILD
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/scripts/BUILD
  src/python/pants/backend/python/dependency_inference/scripts/__init__.py
  src/python/pants/backend/python/dependency_inference/scripts/dependency_parser.py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/util/resources.py
  src/python/pants/version.py
Labels: category:internal

#16434 Prep for 2.14.0.dev5
  src/python/pants/VERSION
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16435 Use our temporary_dir util in _release_helper.py.
  build-support/bin/_release_helper.py
Labels: category:internal

#16431 Fix docker invalidation bug (cherrypick of #16419)
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/package_types.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: category:bugfix

#16439 Fix `CacheContentBehavior::Defer` with a remote cache
  src/python/pants/option/global_options.py
  src/rust/engine/src/context.rs
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: needs-cherrypick, category:bugfix

#16436 Bump release requirements to macos 11.0
  build-support/bin/_release_helper.py
Labels: category:internal

#16444 Allow backend packages to also register remote auth plugins
  src/python/pants/init/extension_loader.py
Labels: category:plugin api change

#16429 go: add debug goal to show package analysis
  src/python/pants/backend/experimental/go/debug_goals/BUILD
  src/python/pants/backend/experimental/go/debug_goals/__init__.py
  src/python/pants/backend/experimental/go/debug_goals/register.py
  src/python/pants/backend/go/goals/debug_goals.py
Labels: category:internal

#16441 Fix `CacheContentBehavior::Defer` with a remote cache (Cherry-pick of #16439)
  src/python/pants/option/global_options.py
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: category:bugfix

#16447 Fix `--process-cleanup` deprecation.
  src/python/pants/engine/internals/options_parsing.py
  src/python/pants/option/global_options.py
Labels: needs-cherrypick, category:bugfix

#16440 Support macOS-10.15 CI on a self-hosted runner.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16448 Fix `--process-cleanup` deprecation. (Cherry-pick of #16447)
  src/python/pants/engine/internals/options_parsing.py
  src/python/pants/option/global_options.py
Labels: category:bugfix

#16420 Add `[python].resolves_to_constraints_file`
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/setup_test.py
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/lockfile_metadata_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/core/goals/update_build_files_test.py
  src/python/pants/core/util_rules/lockfile_metadata.py
Labels: category:new feature

#16387 [internal] Amend missing `timeout` field in target generators
  docs/markdown/Go/go.md
  docs/markdown/Helm/helm-overview.md
  docs/markdown/Java and Scala/jvm-overview.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Shell/shell.md
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/core/goals/test.py
  src/python/pants/jvm/target_types.py
Labels: category:internal

#16442 [internal] Shell completions fix for Bash
  build-support/bin/generate_completions.py
Labels: category:internal

#16449 `GenerateToolLockfileSentinel` encouraged to use language-specific subclasses
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  src/python/pants/backend/cc/lint/clangformat/subsystem.py
  src/python/pants/backend/codegen/avro/java/rules.py
  src/python/pants/backend/codegen/protobuf/java/rules.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/codegen/soap/java/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/rules.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/lint/autoflake/subsystem.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/docformatter/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/isort/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pyupgrade/subsystem.py
  src/python/pants/backend/python/lint/yapf/subsystem.py
  src/python/pants/backend/python/subsystems/debugpy.py
  src/python/pants/backend/python/subsystems/ipython.py
  src/python/pants/backend/python/subsystems/lambdex.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/backend/python/subsystems/setuptools_scm.py
  src/python/pants/backend/python/subsystems/twine.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/jvm/strip_jar/strip_jar.py
  src/python/pants/jvm/test/junit.py
Labels: category:plugin api change

#16453 Build macos10.15 wheels for all 3 pythons.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16457 Add IBM to user list.
  build-support/bin/generate_user_list.py
  build-support/bin/user_list_templates/table.html.mustache
Labels: category:documentation

#16452 Add `__default__` symbol to `[python].resolves_to_constraints_file`
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/setup_test.py
Labels: category:internal

#16460 Add `PexRequirements.req_strings_from_requirement_fields()`
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
Labels: category:internal

#16455 Add support for using environment variables in JVM tests
  docs/markdown/Java and Scala/jvm-overview.md
  docs/markdown/Java and Scala/kotlin.md
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/java/target_types.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/kotlin/test/junit_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/backend/scala/test/BUILD
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/backend/scala/test/scalatest.test.lock
  src/python/pants/backend/scala/test/scalatest_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/jvm/target_types.py
  src/python/pants/jvm/test/junit.py
  src/python/pants/jvm/test/junit_test.py
Labels: category:new feature

#16461 Add `[mypy].extra_type_stubs_lockfile`
  docs/markdown/Python/python-goals/python-check-goal.md
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/typecheck/mypy/mypyc.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/typecheck/mypy/subsystem_test.py
  src/python/pants/backend/python/util_rules/partition.py
Labels: category:new feature

#16469 Use a list of requirement constraints for lockfile invalidation
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/pip_requirement.py
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/lockfile_metadata_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:internal

#16479 Fix docker invalidation bug. (cherrypick #16419)
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/package_types.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: category:bugfix

#16481 Support adding to dict-valued options in config files.
  src/python/pants/backend/docker/registries.py
  src/python/pants/engine/target.py
  src/python/pants/option/config.py
  src/python/pants/option/config_test.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_bootstrapper_test.py
  src/python/pants/option/parser.py
Labels: category:new feature

#16486 Fix partition description for MyPy when multiple resolves
  src/python/pants/backend/python/typecheck/mypy/rules.py
Labels: needs-cherrypick, category:documentation

#16490 Include Helm chart dependency inference rules (cherrypick of #16368)
  src/python/pants/backend/helm/goals/lint_test.py
  src/python/pants/backend/helm/goals/package_test.py
  src/python/pants/backend/helm/util_rules/chart.py
  src/python/pants/backend/helm/util_rules/chart_test.py
Labels: category:bugfix

#16491 Include Helm chart dependency inference rules (cherrypick of #16368)
  src/python/pants/backend/helm/goals/lint_test.py
  src/python/pants/backend/helm/goals/package_test.py
  src/python/pants/backend/helm/util_rules/chart.py
  src/python/pants/backend/helm/util_rules/chart_test.py
Labels: category:internal

#16487 Refactor `create_pex_from_targets` rule with `@rule_helper`
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/backend/scala/test/BUILD
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:internal

#16498 Fix partition description for MyPy when multiple resolves (Cherry-pick of #16486)
  src/python/pants/backend/python/typecheck/mypy/rules.py
Labels: category:documentation

#16500 Add missing `help` message to experimental backends (Cherry-pick of #16403)
  src/python/pants/backend/codegen/soap/target_types.py
  src/python/pants/backend/javascript/target_types.py
  src/python/pants/backend/swift/target_types.py
Labels: category:bugfix

#16496 Ban `platforms` and `internal_only` with `pex_from_targets.py` too
  src/python/pants/backend/helm/util_rules/BUILD
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: category:internal

#16504 Use version 2 of Python lockfile metadata for now
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/lockfile_metadata_test.py
Labels: category:internal

#16502 Support macOS 10.15 CI (cherrypick #16440,#16453)
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16505 Move Ity Kaul to emeritus
  MAINTAINERS.md
Labels: category:internal

#16503 Update docs on how to run Pants in CI.
  docs/markdown/Using Pants/remote-caching-execution.md
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#16509 Update docs on how to run Pants in CI. (Cherry-pick of #16503)
  docs/markdown/Using Pants/remote-caching-execution.md
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#16507 Prepare the 2.14.0.dev6 release
  src/python/pants/VERSION
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16511 Add stray missing change to release notes.
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16510 Minor fix to docs sync instructions.
  docs/.gitignore
  docs/NOTES.md
  docs/package-lock.json
  docs/package.json
Labels: category:internal

#16508 Backport CI improvements.
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/cancel.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16512 Update release helper to know about macos 10.15 and 11 wheels.
  build-support/bin/_release_helper.py
Labels: category:internal

#16501 Prepare 2.13.0rc1
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#16478 Support 3rd party Helm artifacts in Helm deployments
  docs/markdown/Helm/helm-deployments.md
  src/python/pants/backend/helm/dependency_inference/BUILD
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/goals/BUILD
  src/python/pants/backend/helm/goals/deploy_test.py
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/k8s_parser_main.py
  src/python/pants/backend/helm/util_rules/chart.py
  src/python/pants/backend/helm/util_rules/chart_test.py
  src/python/pants/backend/helm/util_rules/renderer.py
Labels: category:new feature

#16492 Perform address mapping on a per-deployment basis
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/dependency_inference/deployment_test.py
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/k8s_parser_test.py
  src/python/pants/backend/helm/subsystems/post_renderer_main.py
  src/python/pants/backend/helm/util_rules/post_renderer.py
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
  src/python/pants/backend/helm/util_rules/renderer.py
  src/python/pants/backend/helm/utils/yaml.py
Labels: category:internal

#16514 Prepare 2.12.1rc3
  src/python/pants/notes/2.12.x.md
Labels: category:internal

#16513 Deprecate `[python].only_binary` and `[python].no_binary` in favor of more powerful `[python].resolves_to_only_binary` and `[python].resolves_to_no_binary`
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/setup_test.py
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/lockfile_metadata_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:user api change

#16518 Update release helper to know about macos 10.15 and 11 wheels (cherrypick #16512)
  build-support/bin/_release_helper.py
Labels: category:internal

#16485 [internal] Replace `pkgutil.get_data` with new `read_resource` API (mk 2)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/BUILD
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/go/go_sources/load_go_binary.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/python/dependency_inference/BUILD
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/scripts/BUILD
  src/python/pants/backend/python/dependency_inference/scripts/dependency_parser_py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/util/resources.py
  src/python/pants/version.py
Labels: category:internal

#16470 Add `[flake8].extra_files` to allow configuring plugins like Bandit
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
Labels: category:new feature

#16468 Fix broken link to community page
  docs/markdown/Contributions/contributor-overview.md
Labels: category:documentation

#16521 Fix lockfile for `python-default`.
  3rdparty/python/user_reqs.lock
Labels: category:internal

#16524 Further `--process-cleanup` deprecation tweaks
  src/python/pants/engine/internals/options_parsing.py
  src/python/pants/option/global_options.py
Labels: needs-cherrypick, category:internal

#16525 Track Python indexes, find-links, and manylinux in lockfile headers
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/lockfile_metadata_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:bugfix

#16528 Further `--process-cleanup` deprecation tweaks (Cherry-pick of #16524)
  src/python/pants/engine/internals/options_parsing.py
  src/python/pants/option/global_options.py
Labels: category:internal

#16529 Upgrade to rust `1.63.0`
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
  src/rust/engine/client/src/pantsd.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/protos/src/lib.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/lib.rs
Labels: category:internal

#16516 Prevent running N^2 publish processes during deploy goal
  src/python/pants/core/goals/deploy.py
Labels: category:bugfix

#16536 Support M1 contributors automatically
  build-support/common.sh
  pants
Labels: category:internal

#16537 Add `[pyoxidizer].lockfile`
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/experimental/python/packaging/pyoxidizer/register.py
  src/python/pants/backend/python/packaging/pyoxidizer/BUILD
  src/python/pants/backend/python/packaging/pyoxidizer/pyoxidizer.lock
  src/python/pants/backend/python/packaging/pyoxidizer/subsystem.py
Labels: category:new feature

#16535 Rename `FmtRequest` to `FmtTargetsRequest` (plus some `fix` refactoring)
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/backend/terraform/style.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: category:plugin api change

#16542 Clarify what folder to run Readme sync from
  build-support/bin/_release_helper.py
  docs/NOTES.md
Labels: category:internal

#16499 Allow for automatic use of `pytest-xdist`
  3rdparty/python/pytest.lock
  src/python/pants/backend/helm/goals/BUILD
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/goals/pytest_runner_test.py
  src/python/pants/backend/python/subsystems/pytest.lock
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/target_types.py
Labels: category:new feature

#16545 Record `RemoteStoreBlobBytesUploaded` for all upload strategies, rather than only for large blobs.
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
Labels: needs-cherrypick, category:bugfix

#16548 Document `[python].resolves_to_constraints_file` and `[python].resolves_to_no_binary`
  docs/markdown/Python/python/python-third-party-dependencies.md
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/post_renderer.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
Labels: category:documentation

#16549 More succint phrasing and better formatting for cli help.
  docs/markdown/Using Pants/command-line-help.md
  src/python/pants/help/help_printer.py
Labels: category:documentation

#16552 Increase timeout for boostraping pants and testing rust under macos 11
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#16546 Fix that running on a BUILD file expands to all of its targets
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/vcs/changed.py
Labels: category:user api change

#16556 Fix broken link to community page (Cherry-pick of #16468)
  docs/markdown/Contributions/contributor-overview.md
Labels: category:documentation

#16557 Fix broken link to community page (Cherry-pick of #16468)
  docs/markdown/Contributions/contributor-overview.md
Labels: category:documentation

#16558 Use Markdown h3 for ToC support (Cherry-pick of #15964)
  build-support/bin/docs_templates/single_option_reference.md.mustache
Labels: category:documentation

#16555 Record `RemoteStoreBlobBytesUploaded` for all upload strategies, rather than only for large blobs. (Cherry-pick of #16545)
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
Labels: category:bugfix

#16544 Add `_FmtBuildFilesRequest` to `fmt`
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
Labels: category:internal

#16551 Upgrade Toolchain Pants Plugin to 0.22.0
  pants.toml
Labels: category:internal

#16559 Use `PipRequirement` for `only_binary` and `no_binary` lockfile metadata
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/setup_test.py
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/lockfile_metadata_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:internal

#16567 fix `cargo install` invocation
  build-support/bin/check_rust_target_headers.sh
Labels: category:internal

#16568 Have `run` run `__main__.py` for non-zipapp PEXs
  src/python/pants/backend/python/goals/run_pex_binary.py
  src/python/pants/backend/python/goals/run_pex_binary_integration_test.py
Labels: needs-cherrypick, category:bugfix

#16554 [2.13.x branch] Upgrade Toolchain Pants Plugin to 0.22.0
  pants.toml
Labels: category:internal

#16572 Fix `fmt` with no specs
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
Labels: category:internal

#16369 Update to `indicatif` `0.17`.
  src/rust/engine/Cargo.lock
  src/rust/engine/ui/Cargo.toml
  src/rust/engine/ui/src/console_ui.rs
Labels: category:internal

#16563 Improve performance of `Owners` rule
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  src/python/pants/backend/java/goals/tailor.py
  src/python/pants/backend/kotlin/goals/tailor.py
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/scala/goals/tailor.py
  src/python/pants/backend/shell/tailor.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/target.py
  src/python/pants/source/filespec.py
  src/python/pants/source/filespec_test.py
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/src/externs/fs.rs
Labels: needs-cherrypick, category:performance

#16488 Disable 80 col hard wrapping in mypy output
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
Labels: category:new feature

#16583 Fix deprecation to use FilespecMatcher in fmt.py
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/core/goals/fmt.py
Labels: category:internal

#16582 Add `[python-repos].find_links` as preferred alias for `[python-repos].repos`
  docs/markdown/Python/python/python-third-party-dependencies.md
  src/python/pants/backend/google_cloud_function/python/BUILD
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/lint/isort/BUILD
  src/python/pants/backend/python/subsystems/repos.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
Labels: category:user api change

#16531 Auto-detect Helm chart source roots
  docs/markdown/Helm/helm-deployments.md
  docs/markdown/Helm/helm-overview.md
  src/python/pants/backend/helm/dependency_inference/chart.py
  src/python/pants/backend/helm/dependency_inference/chart_test.py
  src/python/pants/backend/helm/dependency_inference/unittest_test.py
  src/python/pants/backend/helm/goals/deploy_test.py
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/goals/lint_test.py
  src/python/pants/backend/helm/goals/package.py
  src/python/pants/backend/helm/goals/package_test.py
  src/python/pants/backend/helm/resolve/fetch.py
  src/python/pants/backend/helm/resolve/fetch_test.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/test/unittest_test.py
  src/python/pants/backend/helm/util_rules/chart.py
  src/python/pants/backend/helm/util_rules/chart_metadata.py
  src/python/pants/backend/helm/util_rules/chart_metadata_test.py
  src/python/pants/backend/helm/util_rules/chart_test.py
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
  src/python/pants/backend/helm/util_rules/renderer.py
  src/python/pants/backend/helm/util_rules/renderer_test.py
  src/python/pants/backend/helm/util_rules/sources.py
  src/python/pants/backend/helm/util_rules/sources_test.py
  src/python/pants/backend/helm/util_rules/tool.py
Labels: category:bugfix

#16575 Revert storing `indexes` and `find_links` in lockfile headers due to security
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/lockfile_metadata_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:internal

#16587 Fix list of passthrough arguments for Helm deployments
  src/python/pants/backend/helm/subsystems/helm.py
Labels: category:internal

#16590 Fix `IndexError` when codegen is missing expected `python_requirement` targets
  src/python/pants/util/strutil.py
Labels: category:bugfix

#16591 Fix performance for generating lockfiles for `pytest` and `setuptools`
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/bandit/subsystem_test.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem_test.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem_test.py
  src/python/pants/backend/python/subsystems/ipython.py
  src/python/pants/backend/python/subsystems/ipython_test.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/pytest_test.py
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/backend/python/subsystems/setuptools_test.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/typecheck/mypy/subsystem_test.py
  src/python/pants/backend/python/util_rules/partition.py
  src/python/pants/backend/python/util_rules/partition_test.py
  src/python/pants/core/goals/repl.py
Labels: needs-cherrypick, category:performance

#16550 go: add support for test coverage
  src/python/pants/backend/experimental/go/register.py
  src/python/pants/backend/go/go_sources/generate_testmain/main.go
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/coverage.py
  src/python/pants/backend/go/util_rules/coverage_output.py
  src/python/pants/backend/go/util_rules/coverage_test.py
  src/python/pants/backend/go/util_rules/tests_analysis.py
  src/python/pants/backend/go/util_rules/tests_analysis_test.py
Labels: backend: Go, category:new feature

#16596 Fix performance for generating lockfiles for `pytest` and `setuptools` (Cherry-pick of #16591)
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/bandit/subsystem_test.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem_test.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem_test.py
  src/python/pants/backend/python/subsystems/ipython.py
  src/python/pants/backend/python/subsystems/ipython_test.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/pytest_test.py
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/backend/python/subsystems/setuptools_test.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/typecheck/mypy/subsystem_test.py
  src/python/pants/backend/python/util_rules/partition.py
  src/python/pants/backend/python/util_rules/partition_test.py
  src/python/pants/core/goals/repl.py
Labels: category:performance

#16597 Improve performance of `Owners` rule (#16563)
  src/python/pants/backend/java/goals/tailor.py
  src/python/pants/backend/kotlin/goals/tailor.py
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/scala/goals/tailor.py
  src/python/pants/backend/shell/tailor.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/target.py
  src/python/pants/source/filespec.py
  src/python/pants/source/filespec_test.py
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/src/externs/fs.rs
Labels: category:performance

#16573 Add buildifier as a BUILD file formatter
  build-support/bin/generate_docs.py
  docs/markdown/Using Pants/concepts/enabling-backends.md
  src/python/pants/backend/build_files/fmt/buildifier/BUILD
  src/python/pants/backend/build_files/fmt/buildifier/__init__.py
  src/python/pants/backend/build_files/fmt/buildifier/register.py
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/backend/build_files/fmt/buildifier/rules_integration_test.py
  src/python/pants/backend/build_files/fmt/buildifier/subsystem.py
  src/python/pants/bin/BUILD
Labels: category:new feature

#16560 Add new fmt plugins for build file formatting
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_docs.py
  build-support/bin/generate_github_workflows.py
  docs/markdown/Releases/upgrade-tips.md
  docs/markdown/Using Pants/concepts/enabling-backends.md
  docs/markdown/Using Pants/concepts/targets.md
  pants.toml
  src/python/pants/backend/build_files/BUILD
  src/python/pants/backend/build_files/__init__.py
  src/python/pants/backend/build_files/fmt/BUILD
  src/python/pants/backend/build_files/fmt/__init__.py
  src/python/pants/backend/build_files/fmt/black/BUILD
  src/python/pants/backend/build_files/fmt/black/__init__.py
  src/python/pants/backend/build_files/fmt/black/integration_test.py
  src/python/pants/backend/build_files/fmt/black/register.py
  src/python/pants/backend/build_files/fmt/yapf/BUILD
  src/python/pants/backend/build_files/fmt/yapf/__init__.py
  src/python/pants/backend/build_files/fmt/yapf/integration_test.py
  src/python/pants/backend/build_files/fmt/yapf/register.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/bin/BUILD
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:new feature

#16077 Add Plugin hook for adding custom additional Docker image tags.
  docs/markdown/Docker/tagging-docker-images.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/target_types.py
Labels: category:new feature

#16604 Add `grpcio` to default Python module mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:bugfix

#16605 Add `grpc` to default Python module mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:bugfix

#16606 Mark `[python].requirement_constraints` as deprecated (but not planned for removal)
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
Labels: category:user api change

#16608 Prepare the 2.14.0a0 release.
  .mailmap
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#16543 Mention team meetings as a Contributor permission
  docs/markdown/Getting Help/the-pants-community.md
  docs/markdown/Getting Help/the-pants-community/maintainers.md
Labels: category:documentation

#16617 Optimize `CreateDigest` implementation.
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:performance

#16618 Bump default version of `setuptools` to 63.4
  src/python/pants/backend/python/subsystems/setuptools.lock
  src/python/pants/backend/python/subsystems/setuptools.py
Labels: category:user api change

#16616 Fix `./pants help` docs on command line specs
  docs/markdown/Using Pants/command-line-help.md
  src/python/pants/help/help_printer.py
Labels: needs-cherrypick, category:documentation

#16584 Support Pex's `--path-mapping` with lockfiles for better local requirement support
  docs/markdown/Python/python/python-third-party-dependencies.md
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/subsystems/repos.py
  src/python/pants/backend/python/util_rules/BUILD
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/backend/python/util_rules/pex_test_utils.py
Labels: needs-cherrypick, category:new feature

#16607 Add --squash and --pull options support for docker build
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/target_types.py
Labels: category:new feature, backend: Docker

#16619 Bump default version of setuptools to 63.4
  src/python/pants/backend/python/subsystems/setuptools.lock
  src/python/pants/backend/python/subsystems/setuptools.py
Labels: category:user api change

#16623 Fix `./pants help` docs on command line specs (Cherry-pick of #16616)
  docs/markdown/Using Pants/command-line-help.md
  src/python/pants/help/help_printer.py
Labels: category:documentation

#16622 Clarify wording for `--skip` options
  src/python/pants/option/option_types.py
  src/python/pants/option/option_types_test.py
Labels: needs-cherrypick, category:documentation

#16624 Fix `./pants help` docs on command line specs (Cherry-pick of #16616)
  docs/markdown/Using Pants/command-line-help.md
  src/python/pants/help/help_printer.py
Labels: category:documentation

#16628 Make `DependencyKey` a concrete type
  src/python/pants/engine/rules_test.py
  src/rust/engine/Cargo.lock
  src/rust/engine/rule_graph/Cargo.toml
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/rule_graph/src/rules.rs
  src/rust/engine/rule_graph/src/tests.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/lib.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/scheduler.rs
  src/rust/engine/src/selectors.rs
  src/rust/engine/src/tasks.rs
Labels: category:internal

#16634 Remove unnecessary type parameter from `Get`
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  src/python/pants/backend/helm/util_rules/chart.py
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/engine/internals/.gitignore
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler_test.py
  src/python/pants/engine/internals/selectors.py
Labels: category:plugin api change

#16627 Implement a batched local lookup for missing fingerprints.
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/sharded_lmdb/src/lib.rs
Labels: needs-cherrypick, category:performance

#16635 Have `run` run `__main__.py` for non-zipapp PEXs (Cherry-pick of #16568)
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/goals/run_pex_binary.py
  src/python/pants/backend/python/goals/run_pex_binary_integration_test.py
Labels: category:bugfix
