Repository pantsbuild/pants, pull requests merged in 2022-10, with the labels that each got.

#17078 go: work around issue with options called --env-vars
  src/python/pants/backend/go/goals/generate.py
Labels: category:internal

#17082 go: refactor tailor rule into rule helpers
  src/python/pants/backend/go/goals/tailor.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/assembly_integration_test.py
Labels: backend: Go, category:internal

#17081 Upgrade Pex to 2.1.107.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#17080 Improve usability of the `--engine-visualize-to` option
  src/python/pants/engine/internals/scheduler.py
  src/rust/engine/graph/src/entry.rs
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/graph/src/node.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/scheduler.rs
Labels: category:plugin api change

#17037 Exit normally from K8S parser with unsupported manifests
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/k8s_parser_main.py
Labels: enhancement, needs-cherrypick, category:internal, backend: Helm

#17088 Fix test break cause by importlib-metadata 5.0.0 release.
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
Labels: category:internal

#17091 Fix Helm K8S parser help message
  src/python/pants/backend/helm/subsystems/k8s_parser.py
Labels: needs-cherrypick, category:documentation, backend: Helm

#17090 Upgrade Helm to 3.10
  src/python/pants/backend/helm/subsystems/helm.py
Labels: category:internal, backend: Helm

#17093 Stop treading on `env_vars` as an option name
  src/python/pants/backend/go/goals/generate.py
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/python/subsystems/python_native_code.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/backend/shell/shell_setup.py
  src/python/pants/option/subsystem.py
Labels: category:internal

#17060 Provide `snapshot` to formatter subpartitions in `lint`/`fmt`.
  src/python/pants/backend/build_files/fmt/black/integration_test.py
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/backend/build_files/fmt/buildifier/rules_integration_test.py
  src/python/pants/backend/build_files/fmt/yapf/integration_test.py
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/cc/lint/clangformat/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules_integration_test.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/gofmt/rules_integration_test.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules_integration_test.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/javascript/lint/prettier/rules_integration_test.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules_integration_test.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules_integration_test.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/autoflake/rules_integration_test.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/docformatter/rules_integration_test.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/isort/rules_integration_test.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules_integration_test.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/python/lint/yapf/rules_integration_test.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules_integration_test.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt_integration_test.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/update_build_files.py
Labels: category:internal

#17062 docker: add resolve image intrinsic
  src/python/pants/engine/internals/docker.py
  src/python/pants/engine/internals/docker_test.py
  src/python/pants/engine/internals/scheduler.py
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/types.rs
Labels: category:internal

#17085 Add missing skip options to subsystems/rules
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/java/goals/check.py
  src/python/pants/backend/java/subsystems/javac.py
  src/python/pants/backend/kotlin/goals/check.py
  src/python/pants/backend/kotlin/subsystems/kotlinc.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/scala/goals/check.py
  src/python/pants/backend/scala/subsystems/scalac.py
Labels: category:internal

#17083 Prep release 2.15.0.dev3
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#17084 Rename/Refactor `style_request` to better capture intent.
  src/python/pants/backend/build_files/fmt/black/register.py
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/backend/build_files/fmt/yapf/register.py
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/go/goals/check.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/golangci_lint/rules.py
  src/python/pants/backend/go/lint/vet/rules.py
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/java/goals/check.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/kotlin/goals/check.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/bandit/rules.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/scala/goals/check.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/multi_tool_goal_helper.py
  src/python/pants/core/goals/multi_tool_goal_helper_test.py
  src/python/pants/core/goals/style_request.py
Labels: category:plugin api change

#17099 Revert "Add missing skip options to subsystems/rules"
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/java/goals/check.py
  src/python/pants/backend/java/subsystems/javac.py
  src/python/pants/backend/kotlin/goals/check.py
  src/python/pants/backend/kotlin/subsystems/kotlinc.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/scala/goals/check.py
  src/python/pants/backend/scala/subsystems/scalac.py
Labels: category:internal

#17087 go: add cgo support for tailor
  src/python/pants/backend/go/goals/tailor.py
  src/python/pants/backend/go/goals/tailor_test.py
Labels: backend: Go, category:new feature

#17105 remove moot comment from requirements
  3rdparty/python/requirements.txt
Labels: category:internal

#17022 Update maintainer job description
  docs/markdown/Getting Help/the-pants-community/maintainers.md
Labels: category:documentation

#17095 Finalise environments targets and documentation
  BUILD
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_integration_test.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/internals/platform_rules_test.py
Labels: category:internal

#17112 Upgrade Pex to 2.1.108.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#17101 docker: ensure image names have an image ID appended
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: category:internal

#17115 Fix test break cause by importlib-metadata 5.0.0 release. (Cherry-pick of #17088)
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
Labels: category:internal

#17117 Fix test break cause by importlib-metadata 5.0.0 release. (Cherry-pick of #17088)
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
Labels: category:internal

#17120 Upgrade Pex to 2.1.108. (Cherry-pick of #17112)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#17123 Upgrade Pex to 2.1.108. (Cherry-pick of #17112)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#17125 Fix `bsp-groups.toml` example in documentation
  docs/markdown/Java and Scala/jvm-overview.md
Labels: needs-cherrypick, category:documentation

#17098 Refactor venv export
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/core/goals/export.py
Labels: category:internal

#17068 Auto-apply reviewers to cherrypicks.
  build-support/bin/cherry_pick.sh
Labels: category:internal

#17103 Switch `LintRequest.name` to `.tool_subsystem`
  src/python/pants/backend/build_files/fmt/black/register.py
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/backend/build_files/fmt/yapf/register.py
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/golangci_lint/rules.py
  src/python/pants/backend/go/lint/vet/rules.py
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/bandit/rules.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/core/goals/fmt_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/multi_tool_goal_helper.py
  src/python/pants/core/goals/multi_tool_goal_helper_test.py
Labels: category:plugin api change

#17110 Update maintainer job description (Cherry-pick of #17022)
  docs/markdown/Getting Help/the-pants-community/maintainers.md
Labels: category:documentation

#17109 Update maintainer job description (Cherry-pick of #17022)
  docs/markdown/Getting Help/the-pants-community/maintainers.md
Labels: category:documentation

#17131 Add Aiven to user list.
  build-support/bin/generate_user_list.py
Labels: category:documentation

#17127 Provide a "default" partitioner for `lint`/`fmt`
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/vet/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/engine/target.py
Labels: category:internal

#17138 Generate help info about target_field_name to the docsite.
  build-support/bin/docs_templates/single_option_reference.md.mustache
  src/python/pants/help/help_formatter.py
  src/python/pants/util/strutil.py
Labels: category:documentation

#17147 Fix `bsp-groups.toml` example in documentation (Cherry-pick of #17125)
  docs/markdown/Java and Scala/jvm-overview.md
Labels: category:documentation

#17148 Fix `bsp-groups.toml` example in documentation (Cherry-pick of #17125)
  docs/markdown/Java and Scala/jvm-overview.md
Labels: category:documentation

#17140 Minor cleanups to fmt/lint
  src/python/pants/backend/build_files/fmt/black/register.py
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/backend/build_files/fmt/yapf/register.py
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/golangci_lint/rules.py
  src/python/pants/backend/go/lint/vet/rules.py
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/bandit/rules.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: category:internal

#17145 Fix Helm K8S parser help message (Cherry-pick of #17091)
  src/python/pants/backend/helm/subsystems/k8s_parser.py
Labels: category:documentation

#17143 Exit normally from K8S parser with unsupported manifests (Cherry-pick of #17037)
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/k8s_parser_main.py
Labels: category:bugfix

#17146 Add debug output in case of a KeyError during CoarsenedTarget construction. (Cherry-pick of #17069)
  src/python/pants/engine/internals/graph.py
Labels: category:internal

#17149 Add Doron Somech's proudest contribution (Cherry-pick of #17029)
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#17150 Add Doron Somech's proudest contribution (Cherry-pick of #17029)
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#17152 Add Marcelo to team page, move Josh Reed to Maintainer (Cherry-pick of #16826)
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#17144 Tidy up environments documentation
  src/python/pants/core/util_rules/environments.py
Labels: category:internal

#17151 Add Marcelo to team page, move Josh Reed to Maintainer (Cherry-pick of #16826)
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#17154 Fix spurious linebreaks in the CI docs page.
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#17137 Add OpenAPI linting with Spectral
  build-support/bin/generate_docs.py
  src/python/pants/backend/experimental/openapi/lint/spectral/BUILD
  src/python/pants/backend/experimental/openapi/lint/spectral/__init__.py
  src/python/pants/backend/experimental/openapi/lint/spectral/register.py
  src/python/pants/backend/openapi/lint/spectral/BUILD
  src/python/pants/backend/openapi/lint/spectral/__init__.py
  src/python/pants/backend/openapi/lint/spectral/rules.py
  src/python/pants/backend/openapi/lint/spectral/rules_integration_test.py
  src/python/pants/backend/openapi/lint/spectral/skip_field.py
  src/python/pants/backend/openapi/lint/spectral/subsystem.py
  src/python/pants/bin/BUILD
Labels: category:new feature

#17158 Fix spurious linebreaks in the CI docs page. (Cherry-pick of #17154)
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#17156 Fix spurious linebreaks in the CI docs page. (Cherry-pick of #17154)
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#17160 Prepare 2.13.1rc1 release notes.
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#17161 Prepare 2.15.0.dev4 release notes.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#17119 Always include relevant params in workunit descriptions, and include descriptions in traces by default
  src/python/pants/base/specs_integration_test.py
  src/python/pants/bin/local_pants_runner_integration_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/engine/environment.py
  src/python/pants/engine/internals/engine_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/nodes.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/internals/scheduler_test.py
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/python.rs
Labels: category:user api change

#17159 Prepare 2.14.0rc3 release notes.
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#17164 go/cgo: use debug level to reduce work unit verbosity
  src/python/pants/backend/go/util_rules/cgo.py
Labels: backend: Go, category:internal

#17086 go: enable cgo by default
  src/python/pants/backend/go/subsystems/golang.py
Labels: backend: Go, category:internal

#17135 Remote execution is only enabled globally if environments aren't used at all
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/internals/platform_rules.py
  src/python/pants/engine/internals/platform_rules_test.py
Labels: category:internal

#17172 Fix quoting of GitHub Actions expressions.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17168 Speed up print_engine_hash by not creating the venv.
  build-support/bin/rust/calculate_engine_hash.sh
  build-support/bin/rust/print_engine_hash.sh
Labels: category:internal

#17163 Adding basic support for pyright typechecking
  src/python/pants/backend/experimental/python/typecheck/BUILD
  src/python/pants/backend/experimental/python/typecheck/__init__.py
  src/python/pants/backend/experimental/python/typecheck/pyright/BUILD
  src/python/pants/backend/experimental/python/typecheck/pyright/__init__.py
  src/python/pants/backend/experimental/python/typecheck/pyright/register.py
  src/python/pants/backend/python/typecheck/pyright/BUILD
  src/python/pants/backend/python/typecheck/pyright/__init__.py
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pyright/skip_field.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
Labels: category:new feature

#17179 Mask the environment name in `graph` and `specs_rules`
  src/python/pants/backend/explorer/graphql/query/conftest.py
  src/python/pants/bsp/protocol.py
  src/python/pants/build_graph/build_configuration.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/environment.py
  src/python/pants/engine/explorer.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/platform_rules_test.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/internals/scheduler_test.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/rules.py
  src/python/pants/goal/explorer.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/option/subsystem.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/rule_graph/src/rules.rs
  src/rust/engine/rule_graph/src/tests.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/tasks.rs
Labels: category:internal

#17165 Add Snowflake connector to module mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:user api change

#17187 Fix deprecation message for `env_vars` renames, and extend by a version.
  src/python/pants/engine/environment.py
Labels: category:internal

#17155 Begin migration to explicitly scoped environments
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  pants-plugins/internal_plugins/rules_for_testing/register.py
  src/python/pants/backend/project_info/dependees.py
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/filter_targets.py
  src/python/pants/backend/project_info/list_roots.py
  src/python/pants/backend/project_info/list_targets.py
  src/python/pants/backend/project_info/paths.py
  src/python/pants/engine/goal.py
  src/python/pants/init/engine_initializer.py
Labels: category:plugin api change

#17186 Migrate `test` goal to explicitly scoped environments
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/engine/desktop.py
  src/python/pants/testutil/rule_runner.py
Labels: category:internal

#17183 Fix macros depending on macros from other files
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: needs-cherrypick, category:bugfix

#17153 Genericize our partitioning code
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules_integration_test.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/docker/lint/hadolint/rules_integration_test.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/golangci_lint/rules.py
  src/python/pants/backend/go/lint/golangci_lint/rules_integration_test.py
  src/python/pants/backend/go/lint/vet/rules.py
  src/python/pants/backend/go/lint/vet/rules_integration_test.py
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/goals/lint_test.py
  src/python/pants/backend/helm/util_rules/chart.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/openapi/lint/spectral/rules.py
  src/python/pants/backend/openapi/lint/spectral/rules_integration_test.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/bandit/rules.py
  src/python/pants/backend/python/lint/bandit/rules_integration_test.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shellcheck/rules_integration_test.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/util_rules/partitions.py
Labels: category:internal

#17188 `--remote-execution` no longer implicitly enables `--remote-cache`
  src/rust/engine/src/context.rs
Labels: category:internal

#17177 Set PEX_ROOT for export post-processing command.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
Labels: needs-cherrypick, category:bugfix

#17193 Make a build_files base helper class
  src/python/pants/backend/build_files/fmt/base.py
  src/python/pants/backend/build_files/fmt/black/register.py
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/backend/build_files/fmt/yapf/register.py
Labels: category:internal

#17192 Make fmt/lint result types less boilerplate-y
  src/python/pants/backend/build_files/fmt/black/integration_test.py
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/backend/build_files/fmt/buildifier/rules_integration_test.py
  src/python/pants/backend/build_files/fmt/yapf/integration_test.py
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/cc/lint/clangformat/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules_integration_test.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/docker/lint/hadolint/rules_integration_test.py
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/gofmt/rules_integration_test.py
  src/python/pants/backend/go/lint/golangci_lint/rules.py
  src/python/pants/backend/go/lint/golangci_lint/rules_integration_test.py
  src/python/pants/backend/go/lint/vet/rules.py
  src/python/pants/backend/go/lint/vet/rules_integration_test.py
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/goals/lint_test.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules_integration_test.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/javascript/lint/prettier/rules_integration_test.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules_integration_test.py
  src/python/pants/backend/openapi/lint/spectral/rules.py
  src/python/pants/backend/openapi/lint/spectral/rules_integration_test.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules_integration_test.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/autoflake/rules_integration_test.py
  src/python/pants/backend/python/lint/bandit/rules.py
  src/python/pants/backend/python/lint/bandit/rules_integration_test.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/docformatter/rules_integration_test.py
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/isort/rules_integration_test.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules_integration_test.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/python/lint/yapf/rules_integration_test.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shellcheck/rules_integration_test.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules_integration_test.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt_integration_test.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/util_rules/partitions.py
Labels: category:plugin api change

#17038 fixup name of opt-in flag in error message
  src/python/pants/core/goals/tailor.py
Labels: category:bugfix

#17190 Declaring Javascript, Prettier, and Pyright backends/plugins in BUILD
  src/python/pants/backend/experimental/javascript/lint/prettier/register.py
  src/python/pants/bin/BUILD
Labels: category:bugfix

#17191 Upgrade Toolchain Pants Plugin to 0.24.0
  pants.toml
Labels: category:internal

#17204 Adjust `ensure_remote_has_recursive` to succeed if content only exists remotely
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/tests.rs
Labels: needs-cherrypick, category:bugfix

#17205 Add `_render_message` to `LintResult` to workaround double-logging
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
Labels: category:internal

#17195 Remote cache reads are resilient to remote execution writing to the cache
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
Labels: category:bugfix

#17169 Use a standard Cargo caching action
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17202 Add a `fix` goal
  pants.toml
  src/python/pants/backend/experimental/python/lint/autoflake/register.py
  src/python/pants/backend/experimental/python/lint/pyupgrade/register.py
  src/python/pants/backend/python/lint/autoflake/register.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/autoflake/rules_integration_test.py
  src/python/pants/backend/python/lint/pyupgrade/register.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules_integration_test.py
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/fix_integration_test.py
  src/python/pants/core/goals/fix_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/register.py
Labels: category:new feature

#17218 A general mechanism for classifying CI changes
  .github/workflows/test.yaml
  build-support/bin/classify_changed_files.py
  build-support/bin/classify_changed_files_test.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17222 Cherrypicks of recent CI improvements to 2.14.x
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/classify_changed_files.py
  build-support/bin/classify_changed_files_test.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17216 [2.13.x branch] Upgrade Toolchain Pants Plugin to 0.24.0
  pants.toml
Labels: category:internal

#17207 Docker command runner caches system binary discovery
  src/python/pants/backend/codegen/thrift/apache/rules.py
  src/python/pants/backend/go/util_rules/goroot.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/jvm/jdk_rules.py
Labels: category:internal

#17226 Upgrade default Flake8 version to 5.0
  3rdparty/python/flake8.lock
  build-support/bin/_generate_all_lockfiles_helper.py
  build-support/flake8/.flake8
  build-support/flake8/bin_name_checker.py
  pants.toml
  src/python/pants/backend/python/lint/flake8/flake8.lock
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
Labels: category:user api change

#17220 Select environment in `package` goal
  src/python/pants/core/goals/package.py
Labels: category:internal

#17219 Simplify prelude/build parsing w.r.t. symbols
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/parser.py
Labels: category:internal

#17209 Add sample REAPI server to use when manually testing remote execution.
  BUILD
  build-support/reapi-sample-server/Dockerfile
  build-support/reapi-sample-server/README.md
  build-support/reapi-sample-server/entrypoint.sh
  build-support/reapi-sample-server/run.sh
  pants.remote-execution.toml
  pants.toml
Labels: category:internal

#17198 Tell remote execution to not use remote cache internally
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_tests.rs
Labels: category:internal

#17227 Add `cache_binary_discovery` field to `remote_environment` target
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: category:internal

#17224 Streamline CI
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17229 Fix fs_util not working due to workunit init
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/fs_util/Cargo.toml
  src/rust/engine/fs/fs_util/src/main.rs
Labels: category:internal

#17231 Increase verbosity of the reapi sample server
  build-support/reapi-sample-server/entrypoint.sh
Labels: category:internal

#17232 Streamline CI (cherrypick of #17224)
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17215 Support custom post renderers in Helm deployments
  docs/markdown/Helm/helm-deployments.md
  src/python/pants/backend/helm/subsystems/post_renderer.py
  src/python/pants/backend/helm/subsystems/post_renderer_test.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/util_rules/post_renderer.py
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
  src/python/pants/backend/helm/util_rules/renderer.py
Labels: category:new feature, backend: Helm

#17238 Add CI talk to resources
  docs/markdown/Introduction/media.md
Labels: needs-cherrypick, category:documentation

#17228 Replaces `environment_migrated` bool with `environment_behavior` enum
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  pants-plugins/internal_plugins/rules_for_testing/register.py
  src/python/pants/backend/project_info/dependees.py
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/filter_targets.py
  src/python/pants/backend/project_info/list_roots.py
  src/python/pants/backend/project_info/list_targets.py
  src/python/pants/backend/project_info/paths.py
  src/python/pants/core/goals/package.py
  src/python/pants/core/goals/test.py
  src/python/pants/engine/goal.py
  src/python/pants/init/engine_initializer.py
Labels: category:internal

#17200 Set PEX_ROOT for export post-processing command. (cherry-pick of #17177)
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
Labels: category:performance

#17249 Fix constructing an Action from its action digest in `process_executor`
  src/rust/engine/process_executor/src/main.rs
Labels: category:internal

#17244 Adjust `ensure_remote_has_recursive` to succeed if content only exists remotely (Cherry-pick of #17204)
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/tests.rs
Labels: category:bugfix

#17208 [2.14.x branch] Upgrade Toolchain Pants Plugin to 0.24.0
  pants.toml
Labels: category:internal

#17245 Fix macros depending on macros from other files (Cherry-pick of #17183)
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: category:bugfix

#17254 Upgrade the Pants-provided `coverage` to version 6.5.X
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/subsystems/coverage_py.lock
Labels: category:user api change

#17243 Adjust `ensure_remote_has_recursive` to succeed if content only exists remotely (Cherry-pick of #17204)
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/tests.rs
Labels: category:bugfix

#17256 Add lcov support
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: category:new feature

#17257 Refactor `shunit2` into a proper subsystem.
  src/python/pants/backend/shell/register.py
  src/python/pants/backend/shell/shunit2.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/backend/shell/shunit2_test_runner_test.py
Labels: category:new feature

#17247 Migrates several `Goal` classes to `LOCAL_ONLY`
  src/python/pants/backend/project_info/count_loc.py
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/filedeps.py
  src/python/pants/backend/project_info/filter_targets.py
  src/python/pants/backend/project_info/list_roots.py
  src/python/pants/backend/project_info/list_targets.py
  src/python/pants/backend/project_info/paths.py
  src/python/pants/backend/project_info/peek.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/package.py
  src/python/pants/core/goals/repl.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/testutil/rule_runner.py
Labels: category:internal

#17242 Add CI talk to resources (Cherry-pick of #17238)
  docs/markdown/Introduction/media.md
Labels: category:documentation

#17241 Add CI talk to resources (Cherry-pick of #17238)
  docs/markdown/Introduction/media.md
Labels: category:documentation

#17261 Switch the sample server to using `buildbox-worker`
  build-support/reapi-sample-server/Dockerfile
  build-support/reapi-sample-server/download_install.sh
  build-support/reapi-sample-server/entrypoint.sh
Labels: category:internal

#17097 Synthesize targets for Python lockfiles
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/macros/pipenv_requirements.py
  src/python/pants/backend/python/macros/pipenv_requirements_test.py
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/macros/python_requirements_test.py
  src/python/pants/core/register.py
  src/python/pants/core/target_types.py
Labels: category:new feature

#17258 Silences the environments-related deprecations while @chrisjrn continues working on actually addressing them
  pants-plugins/internal_plugins/releases/register.py
  pants-plugins/internal_plugins/test_lockfile_fixtures/rules.py
  src/python/pants/backend/codegen/export_codegen_goal.py
  src/python/pants/backend/go/goals/debug_goals.py
  src/python/pants/backend/go/goals/generate.py
  src/python/pants/backend/java/goals/debug_goals.py
  src/python/pants/backend/kotlin/goals/debug_goals.py
  src/python/pants/backend/python/mixed_interpreter_constraints/py_constraints.py
  src/python/pants/backend/scala/goals/debug_goals.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/deploy.py
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/publish.py
  src/python/pants/engine/fs_test.py
  src/python/pants/engine/goal_test.py
  src/python/pants/engine/rules_test.py
  src/python/pants/init/logging_integration_test.py
  src/python/pants/jvm/goals/debug_goals.py
  testprojects/pants-plugins/src/python/test_pants_plugin/register.py
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: category:internal

#17271 Add Unit to user list on docsite.
  build-support/bin/generate_user_list.py
Labels: category:internal

#17272 Fix remote execution not working with remote caching and eager fetch mode
  src/rust/engine/src/context.rs
Labels: needs-cherrypick, category:bugfix

#17267 Upgrade Pex to 2.1.111.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#17133 Change fmt/lint/check docs with latest changes
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-lint-goal.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-typecheck-goal.md
Labels: category:documentation

#17274 Fix remote execution not working with remote caching and eager fetch mode (Cherry-pick of #17272)
  src/rust/engine/src/context.rs
Labels: category:bugfix

#17275 Fix remote execution not working with remote caching and eager fetch mode (Cherry-pick of #17272)
  src/rust/engine/src/context.rs
Labels: category:bugfix

#17284 Fix dep inference with empty lines in multiline imports.
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
  src/python/pants/backend/python/dependency_inference/scripts/dependency_parser_py
Labels: needs-cherrypick, category:bugfix

#17285 Fix dep inference with empty lines in multiline imports. (Cherry-pick of #17284)
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
  src/python/pants/backend/python/dependency_inference/scripts/dependency_parser_py
Labels: category:bugfix

#17281 Prepare 2.13.1rc2
  src/python/pants/notes/2.13.x.md
Labels: category:internal

#17279 Prepare 2.14.0rc4
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#17239 Prepare 2.15.0.dev5
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#17295 Fix a nit in the Getting Help docs.
  docs/markdown/Getting Help/getting-help.md
Labels: category:documentation

#17296 Fix a nit in the Getting Help docs. (Cherry-pick of #17295)
  docs/markdown/Getting Help/getting-help.md
Labels: category:documentation

#17297 Fix a nit in the Getting Help docs. (Cherry-pick of #17295)
  docs/markdown/Getting Help/getting-help.md
Labels: category:documentation

#17287 Replace uses of deprecated GHA set-output command
  .github/workflows/cache_comparison.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17298 Retry the streaming portion of downloads, as well as the setup.
  src/python/pants/engine/fs_test.py
  src/rust/engine/src/downloads.rs
Labels: needs-cherrypick, category:bugfix

#17288 Rework partitioning types for more flexibility.
  src/python/pants/backend/build_files/fmt/black/integration_test.py
  src/python/pants/backend/build_files/fmt/buildifier/rules_integration_test.py
  src/python/pants/backend/build_files/fmt/yapf/integration_test.py
  src/python/pants/backend/cc/lint/clangformat/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules_integration_test.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/docker/lint/hadolint/rules_integration_test.py
  src/python/pants/backend/go/lint/gofmt/rules_integration_test.py
  src/python/pants/backend/go/lint/golangci_lint/rules.py
  src/python/pants/backend/go/lint/golangci_lint/rules_integration_test.py
  src/python/pants/backend/go/lint/vet/rules.py
  src/python/pants/backend/go/lint/vet/rules_integration_test.py
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/goals/lint_test.py
  src/python/pants/backend/java/lint/google_java_format/rules_integration_test.py
  src/python/pants/backend/javascript/lint/prettier/rules_integration_test.py
  src/python/pants/backend/kotlin/lint/ktlint/rules_integration_test.py
  src/python/pants/backend/openapi/lint/spectral/rules.py
  src/python/pants/backend/openapi/lint/spectral/rules_integration_test.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules_integration_test.py
  src/python/pants/backend/python/lint/autoflake/rules_integration_test.py
  src/python/pants/backend/python/lint/bandit/rules.py
  src/python/pants/backend/python/lint/bandit/rules_integration_test.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/docformatter/rules_integration_test.py
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/lint/isort/rules_integration_test.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/lint/pyupgrade/rules_integration_test.py
  src/python/pants/backend/python/lint/yapf/rules_integration_test.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shellcheck/rules_integration_test.py
  src/python/pants/backend/shell/lint/shfmt/rules_integration_test.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt_integration_test.py
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/fix_test.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/util_rules/partitions.py
Labels: category:plugin api change

#17307 go: properly handle xtest packages when building
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/go/dependency_inference.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/build_pkg_target_test.py
Labels: backend: Go, category:bugfix

#17310 Replace uses of deprecated GHA set-output command (Cherry-pick of #17287)
  .github/workflows/cache_comparison.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17311 Stabilize python interpreter lookups for bootstrap
  build-support/common.sh
  src/rust/engine/build.rs
Labels: needs-cherrypick, category:internal

#17314 Stabilize python interpreter lookups for bootstrap (Cherry-pick of #17311)
  build-support/common.sh
  src/rust/engine/build.rs
Labels: category:internal

#17312 Fix incomplete cherry-pick of #17177.
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
Labels: category:bugfix

#17302 Retry the streaming portion of downloads, as well as the setup. (Cherry-pick of #17298)
  src/python/pants/engine/fs_test.py
  src/rust/engine/src/downloads.rs
Labels: category:bugfix

#17316 Prepare 2.14.0rc5.
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#17321 Fix use of `--shard` with `--debug`/`--debug-adapter` in `test`.
  src/python/pants/core/goals/test.py
Labels: category:bugfix

#17317 Simplify temp pex cleanup in Python venv export.
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
Labels: category:internal

#17255 Add one-partition-per-input partitioning strategy.
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/util_rules/partitions.py
  src/python/pants/core/util_rules/partitions_test.py
Labels: category:internal

#17313 Updates `publish` to `USES_ENVIRONMENTS`
  src/python/pants/core/goals/package.py
  src/python/pants/core/goals/publish.py
Labels: category:internal

#17223 Make `fmt` a subset of `fix`
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/fix_integration_test.py
  src/python/pants/core/goals/fix_test.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/fmt_test.py
  src/python/pants/core/goals/lint.py
Labels: category:internal

#17315 Makes `check` a `USES_ENVIRONMENTS` goal
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/check_test.py
Labels: category:internal

#17340 Include process execution strategy in Process cache key
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_tests.rs
Labels: category:bugfix

#17341 Implement cancellation of remote processes
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
Labels: category:performance

#17346 Prepare 2.14.0.
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#17134 Refactor plumbing for `test` goal to support batched tests.
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-test-goal.md
  src/python/pants/backend/codegen/protobuf/go/rules_integration_test.py
  src/python/pants/backend/go/dependency_inference_test.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/backend/go/util_rules/coverage_test.py
  src/python/pants/backend/go/util_rules/embed_integration_test.py
  src/python/pants/backend/helm/subsystems/unittest.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/test/unittest_test.py
  src/python/pants/backend/java/subsystems/junit.py
  src/python/pants/backend/kotlin/test/junit_test.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/scala/subsystems/scalatest.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/backend/scala/test/scalatest_test.py
  src/python/pants/backend/shell/shunit2.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/backend/shell/shunit2_test_runner_integration_test.py
  src/python/pants/base/specs_integration_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/jvm/test/junit.py
  src/python/pants/jvm/test/junit_test.py
Labels: category:plugin api change

#17364 Fix linebreak issues in the targets docs page.
  docs/markdown/Using Pants/concepts/targets.md
Labels: needs-cherrypick, category:documentation

#17366 Fix linebreak issues in the targets docs page. (Cherry-pick of #17364)
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#17367 Ensure PATH to shims are absolute for the protobuf buf linter.
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
Labels: category:bugfix

#17358 remote: refactor `make_execute_request` to return a struct instead of tuple
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
Labels: category:internal

#17370 modify `make_execute_request` to be async and return the input root's `DirectoryDigest`
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_execution/src/remote_cache.rs
  src/rust/engine/process_execution/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/remote_tests.rs
Labels: category:internal

#17369 Prepare release 2.13.1.
  src/python/pants/notes/2.13.x.md
Labels: category:internal
