Repository pantsbuild/pants, pull requests merged in 2023-01, with the labels that each got.

#17907 Prep for 2.16.0.dev4
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#17902 upgrade futures and tokio crates
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/src/snapshot_ops.rs
Labels: category:internal

#17913 go: update docs to remove caveats about implemented features
  docs/markdown/Go/go.md
Labels: backend: Go, category:documentation

#17911 Support catching `@rule` errors
  src/python/pants/backend/python/goals/setup_py_test.py
  src/python/pants/base/exceptions.py
  src/python/pants/engine/internals/engine_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler_test.py
  src/python/pants/engine/internals/selectors.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/python.rs
Labels: category:new feature

#17905 Support freezing command line args and env vars into pex binaries.
  docs/markdown/Python/python-goals/python-package-goal.md
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
Labels: category:new feature

#17906 Nudge more technical support toward GH Discussions
  docs/markdown/Getting Help/getting-help.md
Labels: needs-cherrypick, category:documentation

#17917 Add Payhere to user list.
  build-support/bin/generate_user_list.py
Labels: category:documentation

#17898 Allow plugins to add custom schema/authority URL handler rules
  pyproject.toml
  src/python/pants/backend/url_handlers/BUILD
  src/python/pants/backend/url_handlers/__init__.py
  src/python/pants/backend/url_handlers/s3/BUILD
  src/python/pants/backend/url_handlers/s3/__init__.py
  src/python/pants/backend/url_handlers/s3/integration_test.py
  src/python/pants/backend/url_handlers/s3/register.py
  src/python/pants/engine/download_file.py
  src/python/pants/engine/download_file_integration_test.py
  src/python/pants/engine/fs.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/init/engine_initializer.py
  src/rust/engine/src/downloads.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/types.rs
Labels: category:new feature

#17925 Blank page for "Creating a new goal" tutorial.
  docs/markdown/Tutorials/create-a-new-goal.md
Labels: category:internal

#17908 Fix errors and warnings in `./cargo doc`, and run in CI
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  src/rust/engine/Cargo.lock
  src/rust/engine/async_latch/src/lib.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/src/children.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/named_caches.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/protos/build.rs
  src/rust/engine/task_executor/src/lib.rs
Labels: category:internal

#17922 Update and reorganize resource hub
  docs/markdown/Introduction/media.md
Labels: needs-cherrypick, category:documentation

#17877 Add targets to re-wrap source files in different `SourcesField` types.
  src/python/pants/backend/experimental/go/register.py
  src/python/pants/backend/experimental/java/register.py
  src/python/pants/backend/experimental/kotlin/register.py
  src/python/pants/backend/experimental/scala/register.py
  src/python/pants/backend/python/register.py
  src/python/pants/core/register.py
  src/python/pants/core/util_rules/wrap_source.py
  src/python/pants/core/util_rules/wrap_source_intergration_test.py
  testprojects/wrap_as/BUILD
Labels: category:new feature

#17929 docs: reformat the kotlin docs to have better line breaks on readme.com
  docs/markdown/Java and Scala/kotlin.md
Labels: category:documentation

#17930 docs: add the first tutorial on writing plugins to readme docs directory
  docs/markdown/Tutorials/create-a-new-goal.md
  docs/markdown/Writing Plugins/tutorials/01-create-new-goal-with-a-custom-target.md
Labels: category:documentation

#17935 docs: add info about beta stage support of protobuf for Scala and Java
  docs/markdown/Java and Scala/jvm-overview.md
Labels: category:documentation

#17936 Fix incorrect wrapper target type name
  src/python/pants/backend/experimental/go/register.py
Labels: category:internal

#17939 Do not load the BUILD file prelude (macros) in the bootstrap scheduler.
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/init/bootstrap_scheduler.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/init/options_initializer.py
  src/python/pants/testutil/rule_runner.py
Labels: needs-cherrypick, category:bugfix

#17938 Allow `experimental_shell_command`/`experimental_run_in_sandbox` to specify `output_`s from anywhere under the buildroot
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:bugfix

#17941 Do not load the BUILD file prelude (macros) in the bootstrap scheduler. (Cherry-pick of #17939)
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/init/bootstrap_scheduler.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/init/options_initializer.py
  src/python/pants/testutil/rule_runner.py
Labels: category:bugfix

#17940 internals: improve error message when imports are found in a build file or a macro
  src/python/pants/engine/internals/parser.py
Labels: category:internal

#17948 docs: provide a link to Google Cloud Function in the backend docstring
  src/python/pants/backend/google_cloud_function/python/register.py
Labels: category:documentation

#17944 docs: add additional field 'fromfile' for options in the help-all goal output
  src/python/pants/help/help_formatter_test.py
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
Labels: category:internal

#17949 Add Kaiko to "who uses Pants" page.
  build-support/bin/generate_user_list.py
Labels: category:documentation

#17928 Adds `workdir` field for `experimental_shell_command` and friends
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/wrap_source_intergration_test.py
Labels: category:user api change

#17954 Ensure JDK is propagated into `experimental_run_in_sandbox` exection environment
  src/python/pants/backend/shell/util_rules/shell_command.py
Labels: category:internal

#17955 Rename the dependency parser script back to a regular .py suffix.
  src/python/pants/backend/python/dependency_inference/BUILD
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/scripts/BUILD
  src/python/pants/backend/python/dependency_inference/scripts/dependency_parser.py
Labels: category:internal

#17957 Ugrade Pex to 2.1.120
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  pants.toml
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#17918 Enable Linux aarch64 CI.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  pants.ci.aarch64.toml
Labels: category:internal

#17959 Support REPL command history.
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:new feature

#17960 add skip_pyright field to python test targets
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/skip_field.py
Labels: category:bugfix

#17968 add skip_pyright field to python test targets (Cherry-pick of #17960)
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/skip_field.py
Labels: category:bugfix

#17967 Build Linux wheels in custom images.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17652 New `env()` BUILD file function.
  docs/markdown/Using Pants/concepts/targets.md
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
Labels: category:new feature

#17966 go: add fields for analyzing Go standard library packages
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/util_rules/import_analysis.py
  src/python/pants/backend/go/util_rules/import_analysis_test.py
Labels: backend: Go, category:internal

#17972 Minor improvements to `PosixFS`
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/src/posixfs_tests.rs
Labels: category:internal

#17975 Go back to prior manylinux x86_64 image.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17976 Document how to update the pants script.
  docs/markdown/Docker/tagging-docker-images.md
  docs/markdown/Getting Started/getting-started/installation.md
Labels: needs-cherrypick, category:documentation

#17979 Document how to update the pants script. (Cherry-pick of #17976)
  docs/markdown/Docker/tagging-docker-images.md
  docs/markdown/Getting Started/getting-started/installation.md
Labels: category:documentation

#17971 go: gather and link transitive prebuilt object files for cgo mode
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/cgo.py
Labels: backend: Go, category:bugfix

#17973 go: introduce _go_sdk and _go_sdk_package target types for SDK analysis
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/codegen/protobuf/go/rules_integration_test.py
  src/python/pants/backend/experimental/go/register.py
  src/python/pants/backend/go/dependency_inference_test.py
  src/python/pants/backend/go/goals/check_test.py
  src/python/pants/backend/go/goals/generate_test.py
  src/python/pants/backend/go/goals/package_binary_integration_test.py
  src/python/pants/backend/go/goals/tailor_test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/lint/golangci_lint/rules_integration_test.py
  src/python/pants/backend/go/lint/vet/rules_integration_test.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/target_type_rules_test.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/assembly_integration_test.py
  src/python/pants/backend/go/util_rules/build_opts_test.py
  src/python/pants/backend/go/util_rules/build_pkg_target_test.py
  src/python/pants/backend/go/util_rules/cgo_test.py
  src/python/pants/backend/go/util_rules/coverage_test.py
  src/python/pants/backend/go/util_rules/embed_integration_test.py
  src/python/pants/backend/go/util_rules/first_party_pkg_test.py
  src/python/pants/backend/go/util_rules/import_analysis.py
Labels: backend: Go, category:internal

#17969 fix type in `check` help output
  src/python/pants/core/goals/check.py
Labels: category:documentation

#17982 go: track whether a package to build is in stdlib
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/cgo.py
Labels: backend: Go, category:internal

#17980 Pyright should grab non-transitive dependencies and make them available in the sandbox (Cherry-pick of #17235)
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
Labels: category:bugfix

#17983 CI: install Go for now into wheel building jobs
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17984 go: compile Go SDK when building internal binaries
  src/python/pants/backend/go/go_sources/load_go_binary.py
  src/python/pants/backend/go/goals/BUILD
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_test.py
Labels: backend: Go, category:internal

#17974 Remove potential for panics from spawn APIs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/logging/src/lib.rs
  src/rust/engine/logging/src/logger.rs
  src/rust/engine/nailgun/src/server.rs
  src/rust/engine/process_execution/src/bounded.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
  src/rust/engine/process_execution/src/remote.rs
  src/rust/engine/sharded_lmdb/src/lib.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/session.rs
  src/rust/engine/task_executor/src/lib.rs
  src/rust/engine/ui/src/console_ui.rs
  src/rust/engine/watch/src/lib.rs
Labels: category:internal

#17989 Pre-install go on the aarch64 wheel build image.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  build-support/wheel_build_aarch64/Dockerfile
Labels: category:internal

#17990 Use new aarch64 wheel build image.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17988 go: use preexisting constant for testmain filename
  src/python/pants/backend/go/util_rules/tests_analysis.py
Labels: backend: Go, category:internal

#17991 Upgrade to Rust 1.66.1
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
Labels: category:internal

#17985 Streamlining refactor of dependency_parser.py
  src/python/pants/backend/python/dependency_inference/scripts/dependency_parser.py
Labels: category:internal

#17996 Adds workunit for interactive processes. (Cherry-pick of #17544)
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#18002 docs: fix markdown inline code typo in a docstring
  src/python/pants/backend/python/goals/coverage_py.py
Labels: category:documentation

#17915 docs: generate a JSON schema file to be used in IDEs when editing pants.toml
  build-support/bin/BUILD
  build-support/bin/check_json_schema.py
  build-support/bin/generate_json_schema.py
  build-support/bin/generate_json_schema_test.py
  build-support/bin/json_schema_testdata/BUILD
  build-support/bin/json_schema_testdata/all_help_sample_output.json
Labels: category:documentation

#17890 docs: add tutorial to get started writing plugins: No 2
  docs/markdown/Tutorials/integrate-new-goal-with-the-repository.md
Labels: category:documentation

#18001 Clarify runtime vs. complete_platforms for serverless.
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/awslambda/python/target_types_test.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types_test.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:documentation

#18011 Remove macOS 11 x86_64 wheel builds. (Cherry-pick of #18010)
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#18012 Remove macOS 11 x86_64 wheel builds. (Cherry-pick of #18010)
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#18014 Let pyright see dependencies in other source roots.
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
Labels: category:bugfix

#17921 Add Daniel Goldman and Darcy Shen to team page
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: needs-cherrypick, category:documentation

#18000 WSL disclaimer in Getting Started/Prerequisites
  docs/markdown/Getting Started/getting-started/prerequisites.md
Labels: category:documentation

#18020 Kill use of MODE=debug for PR wheel builds.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17999 Prepare the 2.14.1 release.
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#17998 Prepare the 2.16.0.dev5 release.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#18021 Speed up multi-python wheel shards.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#18025 Fix wheel reversioning for Linux aarch64.
  build-support/bin/_release_helper.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#17993 go: use a directory within sandbox for cgo objects from stdlib packages
  src/python/pants/backend/go/util_rules/cgo.py
Labels: backend: Go, category:internal

#17995 go: use a Go binary to check for golang assembly files
  src/python/pants/backend/go/go_sources/BUILD
  src/python/pants/backend/go/go_sources/asm_check/BUILD
  src/python/pants/backend/go/go_sources/asm_check/__init__.py
  src/python/pants/backend/go/go_sources/asm_check/asm_check.go
  src/python/pants/backend/go/util_rules/build_pkg.py
Labels: backend: Go, category:internal

#18026 Fix caching of PATH lookups in remote execution
  src/python/pants/engine/internals/platform_rules.py
Labels: needs-cherrypick, category:bugfix

#18028 go: missed some `obj_dir_path` refactors
  src/python/pants/backend/go/util_rules/cgo.py
Labels: backend: Go, category:internal

#17596 lint: add pydocstyle python backend
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/python/lint/pydocstyle/BUILD
  src/python/pants/backend/python/lint/pydocstyle/__init__.py
  src/python/pants/backend/python/lint/pydocstyle/pydocstyle.lock
  src/python/pants/backend/python/lint/pydocstyle/register.py
  src/python/pants/backend/python/lint/pydocstyle/rules.py
  src/python/pants/backend/python/lint/pydocstyle/rules_integration_test.py
  src/python/pants/backend/python/lint/pydocstyle/skip_field.py
  src/python/pants/backend/python/lint/pydocstyle/subsystem.py
Labels: category:new feature

#18030 Added support for discovering and patching `pyright` config files (cherry-pick of #17771)
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
Labels: category:new feature

#18018 docs: add tutorial to get started writing plugins: No 3
  docs/markdown/Tutorials/test-custom-plugin-goal.md
Labels: category:documentation

#18033 docs: add pydocstyle to the docs and help reference
  build-support/bin/generate_docs.py
  docs/markdown/Python/python-goals/python-lint-goal.md
  docs/markdown/Python/python.md
  docs/markdown/Python/python/python-linters-and-formatters.md
  src/python/pants/bin/BUILD
Labels: category:documentation

#18029 Move group_by_dir to src/python/pants/util/dirutil.py
  docs/markdown/Tutorials/integrate-new-goal-with-the-repository.md
  pants-plugins/internal_plugins/test_lockfile_fixtures/rules.py
  src/python/pants/backend/cc/goals/tailor.py
  src/python/pants/backend/codegen/avro/tailor.py
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/codegen/protobuf/tailor.py
  src/python/pants/backend/codegen/soap/tailor.py
  src/python/pants/backend/codegen/thrift/tailor.py
  src/python/pants/backend/go/goals/generate.py
  src/python/pants/backend/go/goals/tailor.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
  src/python/pants/backend/java/goals/tailor.py
  src/python/pants/backend/javascript/goals/tailor.py
  src/python/pants/backend/kotlin/goals/tailor.py
  src/python/pants/backend/openapi/goals/tailor.py
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/scala/goals/tailor.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/shell/goals/tailor.py
  src/python/pants/backend/swift/goals/tailor.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/goals/tailor.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
  src/python/pants/util/dirutil.py
Labels: category:internal

#18034 Simplify remote store load_bytes API
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
Labels: category:internal

#18036 Properly set pex_root when running python sources in-sandbox. (Cherry-pick of #17750)
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
Labels: category:internal

#18035 Streamline local dist handling when running python sources. (Cherry-pick of #17742)
  src/python/pants/backend/python/goals/run_helper.py
Labels: category:bugfix

#18038 Prepare `2.15.0rc2`.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#18037 Upgrade Pex to 2.1.121.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18041 Remove some dead code from `lockfile.py`
  src/python/pants/backend/python/goals/lockfile.py
Labels: category:plugin api change

#17997 Make the python dep inference script extensible.
  pants.toml
  src/python/pants/backend/python/dependency_inference/BUILD
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/scripts/BUILD
  src/python/pants/backend/python/dependency_inference/scripts/_pants_dep_parser/__init__.py
  src/python/pants/backend/python/dependency_inference/scripts/_pants_dep_parser/dependency_visitor_base.py
  src/python/pants/backend/python/dependency_inference/scripts/_pants_dep_parser/general_dependency_visitor.py
  src/python/pants/backend/python/dependency_inference/scripts/_pants_dep_parser/main.py
  src/python/pants/backend/python/goals/debug_goals.py
Labels: category:plugin api change

#18043 Make mypy cache per-repo
  src/python/pants/backend/python/typecheck/mypy/rules.py
Labels: needs-cherrypick, category:bugfix

#18049 Bump to version `0.26.0` of the Toolchain plugin.
  pants.toml
Labels: category:internal

#18047 Start phasing out `frozen_after_init`
  pants-plugins/internal_plugins/test_lockfile_fixtures/lockfile_fixture.py
  src/python/pants/BUILD
  src/python/pants/backend/go/util_rules/embedcfg.py
  src/python/pants/backend/go/util_rules/sdk.py
  src/python/pants/backend/helm/subsystems/post_renderer.py
  src/python/pants/backend/helm/util_rules/renderer.py
  src/python/pants/backend/helm/util_rules/tool.py
  src/python/pants/backend/helm/utils/yaml.py
  src/python/pants/backend/openapi/util_rules/generator_process.py
  src/python/pants/backend/project_info/dependents.py
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/util_rules/local_dists.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/conftest.py
  src/python/pants/conftest_test.py
Labels: category:internal

#18046 It's time for more string cleaning
  src/python/pants/jvm/resolve/coursier_setup.py
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/option/alias.py
  src/python/pants/option/alias_test.py
  src/python/pants/option/arg_splitter_test.py
  src/python/pants/option/config.py
  src/python/pants/option/custom_types.py
  src/python/pants/option/errors.py
  src/python/pants/option/global_options.py
  src/python/pants/option/option_types.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_fingerprinter.py
  src/python/pants/option/options_integration_test.py
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
  src/python/pants/option/subsystem.py
  src/python/pants/pantsd/service/scheduler_service.py
  src/python/pants/source/source_root.py
  src/python/pants/testutil/rule_runner.py
  src/python/pants/util/collections.py
  src/python/pants/util/frozendict.py
  src/python/pants/util/meta_test.py
  src/python/pants/util/ordered_set_test.py
  src/python/pants/util/strutil_test.py
  src/python/pants/vcs/git_test.py
  tests/python/pants_test/init/test_plugin_resolver.py
Labels: category:internal

#18051 Cosmetic fix for current value information in help output for pass-through arguments.
  src/python/pants/option/parser.py
Labels: category:documentation

#18009 docker: Allow overriding FROM args when determining upstream image dependencies
  src/python/pants/backend/docker/util_rules/dependencies.py
  src/python/pants/backend/docker/util_rules/dependencies_test.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: category:bugfix

#18065 Nudge more technical support toward GH Discussions (Cherry-pick of #17906)
  docs/markdown/Getting Help/getting-help.md
Labels: category:documentation

#18066 Add Daniel Goldman and Darcy Shen to team page (Cherry-pick of #17921)
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#18068 Update and reorganize resource hub (#17922)
  docs/markdown/Introduction/media.md
Labels: category:documentation

#18064 Add `environment=` to `experimental_shell_command`. (Cherry-pick of #17575)
  src/python/pants/backend/shell/shell_command.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/core/util_rules/environments.py
Labels: category:new feature

#18063 Fix validation of release PEXes. (Cherry-pick of #17785)
  build-support/bin/_release_helper.py
Labels: category:internal

#18062 Fix caching of PATH lookups in remote execution (Cherry-pick of #18026)
  src/python/pants/engine/internals/platform_rules.py
Labels: category:bugfix

#18074 Front matter for new tutorial pages.
  docs/markdown/Tutorials/advanced-plugin-concepts.md
  docs/markdown/Tutorials/test-custom-plugin-goal.md
Labels: category:documentation

#18056 Document new pants launcher binary, aka scie-pants.
  docs/markdown/Getting Started/getting-started/installation.md
  docs/markdown/Getting Started/getting-started/manual-installation.md
  docs/markdown/Getting Started/getting-started/prerequisites.md
Labels: category:documentation

#18069 Docs: improve docs on handling option values in cli (Cherry-pick of #17506)
  docs/markdown/Using Pants/concepts/options.md
Labels: category:documentation

#18075 Document new pants launcher binary, aka scie-pants. (Cherry-pick of #18056)
  docs/markdown/Getting Started/getting-started/installation.md
  docs/markdown/Getting Started/getting-started/manual-installation.md
  docs/markdown/Getting Started/getting-started/prerequisites.md
Labels: category:documentation

#18077 Explicitly use "python" ijson backend (cherry-pick of #17787)
  pyproject.toml
  src/python/pants/backend/go/util_rules/import_analysis.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
Labels: category:bugfix

#17821 Add yamllint as a lint tool for YAML sources
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/experimental/tools/yamllint/register.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/tools/yamllint/BUILD
  src/python/pants/backend/tools/yamllint/__init__.py
  src/python/pants/backend/tools/yamllint/rules.py
  src/python/pants/backend/tools/yamllint/rules_integration_test.py
  src/python/pants/backend/tools/yamllint/subsystem.py
  src/python/pants/backend/tools/yamllint/yamllint.lock
  src/python/pants/core/goals/tailor_test.py
  src/python/pants/util/dirutil.py
  src/python/pants/util/dirutil_test.py
Labels: category:new feature

#18052 Migrate remaining frozen_after_init
  docs/markdown/Contributions/development/style-guide.md
  docs/markdown/Writing Plugins/rules-api/rules-api-concepts.md
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/python_sources.py
  src/python/pants/build_graph/address.py
  src/python/pants/build_graph/build_file_aliases.py
  src/python/pants/conftest.py
  src/python/pants/conftest_test.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/repl.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/config_files.py
  src/python/pants/core/util_rules/partitions.py
  src/python/pants/core/util_rules/source_files.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/engine/addresses.py
  src/python/pants/engine/desktop.py
  src/python/pants/engine/env_vars.py
  src/python/pants/engine/fs.py
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/process.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/engine/unions.py
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/dependency_inference/artifact_mapper.py
  src/python/pants/jvm/jar_tool/jar_tool.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/shading/rules.py
  src/python/pants/option/parser.py
  src/python/pants/pantsd/service/pants_service.py
  src/python/pants/source/source_root.py
Labels: category:internal

#18092 Inject a path-safe target spec into `experimental_shell_command` etc processes
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_integration_test.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:bugfix, backend: Shell

#18088 Ensure we set the region when deploying to S3.
  build-support/bin/deploy_to_s3.py
Labels: category:internal

#18078 go: use debug log level when checking C compiler option support (Cherry-pick of #17606)
  src/python/pants/backend/go/util_rules/cgo.py
Labels: category:internal

#18095 go: check for out of range indices in asm check helper
  src/python/pants/backend/go/go_sources/asm_check/asm_check.go
Labels: backend: Go, category:internal

#18096 go: pass source file paths to compiler via config file
  src/python/pants/backend/go/util_rules/build_pkg.py
Labels: backend: Go, category:internal

#18099 use Go 1.19.x in CI
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: backend: Go, category:internal

#18097 go: rename generated test main output
  src/python/pants/backend/go/go_sources/generate_testmain/main.go
  src/python/pants/backend/go/util_rules/tests_analysis.py
Labels: backend: Go, category:internal

#17943 Add new experimental backend for CUE with initial support for the `lint` goal.
  src/python/pants/backend/cue/BUILD
  src/python/pants/backend/cue/__init__.py
  src/python/pants/backend/cue/goals/BUILD
  src/python/pants/backend/cue/goals/__init__.py
  src/python/pants/backend/cue/goals/fix.py
  src/python/pants/backend/cue/goals/fix_test.py
  src/python/pants/backend/cue/rules.py
  src/python/pants/backend/cue/subsystem.py
  src/python/pants/backend/cue/target_types.py
  src/python/pants/backend/experimental/cue/BUILD
  src/python/pants/backend/experimental/cue/__init__.py
  src/python/pants/backend/experimental/cue/register.py
  src/python/pants/bin/BUILD
Labels: category:new feature

#18032 go: add basic parsing of vendor/modules.txt files
  src/python/pants/backend/go/go_sources/BUILD
  src/python/pants/backend/go/go_sources/parse_vendor_modules/BUILD
  src/python/pants/backend/go/go_sources/parse_vendor_modules/__init__.py
  src/python/pants/backend/go/go_sources/parse_vendor_modules/parse.go
  src/python/pants/backend/go/go_sources/parse_vendor_modules/semver.go
  src/python/pants/backend/go/util_rules/vendor.py
  src/python/pants/backend/go/util_rules/vendor_test.py
Labels: backend: Go, category:internal

#18098 go: introduce import maps package attribute
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/import_analysis.py
  src/python/pants/backend/go/util_rules/import_analysis_test.py
Labels: backend: Go, category:internal

#18102 docs: tidy up Writing plugins : rules-api directory files (Cherry-pick of #17710)
  docs/markdown/Writing Plugins/rules-api/rules-api-and-target-api.md
  docs/markdown/Writing Plugins/rules-api/rules-api-concepts.md
  docs/markdown/Writing Plugins/rules-api/rules-api-file-system.md
  docs/markdown/Writing Plugins/rules-api/rules-api-goal-rules.md
  docs/markdown/Writing Plugins/rules-api/rules-api-installing-tools.md
  docs/markdown/Writing Plugins/rules-api/rules-api-process.md
  docs/markdown/Writing Plugins/rules-api/rules-api-testing.md
  docs/markdown/Writing Plugins/rules-api/rules-api-tips.md
Labels: category:documentation

#18105 docs: mention name clashing between custom goals and options when writing plugins (Cherry-pick of #17899)
  docs/markdown/Writing Plugins/rules-api/rules-api-goal-rules.md
  docs/markdown/Writing Plugins/rules-api/rules-api-subsystems.md
Labels: category:documentation

#18107 docs: add tutorials to get started writing plugins (Cherry-pick)
  docs/markdown/Tutorials/advanced-plugin-concepts.md
  docs/markdown/Tutorials/create-a-new-goal.md
  docs/markdown/Tutorials/test-custom-plugin-goal.md
Labels: category:documentation

#18103 docs: fix markdown inline code typo in a docstring (Cherry-pick of #18002)
  src/python/pants/backend/python/goals/coverage_py.py
Labels: category:documentation

#18106 Add support for `fmt` cue files.
  src/python/pants/backend/cue/goals/fix.py
  src/python/pants/backend/cue/goals/fix_test.py
  src/python/pants/backend/cue/goals/lint.py
  src/python/pants/backend/cue/goals/lint_test.py
  src/python/pants/backend/cue/rules.py
  src/python/pants/backend/cue/target_types.py
  src/python/pants/backend/experimental/cue/register.py
Labels: category:new feature

#18104 go: merge some tests of the test goal to impove CI times
  src/python/pants/backend/go/goals/test_test.py
Labels: backend: Go, category:internal

#17945 Add experimental backend for ruff with lint and fmt goals
  build-support/bin/_generate_all_lockfiles_helper.py
  src/python/pants/backend/experimental/python/lint/ruff/BUILD
  src/python/pants/backend/experimental/python/lint/ruff/__init__.py
  src/python/pants/backend/experimental/python/lint/ruff/register.py
  src/python/pants/backend/python/lint/ruff/BUILD
  src/python/pants/backend/python/lint/ruff/__init__.py
  src/python/pants/backend/python/lint/ruff/ruff.lock
  src/python/pants/backend/python/lint/ruff/rules.py
  src/python/pants/backend/python/lint/ruff/rules_integration_test.py
  src/python/pants/backend/python/lint/ruff/skip_field.py
  src/python/pants/backend/python/lint/ruff/subsystem.py
  src/python/pants/backend/python/lint/ruff/subsystem_test.py
  src/python/pants/bin/BUILD
Labels: category:new feature, backend: Python

#17914 go: support building the Go SDK from scratch
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/codegen/protobuf/go/rules_integration_test.py
  src/python/pants/backend/experimental/go/register.py
  src/python/pants/backend/go/dependency_inference_test.py
  src/python/pants/backend/go/go_sources/load_go_binary.py
  src/python/pants/backend/go/goals/package_binary.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/target_type_rules_test.py
  src/python/pants/backend/go/util_rules/build_opts_test.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/build_pkg_target_test.py
  src/python/pants/backend/go/util_rules/build_pkg_test.py
  src/python/pants/backend/go/util_rules/implicit_linker_deps.py
  src/python/pants/backend/go/util_rules/import_analysis.py
  src/python/pants/backend/go/util_rules/import_analysis_test.py
  src/python/pants/backend/go/util_rules/import_config.py
  src/python/pants/backend/go/util_rules/import_config_test.py
  src/python/pants/backend/go/util_rules/link.py
  src/python/pants/backend/go/util_rules/link_defs.py
Labels: backend: Go, category:internal

#18113 go: add `environment` field to `go_binary`
  src/python/pants/backend/go/goals/package_binary.py
  src/python/pants/backend/go/target_types.py
Labels: backend: Go, category:new feature

#18119 Prepare the 2.16.0.dev6 release.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#18118 go: detect when `go.sum` needs additional entries filled in (Cherrypick of #17811)
  src/python/pants/backend/go/goals/debug_goals.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/embed_integration_test.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg_test.py
Labels: category:bugfix

#18123 Don't update old release notes.
  docs/markdown/Releases/versions/release-notes-1-26.md
  docs/markdown/Releases/versions/release-notes-1-27.md
  docs/markdown/Releases/versions/release-notes-1-29.md
  docs/markdown/Releases/versions/release-notes-1-30.md
  docs/markdown/Releases/versions/release-notes-2-1.md
  docs/markdown/Releases/versions/release-notes-2-2.md
  docs/markdown/Releases/versions/release-notes-2-3.md
  docs/markdown/Releases/versions/release-notes-2-5.md
Labels: category:documentation

#18061 Make mypy cache per-repo (Cherry-pick of #18043)
  src/python/pants/backend/python/typecheck/mypy/rules.py
Labels: category:bugfix

#18127 deprecate `frozen_after_init`
  src/python/pants/util/meta.py
Labels: category:plugin api change

#18128 Run `pyupgrade` until convergance
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules_integration_test.py
Labels: needs-cherrypick, category:bugfix

#18130 Run `pyupgrade` until convergance (Cherry-pick of #18128)
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules_integration_test.py
Labels: category:bugfix

#18120 Recommend checking the pantsup.sh script in.
  README.md
  build-support/bin/classify_changed_files.py
  build-support/bin/classify_changed_files_test.py
  docs/markdown/Getting Started/getting-started/installation.md
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#17347 Print diff report when generating new lockfiles.
  pants.toml
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/lockfile_diff.py
  src/python/pants/backend/python/util_rules/lockfile_diff_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/generate_lockfiles_test.py
  src/python/pants/help/maybe_color.py
  src/python/pants/jvm/goals/lockfile.py
  src/python/pants/jvm/goals/lockfile_test.py
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/util/frozendict.py
Labels: category:new feature

#18133 Change to Pantsbuild's custom YouTube url
  docs/markdown/Introduction/media.md
Labels: category:documentation

#18079 Add Pylint post
  docs/markdown/Introduction/media.md
Labels: needs-cherrypick, category:documentation

#18137 Document the new get-pants.sh name.
  docs/markdown/Getting Started/getting-started/installation.md
Labels: category:documentation
