Repository pantsbuild/pants, pull requests merged in 2023-12, with the labels that each got.

#20250 Infers Django migrations and management commands as dependencies of `apps.py`
  src/python/pants/backend/python/framework/django/dependency_inference.py
  src/python/pants/backend/python/framework/django/dependency_inference_test.py
  src/python/pants/backend/python/framework/django/detect_apps.py
  src/python/pants/backend/python/framework/django/detect_apps_test.py
  src/python/pants/backend/python/framework/django/scripts/app_detector.py
Labels: category:new feature, backend: Python

#20239 Fix wrong jar path given to shade jar process
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/package/deploy_jar_test.py
Labels: needs-cherrypick, category:bugfix

#20254 Fix wrong jar path given to shade jar process (Cherry-pick of #20239)
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/package/deploy_jar_test.py
Labels: category:bugfix

#20262 Include guidance on skipping files under Black & isort
  docs/markdown/Python/python/python-linters-and-formatters.md
Labels: category:documentation

#20252 typescript: add tailor goal
  src/python/pants/backend/experimental/typescript/register.py
  src/python/pants/backend/javascript/goals/tailor.py
  src/python/pants/backend/typescript/goals/BUILD
  src/python/pants/backend/typescript/goals/__init__.py
  src/python/pants/backend/typescript/goals/tailor.py
  src/python/pants/backend/typescript/goals/tailor_test.py
  src/python/pants/backend/typescript/target_types.py
  testprojects/src/ts/frontend/config/app.ts
  testprojects/src/ts/frontend/deployment/index.ts
  testprojects/src/ts/frontend/services/browser.test.ts
  testprojects/src/ts/frontend/services/browser.ts
  testprojects/src/ts/frontend/utils/helpers.ts
Labels: category:new feature

#20267 Add support for Scalac plugins in BSP
  src/python/pants/backend/scala/bsp/rules.py
Labels: backend: JVM, category:new feature, bsp

#20264 DRY when handling Scala version values
  src/python/pants/backend/codegen/protobuf/scala/dependency_inference.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/java/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/scala/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/backend/scala/compile/scalac.py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
  src/python/pants/backend/scala/resolve/lockfile.py
  src/python/pants/backend/scala/subsystems/scala.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/backend/scala/util_rules/BUILD
  src/python/pants/backend/scala/util_rules/versions.py
  src/python/pants/backend/scala/util_rules/versions_test.py
  src/python/pants/jvm/target_types.py
Labels: backend: JVM, category:internal

#20269 Use fork of indicatif to work around output truncation
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: needs-cherrypick, category:bugfix

#20277 Use fork of indicatif to work around output truncation (Cherry-pick of #20269)
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:bugfix

#20273 allow passing --timeout along to helm commands
  src/python/pants/backend/helm/subsystems/helm.py
Labels: category:new feature

#20279 Prepare 2.19.0rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20278 Prepare 2.20.0.dev2
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20237 Allow passing arbitrary args to PEX invocation when building FaaS artifacts
  docs/markdown/Python/python-integrations/awslambda-python.md
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/backend/python/util_rules/pex_venv.py
  src/python/pants/backend/python/util_rules/pex_venv_test.py
Labels: needs-cherrypick, category:new feature

#20280 Allow passing arbitrary args to PEX invocation when building FaaS artifacts (Cherry-pick of #20237)
  docs/markdown/Python/python-integrations/awslambda-python.md
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/backend/python/util_rules/pex_venv.py
  src/python/pants/backend/python/util_rules/pex_venv_test.py
Labels: category:new feature

#20272 javascript,typescript: refactor common code from tailor goal into shared library
  src/python/pants/backend/javascript/goals/tailor.py
  src/python/pants/backend/javascript/goals/tailor_test.py
  src/python/pants/backend/javascript/target_types.py
  src/python/pants/backend/typescript/goals/tailor.py
  src/python/pants/backend/typescript/goals/tailor_test.py
  src/python/pants/core/util_rules/ownership.py
  src/python/pants/core/util_rules/source_files.py
Labels: category:internal

#20204 helm: add option to pass `--quiet` when linting charts
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/helm/target_types.py
Labels: category:new feature

#20281 Allow passing arbitrary args to PEX invocation when building FaaS artifacts (Cherry-pick of #20237)
  docs/markdown/Python/python-integrations/awslambda-python.md
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/backend/python/util_rules/pex_venv.py
  src/python/pants/backend/python/util_rules/pex_venv_test.py
Labels: category:new feature

#20284 upgrade to Rust v1.74.1
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/rust-toolchain
Labels: category:internal

#20290 Don't use tabbed-codeblock in Markdown
  docs/markdown/Writing Plugins/target-api/target-api-concepts.md
Labels: category:documentation

#20288 add module mapping for honeycomb-opentelemetry
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#20230 Fix: run `terraform validate` on modules again
  docs/markdown/Terraform/terraform-overview.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-general-subsystems.md
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/goals/check_test.py
Labels: bug, needs-cherrypick, category:bugfix, backend: Terraform

#20276 fix: terraform_relpath works on files not in direct subpath
  src/python/pants/backend/terraform/utils.py
  src/python/pants/backend/terraform/utils_test.py
Labels: needs-cherrypick, category:bugfix, backend: Terraform

#20301 fix: terraform_relpath works on files not in direct subpath (Cherry-pick of #20276)
  src/python/pants/backend/terraform/utils.py
  src/python/pants/backend/terraform/utils_test.py
Labels: category:bugfix

#20299 Fix: run `terraform validate` on modules again (Cherry-pick of #20230)
  docs/markdown/Terraform/terraform-overview.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-general-subsystems.md
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/goals/check_test.py
Labels: category:bugfix

#20298 Fix: run `terraform validate` on modules again (Cherry-pick of #20230)
  docs/markdown/Terraform/terraform-overview.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-general-subsystems.md
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/goals/check_test.py
Labels: category:bugfix

#20300 fix: terraform_relpath works on files not in direct subpath (Cherry-pick of #20276)
  src/python/pants/backend/terraform/utils.py
  src/python/pants/backend/terraform/utils_test.py
Labels: category:bugfix

#20308 Prepare 2.19.0rc2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20289 enable pyupgrade for pants itself as a regular backend
  build-support/bin/terraform_tool_versions.py
  build-support/bin/terraform_tool_versions_test.py
  pants.toml
  src/python/pants/backend/codegen/protobuf/go/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/backend/go/lint/golangci_lint/rules.py
  src/python/pants/backend/go/lint/golangci_lint/rules_integration_test.py
  src/python/pants/backend/go/testutil.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/helm/subsystems/k8s_parser_main.py
  src/python/pants/backend/helm/subsystems/post_renderer_main.py
  src/python/pants/backend/openapi/lint/spectral/rules.py
  src/python/pants/backend/python/framework/django/detect_apps.py
  src/python/pants/backend/python/framework/stevedore/python_target_dependencies_test.py
  src/python/pants/backend/python/lint/isort/rules_integration_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/scripts/pep660_backend_wrapper.py
  src/python/pants/base/exception_sink.py
  src/python/pants/core/goals/export.py
  src/python/pants/engine/fs.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/rules_test.py
  src/python/pants/util/collections_test.py
  src/python/pants_release/reversion.py
  tests/python/pants_test/pantsd/test_lock.py
Labels: category:internal

#20319 Ensure `experimental_test_shell_command` runs in relevant environment
  src/python/pants/backend/shell/goals/test.py
Labels: needs-cherrypick, category:bugfix

#20320 Ensure `experimental_test_shell_command` runs in relevant environment (Cherry-pick of #20319)
  src/python/pants/backend/shell/goals/test.py
Labels: category:bugfix

#20238 Support coursier `--force-version` argument
  src/python/pants/jvm/resolve/common.py
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
  src/python/pants/jvm/target_types.py
Labels: category:new feature

#20321 Ensure `experimental_test_shell_command` runs in relevant environment (Cherry-pick of #20319)
  src/python/pants/backend/shell/goals/test.py
Labels: category:bugfix

#20307 Allow docker image pulling without creds
  src/rust/engine/process_execution/docker/src/docker.rs
Labels: needs-cherrypick, category:bugfix

#20325 Allow docker image pulling without creds (Cherry-pick of #20307)
  src/rust/engine/process_execution/docker/src/docker.rs
Labels: category:bugfix

#20326 Change the slug of the Shell backend doc.
  docs/markdown/Introduction/welcome-to-pants.md
  docs/markdown/Shell/shell.md
  docs/markdown/Using Pants/concepts/enabling-backends.md
Labels: category:documentation

#20316 Implement string interpolation for config values in Rust.
  docs/markdown/Using Pants/concepts/options.md
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/options/Cargo.toml
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
  src/rust/engine/options/src/lib.rs
Labels: category:internal

#20329 Update team.md
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#20330 Support allow_pantsrc to turn off pantsrc processing in rust
  src/rust/engine/client/src/client_tests.rs
  src/rust/engine/client/src/main.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/pantsd/src/pantsd_testing.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: category:internal

#20332 Fix algorithm for gathering prebuilt Go object files
  src/python/pants/backend/go/util_rules/build_pkg.py
Labels: backend: Go, category:bugfix

#20314 Make docker_environment's Pants-provided-PBS an absolute path
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/adhoc_binaries_test.py
Labels: needs-cherrypick, category:bugfix

#20339 Make docker_environment's Pants-provided-PBS an absolute path (Cherry-pick of #20314)
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/adhoc_binaries_test.py
Labels: category:bugfix

#20285 Support dependency inference with JVM codegen backends
  src/python/pants/backend/codegen/protobuf/java/rules.py
  src/python/pants/backend/codegen/protobuf/java/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/java/symbol_mapper.py
  src/python/pants/backend/codegen/protobuf/jvm_symbol_mapper.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/codegen/protobuf/scala/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/scala/symbol_mapper.py
  src/python/pants/backend/codegen/soap/java/dependency_inference.py
  src/python/pants/backend/codegen/soap/java/rules.py
  src/python/pants/backend/codegen/soap/java/rules_integration_test.py
  src/python/pants/backend/codegen/soap/java/symbol_mapper.py
  src/python/pants/backend/codegen/thrift/apache/java/rules.py
  src/python/pants/backend/codegen/thrift/apache/java/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/apache/java/symbol_mapper.py
  src/python/pants/backend/codegen/thrift/jvm_symbol_mapper.py
  src/python/pants/backend/codegen/thrift/scrooge/java/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/java/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/scrooge/java/symbol_mapper.py
  src/python/pants/backend/codegen/thrift/scrooge/scala/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/scala/rules_integration_test.py
  src/python/pants/backend/codegen/thrift/scrooge/scala/scrooge.test.lock
  src/python/pants/backend/codegen/thrift/scrooge/scala/symbol_mapper.py
  src/python/pants/backend/codegen/thrift/thrift_parser.py
  src/python/pants/backend/codegen/thrift/thrift_parser_test.py
  src/python/pants/backend/experimental/openapi/codegen/java/register.py
  src/python/pants/backend/experimental/openapi/register.py
  src/python/pants/backend/openapi/codegen/java/rules.py
  src/python/pants/backend/openapi/codegen/java/rules_integration_test.py
  src/python/pants/backend/openapi/codegen/java/symbol_mapper.py
  src/python/pants/backend/openapi/target_types.py
Labels: backend: JVM, category:new feature, backend: Thrift, backend: OpenAPI, backend: Protobuf

#20346 DRY gather config files by directories
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/scala/lint/scalafmt/subsystem.py
  src/python/pants/backend/tools/yamllint/rules.py
  src/python/pants/backend/tools/yamllint/subsystem.py
  src/python/pants/core/util_rules/config_files.py
  src/python/pants/core/util_rules/config_files_test.py
  src/python/pants/util/dirutil_test.py
Labels: backend: JVM, category:internal

#20317 use pyupgrade to modernize syntax forward to 3.8
  build-support/bin/generate_docs.py
  pants.toml
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/go/util_rules/cgo.py
  src/python/pants/backend/go/util_rules/coverage_html.py
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/backend/project_info/peek.py
  src/python/pants/backend/python/framework/django/dependency_inference.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/backend/python/util_rules/partition.py
  src/python/pants/backend/python/util_rules/scripts/BUILD
  src/python/pants/base/parse_context.py
  src/python/pants/base/specs.py
  src/python/pants/bsp/protocol.py
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/multi_tool_goal_helper.py
  src/python/pants/core/util_rules/partitions.py
  src/python/pants/engine/internals/dep_rules.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/rules.py
  src/python/pants/engine/target.py
  src/python/pants/help/help_printer.py
  src/python/pants/option/config.py
  src/python/pants/pantsd/pants_daemon_core.py
  src/python/pants/testutil/python_interpreter_selection.py
  src/python/pants/testutil/skip_utils.py
  src/python/pants/util/dirutil.py
  src/python/pants_release/reversion.py
  testprojects/src/python/coordinated_runs/waiter.py
  testprojects/src/python/hello/greet/greet.py
Labels: category:internal

#20295 add grpcio-health-checking to default module mappings
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal, backend: Python

#20255 Refactor: DRY adhoc_tool code_quality_tool
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/code_quality_tool.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: category:internal

#20349 Make docker_environment's Pants-provided-PBS an absolute path (Cherry-pick of #20314)
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/adhoc_binaries_test.py
Labels: category:bugfix

#20350 Addresses TODOs in Java and Kotline parsers
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
Labels: backend: JVM, category:internal

#20351 Prepare 2.20.0.dev4
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20353 Prepare 2.18.2rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20352 Prepare 2.19.0rc3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20348 Update all of Pants' unpinned Python deps
  3rdparty/python/user_reqs.lock
Labels: category:internal
