Repository pantsbuild/pants, pull requests merged in 2023-08, with the labels that each got.

#19524 tests: refactor terraform tests to not depend on each other
  src/python/pants/backend/terraform/dependencies_test.py
  src/python/pants/backend/terraform/goals/deploy_test.py
  src/python/pants/backend/terraform/testutil.py
Labels: category:internal

#19538 Upgrade the default pip to v23.1.2.
  src/python/pants/backend/python/subsystems/setup.py
Labels: needs-cherrypick, category:user api change

#19526 tests: refactor internals tests to not depend on each other
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/engine/internals/synthetic_targets_test.py
  src/python/pants/engine/internals/testutil.py
Labels: category:internal

#19508 remove Toolchain references in doc
  docs/markdown/Getting Help/service-providers.md
  docs/markdown/Introduction/welcome-to-pants.md
Labels: category:documentation

#19543 tests: refactor go tests to not depend on each other
  src/python/pants/backend/go/util_rules/go_bootstrap_test.py
  src/python/pants/backend/go/util_rules/goroot_test.py
  src/python/pants/backend/go/util_rules/testutil.py
  src/python/pants/core/subsystems/python_bootstrap_test.py
  src/python/pants/core/util_rules/asdf_test.py
  src/python/pants/core/util_rules/testutil.py
Labels: category:internal

#19539 Fix rules-api docs typos
  docs/markdown/Writing Plugins/rules-api/rules-api-file-system.md
  docs/markdown/Writing Plugins/rules-api/rules-api-goal-rules.md
  docs/markdown/Writing Plugins/rules-api/rules-api-installing-tools.md
Labels: category:documentation

#19426 bump pyright to 1.1.316
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
Labels: category:new feature

#19545 tests: refactor kotlin tests to not depend on other tests
  src/python/pants/backend/kotlin/compile/kotlinc_test.py
  src/python/pants/backend/kotlin/compile/testutil.py
  src/python/pants/backend/kotlin/test/junit_test.py
  src/python/pants/jvm/test/junit_test.py
  src/python/pants/jvm/test/testutil.py
Labels: category:internal

#19547 tests: refactor jvm tests to not depend on other tests
  src/python/pants/jvm/package/war_test.py
  src/python/pants/jvm/shading/rules_integration_test.py
  src/python/pants/jvm/testutil.py
Labels: category:internal

#19546 Fix dead doc links
  docs/markdown/Contributions/contributor-overview.md
  docs/markdown/Contributions/development/contributions-rust.md
  docs/markdown/Contributions/releases/release-strategy.md
  docs/markdown/Docker/docker.md
  docs/markdown/Getting Started/getting-started/existing-repositories.md
  docs/markdown/Getting Started/getting-started/initial-configuration.md
  docs/markdown/Getting Started/getting-started/prerequisites.md
  docs/markdown/Go/go.md
  docs/markdown/Introduction/media.md
  docs/markdown/Java and Scala/jvm-overview.md
  docs/markdown/Java and Scala/kotlin.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Releases/changelog.md
  docs/markdown/Releases/deprecation-policy.md
  docs/markdown/Releases/upgrade-tips.md
  docs/markdown/Shell/shell.md
  docs/markdown/Using Pants/assets.md
  docs/markdown/Using Pants/concepts/enabling-backends.md
  docs/markdown/Using Pants/restricted-internet-access.md
  docs/markdown/Using Pants/setting-up-an-ide.md
  docs/markdown/Using Pants/troubleshooting.md
  docs/markdown/Writing Plugins/rules-api.md
  docs/markdown/Writing Plugins/rules-api/rules-api-file-system.md
  docs/markdown/Writing Plugins/rules-api/rules-api-goal-rules.md
  docs/markdown/Writing Plugins/rules-api/rules-api-logging.md
  docs/markdown/Writing Plugins/rules-api/rules-api-testing.md
  docs/markdown/Writing Plugins/rules-api/rules-api-tips.md
  docs/markdown/Writing Plugins/target-api/target-api-new-fields.md
Labels: category:documentation

#19548 tests: refactor helm tests to not depend on each other
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
  src/python/pants/backend/helm/util_rules/renderer_test.py
  src/python/pants/backend/helm/util_rules/testutil.py
Labels: category:internal

#19531 Automate GitHub Release notes
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
  src/python/pants_release/get_release_notes.py
Labels: category:internal

#19540 Trigger cheeseshop build on release success
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19432 Resolve `pants_requirements` from direct wheel links to GitHub Release assets
  src/python/pants/backend/plugin_development/pants_requirements.py
  src/python/pants/backend/plugin_development/pants_requirements_test.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:plugin api change

#19550 Register the `python_aws_lambda_layer` target type
  src/python/pants/backend/awslambda/python/register.py
Labels: category:internal

#19473 Fix golangci-lint runner script (Cherry-pick of #19015)
  src/python/pants/backend/go/lint/golangci_lint/rules.py
Labels: category:bugfix

#19472 Fix golangci-lint runner script (Cherry-pick of #19015)
  src/python/pants/backend/go/lint/golangci_lint/rules.py
Labels: category:bugfix

#19557 default_module_mapping: add snowflake-sqlalchemy
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#19541 Upgrade the default pip to v23.1.2. (Cherry-pick of #19538)
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:user api change

#19559 Prepare 2.18.0.dev7
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.18.x.md
Labels: category:internal, automation:release-prep

#19554 Stop referring to ~/.cache/pants/setup in CI docs
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: needs-cherrypick, category:documentation

#19560 Stop referring to ~/.cache/pants/setup in CI docs (Cherry-pick of #19554)
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#19561 Stop referring to ~/.cache/pants/setup in CI docs (Cherry-pick of #19554)
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#19563 Fix workflow typo
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19562 Mark python_aws_lambda_layer as packageable
  src/python/pants/backend/awslambda/python/rules.py
Labels: category:internal

#19565 Fix the new tool lockfile deprecation message.
  src/python/pants/backend/python/subsystems/python_tool_base.py
Labels: needs-cherrypick, category:bugfix

#19566 Generate release announcement messages to files.
  src/python/pants_release/generate_release_announcement.py
Labels: category:internal

#19568 Catch google artifact registry gotcha
  docs/markdown/Docker/docker.md
Labels: needs-cherrypick, category:documentation

#19569 Catch google artifact registry gotcha (Cherry-pick of #19568)
  docs/markdown/Docker/docker.md
Labels: category:documentation

#19570 Catch google artifact registry gotcha (Cherry-pick of #19568)
  docs/markdown/Docker/docker.md
Labels: category:documentation

#19555 Add ruff, adjust pyugprade, autoflake in docs
  build-support/bin/generate_docs.py
  docs/markdown/Python/python/python-linters-and-formatters.md
  docs/markdown/Using Pants/concepts/enabling-backends.md
Labels: needs-cherrypick, category:documentation

#19576 Add ruff, adjust pyugprade, autoflake in docs (Cherry-pick of #19555)
  build-support/bin/generate_docs.py
  docs/markdown/Python/python/python-linters-and-formatters.md
  docs/markdown/Using Pants/concepts/enabling-backends.md
Labels: category:documentation

#19577 Add ruff, adjust pyugprade, autoflake in docs (Cherry-pick of #19555)
  build-support/bin/generate_docs.py
  docs/markdown/Python/python/python-linters-and-formatters.md
  docs/markdown/Using Pants/concepts/enabling-backends.md
Labels: category:documentation

#19571 Fix the new tool lockfile deprecation message. (cherrypick of #19565)
  src/python/pants/backend/python/subsystems/python_tool_base.py
Labels: category:bugfix

#19573 Send a release announcement email from GitHub Actions.
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
  src/python/pants_release/generate_release_announcement.py
Labels: category:internal

#19575 Update and streamline the release process docs.
  docs/markdown/Contributions/releases/release-process.md
Labels: category:documentation

#19517 upgrade tonic ecosystem (gRPC crates) to latest versions
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
  src/rust/engine/Cargo.lock
  src/rust/engine/concrete_time/Cargo.toml
  src/rust/engine/fs/fs_util/Cargo.toml
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/fs/store/src/remote/reapi.rs
  src/rust/engine/fs/store/src/remote/reapi_tests.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/grpc_util/src/channel.rs
  src/rust/engine/grpc_util/src/hyper_util.rs
  src/rust/engine/grpc_util/src/lib.rs
  src/rust/engine/grpc_util/src/metrics.rs
  src/rust/engine/grpc_util/src/tls.rs
  src/rust/engine/grpc_util/test-certs/cert.pem
  src/rust/engine/grpc_util/test-certs/key.pem
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/remote/Cargo.toml
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache/reapi.rs
  src/rust/engine/process_executor/Cargo.toml
  src/rust/engine/protos/Cargo.toml
  src/rust/engine/testutil/Cargo.toml
  src/rust/engine/testutil/mock/Cargo.toml
  src/rust/engine/testutil/mock/src/cas.rs
  src/rust/engine/testutil/mock/src/execution_server.rs
Labels: category:internal

#19578 speling fix
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#19525 Add tfsec linter for Terraform
  src/python/pants/backend/experimental/terraform/lint/__init__.py
  src/python/pants/backend/experimental/terraform/lint/tfsec/BUILD
  src/python/pants/backend/experimental/terraform/lint/tfsec/__init__.py
  src/python/pants/backend/experimental/terraform/lint/tfsec/register.py
  src/python/pants/backend/terraform/lint/tfsec/BUILD
  src/python/pants/backend/terraform/lint/tfsec/__init__.py
  src/python/pants/backend/terraform/lint/tfsec/rules.py
  src/python/pants/backend/terraform/lint/tfsec/tfsec.py
  src/python/pants/backend/terraform/lint/tfsec/tfsec_integration_test.py
  src/python/pants/backend/terraform/tool.py
Labels: category:new feature, backend: Terraform

#19582 install protoc in wheel building CI jobs
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19168 initial draft of What's New for v2.17.x
  src/python/pants/notes/2.17.x.md
Labels: category:documentation

#19581 upgrade to Rust v1.71.1
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  rust-toolchain
Labels: category:internal

#19583 Increase timeouts on some frequent offenders
  src/python/pants/backend/adhoc/BUILD
  src/python/pants/backend/docker/target_types_test.py
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/build_graph/BUILD
  src/python/pants/init/BUILD
Labels: category:internal

#19551 tests: treat imports from a test module as a build error
  src/python/pants/BUILD
Labels: category:internal

#19588 Scala: support Enums in dependency inference
  3rdparty/jvm/org/scalameta/BUILD
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser.lock
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: category:bugfix

#19594 Scala: support Enums in dependency inference (Cherry pick of #19588)
  3rdparty/jvm/org/scalameta/BUILD
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser.lock
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: category:bugfix

#19593 Scala: support Enums in dependency inference (Cherry pick of #19588)
  3rdparty/jvm/org/scalameta/BUILD
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser.lock
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: backend: JVM, category:bugfix

#19595 initial draft of What's New for v2.17.x (Cherry-pick of #19168)
  src/python/pants/notes/2.17.x.md
Labels: category:documentation

#19164 Reduce process parallelism on Linux X86 CI machines
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19580 Prepare the 2.17.0rc3 release.
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19597 docs: add 2.16 entry to changelog (Cherry-pick of #19589)
  docs/markdown/Releases/changelog.md
Labels: category:documentation

#19558 Cache Go processes using full version string
  src/python/pants/backend/go/util_rules/sdk.py
Labels: category:bugfix

#19245 javascript: Assign a default name to root nodejs resolves
  src/python/pants/backend/javascript/goals/lockfile.py
  src/python/pants/backend/javascript/goals/lockfile_test.py
  src/python/pants/backend/javascript/nodejs_project.py
  src/python/pants/backend/javascript/nodejs_project_test.py
  src/python/pants/backend/javascript/resolve.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool_test.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
Labels: category:bugfix, backend: JavaScript

#19603 Don't override the ICs in the pants script on MacOS Silicon.
  pants
Labels: category:internal

#19590 docs: set EnvironmentBehavior in plugin Goal examples
  docs/markdown/Tutorials/advanced-plugin-concepts.md
  docs/markdown/Tutorials/create-a-new-goal.md
  docs/markdown/Writing Plugins/rules-api/rules-api-goal-rules.md
Labels: category:documentation

#19567 Show cause when ./pants can't find interpreter
  build-support/common.sh
Labels: category:internal

#19592 add latest helm versions; upgrade default
  src/python/pants/backend/helm/subsystems/helm.py
Labels: category:new feature

#19605 Fix an erroneous options scope in an export error message.
  src/python/pants/backend/python/goals/export.py
Labels: category:bugfix

#19533 Add Docker global no build cache option
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/subsystems/docker_options.py
Labels: category:new feature

#19604 Manually cherry-pick changes to CI automation
  .github/workflows/release.yaml
  build-support/bin/generate_github_workflows.py
  build-support/bin/get_release_notes.py
Labels: category:internal

#19610 Make mypy cache move truly atomic
  src/python/pants/backend/python/typecheck/mypy/rules.py
Labels: needs-cherrypick, category:bugfix

#19611 Use named cache for Docker-env PBS
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/providers/pyenv/rules.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/adhoc_binaries_test.py
  src/python/pants/core/util_rules/archive.py
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: needs-cherrypick, category:bugfix

#19606 Maintain Rust external dep versions at the workspace level
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/address/Cargo.toml
  src/rust/engine/async_latch/Cargo.toml
  src/rust/engine/async_value/Cargo.toml
  src/rust/engine/cache/Cargo.toml
  src/rust/engine/client/Cargo.toml
  src/rust/engine/concrete_time/Cargo.toml
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/brfs/Cargo.toml
  src/rust/engine/fs/fs_util/Cargo.toml
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/graph/Cargo.toml
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/hashing/Cargo.toml
  src/rust/engine/logging/Cargo.toml
  src/rust/engine/nailgun/Cargo.toml
  src/rust/engine/options/Cargo.toml
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/docker/Cargo.toml
  src/rust/engine/process_execution/pe_nailgun/Cargo.toml
  src/rust/engine/process_execution/remote/Cargo.toml
  src/rust/engine/process_executor/Cargo.toml
  src/rust/engine/protos/Cargo.toml
  src/rust/engine/rule_graph/Cargo.toml
  src/rust/engine/sharded_lmdb/Cargo.toml
  src/rust/engine/stdio/Cargo.toml
  src/rust/engine/task_executor/Cargo.toml
  src/rust/engine/testutil/Cargo.toml
  src/rust/engine/testutil/local_cas/Cargo.toml
  src/rust/engine/testutil/local_execution_server/Cargo.toml
  src/rust/engine/testutil/mock/Cargo.toml
  src/rust/engine/tryfuture/Cargo.toml
  src/rust/engine/ui/Cargo.toml
  src/rust/engine/watch/Cargo.toml
  src/rust/engine/workunit_store/Cargo.toml
Labels: category:internal

#19621 Use standard conversion from FallibleProcessResult to ProcessResult
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: backend: JVM, category:internal

#19623 Prepare 2.18.0a0
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.18.x.md
Labels: category:internal, automation:release-prep

#19585 documentation: more complete contributor setup instructions
  docs/markdown/Contributions/development/contributor-setup.md
Labels: category:documentation

#19622 docs: fix markdown inconsistencies (Cherry pick of #19363)
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/python/framework/stevedore/target_types.py
  src/python/pants/backend/python/macros/common_fields.py
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/packaging/pyoxidizer/target_types.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/typecheck/mypy/mypyc.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/wrap_source.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/jvm/target_types.py
  src/python/pants/option/global_options.py
Labels: category:documentation

#19627 docs: mention that python_distribution targets can use transitive excludes
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#19632 Add missing GH_TOKEN env var
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19636 Make determine_python() pin to 3.9 (Cherry-pick of #19116)
  build-support/common.sh
Labels: category:internal

#19630 Add path to cache key for Rust dep inference, for relative imports
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/rust/engine/protos/protos/pants/cache.proto
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:internal

#19624 docs: fix code examples for `setting-up-ide` and `interpreter-compatibility` docs
  docs/markdown/Python/python/python-interpreter-compatibility.md
  docs/markdown/Using Pants/setting-up-an-ide.md
Labels: needs-cherrypick, category:documentation

#19638 docs: fix code examples for `setting-up-ide` and `interpreter-compatibility` docs (Cherry-pick of #19624)
  docs/markdown/Python/python/python-interpreter-compatibility.md
  docs/markdown/Using Pants/setting-up-an-ide.md
Labels: category:documentation

#19639 docs: fix code examples for `setting-up-ide` and `interpreter-compatibility` docs (Cherry-pick of #19624)
  docs/markdown/Python/python/python-interpreter-compatibility.md
  docs/markdown/Using Pants/setting-up-an-ide.md
Labels: category:documentation

#19608 docs: update go tracking link to a live ticket instead of the archived project
  docs/markdown/Go/go.md
Labels: category:documentation

#19629 Additional mentions and tweaks in 2.17's "What's new"
  src/python/pants/notes/2.17.x.md
Labels: needs-cherrypick, category:documentation

#19642 Additional mentions and tweaks in 2.17's "What's new" (Cherry-pick of #19629)
  src/python/pants/notes/2.17.x.md
Labels: category:documentation

#19640 Add path to cache key for Rust dep inference, for relative imports (cherry-pick of #19630)
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/rust/engine/protos/protos/pants/cache.proto
  src/rust/engine/src/intrinsics.rs
Labels: category:internal

#18553 Add support for openapi-format
  build-support/bin/generate_docs.py
  src/python/pants/backend/experimental/openapi/lint/openapi_format/BUILD
  src/python/pants/backend/experimental/openapi/lint/openapi_format/__init__.py
  src/python/pants/backend/experimental/openapi/lint/openapi_format/register.py
  src/python/pants/backend/openapi/lint/openapi_format/BUILD
  src/python/pants/backend/openapi/lint/openapi_format/__init__.py
  src/python/pants/backend/openapi/lint/openapi_format/rules.py
  src/python/pants/backend/openapi/lint/openapi_format/rules_integration_test.py
  src/python/pants/backend/openapi/lint/openapi_format/skip_field.py
  src/python/pants/backend/openapi/lint/openapi_format/subsystem.py
  src/python/pants/bin/BUILD
Labels: category:new feature

#19614 Make mypy cache move truly atomic (Cherry-pick of #19610)
  src/python/pants/backend/python/typecheck/mypy/rules.py
Labels: category:bugfix

#19617 Use named cache for Docker-env PBS (Cherry-pick of #19611)
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/providers/pyenv/rules.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/adhoc_binaries_test.py
  src/python/pants/core/util_rules/archive.py
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: category:bugfix

#19616 Use named cache for Docker-env PBS (Cherry-pick of #19611)
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/providers/pyenv/rules.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/adhoc_binaries_test.py
  src/python/pants/core/util_rules/archive.py
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: category:bugfix

#19645 Undo pyenv install marking files as RO
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: category:bugfix

#19633 Use hardlinking when possible for mypy cache
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: needs-cherrypick, category:bugfix

#19641 Add Python 3.12 to the default interpreter universe
  src/python/pants/backend/python/subsystems/setup.py
Labels: needs-cherrypick, category:user api change

#19648 Undo pyenv install marking files as RO (Cherry-pick of #19645)
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: category:bugfix

#19650 Use hardlinking when possible for mypy cache (Cherry-pick of #19633)
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:bugfix

#19649 Use hardlinking when possible for mypy cache (Cherry-pick of #19633)
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:bugfix

#19646 Have Pants create the `immutable_inputs` base parent(s)
  src/rust/engine/fs/store/src/immutable_inputs.rs
Labels: needs-cherrypick, category:bugfix

#19651 Add Python 3.12 to the default interpreter universe (Cherry-pick of #19641)
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:user api change

#19654 Require scie-pants 0.9.2 or newer, for new distribution model
  src/python/pants/bin/pants_runner.py
Labels: needs-cherrypick, category:user api change

#19652 Have Pants create the `immutable_inputs` base parent(s) (Cherry-pick of #19646)
  src/rust/engine/fs/store/src/immutable_inputs.rs
Labels: category:bugfix

#19653 Have Pants create the `immutable_inputs` base parent(s) (Cherry-pick of #19646)
  src/rust/engine/fs/store/src/immutable_inputs.rs
Labels: category:bugfix

#19655 Require scie-pants 0.9.2 or newer, for new distribution model (Cherry-pick of #19654)
  src/python/pants/bin/pants_runner.py
Labels: category:user api change

#19293 `with contextlib.suppress(ImportError)` weakens imports
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/dep_inference/build.rs
  src/rust/engine/dep_inference/src/javascript/mod.rs
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: category:new feature, backend: Python

#19659 Backport to 2.17: Fix dead doc links (#19546)
  docs/markdown/Contributions/contributor-overview.md
  docs/markdown/Contributions/development/contributions-rust.md
  docs/markdown/Contributions/releases/release-strategy.md
  docs/markdown/Docker/docker.md
  docs/markdown/Getting Started/getting-started/existing-repositories.md
  docs/markdown/Getting Started/getting-started/initial-configuration.md
  docs/markdown/Getting Started/getting-started/prerequisites.md
  docs/markdown/Go/go.md
  docs/markdown/Introduction/media.md
  docs/markdown/Java and Scala/jvm-overview.md
  docs/markdown/Java and Scala/kotlin.md
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Releases/changelog.md
  docs/markdown/Releases/deprecation-policy.md
  docs/markdown/Releases/upgrade-tips.md
  docs/markdown/Shell/shell.md
  docs/markdown/Using Pants/assets.md
  docs/markdown/Using Pants/concepts/enabling-backends.md
  docs/markdown/Using Pants/restricted-internet-access.md
  docs/markdown/Using Pants/setting-up-an-ide.md
  docs/markdown/Using Pants/troubleshooting.md
  docs/markdown/Writing Plugins/rules-api.md
  docs/markdown/Writing Plugins/rules-api/rules-api-file-system.md
  docs/markdown/Writing Plugins/rules-api/rules-api-goal-rules.md
  docs/markdown/Writing Plugins/rules-api/rules-api-logging.md
  docs/markdown/Writing Plugins/rules-api/rules-api-testing.md
  docs/markdown/Writing Plugins/rules-api/rules-api-tips.md
  docs/markdown/Writing Plugins/target-api/target-api-new-fields.md
Labels: category:documentation

#19660 Silence the scie-pants version warning when NO_SCIE_WARNING=1
  src/python/pants/bin/pants_runner.py
Labels: category:internal

#19661 Prepare the 2.17.0rc4 release
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19643 user api change: change the Pip version option to a string
  docs/markdown/Python/python-goals/python-package-goal.md
  docs/markdown/Python/python-integrations/awslambda-python.md
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
  docs/markdown/Python/python-integrations/pyoxidizer.md
  docs/markdown/Python/python.md
  docs/markdown/Python/python/pex-files.md
  docs/markdown/Python/python/pex.md
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#19663 Fix release workflow.
  .github/workflows/release.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#19664 Backport to 2.17: docs: set EnvironmentBehavior in plugin Goal examples (#19590)
  docs/markdown/Tutorials/advanced-plugin-concepts.md
  docs/markdown/Tutorials/create-a-new-goal.md
  docs/markdown/Writing Plugins/rules-api/rules-api-goal-rules.md
Labels: category:documentation

#19670 Bump minimum scie version to 0.10.0
  src/python/pants/bin/pants_runner.py
Labels: needs-cherrypick, category:internal

#19674 Bump minimum scie version to 0.10.0 (Cherry-pick of #19670)
  src/python/pants/bin/pants_runner.py
Labels: category:internal

#19673 Remove `tensorboard` mapping from our default mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: needs-cherrypick, category:bugfix

#19675 upgrade to Rust v1.72.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  rust-toolchain
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/src/externs/address.rs
  src/rust/engine/src/externs/target.rs
  src/rust/engine/task_executor/src/lib.rs
Labels: category:internal

#19671 Update default_module_mapping.py to add snowflake's snowpark
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#19677 Remove `tensorboard` mapping from our default mapping (Cherry-pick of #19673)
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:bugfix

#19678 Prepare the 2.17.0rc5 release.
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19315 Include all binaries available in a venv when fulfilling a VenvPexRequest
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:bugfix, backend: Python

#19680 Add additional public repos to test, fix backend.ai
  .github/workflows/public_repos.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#18565 docs: use Python 3.11+ as example
  docs/markdown/Python/python/python-interpreter-compatibility.md
Labels: category:documentation

#18593 Add lint backend to run semgrep
  build-support/bin/generate_builtin_lockfiles.py
  build-support/bin/generate_docs.py
  src/python/pants/backend/experimental/tools/semgrep/BUILD
  src/python/pants/backend/experimental/tools/semgrep/__init__.py
  src/python/pants/backend/experimental/tools/semgrep/register.py
  src/python/pants/backend/tools/semgrep/BUILD
  src/python/pants/backend/tools/semgrep/__init__.py
  src/python/pants/backend/tools/semgrep/rules.py
  src/python/pants/backend/tools/semgrep/rules_integration_test.py
  src/python/pants/backend/tools/semgrep/rules_test.py
  src/python/pants/backend/tools/semgrep/semgrep.lock
  src/python/pants/backend/tools/semgrep/subsystem.py
  src/python/pants/bin/BUILD
  src/python/pants/core/goals/lint.py
  src/python/pants/option/global_options.py
Labels: category:new feature

#19685 Add missed fixes for semgrep backend
  src/python/pants/backend/tools/semgrep/rules.py
  src/python/pants/backend/tools/semgrep/rules_test.py
  src/python/pants/backend/tools/semgrep/subsystem.py
Labels: category:internal

#19688 Remove `src/python/pants/bin:pants`
  src/python/pants/BUILD
  src/python/pants/bin/BUILD
Labels: category:internal

#19697 docs: mention that python_distribution targets can use transitive excludes (Cherry-pick of #19627)
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#19698 docs: update go tracking link to a live ticket instead of the archived project (Cherry-pick of #19608)
  docs/markdown/Go/go.md
Labels: category:documentation

#19700 docs: use Python 3.11+ as example (Cherry-pick of #18565)
  docs/markdown/Python/python/python-interpreter-compatibility.md
Labels: category:documentation

#19695 docs: fix code examples for `setting-up-ide` and `interpreter-compatibility` docs (Cherry-pick of #19624)
  docs/markdown/Python/python/python-interpreter-compatibility.md
  docs/markdown/Using Pants/setting-up-an-ide.md
Labels: category:documentation

#19694 Require scie-pants 0.9.2 or newer, for new distribution model (Cherry-pick of #19654)
  src/python/pants/bin/pants_runner.py
Labels: category:user api change

#19691 Undo pyenv install marking files as RO (Cherry-pick of #19645)
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: category:bugfix

#19693 Add Python 3.12 to the default interpreter universe (Cherry-pick of #19641)
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:user api change

#19692 Use hardlinking when possible for mypy cache (Cherry-pick of #19633)
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:bugfix

#19699 Remove `tensorboard` mapping from our default mapping (Cherry-pick of #19673)
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:bugfix

#19696 Have Pants create the `immutable_inputs` base parent(s) (Cherry-pick of #19646)
  src/rust/engine/fs/store/src/immutable_inputs.rs
Labels: category:bugfix

#19690 Add path to cache key for Rust dep inference, for relative imports (Cherry-pick of #19630)
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/rust/engine/protos/protos/pants/cache.proto
  src/rust/engine/src/intrinsics.rs
Labels: category:internal

#19701 Bump minimum scie version to 0.10.0 (Cherry-pick of #19670)
  src/python/pants/bin/pants_runner.py
Labels: category:internal

#19702 Silence the scie-pants version warning when NO_SCIE_WARNING=1 (Cherry-pick of #19660)
  src/python/pants/bin/pants_runner.py
Labels: category:internal

#19703 Add missing GH_TOKEN env var (Cherry-pick of #19632)
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19704 Prepare the 2.17.0 release.
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19668 Don't check in the changelog, just hand it to GitHub
  .github/workflows/release.yaml
  docs/markdown/Contributions/releases/release-process.md
  src/python/pants/notes/2.18.x.md
  src/python/pants_release/changelog.py
  src/python/pants_release/changelog_test.py
  src/python/pants_release/generate_github_workflows.py
  src/python/pants_release/get_release_notes.py
  src/python/pants_release/start_release.py
  src/python/pants_release/start_release_test.py
Labels: needs-cherrypick, category:internal

#19683 Version the release asset per-platform PEXs
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#19724 Add a warning about PyPI to `2.17.x.md`
  src/python/pants/notes/2.17.x.md
Labels: needs-cherrypick, category:internal

#19723 Dont allow running `start_release.py` for 2.17.x (or earlier)
  src/python/pants_release/start_release.py
Labels: needs-cherrypick, category:internal

#19721 Allow requesters of `TargetRootsToFieldSets` to turn off the secondary ownership warning
  src/python/pants/core/goals/run.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/target.py
Labels: needs-cherrypick, category:bugfix

#19714 Stop publishing to PyPI
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19716 Remove memoization of the `Paths` intrinsic to reduce memory usage (Cherry-pick of #19689)
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
Labels: category:performance

#19717 Remove memoization of the `Paths` intrinsic to reduce memory usage (Cherry-pick of #19689)
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
Labels: category:performance

#19728 Allow requesters of `TargetRootsToFieldSets` to turn off the secondary ownership warning (Cherry-pick of #19721)
  src/python/pants/core/goals/run.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/target.py
Labels: category:bugfix

#19727 Dont allow running `start_release.py` for 2.17.x (or earlier) (Cherry-pick of #19723)
  src/python/pants_release/start_release.py
Labels: category:internal

#19726 Add a warning about PyPI to `2.17.x.md` (Cherry-pick of #19724)
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19712 Don't check in the changelog, just hand it to GitHub (Cherry-pick of #19668)
  .github/workflows/release.yaml
  docs/markdown/Contributions/releases/release-process.md
  src/python/pants/notes/2.18.x.md
  src/python/pants_release/changelog.py
  src/python/pants_release/changelog_test.py
  src/python/pants_release/generate_github_workflows.py
  src/python/pants_release/get_release_notes.py
  src/python/pants_release/start_release.py
  src/python/pants_release/start_release_test.py
Labels: category:internal

#19729 Update the docs changelog to include 2.17.x.
  docs/markdown/Releases/changelog.md
Labels: needs-cherrypick, category:documentation

#19735 Update the docs changelog to include 2.17.x. (Cherry-pick of #19729)
  docs/markdown/Releases/changelog.md
Labels: category:documentation

#19736 Update the docs changelog to include 2.17.x. (Cherry-pick of #19729)
  docs/markdown/Releases/changelog.md
Labels: category:documentation

#19725 Add a warning about PyPI to `2.17.x.md` (Cherry-pick of #19724)
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19742 Remove last bits of `SecondaryOwnershipMixin`
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/base/specs_integration_test.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/engine/target.py
Labels: needs-cherrypick, category:internal

#19739 Fix typoed artifact name in Lambda docs
  docs/markdown/Python/python-integrations/awslambda-python.md
Labels: needs-cherrypick, category:documentation

#19738 Remove remaining Lambdex code, update FaaS docs
  build-support/bin/generate_builtin_lockfiles.py
  build-support/bin/generate_pex_lockfiles.sh
  docs/markdown/Python/python-integrations/awslambda-python.md
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
  src/python/pants/backend/awslambda/python/BUILD
  src/python/pants/backend/awslambda/python/register.py
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/BUILD
  src/python/pants/backend/google_cloud_function/python/register.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/lambdex.py
  src/python/pants/backend/python/util_rules/faas.py
Labels: category:user api change

#19745 Fix typoed artifact name in Lambda docs (Cherry-pick of #19739)
  docs/markdown/Python/python-integrations/awslambda-python.md
Labels: category:documentation

#19746 Fix typoed artifact name in Lambda docs (Cherry-pick of #19739)
  docs/markdown/Python/python-integrations/awslambda-python.md
Labels: category:documentation
