Repository pantsbuild/pants, pull requests merged in 2023-10, with the labels that each got.

#19887 add support for mTLS in remote cache usage
  docs/markdown/Using Pants/remote-caching-execution/remote-execution.md
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/option/global_options.py
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/grpc_util/src/channel.rs
  src/rust/engine/grpc_util/src/tls.rs
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/process_execution/remote/src/remote_cache/reapi.rs
  src/rust/engine/process_execution/remote/src/remote_cache/reapi_tests.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
Labels: needs-cherrypick, category:new feature, remote

#19916 Remove ` build-support/pants_pyoxidized`
  build-support/pants_pyoxidized/BUILD
  build-support/pants_pyoxidized/pyoxidizer-howto.md
Labels: category:internal

#19960 add support for mTLS in remote cache usage (Cherry-pick of #19887)
  docs/markdown/Using Pants/remote-caching-execution/remote-execution.md
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/option/global_options.py
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/grpc_util/src/channel.rs
  src/rust/engine/grpc_util/src/tls.rs
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/process_execution/remote/src/remote_cache/reapi.rs
  src/rust/engine/process_execution/remote/src/remote_cache/reapi_tests.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
Labels: category:new feature

#19955 Add Tom and Gautham to the Contributors page.
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: needs-cherrypick, category:documentation

#19961 Add Tom and Gautham to the Contributors page. (Cherry-pick of #19955)
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#19962 Add Tom and Gautham to the Contributors page. (Cherry-pick of #19955)
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#19964 Pin manylinux image to avoid openssl error
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#19965 Pin manylinux image to avoid openssl error
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#19967 Fix "the the" typos in the codebase.
  src/python/pants/backend/codegen/utils.py
  src/python/pants/backend/go/util_rules/import_analysis.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/scala/bsp/spec.py
  src/python/pants/backend/terraform/dependencies_test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/option/option_types.py
  src/python/pants/option/subsystem.py
  src/rust/engine/pantsd/src/lib.rs
Labels: category:documentation

#19968 Support using `__defaults__` in same BUILD file as environment targets. (Cherry-pick of #19446)
  docs/markdown/Using Pants/concepts/targets.md
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
Labels: category:bugfix

#19969 Support using `__defaults__` in same BUILD file as environment targets. (Cherry-pick of #19446)
  docs/markdown/Using Pants/concepts/targets.md
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
Labels: category:bugfix

#19976 Prepare 2.18.0rc2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#19983 Prepare 2.19.0.dev2
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#19958 Split remote providers into their own crates
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/remote/Cargo.toml
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/process_execution/remote/src/remote_cache/base_opendal.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/remote_provider/Cargo.toml
  src/rust/engine/remote_provider/remote_provider_opendal/Cargo.toml
  src/rust/engine/remote_provider/remote_provider_opendal/src/action_cache_tests.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/byte_store_tests.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/lib.rs
  src/rust/engine/remote_provider/remote_provider_reapi/Cargo.toml
  src/rust/engine/remote_provider/remote_provider_reapi/src/action_cache.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/action_cache_tests.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store_tests.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/lib.rs
  src/rust/engine/remote_provider/remote_provider_traits/Cargo.toml
  src/rust/engine/remote_provider/remote_provider_traits/src/lib.rs
  src/rust/engine/remote_provider/src/lib.rs
  src/rust/engine/testutil/Cargo.toml
  src/rust/engine/testutil/src/all_the_henries.txt
  src/rust/engine/testutil/src/data.rs
  src/rust/engine/testutil/src/file.rs
Labels: category:internal

#19956 Actually use the `@rule` call-by-name syntax to drive graph solving
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/rules.py
  src/python/pants/option/subsystem.py
  src/rust/engine/rule_graph/src/rules.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/tasks.rs
Labels: category:internal

#19985 Prepare `2.16.1rc3`
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#19989 Prepare `2.17.1rc1`
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19980 `docker_image`: The `image_tags` field must not be empty.
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
Labels: needs-cherrypick, category:bugfix

#19987 Replace maintainer release duty with MOTW in docs
  docs/markdown/Getting Help/the-pants-community/maintainers.md
Labels: needs-cherrypick, category:documentation

#19990 `docker_image`: The `image_tags` field must not be empty. (Cherry-pick of #19980)
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
Labels: category:bugfix

#19992 Replace maintainer release duty with MOTW in docs (Cherry-pick of #19987)
  docs/markdown/Getting Help/the-pants-community/maintainers.md
Labels: category:documentation

#19377 Create system-binaries subsystem to access environment's PATH, modify search paths etc.
  src/python/pants/backend/adhoc/run_system_binary.py
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:new feature

#19991 `docker_image`: The `image_tags` field must not be empty. (Cherry-pick of #19980)
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
Labels: category:bugfix

#19995 docs: Remove pants 2.15 example configuration.
  docs/markdown/Python/python/python-backend.md
Labels: needs-cherrypick, category:documentation

#19997 docs: Remove pants 2.15 example configuration. (Cherry-pick of #19995)
  docs/markdown/Python/python/python-backend.md
Labels: category:documentation

#19998 docs: Remove pants 2.15 example configuration. (Cherry-pick of #19995)
  docs/markdown/Python/python/python-backend.md
Labels: category:documentation

#20003 Specify pants as running with cp3.9 only in plugin docs
  docs/markdown/Writing Plugins/plugins-overview.md
Labels: needs-cherrypick, category:documentation

#20005 Specify pants as running with cp3.9 only in plugin docs (Cherry-pick of #20003)
  docs/markdown/Writing Plugins/plugins-overview.md
Labels: category:documentation

#20000 Upgrade to Rust v1.73.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/dep_inference/build.rs
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/rust-toolchain
Labels: category:internal

#20004 Remove the unneeded util function create_path_env_var.
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/util/strutil.py
Labels: category:internal

#19982 Fix pytype backend location in build-support scripts.
  build-support/bin/generate_builtin_lockfiles.py
  build-support/bin/generate_docs.py
Labels: needs-cherrypick, category:internal

#19993 Fixes for 2.16.x github wheel and PEX builds
  build-support/bin/_release_helper.py
Labels: category:internal

#20009 Remove `--title` from release creation automation
  build-support/bin/_release_helper.py
Labels: category:internal

#20010 Set ICs when building the Pants PEX
  .github/workflows/release.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#20008 Document how to build cross-platform pexes.
  docs/markdown/Python/python/pex.md
Labels: category:documentation

#20001 simplify TLS handling & setup
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/action_cache.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/action_cache_tests.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store.rs
  src/rust/engine/remote_provider/remote_provider_traits/src/lib.rs
  src/rust/engine/remote_provider/src/lib.rs
  src/rust/engine/src/context.rs
Labels: category:internal

#19931 Bump `console_ui` dependencies and simplify code
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/ui/Cargo.toml
  src/rust/engine/ui/src/console_ui.rs
  src/rust/engine/ui/src/instance.rs
  src/rust/engine/ui/src/instance/indicatif.rs
  src/rust/engine/ui/src/instance/prodash.rs
  src/rust/engine/ui/src/lib.rs
Labels: dependencies, category:internal

#20011 Add support for using `MultiGet` with call-by-name `@rule`s and rule helpers
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler_test.py
  src/python/pants/engine/internals/selectors.py
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#20013 Move the pydevd-pycharm requirement into requirements.txt.
  3rdparty/python/BUILD
  3rdparty/python/requirements.txt
Labels: category:internal

#20023 Fix broken target field deprecation check.
  src/rust/engine/src/externs/target.rs
Labels: category:internal

#20028 added a new section in Using Pants in CI on partial clones
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: needs-cherrypick, category:documentation

#20029 added a new section in Using Pants in CI on partial clones (Cherry-pick of #20028)
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#20015 fix: Add github release link for slack
  src/python/pants_release/generate_release_announcement.py
Labels: category:internal

#20030 Fix algorithm for gathering Go build requests with coverage.
  src/python/pants/backend/go/goals/test.py
Labels: category:bugfix

#20032 Fix algorithm for gathering Go build requests with coverage. (Cherry-pick of #20030)
  src/python/pants/backend/go/goals/test.py
Labels: category:bugfix

#20033 Fix algorithm for gathering Go build requests with coverage. (Cherry-pick of #20030)
  src/python/pants/backend/go/goals/test.py
Labels: category:bugfix

#20031 Fix algorithm for gathering Go build requests with coverage. (Cherry-pick of #20030)
  src/python/pants/backend/go/goals/test.py
Labels: category:bugfix

#20041 docs: remove reference to use_deprecated_directory_cli_args_semantics
  docs/markdown/Using Pants/concepts/goals.md
Labels: category:documentation

#20042 Prepare the 2.16.1rc4 release
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#20044 Prepare 2.18.0rc3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20043 Prepare the 2.17.1rc2 release
  src/python/pants/VERSION
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19760 Optionally retry failed tests
  docs/markdown/Using Pants/using-pants-in-ci.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-test-goal.md
  docs/markdown/Writing Plugins/rules-api/rules-api-process.md
  pants.ci.toml
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/javascript/goals/test.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/backend/shell/goals/test.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/core/goals/test.py
  src/python/pants/engine/process.py
  src/python/pants/jvm/test/junit.py
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/nodes.rs
Labels: category:new feature

#20040 doc: Some guidance on auto-fixing goals in CI
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#20057 Fix `Store` benchmarks
  src/rust/engine/fs/store/benches/store.rs
Labels: category:internal

#20045 Filter the Worker Pants user from contributors.
  src/python/pants_release/common.py
Labels: needs-cherrypick, category:internal

#20058 Fix protoc support on M1 mac
  src/python/pants/backend/codegen/protobuf/protoc.py
Labels: category:bugfix

#20060 Filter the Worker Pants user from contributors. (Cherry-pick of #20045)
  src/python/pants_release/common.py
Labels: category:internal

#20061 chore: Bump OpenDAL to v0.41
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal

#20012 Deprecate the platforms field on pex_binary.
  src/python/pants/backend/python/target_types.py
Labels: category:user api change

#20048 Upgrade Pex to 2.1.148.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#20002 Fix `release.py test-release` smoke test for new release style
  src/python/pants_release/release.py
Labels: needs-cherrypick, category:internal

#20073 Fix `release.py test-release` smoke test for new release style (Cherry-pick of #20002)
  src/python/pants_release/release.py
Labels: category:internal

#20072 Prepare 2.19.0.dev3
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20074 Configurable override of url generation for External Tool versions
  src/python/pants/core/util_rules/external_tool.py
  src/python/pants/core/util_rules/external_tool_test.py
Labels: category:new feature

#20055 Add best-effort limits on async file opens to reduce file handle counts
  src/rust/engine/fs/store/src/local.rs
Labels: needs-cherrypick, category:bugfix

#20070 Create the README file in german
  README_de.md
Labels: category:documentation

#19939 Use `ambiguity-resolution` for Python protobuf/grpc dependency inference
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem_test.py
  src/python/pants/backend/codegen/thrift/apache/python/rules.py
  src/python/pants/backend/codegen/utils.py
Labels: category:new feature, backend: Python

#20083 Revert "Create the README file in german (#20070)"
  README_de.md
Labels: category:documentation

#20078 Add best-effort limits on async file opens to reduce file handle counts (Cherry-pick of #20055)
  src/rust/engine/fs/store/src/local.rs
Labels: category:bugfix

#20077 Add best-effort limits on async file opens to reduce file handle counts (Cherry-pick of #20055)
  src/rust/engine/fs/store/src/local.rs
Labels: category:bugfix

#19940 Fix coursier download for arm64, bumps default to v2.1.6
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: needs-cherrypick, category:bugfix

#20088 remove cyclic dependency betweeen `fs` and `testutil` crates
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/src/gitignore.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/src/posixfs_tests.rs
  src/rust/engine/fs/src/testutil.rs
  src/rust/engine/testutil/src/lib.rs
Labels: category:internal

#20085 Plumb the hidden `_find_links` through non-resolve Pex invocations
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: needs-cherrypick, category:plugin api change

#20082 Make CompletePexEnvironment.environment_dict accept `PATH` from `subprocess-environment`
  src/python/pants/backend/python/util_rules/pex_environment.py
Labels: category:bugfix

#20094 vscode: add rust settings to suggested configuration in docs
  docs/markdown/Contributions/development/contributor-setup.md
Labels: category:documentation

#20093 Add 'cattrs' to 'cattrs' default module mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#20095 Plumb the hidden `_find_links` through non-resolve Pex invocations (Cherry-pick of #20085)
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:plugin api change

#20080 Add `TransitivelyExcludeDependenciesRequest` to mirror user-provided values
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/target.py
Labels: category:new feature

#20100 Configurable override of url generation for External Tool versions (Cherry-pick of #20074)
  src/python/pants/core/util_rules/external_tool.py
  src/python/pants/core/util_rules/external_tool_test.py
Labels: category:new feature

#20092 Fix coursier download for arm64, bumps default to v2.1.6 (Cherry-pick of #19940)
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: category:bugfix

#20110 Prepare 2.18.0rc4
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20111 Prepare 2.17.1rc3
  src/python/pants/VERSION
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#20123 [internal] Fix issue with no pip version satisfying this IC range.
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:internal

#20112 The pants native client should respect the `PANTS_BUILDROOT_OVERRIDE` provided by `scie-pants`.
  src/rust/engine/options/src/build_root.rs
Labels: needs-cherrypick, category:bugfix

#20109 Prepare 2.19.0.dev4
  .git-blame-ignore-revs
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20124 The pants native client should respect the `PANTS_BUILDROOT_OVERRIDE` provided by `scie-pants`. (Cherry-pick of #20112)
  src/rust/engine/options/src/build_root.rs
Labels: category:bugfix

#20101 Extend deprecation period for `python_awslambda` alias
  src/python/pants/backend/awslambda/python/target_types.py
Labels: needs-cherrypick, category:internal

#20105 Discover ASDF interpreters by default
  src/python/pants/core/subsystems/python_bootstrap.py
Labels: category:user api change

#20102 Update semgrep to current latest, by default
  src/python/pants/backend/tools/semgrep/rules.py
  src/python/pants/backend/tools/semgrep/semgrep.lock
Labels: category:internal

#20125 Extend deprecation period for `python_awslambda` alias (Cherry-pick of #20101)
  src/python/pants/backend/awslambda/python/target_types.py
Labels: category:internal

#20114 Run benchmarks in "test" mode, in CI
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#20075 Add `exclude_files` field to `deploy_jar` target
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/target_types.py
Labels: needs-cherrypick, category:new feature

#20115 Merge "byte store" and "action cache" provider options
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/action_cache_tests.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/byte_store_tests.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/lib.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/action_cache.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/action_cache_tests.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store_tests.rs
  src/rust/engine/remote_provider/remote_provider_traits/src/lib.rs
  src/rust/engine/remote_provider/src/lib.rs
  src/rust/engine/src/context.rs
Labels: category:internal
