Repository pantsbuild/pants, pull requests merged in 2023-07, with the labels that each got.

#19286 Improved error message when referencing undefined BUILD symbols
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
Labels: category:bugfix

#19411 Automate Slack release announcement.
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
  src/python/pants_release/generate_release_announcement.py
Labels: category:internal

#19406 feat: support backends requirements
  docs/markdown/Writing Plugins/plugins-overview.md
  src/python/pants/backend/experimental/scala/__init__.py
  src/python/pants/backend/experimental/scala/lint/scalafmt/__init__.py
  src/python/pants/backend/experimental/tools/workunit_logger/__init__.py
  src/python/pants/backend/plugin_development/pants_requirements_test.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_test.py
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/macros/common_requirements_rule.py
  src/python/pants/backend/python/macros/pipenv_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/lockfile_metadata_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/backend/python/util_rules/pex_test_utils.py
  src/python/pants/backend/tools/taplo/__init__.py
  src/python/pants/explorer/server/__init__.py
  src/python/pants/init/options_initializer.py
  src/python/pants/init/plugin_resolver.py
  src/python/pants/testutil/pants_integration_test.py
  src/python/pants/util/pip_requirement.py
  src/python/pants/util/pip_requirement_test.py
  src/python/pants/util/requirements.py
  testprojects/pants-plugins/src/python/test_pants_plugin/register.py
  testprojects/pants-plugins/src/python/test_pants_plugin/requirements.txt
  tests/python/pants_test/init/test_plugin_resolver.py
  tests/python/pants_test/integration/BUILD
  tests/python/pants_test/integration/plugin_requirements_integration_test.py
  tests/python/pants_test/util/BUILD
  tests/python/pants_test/util/test_requirements.py
Labels: category:new feature

#19161 Add workflow for testing against public repos
  .github/workflows/public_repos.yaml
  docs/markdown/Contributions/releases/release-process.md
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19412 Add a sponsorships page to the docsite.
  docs/markdown/Introduction/sponsorship.md
Labels: category:documentation

#19417 Add a sponsorships page to the docsite. (Cherry-pick of #19412)
  docs/markdown/Introduction/sponsorship.md
Labels: category:documentation

#19418 Tweak getting-help docs
  docs/markdown/Getting Help/getting-help.md
  docs/markdown/Introduction/sponsorship.md
Labels: needs-cherrypick, category:documentation

#19416 Add a sponsorships page to the docsite. (Cherry-pick of #19412)
  docs/markdown/Introduction/sponsorship.md
Labels: category:documentation

#19413 Refine run_shell_command docs
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/target_types.py
Labels: category:documentation

#19421 Refine run_shell_command docs (Cherry-pick of #19413)
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/target_types.py
Labels: category:documentation

#19422 Refine run_shell_command docs (Cherry-pick of #19413)
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/target_types.py
Labels: category:documentation

#19425 Cherry-pick failure message fixes
  build-support/cherry_pick/helper.js
  build-support/cherry_pick/helper.test.js
  build-support/cherry_pick/make_pr.sh
Labels: category:internal

#19393 Embed a hash of the relevant implementation into the dep inference cache
  src/rust/engine/Cargo.lock
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/dep_inference/build.rs
  src/rust/engine/dep_inference/src/javascript/mod.rs
  src/rust/engine/dep_inference/src/javascript/util.rs
  src/rust/engine/dep_inference/src/lib.rs
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/protos/protos/pants/cache.proto
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:bugfix

#19419 Tweak getting-help docs (Cherry-pick of #19418)
  docs/markdown/Getting Help/getting-help.md
  docs/markdown/Introduction/sponsorship.md
Labels: category:documentation

#19420 Tweak getting-help docs (Cherry-pick of #19418)
  docs/markdown/Getting Help/getting-help.md
  docs/markdown/Introduction/sponsorship.md
Labels: category:documentation

#19435 Prepare the 2.18.0.dev4 release.
  src/python/pants/VERSION
  src/python/pants/notes/2.18.x.md
Labels: category:internal

#19434 Update adhoc-tool.md
  docs/markdown/Ad-Hoc Tools/adhoc-tool.md
Labels: category:documentation

#19225 Provide proper error message for unrecognized symbols during bootstrap.
  src/python/pants/backend/adhoc/BUILD
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
  src/python/pants/engine/target.py
Labels: category:bugfix

#19439 Fix the release announcement step.
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19442 Add Embark Studios to Who Uses Pants page.
  build-support/bin/generate_user_list.py
Labels: category:documentation

#19433 Use the "package_name" variable to fix an UnboundLocalError.
  src/python/pants/backend/go/goals/package_binary.py
Labels: needs-cherrypick, category:bugfix

#19444 Automate GitHub release creation, with wheels
  .github/workflows/release.yaml
  docs/markdown/Contributions/releases/release-process.md
  src/python/pants_release/generate_github_workflows.py
Labels: category:new feature

#19424 Prepare store::remote::ByteStore for other providers
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote/reapi.rs
  src/rust/engine/fs/store/src/remote/reapi_tests.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/grpc_util/src/tls.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
Labels: category:internal

#19453 Use the "package_name" variable to fix an UnboundLocalError. (Cherry-pick of #19433)
  src/python/pants/backend/go/goals/package_binary.py
Labels: category:bugfix

#19456 Visibility: fix issue with using target type in verbose rule selector. (Cherry-pick of #19437)
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:bugfix

#19457 Visibility: fix issue with using target type in verbose rule selector. (Cherry-pick of #19437)
  src/python/pants/backend/adhoc/BUILD
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:bugfix

#19461 Fix unwanted line break in remote-caching-execution.md
  docs/markdown/Using Pants/remote-caching-execution.md
Labels: category:documentation

#19454 Regenerate lockfiles for 3.9.* ICs
  3rdparty/python/user_reqs.lock
Labels: category:internal

#19450 Upload local Pants PEXs to release
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  docs/markdown/Contributions/releases/release-process.md
  src/python/pants/BUILD
  src/python/pants_release/generate_github_workflows.py
  src/python/pants_release/release.py
Labels: category:new feature

#19465 Prepare `2.18.0.dev5`.
  .mailmap
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.18.x.md
Labels: category:internal

#19466 Prepare `2.17.0rc2`.
  src/python/pants/notes/2.17.x.md
Labels: needs-cherrypick, category:internal

#19467 Prepare `2.16.1rc0`.
  src/python/pants/notes/2.16.x.md
Labels: needs-cherrypick, category:internal

#19464 upgrade Rust to v1.71.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  rust-toolchain
  src/rust/engine/src/scheduler.rs
Labels: category:internal

#19155 pex_binary sandbox: Traversing dep graph, stopping after package targets
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: category:bugfix

#19015 Fix golangci-lint runner script
  src/python/pants/backend/go/lint/golangci_lint/rules.py
Labels: needs-cherrypick, backend: Go, category:bugfix

#19296 wire pep621 into tailor
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/goals/tailor_test.py
Labels: category:new feature, backend: Python

#19474 Add `GH_TOKEN` to `gh` commands
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19470 Set explicit ICs in a few more tests.
  src/python/pants/backend/python/goals/publish_test.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules_integration_test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/core/target_types_test.py
Labels: category:internal

#19468 Prepare `2.17.0rc2`. (Cherry-pick of #19466)
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19471 upgrade to Tokio v1.29.1 + deps
  src/rust/engine/Cargo.lock
Labels: category:internal

#19477 Add `GH_REPO` to jobs with `gh` calls
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19469 Prepare `2.16.1rc0`. (Cherry-pick of #19467)
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#19455 Resolve Docker addresses relative to the helm_deployment
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/dependency_inference/deployment_test.py
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/k8s_parser_test.py
Labels: category:new feature, backend: Helm

#19452 Use the "package_name" variable to fix an UnboundLocalError. (Cherry-pick of #19433)
  src/python/pants/backend/go/goals/package_binary.py
Labels: category:bugfix

#19481 Add `gh` as a Pants tool
  .github/workflows/tests/BUILD
  3rdparty/tools/act/.actrc
  3rdparty/tools/act/BUILD
  3rdparty/tools/gh/BUILD
  3rdparty/tools/gh/extract.sh
Labels: category:internal

#19483 Use Pants-sandboxed GH in wheel-build jobs
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19484 Add `bash` to list of tools for GH CLI
  3rdparty/tools/gh/BUILD
Labels: category:internal

#19485 It's `./pants` not `pants` in this repo
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19379 Update changelog/contributors/version bump in one script
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  CONTRIBUTORS.md
  build-support/bin/contributors.py
  docs/markdown/Contributions/releases/release-process.md
  src/python/pants_release/common.py
  src/python/pants_release/generate_release_announcement.py
  src/python/pants_release/git.py
  src/python/pants_release/release.py
  src/python/pants_release/start_release.py
  src/python/pants_release/start_release_test.py
Labels: category:internal

#19487 Use `curl` for uploading wheels
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19488 Add missing "outputs" to GitHub outputs declarations
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19489 Expand the wheel dir when uploading wheels
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19491 Link to use_rust_parser documentation for convenience
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
Labels: needs-cherrypick, category:internal

#19427 Add Support for Kubeconform in Helm backend
  docs/markdown/Helm/helm-kubeconform.md
  src/python/pants/backend/experimental/helm/check/__init__.py
  src/python/pants/backend/experimental/helm/check/kubeconform/BUILD
  src/python/pants/backend/experimental/helm/check/kubeconform/__init__.py
  src/python/pants/backend/experimental/helm/check/kubeconform/register.py
  src/python/pants/backend/helm/check/__init__.py
  src/python/pants/backend/helm/check/kubeconform/BUILD
  src/python/pants/backend/helm/check/kubeconform/__init__.py
  src/python/pants/backend/helm/check/kubeconform/chart.py
  src/python/pants/backend/helm/check/kubeconform/chart_test.py
  src/python/pants/backend/helm/check/kubeconform/common.py
  src/python/pants/backend/helm/check/kubeconform/deployment.py
  src/python/pants/backend/helm/check/kubeconform/deployment_test.py
  src/python/pants/backend/helm/check/kubeconform/extra_fields.py
  src/python/pants/backend/helm/check/kubeconform/subsystem.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/testutil.py
  src/python/pants/backend/helm/util_rules/renderer.py
  src/python/pants/backend/helm/util_rules/renderer_test.py
Labels: category:new feature, backend: Helm

#19482 paths: allow finding paths between addresses that expand to multiple targets
  src/python/pants/backend/project_info/paths.py
  src/python/pants/backend/project_info/paths_test.py
Labels: category:new feature

#19438 Visibility: documentation fixes and clarifications.
  docs/markdown/Using Pants/validating-dependencies.md
Labels: needs-cherrypick, category:documentation

#19475 Add build platform and hosts options to docker_image target
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/target_types.py
Labels: category:new feature

#19494 Visibility: documentation fixes and clarifications. (Cherry-pick of #19438)
  docs/markdown/Using Pants/validating-dependencies.md
Labels: category:documentation

#19495 Visibility: documentation fixes and clarifications. (Cherry-pick of #19438)
  docs/markdown/Using Pants/validating-dependencies.md
Labels: category:documentation

#19459 Prepare remote::remote_cache::CommandRunner for other providers
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/process_execution/remote/src/remote_cache/reapi.rs
  src/rust/engine/process_execution/remote/src/remote_cache/reapi_tests.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/testutil/mock/src/action_cache_service.rs
Labels: category:internal

#19476 docs: explain that visibility rules do not apply transitively
  docs/markdown/Using Pants/validating-dependencies.md
Labels: category:documentation

#19446 Support using `__defaults__` in same BUILD file as environment targets.
  docs/markdown/Using Pants/concepts/targets.md
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
Labels: needs-cherrypick, category:bugfix

#19440 feat: ptype type checker
  build-support/bin/generate_builtin_lockfiles.py
  build-support/bin/generate_docs.py
  src/python/pants/backend/python/typecheck/pytype/BUILD
  src/python/pants/backend/python/typecheck/pytype/__init__.py
  src/python/pants/backend/python/typecheck/pytype/pytype.lock
  src/python/pants/backend/python/typecheck/pytype/register.py
  src/python/pants/backend/python/typecheck/pytype/rules.py
  src/python/pants/backend/python/typecheck/pytype/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pytype/skip_field.py
  src/python/pants/backend/python/typecheck/pytype/subsystem.py
Labels: category:new feature

#19498 python: add default module mapping of scikit-video Python package
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:new feature

#19492 Link to use_rust_parser documentation for convenience (Cherry-pick of #19491)
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
Labels: category:internal

#19501 docs: explain that run_goal_use_sandbox field won't have any effect with the test goal execution
  src/python/pants/backend/python/target_types.py
Labels: category:documentation

#19504 docs: fix typo from docker.md
  docs/markdown/Docker/docker.md
Labels: category:documentation

#19511 Add Aviva Credito to user list.
  build-support/bin/generate_user_list.py
Labels: category:documentation

#19510 docs: mention addressing targets in the current directory with :
  docs/markdown/Using Pants/concepts/goals.md
Labels: category:documentation

#19519 Prepare 2.18.0.dev6
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.18.x.md
Labels: category:internal, automation:release-prep

#19506 Add visibility rules for the python_test targets
  src/python/pants/BUILD
Labels: category:internal

#19527 Support discarding inferred Helm snapshot dependencies
  src/python/pants/backend/helm/dependency_inference/unittest.py
  src/python/pants/backend/helm/dependency_inference/unittest_test.py
Labels: category:bugfix, backend: Helm

#19528 async-ify some of the bootstrap logic
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote/reapi.rs
  src/rust/engine/fs/store/src/remote/reapi_tests.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/grpc_util/src/lib.rs
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/process_execution/remote/src/remote_cache/reapi.rs
  src/rust/engine/process_execution/remote/src/remote_cache/reapi_tests.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
Labels: category:internal

#19535 Send user messages to stderr in `common.py`
  src/python/pants_release/common.py
Labels: category:internal

#19534 Replace v2 .rst changelogs with .md
  src/python/pants/notes/2.0.x.md
  src/python/pants/notes/2.0.x.rst
  src/python/pants/notes/2.1.x.md
  src/python/pants/notes/2.1.x.rst
Labels: category:internal
