Repository pantsbuild/pants, pull requests merged in 2023-09, with the labels that each got.

#19747 Remove Toolchain from who uses Pants page
  build-support/bin/generate_user_list.py
Labels: category:documentation

#19744 Remove last bits of `SecondaryOwnershipMixin` (Cherry-pick of #19742)
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/base/specs_integration_test.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/engine/target.py
Labels: category:internal

#19741 A few cleanups from no longer in-sourcing the changelog
  docs/markdown/Contributions/releases/release-process.md
  pants-plugins/internal_plugins/releases/BUILD
  pants-plugins/internal_plugins/releases/register.py
  pants-plugins/internal_plugins/releases/releases_test.py
  pants.toml
  src/python/pants/ABOUT.md
Labels: needs-cherrypick, category:internal

#19754 Move the explorer plugin to `pants-plugins`
  3rdparty/python/BUILD
  pants-plugins/README.md
  pants-plugins/pants_explorer/server/BUILD
  pants-plugins/pants_explorer/server/__init__.py
  pants-plugins/pants_explorer/server/browser.py
  pants-plugins/pants_explorer/server/graphql/BUILD
  pants-plugins/pants_explorer/server/graphql/context.py
  pants-plugins/pants_explorer/server/graphql/field_types.py
  pants-plugins/pants_explorer/server/graphql/query/BUILD
  pants-plugins/pants_explorer/server/graphql/query/conftest.py
  pants-plugins/pants_explorer/server/graphql/query/root.py
  pants-plugins/pants_explorer/server/graphql/query/rules.py
  pants-plugins/pants_explorer/server/graphql/query/rules_test.py
  pants-plugins/pants_explorer/server/graphql/query/targets.py
  pants-plugins/pants_explorer/server/graphql/query/targets_test.py
  pants-plugins/pants_explorer/server/graphql/rules.py
  pants-plugins/pants_explorer/server/graphql/setup.py
  pants-plugins/pants_explorer/server/graphql/subsystem.py
  pants-plugins/pants_explorer/server/integration_test.py
  pants-plugins/pants_explorer/server/register.py
  pants-plugins/pants_explorer/server/uvicorn.py
  pants.toml
  src/python/pants/backend/BUILD
  src/python/pants_release/release.py
Labels: category:internal

#19753 A few cleanups from no longer in-sourcing the changelog (Cherry-pick of #19741)
  docs/markdown/Contributions/releases/release-process.md
  pants-plugins/internal_plugins/releases/BUILD
  pants-plugins/internal_plugins/releases/register.py
  pants-plugins/internal_plugins/releases/releases_test.py
  pants.toml
  src/python/pants/ABOUT.md
Labels: category:internal

#19764 Remove Helm deprecations scheduled for 2.19
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/goals/deploy_test.py
  src/python/pants/backend/helm/subsystems/unittest.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/test/unittest_test.py
  src/python/pants/backend/helm/util_rules/chart.py
  src/python/pants/backend/helm/util_rules/chart_test.py
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
  src/python/pants/backend/helm/util_rules/renderer.py
  src/python/pants/backend/helm/value_interpolation.py
Labels: category:internal, backend: Helm

#19769 Tweak titles in the release doc
  docs/markdown/Contributions/releases/release-process.md
Labels: needs-cherrypick, category:documentation

#19770 Tweak titles in the release doc (Cherry-pick of #19769)
  docs/markdown/Contributions/releases/release-process.md
Labels: category:documentation

#19768 Remove TestResult.{stdout,stderr} and all uses.
  src/python/pants/backend/codegen/protobuf/go/rules_integration_test.py
  src/python/pants/backend/go/dependency_inference_test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/util_rules/coverage_test.py
  src/python/pants/backend/go/util_rules/embed_integration_test.py
  src/python/pants/backend/javascript/goals/test_integration_test.py
  src/python/pants/backend/kotlin/test/junit_test.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/scala/test/scalatest_test.py
  src/python/pants/backend/shell/goals/test_test.py
  src/python/pants/backend/shell/shunit2_test_runner_integration_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/jvm/test/junit_test.py
Labels: category:plugin api change

#19771 Remove Helm tailor option deprecation scheduled for 2.19
  src/python/pants/backend/helm/goals/tailor.py
  src/python/pants/backend/helm/subsystems/helm.py
Labels: category:internal, backend: Helm

#19784 Avoid Python patch version in engine hash
  build-support/bin/rust/calculate_engine_hash.sh
Labels: category:internal

#19737 Restore retries for stores to remote REAPI byte stores
  src/rust/engine/fs/store/src/remote/reapi.rs
  src/rust/engine/fs/store/src/remote/reapi_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/testutil/mock/src/cas.rs
  src/rust/engine/testutil/mock/src/cas_service.rs
  src/rust/engine/testutil/mock/src/lib.rs
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: needs-cherrypick, category:internal

#19773 feat: add mappings for packages
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#19779 Add 'cattrs' module to 'cattrs' package entry in default_module_mapping.py
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#19798 Restore retries for stores to remote REAPI byte stores (Cherry-pick of #19737)
  src/rust/engine/fs/store/src/remote/reapi.rs
  src/rust/engine/fs/store/src/remote/reapi_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/testutil/mock/src/cas.rs
  src/rust/engine/testutil/mock/src/cas_service.rs
  src/rust/engine/testutil/mock/src/lib.rs
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: category:internal

#19799 Avoid Python patch version in engine hash (Cherry-pick of #19784)
  build-support/bin/rust/calculate_engine_hash.sh
Labels: category:internal

#19801 Avoid Python patch version in engine hash (Cherry-pick of #19784)
  build-support/bin/rust/calculate_engine_hash.sh
Labels: category:internal

#19790 Improve dep inference versioning scheme
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/dep_inference/Cargo.toml
Labels: needs-cherrypick, category:internal

#19800 Avoid Python patch version in engine hash (Cherry-pick of #19784)
  build-support/bin/rust/calculate_engine_hash.sh
Labels: category:internal

#19795 Mark `make_pr.sh` as executable
  build-support/cherry_pick/make_pr.sh
Labels: category:internal

#19788 `with contextlib.suppress(ImportError)` weakens imports (Cherry-pick of #19293)
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/dep_inference/build.rs
  src/rust/engine/dep_inference/src/javascript/mod.rs
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: category:new feature

#19793 Fix the `warn_or_error` on 2.18.x for the rust parser
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
Labels: category:internal

#19802 Improve dep inference versioning scheme (Cherry-pick of #19790)
  src/rust/engine/Cargo.lock
  src/rust/engine/dep_inference/Cargo.toml
Labels: category:internal

#19803 Improve dep inference versioning scheme (Cherry-pick of #19790)
  src/rust/engine/Cargo.lock
  src/rust/engine/dep_inference/Cargo.toml
Labels: category:internal

#19787 Instructions: pants repo debugging with pycharm
  docs/markdown/Contributions/development/contributions-debugging.md
Labels: category:documentation

#19789 `with contextlib.suppress(ImportError)` weakens imports (Cherry-pick of #19293)
  src/rust/engine/Cargo.lock
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/dep_inference/build.rs
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: category:new feature

#19804 Add test for nested no-infer-dep in Rust Python dep inference
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: needs-cherrypick, category:internal

#19679 docs: add chat archive link, more talks, more example repos
  docs/markdown/Getting Help/getting-help.md
  docs/markdown/Introduction/media.md
Labels: category:documentation

#19806 Fix Documentation (InitialConfiguration) go backend
  docs/markdown/Getting Started/getting-started/initial-configuration.md
Labels: needs-cherrypick, category:documentation

#19809 Fix Documentation (InitialConfiguration) go backend (Cherry-pick of #19806)
  docs/markdown/Getting Started/getting-started/initial-configuration.md
Labels: category:documentation

#19810 Fix Documentation (InitialConfiguration) go backend (Cherry-pick of #19806)
  docs/markdown/Getting Started/getting-started/initial-configuration.md
Labels: category:documentation

#19807 Add test for nested no-infer-dep in Rust Python dep inference (Cherry-pick of #19804)
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: category:internal

#19808 Add test for nested no-infer-dep in Rust Python dep inference (Cherry-pick of #19804)
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: category:internal

#19792 Remove "old" Python dep parser
  src/python/pants/backend/python/dependency_inference/BUILD
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/scripts/BUILD
  src/python/pants/backend/python/dependency_inference/scripts/__init__.py
  src/python/pants/backend/python/dependency_inference/scripts/dependency_visitor_base.py
  src/python/pants/backend/python/dependency_inference/scripts/general_dependency_visitor.py
  src/python/pants/backend/python/dependency_inference/scripts/main.py
Labels: category:plugin api change

#19815 Require no post-download validation for remote->FSDB
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/testutil/src/data.rs
Labels: category:internal

#19711 Stream large blobs to remote cache directly from local cache file
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote/reapi.rs
  src/rust/engine/fs/store/src/remote/reapi_tests.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/grpc_util/src/retry.rs
  src/rust/engine/process_execution/remote/src/remote_cache/reapi.rs
  src/rust/engine/testutil/Cargo.toml
Labels: category:performance

#19822 docs: Improve the help string for the global option 'PANTS_CONCURRENT'.
  src/python/pants/option/global_options.py
Labels: needs-cherrypick, category:documentation

#19825 docs: Improve the help string for the global option 'PANTS_CONCURRENT'. (Cherry-pick of #19822)
  src/python/pants/option/global_options.py
Labels: category:documentation

#19824 docs: Improve the help string for the global option 'PANTS_CONCURRENT'. (Cherry-pick of #19822)
  src/python/pants/option/global_options.py
Labels: category:documentation

#19828 docs: remove Toolchain references (cherrypick #19508)
  docs/markdown/Getting Help/service-providers.md
  docs/markdown/Introduction/welcome-to-pants.md
Labels: category:documentation

#19830 Remove 2.18.x workflow bits
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19829 Build and upload local PEXs on 2.17.x
  .github/workflows/release.yaml
  build-support/bin/generate_github_workflows.py
  src/python/pants/BUILD
Labels: category:internal

#19821 Fix global report coverage for namespaced packages
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
  src/python/pants/backend/python/goals/coverage_py_test.py
Labels: needs-cherrypick, category:bugfix

#19755 Optionally resolve rules by a provided id
  src/python/pants/backend/build_files/utils.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/util_rules/partitions.py
  src/python/pants/core/util_rules/wrap_source.py
  src/python/pants/engine/rules.py
  src/python/pants/jvm/target_types.py
  src/rust/engine/Cargo.lock
  src/rust/engine/rule_graph/Cargo.toml
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/rule_graph/src/rules.rs
  src/rust/engine/rule_graph/src/tests.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/tasks.rs
Labels: category:plugin api change

#19796 Tweak `fix` partitioning to closer align to `lint` partitioning
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/fix_test.py
  src/python/pants/core/goals/lint_test.py
Labels: category:bugfix

#19823 add force-exclude to ruff args
  src/python/pants/backend/python/lint/ruff/rules.py
Labels: category:bugfix

#19835 Add missing openapi `java` codegen backend
  src/python/pants/bin/BUILD
Labels: category:user api change

#19837 Fix global report coverage for namespaced packages (Cherry-pick of #19821)
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
  src/python/pants/backend/python/goals/coverage_py_test.py
Labels: category:bugfix

#19838 Fix global report coverage for namespaced packages (Cherry-pick of #19821)
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
  src/python/pants/backend/python/goals/coverage_py_test.py
Labels: category:bugfix

#19839 Fix global report coverage for namespaced packages (Cherry-pick of #19821)
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
  src/python/pants/backend/python/goals/coverage_py_test.py
Labels: category:bugfix

#19834 Backport all the deployment migration things to 2.16
  build-support/bin/_release_helper.py
Labels: category:internal

#19842 Revert `console` and `indicatif` bumps
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal

#19846 Get rid of last uses of OrderedDict.
  src/python/pants/base/hash_utils.py
  src/python/pants/base/hash_utils_test.py
  src/python/pants/core/util_rules/asdf.py
  src/python/pants/goal/run_tracker.py
  src/python/pants/option/options_fingerprinter.py
  src/python/pants/option/options_fingerprinter_test.py
  src/python/pants/option/options_test.py
  src/python/pants/util/frozendict_test.py
Labels: category:internal

#19845 Re-enable tests that were flaky in the past.
  tests/python/pants_test/integration/graph_integration_test.py
Labels: category:internal

#19847 Restore a formerly flaky test.
  tests/python/pants_test/pantsd/test_process_manager.py
Labels: category:internal

#19850 Use mock clock in test that relies on clock behavior.
  src/python/pants/testutil/mock_time.py
  tests/python/pants_test/pantsd/test_process_manager.py
Labels: category:internal

#19849 Mark the pytype type checker as experimental
  src/python/pants/backend/experimental/python/typecheck/pytype/BUILD
  src/python/pants/backend/experimental/python/typecheck/pytype/__init__.py
  src/python/pants/backend/experimental/python/typecheck/pytype/register.py
Labels: needs-cherrypick, category:internal

#19851 Mark the pytype type checker as experimental (Cherry-pick of #19849)
  src/python/pants/backend/experimental/python/typecheck/pytype/BUILD
  src/python/pants/backend/experimental/python/typecheck/pytype/__init__.py
  src/python/pants/backend/experimental/python/typecheck/pytype/register.py
Labels: category:internal

#19817 Bare minimum "Pants compiles its engine"
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  3rdparty/tools/python3/BUILD
  build-support/bin/classify_changed_files.py
  build-support/bin/classify_changed_files_test.py
  build-support/bin/rust/calculate_engine_hash.sh
  pants.toml
  src/python/pants_release/generate_github_workflows.py
  src/rust/engine/BUILD
  src/rust/engine/cargo_build_shim.sh
  src/rust/engine/rust-toolchain
Labels: category:internal

#19848 Add additional directories with register.py to pants bin deps
  src/python/pants/backend/python/framework/django/dependency_inference.py
  src/python/pants/backend/rust/target_types.py
  src/python/pants/bin/BUILD
Labels: needs-cherrypick, category:bugfix

#19853 Add toolchain'd `protoc` compiler to the engine/client target
  3rdparty/tools/protoc/BUILD
  src/rust/engine/BUILD
  src/rust/engine/cargo_build_shim.sh
Labels: category:internal

#19859 Inline the cargo build shim
  build-support/bin/rust/calculate_engine_hash.sh
  src/rust/engine/BUILD
  src/rust/engine/cargo_build_shim.sh
Labels: category:internal

#19833 Port `pantsd` fingerprinting to Rust, and validate from native client
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/global_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_fingerprinter.py
  src/python/pants/option/options_test.py
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/pantsd/process_manager.py
  src/python/pants/pantsd/service/scheduler_service.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/VERSION
  src/rust/engine/client/Cargo.toml
  src/rust/engine/client/src/client.rs
  src/rust/engine/client/src/client_tests.rs
  src/rust/engine/client/src/lib.rs
  src/rust/engine/client/src/main.rs
  src/rust/engine/client/src/pantsd.rs
  src/rust/engine/hashing/src/lib.rs
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/id.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
  src/rust/engine/options/src/types.rs
  src/rust/engine/pantsd/Cargo.toml
  src/rust/engine/pantsd/src/lib.rs
  src/rust/engine/pantsd/src/pantsd_testing.rs
  src/rust/engine/pantsd/src/pantsd_tests.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: needs-cherrypick, category:bugfix

#19861 Strip `python3.9` from `tools`
  src/rust/engine/BUILD
Labels: category:internal

#19855 Add additional directories with register.py to pants bin deps (Cherry pick of #19848)
  src/python/pants/backend/python/framework/django/dependency_inference.py
  src/python/pants/bin/BUILD
Labels: category:bugfix

#19856 Add additional directories with register.py to pants bin deps (Cherry pick of #19848)
  src/python/pants/backend/python/framework/django/dependency_inference.py
  src/python/pants/backend/rust/target_types.py
  src/python/pants/bin/BUILD
Labels: category:bugfix

#19857 Add additional directories with register.py to pants bin deps (Cherry pick of #19848)
  src/python/pants/bin/BUILD
Labels: category:bugfix

#19811 Add cache-to and cache-from options
  docs/markdown/Docker/docker.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/target_types.py
Labels: category:new feature

#19840 Prepare 2.19.0.dev0
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.19.x.md
Labels: category:internal, automation:release-prep

#19841 Prepare 2.18.0rc0
  src/python/pants/VERSION
Labels: category:internal

#19865 Fix release automation - more protoc
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#19867 Port `pantsd` fingerprinting to Rust, and validate from native client (Cherry-pick of #19833)
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/global_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_fingerprinter.py
  src/python/pants/option/options_test.py
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/pantsd/process_manager.py
  src/python/pants/pantsd/service/scheduler_service.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/VERSION
  src/rust/engine/client/Cargo.toml
  src/rust/engine/client/src/client.rs
  src/rust/engine/client/src/client_tests.rs
  src/rust/engine/client/src/lib.rs
  src/rust/engine/client/src/main.rs
  src/rust/engine/client/src/pantsd.rs
  src/rust/engine/hashing/src/lib.rs
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/id.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
  src/rust/engine/options/src/types.rs
  src/rust/engine/pantsd/Cargo.toml
  src/rust/engine/pantsd/src/lib.rs
  src/rust/engine/pantsd/src/pantsd_testing.rs
  src/rust/engine/pantsd/src/pantsd_tests.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: category:bugfix

#19864 Port `pantsd` fingerprinting to Rust, and validate from native client (Cherry-pick of #19833)
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/global_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_fingerprinter.py
  src/python/pants/option/options_test.py
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/pantsd/process_manager.py
  src/python/pants/pantsd/service/scheduler_service.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/VERSION
  src/rust/engine/client/Cargo.toml
  src/rust/engine/client/src/client.rs
  src/rust/engine/client/src/client_tests.rs
  src/rust/engine/client/src/lib.rs
  src/rust/engine/client/src/main.rs
  src/rust/engine/client/src/pantsd.rs
  src/rust/engine/hashing/src/lib.rs
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/id.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
  src/rust/engine/options/src/types.rs
  src/rust/engine/pantsd/Cargo.toml
  src/rust/engine/pantsd/src/lib.rs
  src/rust/engine/pantsd/src/pantsd_testing.rs
  src/rust/engine/pantsd/src/pantsd_tests.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: category:bugfix

#19866 Fix release automation - more protoc (Cherry-pick of #19865)
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19871 Pass `GH_TOKEN` to `src/python/pants_release/changelog.py`
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#19873 Don't attempt to get the GitHub User
  src/python/pants_release/git.py
Labels: needs-cherrypick, category:internal

#19874 Pass `GH_TOKEN` to `src/python/pants_release/changelog.py` (Cherry-pick of #19871)
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19875 Fetch tags in the `publish` job
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#19854 List every single backend in docs
  docs/markdown/Using Pants/concepts/enabling-backends.md
Labels: needs-cherrypick, category:documentation

#19877 Fetch tags in the `publish` job (Cherry-pick of #19875)
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19876 Don't attempt to get the GitHub User (Cherry-pick of #19873)
  src/python/pants_release/git.py
Labels: category:internal

#19797 Introduce by-name `@rule` call syntax
  src/python/pants/backend/build_files/fix/deprecations/renamed_fields_rules_test.py
  src/python/pants/backend/build_files/fix/deprecations/renamed_targets_rules_test.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/internals/rule_visitor_test.py
  src/python/pants/engine/internals/scheduler_test.py
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/rules_test.py
  src/python/pants/option/subsystem.py
  src/python/pants/source/source_root_test.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
Labels: category:internal

#19880 Add kubeconfirm, fix typos in enabling-backends.md docs
  docs/markdown/Using Pants/concepts/enabling-backends.md
Labels: category:documentation

#19878 List every single backend in docs (Cherry-pick of #19854, #19880)
  docs/markdown/Using Pants/concepts/enabling-backends.md
Labels: category:documentation

#19868 Add a sandboxed cargo to the engine compilation
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  3rdparty/tools/rust/BUILD
  src/python/pants_release/generate_github_workflows.py
  src/rust/engine/BUILD
  src/rust/engine/rust-toolchain
Labels: category:internal

#19893 Little improvement to the workflow generator
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19890 Prepare 2.16.1rc1
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#19889 Prepare 2.17.1rc0
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19895 Update release docs with latest changes
  docs/markdown/Contributions/releases/release-process.md
Labels: category:documentation

#19896 Update release docs with latest changes
  docs/markdown/Contributions/releases/release-process.md
Labels: category:documentation

#19881 Upgrade to Rust 1.72.1
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/rust-toolchain
Labels: category:internal

#19827 Add support for OpenDAL-backed remote stores (file://, initially)
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/option/global_options.py
  src/python/pants/option/global_options_test.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote/base_opendal.rs
  src/rust/engine/fs/store/src/remote/base_opendal_tests.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/process_execution/remote/Cargo.toml
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/process_execution/remote/src/remote_cache/base_opendal.rs
  src/rust/engine/process_execution/remote/src/remote_cache/base_opendal_tests.rs
Labels: category:new feature

#19901 Update tests for removal of `python36` from Github Actions hostedtoolcache
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/goals/platform-linux-py36.json
  src/python/pants/backend/python/goals/platform-linux-py38.json
  src/python/pants/backend/python/goals/platform-mac-py36.json
  src/python/pants/backend/python/goals/platform-mac-py38.json
  src/python/pants/testutil/python_interpreter_selection.py
  tests/python/pants_test/init/test_plugin_resolver.py
Labels: needs-cherrypick, category:internal

#19899 Add missing `__init__.py` file for the `yamllint` backend.
  src/python/pants/backend/experimental/tools/yamllint/__init__.py
Labels: needs-cherrypick, category:bugfix

#19894 Fix "failed to create hardlink" error due to multiple mounts on the same device
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/benches/store.rs
  src/rust/engine/fs/store/src/immutable_inputs.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/pe_nailgun/src/lib.rs
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/engine/process_execution/pe_nailgun/src/tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:bugfix

#19904 Update tests for removal of `python36` from Github Actions hostedtoolcache (Cherry-pick of #19901)
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/goals/platform-linux-py36.json
  src/python/pants/backend/python/goals/platform-linux-py38.json
  src/python/pants/backend/python/goals/platform-mac-py36.json
  src/python/pants/backend/python/goals/platform-mac-py38.json
  src/python/pants/testutil/python_interpreter_selection.py
  tests/python/pants_test/init/test_plugin_resolver.py
Labels: category:internal

#19905 Update tests for removal of `python36` from Github Actions hostedtoolcache (Cherry-pick of #19901)
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/goals/platform-linux-py36.json
  src/python/pants/backend/python/goals/platform-linux-py38.json
  src/python/pants/backend/python/goals/platform-mac-py36.json
  src/python/pants/backend/python/goals/platform-mac-py38.json
  src/python/pants/testutil/python_interpreter_selection.py
  tests/python/pants_test/init/test_plugin_resolver.py
Labels: category:internal

#19909 Update tests for removal of `python36` from Github Actions hostedtoolcache (Cherry-pick of #19901)
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/goals/platform-linux-py36.json
  src/python/pants/backend/python/goals/platform-linux-py38.json
  src/python/pants/backend/python/goals/platform-mac-py36.json
  src/python/pants/backend/python/goals/platform-mac-py38.json
  src/python/pants/testutil/python_interpreter_selection.py
  tests/python/pants_test/init/test_plugin_resolver.py
Labels: category:internal

#19908 Add missing `__init__.py` file for the `yamllint` backend. (Cherry-pick of #19899)
  src/python/pants/backend/experimental/tools/yamllint/__init__.py
Labels: category:bugfix

#19906 Add missing `__init__.py` file for the `yamllint` backend. (Cherry-pick of #19899)
  src/python/pants/backend/experimental/tools/yamllint/__init__.py
Labels: category:bugfix

#19912 Reenable possibly flaky graph test.
  src/rust/engine/graph/src/tests.rs
Labels: category:internal

#19900 Enable lockfile diff report by default.
  src/python/pants/core/goals/generate_lockfiles.py
Labels: category:user api change

#19915 Add (experimental) named caches field to `shell_command` and `adhoc_tool`
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
Labels: category:internal

#19910 Fix "failed to create hardlink" error due to multiple mounts on the same device (Cherry-pick of #19894)
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/benches/store.rs
  src/rust/engine/fs/store/src/immutable_inputs.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/pe_nailgun/src/lib.rs
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/engine/process_execution/pe_nailgun/src/tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#19914 Fix "failed to create hardlink" error due to multiple mounts on the same device (Cherry-pick of #19894)
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/benches/store.rs
  src/rust/engine/fs/store/src/immutable_inputs.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/pe_nailgun/src/lib.rs
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/engine/process_execution/pe_nailgun/src/tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#19917 Use preamble for more Rust stuff
  build-support/bin/check_rust_pre_commit.sh
  build-support/bin/check_rust_target_headers.sh
  build-support/bin/create_s3_index_file.sh
  build-support/preambles/config.yaml
  build-support/rust-target-prefix.txt
Labels: category:internal

#19870 bump javaparser and add test for sealed/permits/yield/switch expressions
  3rdparty/jvm/com/github/javaparser/BUILD
  src/python/pants/backend/java/dependency_inference/java_parser.lock
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/backend/java/dependency_inference/java_parser_test.py
Labels: category:bugfix

#19911 Move .pids under .pants.d by default
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .gitignore
  build-support/bin/cache_comparison.py
  build-support/bin/generate_json_schema.py
  build-support/python/clean.sh
  docs/markdown/Getting Started/getting-started/initial-configuration.md
  docs/markdown/Go/go.md
  docs/markdown/Using Pants/troubleshooting.md
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/init/util.py
  src/python/pants/option/global_options.py
  src/python/pants/option/options_bootstrapper_test.py
  src/python/pants/pantsd/process_manager.py
  src/python/pants/testutil/rule_runner.py
  src/python/pants/vcs/changed_integration_test.py
  src/python/pants_release/generate_github_workflows.py
  src/rust/engine/client/src/client_tests.rs
  src/rust/engine/pantsd/src/lib.rs
  tests/python/pants_test/pantsd/pantsd_integration_test_base.py
  tests/python/pants_test/pantsd/test_process_manager.py
Labels: category:user api change

#19918 Move `check_banned_imports` into Pants
  build-support/bin/check_banned_imports.py
  build-support/githooks/pre-commit
  src/rust/engine/BUILD
Labels: category:internal

#19919 Move `check_inits.py` into Pants
  BUILD
  build-support/bin/check_inits.py
  build-support/githooks/pre-commit
Labels: category:internal

#19928 Prepare `2.16.1rc2`
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#19927 Pin Pants PEX ICs to 3.9
  src/python/pants/BUILD
Labels: category:internal

#19929 Restore a flaky test.
  tests/python/pants_test/integration/goal_rule_integration_test.py
Labels: category:internal

#19920 Support using `parametrize()` with a single value.
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
Labels: category:bugfix

#19924 Remove references to PyPI/`pantsbuild.pants` wheels in docs
  README.md
  docs/markdown/Contributions/releases/release-process.md
  docs/markdown/Releases/upgrade-tips.md
  docs/markdown/Using Pants/restricted-internet-access.md
Labels: needs-cherrypick, category:documentation

#19930 Remove references to PyPI/`pantsbuild.pants` wheels in docs (Cherry-pick of #19924)
  README.md
  docs/markdown/Contributions/releases/release-process.md
  docs/markdown/Releases/upgrade-tips.md
  docs/markdown/Using Pants/restricted-internet-access.md
Labels: category:documentation

#19933 Prepare 2.18.0rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#19936 Remove references to PyPI/`pantsbuild.pants` wheels in docs (Cherry-pick of #19924)
  README.md
  docs/markdown/Contributions/releases/release-process.md
  docs/markdown/Releases/upgrade-tips.md
  docs/markdown/Using Pants/restricted-internet-access.md
Labels: category:documentation

#19934 Prepare 2.19.0.dev1
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#19684 Regex dependency inference module mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
  src/python/pants/backend/python/dependency_inference/module_mapper.py
  src/python/pants/backend/python/dependency_inference/module_mapper_test.py
Labels: category:bugfix

#19935 Visibility: Fix issue with root paths.
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
Labels: needs-cherrypick, category:bugfix

#19937 Visibility: Fix issue with root paths. (Cherry-pick of #19935)
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
Labels: category:bugfix

#19923 Always have coloured output and then strip later for pytest, helm unittest, shunit2
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/openapi/lint/openapi_format/rules.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules.py
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/ruff/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/backend/shell/shunit2_test_runner_integration_test.py
  src/python/pants/backend/tools/semgrep/rules.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/test.py
  src/python/pants/jvm/compile.py
  src/python/pants/option/global_options.py
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: category:plugin api change

#19938 Require Cargo.lock matches Cargo.toml in CI
  .github/workflows/test.yaml
  build-support/bin/check_rust_pre_commit.sh
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19858 Support pass-through args to the repl goal for ipython
  docs/markdown/Python/python-goals/python-repl-goal.md
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/scala/goals/repl.py
  src/python/pants/core/goals/repl.py
  src/python/pants/core/goals/repl_test.py
Labels: category:new feature

#19831 Add a GitHub Actions Cache remote cache backend
  docs/markdown/Using Pants/remote-caching-execution.md
  docs/markdown/Using Pants/remote-caching-execution/remote-caching.md
  src/python/pants/option/global_options.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote/base_opendal.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
Labels: category:new feature

#19903 Immediately invalidate written files in write_digest
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/fs/src/directory_tests.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/scheduler.rs
  src/rust/engine/watch/src/lib.rs
  src/rust/engine/watch/src/tests.rs
Labels: needs-cherrypick, category:bugfix

#19430 Fix missing venv path when running Pyright
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
Labels: category:bugfix

#19948 Immediately invalidate written files in write_digest (Cherry-pick of #19903)
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/fs/src/directory_tests.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/scheduler.rs
  src/rust/engine/watch/src/lib.rs
  src/rust/engine/watch/src/tests.rs
Labels: category:bugfix

#19949 Immediately invalidate written files in write_digest (Cherry-pick of #19903)
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/fs/src/directory_tests.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/scheduler.rs
  src/rust/engine/watch/src/lib.rs
  src/rust/engine/watch/src/tests.rs
Labels: category:bugfix

#19945 Fetch shellcheck from vscode-shellcheck for M1 support
  src/python/pants/backend/shell/lint/shellcheck/subsystem.py
Labels: needs-cherrypick, category:bugfix

#19951 Fetch shellcheck from vscode-shellcheck for M1 support (Cherry-pick of #19945)
  src/python/pants/backend/shell/lint/shellcheck/subsystem.py
Labels: category:bugfix

#19952 Fetch shellcheck from vscode-shellcheck for M1 support (Cherry-pick of #19945)
  src/python/pants/backend/shell/lint/shellcheck/subsystem.py
Labels: category:bugfix

#19926 Don't crash in the presence of non-UTF-8 env vars.
  src/python/pants/bin/loader_integration_test.py
  src/python/pants/bin/remote_pants_runner.py
  src/python/pants/testutil/pants_integration_test.py
  src/rust/engine/client/src/main.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/env_tests.rs
  src/rust/engine/src/externs/nailgun.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: category:bugfix
