Repository pantsbuild/pants, pull requests merged in 2023-11, with the labels that each got.

#20126 Add `exclude_files` field to `deploy_jar` target (Cherry-pick of #20075)
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/target_types.py
Labels: category:new feature

#20121 Restore x86-on-Arm Mac downloads for older coursier versions
  src/python/pants/core/util_rules/external_tool.py
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: needs-cherrypick, category:internal

#20118 Restore protoc 3.20.1 support on apple silicon
  src/python/pants/backend/codegen/protobuf/protoc.py
Labels: category:internal

#20139 Fix mypy cache dir not being created
  src/python/pants/backend/python/typecheck/mypy/rules.py
Labels: needs-cherrypick, category:bugfix

#20142 Fix mypy cache dir not being created (Cherry-pick of #20139)
  src/python/pants/backend/python/typecheck/mypy/rules.py
Labels: category:bugfix

#20141 Restore x86-on-Arm Mac downloads for older coursier versions (Cherry-pick of #20121)
  src/python/pants/core/util_rules/external_tool.py
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: category:internal

#20059 Parametrizable plugin fields for target generators
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/target.py
Labels: category:new feature

#20144 Avoid quotes in suggested .env file for IDEs
  docs/markdown/Using Pants/setting-up-an-ide.md
Labels: needs-cherrypick, category:documentation

#19999 Initial sketch of what's new in 2.18
  src/python/pants/notes/2.18.x.md
Labels: needs-cherrypick, category:documentation

#20146 Avoid quotes in suggested .env file for IDEs (Cherry-pick of #20144)
  docs/markdown/Using Pants/setting-up-an-ide.md
Labels: category:documentation

#20145 Avoid quotes in suggested .env file for IDEs (Cherry-pick of #20144)
  docs/markdown/Using Pants/setting-up-an-ide.md
Labels: category:documentation

#20147 Initial sketch of what's new in 2.18 (Cherry-pick of #19999)
  src/python/pants/notes/2.18.x.md
Labels: category:documentation

#20148 Prepare 2.18.0rc5
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20143 Add helper for conditionally recording metrics
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/grpc_util/src/lib.rs
  src/rust/engine/grpc_util/src/metrics.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/lib.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store.rs
  src/rust/engine/workunit_store/src/lib.rs
Labels: category:internal

#20138 Add additional metrics for remote byte stores
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/lib.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store.rs
  src/rust/engine/remote_provider/remote_provider_traits/src/lib.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: category:internal

#20069 Fix `protobuf_sources` with parametrized `python_resolve`
  src/python/pants/backend/codegen/protobuf/python/additional_fields.py
Labels: category:bugfix

#20157 Resolve appropriate Scala artifacts for BSP
  src/python/pants/backend/scala/bsp/rules.py
Labels: needs-cherrypick, backend: JVM, category:bugfix, bsp

#20155 Update docs with get-pants.sh new install location: `~/.local/bin`
  docs/markdown/Getting Started/getting-started/installation.md
Labels: enhancement, category:documentation

#20065 Support grouping parametrizations
  docs/markdown/Using Pants/concepts/targets.md
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/defaults_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
Labels: category:new feature

#20165 Misc help text cleanups
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/wrap_source.py
  src/python/pants/engine/fs.py
Labels: category:internal

#20096 Optional nix setup for developing in the Pants repo
  docs/markdown/Contributions/development/contributor-setup.md
  shell.nix
Labels: category:internal

#20168 Prepare 2.19.0a0
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20167 Prepare 2.18.0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20169 Prepare 2.17.1
  src/python/pants/VERSION
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#20149 Update PEX to 2.1.152
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:internal

#20154 Add docker image output field to support publish to repository when using BuildKit
  docs/markdown/Docker/docker.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_binary_test.py
Labels: category:new feature, backend: Docker

#20177 Fix: support helm repos with trailing slashes
  src/python/pants/backend/helm/dependency_inference/chart.py
  src/python/pants/backend/helm/dependency_inference/chart_test.py
Labels: category:bugfix, backend: Helm

#20185 Add docker image output field to support publish to repository when using BuildKit (Cherry-pick of #20154)
  docs/markdown/Docker/docker.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_binary_test.py
Labels: category:new feature

#20135 Code Quality Tool Lib
  src/python/pants/backend/adhoc/code_quality_tool.py
  src/python/pants/backend/adhoc/code_quality_tool_integration_test.py
  src/python/pants/backend/experimental/adhoc/register.py
Labels: category:new feature

#20183 Remove documentation about new remote caching in 2.19
  docs/markdown/Using Pants/remote-caching-execution/remote-caching.md
  src/python/pants/option/global_options.py
Labels: category:documentation

#20184 Use a Zulu JDK 8 to run the Kotlin analyzer.
  src/python/pants/backend/kotlin/dependency_inference/BUILD
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser_test.py
Labels: needs-cherrypick, category:bugfix

#20194 Use a Zulu JDK 8 to run the Kotlin analyzer. (Cherry-pick of #20184)
  src/python/pants/backend/kotlin/dependency_inference/BUILD
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser_test.py
Labels: category:bugfix

#20191 Do not choke on values from macros on environment targets during bootstrap.
  docs/markdown/Using Pants/environments.md
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/parser.py
Labels: category:bugfix

#20195 Use a Zulu JDK 8 to run the Kotlin analyzer. (Cherry-pick of #20184)
  src/python/pants/backend/kotlin/dependency_inference/BUILD
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser_test.py
Labels: category:bugfix

#20198 Do not choke on values from macros on environment targets during bootstrap. (Cherry-pick of #20191)
  docs/markdown/Using Pants/environments.md
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/parser.py
Labels: category:bugfix

#20197 upgrade to Rust v1.74.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/rust-toolchain
  src/rust/engine/testutil/src/data.rs
Labels: category:internal

#20196 Remove print() statement
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
Labels: needs-cherrypick, category:bugfix

#20203 Remove print() statement (Cherry-pick of #20196)
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
Labels: category:bugfix

#20190 Support inferring JS deps from `export ... from ...` statements
  src/rust/engine/dep_inference/src/javascript/mod.rs
  src/rust/engine/dep_inference/src/javascript/tests.rs
Labels: category:bugfix

#20117 Refine Rust workspace members for recently added crates
  src/rust/engine/Cargo.toml
Labels: category:internal

#20199 Do not choke on values from macros on environment targets during bootstrap. (Cherry-pick of #20191)
  docs/markdown/Using Pants/environments.md
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/parser.py
Labels: category:bugfix

#20163 Resolve appropriate Scala artifacts for BSP (Cherry-pick of #20157)
  src/python/pants/backend/scala/bsp/rules.py
Labels: category:bugfix

#20192 Skip jvm dependencies without entries
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
Labels: needs-cherrypick, backend: JVM, category:bugfix

#20211 Skip jvm dependencies without entries (Cherry-pick of #20192)
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
Labels: category:bugfix

#20213 Remove deprecated `@rule_helper`
  build-support/flake8/await_in_loop.py
  src/python/pants/engine/internals/rule_visitor_test.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/rules_test.py
  src/python/pants/testutil/rule_runner.py
Labels: category:plugin api change

#20212 Skip jvm dependencies without entries (Cherry-pick of #20192)
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
Labels: category:bugfix

#20214 Remove deprecated `[export].symlink_python_virtualenv` option
  src/python/pants/backend/python/goals/export.py
Labels: category:user api change

#20217 Silence warnings about internal call of deprecated Helm function on 2.18
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/util_rules/renderer.py
Labels: category:bugfix

#20215 Prepare 2.20.0.dev0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20216 Prepare 2.18.1rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20223 Add link to talk at Hamburg Python Pizza
  docs/markdown/Introduction/media.md
Labels: category:documentation

#20220 Fix spurious warnings about Helm interpolations due to incorrect comparison
  src/python/pants/backend/helm/target_types.py
Labels: category:bugfix

#20218 Prepare 2.16.1
  src/python/pants/VERSION
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#20116 Add `remote_oauth_bearer_token` option, deprecating `remote_oauth_bearer_token_path`
  docs/markdown/Using Pants/remote-caching-execution/remote-caching.md
  src/python/pants/option/global_options.py
  src/rust/engine/remote_provider/remote_provider_opendal/src/lib.rs
Labels: category:user api change

#20231 Add note in docker_environment image field help on tool requirements
  src/python/pants/core/util_rules/environments.py
Labels: category:documentation

#20235 Add note in docker_environment image field help on tool requirements (Cherry-pick of #20231)
  src/python/pants/core/util_rules/environments.py
Labels: category:documentation

#20233 add reformat commit to ignore revs
  .git-blame-ignore-revs
Labels: category:internal

#20234 Add note in docker_environment image field help on tool requirements (Cherry-pick of #20231)
  src/python/pants/core/util_rules/environments.py
Labels: category:documentation

#20236 upgrade to tonic v0.10.x
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/protos/Cargo.toml
Labels: category:internal

#20248 Discover Ruff config in pyproject.toml in subdirectories
  src/python/pants/backend/python/lint/ruff/rules_integration_test.py
  src/python/pants/backend/python/lint/ruff/subsystem.py
Labels: category:new feature

#20249 Update to Ruff 0.1.6
  src/python/pants/backend/experimental/python/lint/ruff/register.py
  src/python/pants/backend/python/lint/ruff/ruff.lock
Labels: category:user api change

#20244 Prepare 2.18.1rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep
