Repository pantsbuild/pants, pull requests merged in 2023-05, with the labels that each got.

#18742 javascript: Nodejs tests batch support
  src/python/pants/backend/javascript/goals/test.py
  src/python/pants/backend/javascript/goals/test_integration_test.py
  src/python/pants/backend/javascript/goals/test_test.py
  src/python/pants/backend/javascript/subsystems/nodejstest.py
  src/python/pants/backend/javascript/target_types.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/core/goals/test.py
Labels: category:new feature

#18868 Unhide visibility docs. (Cherry-pick of #18824)
  docs/markdown/Using Pants/validating-dependencies.md
Labels: category:internal

#18867 help backends: Only list enabled experimental backends unless advanced help. (Cherry-pick of #18821)
  src/python/pants/help/help_printer.py
Labels: category:bugfix

#18869 Include `symbols` as topic in usage help. (Cherry-pick of #18825)
  src/python/pants/help/help_printer.py
Labels: category:documentation

#18855 Eagerly clean running nodes rather than interrupting them.
  src/rust/engine/async_value/src/lib.rs
  src/rust/engine/async_value/src/tests.rs
  src/rust/engine/graph/src/context.rs
  src/rust/engine/graph/src/entry.rs
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/graph/src/node.rs
  src/rust/engine/graph/src/tests.rs
  src/rust/engine/src/nodes.rs
Labels: category:new feature

#18866 Patch `StreamingWorkunitContext.get_expanded_specs()`. (Cherry-pick of #18713)
  src/python/pants/engine/streaming_workunit_handler.py
Labels: category:bugfix

#18874 Update to tokio 1.28.0
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/async_latch/Cargo.toml
  src/rust/engine/async_value/Cargo.toml
  src/rust/engine/client/Cargo.toml
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/brfs/Cargo.toml
  src/rust/engine/fs/fs_util/Cargo.toml
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/graph/Cargo.toml
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/hashing/Cargo.toml
  src/rust/engine/logging/Cargo.toml
  src/rust/engine/nailgun/Cargo.toml
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/docker/Cargo.toml
  src/rust/engine/process_execution/pe_nailgun/Cargo.toml
  src/rust/engine/process_execution/remote/Cargo.toml
  src/rust/engine/process_executor/Cargo.toml
  src/rust/engine/sharded_lmdb/Cargo.toml
  src/rust/engine/stdio/Cargo.toml
  src/rust/engine/task_executor/Cargo.toml
  src/rust/engine/testutil/mock/Cargo.toml
  src/rust/engine/watch/Cargo.toml
  src/rust/engine/workunit_store/Cargo.toml
Labels: category:internal

#18876 Upgrade Pex to 2.1.135.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18861 Ensure non-ambiguous args/env vars injection into PEXes
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: needs-cherrypick, category:bugfix

#18873 Remove existing entry if any when materialising symlink
  src/rust/engine/fs/store/src/lib.rs
Labels: needs-cherrypick, category:bugfix

#18864 javascript: Add support for the pnpm package manager
  src/python/pants/backend/javascript/goals/BUILD
  src/python/pants/backend/javascript/goals/jest_resources/BUILD
  src/python/pants/backend/javascript/goals/jest_resources/pnpm-lock.yaml
  src/python/pants/backend/javascript/goals/lockfile.py
  src/python/pants/backend/javascript/goals/lockfile_test.py
  src/python/pants/backend/javascript/goals/mocha_resources/BUILD
  src/python/pants/backend/javascript/goals/mocha_resources/package.json
  src/python/pants/backend/javascript/goals/mocha_resources/pnpm-lock.yaml
  src/python/pants/backend/javascript/goals/test_integration_test.py
  src/python/pants/backend/javascript/install_node_package.py
  src/python/pants/backend/javascript/nodejs_project.py
  src/python/pants/backend/javascript/nodejs_project_environment.py
  src/python/pants/backend/javascript/nodejs_project_test.py
  src/python/pants/backend/javascript/package/BUILD
  src/python/pants/backend/javascript/package/pnpm-lock.yaml
  src/python/pants/backend/javascript/package/rules_integration_test.py
  src/python/pants/backend/javascript/package/rules_test.py
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/backend/javascript/resolve.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_test.py
Labels: category:new feature

#18877 Ensure non-ambiguous args/env vars injection into PEXes (Cherry-pick of #18861)
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:bugfix

#18892 Credit the Works on ARM program for our CI resources.
  README.md
  build-support/bin/generate_github_workflows.py
Labels: category:documentation

#18860 Actually run deprecated targets fixer
  src/python/pants/backend/build_files/fix/deprecations/renamed_targets_rules.py
  src/python/pants/backend/build_files/fix/deprecations/renamed_targets_rules_test.py
  src/python/pants/core/goals/update_build_files.py
Labels: needs-cherrypick, category:bugfix

#18893 Actually run deprecated targets fixer (Cherry-pick of #18860)
  src/python/pants/backend/build_files/fix/deprecations/renamed_targets_rules.py
  src/python/pants/backend/build_files/fix/deprecations/renamed_targets_rules_test.py
  src/python/pants/core/goals/update_build_files.py
Labels: category:bugfix

#18900 update troubleshooting document about self-hosted action runner
  docs/markdown/Using Pants/troubleshooting.md
Labels: needs-cherrypick, category:documentation

#18907 Add missing backtick in help string
  src/python/pants/backend/adhoc/target_types.py
Labels: category:documentation

#18894 Fix adhoc output_... example, document run_shell_command workdir changes
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/notes/2.16.x.md
Labels: needs-cherrypick, category:documentation

#18910 Fix adhoc output_... example, document run_shell_command workdir changes (Cherry-pick of #18894)
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/notes/2.16.x.md
Labels: category:documentation

#18916 Fingerprint the entire `--version` output of Python interpreters for the pants_venv script.
  build-support/pants_venv
Labels: category:internal

#18927 Remove `ox`-related code
  src/python/pants/bin/pants_loader.py
  src/python/pants/init/extension_loader.py
  src/python/pants/init/plugin_resolver.py
  src/python/pants/option/subsystem.py
  src/python/pants/ox.py
Labels: category:internal

#18833 Deprecate running Pants outside scie-pants.
  pants
  src/python/pants/bin/pants_runner.py
  src/python/pants/testutil/pants_integration_test.py
Labels: category:user api change

#18917 Optimize `Target` and `FieldSet` operations
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/core/util_rules/partitions.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: needs-cherrypick, category:performance

#18919 javascript: Handle package.json placed at the root of the repository
  src/python/pants/backend/javascript/nodejs_project.py
  src/python/pants/backend/javascript/nodejs_project_test.py
Labels: category:bugfix

#18938 Move lockfile test from Ruff (which doesn't delcare lockfile rules) to `lockfile` helper
  src/python/pants/backend/python/lint/ruff/BUILD
  src/python/pants/backend/python/lint/ruff/subsystem_test.py
  src/python/pants/backend/python/util_rules/lockfile_test.py
Labels: category:internal

#18931 javascript: Implement dependency inference opt-out and improve resillience
  src/python/pants/backend/javascript/dependency_inference/import_parser/package-lock.json
  src/python/pants/backend/javascript/dependency_inference/import_parser/package.json
  src/python/pants/backend/javascript/dependency_inference/import_parser/rules.py
  src/python/pants/backend/javascript/dependency_inference/import_parser/rules_test.py
  src/python/pants/backend/javascript/dependency_inference/import_parser/script.cjs
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/javascript/subsystems/nodejs_infer.py
Labels: category:new feature

#18926 javascript: Support `package` goal in `node_build_script` target
  src/python/pants/backend/javascript/package/rules.py
  src/python/pants/backend/javascript/package/rules_integration_test.py
  src/python/pants/backend/javascript/package_json.py
Labels: category:user api change

#18930 Ensure packaged artefacts are fully replaced in dist/
  src/python/pants/core/goals/package.py
  src/python/pants/core/goals/package_test.py
  src/python/pants/engine/fs.py
  src/python/pants/engine/fs_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/src/externs/interface.rs
Labels: category:bugfix

#16410 Update the identity of the response team for CoC violation reporting.
  CODE_OF_CONDUCT.md
  docs/markdown/Getting Help/the-pants-community/code-of-conduct.md
Labels: category:documentation

#18929 fix documentation (Cherry-pick of #18302)
  docs/markdown/Python/python-integrations/awslambda-python.md
Labels: category:documentation

#18940 Do not choke on missing lockfiles.
  src/python/pants/core/target_types.py
  src/python/pants/core/target_types_test.py
Labels: needs-cherrypick, category:bugfix

#18946 doc: mention `use_local_alias` for the `[docker].registries` option.
  src/python/pants/backend/docker/subsystems/docker_options.py
Labels: category:documentation

#18944 Optimize `Target` and `FieldSet` operations (cherry-pick #18917)
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/core/util_rules/partitions.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:performance

#18942 Prepare the 2.17.0.dev5 release
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#18948 Do not choke on missing lockfiles. (Cherry-pick of #18940)
  src/python/pants/core/target_types.py
  src/python/pants/core/target_types_test.py
Labels: category:bugfix

#18947 Do not choke on missing lockfiles. (Cherry-pick of #18940)
  src/python/pants/core/target_types.py
  src/python/pants/core/target_types_test.py
Labels: category:bugfix

#18950 doc: mention `use_local_alias` for the `[docker].registries` option. (Cherry-pick of #18946)
  src/python/pants/backend/docker/subsystems/docker_options.py
Labels: category:documentation

#18854 Extract Python dependencies in an intrinsic
  pants.toml
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
  src/python/pants/backend/python/dependency_inference/subsystem.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/engine/internals/native_dep_inference.py
  src/python/pants/engine/internals/scheduler.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/dep_inference/build.rs
  src/rust/engine/dep_inference/src/lib.rs
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
  src/rust/engine/protos/protos/pants/cache.proto
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/types.rs
Labels: category:new feature

#18945 Add module mappings for all OTEL instrumentation libraries
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#18921 javascript: Do not add literal {chroot} to pnpm cache path
  src/python/pants/backend/javascript/nodejs_project.py
  src/python/pants/backend/javascript/nodejs_project_environment_integration_test.py
Labels: category:bugfix

#18954 Have this repo use the new rust parser for Python
  pants.toml
Labels: category:internal

#18953 Add initial CODEOWNERS with me
  .github/CODEOWNERS
Labels: category:internal

#18957 Include the Pants native client in released wheels
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  build-support/bin/rust/bootstrap_code.sh
  pants
  src/python/pants/BUILD
  src/python/pants/bin/.gitignore
  src/python/pants/bin/BUILD
  src/rust/engine/client/src/main.rs
  src/rust/engine/options/src/build_root.rs
  src/rust/engine/options/src/build_root_tests.rs
Labels: category:new feature

#18964 DRY Lambda/GCF FaaS targets
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/awslambda/python/target_types_test.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types_test.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
Labels: category:internal

#18952 Remove the underlying implementation of `anonymous-telemetry`
  3rdparty/python/BUILD
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  pants.toml
  src/python/pants/goal/anonymous_telemetry.py
  src/python/pants/goal/anonymous_telemetry_integration_test.py
  src/python/pants/goal/anonymous_telemetry_test.py
Labels: category:user api change

#18963 Make `DigestSubset` symlink-aware
  src/rust/engine/fs/store/src/snapshot_ops.rs
  src/rust/engine/fs/store/src/snapshot_ops_tests.rs
  src/rust/engine/fs/store/src/snapshot_tests.rs
Labels: needs-cherrypick, category:bugfix

#18968 Bump Pyo3 to 0.18
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/src/externs/engine_aware.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/python.rs
Labels: category:internal

#18970 Make `DigestSubset` symlink-aware (Cherry-pick of #18963)
  src/rust/engine/fs/store/src/snapshot_ops.rs
  src/rust/engine/fs/store/src/snapshot_ops_tests.rs
  src/rust/engine/fs/store/src/snapshot_tests.rs
Labels: category:bugfix

#18975 Have the cherry-pick script do every relevant milestone
  build-support/bin/cherry_pick.sh
Labels: category:internal

#18976 Log new dependency parsing at Debug, not Info
  src/rust/engine/src/intrinsics.rs
Labels: category:internal

#18971 Require urllib3<2, to reduce installation issues (cherry-pick of #18959)
  3rdparty/python/BUILD
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
Labels: category:bugfix

#18973 Require urllib3<2, to reduce installation issues (cherry-pick of #18959)
  3rdparty/python/BUILD
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
Labels: category:bugfix

#18943 update troubleshooting document about self-hosted action runner (Cherry-pick of #18900)
  docs/markdown/Using Pants/troubleshooting.md
Labels: category:documentation

#18982 Move mandatory process' level to DEBUG
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: needs-cherrypick, category:internal

#18865 Add Taplo toml formatter
  src/python/pants/backend/tools/taplo/BUILD
  src/python/pants/backend/tools/taplo/register.py
  src/python/pants/backend/tools/taplo/rules.py
  src/python/pants/backend/tools/taplo/rules_integration_test.py
  src/python/pants/backend/tools/taplo/subsystem.py
  src/python/pants/option/option_types.py
Labels: category:new feature

#18988 Tweak the cherry-pick script
  build-support/bin/cherry_pick.sh
Labels: category:internal

#18993 Fix example `first_party_dependency_version_scheme` in docs
  docs/markdown/Python/python/python-distributions.md
Labels: category:documentation

#18986 Prepare the 2.16.0rc2 release.
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#18999 Fix release script's expected maintainers (Cherry-pick of #18477)
  build-support/bin/_release_helper.py
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#18934 javascript: Support Node.js subpath imports
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/javascript/dependency_inference/rules_test.py
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/backend/javascript/package_json_test.py
Labels: category:new feature

#18995 Replace `Snapshot::_unsafe_create` with `create_for_testing`.
  src/python/pants/backend/project_info/peek_test.py
  src/python/pants/core/goals/fix_test.py
  src/python/pants/engine/fs_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/rust/engine/fs/store/src/snapshot.rs
  src/rust/engine/src/externs/fs.rs
Labels: category:internal

#18996 Prepare 2.14.2.
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#18997 Prepare 2.15.1rc3.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#19003 Upgrade Pex to 2.1.137.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  build-support/bin/generate_builtin_lockfiles.py
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18935 fmtrequest -> abstractfmtrequest
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-fmt-goal.md
  docs/markdown/Writing Plugins/rules-api/rules-api-unions.md
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/fix_test.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: category:plugin api change

#19000 Shorten the deprecation for `export` without `--resolve`.
  src/python/pants/backend/python/goals/export.py
Labels: category:user api change

#19009 Docs tweaks for 2.16.x
  src/python/pants/backend/tools/preamble/subsystem.py
  src/python/pants/notes/2.16.x.md
Labels: needs-cherrypick, category:documentation

#18983 [2.14.x] Remove the Toolchain plugin
  .github/workflows/cache_comparison.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  pants.ci.toml
  pants.toml
Labels: category:internal

#19010 Move disabling the native-client into the native client itself
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  pants
  src/rust/engine/client/src/main.rs
Labels: category:internal

#18979 [2.16.x branch] Remove the Toolchain plugin
  .github/workflows/cache_comparison.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  pants.ci.toml
  pants.toml
Labels: category:internal

#18989 Port `Address` to Rust
  src/python/pants/backend/project_info/peek.py
  src/python/pants/base/specs.py
  src/python/pants/build_graph/address.py
  src/python/pants/build_graph/address_test.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/target.py
  src/python/pants/init/specs_calculator.py
  src/rust/engine/Cargo.toml
  src/rust/engine/src/externs/address.rs
Labels: category:internal

#19012 Docs tweaks for 2.16.x (Cherry-pick of #19009)
  src/python/pants/backend/tools/preamble/subsystem.py
  src/python/pants/notes/2.16.x.md
Labels: category:documentation

#18925 javascript: Add an explicit `npm_distribution` target instead of coupling to `node_package`
  src/python/pants/backend/javascript/install_node_package.py
  src/python/pants/backend/javascript/package/rules.py
  src/python/pants/backend/javascript/package/rules_test.py
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/backend/javascript/resolve.py
Labels: category:user api change

#19019 Clarify how to set $0 properly in `run_in_shell_command`
  src/python/pants/backend/shell/target_types.py
Labels: needs-cherrypick, category:documentation

#19021 Add an auto-cherry-pick GitHub Action
  .github/workflows/auto-cherry-picker.yaml
  build-support/bin/cherry_pick.sh
Labels: category:internal

#19026 Add missing space in `cherry_pick.sh`
  build-support/bin/cherry_pick.sh
Labels: category:internal

#19029 Fix cherry pick reviewer list
  build-support/bin/cherry_pick.sh
Labels: category:internal

#19028 Do not publish wheels for all SHAs, and publish to PyPI from Github Actions.
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  build-support/bin/_release_helper.py
  build-support/bin/generate_github_workflows.py
  docs/markdown/Contributions/releases/release-process.md
  docs/markdown/Getting Started/getting-started/installation.md
  docs/markdown/Getting Started/getting-started/manual-installation.md
Labels: category:user api change

#19030 Remove superfluous space from cherry pick script
  build-support/bin/cherry_pick.sh
Labels: category:internal

#19020 Use `{bin_name()} run` as `$0` in `run_shell_command`
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: needs-cherrypick, category:bugfix

#19033 Fixes for release job
  .github/workflows/release.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#18977 Add a new GitHub Action to greet newcomers
  .github/workflows/welcome-newcomers.yaml
Labels: category:internal

#19031 Clarify how to set $0 properly in `run_in_shell_command` (Cherry-pick of #19019)
  src/python/pants/backend/shell/target_types.py
Labels: category:documentation

#19024 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: category:internal

#19023 Support Python requirement target addrs in tool requirements. (Cherry-pick of #19014)
  docs/markdown/Python/python/python-lockfiles.md
  pants.toml
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/python_tool_base_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/init/plugin_resolver.py
Labels: category:user api change

#19037 Remove unecessary checkout from the welcome action
  .github/workflows/welcome-newcomers.yaml
Labels: category:internal

#19038 Prepare `2.17.0a0`.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19039 Fixup welcome-newcomers.yaml
  .github/workflows/welcome-newcomers.yaml
Labels: category:internal

#18987 Move mandatory process' level to DEBUG (Cherry-pick of #18982)
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: category:internal

#19042 Prepare `2.15.1`.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#19041 add bazel-remote to list of compatible remote caches
  docs/markdown/Using Pants/remote-caching-execution.md
Labels: needs-cherrypick, category:documentation

#19044 Prepare `2.16.0rc3`.
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#19048 Update cherry-picker to use `pull_request_target`
  .github/workflows/auto-cherry-picker.yaml
Labels: category:internal

#19055 Add `botocore-a-la-carte` reference to `s3` URL Handler
  src/python/pants/backend/url_handlers/s3/register.py
Labels: needs-cherrypick, category:documentation

#19061 Release doc and script fixes (Cherry-pick of #19043)
  build-support/pants_venv
  docs/NOTES.md
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#19059 Change CI trigger to includelist `main` and `2.*.x`
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#19058 Additional release job publishing fixes
  .github/workflows/release.yaml
  build-support/bin/_release_helper.py
  build-support/bin/generate_github_workflows.py
  src/python/pants/notes/2.17.x.md
Labels: needs-cherrypick, category:internal

#19064 Additional release job publishing fixes (Cherry-pick of #19058)
  .github/workflows/release.yaml
  build-support/bin/_release_helper.py
  build-support/bin/generate_github_workflows.py
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19063 Do not build wheels on push, since that is now accomplished by the release job.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#19022 Implement layout="zip" for Lambda/GCF, skipping lambdex
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/backend/python/util_rules/pex_venv.py
  src/python/pants/backend/python/util_rules/pex_venv_test.py
Labels: category:user api change

#19045 Use hand-written change detection for PR/push job trimming
  .github/workflows/test.yaml
  build-support/bin/classify_changed_files.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#19065 Remove unnecessary interpreter constraint config.
  pants.toml
Labels: category:internal

#19071 Revert "Implement layout="zip" for Lambda/GCF, skipping lambdex"
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/backend/python/util_rules/pex_venv.py
  src/python/pants/backend/python/util_rules/pex_venv_test.py
Labels: category:internal

#19073 Some 2.18.0.dev0 deprecations
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/python/framework/django/detect_apps.py
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/target.py
Labels: category:user api change

#19075 Require pants to run via scie-pants.
  src/python/pants/bin/pants_runner.py
Labels: category:user api change

#18829 Only build and release wheels for Python 3.9.
  .github/workflows/test.yaml
  build-support/bin/_release_helper.py
  build-support/bin/generate_github_workflows.py
Labels: category:user api change

#19080 Fix bad merge of #18829.
  .github/workflows/release.yaml
Labels: category:internal

#19079 Bring the tool `--export` option deprecation forward.
  src/python/pants/backend/python/subsystems/python_tool_base.py
Labels: needs-cherrypick, category:user api change

#19081 Bring the tool `--export` option deprecation forward. (Cherry-pick of #19079)
  src/python/pants/backend/python/subsystems/python_tool_base.py
Labels: category:user api change

#19077 Remove more 2.18.0.dev0 deprecations (follow up to #19073)
  src/python/pants/backend/python/goals/export.py
Labels: category:user api change

#19083 Bring the tool `--export` option deprecation forward. (Cherry-pick of #19079)
  src/python/pants/backend/python/subsystems/python_tool_base.py
Labels: category:user api change

#19084 Deprecate [mypy].extra_type_stubs and its lockfile.
  docs/markdown/Python/python-goals/python-check-goal.md
  docs/markdown/Python/python/python-third-party-dependencies.md
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: needs-cherrypick, category:user api change

#19087 Deprecate [mypy].extra_type_stubs and its lockfile. (Cherry-pick of #19084)
  docs/markdown/Python/python-goals/python-check-goal.md
  docs/markdown/Python/python/python-third-party-dependencies.md
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: category:user api change

#19088 Fix docs link to pants_from_sources script.
  docs/markdown/Contributions/development/running-pants-from-sources.md
Labels: needs-cherrypick, category:documentation

#18974 Run `terraform init` as part of `check` goal
  src/python/pants/backend/experimental/terraform/register.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/dependency_inference_test.py
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/goals/check_test.py
  src/python/pants/backend/terraform/tool.py
Labels: category:user api change, backend: Terraform

#19089 Fix docs link to pants_from_sources script. (Cherry-pick of #19088)
  docs/markdown/Contributions/development/running-pants-from-sources.md
Labels: category:documentation

#19090 Fix docs link to pants_from_sources script. (Cherry-pick of #19088)
  docs/markdown/Contributions/development/running-pants-from-sources.md
Labels: category:documentation

#18978 Remove the Toolchain plugin
  .github/workflows/cache_comparison.yaml
  .github/workflows/release.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  pants.ci.toml
  pants.toml
Labels: category:internal

#19092 Increase the logging of release version file publishing.
  build-support/bin/create_s3_index_file.sh
  build-support/bin/deploy_to_s3.py
Labels: needs-cherrypick, category:internal

#19086 Deprecate [mypy].extra_type_stubs and its lockfile. (Cherry-pick of #19084)
  docs/markdown/Python/python-goals/python-check-goal.md
  docs/markdown/Python/python/python-third-party-dependencies.md
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: category:user api change

#19050 Use a trait for remote ByteStore network implementation
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote/reapi.rs
  src/rust/engine/fs/store/src/remote_tests.rs
Labels: category:internal

#19099 Add more linux x86 test CI shards
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#19103 Don't try and garbage collect tempfiles
  src/rust/engine/fs/store/src/local.rs
Labels: needs-cherrypick, category:bugfix

#19096 Simplify interpreter-related CI config.
  .github/workflows/cache_comparison.yaml
  .github/workflows/release.yaml
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  3rdparty/python/flake8.lock
  3rdparty/python/mypy.lock
  3rdparty/python/pytest.lock
  build-support/README.md
  build-support/bin/classify_changed_files.py
  build-support/bin/generate_github_workflows.py
  build-support/bin/generate_json_schema_test.py
  build-support/bin/release.py
  build-support/bin/release.sh
  docs/markdown/Contributions/releases/release-process.md
  pants.toml
  src/python/pants/BUILD
  src/python/pants/backend/build_files/fix/deprecations/renamed_fields_rules.py
  src/python/pants/backend/helm/util_rules/chart_metadata.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/source/source_root.py
  src/python/pants/testutil/BUILD
  tests/python/pants_test/integration/pep561_integration_test.py
Labels: category:plugin api change

#19101 Add more linux x86 test CI shards (Cherry-pick of #19099)
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#19056 Workaround `botocore` bug in S3 URL Handler backend
  src/python/pants/backend/url_handlers/s3/integration_test.py
  src/python/pants/backend/url_handlers/s3/register.py
Labels: needs-cherrypick, category:bugfix

#19095 Run the cherry pick script with `-x` for debugging
  .github/workflows/auto-cherry-picker.yaml
Labels: category:internal

#19076 Implement layout="zip" for Lambda/GCF, deprecating lambdex
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/subsystems/lambdex.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/backend/python/util_rules/pex_venv.py
  src/python/pants/backend/python/util_rules/pex_venv_test.py
Labels: needs-cherrypick, category:user api change

#19112 Upgrade to `actions/checkout@v3`
  .github/workflows/auto-cherry-picker.yaml
Labels: category:internal

#19120 Implement layout="zip" for Lambda/GCF, deprecating lambdex (Cherry-pick of #19076)
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/subsystems/lambdex.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/backend/python/util_rules/pex_venv.py
  src/python/pants/backend/python/util_rules/pex_venv_test.py
Labels: category:user api change

#19116 Make determine_python() pin to 3.9
  build-support/common.sh
Labels: category:internal

#19114 add bazel-remote to list of compatible remote caches (Cherry-pick of #19041)
  docs/markdown/Using Pants/remote-caching-execution.md
Labels: category:documentation

#19115 add bazel-remote to list of compatible remote caches (Cherry-pick of #19041)
  docs/markdown/Using Pants/remote-caching-execution.md
Labels: category:documentation

#19111 Workaround `botocore` bug in S3 URL Handler backend (Cherry-pick of #19056)
  src/python/pants/backend/url_handlers/s3/integration_test.py
  src/python/pants/backend/url_handlers/s3/register.py
Labels: category:bugfix

#19100 Enable env vars in node_build_script
  src/python/pants/backend/javascript/package/rules.py
  src/python/pants/backend/javascript/package/rules_test.py
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/backend/javascript/run/rules.py
  src/python/pants/backend/javascript/run/rules_test.py
Labels: category:new feature

#19127 Use explicit depths on fetches when running cherry-picks in CI
  build-support/bin/cherry_pick.sh
Labels: category:internal

#19004 Terraform: Hashes for MacOS binaries have changed
  build-support/bin/terraform_tool_versions.py
  src/python/pants/backend/terraform/tool.py
Labels: needs-cherrypick, category:user api change, backend: Terraform

#19040 javascript: Allow nodejs-backed tools to point to a resolve and/or package manager
  src/python/pants/backend/javascript/goals/BUILD
  src/python/pants/backend/javascript/goals/lockfile.py
  src/python/pants/backend/javascript/goals/lockfile_test.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/javascript/lint/prettier/subsystem.py
  src/python/pants/backend/javascript/resolve.py
  src/python/pants/backend/javascript/subsystems/BUILD
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_test.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool_test.py
  src/python/pants/backend/javascript/subsystems/npx_tool.py
  src/python/pants/backend/javascript/subsystems/npx_tool_test.py
  src/python/pants/backend/javascript/subsystems/package-lock.json
  src/python/pants/backend/javascript/subsystems/pnpm-lock.yaml
  src/python/pants/backend/javascript/subsystems/yarn.lock
  src/python/pants/backend/openapi/lint/spectral/rules.py
  src/python/pants/backend/openapi/lint/spectral/subsystem.py
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
Labels: category:user api change

#19125 Fix auto-cherry-picker's merge-conflicts
  .github/workflows/auto-cherry-picker.yaml
Labels: category:internal

#19134 Drop our explicit dep on `syn`
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal

#19133 If a shebang already exists when adding a preamble, preserve it.
  src/python/pants/backend/tools/preamble/rules.py
  src/python/pants/backend/tools/preamble/rules_integration_test.py
Labels: needs-cherrypick, category:bugfix

#19136 Terraform: Hashes for MacOS binaries have changed (Cherry-pick of #19004)
  build-support/bin/terraform_tool_versions.py
  src/python/pants/backend/terraform/tool.py
Labels: category:user api change

#19138 If a shebang already exists when adding a preamble, preserve it. (Cherry-pick of #19133)
  src/python/pants/backend/tools/preamble/rules.py
  src/python/pants/backend/tools/preamble/rules_integration_test.py
Labels: category:bugfix

#19137 If a shebang already exists when adding a preamble, preserve it. (Cherry-pick of #19133)
  src/python/pants/backend/tools/preamble/rules.py
  src/python/pants/backend/tools/preamble/rules_integration_test.py
Labels: category:bugfix

#19135 Terraform: Hashes for MacOS binaries have changed (Cherry-pick of #19004)
  build-support/bin/terraform_tool_versions.py
  src/python/pants/backend/terraform/tool.py
Labels: category:user api change

#19027 Warn about `files()` in PEXes in one place
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: needs-cherrypick, category:internal

#19148 Warn about `files()` in PEXes in one place (Cherry-pick of #19027)
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: category:internal

#19146 Prepare `2.16.0rc4`.
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#19094 Increase the logging of release version file publishing. (Cherry-pick of #19092)
  build-support/bin/create_s3_index_file.sh
  build-support/bin/deploy_to_s3.py
Labels: category:internal

#19140 refactor(internal): adjust pants_venv venv_dir calculation
  build-support/pants_venv
Labels: category:internal
