Repository pantsbuild/pants, pull requests merged in 2023-06, with the labels that each got.

#19211 Deprecate the version/extra_requirements options on python tools. (Cherry-pick of #19204)
  src/python/pants/backend/python/subsystems/python_tool_base.py
Labels: category:user api change

#19208 Avoid requiring Python when trying to install Python (using Pyenv)
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: needs-cherrypick, category:internal

#19210 Deprecate the version/extra_requirements options on python tools. (Cherry-pick of #19204)
  src/python/pants/backend/python/subsystems/python_tool_base.py
Labels: category:user api change

#19215 Avoid requiring Python when trying to install Python (using Pyenv) (Cherry-pick of #19208)
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: category:internal

#19216 Rename `python_awslambda` to `python_aws_lambda_function`
  docs/markdown/Python/python-goals/python-test-goal.md
  docs/markdown/Shell/shell.md
  docs/markdown/Using Pants/assets.md
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/awslambda/python/target_types_test.py
  src/python/pants/backend/python/dependency_inference/subsystem.py
  src/python/pants/backend/python/subsystems/lambdex.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/target_types.py
  src/python/pants/engine/internals/specs_rules.py
Labels: category:user api change

#19217 Update FaaS docs for 2.18, including Lambda layers
  docs/markdown/Python/python-integrations/awslambda-python.md
  docs/markdown/Python/python-integrations/google-cloud-function-python.md
Labels: category:documentation

#19001 internal: Create dep inference request type
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/engine/fs.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/native_engine_test.py
  src/rust/engine/protos/protos/pants/cache.proto
  src/rust/engine/protos/src/hashing.rs
  src/rust/engine/protos/src/lib.rs
  src/rust/engine/src/externs/dep_inference.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/types.rs
Labels: category:internal

#19214 Avoid requiring Python when trying to install Python (using Pyenv) (Cherry-pick of #19208)
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: category:internal

#19209 Deprecate using `PythonBinary`
  src/python/pants/core/util_rules/system_binaries.py
Labels: needs-cherrypick, category:plugin api change

#19221 Prepare `2.16.0rc5`.
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#19223 Upgrade `pyo3` to `0.19`.
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/externs/engine_aware.rs
  src/rust/engine/src/externs/mod.rs
Labels: category:internal

#19226 Prepare `2.17.0rc0`.
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#19220 Upgrade Helm unittest
  src/python/pants/backend/helm/subsystems/unittest.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/test/unittest_test.py
  src/python/pants/core/util_rules/external_tool.py
Labels: category:internal, backend: Helm

#19224 Fix secondary ownership warning semantics (Cherry-pick of #19191)
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/specs_rules_test.py
Labels: category:internal

#19229 Remove the last mentions of NO_TOOL_LOCKFILE.
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/generate_lockfiles_test.py
Labels: category:internal

#19228 upgrade to Rust v1.70.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  rust-toolchain
Labels: category:internal

#19184 store stdout/stderr output from tests as bytes
  src/python/pants/backend/go/goals/test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
Labels: category:bugfix

#19243 Revert "javascript: Assign a default name to root nodejs resolves (#1…
  src/python/pants/backend/javascript/nodejs_project.py
  src/python/pants/backend/javascript/nodejs_project_test.py
Labels: category:bugfix, backend: JavaScript

#19233 Prep 1.28.0.dev1
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/notes/2.18.x.md
Labels: category:internal

#19234 Helm deployment chart field
  docs/markdown/Helm/helm-deployments.md
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/dependency_inference/deployment_test.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/util_rules/chart.py
Labels: category:new feature, backend: Helm

#19205 Support usage of `scala_artifact` addresses in `scalac_plugin` targets
  src/python/pants/backend/kotlin/compile/kotlinc_plugins.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/scala/compile/acyclic-scala212.test.lock
  src/python/pants/backend/scala/compile/scalac_plugins.py
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/target_types.py
Labels: backend: JVM, category:bugfix

#19246 `scandir` returns `Stat`s relative to its directory.
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/src/gitignore.rs
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/src/posixfs_tests.rs
Labels: category:performance

#19252 Delete dead code from old Python Tool Export
  src/python/pants/backend/python/goals/export.py
Labels: category:internal

#19254 Add cherry-pick PRs to their milestone for better visibility
  build-support/bin/cherry_pick.sh
Labels: category:internal

#19249 Handle `from foo import *` wildcard imports in Rust dep inference parser
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: needs-cherrypick, category:internal

#19251 Break a generic copy function out of deploy_to_s3.
  build-support/bin/copy_to_s3.py
  build-support/bin/deploy_to_s3.py
Labels: category:internal

#19255 Handle `from foo import *` wildcard imports in Rust dep inference parser (Cherry-pick of #19249)
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: category:internal

#19258 Add taplo to the release
  src/python/pants/bin/BUILD
Labels: category:bugfix

#19259 Add taplo to the release (Cherry-pick of #19258)
  src/python/pants/bin/BUILD
Labels: category:bugfix

#19266 Improve handling of additional files in Helm unit tests (Cherry-pick of #19263)
  docs/markdown/Helm/helm-overview.md
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/test/unittest_test.py
Labels: category:bugfix, backend: Helm, auto-cherry-picking-failed

#19267 Improve handling of additional files in Helm unit tests (Cherry-pick of #19263)
  docs/markdown/Helm/helm-overview.md
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/test/unittest_test.py
Labels: category:bugfix, backend: Helm, auto-cherry-picking-failed

#19268 Improve handling of additional files in Helm unit tests (Cherry-pick of #19263)
  docs/markdown/Helm/helm-overview.md
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/test/unittest_test.py
Labels: category:bugfix, backend: Helm, auto-cherry-picking-failed

#18842 Add experimental support for Rustfmt
  src/python/pants/backend/experimental/rust/BUILD
  src/python/pants/backend/experimental/rust/__init__.py
  src/python/pants/backend/experimental/rust/register.py
  src/python/pants/backend/python/framework/django/scripts/dependency_visitor.py
  src/python/pants/backend/rust/BUILD
  src/python/pants/backend/rust/__init__.py
  src/python/pants/backend/rust/goals/BUILD
  src/python/pants/backend/rust/goals/__init__.py
  src/python/pants/backend/rust/goals/tailor.py
  src/python/pants/backend/rust/lint/__init__.py
  src/python/pants/backend/rust/lint/rustfmt/BUILD
  src/python/pants/backend/rust/lint/rustfmt/__init__.py
  src/python/pants/backend/rust/lint/rustfmt/rules.py
  src/python/pants/backend/rust/lint/rustfmt/rules_integration_test.py
  src/python/pants/backend/rust/lint/rustfmt/skip_field.py
  src/python/pants/backend/rust/lint/rustfmt/subsystem.py
  src/python/pants/backend/rust/subsystems/BUILD
  src/python/pants/backend/rust/subsystems/__init__.py
  src/python/pants/backend/rust/subsystems/rust.py
  src/python/pants/backend/rust/target_types.py
  src/python/pants/backend/rust/util_rules/BUILD
  src/python/pants/backend/rust/util_rules/__init__.py
  src/python/pants/backend/rust/util_rules/toolchains.py
Labels: category:new feature, backend: Rust

#19222 Deprecate using `PythonBinary` (Cherry-pick of #19209)
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:plugin api change

#19262 Save CI test reports to S3.
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  build-support/bin/copy_to_s3.py
  build-support/bin/deploy_to_s3.py
  build-support/bin/generate_github_workflows.py
  pants.ci.toml
Labels: category:internal

#19274 Prepare the 2.16.0rc6 release.
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#19275 Prepare the 2.15.2rc0 release.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#19276 Prepare the 2.17.0rc1 release.
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#18998 Apply taplo to the repository
  .taplo.toml
  pants.toml
  pyproject.toml
  src/rust/engine/Cargo.toml
  src/rust/engine/address/Cargo.toml
  src/rust/engine/async_latch/Cargo.toml
  src/rust/engine/async_value/Cargo.toml
  src/rust/engine/cache/Cargo.toml
  src/rust/engine/client/Cargo.toml
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/brfs/Cargo.toml
  src/rust/engine/fs/fs_util/Cargo.toml
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/graph/Cargo.toml
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/hashing/Cargo.toml
  src/rust/engine/logging/Cargo.toml
  src/rust/engine/nailgun/Cargo.toml
  src/rust/engine/options/Cargo.toml
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/docker/Cargo.toml
  src/rust/engine/process_execution/pe_nailgun/Cargo.toml
  src/rust/engine/process_execution/remote/Cargo.toml
  src/rust/engine/process_executor/Cargo.toml
  src/rust/engine/protos/Cargo.toml
  src/rust/engine/rule_graph/Cargo.toml
  src/rust/engine/sharded_lmdb/Cargo.toml
  src/rust/engine/stdio/Cargo.toml
  src/rust/engine/task_executor/Cargo.toml
  src/rust/engine/testutil/Cargo.toml
  src/rust/engine/testutil/local_cas/Cargo.toml
  src/rust/engine/testutil/local_execution_server/Cargo.toml
  src/rust/engine/testutil/mock/Cargo.toml
  src/rust/engine/tryfuture/Cargo.toml
  src/rust/engine/ui/Cargo.toml
  src/rust/engine/watch/Cargo.toml
  src/rust/engine/workunit_store/Cargo.toml
  testprojects/src/python/mypyc_fib/pyproject.toml
  testprojects/src/python/native/pyproject.toml
Labels: category:internal

#19285 Fix S3 URL Handler for good
  src/python/pants/backend/url_handlers/s3/integration_test.py
  src/python/pants/backend/url_handlers/s3/register.py
Labels: needs-cherrypick, category:internal

#19288 Fix S3 URL Handler for good (Cherry-pick of #19285)
  src/python/pants/backend/url_handlers/s3/integration_test.py
  src/python/pants/backend/url_handlers/s3/register.py
Labels: category:internal

#19289 Fix S3 URL Handler for good (Cherry-pick of #19285)
  src/python/pants/backend/url_handlers/s3/integration_test.py
  src/python/pants/backend/url_handlers/s3/register.py
Labels: category:internal

#19287 Don't gpg-sign PyPI uploads in our release process.
  build-support/bin/release.py
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#19278 Add `act` to Pants (all in BUILD) and smoke test our workflows
  .github/workflows/BUILD
  .github/workflows/tests/BUILD
  build-support/bin/act/.actrc
  build-support/bin/act/BUILD
  pants.toml
Labels: category:internal

#19291 Fix release script
  build-support/bin/_release_helper.py
Labels: category:internal

#19290 Fix release helper for the 2.16.x branch.
  build-support/bin/_release_helper.py
Labels: category:internal

#19294 raise an error if isort can't read a config file
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/isort/rules_integration_test.py
Labels: category:bugfix, backend: Python

#19295 remove the custom check for "./pants" in code.
  build-support/flake8/.flake8
  build-support/flake8/bin_name_checker.py
Labels: category:internal

#19292 Prepare the 2.16.0rc7 release.
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#19297 Create a top-level pants_release package.
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  build-support/bin/BUILD
  build-support/bin/changelog.py
  build-support/bin/check_banned_imports.py
  build-support/bin/check_inits.py
  build-support/bin/classify_changed_files.py
  build-support/bin/copy_to_s3.py
  build-support/bin/generate_docs.py
  build-support/bin/generate_github_workflows.py
  docs/markdown/Contributions/releases/release-process.md
  src/python/pants_release/BUILD
  src/python/pants_release/common.py
  src/python/pants_release/release.py
  src/python/pants_release/reversion.py
  src/python/pants_release/reversion_test.py
Labels: category:internal

#19230 Modernize the Cherry-Picker script
  .github/workflows/BUILD
  .github/workflows/auto-cherry-picker.yaml
  .github/workflows/tests/BUILD
  .github/workflows/tests/auto_cherry_picker_smoke_test.py
  build-support/bin/cherry_pick.sh
  build-support/cherry_pick/BUILD
  build-support/cherry_pick/helper.js
  build-support/cherry_pick/helper.test.js
  build-support/cherry_pick/make_pr.sh
  build-support/cherry_pick/package-lock.json
  build-support/cherry_pick/package.json
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#19300 Move more release code to src/python/pants_release.
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  build-support/bin/classify_changed_files.py
  build-support/bin/classify_changed_files_test.py
  build-support/githooks/pre-commit
  docs/markdown/Contributions/releases/release-process.md
  src/python/pants_release/backfill_s3_release_tag_mappings.py
  src/python/pants_release/common.py
  src/python/pants_release/copy_to_s3.py
  src/python/pants_release/deploy_to_s3.py
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19272 Replace `include_special_cased_deps` flag with `should_traverse_deps_predicate`
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/dependents.py
  src/python/pants/backend/project_info/filedeps.py
  src/python/pants/backend/project_info/paths.py
  src/python/pants/backend/project_info/peek.py
  src/python/pants/backend/visibility/lint.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/target.py
Labels: category:plugin api change

#19303 Write directly to relevant notes file in changelog.py
  docs/markdown/Contributions/releases/release-process.md
  src/python/pants_release/changelog.py
  src/python/pants_release/changelog_test.py
  src/python/pants_release/common.py
  src/python/pants_release/git.py
  src/python/pants_release/release.py
Labels: category:internal

#19307 A few fixes for the auto-cherry-pick script
  .github/workflows/auto-cherry-picker.yaml
  .github/workflows/tests/auto_cherry_picker_smoke_test.py
Labels: category:internal

#19311 Get doc titles from the in-repo markdown files
  build-support/bin/generate_docs.py
  build-support/bin/generate_docs_test.py
Labels: category:documentation

#19312 Fix auto-cherry-pick issues discovered when run
  .github/workflows/auto-cherry-picker.yaml
  .github/workflows/tests/BUILD
  .github/workflows/tests/auto_cherry_picker_smoke_test.py
  build-support/cherry_pick/helper.js
  build-support/cherry_pick/helper.test.js
Labels: category:internal

#19316 Prepare the 2.16.0 release.
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#19317 Prepare the 2.15.2 release.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#19299 docs: layout tweak of caching info, remove toolchain :( and additional info about bazel-remote-cache
  docs/markdown/Using Pants/remote-caching-execution.md
Labels: needs-cherrypick, category:documentation

#19310 Fix helm documentation example (Cherry-pick of #19271)
  docs/markdown/Helm/helm-deployments.md
  src/python/pants/backend/helm/target_types.py
Labels: category:bugfix, backend: Helm, auto-cherry-picking-failed

#19324 Pin `test_package_pex_environment`'s image to a particular sha
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: category:internal

#19322 A couple of fixes to cherry-picking and `make_pr.sh`
  .github/workflows/auto-cherry-picker.yaml
  .github/workflows/tests/auto_cherry_picker_smoke_test.py
  build-support/cherry_pick/make_pr.sh
Labels: category:internal

#19337 Pin `test_package_pex_environment`'s image to a particular sha (Cherry-pick of #19324)
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: category:internal

#19335 Pin `test_package_pex_environment`'s image to a particular sha (Cherry-pick of #19324)
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: category:internal

#19336 Pin `test_package_pex_environment`'s image to a particular sha (Cherry-pick of #19324)
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: category:internal

#19339 Remove dependency on `importlib_resources`
  3rdparty/python/requirements.txt
  src/python/pants/util/resources.py
Labels: category:internal

#19333 Backport `make_pr.sh` to 2.16.x
  build-support/cherry_pick/make_pr.sh
Labels: category:internal

#19332 Backport `make_pr.sh` to 2.15.x
  build-support/cherry_pick/make_pr.sh
Labels: category:internal

#19314 Infer FaaS runtime from interpreter constraints, when unambiguous
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/awslambda/python/target_types_test.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types_test.py
  src/python/pants/backend/python/util_rules/BUILD
  src/python/pants/backend/python/util_rules/complete_platform_faas-test-3-45.json
  src/python/pants/backend/python/util_rules/complete_platform_faas-test-67-89.json
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/backend/python/util_rules/interpreter_constraints_test.py
Labels: category:new feature

#19329 docs: layout tweak of caching info, remove toolchain :( and additional info about bazel-remote-cache (Cherry-pick of #19299)
  docs/markdown/Using Pants/remote-caching-execution.md
Labels: category:documentation

#19330 docs: layout tweak of caching info, remove toolchain :( and additional info about bazel-remote-cache (Cherry-pick of #19299)
  docs/markdown/Using Pants/remote-caching-execution.md
Labels: category:documentation

#19331 docs: layout tweak of caching info, remove toolchain :( and additional info about bazel-remote-cache (Cherry-pick of #19299)
  docs/markdown/Using Pants/remote-caching-execution.md
Labels: category:documentation

#19302 Deprecate old value interpolation in Helm deployments
  docs/markdown/Helm/helm-deployments.md
  src/python/pants/backend/helm/goals/deploy_test.py
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/util_rules/renderer.py
Labels: category:new feature, backend: Helm

#19327 Add module mappings for `django-postgres-extra` and `UnleashClient`
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#19320 Get doc titles from the in-repo markdown files (Cherry-pick of #19311)
  build-support/bin/generate_docs.py
  build-support/bin/generate_docs_test.py
Labels: category:documentation

#19321 Get doc titles from the in-repo markdown files (Cherry-pick of #19311)
  build-support/bin/generate_docs.py
  build-support/bin/generate_docs_test.py
Labels: category:documentation

#19313 Fix helm documentation example (Cherry-pick of #19271)
  docs/markdown/Helm/helm-deployments.md
  src/python/pants/backend/helm/target_types.py
Labels: category:bugfix, backend: Helm, auto-cherry-picking-failed

#19306 Add `TraverseIfNotPackageTarget` deps traversal predicate for use in plugins
  src/python/pants/core/goals/package.py
  src/python/pants/core/goals/package_test.py
Labels: category:new feature

#18985 javascript: Rust based dep inference for javascript
  src/python/pants/backend/javascript/dependency_inference/import_parser/BUILD
  src/python/pants/backend/javascript/dependency_inference/import_parser/__init__.py
  src/python/pants/backend/javascript/dependency_inference/import_parser/package-lock.json
  src/python/pants/backend/javascript/dependency_inference/import_parser/package.json
  src/python/pants/backend/javascript/dependency_inference/import_parser/rules.py
  src/python/pants/backend/javascript/dependency_inference/import_parser/rules_test.py
  src/python/pants/backend/javascript/dependency_inference/import_parser/script.cjs
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/backend/javascript/package_json_test.py
  src/python/pants/engine/internals/native_dep_inference.py
  src/python/pants/engine/internals/scheduler.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/dep_inference/build.rs
  src/rust/engine/dep_inference/src/javascript/import_pattern.rs
  src/rust/engine/dep_inference/src/javascript/mod.rs
  src/rust/engine/dep_inference/src/javascript/tests.rs
  src/rust/engine/dep_inference/src/lib.rs
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/util.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/types.rs
Labels: category:new feature, backend: JavaScript

#19264 Support Helm unittest snapshots
  docs/markdown/Helm/helm-overview.md
  src/python/pants/backend/helm/dependency_inference/unittest.py
  src/python/pants/backend/helm/dependency_inference/unittest_test.py
  src/python/pants/backend/helm/goals/tailor.py
  src/python/pants/backend/helm/goals/tailor_test.py
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/test/unittest_test.py
  src/python/pants/core/goals/generate_snapshots.py
  src/python/pants/core/goals/generate_snapshots_test.py
  src/python/pants/core/register.py
Labels: category:new feature, backend: Helm

#19351 Prepare 2.18.0.dev2 release
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/notes/2.18.x.md
Labels: category:internal

#19355 add module mapping for launchdarkly-server-sdk
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#19354 Add build_network option to docker_image target
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/target_types.py
Labels: category:new feature

#19359 docs: fix markdown inconsistencies
  src/python/pants/backend/build_files/fix/deprecations/subsystem.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/scala/subsystem.py
  src/python/pants/backend/go/goals/generate.py
  src/python/pants/backend/go/subsystems/gotest.py
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/python/dependency_inference/subsystem.py
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/repos.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/setup_py_generation.py
  src/python/pants/backend/scala/subsystems/scala_infer.py
  src/python/pants/backend/tools/preamble/subsystem.py
  src/python/pants/core/goals/multi_tool_goal_helper.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/util_rules/asdf.py
  src/python/pants/core/util_rules/external_tool.py
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/jvm/subsystems.py
  src/python/pants/option/global_options.py
  src/python/pants/util/strutil.py
Labels: category:documentation

#19078 Add environment variable help options
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_printer.py
Labels: category:new feature

#19360 Run the deploy_to_s3.py script via Pants.
  .github/workflows/release.yaml
  src/python/pants_release/common.py
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#19366 Fix pytest-cov validation check.
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_test.py
  src/python/pants/backend/python/subsystems/pytest_runner_test.py
Labels: needs-cherrypick, category:bugfix

#19034 add support for alias-flags
  pants.toml
  src/python/pants/option/alias.py
  src/python/pants/option/alias_test.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/parser.py
Labels: category:new feature

#19369 docs: update plugin writing tutorials
  docs/markdown/Tutorials/advanced-plugin-concepts.md
  docs/markdown/Tutorials/create-a-new-goal.md
Labels: category:documentation

#19365 docs: add style guide instructions for writing Python docstrings
  docs/markdown/Contributions/development/style-guide.md
Labels: category:documentation

#19185 Terraform: Add `experimental-deploy` and wire-in dependency inference
  src/python/pants/backend/experimental/terraform/register.py
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/dependencies_test.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/goals/check_test.py
  src/python/pants/backend/terraform/goals/deploy.py
  src/python/pants/backend/terraform/goals/deploy_test.py
  src/python/pants/backend/terraform/target_types.py
  src/python/pants/backend/terraform/tool.py
  src/python/pants/backend/terraform/utils.py
Labels: category:new feature, backend: Terraform

#19323 turn `path/BUILD` into `path` in the `tailor` goal
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
Labels: category:new feature

#19374 docs: apply suggested edits to guide docs from readme.com
  docs/markdown/Contributions/development/style-guide.md
  docs/markdown/Python/python/python-distributions.md
  docs/markdown/Using Pants/concepts/targets.md
Labels: category:documentation

#19363 docs: fix markdown inconsistencies
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/python/framework/stevedore/target_types.py
  src/python/pants/backend/python/macros/common_fields.py
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/packaging/pyoxidizer/target_types.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/typecheck/mypy/mypyc.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/wrap_source.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/jvm/target_types.py
  src/python/pants/option/global_options.py
Labels: category:documentation

#19386 Remove `PythonExecutable`'s `immutable_input_digests`
  src/python/pants/backend/python/util_rules/pex_environment.py
Labels: category:internal

#19387 Add `DepsTraversalBehavior(Enum)` and some docstrings
  src/python/pants/core/goals/package.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/target.py
Labels: category:internal

#19139 docs: recommend scie-pants on upgrade tips page
  docs/markdown/Releases/upgrade-tips.md
Labels: category:documentation

#19399 Remove deprecated `PythonBinary` type.
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/core/util_rules/system_binaries_test.py
Labels: category:plugin api change

#19400 Remove support for referencing 2nd owner via file.
  src/python/pants/base/exiter_integration_test.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/internals/specs_rules_test.py
Labels: category:user api change

#19401 Prepare the 2.18.0.dev3 release.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.18.x.md
Labels: category:internal

#19402 Fix "Deploy commit mapping to S3" step.
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal
