Repository pantsbuild/pants, pull requests merged in 2023-04, with the labels that each got.

#18643 Prepare the 2.17.0.dev2 release.
  src/python/pants/VERSION
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/engine/goal.py
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#18644 Prepare the 2.15.1rc1 release.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#18646 Prepare the 2.14.2rc1 release.
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#18645 Prepare the 2.16.0rc0 release.
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#18561 Make UUID message clearer
  src/python/pants/goal/anonymous_telemetry.py
Labels: category:documentation

#18647 Add types-beautifulsoup4 to default module mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#18637 Remove a python-specific tip from the general prereqs page.
  docs/markdown/Getting Started/getting-started/prerequisites.md
  docs/markdown/Python/python/python-interpreter-compatibility.md
Labels: category:documentation

#18638 Improve lockfile consumption error message.
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: category:documentation

#18420 Error when goals used without relevant backends activated
  src/python/pants/help/help_printer.py
  src/python/pants/init/engine_initializer.py
  tests/python/pants_test/integration/goal_rule_integration_test.py
Labels: category:documentation

#18650 Remove a python-specific tip from the general prereqs page. (Cherry-pick of #18637)
  docs/markdown/Getting Started/getting-started/prerequisites.md
  docs/markdown/Python/python/python-interpreter-compatibility.md
Labels: category:documentation

#18651 Remove a python-specific tip from the general prereqs page. (Cherry-pick of #18637)
  docs/markdown/Getting Started/getting-started/prerequisites.md
  docs/markdown/Python/python/python-interpreter-compatibility.md
Labels: category:documentation

#18648 Add support for `Get(MyType)` syntax with no input args
  docs/markdown/Tutorials/advanced-plugin-concepts.md
  src/python/pants/backend/go/util_rules/go_bootstrap.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/internals/rule_visitor_test.py
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/internals/selectors_test.py
  src/rust/engine/src/externs/mod.rs
Labels: category:plugin api change

#18656 Document AWS CDK issue that multiple users have encountered.
  docs/markdown/Using Pants/troubleshooting.md
Labels: needs-cherrypick, category:documentation

#18649 Include global Git ignore file and `.git/info/exclude` in `pants_ignore` to ignore for file watching
  src/python/pants/option/global_options.py
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/src/gitignore.rs
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/fs/src/glob_matching_tests.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/src/posixfs_tests.rs
  src/rust/engine/src/context.rs
Labels: category:new feature

#18666 Document AWS CDK issue that multiple users have encountered. (Cherry-pick of #18656)
  docs/markdown/Using Pants/troubleshooting.md
Labels: category:documentation

#18523 javascript: Do not read none mapped package.json files in javascript rules
  src/python/pants/backend/javascript/nodejs_project_test.py
  src/python/pants/backend/javascript/package/rules_test.py
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/backend/javascript/package_json_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/specs_rules.py
Labels: category:bugfix

#18655 Deprecate some `Request` types in favor of `Get()` with only one arg
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  pants-plugins/internal_plugins/test_lockfile_fixtures/rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/go/util_rules/cgo.py
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/framework/django/dependency_inference.py
  src/python/pants/backend/python/framework/django/detect_apps.py
  src/python/pants/backend/python/framework/django/detect_apps_test.py
  src/python/pants/backend/python/mixed_interpreter_constraints/py_constraints.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/partition.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/target.py
  src/python/pants/init/specs_calculator.py
Labels: category:plugin api change

#18673 Fix JVM resource JAR creation on older Mac OSes
  src/python/pants/jvm/resources.py
Labels: needs-cherrypick, category:bugfix

#18675 Fix JVM resource JAR creation on older Mac OSes (Cherry-pick of #18673)
  src/python/pants/jvm/resources.py
Labels: category:bugfix

#18676 Fix JVM resource JAR creation on older Mac OSes (Cherry-pick of #18673)
  src/python/pants/jvm/resources.py
Labels: category:bugfix

#18672 Add PEP 621 pyproject.toml file docs
  docs/markdown/Python/python/python-third-party-dependencies.md
Labels: needs-cherrypick, category:documentation

#18677 Add PEP 621 pyproject.toml file docs (Cherry-pick of #18672)
  docs/markdown/Python/python/python-third-party-dependencies.md
Labels: category:documentation

#18670 Helm: Add support for DNS lookups in Chart templates
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/util_rules/renderer.py
  src/python/pants/backend/helm/util_rules/renderer_test.py
Labels: category:new feature, backend: Helm

#18678 Bump minimum supported version of Pex to v2.1.129.
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:bugfix

#18687 Bump minimum supported version of Pex to v2.1.129. (Cherry-pick of #18678)
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:bugfix

#18663 doc: Describe relevant error modes during rule compilation
  src/python/pants/engine/internals/scheduler_test.py
  src/rust/engine/src/nodes.rs
Labels: category:bugfix

#18692 Makes `adhoc_tool` actually respect the `extra_env_vars` field; adds tests
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/run_system_binary_integration_test.py
  src/python/pants/backend/shell/util_rules/shell_command_integration_test.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: needs-cherrypick, category:bugfix

#18690 No need to use lambda when setting help text for ruff
  src/python/pants/backend/python/lint/ruff/subsystem.py
Labels: category:internal

#18685 A Cloudflare Worker to handle requests to static.pantsbuild.org.
  build-support/cloudflare/BUILD
  build-support/cloudflare/redirect2githubpages.js
Labels: category:internal

#18695 Add timeout to remote store calls, and adjust name of cache timeout.
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/option/global_options.py
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: needs-cherrypick, category:bugfix

#18696 Remove implicit conversion from `std::io::Error` to `StoreError`
  src/rust/engine/fs/store/src/lib.rs
Labels: category:bugfix

#18679 Skip flaky pantsd integration tests. (Cherry-pick of #18665)
  tests/python/pants_test/pantsd/pantsd_integration_test.py
Labels: category:internal

#18699 Adds a fully-qualified path to a Python interpreter for `pex_binary` `RunRequest`s
  src/python/pants/backend/adhoc/adhoc_tool_integration_test.py
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/run_pex_binary.py
Labels: needs-cherrypick, category:bugfix

#18697 Add timeout to remote store calls, and adjust name of cache timeout. (Cherry-pick of #18695)
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/option/global_options.py
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/workunit_store/src/metrics.rs
Labels: category:bugfix

#18701 refactor `package_python_dist` rule so most of the logic can be reused
  src/python/pants/backend/python/goals/setup_py.py
Labels: needs-cherrypick, category:internal, backend: Python

#18703 refactor `package_python_dist` rule so most of the logic can be reused (Cherry-pick of #18701)
  src/python/pants/backend/python/goals/setup_py.py
Labels: category:internal, backend: Python

#18702 Move/Rename: `goals/setup_py.py` -> `{util_rules,goals}/package_dists.py` + `subsystems/setup_py_generation.py`
  docs/markdown/Writing Plugins/common-plugin-tasks/plugins-setup-py.md
  pants-plugins/internal_plugins/releases/register.py
  src/python/pants/backend/BUILD
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/goals/package_dists.py
  src/python/pants/backend/python/goals/package_dists_integration_test.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/register.py
  src/python/pants/backend/python/subsystems/setup_py_generation.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/typecheck/mypy/mypyc.py
  src/python/pants/backend/python/util_rules/BUILD
  src/python/pants/backend/python/util_rules/local_dists_test.py
  src/python/pants/backend/python/util_rules/package_dists.py
  src/python/pants/backend/python/util_rules/package_dists_test.py
  src/python/pants/core/goals/publish_test.py
Labels: category:plugin api change, backend: Python

#18627 Remove deprecated default ICs.
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/util_rules/interpreter_constraints_test.py
  src/python/pants/engine/BUILD
  src/python/pants/engine/streaming_workunit_handler_integration_test.py
  src/python/pants/testutil/pants_integration_test.py
  tests/python/pants_test/pantsd/pantsd_integration_test_base.py
Labels: category:user api change

#18710 Prep for 2.17.0.dev3
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/engine/goal.py
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#18639 python_distribution editable installs in exports
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/backend/python/register.py
  src/python/pants/backend/python/util_rules/BUILD
  src/python/pants/backend/python/util_rules/dists.py
  src/python/pants/backend/python/util_rules/local_dists_pep660.py
  src/python/pants/backend/python/util_rules/local_dists_pep660_test.py
  src/python/pants/backend/python/util_rules/scripts/BUILD
  src/python/pants/backend/python/util_rules/scripts/__init__.py
  src/python/pants/backend/python/util_rules/scripts/pep660_backend_wrapper.py
Labels: category:new feature, backend: Python

#18709 A RuleRunner subclass to set ICs in Python-related tests.
  src/python/pants/testutil/python_rule_runner.py
  src/python/pants/testutil/rule_runner.py
Labels: category:internal

#18682 javascript: Use binary shims in nodejs sandboxes
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/javascript/dependency_inference/import_parser/rules_test.py
  src/python/pants/backend/javascript/dependency_inference/rules_test.py
  src/python/pants/backend/javascript/goals/lockfile_test.py
  src/python/pants/backend/javascript/goals/test_integration_test.py
  src/python/pants/backend/javascript/package/rules_integration_test.py
  src/python/pants/backend/javascript/package/rules_test.py
  src/python/pants/backend/javascript/run/rules_test.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_test.py
  src/python/pants/backend/javascript/subsystems/npx_tool_test.py
  src/python/pants/backend/shell/subsystems/shell_setup.py
  src/python/pants/core/util_rules/search_paths.py
Labels: category:bugfix

#18712 Switch many tests to use PythonRuleRunner.
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/project_info/dependencies_test.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/python/pants/backend/python/goals/debug_goals_test.py
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/goals/repl_integration_test.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/lint/bandit/rules_integration_test.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/lint/flake8/subsystem_test.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/lint/pylint/subsystem_test.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/subsystem_test.py
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/util_rules/BUILD
  src/python/pants/backend/python/util_rules/local_dists_pep660_test.py
  src/python/pants/backend/python/util_rules/local_dists_test.py
  src/python/pants/backend/python/util_rules/package_dists_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/vcs_versioning_test.py
  src/python/pants/backend/shell/shunit2_test_runner_integration_test.py
Labels: category:internal

#18711 Add `tool_id` `classproperty` to `LintRequest`
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules.py
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/fix_test.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/multi_tool_goal_helper.py
  src/python/pants/core/goals/multi_tool_goal_helper_test.py
Labels: needs-cherrypick, category:internal

#18700 Adds a fully-qualified path to a Python interpreter for `pex_binary` `RunRequest`s (Cherry-pick of #18699)
  src/python/pants/backend/adhoc/adhoc_tool_integration_test.py
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/run_pex_binary.py
Labels: category:bugfix

#18716 Add ruff lint rules
  src/python/pants/backend/python/lint/ruff/rules.py
  src/python/pants/backend/python/lint/ruff/rules_integration_test.py
Labels: needs-cherrypick, category:bugfix

#18719 Fix `repr` for `Field`s that don't define `default`.
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: needs-cherrypick, category:bugfix

#18723 Fix `repr` for `Field`s that don't define `default`. (Cherry-pick of #18719)
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:bugfix

#18720 [internal] update Toolchain pants plugin to v0.27.0
  pants.toml
Labels: needs-cherrypick, category:internal

#18728 Release script tweaks
  build-support/bin/changelog.py
  build-support/bin/contributors.py
Labels: category:internal

#18727 Update Toolchain pants plugin to v0.27.0
  pants.toml
Labels: category:internal

#18718 Edit Python publishing docs for clarity.
  docs/markdown/Python/python-goals/python-publish-goal.md
  docs/markdown/Python/python/python-distributions.md
Labels: category:documentation

#18725 Use address as stable key when batching field sets in `lint`/`test`
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
Labels: needs-cherrypick, category:bugfix

#18724 Fix `repr` for `Field`s that don't define `default`. (Cherry-pick of #18719)
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:bugfix

#18715 Prefactor: Move `get_hash` from docker backend to `strutil`
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
  src/python/pants/backend/docker/utils.py
  src/python/pants/backend/docker/utils_test.py
  src/python/pants/notes/2.16.x.md
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: needs-cherrypick, category:internal

#18735 Add missing backtick to docstring
  src/python/pants/base/specs.py
Labels: category:internal

#18739 Add ruff lint rules (Cherry-pick of #18716)
  src/python/pants/backend/python/lint/ruff/rules.py
  src/python/pants/backend/python/lint/ruff/rules_integration_test.py
Labels: category:bugfix

#18733 Use address as stable key when batching field sets in `lint`/`test` (Cherry-pick of #18725)
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
Labels: category:bugfix

#18732 [internal][2.14.x branch] update Toolchain pants plugin to v0.27.0
  pants.toml
Labels: category:internal

#18740 Avoid using private type `hashlib._Hash`, which may not exist
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: needs-cherrypick, category:internal

#18734 Use address as stable key when batching field sets in `lint`/`test` (Cherry-pick of #18725)
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
Labels: category:bugfix

#18738 Prefactor: Move `get_hash` from docker backend to `strutil` (Cherry-pick of #18715)
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
  src/python/pants/backend/docker/utils.py
  src/python/pants/backend/docker/utils_test.py
  src/python/pants/notes/2.16.x.md
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: category:internal

#18708 Add a fingerprinted environment variables option to pyenv provider backend
  src/python/pants/backend/python/providers/pyenv/custom_install/rules_integration_test.py
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: needs-cherrypick, category:internal

#18741 Avoid using private type `hashlib._Hash`, which may not exist (Cherry-pick of #18740)
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: category:internal

#18746 Add a fingerprinted environment variables option to pyenv provider backend (Cherry-pick of #18708)
  src/python/pants/backend/python/providers/pyenv/custom_install/rules_integration_test.py
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: category:internal

#18747 Clear FSDB materialization cache when `remove`ing a file
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/fs/store/src/local_tests.rs
Labels: category:bugfix

#18750 docs: Fix typo on requirements-overrides code snippet
  src/python/pants/backend/python/macros/common_fields.py
Labels: category:documentation

#18753 Upgrade Pex to 2.1.132.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  pants.toml
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18754 Switch to new lockfile generation script.
  3rdparty/python/flake8.lock
  3rdparty/python/mypy.lock
  3rdparty/python/pytest.lock
  3rdparty/python/user_reqs.lock
  build-support/bin/_generate_all_lockfiles_helper.py
  build-support/bin/generate_all_lockfiles.sh
  build-support/bin/generate_builtin_lockfiles.py
  build-support/bin/generate_pex_lockfiles.sh
  pants.toml
  src/python/pants/backend/cc/lint/clangformat/clangformat.lock
  src/python/pants/backend/codegen/avro/java/avro-tools.default.lockfile.txt
  src/python/pants/backend/codegen/protobuf/java/grpc-java.default.lockfile.txt
  src/python/pants/backend/codegen/protobuf/python/mypy_protobuf.lock
  src/python/pants/backend/codegen/protobuf/scala/scalapbc.default.lockfile.txt
  src/python/pants/backend/codegen/thrift/scrooge/scrooge.default.lockfile.txt
  src/python/pants/backend/docker/subsystems/dockerfile.lock
  src/python/pants/backend/helm/subsystems/k8s_parser.lock
  src/python/pants/backend/helm/subsystems/post_renderer.lock
  src/python/pants/backend/java/lint/google_java_format/google_java_format.default.lockfile.txt
  src/python/pants/backend/kotlin/lint/ktlint/ktlint.lock
  src/python/pants/backend/python/lint/add_trailing_comma/add_trailing_comma.lock
  src/python/pants/backend/python/lint/autoflake/autoflake.lock
  src/python/pants/backend/python/lint/bandit/bandit.lock
  src/python/pants/backend/python/lint/black/black.lock
  src/python/pants/backend/python/lint/docformatter/docformatter.lock
  src/python/pants/backend/python/lint/flake8/flake8.lock
  src/python/pants/backend/python/lint/isort/isort.lock
  src/python/pants/backend/python/lint/pydocstyle/pydocstyle.lock
  src/python/pants/backend/python/lint/pylint/pylint.lock
  src/python/pants/backend/python/lint/pyupgrade/pyupgrade.lock
  src/python/pants/backend/python/lint/ruff/ruff.lock
  src/python/pants/backend/python/lint/yapf/yapf.lock
  src/python/pants/backend/python/packaging/pyoxidizer/pyoxidizer.lock
  src/python/pants/backend/python/subsystems/coverage_py.lock
  src/python/pants/backend/python/subsystems/debugpy.lock
  src/python/pants/backend/python/subsystems/ipython.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/pytest.lock
  src/python/pants/backend/python/subsystems/setuptools.lock
  src/python/pants/backend/python/subsystems/setuptools_scm.lock
  src/python/pants/backend/python/subsystems/twine.lock
  src/python/pants/backend/python/typecheck/mypy/mypy.lock
  src/python/pants/backend/python/typecheck/mypy/older_mypy_for_testing.lock
  src/python/pants/backend/python/util_rules/lockfile_diff_test.py
  src/python/pants/backend/scala/lint/scalafmt/scalafmt.default.lockfile.txt
  src/python/pants/backend/scala/subsystems/scalatest.default.lockfile.txt
  src/python/pants/backend/terraform/hcl2.lock
  src/python/pants/backend/tools/yamllint/yamllint.lock
  src/python/pants/jvm/shading/jarjar.default.lockfile.txt
  src/python/pants/jvm/test/junit.default.lockfile.txt
Labels: category:internal

#18760 Allow BinaryPaths to close over their type.
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/init/plugin_resolver.py
Labels: category:plugin api change

#18748 javascript: Manage npm version with corepack
  src/python/pants/backend/javascript/dependency_inference/import_parser/package.json
  src/python/pants/backend/javascript/nodejs_project_environment.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_test.py
Labels: category:new feature, backend: JavaScript

#18763 Use Self backport in BinaryPath factory method.
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:user api change

#18765 Remove superfluous custom helm tool resolves.
  pants.toml
  src/python/pants/backend/helm/subsystems/BUILD
Labels: category:internal

#18768 Flush metadata to disk before renaming immutable store files
  src/rust/engine/fs/store/src/local.rs
Labels: category:bugfix

#18769 Upgrade Pex to 2.1.133.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18694 Makes `adhoc_tool` actually respect the `extra_env_vars` field; adds tests (Cherry-pick of #18692)
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/run_system_binary_integration_test.py
  src/python/pants/backend/shell/util_rules/shell_command_integration_test.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:bugfix

#18770 Dedup graph errors.
  src/rust/engine/rule_graph/src/builder.rs
Labels: category:bugfix

#18774 Get rid of spectral rust crate.
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/docker/Cargo.toml
  src/rust/engine/process_execution/docker/src/docker_tests.rs
  src/rust/engine/process_execution/pe_nailgun/Cargo.toml
  src/rust/engine/process_execution/remote/Cargo.toml
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/local_tests.rs
Labels: category:internal

#18777 Use a released version of bollard
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/docker/Cargo.toml
Labels: category:internal

#18778 Upgrade mheap/github-action-required-labels to v4.0.0
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#18781 Update linter documentation to refer to install_from_resolve
  docs/markdown/Python/python/python-linters-and-formatters.md
  docs/markdown/Python/python/python-lockfiles.md
Labels: category:documentation

#18780 Option required flag
  src/python/pants/backend/project_info/paths.py
  src/python/pants/backend/project_info/paths_test.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/option/errors.py
  src/python/pants/option/option_types.py
  src/python/pants/option/option_types_test.py
  src/python/pants/option/option_value_container.py
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
  src/python/pants/option/ranked_value.py
Labels: category:new feature

#18782 Update linter documentation to refer to install_from_resolve (Cherry-pick of #18781)
  docs/markdown/Python/python/python-linters-and-formatters.md
  docs/markdown/Python/python/python-lockfiles.md
Labels: category:documentation

#18776 Use the resolve's ICs for tools.
  src/python/pants/backend/docker/goals/run_image_integration_test.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules_integration_test.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:user api change

#18785 Upgrade Pex to 2.1.134.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#18789 Upgrade Pex to 2.1.134. (Cherry-pick of #18785)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18786 Add info on how to configure Docker Desktop for using docker_environment
  src/python/pants/core/util_rules/environments.py
Labels: category:documentation

#18790 Support docformatter 1.6.0+
  src/python/pants/backend/python/lint/docformatter/rules.py
Labels: category:internal

#18787 The `OverridesField.compute_value()` must return a hashable value.
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/defaults_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: needs-cherrypick, category:bugfix

#18797 Remove defunct newsletter (Cherry-pick of #18355)
  docs/markdown/Getting Help/getting-help.md
Labels: category:documentation

#18794 Add Pylint post (Cherry-pick of #18079)
  docs/markdown/Introduction/media.md
Labels: category:documentation

#18366 Improve error location for invalid targets/target fields.
  src/python/pants/backend/go/target_type_rules_test.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/providers/pyenv/custom_install/rules.py
  src/python/pants/backend/visibility/glob_test.py
  src/python/pants/backend/visibility/rule_types_test.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/synthetic_targets.py
  src/python/pants/engine/internals/synthetic_targets_test.py
  src/python/pants/engine/internals/target_adaptor.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:documentation

#18796 Remove defunct newsletter (Cherry-pick of #18355)
  docs/markdown/Getting Help/getting-help.md
Labels: category:documentation

#18795 Jacob Floyd/Huon Wilson updates to team page (Cherry-pick of #18221)
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#18798 The `OverridesField.compute_value()` must return a hashable value. (Cherry-pick of #18787)
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/defaults_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/util/frozendict.py
  src/python/pants/util/frozendict_test.py
Labels: category:bugfix

#18799 The `OverridesField.compute_value()` must return a hashable value. (Cherry-pick of #18787)
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/defaults_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:bugfix

#18783 upgrade Rust to v1.69.0
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
  src/rust/engine/graph/src/lib.rs
Labels: category:internal

#18793 Default to using the entire tool lockfile.
  docs/markdown/Python/python/python-linters-and-formatters.md
  docs/markdown/Python/python/python-lockfiles.md
  pants.toml
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/python_tool_base_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:user api change

#18802 Revert "Option required flag"
  src/python/pants/backend/project_info/paths.py
  src/python/pants/backend/project_info/paths_test.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/option/errors.py
  src/python/pants/option/option_types.py
  src/python/pants/option/option_types_test.py
  src/python/pants/option/option_value_container.py
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
  src/python/pants/option/ranked_value.py
Labels: category:internal

#18800 Prepare the 2.14.2rc2 release.
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#18803 Prepare the 2.16.0rc1 release.
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#18801 Prepare the 2.15.1rc2 release.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#18804 Prepare the 2.17.0.dev4 release.
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.17.x.md
Labels: category:internal

#18807 Default to using the entire tool lockfile. (Cherry-pick of #18793)
  docs/markdown/Python/python/python-linters-and-formatters.md
  docs/markdown/Python/python/python-lockfiles.md
  pants.toml
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/python_tool_base_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:user api change

#18817 Don't specify interpreter_constraints when building the release pex. (Cherry-pick of #18280)
  build-support/bin/_release_helper.py
Labels: category:internal

#18818 Don't specify interpreter_constraints when building the release pex. (Cherry-pick of #18280)
  build-support/bin/_release_helper.py
Labels: category:internal

#18820 Fix release script's expected maintainers (Cherry-pick of #18477)
  build-support/bin/_release_helper.py
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#18805 Remove redundant PythonToolBase/JvmToolBase features.
  src/python/pants/backend/cc/lint/clangformat/subsystem.py
  src/python/pants/backend/codegen/avro/java/subsystem.py
  src/python/pants/backend/codegen/protobuf/java/subsystem.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/scala/subsystem.py
  src/python/pants/backend/codegen/soap/java/jaxws.py
  src/python/pants/backend/codegen/thrift/scrooge/subsystem.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/post_renderer.py
  src/python/pants/backend/java/lint/google_java_format/subsystem.py
  src/python/pants/backend/java/subsystems/junit.py
  src/python/pants/backend/kotlin/lint/ktlint/subsystem.py
  src/python/pants/backend/openapi/subsystems/openapi_generator.py
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/lint/add_trailing_comma/subsystem.py
  src/python/pants/backend/python/lint/autoflake/subsystem.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/docformatter/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/isort/subsystem.py
  src/python/pants/backend/python/lint/pydocstyle/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pyupgrade/subsystem.py
  src/python/pants/backend/python/lint/ruff/subsystem.py
  src/python/pants/backend/python/lint/yapf/subsystem.py
  src/python/pants/backend/python/packaging/pyoxidizer/subsystem.py
  src/python/pants/backend/python/subsystems/debugpy.py
  src/python/pants/backend/python/subsystems/ipython.py
  src/python/pants/backend/python/subsystems/lambdex.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/python_tool_base_test.py
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/backend/python/subsystems/setuptools_scm.py
  src/python/pants/backend/python/subsystems/twine.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/lockfile_test.py
  src/python/pants/backend/scala/lint/scalafmt/subsystem.py
  src/python/pants/backend/scala/subsystems/scalatest.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/tools/yamllint/subsystem.py
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/jvm/resolve/jvm_tool_test.py
  src/python/pants/jvm/shading/jarjar.py
Labels: category:plugin api change

#18819 Fix release script's expected maintainers (Cherry-pick of #18477)
  build-support/bin/_release_helper.py
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#18828 docs: reorder contributor steps, rustup is required for git hooks install to work smoothly
  docs/markdown/Contributions/development/contributor-setup.md
Labels: category:documentation

#18826 Include `pants.backend.url_handlers.s3` in pants distribution.
  src/python/pants/bin/BUILD
Labels: needs-cherrypick, category:bugfix

#18813 Use build root as workdir for shell_command(workdir="")
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: needs-cherrypick, category:bugfix

#18825 Include `symbols` as topic in usage help.
  src/python/pants/help/help_printer.py
Labels: needs-cherrypick, category:documentation

#18815 Reduce get_snapshot copypasta
  src/python/pants/backend/build_files/fmt/black/integration_test.py
  src/python/pants/backend/cc/lint/clangformat/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules_integration_test.py
  src/python/pants/backend/go/lint/gofmt/rules_integration_test.py
  src/python/pants/backend/java/lint/google_java_format/rules_integration_test.py
  src/python/pants/backend/javascript/lint/prettier/rules_integration_test.py
  src/python/pants/backend/kotlin/lint/ktlint/rules_integration_test.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules_integration_test.py
  src/python/pants/backend/python/lint/autoflake/rules_integration_test.py
  src/python/pants/backend/python/lint/black/rules_integration_test.py
  src/python/pants/backend/python/lint/docformatter/rules_integration_test.py
  src/python/pants/backend/python/lint/isort/rules_integration_test.py
  src/python/pants/backend/python/lint/pyupgrade/rules_integration_test.py
  src/python/pants/backend/python/lint/ruff/rules_integration_test.py
  src/python/pants/backend/python/lint/yapf/rules_integration_test.py
  src/python/pants/backend/scala/lint/scalafmt/rules_integration_test.py
  src/python/pants/backend/shell/lint/shfmt/rules_integration_test.py
  src/python/pants/testutil/rule_runner.py
Labels: category:internal

#18788 New API type: `CurrentExecutingGoals`.
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/goal_test.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/testutil/rule_runner.py
Labels: category:new feature

#18823 Support using `scie-pants` in the pre-commit hook.
  build-support/githooks/pre-commit
Labels: category:internal

#18713 Patch `StreamingWorkunitContext.get_expanded_specs()`.
  src/python/pants/engine/streaming_workunit_handler.py
Labels: needs-cherrypick, category:bugfix

#18831 Triage some noqa: PNT30 await-in-loops
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/source/source_root.py
Labels: category:performance

#18806 Use the resolve's ICs for tools. (Cherry-pick of #18776)
  src/python/pants/backend/docker/goals/run_image_integration_test.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules_integration_test.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:user api change

#18814 Write adhoc_tool(stdout/stderr="...") relative to workdir, support absolute paths
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: needs-cherrypick, category:bugfix

#18838 Increase the optimization level for dev/debug builds, and reduce debug info in release builds
  src/rust/engine/Cargo.toml
Labels: category:internal

#18822 helm: add missing no-infer-dep pragmas.
  src/python/pants/backend/helm/subsystems/k8s_parser_main.py
  src/python/pants/backend/helm/subsystems/post_renderer_main.py
Labels: category:internal

#18844 Upgrade cargo audit to 0.17.5, allow manual triggering of cargo audit workflow
  .github/workflows/audit.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#18839 Write adhoc_tool(stdout/stderr="...") relative to workdir, support absolute paths (Cherry-pick of #18814)
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: category:bugfix

#18840 Handle workdir="."/default properly in run_shell_command
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: needs-cherrypick, category:bugfix

#18847 Increase timeout for cgo_test.py
  src/python/pants/backend/go/util_rules/BUILD
Labels: category:internal

#18850 Handle workdir="."/default properly in run_shell_command (Cherry-pick of #18840)
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: category:bugfix

#18858 Update mypy and pytest documentation to refer to install_from_resolve (Cherry pick of #18791)
  docs/markdown/Python/python-goals/python-check-goal.md
  docs/markdown/Python/python-goals/python-test-goal.md
Labels: category:documentation

#18857 Increase timeouts of several tests
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/base/BUILD
  src/python/pants/init/BUILD
Labels: category:internal

#18859 Increase test timeouts (Cherry pick of #18627, #18712, #18847, #18857)
  src/python/pants/backend/go/util_rules/BUILD
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/util_rules/BUILD
  src/python/pants/base/BUILD
  src/python/pants/engine/BUILD
  src/python/pants/init/BUILD
Labels: category:internal

#18862 Fix library name typo in third party example
  docs/markdown/Python/python/python-third-party-dependencies.md
Labels: category:documentation

#18863 Remove reference to readme.com as the way to edit documentation
  docs/markdown/Contributions/contributor-overview.md
Labels: category:documentation

#18835 Add concrete `Context` type to the `graph` crate
  src/rust/engine/Cargo.lock
  src/rust/engine/graph/Cargo.toml
  src/rust/engine/graph/src/context.rs
  src/rust/engine/graph/src/entry.rs
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/graph/src/node.rs
  src/rust/engine/graph/src/tests.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/lib.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/scheduler.rs
  src/rust/engine/src/session.rs
  src/rust/engine/workunit_store/src/lib.rs
Labels: category:internal

#18870 Include `pants.backend.url_handlers.s3` in pants distribution. (Cherry-pick of #18826)
  src/python/pants/bin/BUILD
Labels: category:bugfix
