Repository pantsbuild/pants, pull requests merged in 2023-02, with the labels that each got.

#18139 Document the new get-pants.sh name. (Cherry-pick of #18137)
  docs/markdown/Getting Started/getting-started/installation.md
Labels: category:documentation

#18142 Default to the new "Dependents" header in the py_constraints report.
  src/python/pants/backend/python/mixed_interpreter_constraints/py_constraints.py
  src/python/pants/backend/python/mixed_interpreter_constraints/py_constraints_test.py
Labels: category:user api change

#18140 go: fix backend to work when run in non-local environments
  src/python/pants/backend/codegen/protobuf/go/rules_integration_test.py
  src/python/pants/backend/experimental/go/register.py
  src/python/pants/backend/go/dependency_inference_test.py
  src/python/pants/backend/go/goals/check_test.py
  src/python/pants/backend/go/goals/generate_test.py
  src/python/pants/backend/go/goals/package_binary_integration_test.py
  src/python/pants/backend/go/goals/tailor_test.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/lint/golangci_lint/rules_integration_test.py
  src/python/pants/backend/go/lint/vet/rules_integration_test.py
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/target_type_rules_test.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/assembly_integration_test.py
  src/python/pants/backend/go/util_rules/build_opts_test.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/build_pkg_target_test.py
  src/python/pants/backend/go/util_rules/cgo_test.py
  src/python/pants/backend/go/util_rules/coverage_test.py
  src/python/pants/backend/go/util_rules/embed_integration_test.py
  src/python/pants/backend/go/util_rules/first_party_pkg_test.py
  src/python/pants/backend/go/util_rules/implicit_linker_deps.py
  src/python/pants/backend/go/util_rules/import_analysis.py
Labels: backend: Go, category:bugfix

#18147 Splits up `shell_command.py`
  src/python/pants/backend/shell/util_rules/adhoc_process_support.py
  src/python/pants/backend/shell/util_rules/run_in_sandbox.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:internal

#18148 go: don't check for `Target` attribute on stdlib packages
  src/python/pants/backend/go/util_rules/import_analysis.py
Labels: backend: Go, category:bugfix

#18144 Add the `environment` field to most Python binary target types
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/python/packaging/pyoxidizer/target_types.py
Labels: needs-cherrypick, category:bugfix

#18094 [python-infer]: allow ignoring unowned imports
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/python/pants/backend/python/dependency_inference/subsystem.py
Labels: category:new feature

#18146 docs: add "What's New" section to 2.16 release notes
  src/python/pants/notes/2.16.x.md
Labels: category:documentation

#18150 Add the `environment` field to most Python binary target types (Cherry-pick of #18144)
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/python/packaging/pyoxidizer/target_types.py
Labels: category:bugfix

#18156 Prepare the 2.15.0rc3 release
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#18160 Ensure we set the region when deploying to S3. (Cherry-pick of #18088)
  build-support/bin/deploy_to_s3.py
Labels: category:internal

#18158 Support using `scie-pants` for Pants dev work.
  pants.toml
Labels: category:internal

#18132 Add backend for projects that use openstack/stevedore
  build-support/bin/generate_docs.py
  pants.toml
  src/python/pants/backend/experimental/python/framework/__init__.py
  src/python/pants/backend/experimental/python/framework/stevedore/BUILD
  src/python/pants/backend/experimental/python/framework/stevedore/__init__.py
  src/python/pants/backend/experimental/python/framework/stevedore/register.py
  src/python/pants/backend/python/framework/__init__.py
  src/python/pants/backend/python/framework/stevedore/BUILD
  src/python/pants/backend/python/framework/stevedore/__init__.py
  src/python/pants/backend/python/framework/stevedore/python_target_dependencies.py
  src/python/pants/backend/python/framework/stevedore/python_target_dependencies_test.py
  src/python/pants/backend/python/framework/stevedore/rules.py
  src/python/pants/backend/python/framework/stevedore/rules_test.py
  src/python/pants/backend/python/framework/stevedore/target_types.py
  src/python/pants/bin/BUILD
Labels: category:new feature

#18157 `shell_command`/`run_in_sandbox` workdir/output dir adjustments
  src/python/pants/backend/shell/register.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/adhoc_process_support.py
  src/python/pants/backend/shell/util_rules/run_in_sandbox.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/wrap_source_intergration_test.py
Labels: category:user api change

#18171 go: allow coverage for standard library packages
  src/python/pants/backend/go/util_rules/build_pkg_target.py
Labels: backend: Go, category:internal

#18170 [internal] note dependency to `scie-pants` on "testing" env vars.
  src/python/pants/base/build_root.py
  src/python/pants/version.py
Labels: category:internal

#18176 go: update build tags check from latest go sources
  src/python/pants/backend/go/go_sources/analyze_package/build_context.go
Labels: backend: Go, category:internal

#18165 Adds fields to capture stdout/stderr to `experimental_run_in_sandbox`
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/adhoc_process_support.py
  src/python/pants/backend/shell/util_rules/run_in_sandbox.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:user api change

#18184 Adjusts `BinaryShims` to use native digest operations and `immutable_input_digests`
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-upgrade-guide.md
  src/python/pants/backend/codegen/protobuf/lint/buf/format_rules.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/core/util_rules/system_binaries_test.py
Labels: category:internal

#18060 Make mypy cache per-repo (Cherry-pick of #18043)
  src/python/pants/backend/python/typecheck/mypy/rules.py
Labels: category:bugfix

#18166 Shutdown all threads as part of Scheduler shutdown
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/bin/remote_pants_runner.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/rules_test.py
  src/python/pants/init/BUILD
  src/python/pants/init/options_initializer.py
  src/python/pants/option/global_options_test.py
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/benches/store.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/scheduler.rs
  src/rust/engine/task_executor/Cargo.toml
  src/rust/engine/task_executor/src/lib.rs
  tests/python/pants_test/init/test_options_initializer.py
  tests/python/pants_test/init/test_plugin_resolver.py
Labels: needs-cherrypick, category:bugfix

#18154 Visibility backend: adjust rule set selector syntax making path values default rather than target types.
  docs/markdown/Using Pants/validating-dependencies.md
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:user api change

#18168 Remove the `boot_script` from `experimental_shell_command`/`experimental_run_in_sandbox`
  src/python/pants/backend/shell/util_rules/adhoc_process_support.py
  src/python/pants/backend/shell/util_rules/builtin.py
  src/python/pants/backend/shell/util_rules/run_in_sandbox.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:internal

#18188 Shutdown all threads as part of Scheduler shutdown (Cherry-pick of #18166)
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/bin/remote_pants_runner.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/rules_test.py
  src/python/pants/init/BUILD
  src/python/pants/init/options_initializer.py
  src/python/pants/option/global_options_test.py
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/benches/store.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/scheduler.rs
  src/rust/engine/task_executor/Cargo.toml
  src/rust/engine/task_executor/src/lib.rs
  tests/python/pants_test/init/test_options_initializer.py
  tests/python/pants_test/init/test_plugin_resolver.py
Labels: category:bugfix

#18192 Adjust the default for `root_output_directory`
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:user api change, backend: Shell

#18196 Prepare 2.15.0rc4.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#18200 Have lambdex create a new output file.
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/lambdex.py
Labels: category:bugfix

#18201 Have lambdex create a new output file. (Cherry-pick of #18200)
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/lambdex.py
Labels: category:bugfix

#18203 Use `EnvironmentAwarePackageRequest` in many more contexts.
  BUILD
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/docker/goals/package_image_integration_test.py
  src/python/pants/backend/docker/lint/hadolint/rules_integration_test.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/helm/goals/deploy_test.py
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/shell/goals/test_test.py
  src/python/pants/backend/shell/util_rules/adhoc_process_support.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/target_types.py
Labels: needs-cherrypick, category:bugfix

#18205 go: disable coverage redesign experiment on Go v1.20+
  src/python/pants/backend/go/util_rules/sdk.py
Labels: backend: Go, category:bugfix

#18207 go: upgrade golangci-lint to fix issue with Go v1.20
  src/python/pants/backend/go/lint/golangci_lint/subsystem.py
Labels: backend: Go, category:bugfix

#18206 Use `EnvironmentAwarePackageRequest` in many more contexts. (Cherry-pick of #18203)
  BUILD
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/docker/goals/package_image_integration_test.py
  src/python/pants/backend/docker/lint/hadolint/rules_integration_test.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/helm/goals/deploy_test.py
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/target_types.py
Labels: category:bugfix

#18204 Relativize the pants_bin_name if necessary.
  src/python/pants/bin/pants_runner.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_bootstrapper_test.py
  src/python/pants/util/dirutil.py
  src/python/pants/util/docutil.py
Labels: category:user api change

#18173 The beginnings of a Django plugin.
  src/python/pants/backend/experimental/python/framework/django/BUILD
  src/python/pants/backend/experimental/python/framework/django/__init__.py
  src/python/pants/backend/experimental/python/framework/django/register.py
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
  src/python/pants/backend/python/dependency_inference/scripts/main.py
  src/python/pants/backend/python/framework/django/BUILD
  src/python/pants/backend/python/framework/django/__init__.py
  src/python/pants/backend/python/framework/django/dependency_inference.py
  src/python/pants/backend/python/framework/django/dependency_inference_test.py
  src/python/pants/backend/python/framework/django/detect_apps.py
  src/python/pants/backend/python/framework/django/detect_apps_test.py
  src/python/pants/backend/python/framework/django/scripts/BUILD
  src/python/pants/backend/python/framework/django/scripts/__init__.py
  src/python/pants/backend/python/framework/django/scripts/app_detector.py
  src/python/pants/backend/python/framework/django/scripts/dependency_visitor.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
Labels: category:new feature

#18214 Give dedicated threads names
  src/rust/engine/nailgun/src/server.rs
  src/rust/engine/src/context.rs
  src/rust/engine/watch/src/lib.rs
  src/rust/engine/watch/src/tests.rs
Labels: category:internal

#18216 Always explicitly shutdown executors
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/bin/remote_pants_runner.py
  src/python/pants/init/engine_initializer.py
  src/rust/engine/src/externs/nailgun.rs
  src/rust/engine/src/externs/scheduler.rs
  src/rust/engine/src/externs/testutil.rs
  src/rust/engine/task_executor/src/lib.rs
Labels: needs-cherrypick, category:bugfix

#18218 Always explicitly shutdown executors (Cherry-pick of #18216)
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/bin/remote_pants_runner.py
  src/python/pants/init/engine_initializer.py
  src/rust/engine/src/externs/nailgun.rs
  src/rust/engine/src/externs/scheduler.rs
  src/rust/engine/src/externs/testutil.rs
  src/rust/engine/task_executor/src/lib.rs
Labels: category:bugfix

#18219 Fix published wheel RECORDs.
  build-support/bin/reversion.py
Labels: needs-cherrypick, category:bugfix

#18220 Fix published wheel RECORDs. (Cherry-pick of #18219)
  build-support/bin/reversion.py
Labels: category:bugfix

#18174 python: teach tailor goal to create resource targets for py.typed marker files
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/goals/tailor_test.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/tailor_test.py
Labels: category:new feature

#18221 Jacob Floyd/Huon Wilson updates to team page
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: needs-cherrypick, category:documentation

#18172 BUILD file target field default should respect values from `__defaults__`.
  docs/markdown/Using Pants/concepts/targets.md
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/parser.py
Labels: category:bugfix

#18224 Prepare the 2.15.0rc5 release.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#18227 docs: further updates to 2.16.x What's New
  src/python/pants/notes/2.16.x.md
Labels: category:documentation

#18054 Stream large remote cache downloads directly to disk
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/grpc_util/src/lib.rs
  src/rust/engine/grpc_util/src/retry.rs
Labels: category:bugfix

#18226 docs: add What's New section for 2.15.x release notes
  src/python/pants/notes/2.15.x.md
Labels: category:documentation

#18230 Upgrade Pex to 2.1.122.
  .github/workflows/test.yaml
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  build-support/bin/_release_helper.py
  build-support/bin/generate_github_workflows.py
  pants.toml
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18228 Move ruff from fmt to fix
  src/python/pants/backend/python/lint/ruff/rules.py
  src/python/pants/backend/python/lint/ruff/rules_integration_test.py
Labels: category:bugfix, backend: Python

#18223 Refactors `experimental_shell_command`-related files to better separate concerns
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/adhoc_process_support.py
  src/python/pants/backend/shell/util_rules/run_in_sandbox.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:internal, backend: Shell

#18232 docs: add What's New section for 2.15.x release notes (#18226)
  src/python/pants/notes/2.15.x.md
Labels: category:documentation

#18234 Update the stated release target to match our desired reality.
  docs/markdown/Contributions/releases/release-strategy.md
Labels: needs-cherrypick, category:documentation

#18238 docs: fix typo
  src/python/pants/notes/2.16.x.md
Labels: category:documentation

#18236 Allow exporting codegenerated files/resources
  src/python/pants/core/target_types.py
Labels: needs-cherrypick, category:new feature

#18241 Allow exporting codegenerated files/resources (Cherry-pick of #18236)
  src/python/pants/core/target_types.py
Labels: category:new feature

#18225 Avoid bind-mounts for docker environments on macOS
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/internals/scheduler_test_base.py
  src/python/pants/engine/rules_test.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/option/global_options.py
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/snapshot_tests.rs
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
  src/rust/engine/process_execution/src/nailgun/tests.rs
  src/rust/engine/process_execution/src/named_caches.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:bugfix

#18244 Allow breakpoints to be hit when run_in_sandbox is False
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_source.py
Labels: needs-cherrypick, category:bugfix

#18247 Revert "Avoid bind-mounts for docker environments on macOS (#18225)"
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/internals/scheduler_test_base.py
  src/python/pants/engine/rules_test.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/option/global_options.py
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/snapshot_tests.rs
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/nailgun/mod.rs
  src/rust/engine/process_execution/src/nailgun/nailgun_pool.rs
  src/rust/engine/process_execution/src/nailgun/tests.rs
  src/rust/engine/process_execution/src/named_caches.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:internal

#18245 Allow breakpoints to be hit when run_in_sandbox is False (Cherry-pick of #18244)
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_source.py
Labels: category:bugfix

#18248 Allow lambdas for `Field` and `Target` help
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/build_files/fix/deprecations/subsystem.py
  src/python/pants/backend/build_files/fmt/buildifier/subsystem.py
  src/python/pants/backend/cc/lint/clangformat/subsystem.py
  src/python/pants/backend/codegen/avro/target_types.py
  src/python/pants/backend/codegen/protobuf/python/additional_fields.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/target_types.py
  src/python/pants/backend/codegen/thrift/target_types.py
  src/python/pants/backend/cue/subsystem.py
  src/python/pants/backend/cue/target_types.py
  src/python/pants/backend/debian/target_types.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/go/goals/generate.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/javascript/lint/prettier/subsystem.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/plugin_development/pants_requirements.py
  src/python/pants/backend/project_info/filter_targets.py
  src/python/pants/backend/project_info/regex_lint.py
  src/python/pants/backend/python/framework/stevedore/target_types.py
  src/python/pants/backend/python/goals/publish.py
  src/python/pants/backend/python/macros/common_fields.py
  src/python/pants/backend/python/macros/python_requirements.py
  src/python/pants/backend/python/packaging/pyoxidizer/subsystem.py
  src/python/pants/backend/python/packaging/pyoxidizer/target_types.py
  src/python/pants/backend/python/subsystems/repos.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/typecheck/mypy/mypyc.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/terraform/target_types.py
  src/python/pants/backend/tools/preamble/subsystem.py
  src/python/pants/core/goals/package.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/subsystems/debug_adapter.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/wrap_source.py
  src/python/pants/engine/target.py
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/jvm/subsystems.py
  src/python/pants/jvm/target_types.py
  src/python/pants/option/subsystem.py
  src/python/pants/util/strutil.py
  src/python/pants/vcs/changed.py
Labels: category:internal

#18251 Fix bootstrap issue with `__defaults__` and environments.
  docs/markdown/Using Pants/concepts/targets.md
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
Labels: needs-cherrypick, category:bugfix

#18237 Extracts `backend.adhoc` package and `backend.experimental.adhoc` backend for `adhoc_tool`
  pants.toml
  src/python/pants/backend/adhoc/BUILD
  src/python/pants/backend/adhoc/__init__.py
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/experimental/adhoc/BUILD
  src/python/pants/backend/experimental/adhoc/__init__.py
  src/python/pants/backend/experimental/adhoc/adhoc_tool_backend_integration_test.py
  src/python/pants/backend/experimental/adhoc/register.py
  src/python/pants/backend/shell/register.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/bin/BUILD
  src/python/pants/core/util_rules/adhoc_process_support.py
  src/python/pants/engine/target.py
Labels: category:user api change, backend: Shell

#18258 Delete override of expected `exe` name for `shfmt`.
  src/python/pants/backend/shell/lint/shfmt/subsystem.py
Labels: needs-cherrypick, category:bugfix

#18259 Delete override of expected `exe` name for `shfmt`. (Cherry-pick of #18258)
  src/python/pants/backend/shell/lint/shfmt/subsystem.py
Labels: category:bugfix

#18257 Upgrade to Lambdex 0.1.9
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/lambdex.py
Labels: needs-cherrypick, category:bugfix

#18261 Upgrade to Lambdex 0.1.9 (Cherry-pick of #18257)
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/lambdex.py
Labels: category:bugfix

#18262 Fix bootstrap issue with `__defaults__` and environments. (Cherry-pick of #18251)
  docs/markdown/Using Pants/concepts/targets.md
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/defaults.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
Labels: category:bugfix

#18263 Prepare the 2.15.0rc6 release.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#18255 Deprecates `experimental_shell_command`, replacing with `shell_command`
  docs/markdown/Helm/helm-deployments.md
  docs/markdown/Shell/run-shell-commands.md
  src/python/pants/backend/shell/goals/test_test.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
  src/python/pants/core/util_rules/wrap_source_intergration_test.py
  src/python/pants/notes/2.16.x.md
  testprojects/wrap_as/BUILD
Labels: category:user api change

#18266 Deprecates `experimental_run_shell_command` in favour of `run_shell_command`
  docs/markdown/Helm/helm-deployments.md
  docs/markdown/Shell/run-shell-commands.md
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command_integration_test.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
  testprojects/src/python/BUILD
Labels: category:user api change, backend: Shell

#18270 docs: use an example black version that does not explode
  docs/markdown/Python/python-goals/python-package-goal.md
Labels: category:documentation

#18272 Fix release for /tmp on a seperate filesystem.
  build-support/bin/reversion.py
Labels: category:internal

#18271 go: support embed configuration in stdlib packages
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/build_pkg_target_test.py
  src/python/pants/backend/go/util_rules/import_analysis.py
Labels: backend: Go, category:bugfix

#18229 go: update pass-through `go test` options for Go v1.20
  src/python/pants/backend/go/go_sources/gentestflags.go
  src/python/pants/backend/go/goals/test.py
Labels: backend: Go, category:internal

#18280 Don't specify interpreter_constraints when building the release pex.
  build-support/bin/_release_helper.py
Labels: category:internal

#18281 Add default gha 1000:1000 user to GHA images.
  build-support/wheel_build_aarch64/Dockerfile
  build-support/wheel_build_x86_64/Dockerfile
Labels: category:internal

#18296 go: fix `go vet` test flakiness
  src/python/pants/backend/go/lint/vet/rules_integration_test.py
Labels: backend: Go, category:internal

#18297 Prep for 2.16.0.dev7
  CONTRIBUTORS.md
  src/python/pants/VERSION
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#18299 Change bool values to lowercase in TOML snippets
  docs/markdown/Python/python-goals/python-test-goal.md
Labels: category:documentation

#18295 Ensure that the pep-517 backend shim works on Python 2.7.
  src/python/pants/backend/python/util_rules/dists.py
  src/python/pants/backend/python/util_rules/dists_test.py
Labels: category:bugfix

#18267 Restore `experimental_run_shell_command`, which was accidentally deleted
  src/python/pants/backend/shell/target_types.py
Labels: category:internal, backend: Shell

#18298 Add mailmap entry for cburroughs
  .mailmap
  CONTRIBUTORS.md
Labels: category:internal

#18300 Ensure that the pep-517 backend shim works on Python 2.7. (Cherry-pick of #18295)
  src/python/pants/backend/python/util_rules/dists.py
  src/python/pants/backend/python/util_rules/dists_test.py
Labels: category:bugfix

#18314 go: cleanup `go-dump-import-path-mapping` debug goal
  src/python/pants/backend/go/goals/debug_goals.py
Labels: backend: Go, category:internal

#18312 go: add backends which were missing from distribution
  src/python/pants/bin/BUILD
Labels: backend: Go, category:internal

#18316 go: add backends which were missing from distribution (Cherrypick of #18312)
  src/python/pants/bin/BUILD
Labels: backend: Go, category:internal

#18317 go: cleanup `go-dump-import-path-mapping` debug goal (Cherry-pick of #18314)
  src/python/pants/backend/go/goals/debug_goals.py
Labels: backend: Go, category:internal

#18304 Remove dependency on clap 2
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/process_executor/Cargo.toml
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/testutil/local_execution_server/Cargo.toml
  src/rust/engine/testutil/local_execution_server/src/main.rs
Labels: category:internal

#18305 Get rid of the LockfileContent class
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/lockfile_diff.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:plugin api change

#18302 fix documentation
  docs/markdown/Python/python-integrations/awslambda-python.md
Labels: category:documentation

#18233 removing some unwraps from the FFI layer
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#17449 Enable running third-party Go `main` packages
  src/python/pants/backend/go/goals/package_binary.py
  src/python/pants/backend/go/goals/package_binary_integration_test.py
  src/python/pants/backend/go/goals/run_binary_integration_test.py
  src/python/pants/backend/go/target_type_rules_test.py
  src/python/pants/backend/go/testutil.py
  src/python/pants/backend/go/util_rules/binary.py
  src/python/pants/backend/go/util_rules/embed_integration_test.py
  src/python/pants/testutil/pants_integration_test.py
Labels: backend: Go, category:new feature

#18310 (P)refactor `hashing` crate
  src/rust/engine/Cargo.lock
  src/rust/engine/hashing/Cargo.toml
  src/rust/engine/hashing/src/hasher_tests.rs
  src/rust/engine/hashing/src/lib.rs
  src/rust/engine/sharded_lmdb/src/lib.rs
Labels: category:internal

#18332 Adds `system_binary` target, which can be used to reproducibly find a pre-installed binary for use with `adhoc_tool`
  src/python/pants/backend/adhoc/run_system_binary.py
  src/python/pants/backend/adhoc/run_system_binary_integration_test.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/experimental/adhoc/register.py
Labels: category:new feature

#18327 Docker environment uses a volume for named caches
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/nailgun/tests.rs
  src/rust/engine/process_execution/src/named_caches.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
Labels: needs-cherrypick, category:bugfix

#18336 Bump to a new version of buildgrid to fix a pinning issue.
  build-support/reapi-sample-server/Dockerfile
  pants.remote-execution.toml
Labels: category:internal

#18337 Docker environment uses a volume for named caches (Cherry-pick of #18327)
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/docker_tests.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/nailgun/tests.rs
  src/rust/engine/process_execution/src/named_caches.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
Labels: category:bugfix

#18330 Deprecate the `@rule_helper` decorator.
  src/python/pants/backend/cc/util_rules/toolchain.py
  src/python/pants/backend/cue/rules.py
  src/python/pants/backend/go/goals/generate.py
  src/python/pants/backend/go/goals/tailor.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/cgo.py
  src/python/pants/backend/go/util_rules/go_bootstrap.py
  src/python/pants/backend/go/util_rules/go_mod.py
  src/python/pants/backend/go/util_rules/third_party_pkg.py
  src/python/pants/backend/helm/subsystems/post_renderer.py
  src/python/pants/backend/helm/util_rules/chart.py
  src/python/pants/backend/helm/util_rules/post_renderer.py
  src/python/pants/backend/helm/util_rules/renderer.py
  src/python/pants/backend/helm/util_rules/sources.py
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_requirement.py
  src/python/pants/backend/python/goals/tailor.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/backend/python/macros/common_requirements_rule.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/util_rules/lockfile_diff.py
  src/python/pants/backend/python/util_rules/partition.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/base/deprecated.py
  src/python/pants/core/goals/deploy.py
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/asdf.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/wrap_source.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/internals/specs_rules.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/target.py
  src/python/pants/jvm/bsp/compile.py
  src/python/pants/jvm/bsp/resources.py
  src/python/pants/jvm/package/war.py
  src/python/pants/jvm/run.py
  src/python/pants/testutil/rule_runner.py
Labels: category:plugin api change

#18260 Prep for having build file symbol info.
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
Labels: category:internal

#18338 Prepare `2.15.0rc7`.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#18341 Ugrade Pex to 2.1.123.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18073 docs: mention code generation when troubleshooting missing imports from first-party code
  docs/markdown/Using Pants/troubleshooting.md
Labels: category:documentation

#18339 datahub & slugify default module mappings
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#18273 Support using `env()` in prelude macro files
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
Labels: category:bugfix

#18342 Add yamllint to the list of backends
  build-support/bin/generate_docs.py
  src/python/pants/backend/experimental/tools/yamllint/BUILD
  src/python/pants/backend/experimental/tools/yamllint/register.py
  src/python/pants/bin/BUILD
Labels: category:internal

#18343 Use new Linux aarch64 wheel build image.
  .github/workflows/test.yaml
  build-support/bin/_release_helper.py
  build-support/bin/classify_changed_files.py
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#18340 Upgrade the `os_pipe` crate, and use new safe IO types
  src/rust/engine/Cargo.lock
  src/rust/engine/nailgun/Cargo.toml
  src/rust/engine/nailgun/src/server.rs
Labels: category:internal

#18350 Streamline PexRequest creation in a few places
  pants-plugins/internal_plugins/test_lockfile_fixtures/rules.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/util_rules/dists.py
Labels: category:internal

#18315 18215: split process execution into smaller crates
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/docker/Cargo.toml
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/docker/src/docker_tests.rs
  src/rust/engine/process_execution/docker/src/lib.rs
  src/rust/engine/process_execution/pe_nailgun/Cargo.toml
  src/rust/engine/process_execution/pe_nailgun/src/lib.rs
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/engine/process_execution/pe_nailgun/src/parsed_jvm_command_lines.rs
  src/rust/engine/process_execution/pe_nailgun/src/parsed_jvm_command_lines_tests.rs
  src/rust/engine/process_execution/pe_nailgun/src/tests.rs
  src/rust/engine/process_execution/remote/Cargo.toml
  src/rust/engine/process_execution/remote/src/lib.rs
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_executor/Cargo.toml
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:internal

#18355 Remove defunct newsletter
  docs/markdown/Getting Help/getting-help.md
Labels: needs-cherrypick, category:documentation

#18309 Switch store code from `Option<Digest>` to `Fingerprint`
  src/rust/engine/cache/src/lib.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/fs/store/src/local_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/sharded_lmdb/src/lib.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:internal

#18358 use valid container/app names in helm examples
  docs/markdown/Helm/helm-deployments.md
Labels: category:documentation, backend: Helm

#18357 Prepare `2.15.0`.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#18360 Upgrade the thread-local crate.
  src/rust/engine/Cargo.lock
Labels: category:internal

#18363 [internal] adhoc: drop deprecated `@rule_helper`.
  src/python/pants/backend/adhoc/run_system_binary.py
Labels: category:internal

#18303 Add flake8 rule disallowing await inside loops
  build-support/flake8/.flake8
  build-support/flake8/await_in_loop.py
  src/python/pants/backend/cc/util_rules/toolchain.py
  src/python/pants/backend/go/goals/debug_goals.py
  src/python/pants/backend/go/goals/generate.py
  src/python/pants/backend/go/util_rules/goroot.py
  src/python/pants/backend/openapi/goals/tailor.py
  src/python/pants/backend/python/framework/django/detect_apps.py
  src/python/pants/backend/python/goals/setup_py.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/bsp/util_rules/targets.py
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/engine/internals/dep_rules.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/jvm/goals/lockfile.py
  src/python/pants/source/source_root.py
Labels: category:internal

#18208 javascript: Support esm modules and commonjs specific javascript file extensions
  src/python/pants/backend/javascript/goals/tailor_test.py
  src/python/pants/backend/javascript/target_types.py
Labels: category:new feature, backend: JavaScript

#18367 Errors in `--loop` wait for changes rather than re-running immediately
  src/rust/engine/graph/src/entry.rs
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/graph/src/tests.rs
  src/rust/engine/hashing/Cargo.toml
  src/rust/engine/src/scheduler.rs
  src/rust/engine/src/session.rs
Labels: category:bugfix

#18371 docs: upgrade plugin writing tutorial to 2.15.0
  docs/markdown/Tutorials/test-custom-plugin-goal.md
Labels: category:documentation

#18373 Fix export-codgen with multiple output types from same input type
  src/python/pants/backend/codegen/export_codegen_goal.py
  src/python/pants/backend/codegen/export_codegen_goal_test.py
Labels: category:bugfix

#18374 Simplify canceling jobs for previous pushes of the same PR.
  .github/workflows/cancel.yaml
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#18376 Upgrade Pex to 2.1.124.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  pants.toml
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18380 docs: tidy up writing plugins tutorial
  docs/markdown/Tutorials/create-a-new-goal.md
Labels: category:documentation

#18347 Adds support for supplying "runnable" dependencies to the `execution_dependencies` field
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/run_system_binary.py
  src/python/pants/backend/adhoc/run_system_binary_integration_test.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/core/util_rules/adhoc_process_support.py
  src/python/pants/engine/target.py
  src/python/pants/util/frozendict.py
  src/python/pants/util/frozendict_test.py
Labels: category:new feature
