Repository pantsbuild/pants, pull requests merged in 2023-03, with the labels that each got.

#18362 [internal] Don't choke on union types.
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/internals/rule_visitor_test.py
  src/python/pants/util/backport.py
  src/python/pants/util/typing.py
  src/python/pants/util/typing_test.py
Labels: category:internal

#18112 Support for `peek`ing at dependency/dependents rules
  src/python/pants/backend/go/goals/BUILD
  src/python/pants/backend/go/util_rules/BUILD
  src/python/pants/backend/project_info/peek.py
  src/python/pants/backend/project_info/peek_test.py
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/dep_rules.py
Labels: category:new feature

#18389 Give pantsd more RAM by default.
  src/python/pants/option/global_options.py
Labels: category:user api change

#18390 Deprecate the default interpreter constraints.
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/option/option_types.py
Labels: category:user api change

#18393 Some doc fixes suggested by users.
  docs/markdown/Docker/docker.md
  docs/markdown/Python/python/python-distributions.md
Labels: category:documentation

#18394 Some doc fixes suggested by users. (Cherry-pick of #18393)
  docs/markdown/Docker/docker.md
  docs/markdown/Python/python/python-distributions.md
Labels: category:documentation

#18396 Fix `paths` issue with transitive excludes.
  src/python/pants/backend/project_info/paths.py
  src/python/pants/backend/project_info/paths_test.py
Labels: category:bugfix

#18395 Upgrade Pex to 2.1.125.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18369 Visibility: support matching on target names.
  docs/markdown/Using Pants/validating-dependencies.md
  src/python/pants/backend/visibility/glob.py
  src/python/pants/backend/visibility/glob_test.py
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:new feature

#18397 Support specifying a named resolve as the superset in a PexRequirements.
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:plugin api change

#18398 Fix OSError when running pants in nspawn container
  src/python/pants/bin/remote_pants_runner.py
Labels: category:bugfix

#18378 Build file help info
  src/python/pants/build_graph/build_configuration.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/explorer/server/graphql/query/conftest.py
  src/python/pants/goal/explorer.py
  src/python/pants/goal/help.py
  src/python/pants/help/flag_error_help_printer.py
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_printer.py
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: category:new feature

#18383 Add `sources_fingerprint` to `peek` on source-creating targets
  src/python/pants/backend/project_info/peek.py
  src/python/pants/backend/project_info/peek_test.py
Labels: category:new feature

#18402 Update module mapping for attrs
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#18407 [internal] Err out with helpful message if no Python found.
  build-support/common.sh
Labels: category:internal

#18408 Upgrade Pex to 2.1.126.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18415 Delegate lockfile requirement validation to Pex when possible.
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:user api change

#18416 docs: update What's New for 2.16
  src/python/pants/notes/2.16.x.md
Labels: category:documentation

#18405 Add `python311` runtime to `python_google_cloud_function` target
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types_test.py
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/subsystems/lambdex.py
Labels: category:user api change

#18419 docs: fix typos and some language updates
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#18413 python: collect files with '[tool.ruff' sections as candidates for Ruff config files
  src/python/pants/backend/python/lint/ruff/subsystem.py
Labels: category:bugfix, backend: Python

#18352 Add the ability for Pants to provide Python via a union (with a pyenv impl)
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/providers/BUILD
  src/python/pants/backend/python/providers/__init__.py
  src/python/pants/backend/python/providers/experimental/__init__.py
  src/python/pants/backend/python/providers/experimental/pyenv/BUILD
  src/python/pants/backend/python/providers/experimental/pyenv/__init__.py
  src/python/pants/backend/python/providers/experimental/pyenv/register.py
  src/python/pants/backend/python/providers/pyenv/BUILD
  src/python/pants/backend/python/providers/pyenv/__init__.py
  src/python/pants/backend/python/providers/pyenv/rules.py
  src/python/pants/backend/python/providers/pyenv/rules_integration_test.py
  src/python/pants/backend/python/providers/pyenv/target_types.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/bin/BUILD
  src/python/pants/core/goals/run.py
  src/python/pants/init/plugin_resolver.py
Labels: category:new feature

#18422 Expand on 2.16 shell/adhoc what's new, and some other sections
  src/python/pants/notes/2.16.x.md
Labels: category:documentation

#18428 docs: add 2.15 link to changelog
  docs/markdown/Releases/changelog.md
Labels: category:internal

#18409 golang: add support for passthrough args for gofmt
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/gofmt/rules_integration_test.py
  src/python/pants/backend/go/lint/gofmt/subsystem.py
Labels: backend: Go, category:new feature

#18418 Allow python tools to be installed from a user resolve.
  src/python/pants/backend/python/pip_requirement.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/python_tool_base_test.py
  src/python/pants/backend/python/subsystems/setuptools_scm.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:new feature

#18427 `shell_command`/`adhoc_tool` doc minor suggestions
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#18403 Prepare 2.16.0a0.
  CONTRIBUTORS.md
  build-support/bin/classify_changed_files.py
  build-support/bin/classify_changed_files_test.py
  src/python/pants/VERSION
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#18421 Fixes to visualisations for xdot
  src/python/pants/engine/rules_test.py
  src/rust/engine/graph/src/entry.rs
  src/rust/engine/rule_graph/src/lib.rs
Labels: category:bugfix

#18429 go: skip go v1.20+ when searching for the GOROOT
  src/python/pants/backend/go/util_rules/goroot.py
  src/python/pants/backend/go/util_rules/goroot_test.py
Labels: backend: Go, category:bugfix

#18436 docs: bump updatedAt time
  docs/markdown/Releases/changelog.md
Labels: category:internal

#18370 Removing more unwraps from FFI layer
  src/rust/engine/options/src/env_tests.rs
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/pe_nailgun/src/lib.rs
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
Labels: category:internal

#18432 docs: add 2.15 link to changelog (Cherry-pick of #18428)
  docs/markdown/Releases/changelog.md
Labels: category:internal

#18438 docs: bump updatedAt time (Cherry pick of #18436)
  docs/markdown/Releases/changelog.md
Labels: category:internal

#18439 Fix cancelling parallel jobs.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#18440 Update the release instructions for docs/.
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#18417 Refactor common "bootstrap" logic to prepare for internal re-use
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/go/util_rules/go_bootstrap.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/subsystems/python_bootstrap_test.py
  src/python/pants/core/util_rules/asdf.py
  src/python/pants/core/util_rules/search_paths.py
  src/python/pants/core/util_rules/search_paths_test.py
  src/python/pants/engine/env_vars.py
  src/python/pants/engine/internals/platform_rules.py
  src/python/pants/engine/internals/platform_rules_test.py
  src/python/pants/option/subsystem.py
Labels: category:internal

#18441 Improve release docs publishing instructions.
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#18444 Fixup release docs for docs/. (Cherry-pick of #18440 & #18441)
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#18443 Fixup release docs for docs/. (Cherry-pick of #18440 & #18441)
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#18446 Synthesized lockfile targets should never err on missing lockfiles. (Cherry-pick of #18406)
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/core/target_types.py
  src/python/pants/core/target_types_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/option/global_options.py
Labels: category:bugfix

#18445 Upgrade Pex to 2.1.127.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18412 Support running `pants` from anywhere in the project.
  src/python/pants/base/specs_parser.py
  src/python/pants/base/specs_parser_test.py
  src/python/pants/bin/daemon_pants_runner.py
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/bin/pants_loader.py
  src/python/pants/bin/pants_runner.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/src/externs/interface.rs
Labels: category:new feature

#18447 Synthesized lockfile targets should never err on missing lockfiles. (Cherry-pick of #18406)
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/core/target_types.py
  src/python/pants/core/target_types_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/option/global_options.py
Labels: category:bugfix

#18442 Support type hints in prelude files.
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: needs-cherrypick, category:bugfix

#18449 Support type hints in prelude files. (Cherry-pick of #18442)
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: category:bugfix

#17480 Helpers to generate python lockfile rules
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-helpers.md
  src/python/pants/backend/BUILD
  src/python/pants/backend/cc/lint/clangformat/subsystem.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/post_renderer.py
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/lint/add_trailing_comma/subsystem.py
  src/python/pants/backend/python/lint/autoflake/subsystem.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/docformatter/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/isort/subsystem.py
  src/python/pants/backend/python/lint/pydocstyle/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pyupgrade/subsystem.py
  src/python/pants/backend/python/lint/ruff/subsystem.py
  src/python/pants/backend/python/lint/ruff/subsystem_test.py
  src/python/pants/backend/python/lint/yapf/subsystem.py
  src/python/pants/backend/python/packaging/pyoxidizer/subsystem.py
  src/python/pants/backend/python/subsystems/debugpy.py
  src/python/pants/backend/python/subsystems/ipython.py
  src/python/pants/backend/python/subsystems/lambdex.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/backend/python/subsystems/setuptools_scm.py
  src/python/pants/backend/python/subsystems/twine.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/lockfile.py
  src/python/pants/backend/python/util_rules/lockfile_test.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/tools/yamllint/subsystem.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/testutil/rule_runner.py
Labels: category:internal

#18453 Upgrade Pex to 2.1.128.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#18452 Only expose the equiv of `from typing import *` in prelude files
  src/python/pants/engine/internals/build_files.py
Labels: needs-cherrypick, category:bugfix

#18455 Only expose the equiv of `from typing import *` in prelude files (Cherry-pick of #18452)
  src/python/pants/engine/internals/build_files.py
Labels: category:bugfix

#18454 Upgrade Pex to 2.1.128. (Cherry-pick of #18453)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18459 Fix commit collision between #17480 and #18431.
  src/python/pants/backend/python/lint/ruff/subsystem_test.py
Labels: category:internal

#18458 Expose environment information on process metadata
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/core/subsystems/python_bootstrap_test.py
  src/python/pants/core/util_rules/asdf_test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/core/util_rules/search_paths_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/platform_rules_test.py
  src/python/pants/engine/process.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/docker/src/docker_tests.rs
  src/rust/engine/process_execution/pe_nailgun/src/lib.rs
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
Labels: category:new feature

#18463 Expose environment information on process metadata (Cherry-pick of #18458)
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/core/subsystems/python_bootstrap_test.py
  src/python/pants/core/util_rules/asdf_test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/platform_rules_test.py
  src/python/pants/engine/process.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/docker/src/docker_tests.rs
  src/rust/engine/process_execution/pe_nailgun/src/lib.rs
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/remote/src/remote_cache.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/nodes.rs
Labels: category:new feature

#18465 Preserve environment variables in `pantsd` to allow Docker auth.
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/util/contextutil.py
  src/python/pants/util/contextutil_test.py
Labels: needs-cherrypick, category:bugfix

#18468 Preserve environment variables in `pantsd` to allow Docker auth. (Cherry-pick of #18465)
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/util/contextutil.py
  src/python/pants/util/contextutil_test.py
Labels: category:bugfix

#18467 Preserve environment variables in `pantsd` to allow Docker auth. (Cherry-pick of #18465)
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/util/contextutil.py
  src/python/pants/util/contextutil_test.py
Labels: category:bugfix

#18470 Prepare 2.17.0.dev0
  pants.toml
  src/python/pants/VERSION
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/python/mixed_interpreter_constraints/py_constraints.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/core/util_rules/adhoc_process_support.py
  src/python/pants/engine/environment.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/rules.py
  src/python/pants/notes/2.17.x.md
  src/python/pants/util/meta.py
Labels: category:internal

#18472 Upgrade Pex to 2.1.129.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: needs-cherrypick, category:user api change

#18469 Finish parallelizing materialization of Process inputs
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/pe_nailgun/src/lib.rs
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:performance

#18471 Expand lockfile documentation to its own page.
  docs/markdown/Python/python/python-lockfiles.md
  docs/markdown/Python/python/python-third-party-dependencies.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-helpers.md
Labels: category:documentation

#18474 Expand lockfile documentation to its own page. (cherrypick of #18471)
  docs/markdown/Python/python/python-lockfiles.md
  docs/markdown/Python/python/python-third-party-dependencies.md
  docs/markdown/Writing Plugins/common-plugin-tasks/plugin-helpers.md
Labels: category:documentation

#18477 Fix release script's expected maintainers
  build-support/bin/_release_helper.py
  docs/markdown/Contributions/releases/release-process.md
Labels: category:internal

#18478 Support dynamic removal_hint messages.
  src/python/pants/option/option_types.py
  src/python/pants/option/option_types_test.py
Labels: category:internal

#18480 upgrade Rust to v1.68.0
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
  src/rust/engine/src/scheduler.rs
Labels: category:internal

#18479 Support dynamic removal_hint messages. (Cherry-pick of #18478)
  src/python/pants/option/option_types.py
  src/python/pants/option/option_types_test.py
Labels: category:internal

#18485 update scie-jump cache directory reference
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#18484 fix malformed pantsbuild/example-python link
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#18487 Disable hardlinking of immutable inputs
  src/rust/engine/fs/store/src/lib.rs
Labels: needs-cherrypick, category:internal

#18433 Always provide Python-for-Pants-scripts
  pants.toml
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_requirement.py
  src/python/pants/backend/python/providers/pyenv/rules_integration_test.py
  src/python/pants/backend/python/util_rules/local_dists.py
  src/python/pants/backend/python/util_rules/local_dists_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/core/register.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/adhoc_binaries_test.py
  src/python/pants/core/util_rules/archive.py
  src/python/pants/jvm/resolve/coursier_setup.py
  src/python/pants/testutil/pants_integration_test.py
  src/python/pants/testutil/rule_runner.py
Labels: needs-cherrypick, category:new feature

#18481 Let a user resolve shadow a tool lockfile of the same name
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/macros/common_requirements_rule.py
  src/python/pants/backend/python/macros/pipenv_requirements_test.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
  src/python/pants/backend/python/macros/python_requirements_test.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/generate_lockfiles_test.py
  src/python/pants/engine/internals/synthetic_targets_test.py
Labels: category:user api change

#18483 enable cargo sparse protocol for index downloads
  src/rust/engine/.cargo/config
Labels: category:internal

#18493 Let a user resolve shadow a tool lockfile of the same name (Cherry-pick of #18481)
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/macros/common_requirements_rule.py
  src/python/pants/backend/python/macros/pipenv_requirements_test.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
  src/python/pants/backend/python/macros/python_requirements_test.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/generate_lockfiles_test.py
  src/python/pants/engine/internals/synthetic_targets_test.py
Labels: category:user api change

#18494 Deprecate old-style custom tool lockfiles.
  3rdparty/python/BUILD
  3rdparty/python/flake8-requirements.txt
  3rdparty/python/mypy-requirements.txt
  3rdparty/python/pytest-requirements.txt
  docs/markdown/Python/python/python-lockfiles.md
  pants.toml
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:user api change

#18473 Upgrade Pex to 2.1.129. (Cherry-pick of #18472)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18495 Always provide Python-for-Pants-scripts (Cherry-pick of #18433)
  pants.toml
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_python_requirement.py
  src/python/pants/backend/python/providers/pyenv/rules_integration_test.py
  src/python/pants/backend/python/util_rules/local_dists.py
  src/python/pants/backend/python/util_rules/local_dists_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
  src/python/pants/core/register.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/adhoc_binaries_test.py
  src/python/pants/core/util_rules/archive.py
  src/python/pants/jvm/resolve/coursier_setup.py
  src/python/pants/testutil/pants_integration_test.py
  src/python/pants/testutil/rule_runner.py
Labels: category:new feature

#18496 Add ExoFlare to user list.
  build-support/bin/generate_user_list.py
Labels: category:documentation

#18492 Disable hardlinking of immutable inputs (Cherry-pick of #18487)
  src/rust/engine/fs/store/src/lib.rs
Labels: category:internal

#18498 Deprecate old-style custom tool lockfiles. (#18494)
  3rdparty/python/BUILD
  3rdparty/python/flake8-requirements.txt
  3rdparty/python/mypy-requirements.txt
  3rdparty/python/pytest-requirements.txt
  docs/markdown/Python/python/python-lockfiles.md
  pants.toml
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:user api change

#18501 Re-enable hardlinking using `fclonefileat` on macOS.
  src/rust/engine/fs/store/src/lib.rs
Labels: category:bugfix

#18513 Update docs on running pants from sources with scie-pants.
  docs/markdown/Contributions/development/running-pants-from-sources.md
Labels: category:documentation

#18514 Update docs on running pants from sources with scie-pants. (Cherry-pick of #18513)
  docs/markdown/Contributions/development/running-pants-from-sources.md
Labels: category:documentation

#18518 Use wheel build images from GitHub Packages.
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
  pants.toml
Labels: category:internal

#18521 Remove temporary comment in pants.toml.
  pants.toml
Labels: category:internal

#18522 Use wheel build images from GitHub Packages. (#18518)
  .github/workflows/test.yaml
  build-support/bin/generate_github_workflows.py
Labels: category:internal

#18529 Clarify that experimental_ shell functions are deprecated and replaced
  src/python/pants/notes/2.16.x.md
Labels: category:documentation

#18535 Fix Poetry req synthesis for URLs with markers.
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
Labels: needs-cherrypick, category:bugfix

#18539 docs: fix an f-string in help
  src/python/pants/engine/target.py
Labels: category:documentation

#18536 Fix Poetry req synthesis for URLs with markers. (Cherry-pick of #18535)
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
Labels: category:bugfix

#18534 engine: add an option to clear the destination directory when writing digest to disk
  src/python/pants/engine/fs.py
  src/python/pants/engine/fs_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/src/externs/interface.rs
Labels: category:new feature, backend: Python

#18537 Fix Poetry req synthesis for URLs with markers. (Cherry-pick of #18535)
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
Labels: category:bugfix

#18538 Fix Poetry req synthesis for URLs with markers. (Cherry-pick of #18535)
  src/python/pants/backend/python/macros/poetry_requirements.py
  src/python/pants/backend/python/macros/poetry_requirements_test.py
Labels: category:bugfix

#18541 Add support for Docker registry auth
  src/python/pants/pantsd/pants_daemon.py
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/docker/Cargo.toml
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:bugfix

#18549 Add support for Docker registry auth (Cherry-pick of #18541)
  src/python/pants/pantsd/pants_daemon.py
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/docker/Cargo.toml
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#18550 Add support for Docker registry auth (Cherry-pick of #18541)
  src/python/pants/pantsd/pants_daemon.py
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#18551 Declare ruff outputs as files.
  src/python/pants/backend/python/lint/ruff/rules.py
Labels: needs-cherrypick, category:bugfix

#18557 Declare ruff outputs as files. (Cherry-pick of #18551)
  src/python/pants/backend/python/lint/ruff/rules.py
Labels: category:bugfix

#18556 Adjust test timeouts
  src/python/pants/backend/codegen/protobuf/go/BUILD
  src/python/pants/backend/codegen/protobuf/scala/BUILD
  src/python/pants/backend/go/BUILD
  src/python/pants/backend/go/goals/BUILD
  src/python/pants/backend/go/lint/golangci_lint/BUILD
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/lint/yapf/BUILD
  src/python/pants/backend/scala/compile/BUILD
  src/python/pants/base/BUILD
  src/python/pants/engine/internals/BUILD
  tests/python/pants_test/pantsd/pantsd_integration_test.py
  tests/python/pants_test/pantsd/pantsd_integration_test_base.py
Labels: needs-cherrypick, category:internal

#18559 Add a few more packages/modules to default_module_mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#18560 Fail fast for attempts to use `test --debug` with a docker environment
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_integration_test.py
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:bugfix

#18153 Materialize "large" files in a new store location and hardlink them in sandboxes
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/fs/store/benches/store.rs
  src/rust/engine/fs/store/src/immutable_inputs.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/fs/store/src/local_tests.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/snapshot.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/hashing/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/sharded_lmdb/src/lib.rs
  src/rust/engine/sharded_lmdb/src/tests.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/nodes.rs
Labels: category:performance

#18558 Adjust test timeouts (Cherry-pick of #18556)
  src/python/pants/backend/codegen/protobuf/go/BUILD
  src/python/pants/backend/codegen/protobuf/scala/BUILD
  src/python/pants/backend/go/BUILD
  src/python/pants/backend/go/goals/BUILD
  src/python/pants/backend/go/lint/golangci_lint/BUILD
  src/python/pants/backend/python/goals/BUILD
  src/python/pants/backend/python/lint/yapf/BUILD
  src/python/pants/backend/scala/compile/BUILD
  src/python/pants/base/BUILD
  src/python/pants/engine/internals/BUILD
  tests/python/pants_test/pantsd/pantsd_integration_test.py
Labels: category:internal

#18571 Add Tobias Nilsson to team page
  docs/markdown/Getting Help/the-pants-community/team.md
Labels: category:documentation

#18567 Fail fast for attempts to use `test --debug` with a docker environment (Cherry-pick of #18560)
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_integration_test.py
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#18568 Fail fast for attempts to use `test --debug` with a docker environment (Cherry-pick of #18560)
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_integration_test.py
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#18572 Adds `adhoc` to list of enabled backends
  build-support/bin/generate_docs.py
Labels: needs-cherrypick, category:internal

#18578 Upgrade Pex to 2.1.130. (Cherry-pick of #18576)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18580 Adds `adhoc` to list of enabled backends (Cherry-pick of #18572)
  build-support/bin/generate_docs.py
Labels: category:internal

#18583 Prepare `2.14.2rc0`.
  src/python/pants/notes/2.14.x.md
Labels: category:internal

#18584 Prepare `2.15.1rc0`.
  src/python/pants/notes/2.15.x.md
Labels: category:internal

#18585 Ensure that a symlinked exported venv exists and is valid. (Cherry-pick of #18575)
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:bugfix

#18586 Prepare `2.16.0a1`.
  src/python/pants/notes/2.16.x.md
Labels: category:internal

#18582 Set the entire env in __run.sh
  src/rust/engine/process_execution/src/local.rs
Labels: category:internal

#18598 Remove deprecations from `adhoc_tool`/`shell_command` stablisation process
  docs/markdown/Shell/run-shell-commands.md
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/run_system_binary.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/goals/test_test.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: category:user api change

#18590 Prepare `2.17.0.dev1`.
  CONTRIBUTORS.md
  build-support/bin/_generate_all_lockfiles_helper.py
  docs/markdown/Writing Plugins/rules-api/rules-api-subsystems.md
  src/python/pants/VERSION
  src/python/pants/backend/cc/subsystems/compiler.py
  src/python/pants/backend/go/lint/golangci_lint/rules_integration_test.py
  src/python/pants/backend/go/lint/vet/rules_integration_test.py
  src/python/pants/backend/helm/goals/lint_test.py
  src/python/pants/backend/helm/goals/package_test.py
  src/python/pants/backend/javascript/subsystems/npx_tool_test.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
  src/python/pants/backend/python/goals/repl_integration_test.py
  src/python/pants/backend/python/goals/setup_py_test.py
  src/python/pants/backend/python/lint/bandit/rules_integration_test.py
  src/python/pants/backend/python/lint/flake8/rules_integration_test.py
  src/python/pants/backend/python/lint/pydocstyle/rules_integration_test.py
  src/python/pants/backend/python/lint/pylint/rules_integration_test.py
  src/python/pants/backend/python/lint/ruff/rules_integration_test.py
  src/python/pants/backend/python/mixed_interpreter_constraints/py_constraints.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/util_rules/partition_test.py
  src/python/pants/core/goals/update_build_files_test.py
  src/python/pants/engine/environment.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/internals/options_parsing_test.py
  src/python/pants/engine/rules.py
  src/python/pants/jvm/resolve/jvm_tool_test.py
  src/python/pants/notes/2.17.x.md
  src/python/pants/option/options_integration_test.py
  src/python/pants/option/subsystem.py
  src/python/pants/util/meta.py
  src/python/pants/util/meta_test.py
  src/python/pants/vcs/changed.py
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: category:internal

#18599 Improve debug information for docker auth, and expose an environment variable.
  src/python/pants/pantsd/pants_daemon.py
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/docker/Cargo.toml
Labels: needs-cherrypick, category:bugfix

#18608 Fix a string that should have been an f-string
  src/python/pants/backend/python/util_rules/pex_requirements.py
Labels: needs-cherrypick, category:documentation

#18606 Fix `./pants` -> `pants` in some docs and help strings. (Cherry-pick of #18596)
  build-support/bin/docs_templates/options_scope_reference.md.mustache
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/goals/repl_integration_test.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/option/arg_splitter.py
  src/python/pants/option/global_options.py
  src/python/pants/option/option_types.py
Labels: category:documentation

#18607 Fix `./pants` -> `pants` in some docs and help strings. (cherrypick of #18596)
  build-support/bin/docs_templates/options_scope_reference.md.mustache
  src/python/pants/backend/python/goals/lockfile_test.py
  src/python/pants/backend/python/goals/repl_integration_test.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/option/arg_splitter.py
  src/python/pants/option/global_options.py
  src/python/pants/option/option_types.py
Labels: category:documentation

#18603 Improve debug information for docker auth, and expose an environment variable. (Cherry-pick of #18599)
  src/python/pants/pantsd/pants_daemon.py
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/Cargo.toml
Labels: category:bugfix

#18573 expose PANTS_VERSION and make it string-comparable
  src/python/pants/core/aliases_test.py
  src/python/pants/core/register.py
  src/python/pants/testutil/rule_runner.py
  src/python/pants/version.py
Labels: category:new feature

#18605 Remove `safe_create_dir(_all)` in favor of stdlib implementation.
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/fs/store/benches/store.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/sharded_lmdb/src/lib.rs
  src/rust/engine/src/context.rs
Labels: category:internal

#18617 Upgrade to Rust `1.68.2`.
  .github/workflows/test-cron.yaml
  .github/workflows/test.yaml
  rust-toolchain
Labels: category:internal

#18600 Only materialize immutable files once per process
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/fs/store/src/remote.rs
  src/rust/engine/fs/store/src/remote_tests.rs
Labels: category:performance

#18610 Fix PexPEX invocations
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
Labels: needs-cherrypick, category:bugfix

#18554 javascript: Test goal with package manager installed test runner support
  src/python/pants/backend/experimental/javascript/register.py
  src/python/pants/backend/javascript/goals/BUILD
  src/python/pants/backend/javascript/goals/jest_resources/BUILD
  src/python/pants/backend/javascript/goals/jest_resources/package-lock.json
  src/python/pants/backend/javascript/goals/mocha_resources/BUILD
  src/python/pants/backend/javascript/goals/mocha_resources/package-lock.json
  src/python/pants/backend/javascript/goals/tailor.py
  src/python/pants/backend/javascript/goals/tailor_test.py
  src/python/pants/backend/javascript/goals/test.py
  src/python/pants/backend/javascript/goals/test_integration_test.py
  src/python/pants/backend/javascript/install_node_package.py
  src/python/pants/backend/javascript/nodejs_project_environment.py
  src/python/pants/backend/javascript/nodejs_project_test.py
  src/python/pants/backend/javascript/package/rules.py
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/backend/javascript/package_json_test.py
  src/python/pants/backend/javascript/resolve_test.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejstest.py
  src/python/pants/backend/javascript/target_types.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/core/goals/test.py
  testprojects/src/js/coverage_workspaces/BUILD
  testprojects/src/js/coverage_workspaces/jest_coverage
  testprojects/src/js/coverage_workspaces/mocha_coverage
  testprojects/src/js/coverage_workspaces/package-lock.json
  testprojects/src/js/coverage_workspaces/package.json
  testprojects/src/js/jest_coverage/BUILD
  testprojects/src/js/jest_coverage/package-lock.json
  testprojects/src/js/jest_coverage/package.json
  testprojects/src/js/jest_coverage/src/BUILD
  testprojects/src/js/jest_coverage/src/index.cjs
  testprojects/src/js/jest_coverage/src/test/BUILD
  testprojects/src/js/jest_coverage/src/test/index.test.js
  testprojects/src/js/mocha_coverage/BUILD
  testprojects/src/js/mocha_coverage/package-lock.json
  testprojects/src/js/mocha_coverage/package.json
  testprojects/src/js/mocha_coverage/src/BUILD
  testprojects/src/js/mocha_coverage/src/index.cjs
  testprojects/src/js/mocha_coverage/src/test/BUILD
  testprojects/src/js/mocha_coverage/src/test/index.test.js
Labels: category:new feature

#18626 Upgrade Pex to 2.1.131.
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/subsystems/lambdex.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#18619 narrow pex_binary files warning
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
Labels: needs-cherrypick, category:bugfix, backend: Python

#18628 narrow pex_binary files warning (Cherry-pick of #18619)
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
Labels: category:bugfix, backend: Python

#18377 Fix export-codgen with multiple output types from same input type (Cherry-pick of #18373)
  src/python/pants/backend/codegen/export_codegen_goal.py
  src/python/pants/backend/codegen/export_codegen_goal_test.py
Labels: category:bugfix

#18611 Fix a string that should have been an f-string (Cherry-pick of #18608)
  src/python/pants/backend/python/util_rules/pex_requirements.py
Labels: category:documentation

#18622 Plumb entire lockfile/internal only code through `create_pex_from_targets`
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: needs-cherrypick, category:bugfix

#18633 Fix PexPEX invocations (Cherry-pick of #18610)
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
Labels: category:bugfix, backend: Python

#18634 Plumb entire lockfile/internal only code through `create_pex_from_targets` (Cherry-pick of #18622)
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: category:bugfix

#18632 Ensure that sandboxed processes exit before their sandboxes are cleaned up
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/src/children.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/intrinsics.rs
Labels: needs-cherrypick, category:bugfix

#18636 Plumb entire lockfile/internal only code through `create_pex_from_targets` (cherry-pick of #18622)
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: category:bugfix

#18635 Plumb entire lockfile/internal only code through `create_pex_from_targets` (cherry-pick of #18622)
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: category:bugfix

#18641 Ensure that sandboxed processes exit before their sandboxes are clean…
  src/rust/engine/process_execution/src/children.rs
  src/rust/engine/process_execution/src/docker.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#18640 Ensure that sandboxed processes exit before their sandboxes are clean…
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/src/children.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix

#18642 Ensure that sandboxed processes exit before their sandboxes are clean…
  src/rust/engine/process_execution/src/children.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/src/intrinsics.rs
Labels: category:bugfix
