Repository pantsbuild/pants, pull requests merged in 2024-08, with the labels that each got.

#21244 use entire URL string as cache key for download intrinsic rule (Cherry pick of #21215)
  src/python/pants/engine/download_file_integration_test.py
  src/rust/engine/src/nodes/downloaded_file.rs
Labels: category:bugfix, release-notes:not-required

#21242 log logfile path when error opening
  src/rust/engine/logging/src/logger.rs
Labels: category:bugfix, release-notes:not-required

#21234 Auto-select complete platforms for AWS Lambda functions on ARM architecture
  build-support/bin/generate_faas_complete_platforms.py
  docs/notes/2.23.x.md
  src/python/pants/backend/awslambda/python/complete_platform_3.10-arm64.json
  src/python/pants/backend/awslambda/python/complete_platform_3.10-x86_64.json
  src/python/pants/backend/awslambda/python/complete_platform_3.11-arm64.json
  src/python/pants/backend/awslambda/python/complete_platform_3.11-x86_64.json
  src/python/pants/backend/awslambda/python/complete_platform_3.12-arm64.json
  src/python/pants/backend/awslambda/python/complete_platform_3.12-x86_64.json
  src/python/pants/backend/awslambda/python/complete_platform_3.6.json
  src/python/pants/backend/awslambda/python/complete_platform_3.7.json
  src/python/pants/backend/awslambda/python/complete_platform_3.8-arm64.json
  src/python/pants/backend/awslambda/python/complete_platform_3.8-x86_64.json
  src/python/pants/backend/awslambda/python/complete_platform_3.9-arm64.json
  src/python/pants/backend/awslambda/python/complete_platform_3.9-x86_64.json
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/awslambda/python/target_types_test.py
  src/python/pants/backend/python/util_rules/faas.py
Labels: category:new feature, backend: Python

#21176 javascript: jsconfig (tsconfig) parsing for dependency inference
  build-support/cherry_pick/package-lock.json
  build-support/cherry_pick/package.json
  docs/docs/javascript/overview/enabling-javascript-support.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/javascript/dependency_inference/rules_test.py
  src/python/pants/backend/javascript/subsystems/nodejs_infer.py
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules_test.py
  src/python/pants/backend/python/dependency_inference/subsystem.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/typescript/BUILD
  src/python/pants/backend/typescript/tsconfig.py
  src/python/pants/backend/typescript/tsconfig_test.py
  src/python/pants/core/util_rules/unowned_dependency_behavior.py
  src/python/pants/engine/internals/native_dep_inference.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/native_engine_test.py
  src/python/pants/engine/internals/scheduler.py
  src/rust/engine/dep_inference/src/javascript/import_pattern.rs
  src/rust/engine/dep_inference/src/javascript/mod.rs
  src/rust/engine/dep_inference/src/javascript/tests.rs
  src/rust/engine/protos/protos/pants/cache.proto
  src/rust/engine/protos/src/hashing.rs
  src/rust/engine/src/externs/dep_inference.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/intrinsics/dep_inference.rs
  src/rust/engine/src/types.rs
  testprojects/src/js/mocha_coverage/src/test/index.test.js
Labels: category:new feature, backend: JavaScript

#21144 Enable MockGet when using call-by-name
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21253 lookup the correct EnvironmentTarget for adhoc_tool
  src/python/pants/backend/adhoc/adhoc_tool.py
Labels: needs-cherrypick, category:internal, release-notes:not-required

#21257 lookup the correct EnvironmentTarget for adhoc_tool (Cherry-pick of #21253)
  src/python/pants/backend/adhoc/adhoc_tool.py
Labels: category:internal

#21256 disable clippy from processing generated prost code
  src/rust/engine/protos/src/lib.rs
Labels: category:internal, release-notes:not-required

#21222 Port JVM tools to use JvmToolBase and ExportableTool
  docs/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/openapi/subsystems/openapi_generator.py
  src/python/pants/backend/openapi/util_rules/generator_process.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/scala/util_rules/versions.py
  src/python/pants/jvm/goals/lockfile.py
  src/python/pants/jvm/jar_tool/jar_tool.py
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/jvm/resolve/jvm_tool_test.py
  src/python/pants/jvm/shading/jarjar.py
  src/python/pants/jvm/shading/rules.py
  src/python/pants/jvm/strip_jar/strip_jar.py
Labels: backend: JVM, category:internal

#21247 Terraform multi-platform lockfiles
  docs/docs/terraform/index.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/goals/lockfiles.py
  src/python/pants/backend/terraform/goals/lockfiles_test.py
  src/python/pants/backend/terraform/testutil.py
  src/python/pants/backend/terraform/tool.py
Labels: category:new feature, backend: Terraform

#21221 Caching for Terraform!
  docs/docs/terraform/index.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/dependencies_test.py
  src/python/pants/backend/terraform/testutil.py
  src/python/pants/backend/terraform/tool.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/engine/process.py
Labels: category:new feature, backend: Terraform

#21259 jvm resources action is not reproducible
  docs/notes/2.23.x.md
  src/python/pants/jvm/resources.py
  src/python/pants/jvm/resources_test.py
Labels: needs-cherrypick, category:bugfix

#21270 `[export].py_generated_sources_in_resolve` is an advanced option
  docs/notes/2.22.x.md
  src/python/pants/backend/python/goals/export.py
Labels: needs-cherrypick, category:internal

#21271 `[export].py_generated_sources_in_resolve` is an advanced option (Cherry-pick of #21270)
  docs/notes/2.22.x.md
  src/python/pants/backend/python/goals/export.py
Labels: category:internal

#21263 Squash errors from native options parser, treat as discrepancy
  src/python/pants/option/global_options.py
  src/python/pants/option/options.py
Labels: needs-cherrypick, category:internal

#21265 Allow int values for float options in native config file parser
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
Labels: needs-cherrypick, category:internal

#21254 adhoc/shell: capture files relative to root of sandbox for in-workspace executions
  docs/docs/using-pants/environments.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
  src/python/pants/core/util_rules/environments.py
Labels: category:bugfix

#21248 Add complete platforms for Google Cloud Functions + auto-infer based on runtime
  build-support/bin/generate_faas_complete_platforms.py
  docs/notes/2.23.x.md
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/BUILD
  src/python/pants/backend/google_cloud_function/python/complete_platform_python310_20240728_3_10_14_RC00.json
  src/python/pants/backend/google_cloud_function/python/complete_platform_python311_20240728_3_11_9_RC00.json
  src/python/pants/backend/google_cloud_function/python/complete_platform_python312_20240728_3_12_4_RC00.json
  src/python/pants/backend/google_cloud_function/python/complete_platform_python37_20240728_3_7_17_RC00.json
  src/python/pants/backend/google_cloud_function/python/complete_platform_python38_20240728_3_8_19_RC00.json
  src/python/pants/backend/google_cloud_function/python/complete_platform_python39_20240728_3_9_19_RC00.json
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
Labels: category:user api change, backend: Python

#21273 Allow int values for float options in native config file parser (Cherry-pick of #21265)
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
Labels: category:internal

#21272 Squash errors from native options parser, treat as discrepancy (Cherry-pick of #21263)
  src/python/pants/option/global_options.py
  src/python/pants/option/options.py
Labels: category:internal

#20913 allow plugins to provide "auxiliary" goals (and refactor BSP into backends)
  docs/docs/using-pants/key-concepts/backends.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/experimental/bsp/BUILD
  src/python/pants/backend/experimental/bsp/__init__.py
  src/python/pants/backend/experimental/bsp/register.py
  src/python/pants/backend/experimental/java/bsp/BUILD
  src/python/pants/backend/experimental/java/bsp/__init__.py
  src/python/pants/backend/experimental/java/bsp/register.py
  src/python/pants/backend/experimental/java/register.py
  src/python/pants/backend/experimental/scala/bsp/BUILD
  src/python/pants/backend/experimental/scala/bsp/__init__.py
  src/python/pants/backend/experimental/scala/bsp/register.py
  src/python/pants/backend/experimental/scala/register.py
  src/python/pants/bin/BUILD
  src/python/pants/bin/auxiliary_goal_integration_test.py
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/bsp/goal.py
  src/python/pants/build_graph/build_configuration.py
  src/python/pants/core/register.py
  src/python/pants/goal/auxiliary_goal.py
  src/python/pants/goal/builtins.py
  src/python/pants/init/extension_loader.py
  src/python/pants/option/arg_splitter.py
  src/python/pants/option/arg_splitter_test.py
  src/python/pants/option/options.py
  src/python/pants/option/scope.py
  src/python/pants/testutil/rule_runner.py
Labels: category:new feature

#21267 jvm resources action is not reproducible (Cherry-pick of #21259)
  src/python/pants/jvm/resources.py
  src/python/pants/jvm/resources_test.py
Labels: category:bugfix, release-notes:not-required

#21268 jvm resources action is not reproducible (Cherry-pick of #21259)
  src/python/pants/jvm/resources.py
  src/python/pants/jvm/resources_test.py
Labels: category:bugfix, release-notes:not-required

#21269 jvm resources action is not reproducible (Cherry-pick of #21259)
  src/python/pants/jvm/resources.py
  src/python/pants/jvm/resources_test.py
Labels: category:bugfix, release-notes:not-required

#21206 Add JSX support built on the JS backend
  .gitignore
  docs/notes/2.23.x.md
  src/python/pants/backend/experimental/javascript/register.py
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/javascript/goals/test.py
  src/python/pants/backend/javascript/install_node_package.py
  src/python/pants/backend/javascript/lint/prettier/rules.py
  src/python/pants/backend/javascript/target_types.py
  src/python/pants/backend/jsx/BUILD
  src/python/pants/backend/jsx/__init__.py
  src/python/pants/backend/jsx/goals/BUILD
  src/python/pants/backend/jsx/goals/__init__.py
  src/python/pants/backend/jsx/goals/tailor.py
  src/python/pants/backend/jsx/goals/tailor_test.py
  src/python/pants/backend/jsx/target_types.py
  src/python/pants/engine/target.py
  testprojects/src/js/hello_react/BUILD
  testprojects/src/js/hello_react/babel.config.json
  testprojects/src/js/hello_react/jsconfig.json
  testprojects/src/js/hello_react/package-lock.json
  testprojects/src/js/hello_react/package.json
  testprojects/src/js/hello_react/src/App.jsx
  testprojects/src/js/hello_react/src/BUILD
  testprojects/src/js/hello_react/src/index.jsx
  testprojects/src/js/hello_react/src/test/BUILD
  testprojects/src/js/hello_react/src/test/index.test.jsx
Labels: category:new feature, backend: JavaScript

#21266 Update Lambda and GCF docs for runtime inference
  docs/docs/python/integrations/aws-lambda.mdx
  docs/docs/python/integrations/google-cloud-functions.mdx
Labels: category:documentation, release-notes:not-required

#21279 Prepare 2.20.4rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21281 Prepare 2.23.0.dev6
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21280 Prepare 2.21.2rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21208 update-build-files: add support for Buildifier formatter
  docs/notes/2.23.x.md
  src/python/pants/backend/BUILD
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:new feature

#20293 typescript: add dependency inference for file imports
  docs/notes/2.23.x.md
  src/python/pants/backend/experimental/typescript/register.py
  src/python/pants/backend/typescript/README.md
  src/python/pants/backend/typescript/dependency_inference/BUILD
  src/python/pants/backend/typescript/dependency_inference/__init__.py
  src/python/pants/backend/typescript/dependency_inference/rules.py
  src/python/pants/backend/typescript/dependency_inference/rules_test.py
  src/python/pants/init/load_backends_integration_test.py
  testprojects/src/ts/frontend/config/app.ts
  testprojects/src/ts/frontend/config/dispatcher.ts
  testprojects/src/ts/frontend/config/receiver.ts
Labels: category:new feature, backend: JavaScript

#21286 internal: refactor update-build-files related rules
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
Labels: category:internal, release-notes:not-required

#21274 Add `PytestPluginSetup.extra_sys_path` for pants-plugins
  docs/notes/2.23.x.md
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/pytest_runner_integration_test.py
Labels: category:plugin api change, backend: Python

#21293 docs: mention that python requirements need to be specified using full address from the root
  src/python/pants/backend/python/subsystems/python_tool_base.py
Labels: category:documentation, release-notes:not-required

#21202 pex-cli: add [pex-cli].args option to pass arguments to the PEX process globally
  docs/notes/2.23.x.md
  src/python/pants/backend/python/goals/run_pex_binary_integration_test.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_cli_test.py
Labels: category:new feature, backend: Python

#21301 Add `TupleSequenceField` type
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:internal, release-notes:not-required

#21296 add some logging to the downloads intrinsic
  src/rust/engine/src/downloads.rs
Labels: category:internal, release-notes:not-required

#21291 Scala: Read consumed symbols from types applied to terms
  docs/notes/2.23.x.md
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: backend: JVM, category:new feature

#19308 Add nFPM backend for building system packages (only the nfpm core bits)
  docs/docs/using-pants/key-concepts/backends.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/experimental/nfpm/BUILD
  src/python/pants/backend/experimental/nfpm/__init__.py
  src/python/pants/backend/experimental/nfpm/register.py
  src/python/pants/backend/nfpm/BUILD
  src/python/pants/backend/nfpm/__init__.py
  src/python/pants/backend/nfpm/config.py
  src/python/pants/backend/nfpm/dependency_inference.py
  src/python/pants/backend/nfpm/field_sets.py
  src/python/pants/backend/nfpm/fields/BUILD
  src/python/pants/backend/nfpm/fields/__init__.py
  src/python/pants/backend/nfpm/fields/_relationships.py
  src/python/pants/backend/nfpm/fields/all.py
  src/python/pants/backend/nfpm/fields/contents.py
  src/python/pants/backend/nfpm/fields/contents_test.py
  src/python/pants/backend/nfpm/fields/scripts.py
  src/python/pants/backend/nfpm/fields/version.py
  src/python/pants/backend/nfpm/rules.py
  src/python/pants/backend/nfpm/subsystem.py
  src/python/pants/backend/nfpm/target_types.py
  src/python/pants/backend/nfpm/target_types_rules.py
  src/python/pants/backend/nfpm/target_types_test.py
  src/python/pants/backend/nfpm/util_rules/BUILD
  src/python/pants/backend/nfpm/util_rules/__init__.py
  src/python/pants/backend/nfpm/util_rules/generate_config.py
  src/python/pants/backend/nfpm/util_rules/sandbox.py
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
  src/python/pants/bin/BUILD
Labels: category:new feature

#21300 Add deb packaging and integration tests to nfpm backend
  docs/notes/2.23.x.md
  src/python/pants/backend/nfpm/dependency_inference_test.py
  src/python/pants/backend/nfpm/field_sets.py
  src/python/pants/backend/nfpm/field_sets_test.py
  src/python/pants/backend/nfpm/fields/all.py
  src/python/pants/backend/nfpm/fields/deb.py
  src/python/pants/backend/nfpm/fields/version.py
  src/python/pants/backend/nfpm/rules.py
  src/python/pants/backend/nfpm/rules_integration_test.py
  src/python/pants/backend/nfpm/target_types.py
  src/python/pants/backend/nfpm/util_rules/generate_config_test.py
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
Labels: category:new feature

#21297 Add rpm packaging to nfpm backend
  docs/notes/2.23.x.md
  src/python/pants/backend/nfpm/dependency_inference_test.py
  src/python/pants/backend/nfpm/field_sets.py
  src/python/pants/backend/nfpm/field_sets_test.py
  src/python/pants/backend/nfpm/fields/all.py
  src/python/pants/backend/nfpm/fields/contents.py
  src/python/pants/backend/nfpm/fields/rpm.py
  src/python/pants/backend/nfpm/fields/version.py
  src/python/pants/backend/nfpm/rules.py
  src/python/pants/backend/nfpm/rules_integration_test.py
  src/python/pants/backend/nfpm/target_types.py
  src/python/pants/backend/nfpm/util_rules/generate_config_test.py
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
Labels: category:new feature

#21298 Add apk packaging to nfpm backend
  docs/notes/2.23.x.md
  src/python/pants/backend/nfpm/dependency_inference_test.py
  src/python/pants/backend/nfpm/field_sets.py
  src/python/pants/backend/nfpm/field_sets_test.py
  src/python/pants/backend/nfpm/fields/all.py
  src/python/pants/backend/nfpm/fields/apk.py
  src/python/pants/backend/nfpm/fields/contents.py
  src/python/pants/backend/nfpm/fields/version.py
  src/python/pants/backend/nfpm/rules.py
  src/python/pants/backend/nfpm/rules_integration_test.py
  src/python/pants/backend/nfpm/target_types.py
  src/python/pants/backend/nfpm/util_rules/generate_config_test.py
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
Labels: category:new feature

#21299 Add archlinux packaging to nfpm backend
  docs/notes/2.23.x.md
  src/python/pants/backend/nfpm/dependency_inference_test.py
  src/python/pants/backend/nfpm/field_sets.py
  src/python/pants/backend/nfpm/field_sets_test.py
  src/python/pants/backend/nfpm/fields/all.py
  src/python/pants/backend/nfpm/fields/archlinux.py
  src/python/pants/backend/nfpm/fields/contents.py
  src/python/pants/backend/nfpm/fields/version.py
  src/python/pants/backend/nfpm/rules.py
  src/python/pants/backend/nfpm/rules_integration_test.py
  src/python/pants/backend/nfpm/target_types.py
  src/python/pants/backend/nfpm/util_rules/generate_config_test.py
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
Labels: category:new feature

#21304 add some basic unit tests for the download intrinsic
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/downloads.rs
  src/rust/engine/src/nodes/downloaded_file.rs
Labels: category:internal, release-notes:not-required

#21302 Add airflow providers default module mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
  src/python/pants/backend/python/dependency_inference/module_mapper_test.py
Labels: category:internal

#21312 upgrade to Rust v1.80.1
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/rust-toolchain
Labels: category:internal, release-notes:not-required

#21310 nfpm: Improve clarity of test names and where to packager fields
  src/python/pants/backend/nfpm/target_types.py
  src/python/pants/backend/nfpm/util_rules/generate_config_test.py
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
Labels: category:internal, release-notes:not-required

#21283 docker: support optional tools for Docker executions
  docs/notes/2.23.x.md
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_binary_test.py
Labels: category:new feature

#21315 Update targets-and-build-files.mdx
  docs/docs/using-pants/key-concepts/targets-and-build-files.mdx
Labels: category:documentation, release-notes:not-required

#21311 move BSP `QueryRule` registration out of core rules
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/bsp/rules.py
  src/python/pants/bsp/util_rules/queries.py
  src/python/pants/init/engine_initializer.py
Labels: category:internal, release-notes:not-required

#21313 Fix documentation example for pants-complete
  src/python/pants/goal/completion.py
Labels: category:documentation, release-notes:not-required

#21303 Apply InteractiveProcess restartability correctly
  src/python/pants/core/goals/deploy.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/publish.py
  src/python/pants/core/goals/repl.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_integration_test.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/engine/intrinsics.py
  src/python/pants/engine/rules.py
  src/rust/engine/src/intrinsics/interactive_process.rs
Labels: needs-cherrypick, category:internal

#21308 allow configuration of retry behavior for file downloads
  docs/notes/2.23.x.md
  src/python/pants/backend/url_handlers/s3/register.py
  src/python/pants/engine/download_file.py
  src/python/pants/engine/download_file_integration_test.py
  src/python/pants/engine/fs.py
  src/python/pants/engine/fs_test.py
  src/python/pants/option/global_options.py
  src/rust/engine/src/downloads.rs
  src/rust/engine/src/nodes/downloaded_file.rs
Labels: category:new feature

#21329 A runs-on config file
  .github/runs-on.yml
Labels: category:internal

#21330 A new AMI for aarch64 runners on runs-on
  .github/runs-on.yml
Labels: needs-cherrypick, category:internal

#21332 Update aarch64 AMI
  .github/runs-on.yml
Labels: category:internal

#21334 Custom runs-on AMI config (cherry-pick of #21329, #21332)
  .github/runs-on.yml
Labels: category:internal

#21335 Custom runs-on AMI config (cherry-pick of #21329, #21332)
  .github/runs-on.yml
Labels: category:internal

#21336 Custom runs-on AMI config (cherry-pick of #21329, #21332)
  .github/runs-on.yml
Labels: category:internal

#21325 Switch to using runs-on Linux ARM64 runners
  .github/workflows/clear_self_hosted_persistent_caches.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  pants.ci.aarch64.toml
  src/python/pants_release/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#21326 Deprecate running Pants on macOS 10.15 and macOS 11
  docs/notes/2.23.x.md
  src/python/pants/bin/pants_runner.py
  src/python/pants/option/global_options.py
  src/python/pants/util/osutil.py
Labels: category:user api change

#21337 Switch to using runs-on Linux ARM64 runners (Cherry-pick of #21325)
  .github/workflows/clear_self_hosted_persistent_caches.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  pants.ci.aarch64.toml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21338 Switch to using runs-on Linux ARM64 runners (Cherry-pick of #21325)
  .github/workflows/clear_self_hosted_persistent_caches.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  pants.ci.aarch64.toml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21339 Switch to using runs-on Linux ARM64 runners (cherry-pick of #21325)
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  pants.ci.aarch64.toml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21317 Upgrade to latest pex CLI tool
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/notes/2.23.x.md
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:user api change

#21324 Fix bug when computing implicit kwargs in @rules called by name. (cherrypick of #21038)
  src/rust/engine/src/nodes/task.rs
Labels: category:bugfix, release-notes:not-required

#21341 Enable MockGet when using call-by-name (cherry-pick of #21144)
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/python.rs
Labels: category:internal

#21340 Document our new aarch64 GHA runners.
  README.md
  docs/docs/contributions/releases/github-actions-linux-aarch64-runners.mdx
  docs/docs/contributions/releases/github-actions-macos-arm64-runners.mdx
  docs/docs/contributions/releases/index.mdx
Labels: category:internal

#21282 helm: add option to disable k8s manifest parsing for dependency inference
  docs/notes/2.23.x.md
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/dependency_inference/subsystem.py
  src/python/pants/backend/helm/utils/yaml.py
Labels: category:new feature, backend: Helm

#21344 Prepare 2.20.4
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21319 Apply InteractiveProcess restartability correctly (Cherry-pick of #21303)
  src/python/pants/core/goals/deploy.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/publish.py
  src/python/pants/core/goals/repl.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_integration_test.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/engine/intrinsics.py
  src/python/pants/engine/rules.py
  src/rust/engine/src/intrinsics/interactive_process.rs
Labels: category:internal

#21288 typescript: add support for unowned dependency behavior
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/typescript/dependency_inference/rules.py
  src/python/pants/backend/typescript/dependency_inference/rules_test.py
  testprojects/src/ts/frontend/config/app.ts
  testprojects/src/ts/frontend/config/generator.js
Labels: category:new feature, backend: JavaScript, release-notes:not-required

#21309 Allow inclusion of extra tools in sandbox for go backend
  docs/docs/go/private-modules/_category_.json
  docs/docs/go/private-modules/index.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/go/subsystems/golang.py
  src/python/pants/backend/go/util_rules/sdk.py
Labels: backend: Go, category:new feature

#21342 Revert "Update release docs to work around file watcher race condition."
  docs/docs/contributions/releases/release-process.mdx
Labels: category:internal

#21285 Deprecate implicit FaaS platform resolution
  docs/docs/contributions/development/maintenance-tasks-and-scripts.mdx
  docs/docs/python/integrations/aws-lambda.mdx
  docs/docs/python/integrations/google-cloud-functions.mdx
  docs/docs/python/overview/pex.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/awslambda/python/target_types_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
Labels: category:user api change, backend: Python

#20957 Pass python.path explicitly to lockfile generation
  docs/notes/2.23.x.md
  src/python/pants/backend/python/goals/lockfile.py
Labels: category:bugfix

#21348 minor 2.22.x release notes copy edits
  docs/notes/2.22.x.md
Labels: needs-cherrypick, category:internal

#21351 minor 2.22.x release notes copy edits (Cherry-pick of #21348)
  docs/notes/2.22.x.md
Labels: category:internal

#21354 remove leftover debug prints
  src/python/pants/backend/docker/util_rules/docker_binary.py
Labels: category:internal, release-notes:not-required

#21355 Always run setuptools_scm in the local environment (cherry-pick of #21188)
  src/python/pants/backend/python/util_rules/vcs_versioning.py
Labels: category:bugfix, release-notes:not-required

#21353 Run all vcs versioning processes locally
  docs/notes/2.22.x.md
  docs/notes/2.23.x.md
  src/python/pants/backend/python/util_rules/vcs_versioning.py
Labels: needs-cherrypick, category:internal

#21352 Explain rare quoting differences between the options parsers
  src/python/pants/option/options.py
Labels: needs-cherrypick, category:internal

#21357 Run all vcs versioning processes locally (cherrypick of #21353)
  docs/notes/2.22.x.md
  src/python/pants/backend/python/util_rules/vcs_versioning.py
Labels: category:internal

#21356 Explain rare quoting differences between the options parsers (Cherry-pick of #21352)
  src/python/pants/option/options.py
Labels: category:internal

#21358 Prepare 2.22.0rc3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21361 Terraform: downgrade python-hcl2 from 4.3.2 to 4.3.0 to work around parsing issues
  docs/notes/2.23.x.md
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/hcl2.lock
Labels: needs-cherrypick, category:bugfix

#21363 docs: fix a round of broken link anchors
  docs/docs/docker/index.mdx
  docs/docs/getting-started/incremental-adoption.mdx
  docs/docs/jvm/java-and-scala.mdx
  docs/docs/jvm/kotlin.mdx
  docs/docs/python/goals/check.mdx
  docs/docs/python/goals/test.mdx
  docs/docs/python/integrations/aws-lambda.mdx
  docs/docs/python/overview/linters-and-formatters.mdx
  docs/docs/python/overview/lockfiles.mdx
  docs/docs/using-pants/advanced-target-selection.mdx
  docs/docs/using-pants/key-concepts/backends.mdx
  docs/docs/using-pants/restricted-internet-access.mdx
  docs/docs/using-pants/troubleshooting-common-issues.mdx
  docs/docs/using-pants/using-pants-in-ci.mdx
  docs/docs/using-pants/validating-dependencies.mdx
Labels: needs-cherrypick, category:documentation, release-notes:not-required

#21364 Terraform: downgrade python-hcl2 from 4.3.2 to 4.3.0 to work around parsing issues (Cherry-pick of #21361)
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/hcl2.lock
Labels: category:bugfix

#21368 [Call-by-name] JVM linters
  docs/notes/2.23.x.md
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/scala/lint/scalafix/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
Labels: category:internal
