Repository pantsbuild/pants, pull requests merged in 2024-10, with the labels that each got.

#21460 upgrade `pin-project` crate
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal, release-notes:not-required

#21461 upgrade `shell-quote` crate to v0.7
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/workspace_tests.rs
Labels: category:internal, release-notes:not-required

#21464 pyo3: use `FromPyObject::extract_bound`
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21465 PyO3: migrate `PyTypes` and `TypeId` to use `Bound` instead of `&PyAny`
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/nodes/task.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21466 remove extraneous request logging
  src/rust/engine/grpc_util/src/channel.rs
Labels: category:internal, release-notes:not-required

#21469 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/externs/dep_inference.rs`
  src/rust/engine/src/externs/dep_inference.rs
Labels: category:internal, release-notes:not-required

#21470 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/externs/engine_aware.rs`
  src/rust/engine/src/externs/engine_aware.rs
  src/rust/engine/src/nodes/mod.rs
  src/rust/engine/src/nodes/task.rs
Labels: category:internal, release-notes:not-required

#21473 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/externs/options.rs`
  src/rust/engine/src/externs/options.rs
Labels: category:internal, release-notes:not-required

#21474 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/externs/process.rs`
  src/rust/engine/src/externs/process.rs
Labels: category:internal, release-notes:not-required

#21471 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/externs/nailgun.rs`
  src/rust/engine/src/externs/nailgun.rs
Labels: category:internal, release-notes:not-required

#21472 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/externs/testutil.rs`
  src/rust/engine/src/externs/testutil.rs
Labels: category:internal, release-notes:not-required

#21475 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/externs/stdio.rs`
  src/rust/engine/src/externs/stdio.rs
Labels: category:internal, release-notes:not-required

#21477 PyO3: migrate `PyModule` setup to `Bound` smart pointer
  src/rust/engine/src/externs/address.rs
  src/rust/engine/src/externs/dep_inference.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/nailgun.rs
  src/rust/engine/src/externs/options.rs
  src/rust/engine/src/externs/pantsd.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/externs/scheduler.rs
  src/rust/engine/src/externs/target.rs
  src/rust/engine/src/externs/testutil.rs
  src/rust/engine/src/externs/workunits.rs
  src/rust/engine/src/intrinsics/dep_inference.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/intrinsics/docker.rs
  src/rust/engine/src/intrinsics/interactive_process.rs
  src/rust/engine/src/intrinsics/mod.rs
  src/rust/engine/src/intrinsics/process.rs
  src/rust/engine/src/intrinsics/values.rs
Labels: category:internal, release-notes:not-required

#21476 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/externs/target.rs`
  src/rust/engine/src/externs/target.rs
Labels: category:internal, release-notes:not-required

#21468 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/externs/address.rs`
  src/rust/engine/src/externs/address.rs
Labels: category:internal, release-notes:not-required

#21467 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/externs/fs.rs`
  src/rust/engine/src/externs/fs.rs
Labels: category:internal, release-notes:not-required

#21479 PyO3: introduce `getattr_bound` helper (and friends) to ease migration to `Bound`
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/nodes/downloaded_file.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21480 Support trailing global flags in the native parser.
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
Labels: needs-cherrypick, category:bugfix, release-notes:not-required

#21481 PyO3: migrate `src/rust/engine/src/nodes/execute_process.rs` to `Bound` smart pointer (and add more helpers)
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/nodes/execute_process.rs
  src/rust/engine/src/nodes/mod.rs
Labels: category:internal, release-notes:not-required

#21482 PyO3: migrate to `Bound` smart pointer for `src/rust/engine/src/nodes/task.rs`
  src/rust/engine/src/nodes/task.rs
Labels: category:internal, release-notes:not-required

#21483 PyO3: migrate another spot in `src/rust/engine/src/externs/options.rs`
  src/rust/engine/src/externs/options.rs
Labels: category:internal, release-notes:not-required

#21484 PyO3: migrate to `Bound` for `src/rust/engine/src/intrinsics/docker.rs`
  src/rust/engine/src/intrinsics/docker.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21485 Support trailing global flags in the native parser. (Cherry-pick of #21480)
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
Labels: category:bugfix, release-notes:not-required

#21486 Support trailing global flags in the native parser. (Cherry-pick of #21480)
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
Labels: category:bugfix, release-notes:not-required

#21489 PyO3: migrate to `Bound` in parts of `externs/interface.rs`
  src/rust/engine/src/externs/interface.rs
Labels: category:internal, release-notes:not-required

#21490 PyO3: migrate various externs files to `Bound` smart pointer
  src/rust/engine/src/externs/engine_aware.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/intrinsics/interactive_process.rs
  src/rust/engine/src/nodes/snapshot.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21495 PyO3: migrate functions using a RefCell and mutable borrows to `Bound` smart pointer
  src/rust/engine/src/externs/interface.rs
Labels: category:internal, release-notes:not-required

#21494 PyO3: migrate more of `externs/interface.rs` to `Bound` smart pointer
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/nodes/mod.rs
Labels: category:internal, release-notes:not-required

#21488 Use LnBinary instead of hardcoded /bin/ln in jvm.sh
  docs/notes/2.24.x.md
  src/python/pants/jvm/jdk_rules.py
Labels: backend: JVM, category:bugfix

#21498 PyO3: continue porting to the `Bound` smart pointer (including `TypeId` and `Value`)
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/options.rs
  src/rust/engine/src/interning.rs
  src/rust/engine/src/intrinsics/dep_inference.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/intrinsics/interactive_process.rs
  src/rust/engine/src/intrinsics/process.rs
  src/rust/engine/src/nodes/downloaded_file.rs
  src/rust/engine/src/nodes/execute_process.rs
  src/rust/engine/src/nodes/mod.rs
  src/rust/engine/src/nodes/snapshot.rs
  src/rust/engine/src/nodes/task.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21504 go: recognize `-fullpath` test binary option
  docs/notes/2.24.x.md
  src/python/pants/backend/go/goals/test.py
Labels: category:internal

#21499 PyO3: complete `Bound` migration and disable `gil-refs` feature on `pyo3` crate
  src/rust/engine/Cargo.toml
  src/rust/engine/src/externs/address.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/nailgun.rs
  src/rust/engine/src/externs/options.rs
  src/rust/engine/src/externs/scheduler.rs
  src/rust/engine/src/externs/target.rs
  src/rust/engine/src/intrinsics/interactive_process.rs
  src/rust/engine/src/nodes/execute_process.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21500 PyO3: upgrade to v0.22.x
  docs/notes/2.24.x.md
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/rules.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/externs/address.rs
  src/rust/engine/src/externs/dep_inference.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/options.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/nodes/execute_process.rs
  src/rust/engine/src/nodes/session_values.rs
  src/rust/engine/src/session.rs
Labels: category:internal

#21512 restore string borrowing logic for `AddressInput::parse`
  src/rust/engine/Cargo.lock
  src/rust/engine/src/externs/address.rs
Labels: category:internal, release-notes:not-required

#21496 Prepare 2.22.1rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21493 Prepare 2.23.0rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21492 Prepare 2.24.0.dev1
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21510 Upgrade `pyright` to version 1.1.383
  docs/notes/2.24.x.md
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
Labels: category:internal, backend: Python

#21511 Upgrade rust cache action.
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21513 upgrade the `strum` crate
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/client/src/main.rs
Labels: category:internal, release-notes:not-required

#21258 Make ExternalTool exportable
  docs/docs/using-pants/setting-up-an-ide.mdx
  docs/docs/writing-plugins/common-plugin-tasks/add-a-formatter.mdx
  docs/docs/writing-plugins/common-plugin-tasks/add-a-linter.mdx
  docs/docs/writing-plugins/common-plugin-tasks/add-codegen.mdx
  docs/docs/writing-plugins/common-plugin-tasks/allowing-tool-export.mdx
  docs/notes/2.24.x.md
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/backend/cc/subsystems/compiler.py
  src/python/pants/backend/codegen/protobuf/go/rules.py
  src/python/pants/backend/codegen/protobuf/java/rules.py
  src/python/pants/backend/codegen/protobuf/lint/buf/register.py
  src/python/pants/backend/codegen/protobuf/protoc.py
  src/python/pants/backend/codegen/protobuf/python/rules.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/cue/goals/fix.py
  src/python/pants/backend/cue/goals/lint.py
  src/python/pants/backend/cue/subsystem.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/experimental/helm/check/kubeconform/register.py
  src/python/pants/backend/experimental/helm/register.py
  src/python/pants/backend/go/lint/golangci_lint/rules.py
  src/python/pants/backend/helm/subsystems/unittest.py
  src/python/pants/backend/makeself/subsystem.py
  src/python/pants/backend/nfpm/subsystem.py
  src/python/pants/backend/project_info/count_loc.py
  src/python/pants/backend/python/providers/pyenv/rules.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/shell/subsystems/shunit2.py
  src/python/pants/backend/terraform/lint/tfsec/rules.py
  src/python/pants/backend/terraform/tool.py
  src/python/pants/backend/tools/taplo/rules.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/export_integration_test.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/resolves.py
  src/python/pants/core/util_rules/external_tool.py
  src/python/pants/core/util_rules/external_tool_test.py
  src/python/pants/jvm/resolve/coursier_setup.py
  src/python/pants/testutil/rule_runner.py
Labels: category:new feature

#21225 Remove GenerateToolLockfileSentinel
  docs/notes/2.24.x.md
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/generate_lockfiles_test.py
  src/python/pants/jvm/resolve/jvm_tool.py
Labels: category:plugin api change

#21520 upgrade to PyO3 v0.22.4
  src/rust/engine/Cargo.lock
Labels: category:internal, release-notes:not-required

#21516 delete pymupdf from `default_module_mapping.py`
  docs/notes/2.24.x.md
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:user api change

#21531 Update the ARM64 CI AMI.
  .github/runs-on.yml
  docs/docs/contributions/releases/github-actions-linux-aarch64-runners.mdx
Labels: needs-cherrypick, category:internal

#21535 Update the ARM64 CI AMI. (Cherry-pick of #21531)
  .github/runs-on.yml
Labels: category:internal

#21536 Update the ARM64 CI AMI. (Cherry-pick of #21531)
  .github/runs-on.yml
Labels: category:internal

#21533 Update the ARM64 CI AMI. (Cherry-pick of #21531)
  .github/runs-on.yml
  docs/docs/contributions/releases/github-actions-linux-aarch64-runners.mdx
Labels: category:internal

#21534 Change arm64 CI instance label
  .github/workflows/clear_self_hosted_persistent_caches.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#21540 Constrain the ICs in the coverage py integration tests.
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: needs-cherrypick, category:internal

#21541 Constrain the ICs in the coverage py integration tests. (Cherry-pick of #21540)
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: category:internal

#21542 Constrain the ICs in the coverage py integration tests. (Cherry-pick of #21540)
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: category:internal

#21543 Constrain the ICs in the coverage py integration tests. (Cherry-pick of #21540)
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: category:internal

#21544 Fix the remaining coverage py integration tests
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: needs-cherrypick, category:internal

#21548 Fix the remaining coverage py integration tests (Cherry-pick of #21544)
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: category:internal

#21547 Fix the remaining coverage py integration tests (Cherry-pick of #21544)
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: category:internal

#21546 Fix the remaining coverage py integration tests (Cherry-pick of #21544)
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: category:internal

#21539 Change arm64 CI instance label (Cherry-pick of #21534)
  .github/workflows/clear_self_hosted_persistent_caches.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21538 Change arm64 CI instance label (Cherry-pick of #21534)
  .github/workflows/clear_self_hosted_persistent_caches.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21515 Remove direct pex imports from the codebase
  src/python/pants/backend/python/util_rules/BUILD
  src/python/pants/core/subsystems/python_bootstrap.py
  tests/python/pants_test/init/test_plugin_resolver.py
Labels: category:internal, backend: Python

#21545 Upgrade Pex CLI default to latest release
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/notes/2.24.x.md
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:internal

#21557 Prepare 2.24.0.dev2
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21563 golang: support `all:` prefix for `go:embed` directives (Cherry-pick of #21559)
  docs/notes/2.23.x.md
  src/python/pants/backend/go/go_sources/embedcfg/main.go
  src/python/pants/backend/go/util_rules/embed_integration_test.py
Labels: category:bugfix

#21564 golang: support `all:` prefix for `go:embed` directives (Cherry-pick of #21559)
  docs/notes/2.22.x.md
  src/python/pants/backend/go/go_sources/embedcfg/main.go
  src/python/pants/backend/go/util_rules/embed_integration_test.py
Labels: category:bugfix

#21570 upgrade to PyO3 v0.22.5
  src/rust/engine/Cargo.lock
Labels: category:internal, release-notes:not-required

#21459 Document missing binary as common issue
  docs/docs/contributions/releases/release-process.mdx
  docs/docs/using-pants/key-concepts/options.mdx
  docs/docs/using-pants/troubleshooting-common-issues.mdx
Labels: category:documentation, release-notes:not-required

#21555 remove category label requirement from PRs
  .github/workflows/test.yaml
  docs/docs/contributions/index.mdx
  src/python/pants_release/changelog.py
  src/python/pants_release/changelog_test.py
  src/python/pants_release/generate_github_workflows.py
Labels: release-notes:not-required

#21568 use explicit setup-python versions over implicit expose-
  .github/workflows/cache_comparison.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21571 upgrade to MyPy v1.13.0
  3rdparty/python/mypy-requirements.txt
  3rdparty/python/mypy.lock
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/project_info/dependencies_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/base/deprecated_test.py
  src/python/pants/bsp/goal.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/unions_test.py
  src/python/pants/option/option_types.py
  src/python/pants/testutil/rule_runner.py
Labels: category:internal, release-notes:not-required

#21575 mypy: lint scripts without extensions
  docs/notes/2.24.x.md
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
Labels: category:bugfix

#21580 tests: make cas testutil functions async
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/action_cache_tests.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store_tests.rs
  src/rust/engine/src/externs/testutil.rs
  src/rust/engine/testutil/local_cas/Cargo.toml
  src/rust/engine/testutil/local_cas/src/main.rs
  src/rust/engine/testutil/local_execution_server/Cargo.toml
  src/rust/engine/testutil/local_execution_server/src/main.rs
  src/rust/engine/testutil/mock/src/cas.rs
  src/rust/engine/testutil/mock/src/execution_server.rs
Labels: category:internal, release-notes:not-required

#21583 tests: remove instance of `std::net::TcpListener`
  src/rust/engine/testutil/mock/src/execution_server.rs
Labels: category:internal, release-notes:not-required

#21584 Prepare 2.22.1rc2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21585 Prepare 2.21.2rc2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21586 use an `EnvironmentTarget` helper instead of direct `isinstance` checks
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/asdf.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/search_paths.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:internal, release-notes:not-required

#21582 Install Pythons in "Build wheels (macOS12-x86_64)" jobs too
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21589 Upgrade to fixed rust-cache action.
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21237 Run ruff as an external tool, not via Python/PEX
  build-support/bin/generate_builtin_lockfiles.py
  docs/notes/2.24.x.md
  src/python/pants/backend/build_files/fmt/ruff/integration_test.py
  src/python/pants/backend/build_files/fmt/ruff/register.py
  src/python/pants/backend/python/lint/ruff/BUILD
  src/python/pants/backend/python/lint/ruff/check/rules.py
  src/python/pants/backend/python/lint/ruff/common.py
  src/python/pants/backend/python/lint/ruff/format/rules.py
  src/python/pants/backend/python/lint/ruff/ruff.lock
  src/python/pants/backend/python/lint/ruff/rules_integration_test.py
  src/python/pants/backend/python/lint/ruff/subsystem.py
  src/python/pants/core/goals/update_build_files.py
Labels: category:user api change

#21561 Ensure deterministic `jvm` lockfiles
  docs/notes/2.24.x.md
  src/python/pants/jvm/resolve/coursier_fetch.py
Labels: needs-cherrypick, category:bugfix

#21590 Ensure deterministic `jvm` lockfiles (Cherry-pick of #21561)
  src/python/pants/jvm/resolve/coursier_fetch.py
Labels: category:bugfix, release-notes:not-required

#21591 Ensure deterministic `jvm` lockfiles (Cherry-pick of #21561)
  src/python/pants/jvm/resolve/coursier_fetch.py
Labels: category:bugfix, release-notes:not-required

#21588 Edit release notes for 2.23
  docs/notes/2.23.x.md
Labels: needs-cherrypick, release-notes:not-required

#21593 Prepare 2.22.1rc3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21592 Mention our sponsors in the release notes.
  docs/notes/2.23.x.md
  docs/notes/2.24.x.md
Labels: needs-cherrypick, category:internal

#21594 Edit release notes for 2.23 (Cherry-pick of #21588)
  docs/notes/2.23.x.md
Labels: category:internal

#21597 Mention our sponsors in the release notes. (#21592)
  docs/notes/2.23.x.md
Labels: category:internal

#21598 Prepare 2.23.0rc2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep
