Repository pantsbuild/pants, pull requests merged in 2024-12, with the labels that each got.

#21698 A global lock on side effects into the workspace.
  docs/notes/2.24.x.md
  src/rust/engine/src/externs/interface.rs
Labels: needs-cherrypick, category:bugfix

#21694 Fix: Creating ZIP archives with no file extension
  docs/notes/2.25.x.md
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/archive_test.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: needs-cherrypick, category:bugfix

#21708 A global lock on side effects into the workspace. (Cherry-pick of #21698)
  docs/notes/2.24.x.md
  src/rust/engine/src/externs/interface.rs
Labels: category:bugfix

#21721 miscellaneous 2.24 release notes copy edits
  docs/notes/2.24.x.md
Labels: needs-cherrypick

#21715 enable C420: Unnecessary dict comprehension
  build-support/flake8/.flake8
  src/python/pants/backend/debian/target_types_test.py
  src/python/pants/backend/nfpm/dependency_inference_test.py
  src/python/pants/backend/nfpm/rules_integration_test.py
  src/python/pants/backend/nfpm/util_rules/generate_config_test.py
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
  src/python/pants/backend/python/util_rules/ancestor_files_test.py
  src/python/pants/backend/shell/lint/shfmt/subsystem.py
  src/python/pants/backend/visibility/rule_types_test.py
  src/python/pants/core/util_rules/source_files_test.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/testutil/rule_runner.py
  src/python/pants/util/ordered_set.py
Labels: release-notes:not-required

#21722 add Platinum support callout to upcoming release notes
  docs/notes/2.24.x.md
  docs/notes/2.25.x.md
Labels: needs-cherrypick

#21726 Deprecate using scie-pants older than 0.12.2, improve upgrade docs
  docs/docs/getting-started/installing-pants.mdx
  docs/notes/2.24.x.md
  docs/notes/2.25.x.md
  src/python/pants/bin/pants_runner.py
Labels: needs-cherrypick

#21705 Fix: Creating ZIP archives with no file extension (Cherry-pick of #21694)
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/archive_test.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:bugfix, release-notes:not-required

#21735 fix: Handle buildx output with BUILDX_NO_DEFAULT_ATTESTATIONS=1
  docs/notes/2.22.x.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
Labels: needs-cherrypick, category:bugfix, backend: Docker

#21712 resolve Python 3.11 importlib deprecation WARNings
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/jvm/resolve/coursier_fetch.py
Labels: release-notes:not-required

#21738 fix: Handle buildx output with BUILDX_NO_DEFAULT_ATTESTATIONS=1 (Cherry-pick of #21735)
  docs/notes/2.22.x.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
Labels: category:bugfix

#21737 fix: Handle buildx output with BUILDX_NO_DEFAULT_ATTESTATIONS=1 (Cherry-pick of #21735)
  docs/notes/2.22.x.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
Labels: category:bugfix

#21725 Fix bad `__hash__` implementations.
  docs/notes/2.24.x.md
  docs/notes/2.25.x.md
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/engine/collection.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/mapper.py
  src/python/pants/engine/internals/mapper_test.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/synthetic_targets.py
  src/python/pants/engine/internals/target_adaptor.py
  src/python/pants/engine/target.py
Labels: category:internal

#21695 Port the cli aliasing feature to rust
  pants-plugins/internal_plugins/releases/register.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/help/help_formatter_test.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_tools_test.py
  src/python/pants/option/native_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_bootstrapper_test.py
  src/python/pants/option/options_test.py
  src/rust/engine/Cargo.lock
  src/rust/engine/client/src/client_tests.rs
  src/rust/engine/client/src/main.rs
  src/rust/engine/options/Cargo.toml
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/cli_alias.rs
  src/rust/engine/options/src/cli_alias_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/pantsd/src/pantsd_testing.rs
  src/rust/engine/src/externs/options.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: category:internal

#21710 filter known PBS release by the PBS-specific release tag
  docs/notes/2.25.x.md
  src/python/pants/backend/python/providers/python_build_standalone/constraints.py
  src/python/pants/backend/python/providers/python_build_standalone/constraints_test.py
  src/python/pants/backend/python/providers/python_build_standalone/rules.py
  src/python/pants/backend/python/providers/python_build_standalone/rules_integration_test.py
  src/python/pants/backend/python/providers/python_build_standalone/scripts/generate_urls.py
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:new feature

#21743 Remove the legacy CLI Alias code.
  src/python/pants/option/alias.py
  src/python/pants/option/alias_test.py
Labels: category:internal

#21749 Install Python headers in the ARM64 wheel-building container.
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21733 Prepare 2.25.0.dev1
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21750 Remove long-obsolete cruft from options registration.
  src/python/pants/option/options.py
  src/python/pants/option/subsystem.py
Labels: category:internal

#21740 feat: add devcontainer
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/postCreateCommand.sh
  .devcontainer/postStartCommand.sh
  docs/docs/contributions/development/setting-up-pants.mdx
Labels: category:internal

#21717 bump timeout for js export tests
  src/python/pants/backend/javascript/goals/BUILD
Labels: release-notes:not-required

#21756 fix flaky failure in `export_integration_test.py`
  src/python/pants/backend/python/goals/export_integration_test.py
Labels: category:internal, release-notes:not-required

#21745 fix issue with duplicated `BinaryPath` instances passed to `BinaryShimsRequest`
  docs/notes/2.25.x.md
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/core/util_rules/system_binaries_test.py
Labels: needs-cherrypick, category:bugfix

#21758 fix issue with duplicated `BinaryPath` instances passed to `BinaryShimsRequest` (Cherry-pick of #21745)
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/core/util_rules/system_binaries_test.py
Labels: category:bugfix, release-notes:not-required

#21759 fix issue with duplicated `BinaryPath` instances passed to `BinaryShimsRequest` (Cherry pick of #21745)
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/core/util_rules/system_binaries_test.py
Labels: category:bugfix, release-notes:not-required

#21753 only emit a `mkdir` into remote execution wrapper for non-empty paths
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/tests.rs
Labels: needs-cherrypick, category:bugfix, release-notes:not-required

#21760 only emit a `mkdir` into remote execution wrapper for non-empty paths (Cherry-pick of #21753)
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/tests.rs
Labels: category:bugfix, release-notes:not-required

#21761 PyO3: Upgrade to v0.23.3
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal, release-notes:not-required

#21762 Upgrade to Pex 2.27.1
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/notes/2.25.x.md
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:bugfix

#21765 Prepare 2.24.0rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21714 truth in advertising for all major Python versions
  src/python/pants/backend/python/lint/docformatter/rules_integration_test.py
  src/python/pants/testutil/python_interpreter_selection.py
Labels: release-notes:not-required

#21766 Use OptionInfo type for option registration args/kwargs.
  src/python/pants/core/util_rules/environments.py
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/option/global_options.py
  src/python/pants/option/native_options.py
  src/python/pants/option/option_types.py
  src/python/pants/option/option_types_test.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_test.py
  src/python/pants/option/registrar.py
  src/python/pants/option/subsystem.py
Labels: category:internal

#21768 Prepare 2.23.1rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21739 infer the PBS release tag from the user-supplied URLs
  docs/notes/2.25.x.md
  src/python/pants/backend/python/providers/python_build_standalone/rules.py
  src/python/pants/backend/python/providers/python_build_standalone/rules_integration_test.py
Labels: category:new feature

#21767 Prepare 2.25.0.dev2
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21772 Get rid of bootstrap_option_values in Options instance.
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/option/global_options.py
  src/python/pants/option/options.py
  src/python/pants/pantsd/pants_daemon_core.py
Labels: category:internal

#21776 store all known releases for Python Build Standalone known versions
  docs/notes/2.25.x.md
  src/python/pants/backend/python/providers/python_build_standalone/rules.py
  src/python/pants/backend/python/providers/python_build_standalone/rules_integration_test.py
  src/python/pants/backend/python/providers/python_build_standalone/scripts/generate_urls.py
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:bugfix

#21770 Prepare 2.23.1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21316 Support Python codegen for the OpenAPI backend
  docs/notes/2.25.x.md
  src/python/pants/backend/experimental/openapi/codegen/python/BUILD
  src/python/pants/backend/experimental/openapi/codegen/python/__init__.py
  src/python/pants/backend/experimental/openapi/codegen/python/register.py
  src/python/pants/backend/openapi/codegen/java/rules.py
  src/python/pants/backend/openapi/codegen/python/BUILD
  src/python/pants/backend/openapi/codegen/python/__init__.py
  src/python/pants/backend/openapi/codegen/python/extra_fields.py
  src/python/pants/backend/openapi/codegen/python/generate.py
  src/python/pants/backend/openapi/codegen/python/generate_integration_test.py
  src/python/pants/backend/openapi/codegen/python/openapi.test.lock
  src/python/pants/backend/openapi/codegen/python/package_mapper.py
  src/python/pants/backend/openapi/codegen/python/rules.py
  src/python/pants/backend/openapi/util_rules/generator_process.py
  src/python/pants/backend/openapi/util_rules/generator_process_test.py
  src/python/pants/backend/python/target_types.py
Labels: category:new feature, backend: Python, backend: OpenAPI

#21791 E721: Do not compare types, use 'isinstance()'
  build-support/flake8/.flake8
  src/python/pants/backend/python/util_rules/package_dists_test.py
  src/python/pants/engine/collection.py
  src/python/pants/option/ranked_value.py
  src/python/pants/option/subsystem.py
  src/python/pants/util/memo_test.py
Labels: release-notes:not-required

#21795 Prepare 2.25.0.dev3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21797 Fix typo in docs.
  docs/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx
  src/python/pants/core/util_rules/environments_test.py
Labels: category:documentation, release-notes:not-required

#21789 infer all PBS-related metadata from the URL
  docs/notes/2.25.x.md
  src/python/pants/backend/python/providers/python_build_standalone/rules.py
  src/python/pants/backend/python/providers/python_build_standalone/rules_integration_test.py
  src/python/pants/backend/python/providers/python_build_standalone/rules_test.py
Labels: category:new feature

#21784 Simplify OptionsBootstrapper
  pants-plugins/internal_plugins/releases/register.py
  src/python/pants/bin/daemon_pants_runner.py
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/bin/pants_runner.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/init/options_initializer.py
  src/python/pants/option/global_options_test.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_bootstrapper_test.py
  src/python/pants/option/options_test.py
  src/python/pants/option/subsystem_test.py
  src/python/pants/pantsd/pants_daemon.py
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
  tests/python/pants_test/init/test_options_initializer.py
Labels: category:internal

#21800 Remove the legacy Python config implementation.
  src/python/pants/engine/fs.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/option/BUILD
  src/python/pants/option/config.py
  src/python/pants/option/config_test.py
  src/python/pants/option/native_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_test.py
  src/python/pants/testutil/pants_integration_test.py
Labels: category:internal

#21801 use shell quoting for directories in remote execution wrapper script
  src/rust/engine/Cargo.lock
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/tests.rs
Labels: category:internal, release-notes:not-required

#21802 scrape the `20241219` release of PBS
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal, release-notes:not-required

#21803 support `{chroot}` for program arguments in remote execution
  docs/notes/2.25.x.md
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/tests.rs
Labels: category:internal
