Repository pantsbuild/pants, pull requests merged in 2024-03, with the labels that each got.

#20628 Fix use of deprecated fields on target generators.
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
Labels: category:bugfix

#20635 Prepare 2.18.3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20636 Prepare 2.19.1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20637 Prepare 2.21.0.dev1
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20571 enhancement: Allow fromfile config value to be optional
  docs/docs/using-pants/key-concepts/options.mdx
  src/python/pants/option/options.py
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
Labels: category:new feature

#20634 Support @fromfile option values in the Rust options parser.
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/options/Cargo.toml
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/env_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
Labels: category:internal

#20638 Set `BLACK_CACHE_DIR` variable to point to folder in sandbox
  src/python/pants/backend/python/lint/black/rules.py
Labels: category:internal, backend: Python

#20640 Remove force flags from release tagging & confirm commit before doing so
  src/python/pants_release/release.py
Labels: needs-cherrypick, category:internal

#20647 Upgrade Ruff to v0.3.0
  build-support/bin/generate_builtin_lockfiles.py
  src/python/pants/backend/python/lint/ruff/ruff.lock
Labels: category:user api change, backend: Python

#20644 Remove force flags from release tagging & confirm commit before doing so (Cherry-pick of #20640)
  src/python/pants_release/release.py
Labels: category:internal

#20645 Remove force flags from release tagging & confirm commit before doing so (Cherry-pick of #20640)
  src/python/pants_release/release.py
Labels: category:internal

#20653 upgrade Pex to 2.2.1 (Cherry-pick of #20587, etc.)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:internal

#20652 upgrade Pex to 2.2.1 (Cherry-pick of #20587)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:internal

#20655 Fix the exception sink test error message check.
  src/python/pants/base/exception_sink_test.py
Labels: category:internal

#20656 Get rid of a TestCase class.
  src/python/pants/option/options_test.py
Labels: category:internal

#20633 Docker: fix base image dependency inference for parametrized targets.
  src/python/pants/backend/docker/subsystems/dockerfile_parser_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_wrapper_script.py
Labels: needs-cherrypick, category:bugfix

#20658 Docker: fix base image dependency inference for parametrized targets. (Cherry-pick of #20633)
  src/python/pants/backend/docker/subsystems/dockerfile_parser_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_wrapper_script.py
Labels: category:bugfix

#20657 Docker: fix base image dependency inference for parametrized targets. (Cherry-pick of #20633)
  src/python/pants/backend/docker/subsystems/dockerfile_parser_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_wrapper_script.py
Labels: category:bugfix

#20660 Tighten up options tests
  src/python/pants/option/options_test.py
Labels: category:internal

#20661 Prepare 2.20.0rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20662 Prepare 2.21.0.dev2
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20600 Docker: Support multiple `cache_from` values for `docker_image`.
  docs/docs/docker/index.mdx
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
Labels: category:new feature, backend: Docker

#20663 Add Pyright, Pytype and Ruff to Python overview docs
  docs/docs/python/overview/index.mdx
Labels: category:documentation, backend: Python

#20625 add new default mappings for databricks
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#20669 add module mapping for cloud-sql-python-connector
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#20677 Support Go versioning with patch
  src/python/pants/backend/go/util_rules/go_bootstrap.py
Labels: backend: Go, category:bugfix

#20681 upgrade `pyo3` crate to v0.20.3
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal

#20683 Prepare 2.21.0.dev3
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20680 fix doc link
  docs/docs/using-pants/setting-up-an-ide.mdx
Labels: category:documentation

#20682 refactor intrinics implementation into separate sub-modules
  src/rust/engine/src/intrinsics.rs
  src/rust/engine/src/intrinsics/dep_inference.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/intrinsics/docker.rs
  src/rust/engine/src/intrinsics/interactive_process.rs
  src/rust/engine/src/intrinsics/mod.rs
  src/rust/engine/src/intrinsics/process.rs
  src/rust/engine/src/intrinsics/values.rs
Labels: category:internal

#19478 `complete` built-in goal which can be called by completion scripts (or IDEs) to process a list of commands
  src/python/pants/goal/BUILD
  src/python/pants/goal/builtins.py
  src/python/pants/goal/completion.py
  src/python/pants/goal/completion_integration_test.py
  src/python/pants/goal/pants-completion.bash
  src/python/pants/goal/pants-completion.zsh
  src/python/pants/option/options.py
Labels: category:internal

#20649 Core: Fix `__defaults__` to also apply for generated file targets.
  .gitignore
  docs/docs/using-pants/key-concepts/targets-and-build-files.mdx
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/target.py
Labels: category:bugfix

#20678 add default module mapping for delta-spark
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#20685 update docs to use proper docker sha256 format
  docs/docs/using-pants/environments.mdx
Labels: category:documentation

#20665 docs: update docs for debian_package target
  src/python/pants/backend/debian/target_types.py
Labels: category:documentation

#20690 Link to rate limit issue in GitHub Actions remote cache provider docs
  docs/docs/using-pants/remote-caching-and-execution/remote-caching.mdx
Labels: needs-cherrypick, category:documentation

#20692 Link to rate limit issue in GitHub Actions remote cache provider docs (Cherry-pick of #20690)
  docs/docs/using-pants/remote-caching-and-execution/remote-caching.mdx
Labels: category:documentation

#20688 Update welcome-to-pants.mdx - fix link to sample users
  docs/docs/introduction/welcome-to-pants.mdx
Labels: category:documentation

#20693 docker buildx output format changed in 0.13.1
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
Labels: category:bugfix

#20696 Switch OptionId from a tuple struct to named fields.
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/id.rs
  src/rust/engine/options/src/id_tests.rs
Labels: category:internal

#20606 Add test retries to remaining backends
  docs/docs/go/index.mdx
  docs/docs/helm/index.mdx
  docs/docs/jvm/java-and-scala.mdx
  docs/docs/jvm/kotlin.mdx
  docs/docs/python/goals/test.mdx
  docs/docs/shell/index.mdx
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/test/unittest_test.py
  src/python/pants/backend/javascript/goals/test.py
  src/python/pants/backend/javascript/goals/test_integration_test.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/backend/scala/test/scalatest_test.py
  src/python/pants/backend/shell/goals/test.py
  src/python/pants/backend/shell/goals/test_test.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/backend/shell/shunit2_test_runner_integration_test.py
  src/python/pants/jvm/test/junit.py
  src/python/pants/jvm/test/junit_test.py
  src/python/pants/jvm/test/testutil.py
Labels: backend: Go, backend: JVM, category:new feature, backend: Helm, backend: Shell, backend: JavaScript

#20711 Prepare 2.19.2rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20702 use default upstream and upgrade shellcheck
  src/python/pants/backend/shell/lint/shellcheck/subsystem.py
Labels: category:new feature, backend: Shell

#20705 Python: fix module mappings for opentelemetry libs.
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: needs-cherrypick, category:internal

#20710 Prepare 2.21.0.dev4
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20717 upgrade Rust to v1.77.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/engine/process_execution/pe_nailgun/src/parsed_jvm_command_lines.rs
  src/rust/engine/rust-toolchain
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/workunit_store/src/lib.rs
Labels: category:internal

#20712 Properly format error about invalid scope names
  src/python/pants/option/subsystem.py
Labels: category:bugfix

#20715 Add extra newlines to avoid softwrapping the :::caution in `export` docs
  src/python/pants/core/goals/export.py
Labels: needs-cherrypick, category:documentation

#20716 Use `[]()` links not `<>` in `[pex].emit_warnings` docs
  src/python/pants/backend/python/util_rules/pex_environment.py
Labels: needs-cherrypick, category:documentation

#20720 Add extra newlines to avoid softwrapping the :::caution in `export` docs (Cherry-pick of #20715)
  src/python/pants/core/goals/export.py
Labels: category:documentation

#20719 Add extra newlines to avoid softwrapping the :::caution in `export` docs (Cherry-pick of #20715)
  src/python/pants/core/goals/export.py
Labels: category:documentation

#20721 Use `[]()` links not `<>` in `[pex].emit_warnings` docs (Cherry-pick of #20716)
  src/python/pants/backend/python/util_rules/pex_environment.py
Labels: category:documentation

#20724 add new module mapping for auth0-python
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#20713 Python: fix module mappings for opentelemetry libs. (Cherry-pick of #20705)
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#20687 Add "what's new" in 2.20
  src/python/pants/notes/2.20.x.md
Labels: needs-cherrypick, category:documentation

#20726 Add "what's new" in 2.20 (Cherry-pick of #20687)
  src/python/pants/notes/2.20.x.md
Labels: category:documentation

#20727 Prepare 2.20.0rc2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20734 upgrade Pex to 2.3.0
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:bugfix, backend: Python

#20698 New implementation of rust cli args parsing.
  src/python/pants/option/subsystem.py
  src/python/pants/option/subsystem_test.py
  src/rust/engine/Cargo.lock
  src/rust/engine/options/Cargo.toml
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/id.rs
  src/rust/engine/options/src/id_tests.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: category:internal
