Repository pantsbuild/pants, pull requests merged in 2024-05, with the labels that each got.

#20861 Add a space before "However" in `update-build-files`'s "... BUILD files found.However, ..."
  src/python/pants/core/goals/update_build_files.py
Labels: category:bugfix

#20867 Upgrade to shfmt 3.8.0
  src/python/pants/backend/shell/lint/shfmt/subsystem.py
Labels: category:user api change

#20869 Handle env vars for dotted scopes
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/env_tests.rs
Labels: category:internal

#20868 Fall back to [DEFAULT] section in rust config parser
  src/python/pants/option/options_test.py
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
Labels: category:internal

#20827 Introduce a "stable release manager" process
  docs/docs/contributions/releases/release-strategy.mdx
Labels: category:internal

#20875 Support parsing Config from memory in Rust.
  src/python/pants/option/config.py
  src/python/pants/option/config_test.py
  src/python/pants/option/options_bootstrapper.py
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
Labels: category:internal

#20872 Prepare 2.22.0.dev1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20879 Prepare 2.20.1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20876 Fix dependencies and dependents to use output file when using json formatting (Cherry-pick of #20843)
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/dependencies_test.py
  src/python/pants/backend/project_info/dependents.py
  src/python/pants/backend/project_info/dependents_test.py
Labels: category:bugfix

#20877 Fix dependencies and dependents to use output file when using json formatting (Cherry-pick of #20843)
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/dependencies_test.py
  src/python/pants/backend/project_info/dependents.py
  src/python/pants/backend/project_info/dependents_test.py
Labels: category:bugfix

#20880 Rust options parser tweaks
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/pantsd/src/lib.rs
Labels: category:internal

#20883 pyo3 interfaces for the Rust options parser.
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#20884 docs: Fix broken links
  src/python/pants/backend/python/goals/coverage_py.py
Labels: category:documentation

#20878 Start the release notes for 2.22
  docs/notes/2.22.x.md
Labels: category:documentation

#20850 Require release notes or explicit opt-out in every PR
  .github/workflows/test.yaml
  build-support/bin/classify_changed_files.py
  build-support/bin/classify_changed_files_test.py
  docs/docs/contributions/index.mdx
  docs/docs/contributions/releases/release-process.mdx
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#20881 upgrade Rust to v1.78.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/.cargo/config.toml
  src/rust/engine/BUILD
  src/rust/engine/hashing/src/lib.rs
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store.rs
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rust-toolchain
  src/rust/engine/src/python.rs
Labels: category:internal

#20695 Bundle OpenAPI files as a single resource
  docs/notes/2.22.x.md
  src/python/pants/backend/experimental/openapi/register.py
  src/python/pants/backend/openapi/subsystems/redocly.py
  src/python/pants/backend/openapi/util_rules/openapi_document.py
  src/python/pants/backend/openapi/util_rules/openapi_document_test.py
Labels: category:new feature

#20887 Integrate the native options parser into Python.
  docs/notes/2.22.x.md
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/global_options.py
  src/python/pants/option/native_options.py
  src/python/pants/option/option_value_container.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/parser.py
  src/python/pants/option/ranked_value.py
Labels: category:new feature

#20903 Adjust docs for python `export` goal option
  src/python/pants/backend/python/goals/export.py
Labels: needs-cherrypick, category:documentation, release-notes:not-required

#20854 Add sql backend + sqlfluff linter
  build-support/bin/generate_builtin_lockfiles.py
  docs/docs/ad-hoc-tools/_category_.json
  docs/docs/contributions/_category_.json
  docs/docs/releases/_category_.json
  docs/docs/sql/_category_.json
  docs/docs/sql/index.mdx
  docs/docs/writing-plugins/_category_.json
  docs/notes/2.22.x.md
  src/python/pants/backend/experimental/sql/__init__.py
  src/python/pants/backend/experimental/sql/lint/__init__.py
  src/python/pants/backend/experimental/sql/lint/sqlfluff/__init__.py
  src/python/pants/backend/experimental/sql/lint/sqlfluff/register.py
  src/python/pants/backend/experimental/sql/register.py
  src/python/pants/backend/sql/BUILD
  src/python/pants/backend/sql/__init__.py
  src/python/pants/backend/sql/lint/__init__.py
  src/python/pants/backend/sql/lint/sqlfluff/BUILD
  src/python/pants/backend/sql/lint/sqlfluff/__init__.py
  src/python/pants/backend/sql/lint/sqlfluff/rules.py
  src/python/pants/backend/sql/lint/sqlfluff/rules_integration_test.py
  src/python/pants/backend/sql/lint/sqlfluff/skip_field.py
  src/python/pants/backend/sql/lint/sqlfluff/sqlfluff.lock
  src/python/pants/backend/sql/lint/sqlfluff/subsystem.py
  src/python/pants/backend/sql/tailor.py
  src/python/pants/backend/sql/target_types.py
Labels: category:new feature

#20907 Prepare 2.20.2rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20908 Prepare 2.21.0a1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20909 Prepare 2.22.0.dev2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20906 Prepare 2.19.3rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20890 Add docs for `jvm_artifacts` target generator
  docs/docs/jvm/java-and-scala.mdx
  docs/notes/2.22.x.md
Labels: needs-cherrypick, category:documentation, release-notes:not-required

#20901 Add tool version into `install_from_resolve` arg documentation
  docs/notes/2.22.x.md
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/option/scope.py
Labels: category:documentation, backend: Python

#20919 Add docs for `jvm_artifacts` target generator (Cherry-pick of #20890)
  docs/docs/jvm/java-and-scala.mdx
Labels: category:documentation

#20920 Add docs for `jvm_artifacts` target generator (Cherry-pick of #20890)
  docs/docs/jvm/java-and-scala.mdx
Labels: category:documentation

#20741 update k8s_parser lock; broaden model compatibility
  docs/notes/2.22.x.md
  src/python/pants/backend/helm/subsystems/k8s_parser.lock
  src/python/pants/backend/helm/subsystems/k8s_parser.py
Labels: category:internal, backend: Helm

#20924 Update Ruff version to 0.4.4
  docs/notes/2.22.x.md
  src/python/pants/backend/python/lint/ruff/ruff.lock
Labels: category:internal, backend: Python

#20501 Update semgrep 1.46.0 -> 1.72.0
  docs/notes/2.22.x.md
  src/python/pants/backend/tools/semgrep/rules_integration_test.py
  src/python/pants/backend/tools/semgrep/semgrep.lock
  src/python/pants/backend/tools/semgrep/subsystem.py
Labels: category:user api change

#20894 Add release notes for 2.21.x
  docs/notes/2.21.x.md
Labels: needs-cherrypick, category:documentation

#20926 Add release notes for 2.21.x (Cherry-pick of #20894)
  src/python/pants/notes/2.21.x.md
Labels: category:documentation

#20902 Fix markdown syntax in "Making subsystems exportable ..." docs
  docs/docs/writing-plugins/common-subsystem-tasks.mdx
Labels: needs-cherrypick, category:documentation, release-notes:not-required

#20928 Fix markdown syntax in "Making subsystems exportable ..." docs (Cherry-pick of #20902)
  docs/docs/writing-plugins/common-subsystem-tasks.mdx
Labels: category:documentation

#20927 Create FUNDING.yml
  .github/FUNDING.yml
Labels: category:internal

#20929 Include extra_build_args on pex_binaries too
  docs/notes/2.22.x.md
  src/python/pants/backend/python/target_types.py
Labels: category:new feature

#20802 Use Wildcard When jvm_exclude Artifact is None
  docs/notes/2.22.x.md
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
  src/python/pants/jvm/target_types.py
Labels: category:bugfix

#20921 Add `help_short` field for Python tools and use it to generate the help text
  docs/notes/2.22.x.md
  src/python/pants/backend/cc/lint/clangformat/subsystem.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/post_renderer.py
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/lint/add_trailing_comma/subsystem.py
  src/python/pants/backend/python/lint/autoflake/subsystem.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/docformatter/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/isort/subsystem.py
  src/python/pants/backend/python/lint/pydocstyle/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pyupgrade/subsystem.py
  src/python/pants/backend/python/lint/ruff/subsystem.py
  src/python/pants/backend/python/lint/yapf/subsystem.py
  src/python/pants/backend/python/packaging/pyoxidizer/subsystem.py
  src/python/pants/backend/python/subsystems/debugpy.py
  src/python/pants/backend/python/subsystems/ipython.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/backend/python/subsystems/setuptools_scm.py
  src/python/pants/backend/python/subsystems/twine.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/typecheck/pytype/subsystem.py
  src/python/pants/backend/sql/lint/sqlfluff/subsystem.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/tools/semgrep/subsystem.py
  src/python/pants/backend/tools/yamllint/subsystem.py
Labels: category:documentation, backend: Python

#20935 Prepare 2.21.0rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20767 internal: sort more tuples to potentially improve cache hit rates.
  src/python/pants/backend/python/dependency_inference/module_mapper.py
  src/python/pants/backend/python/framework/stevedore/python_target_dependencies.py
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/util_rules/local_dists.py
  src/python/pants/backend/python/util_rules/local_dists_pep660.py
  src/python/pants/backend/python/util_rules/package_dists.py
  src/python/pants/engine/target.py
Labels: category:internal

#20936 Update release notes links in Plugin Upgrade Guide docs after movement
  docs/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx
Labels: needs-cherrypick, category:documentation, release-notes:not-required

#20937 Restore stub release notes files, with links to new location
  src/python/pants/notes/1.0.x.rst
  src/python/pants/notes/1.1.x.rst
  src/python/pants/notes/1.10.x.rst
  src/python/pants/notes/1.11.x.rst
  src/python/pants/notes/1.12.x.rst
  src/python/pants/notes/1.13.x.rst
  src/python/pants/notes/1.14.x.rst
  src/python/pants/notes/1.15.x.rst
  src/python/pants/notes/1.16.x.rst
  src/python/pants/notes/1.17.x.rst
  src/python/pants/notes/1.18.x.rst
  src/python/pants/notes/1.19.x.rst
  src/python/pants/notes/1.2.x.rst
  src/python/pants/notes/1.20.x.rst
  src/python/pants/notes/1.21.x.rst
  src/python/pants/notes/1.22.x.rst
  src/python/pants/notes/1.23.x.rst
  src/python/pants/notes/1.24.x.rst
  src/python/pants/notes/1.25.x.rst
  src/python/pants/notes/1.26.x.rst
  src/python/pants/notes/1.27.x.rst
  src/python/pants/notes/1.28.x.rst
  src/python/pants/notes/1.29.x.rst
  src/python/pants/notes/1.3.x.rst
  src/python/pants/notes/1.30.x.rst
  src/python/pants/notes/1.4.x.rst
  src/python/pants/notes/1.5.x.rst
  src/python/pants/notes/1.6.x.rst
  src/python/pants/notes/1.7.x.rst
  src/python/pants/notes/1.8.x.rst
  src/python/pants/notes/1.9.x.rst
  src/python/pants/notes/2.0.x.md
  src/python/pants/notes/2.0.x.rst
  src/python/pants/notes/2.1.x.md
  src/python/pants/notes/2.1.x.rst
  src/python/pants/notes/2.10.x.md
  src/python/pants/notes/2.11.x.md
  src/python/pants/notes/2.12.x.md
  src/python/pants/notes/2.13.x.md
  src/python/pants/notes/2.14.x.md
  src/python/pants/notes/2.15.x.md
  src/python/pants/notes/2.16.x.md
  src/python/pants/notes/2.17.x.md
  src/python/pants/notes/2.18.x.md
  src/python/pants/notes/2.19.x.md
  src/python/pants/notes/2.2.x.md
  src/python/pants/notes/2.20.x.md
  src/python/pants/notes/2.21.x.md
  src/python/pants/notes/2.22.x.md
  src/python/pants/notes/2.3.x.md
  src/python/pants/notes/2.4.x.md
  src/python/pants/notes/2.5.x.md
  src/python/pants/notes/2.6.x.md
  src/python/pants/notes/2.7.x.md
  src/python/pants/notes/2.8.x.md
  src/python/pants/notes/2.9.x.md
  src/python/pants/notes/master.rst
Labels: category:documentation, release-notes:not-required

#20940 Update release notes links in Plugin Upgrade Guide docs after movement (Cherry-pick of #20936)
  docs/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx
Labels: category:documentation

#20941 Update release notes links in Plugin Upgrade Guide docs after movement (Cherry-pick of #20936)
  docs/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx
Labels: category:documentation

#20942 Update release notes links in Plugin Upgrade Guide docs after movement (Cherry-pick of #20936)
  docs/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx
Labels: category:documentation

#20943 An option for excluding certain files from all deploy jars
  docs/notes/2.22.x.md
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/subsystems.py
Labels: category:new feature

#20944 refactor fork/exec logic for the command runners
  src/rust/engine/process_execution/src/cache_tests.rs
  src/rust/engine/process_execution/src/fork_exec.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/src/context.rs
Labels: category:internal

#20788 Mark most JVM-based subsystems as exportable
  docs/notes/2.22.x.md
  src/python/pants/backend/codegen/avro/java/rules.py
  src/python/pants/backend/codegen/protobuf/java/rules.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/codegen/soap/java/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/scala/lint/scalafix/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/jvm/test/junit.py
Labels: backend: JVM, category:internal

#20787 Mark all Python tools as exportable
  docs/docs/python/overview/lockfiles.mdx
  docs/docs/using-pants/setting-up-an-ide.mdx
  docs/notes/2.22.x.md
  src/python/pants/backend/cc/lint/clangformat/subsystem.py
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/backend/python/lint/add_trailing_comma/subsystem.py
  src/python/pants/backend/python/lint/autoflake/subsystem.py
  src/python/pants/backend/python/lint/bandit/subsystem.py
  src/python/pants/backend/python/lint/black/subsystem.py
  src/python/pants/backend/python/lint/docformatter/subsystem.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/isort/subsystem.py
  src/python/pants/backend/python/lint/pydocstyle/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/lint/pyupgrade/subsystem.py
  src/python/pants/backend/python/lint/ruff/subsystem.py
  src/python/pants/backend/python/lint/yapf/subsystem.py
  src/python/pants/backend/python/packaging/pyoxidizer/subsystem.py
  src/python/pants/backend/python/subsystems/ipython.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/subsystems/setuptools_scm.py
  src/python/pants/backend/python/subsystems/twine.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/typecheck/pytype/rules.py
  src/python/pants/backend/tools/semgrep/subsystem.py
  src/python/pants/backend/tools/yamllint/subsystem.py
Labels: category:new feature, backend: Python

#20764 make `pants help-all` more deterministic
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/wrap_source.py
  src/python/pants/engine/target.py
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_printer.py
Labels: category:internal

#20360 Add `makeself` backend
  docs/docs/shell/self-extractable-archives.mdx
  docs/notes/2.22.x.md
  src/python/pants/backend/experimental/makeself/BUILD
  src/python/pants/backend/experimental/makeself/__init__.py
  src/python/pants/backend/experimental/makeself/register.py
  src/python/pants/backend/makeself/BUILD
  src/python/pants/backend/makeself/__init__.py
  src/python/pants/backend/makeself/goals/BUILD
  src/python/pants/backend/makeself/goals/__init__.py
  src/python/pants/backend/makeself/goals/package.py
  src/python/pants/backend/makeself/goals/package_run_integration_test.py
  src/python/pants/backend/makeself/goals/run.py
  src/python/pants/backend/makeself/subsystem.py
  src/python/pants/backend/makeself/system_binaries.py
  src/python/pants/backend/makeself/target_types.py
  src/python/pants/bin/BUILD
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:new feature

#20939 Allow Extra Args to be passed to FaaS Pex Build
  docs/notes/2.22.x.md
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
Labels: category:new feature

#20772 add "workspace" process execution strategy
  docs/notes/2.22.x.md
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/environment.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/process_test.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/process_execution/src/workspace.rs
  src/rust/engine/process_execution/src/workspace_tests.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/process.rs
Labels: category:new feature

#20951 Bump pyo3 to 0.21.2
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal

#20955 Prepare 2.22.0.dev3
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20956 Don't filter the env passed to OptionsBootstrapper.
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_bootstrapper_test.py
Labels: category:internal

#20953 Publish: sort the results output at the end.
  docs/notes/2.22.x.md
  src/python/pants/core/goals/publish.py
Labels: category:documentation

#20946 Lower log message level for nailgun to reduce verbosity
  docs/notes/2.22.x.md
  src/python/pants/core/goals/check_test.py
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
Labels: category:documentation

#20963 Prepare 2.20.2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20960 Scala: Detect consumed symbols in self-type annotations
  docs/notes/2.22.x.md
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: backend: JVM, category:new feature

#20958 Always match source globs using the `any` conjunction.
  docs/notes/2.22.x.md
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  tests/python/pants_test/integration/graph_integration_test.py
Labels: category:bugfix

#20934 Update address parameters on overrides
  docs/notes/2.22.x.md
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
  src/rust/engine/src/externs/address.rs
Labels: needs-cherrypick, category:bugfix

#20967 Fixed broken PyOxidizer link in released notes
  docs/notes/2.22.x.md
Labels: category:internal

#20961 Prepare 2.21.0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20969 OpenAPI Java codegen fails with an ambiguous class path
  docs/notes/2.22.x.md
  src/python/pants/backend/experimental/openapi/register.py
  src/python/pants/backend/openapi/codegen/java/rules_integration_test.py
  src/python/pants/backend/openapi/target_types.py
  src/python/pants/backend/openapi/util_rules/openapi_bundle.py
  src/python/pants/backend/openapi/util_rules/openapi_bundle_test.py
  src/python/pants/jvm/compile.py
Labels: backend: JVM, category:user api change, backend: OpenAPI

#20973 Add missing sql backends in pants packaging
  src/python/pants/backend/experimental/sql/BUILD
  src/python/pants/backend/experimental/sql/lint/sqlfluff/BUILD
  src/python/pants/bin/BUILD
Labels: category:internal, release-notes:not-required

#20974 Make various JDK tests work on all platforms.
  src/python/pants/backend/java/compile/javac_test.py
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/jvm/jdk_rules_test.py
Labels: category:internal

#20874 Expose intrinsics as decorated Python functions instead
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/intrinsics.py
  src/python/pants/init/engine_initializer.py
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/intrinsics/dep_inference.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/intrinsics/docker.rs
  src/rust/engine/src/intrinsics/interactive_process.rs
  src/rust/engine/src/intrinsics/mod.rs
  src/rust/engine/src/intrinsics/process.rs
  src/rust/engine/src/intrinsics/values.rs
  src/rust/engine/src/lib.rs
  src/rust/engine/src/nodes/mod.rs
  src/rust/engine/src/nodes/task.rs
  src/rust/engine/src/tasks.rs
Labels: category:internal
