Repository pantsbuild/pants, pull requests merged in 2024-06, with the labels that each got.

#20983 Use code blocks in nodejs-test example docs
  src/python/pants/backend/javascript/subsystems/nodejstest.py
Labels: category:documentation, release-notes:not-required

#20975 export generated python sources to exported venvs
  docs/docs/python/integrations/protobuf-and-grpc.mdx
  docs/docs/python/integrations/thrift.mdx
  docs/notes/2.22.x.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/engine/internals/graph.py
Labels: category:new feature, backend: Python

#20900 add workspace environment support
  docs/docs/using-pants/environments.mdx
  docs/notes/2.22.x.md
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/register.py
  src/python/pants/core/util_rules/adhoc_process_support.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/engine/environment.py
  src/python/pants/engine/process_test.py
Labels: category:new feature

#20984 Fix help text for `stevedore_namespace` BUILD file symbol.
  src/python/pants/backend/python/framework/stevedore/target_types.py
Labels: category:documentation, release-notes:not-required

#20998 Update console and indicatif deps
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: needs-cherrypick, category:internal

#21003 Use GitHub-hosted macos-12 in CI, not deprecated macos-11
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#20871 Flag to disable publishing dependencies in deploy goal
  docs/notes/2.22.x.md
  src/python/pants/core/goals/deploy.py
Labels: category:new feature

#21001 Update console and indicatif deps (Cherry-pick of #20998)
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal

#21002 Update console and indicatif deps (Cherry-pick of #20998)
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal

#20995 Prepare 2.22.0a0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21010 Add release notes file for 2.23.x
  docs/notes/2.23.x.md
Labels: category:internal

#21007 Upgrade default `pyright` version from 1.1.316 to 1.1.365
  docs/notes/2.23.x.md
  src/python/pants/backend/python/typecheck/pyright/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pyright/subsystem.py
Labels: category:internal, backend: Python

#21011 fix regression in choosing a compatible local environment
  docs/notes/2.23.x.md
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: needs-cherrypick, category:bugfix

#21014 fix regression in choosing a compatible local environment (Cherry pick of #21011)
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: category:bugfix, release-notes:not-required

#20971 scala source file should not depend on scalac plugins
  docs/notes/2.23.x.md
  src/python/pants/backend/scala/compile/scalac_test.py
  src/python/pants/backend/scala/dependency_inference/rules.py
Labels: backend: JVM, category:bugfix

#21024 rename `workspace_environment` to `experimental_workspace_environment`
  docs/docs/using-pants/environments.mdx
  docs/notes/2.22.x.md
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/process_test.py
  src/python/pants/help/help_integration_test.py
Labels: needs-cherrypick, category:internal, release-notes:not-required

#21025 rename `workspace_environment` to `experimental_workspace_environment` (Cherry-pick of #21024)
  docs/docs/using-pants/environments.mdx
  docs/notes/2.22.x.md
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/engine/process_test.py
  src/python/pants/help/help_integration_test.py
Labels: category:internal

#21032 Make various tests pass on MacOS ARM
  src/python/pants/backend/python/lint/flake8/flake8_plugin_test.lock
  src/python/pants/backend/python/providers/pyenv/rules_integration_test.py
  src/python/pants/backend/terraform/goals/check_test.py
  src/python/pants/engine/internals/docker_test.py
  src/python/pants/engine/platform.py
  testprojects/src/python/native/impl.c
Labels: category:internal

#21033 Provide default tfsec versions for all platforms
  docs/notes/2.23.x.md
  src/python/pants/backend/terraform/lint/tfsec/tfsec.py
Labels: category:bugfix

#21038 Fix bug when computing implicit kwargs in @rules called by name.
  src/rust/engine/src/nodes/task.rs
Labels: category:bugfix, release-notes:not-required

#21035 Support extra env vars resolution of `PATH` in nodejs processes
  docs/notes/2.23.x.md
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_test.py
Labels: category:bugfix, backend: JavaScript

#21008 Use GitHub-hosted macos-12 in CI, not deprecated macos-11 (Cherry-pick of #21003)
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21009 Use GitHub-hosted macos-12 in CI, not deprecated macos-11 (Cherry-pick of #21003)
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21030 Pick provider closest to the rule/subsystem/target type.
  docs/notes/2.23.x.md
  src/python/pants/help/help_info_extracter.py
Labels: category:bugfix

#21041 Resolve 2.23.0.dev0 deprecations: dependees, old ruff, crossversion=partial, remote_auth_bearer_token_path
  docs/notes/2.23.x.md
  src/python/pants/backend/experimental/python/lint/ruff/register.py
  src/python/pants/backend/project_info/dependents.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/backend/scala/util_rules/versions.py
  src/python/pants/backend/scala/util_rules/versions_test.py
  src/python/pants/goal/run_tracker.py
  src/python/pants/option/global_options.py
  src/python/pants/option/global_options_test.py
  src/python/pants/vcs/changed.py
Labels: category:user api change

#21042 [Call-by-name] Fixed ignored compound statements and generator MultiGets
  src/python/pants/goal/migrate_call_by_name.py
  src/python/pants/goal/migrate_call_by_name_integration_test.py
Labels: category:internal

#21000 Fixed Docker <unknown> image_id returned from parser using recent BuildKit on Windows
  docs/notes/2.23.x.md
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
Labels: category:bugfix, backend: Docker

#21039 Prepare 2.23.0.dev0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21046 build: Bump pex to 2.3.3
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/notes/2.23.x.md
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:bugfix

#20968 Add lint backend to run trufflehog
  docs/notes/2.23.x.md
  src/python/pants/backend/experimental/tools/trufflehog/BUILD
  src/python/pants/backend/experimental/tools/trufflehog/__init__.py
  src/python/pants/backend/experimental/tools/trufflehog/register.py
  src/python/pants/backend/tools/trufflehog/BUILD
  src/python/pants/backend/tools/trufflehog/__init__.py
  src/python/pants/backend/tools/trufflehog/rules.py
  src/python/pants/backend/tools/trufflehog/rules_integration_test.py
  src/python/pants/backend/tools/trufflehog/subsystem.py
  src/python/pants/bin/BUILD
Labels: category:new feature

#20531 Add support for fine grained diff with line numbers
  docs/notes/2.23.x.md
  src/python/pants/backend/BUILD
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/target_adapter_test.py
  src/python/pants/engine/internals/target_adaptor.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/init/specs_calculator.py
  src/python/pants/option/global_options.py
  src/python/pants/vcs/changed.py
  src/python/pants/vcs/changed_integration_test.py
  src/python/pants/vcs/git.py
  src/python/pants/vcs/git_test.py
  src/python/pants/vcs/hunk.py
  testprojects/pants-plugins/src/python/python_constant/BUILD
  testprojects/pants-plugins/src/python/python_constant/__init__.py
  testprojects/pants-plugins/src/python/python_constant/register.py
  testprojects/pants-plugins/src/python/python_constant/target_types.py
  testprojects/pants-plugins/src/python/python_constant/target_types_test.py
  testprojects/src/python/vcs_test/BUILD
  testprojects/src/python/vcs_test/changed_integration_test.py
Labels: category:internal

#21028 Support documenting macro constants.
  3rdparty/python/mypy.lock
  3rdparty/python/pytest.lock
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/docs/writing-plugins/macros.mdx
  docs/notes/2.23.x.md
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/parser.py
Labels: category:new feature

#21057 fix: args for `helm pull` for OCI artifacts
  docs/notes/2.23.x.md
  src/python/pants/backend/helm/resolve/fetch.py
  src/python/pants/backend/helm/resolve/fetch_test.py
Labels: category:bugfix, backend: Helm

#20989 Resolve addresses in ARGs passed to COPY
  docs/docs/docker/index.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_wrapper_script.py
  src/python/pants/backend/docker/util_rules/dependencies.py
  src/python/pants/backend/docker/util_rules/dependencies_test.py
  src/python/pants/backend/docker/util_rules/docker_build_args.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
  src/python/pants/backend/docker/utils.py
Labels: category:new feature, backend: Docker

#20972 separate shell tailoring between sources and tests
  docs/notes/2.23.x.md
  src/python/pants/backend/shell/goals/tailor.py
  src/python/pants/backend/shell/goals/tailor_test.py
  src/python/pants/backend/shell/subsystems/shell_setup.py
Labels: category:user api change, backend: Shell

#21043 [Call-by-name] `cc` backend migration
  docs/notes/2.23.x.md
  src/python/pants/backend/cc/dependency_inference/rules.py
  src/python/pants/backend/cc/goals/tailor.py
Labels: category:internal

#21049 Fix non-writable files if "." in `output_directories`
  docs/notes/2.23.x.md
  src/python/pants/engine/process.py
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/tests.rs
Labels: category:bugfix

#21060 Rewrite IPython repl docs for new `install_from_resolve` approach
  docs/docs/python/goals/repl.mdx
Labels: needs-cherrypick, category:documentation, release-notes:not-required

#21068 Rewrite IPython repl docs for new `install_from_resolve` approach (Cherry-pick of #21060)
  docs/docs/python/goals/repl.mdx
Labels: category:documentation

#21069 Rewrite IPython repl docs for new `install_from_resolve` approach (Cherry-pick of #21060)
  docs/docs/python/goals/repl.mdx
Labels: category:documentation

#21070 Rewrite IPython repl docs for new `install_from_resolve` approach (Cherry-pick of #21060)
  docs/docs/python/goals/repl.mdx
Labels: category:documentation, release-notes:not-required

#21051 Add "workspace invalidation" sources support for shell / adhoc backends
  docs/docs/using-pants/environments.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: category:new feature

#21073 Fixed several broken links in docs
  docs/docs/docker/tagging-docker-images.mdx
  docs/docs/jvm/java-and-scala.mdx
  docs/docs/jvm/kotlin.mdx
  docs/docs/python/integrations/protobuf-and-grpc.mdx
  docs/docs/python/integrations/thrift.mdx
Labels: category:documentation, release-notes:not-required

#21055 Scala: Support the usage of the `_root_` package name
  docs/notes/2.23.x.md
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: backend: JVM, category:new feature

#21080 Prepare 2.23.0.dev1
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21079 Bump default ruff version to 0.4.9
  docs/notes/2.23.x.md
  src/python/pants/backend/python/lint/ruff/ruff.lock
Labels: category:user api change, backend: Python

#21081 Update release docs to work around file watcher race condition.
  docs/docs/contributions/releases/release-process.mdx
Labels: category:documentation, release-notes:not-required

#21047 Fix running python_sources with pex --executable
  docs/notes/2.23.x.md
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
Labels: needs-cherrypick, category:bugfix, backend: Python

#21061 Sketch new "Maintenance tasks and scripts" contributing dev docs
  build-support/bin/generate_json_schema.py
  docs/docs/contributions/development/maintenance-tasks-and-scripts.mdx
Labels: category:documentation, release-notes:not-required

#21084 Fix running python_sources with pex --executable (Cherry-pick of #21047)
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
Labels: category:bugfix, backend: Python

#21085 Fix running python_sources with pex --executable (Cherry-pick of #21047)
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
Labels: category:bugfix, backend: Python

#21086 Fix running python_sources with pex --executable (Cherry-pick of #21047)
  docs/notes/2.22.x.md
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/run_python_source_integration_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
Labels: category:bugfix, backend: Python

#21071 [Call-by-name] `cc.lint.clang-format` migration
  src/python/pants/backend/cc/lint/clangformat/rules.py
Labels: category:internal

#21064 [Call-by-name] `swift` backend migration
  docs/notes/2.23.x.md
  src/python/pants/backend/swift/goals/tailor.py
Labels: category:internal

#21088 Move Eric Arellano to emeritus
  MAINTAINERS.md
Labels: category:internal, release-notes:not-required

#21027 parametrize: expand grouped parametrizations.
  docs/docs/using-pants/key-concepts/targets-and-build-files.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/python/macros/common_requirements_rule.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/parametrize.py
  src/python/pants/engine/internals/parametrize_test.py
  src/python/pants/engine/target.py
  src/python/pants/util/frozendict.py
  src/python/pants/util/frozendict_test.py
Labels: category:new feature

#20988 Run more rules concurrently when building a pex
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:internal, backend: Python

#21067 Fix k8s-parser not able to load hikaru models
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/k8s_parser_main.py
Labels: needs-cherrypick, category:bugfix, backend: Helm, release-notes:not-required

#21062 Generate entry_points.txt for python_tests that require entry points from a python_distribution
  docs/notes/2.23.x.md
  src/python/pants/backend/experimental/python/framework/stevedore/register.py
  src/python/pants/backend/experimental/python/register.py
  src/python/pants/backend/python/framework/stevedore/python_target_dependencies.py
  src/python/pants/backend/python/framework/stevedore/python_target_dependencies_test.py
  src/python/pants/backend/python/framework/stevedore/rules.py
  src/python/pants/backend/python/framework/stevedore/rules_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/util_rules/entry_points.py
  src/python/pants/backend/python/util_rules/entry_points_test.py
Labels: category:new feature, backend: Python

#21087 Refactor venv export to use explicit `PythonExecutable` lookup
  docs/notes/2.23.x.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:new feature, backend: Python

#20996 add intrinsic rule to request metadata about paths in filesystem
  docs/notes/2.23.x.md
  src/python/pants/engine/fs.py
  src/python/pants/engine/fs_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/intrinsics.py
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/nodes/mod.rs
  src/rust/engine/src/nodes/path_metadata.rs
  src/rust/engine/src/types.rs
Labels: category:new feature

#20818 docs: there may be multiple BUILD files in a directory
  docs/docs/using-pants/key-concepts/targets-and-build-files.mdx
Labels: category:documentation, release-notes:not-required

#21021 Always capture a `corepack` installation and support omitting version strings
  docs/notes/2.23.x.md
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_test.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool_test.py
Labels: category:bugfix, backend: JavaScript

#21090 Fix k8s-parser not able to load hikaru models (Cherry-pick of #21067)
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/k8s_parser_main.py
Labels: category:bugfix, release-notes:not-required

#21101 Prepare 2.23.0.dev2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21102 Prepare 2.22.0rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21092 shell/adhoc: use metadata hashing instead of content hashing for `workspace_invalidation_sources`
  src/python/pants/core/util_rules/adhoc_process_support.py
  src/python/pants/core/util_rules/adhoc_process_support_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/rust/engine/src/externs/fs.rs
Labels: category:bugfix, release-notes:not-required

#21105 upgrade Rust to v1.79.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/Cargo.toml
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rust-toolchain
Labels: category:internal, release-notes:not-required

#21095 docs: how to publish a Pants config schema file in Schema Store
  docs/docs/contributions/development/maintenance-tasks-and-scripts.mdx
  docs/docs/contributions/releases/release-process.mdx
Labels: category:documentation, release-notes:not-required

#21089 [Call-by-name] Replaced `ast` with `libcst` in migration code
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/goal/migrate_call_by_name.py
  src/python/pants/goal/migrate_call_by_name_integration_test.py
  src/python/pants/goal/migrate_call_by_name_test.py
  src/python/pants/util/astutil.py
  src/python/pants/util/astutil_test.py
  src/python/pants/util/cstutil.py
  src/python/pants/util/cstutil_test.py
Labels: category:internal, release-notes:not-required

#21107 upgrade `futures` and related crates to v0.3.30
  src/rust/engine/Cargo.lock
Labels: category:internal

#21053 fix(scala): dependency inference for typed patterns referring same package
  docs/notes/2.23.x.md
  src/python/pants/backend/scala/dependency_inference/ScalaParser.scala
  src/python/pants/backend/scala/dependency_inference/scala_parser_test.py
Labels: category:bugfix

#21108 upgrade `tracing` and related crates
  src/rust/engine/Cargo.lock
Labels: category:internal

#21015 delete "future" release notes from automatic cherry pick
  .github/workflows/auto-cherry-picker.yaml
Labels: category:bugfix, release-notes:not-required

#21111 improve tfsec version providing, behavior, add more known versions
  docs/notes/2.23.x.md
  src/python/pants/backend/terraform/lint/tfsec/tfsec.py
Labels: category:new feature, backend: Terraform

#21110 Bump default terraform version to 1.9.0, add all known terraform versions inbetween
  docs/notes/2.23.x.md
  src/python/pants/backend/terraform/tool.py
Labels: category:user api change, backend: Terraform
