Repository pantsbuild/pants, pull requests merged in 2024-02, with the labels that each got.

#20464 add latest (25.2) to known protoc versions
  src/python/pants/backend/codegen/protobuf/protoc.py
Labels: category:internal, backend: Protobuf

#20472 python-infer: Avoid false positive strings
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
Labels: category:bugfix, backend: Python

#20482 Update broken link to default versioning scheme
  docs/docs/using-pants/generating-version-tags-from-git.mdx
Labels: category:documentation

#20358 Introduce `ruff-check` and `ruff-format` tool ids
  src/python/pants/backend/python/lint/ruff/rules.py
  src/python/pants/backend/python/lint/ruff/subsystem.py
Labels: category:bugfix, backend: Python

#20477 python-infer: respect ignore pragma w/ strings
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: needs-cherrypick, category:bugfix, backend: Python

#20489 Fix capitalization of Terraform in left nav
  docs/docs/terraform/_category_.json
Labels: category:documentation

#20490 Fix capitalization of Terraform in left nav
  docs/docs/terraform/_category_.json
Labels: category:documentation

#20486 Fix direct_url in python PEP660 editable wheels
  src/python/pants/backend/python/util_rules/dists.py
  src/python/pants/backend/python/util_rules/dists_test.py
  src/python/pants/backend/python/util_rules/local_dists_pep660.py
  src/python/pants/backend/python/util_rules/local_dists_pep660_test.py
  src/python/pants/backend/python/util_rules/package_dists.py
Labels: needs-cherrypick, category:bugfix, backend: Python

#20483 python-infer: Avoid false positive strings (Cherry-pick of #20472)
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
Labels: category:bugfix

#20484 python-infer: respect ignore pragma w/ strings (Cherry-pick of #20477)
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: category:bugfix

#20494 Fix direct_url in python PEP660 editable wheels (Cherry-pick of #20486)
  src/python/pants/backend/python/util_rules/dists.py
  src/python/pants/backend/python/util_rules/dists_test.py
  src/python/pants/backend/python/util_rules/local_dists_pep660.py
  src/python/pants/backend/python/util_rules/local_dists_pep660_test.py
  src/python/pants/backend/python/util_rules/package_dists.py
Labels: category:bugfix

#20495 Bump year in `[tailor].build_file_header` to 2024
  pants.toml
Labels: category:internal

#20496 upgrade Pex to 2.1.162
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:bugfix, backend: Python

#20502 upgrade Pex to 2.1.163
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:bugfix, backend: Python

#20500 Use Python subsystem's default ICs when generating builtin lockfile
  build-support/bin/generate_builtin_lockfiles.py
  src/python/pants/backend/python/typecheck/pytype/subsystem.py
Labels: category:internal

#20499 Update built-in ruff 0.1.6 -> 0.2.1
  src/python/pants/backend/python/lint/ruff/ruff.lock
Labels: category:user api change

#20504 add module mapping overrides for some django-* modules
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:bugfix

#20411 Allow using Ruff to format BUILD files
  docs/docs/using-pants/key-concepts/backends.mdx
  src/python/pants/backend/BUILD
  src/python/pants/backend/build_files/fmt/ruff/BUILD
  src/python/pants/backend/build_files/fmt/ruff/__init__.py
  src/python/pants/backend/build_files/fmt/ruff/integration_test.py
  src/python/pants/backend/build_files/fmt/ruff/register.py
  src/python/pants/backend/python/lint/ruff/rules.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:new feature, backend: Python

#20505 Allow unmatching "changed" globs
  src/python/pants/init/specs_calculator.py
  src/python/pants/vcs/git.py
  src/python/pants/vcs/git_test.py
Labels: category:bugfix

#20481 plumb through Pex's --check zipapp validation
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:bugfix, backend: Python

#20493 Improve build file syntax error
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: category:internal, onboarding

#20297 python: improve error message when parsing Python interpreter constraints
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/backend/python/util_rules/interpreter_constraints_test.py
Labels: category:new feature, backend: Python

#20497 Add support for the pex `--executable` argument
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_pex_binary_integration_test.py
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_test.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:new feature, backend: Python

#20519 Fix Pex references to point to new home.
  MAINTAINERS.md
  docs/docs/python/integrations/aws-lambda.mdx
  docs/docs/python/integrations/google-cloud-functions.mdx
  docs/docs/python/overview/lockfiles.mdx
  docs/docs/python/overview/pex.mdx
  docs/docs/writing-plugins/the-rules-api/file-system.mdx
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/notes/1.1.x.rst
  src/python/pants/notes/1.10.x.rst
  src/python/pants/notes/1.11.x.rst
  src/python/pants/notes/1.15.x.rst
  src/python/pants/notes/1.16.x.rst
  src/python/pants/notes/1.20.x.rst
  src/python/pants/notes/1.21.x.rst
  src/python/pants/notes/1.26.x.rst
  src/python/pants/notes/1.27.x.rst
  src/python/pants/notes/1.29.x.rst
  src/python/pants/notes/1.5.x.rst
Labels: category:documentation

#20514 Fix formatting of the "pex.platforms is deprecated" message
  src/python/pants/backend/python/target_types.py
Labels: needs-cherrypick, category:bugfix

#20336 Generate `jvm_artifact` targets from `pom.xml`
  src/python/pants/jvm/jvm_common.py
  src/python/pants/jvm/target_types.py
  src/python/pants/jvm/target_types_test.py
Labels: category:new feature

#20523 python: respect closed option when exporting dependency graph as JSON
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/dependencies_test.py
  src/python/pants/backend/project_info/dependents.py
  src/python/pants/backend/project_info/dependents_test.py
Labels: category:new feature

#20524 docs: provide example how to convert target addresses to source files in rules API
  docs/docs/writing-plugins/the-rules-api/rules-and-the-target-api.mdx
Labels: category:documentation

#20529 Add TypeScript plugin to Pants loader
  src/python/pants/bin/BUILD
Labels: category:internal, backend: JavaScript

#20532 Bump PyO3 to 0.20 to fix backtraces (Cherry-pick of #20517)
  src/python/pants/engine/internals/scheduler_test.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/interning.rs
Labels: category:bugfix

#20533 docker: fix missing image_id when using containerd-snapshotter
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
Labels: category:bugfix

#20527 Fix formatting of the "pex.platforms is deprecated" message (Cherry-pick of #20514)
  src/python/pants/backend/python/target_types.py
Labels: category:bugfix

#20535 Generate option value derivations in the rust parser.
  src/rust/engine/Cargo.lock
  src/rust/engine/client/src/client_tests.rs
  src/rust/engine/client/src/main.rs
  src/rust/engine/options/Cargo.toml
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/pantsd/src/lib.rs
  src/rust/engine/pantsd/src/pantsd_testing.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: category:internal

#20521 docs: mention that when piping xargs may end up invoking Pants goal more than once
  docs/docs/using-pants/advanced-target-selection.mdx
  docs/docs/using-pants/project-introspection.mdx
Labels: category:documentation

#20522 docs: provide options to refer to a group of targets
  docs/docs/using-pants/advanced-target-selection.mdx
  docs/docs/using-pants/key-concepts/targets-and-build-files.mdx
Labels: category:documentation

#20512 stats: add output_file option to output the stats to a file
  src/python/pants/goal/stats_aggregator.py
  src/python/pants/goal/stats_aggregator_integration_test.py
Labels: category:new feature

#20539 docs: provide example of having a --option in [cli.alias]
  src/python/pants/option/alias.py
Labels: category:documentation

#20547 fix pants.log location in docs
  docs/docs/using-pants/using-pants-in-ci.mdx
  src/python/pants/engine/streaming_workunit_handler.py
Labels: category:documentation

#20546 Fix reference to default_run_goal_use_sandbox option in docs.
  src/python/pants/backend/python/target_types.py
Labels: category:documentation

#20543 javascript: fix running scripts with yarn
  src/python/pants/backend/javascript/run/rules.py
  src/python/pants/backend/javascript/run/rules_test.py
Labels: category:bugfix

#20530 Docker: Add `full_directory` interpolation value for repository configuration.
  docs/docs/docker/tagging-docker-images.mdx
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/subsystems/docker_options.py
Labels: category:new feature

#20480 stop swallowing warnings from Pex by default
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_environment.py
Labels: category:bugfix, backend: Python

#20551 add more module mappings for popular packages
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:new feature

#20553 Prepare 2.20.0a0
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20488 run `terraform plan` when setting `--dry-run` flag on `experimental-deploy` goal
  docs/docs/helm/deployments.mdx
  docs/docs/terraform/index.mdx
  src/python/pants/backend/helm/goals/deploy.py
  src/python/pants/backend/helm/goals/deploy_test.py
  src/python/pants/backend/helm/subsystems/helm.py
  src/python/pants/backend/terraform/goals/deploy.py
  src/python/pants/backend/terraform/goals/deploy_test.py
  src/python/pants/core/goals/deploy.py
Labels: category:new feature

#20555 Add all new Ruff backends to list of plugins
  src/python/pants/bin/BUILD
Labels: needs-cherrypick, category:bugfix, backend: Python

#20556 Add all new Ruff backends to list of plugins (Cherry-pick of #20555)
  src/python/pants/bin/BUILD
Labels: category:bugfix

#20557 doc: tweaks.
  docs/docs/python/overview/pex.mdx
  docs/docs/using-pants/key-concepts/options.mdx
Labels: needs-cherrypick, category:internal

#20554 Remove asm -compiling-runtime flag for go 1.22+ compatible versions
  src/python/pants/backend/go/util_rules/assembly.py
Labels: needs-cherrypick, backend: Go, category:bugfix

#20560 Prepare 2.19.1rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20562 Remove asm -compiling-runtime flag for go 1.22+ compatible versions (Cherry-pick of #20554)
  src/python/pants/backend/go/util_rules/assembly.py
Labels: category:bugfix

#20563 Remove asm -compiling-runtime flag for go 1.22+ compatible versions (Cherry-pick of #20554)
  src/python/pants/backend/go/util_rules/assembly.py
Labels: category:bugfix

#20561 Remove asm -compiling-runtime flag for go 1.22+ compatible versions (Cherry-pick of #20554)
  src/python/pants/backend/go/util_rules/assembly.py
Labels: category:bugfix

#20544 Restructure JVM docs.
  docs/docs/introduction/welcome-to-pants.mdx
  docs/docs/java-and-scala/_category_.json
  docs/docs/jvm/_category_.json
  docs/docs/jvm/java-and-scala.mdx
  docs/docs/jvm/kotlin.mdx
  docs/docs/using-pants/key-concepts/backends.mdx
  docs/docs/using-pants/troubleshooting-common-issues.mdx
  src/python/pants/notes/2.19.x.md
Labels: needs-cherrypick, category:documentation

#20549 Inline multiple config files into options sources.
  src/rust/engine/client/src/client_tests.rs
  src/rust/engine/client/src/main.rs
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/pantsd/src/pantsd_testing.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: category:internal

#20567 upgrade to Rust v1.76.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/env_tests.rs
  src/rust/engine/options/src/parse_tests.rs
  src/rust/engine/rust-toolchain
Labels: category:internal

#20569 A convenience script for previewing docs changes.
  build-support/preview_docs.sh
Labels: category:internal

#20564 Restructure JVM docs. (Cherry-pick of #20544)
  docs/docs/introduction/welcome-to-pants.mdx
  docs/docs/java-and-scala/_category_.json
  docs/docs/jvm/_category_.json
  docs/docs/jvm/java-and-scala.mdx
  docs/docs/jvm/kotlin.mdx
  docs/docs/using-pants/key-concepts/backends.mdx
  docs/docs/using-pants/troubleshooting-common-issues.mdx
  src/python/pants/notes/2.19.x.md
Labels: category:documentation

#20580 Fix update build files formatter selection
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: needs-cherrypick, category:bugfix, backend: Python

#20582 Fix update build files formatter selection (Cherry-pick of #20580)
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/goals/update_build_files_test.py
Labels: category:bugfix

#20566 docs: export dependency graph as adjacency list
  docs/docs/using-pants/project-introspection.mdx
Labels: needs-cherrypick, category:documentation

#20585 docs: export dependency graph as adjacency list (Cherry-pick of #20566)
  docs/docs/using-pants/project-introspection.mdx
Labels: category:documentation

#20583 Update `doc_url` calls for new website
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/target_types.py
  src/python/pants/backend/codegen/thrift/target_types.py
  src/python/pants/backend/codegen/utils.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/python/packaging/pyoxidizer/target_types.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/repos.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/twine.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/local_dists.py
  src/python/pants/backend/python/util_rules/local_dists_pep660.py
  src/python/pants/backend/python/util_rules/package_dists.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/bin/pants_runner.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/util_rules/external_tool.py
  src/python/pants/core/util_rules/subprocess_environment.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
  src/python/pants/engine/target.py
  src/python/pants/goal/anonymous_telemetry.py
  src/python/pants/help/help_integration_test.py
  src/python/pants/init/logging.py
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/option/global_options.py
  src/python/pants/source/source_root.py
  src/python/pants/util/docutil.py
  src/python/pants/util/docutil_test.py
  src/python/pants/vcs/changed.py
  src/rust/engine/src/nodes.rs
Labels: needs-cherrypick, category:documentation

#20588 Update `doc_url` calls for new website (Cherry-pick of #20583)
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/target_types.py
  src/python/pants/backend/codegen/thrift/target_types.py
  src/python/pants/backend/codegen/utils.py
  src/python/pants/backend/docker/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/python/packaging/pyoxidizer/target_types.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/subsystems/repos.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/twine.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
  src/python/pants/backend/python/util_rules/local_dists.py
  src/python/pants/backend/python/util_rules/local_dists_pep660.py
  src/python/pants/backend/python/util_rules/package_dists.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/bin/pants_runner.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/util_rules/external_tool.py
  src/python/pants/core/util_rules/subprocess_environment.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/parser_test.py
  src/python/pants/engine/target.py
  src/python/pants/goal/anonymous_telemetry.py
  src/python/pants/help/help_integration_test.py
  src/python/pants/init/logging.py
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/option/global_options.py
  src/python/pants/source/source_root.py
  src/python/pants/util/docutil.py
  src/python/pants/util/docutil_test.py
  src/python/pants/vcs/changed.py
  src/rust/engine/src/nodes.rs
Labels: category:documentation

#20540 javascript: package yarn v2
  src/python/pants/backend/javascript/nodejs_project.py
  src/python/pants/backend/javascript/nodejs_project_test.py
Labels: category:bugfix

#20587 upgrade Pex to 2.2.1
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:internal, backend: Python

#20513 Make default module mapping logic consistent and easy to understand
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
  src/python/pants/backend/python/dependency_inference/module_mapper.py
  src/python/pants/backend/python/dependency_inference/module_mapper_test.py
Labels: category:internal, backend: Python

#20590 Silence warnings from Pex by default, for now
  pants.toml
  src/python/pants/backend/python/util_rules/pex_cli_test.py
  src/python/pants/backend/python/util_rules/pex_environment.py
Labels: needs-cherrypick, category:bugfix

#20593 Silence warnings from Pex by default, for now (Cherry-pick of #20590)
  pants.toml
  src/python/pants/backend/python/util_rules/pex_cli_test.py
  src/python/pants/backend/python/util_rules/pex_environment.py
Labels: category:bugfix

#20574 Begin adding goal to assist with the call-by-name `@rule` syntax migration.
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/goal/builtins.py
  src/python/pants/goal/migrate_call_by_name.py
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/python.rs
Labels: category:internal

#20602 Fix direct_url in python PEP660 editable wheels (Cherry-pick of #20486)
  src/python/pants/backend/python/util_rules/dists.py
  src/python/pants/backend/python/util_rules/dists_test.py
  src/python/pants/backend/python/util_rules/local_dists_pep660.py
  src/python/pants/backend/python/util_rules/local_dists_pep660_test.py
  src/python/pants/backend/python/util_rules/package_dists.py
Labels: category:bugfix

#20601 python-infer: respect ignore pragma w/ strings (Cherry-pick of #20477)
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: category:bugfix

#20599 python-infer: Avoid false positive strings (Cherry-pick of #20472)
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies.py
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
Labels: category:bugfix

#20581 Resolve adhoc_tool, code_quality_tool execution dependencies relative to target location
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/code_quality_tool_integration_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: needs-cherrypick, category:bugfix

#20608 Resolve adhoc_tool, code_quality_tool execution dependencies relative to target location (Cherry-pick of #20581)
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/code_quality_tool_integration_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: category:bugfix

#20604 Document the need for migrating tool to user lockfiles for export
  docs/docs/python/overview/lockfiles.mdx
  docs/docs/using-pants/setting-up-an-ide.mdx
  src/python/pants/core/goals/export.py
Labels: needs-cherrypick, category:documentation, backend: Python

#20614 Document the need for migrating tool to user lockfiles for export (Cherry-pick of #20604)
  docs/docs/python/overview/lockfiles.mdx
  docs/docs/using-pants/setting-up-an-ide.mdx
  src/python/pants/core/goals/export.py
Labels: category:documentation

#20613 Document the need for migrating tool to user lockfiles for export (Cherry-pick of #20604)
  docs/docs/python/overview/lockfiles.mdx
  docs/docs/using-pants/setting-up-an-ide.mdx
  src/python/pants/core/goals/export.py
Labels: category:documentation

#20615 Document the need for migrating tool to user lockfiles for export (Cherry-pick of #20604)
  docs/docs/python/overview/lockfiles.mdx
  docs/docs/using-pants/setting-up-an-ide.mdx
  src/python/pants/core/goals/export.py
Labels: category:documentation

#20607 allow passing extra docker run args to docker_image
  src/python/pants/backend/docker/goals/run_image.py
  src/python/pants/backend/docker/goals/run_image_integration_test.py
  src/python/pants/backend/docker/target_types.py
Labels: category:new feature, backend: Docker

#20619 Remove now-expired deprecated `python_awslambda` alias
  src/python/pants/backend/awslambda/python/target_types.py
Labels: category:user api change

#20612 Prepare 2.18.3rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20597 add new default module mappings for py-healthcheck
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:new feature

#20616 Extend 2.21 deprecations: remote_oauth_bearer_token_path, crossversion=partial
  src/python/pants/backend/scala/target_types.py
  src/python/pants/option/global_options.py
Labels: needs-cherrypick, category:internal

#20623 Extend 2.21 deprecations: remote_oauth_bearer_token_path, crossversion=partial (Cherry-pick of #20616)
  src/python/pants/backend/scala/target_types.py
  src/python/pants/option/global_options.py
Labels: category:internal

#20611 Prepare 2.19.1rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20610 Prepare 2.20.0rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20609 Prepare 2.21.0.dev0
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20598 use explicit Pex options for package "binary-ness"
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
Labels: category:new feature, backend: Python

#20629 docs: Fix GitHub brand notation
  build-support/common.sh
  docs/docs/contributions/releases/github-actions-macos-arm64-runners.mdx
  docs/docs/contributions/releases/release-process.mdx
  docs/docs/docker/index.mdx
  docs/docs/using-pants/using-pants-in-ci.mdx
Labels: category:documentation

#20626 Split skip ruff field into two
  src/python/pants/backend/BUILD
  src/python/pants/backend/build_files/fmt/ruff/integration_test.py
  src/python/pants/backend/build_files/fmt/ruff/register.py
  src/python/pants/backend/experimental/python/lint/ruff/check/register.py
  src/python/pants/backend/experimental/python/lint/ruff/format/register.py
  src/python/pants/backend/python/lint/ruff/check/BUILD
  src/python/pants/backend/python/lint/ruff/check/rules.py
  src/python/pants/backend/python/lint/ruff/check/skip_field.py
  src/python/pants/backend/python/lint/ruff/check_rules.py
  src/python/pants/backend/python/lint/ruff/common.py
  src/python/pants/backend/python/lint/ruff/format/BUILD
  src/python/pants/backend/python/lint/ruff/format/rules.py
  src/python/pants/backend/python/lint/ruff/format/skip_field.py
  src/python/pants/backend/python/lint/ruff/rules_integration_test.py
  src/python/pants/backend/python/lint/ruff/skip_field.py
  src/python/pants/backend/python/lint/ruff/subsystem.py
  src/python/pants/core/goals/update_build_files.py
Labels: needs-cherrypick, category:new feature, backend: Python

#20365 Regenerate all Python tool lock-files (updating many) and update to pip_version = 24.0, for Py 3.12 support
  src/python/pants/backend/cc/lint/clangformat/clangformat.lock
  src/python/pants/backend/codegen/protobuf/python/grpclib.lock
  src/python/pants/backend/codegen/protobuf/python/mypy_protobuf.lock
  src/python/pants/backend/docker/subsystems/dockerfile.lock
  src/python/pants/backend/helm/subsystems/k8s_parser.lock
  src/python/pants/backend/helm/subsystems/post_renderer.lock
  src/python/pants/backend/python/lint/add_trailing_comma/add_trailing_comma.lock
  src/python/pants/backend/python/lint/autoflake/autoflake.lock
  src/python/pants/backend/python/lint/bandit/bandit.lock
  src/python/pants/backend/python/lint/black/black.lock
  src/python/pants/backend/python/lint/docformatter/docformatter.lock
  src/python/pants/backend/python/lint/docformatter/subsystem.py
  src/python/pants/backend/python/lint/flake8/flake8.lock
  src/python/pants/backend/python/lint/isort/isort.lock
  src/python/pants/backend/python/lint/pydocstyle/pydocstyle.lock
  src/python/pants/backend/python/lint/pylint/pylint.lock
  src/python/pants/backend/python/lint/pyupgrade/pyupgrade.lock
  src/python/pants/backend/python/lint/ruff/ruff.lock
  src/python/pants/backend/python/lint/yapf/yapf.lock
  src/python/pants/backend/python/packaging/pyoxidizer/pyoxidizer.lock
  src/python/pants/backend/python/subsystems/coverage_py.lock
  src/python/pants/backend/python/subsystems/debugpy.lock
  src/python/pants/backend/python/subsystems/ipython.lock
  src/python/pants/backend/python/subsystems/pytest.lock
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/setuptools.lock
  src/python/pants/backend/python/subsystems/setuptools_scm.lock
  src/python/pants/backend/python/subsystems/twine.lock
  src/python/pants/backend/python/typecheck/mypy/mypy.lock
  src/python/pants/backend/python/typecheck/pytype/pytype.lock
  src/python/pants/backend/terraform/hcl2.lock
  src/python/pants/backend/tools/semgrep/semgrep.lock
  src/python/pants/backend/tools/yamllint/yamllint.lock
Labels: category:user api change
