Repository pantsbuild/pants, pull requests merged in 2024-09, with the labels that each got.

#21345 typescript: handle tsconfig.json files that are in non-standard JSON format
  src/python/pants/backend/typescript/tsconfig.py
  src/python/pants/backend/typescript/tsconfig_test.py
Labels: category:internal, backend: JavaScript, release-notes:not-required

#21370 do not fetch path to getent bin
  src/python/pants/backend/terraform/tool.py
Labels: category:bugfix, backend: Terraform, release-notes:not-required

#21187 Update default Node version to 22.6.0
  docs/notes/2.23.x.md
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool_test.py
Labels: category:user api change, backend: JavaScript

#21374 Rename some intrinsics.
  docs/notes/2.23.x.md
  src/python/pants/backend/build_files/fix/deprecations/renamed_fields_rules.py
  src/python/pants/backend/build_files/fix/deprecations/renamed_targets_rules.py
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
  src/python/pants/backend/cc/dependency_inference/rules.py
  src/python/pants/backend/cc/lint/clangformat/rules.py
  src/python/pants/backend/cue/rules.py
  src/python/pants/backend/debian/rules.py
  src/python/pants/backend/makeself/goals/package.py
  src/python/pants/backend/makeself/subsystem.py
  src/python/pants/backend/nfpm/rules.py
  src/python/pants/backend/nfpm/util_rules/generate_config.py
  src/python/pants/backend/nfpm/util_rules/sandbox.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/vcs_versioning.py
  src/python/pants/backend/scala/lint/scalafix/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/backend/sql/lint/sqlfluff/rules.py
  src/python/pants/backend/tools/semgrep/rules.py
  src/python/pants/backend/tools/trufflehog/rules.py
  src/python/pants/backend/tools/yamllint/rules.py
  src/python/pants/backend/typescript/tsconfig.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/intrinsics.py
  src/python/pants/goal/migrate_call_by_name_test.py
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/intrinsics/process.rs
Labels: category:plugin api change

#21373 docs: Fix duped v1.pantsbuild.org link
  docs/docs/introduction/welcome-to-pants.mdx
Labels: category:documentation, release-notes:not-required

#21375 A execute_process_or_raise rule alias.
  docs/notes/2.23.x.md
  src/python/pants/backend/debian/rules.py
  src/python/pants/backend/java/lint/google_java_format/rules.py
  src/python/pants/backend/kotlin/lint/ktlint/rules.py
  src/python/pants/backend/makeself/goals/package.py
  src/python/pants/backend/makeself/subsystem.py
  src/python/pants/backend/nfpm/rules.py
  src/python/pants/backend/scala/lint/scalafmt/rules.py
  src/python/pants/engine/process.py
Labels: category:plugin api change

#21378 Prepare 2.22.0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21381 upgrade to Rust v1.81.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/pantsd/src/lib.rs
  src/rust/engine/rust-toolchain
Labels: category:internal, release-notes:not-required

#21365 Terraform: downgrade python-hcl2 from 4.3.2 to 4.3.0 to work around parsing issues (Cherry-pick of #21361)
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/hcl2.lock
Labels: category:bugfix, release-notes:not-required

#21377 system_binaries: output errors from failed candidate binaries
  src/python/pants/backend/adhoc/run_system_binary.py
  src/python/pants/backend/adhoc/run_system_binary_integration_test.py
Labels: category:bugfix, release-notes:not-required

#21277 adhoc/shell: check whether or not outputs were actually captured
  3rdparty/tools/act/BUILD
  docs/notes/2.23.x.md
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: category:new feature

#21384 Bump PyGithub release management dep: 2.0.0rc1 -> 2.4.0
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
Labels: category:internal

#21327 Implement complementary TSX backend
  docs/notes/2.23.x.md
  pants.toml
  src/python/pants/backend/experimental/typescript/register.py
  src/python/pants/backend/tsx/BUILD
  src/python/pants/backend/tsx/__init__.py
  src/python/pants/backend/tsx/goals/BUILD
  src/python/pants/backend/tsx/goals/__init__.py
  src/python/pants/backend/tsx/goals/tailor.py
  src/python/pants/backend/tsx/goals/tailor_test.py
  src/python/pants/backend/tsx/target_types.py
  src/python/pants/backend/typescript/target_types.py
  testprojects/src/ts/hello_react_ts/BUILD
  testprojects/src/ts/hello_react_ts/babel.config.json
  testprojects/src/ts/hello_react_ts/package-lock.json
  testprojects/src/ts/hello_react_ts/package.json
  testprojects/src/ts/hello_react_ts/src/App.tsx
  testprojects/src/ts/hello_react_ts/src/BUILD
  testprojects/src/ts/hello_react_ts/src/index.tsx
  testprojects/src/ts/hello_react_ts/src/setupTests.ts
  testprojects/src/ts/hello_react_ts/src/test/BUILD
  testprojects/src/ts/hello_react_ts/src/test/index.test.tsx
  testprojects/src/ts/hello_react_ts/tsconfig.json
Labels: category:new feature, backend: JavaScript

#21379 use latest tagged expose-pythons pantsbuild action
  .github/workflows/cache_comparison.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21360 docs: mention that --changed-* filters only apply to first party dependencies
  docs/docs/using-pants/advanced-target-selection.mdx
Labels: category:documentation, release-notes:not-required

#21380 Add new `uv_requirements` macro for parsing `uv` dev dependencies
  docs/notes/2.23.x.md
  src/python/pants/backend/python/macros/uv_requirements.py
  src/python/pants/backend/python/macros/uv_requirements_test.py
  src/python/pants/backend/python/register.py
Labels: category:new feature, backend: Python

#21387 announce (and warn about) end of Python 2.7 support starting in v2.24.x
  docs/docs/python/overview/interpreter-compatibility.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/python/lint/flake8/subsystem_test.py
  src/python/pants/backend/python/lint/pylint/subsystem_test.py
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/subsystems/setup_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/backend/python/util_rules/interpreter_constraints_test.py
Labels: category:user api change

#21383 Prepare 2.23.0a0
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21395 Add a changelog file for 2.24
  docs/notes/2.24.x.md
Labels: category:internal

#21397 python: a mandatory option is not really "advanced" (interpreter_constraints)
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:internal, release-notes:not-required

#21390 system_binary: log a warning when candidate binaries fail
  docs/notes/2.24.x.md
  src/python/pants/backend/adhoc/run_system_binary.py
  src/python/pants/backend/adhoc/run_system_binary_integration_test.py
  src/python/pants/backend/adhoc/target_types.py
Labels: category:new feature

#21392 pass along query parameters to s3:// urls
  docs/notes/2.23.x.md
  src/python/pants/backend/url_handlers/s3/integration_test.py
  src/python/pants/backend/url_handlers/s3/register.py
Labels: category:bugfix

#21314 Upgrade `setuptools` to fix CVE
  docs/notes/2.24.x.md
  src/python/pants/backend/python/subsystems/setuptools.lock
  src/python/pants/backend/python/subsystems/setuptools.py
  src/python/pants/core/goals/publish_test.py
Labels: category:internal, backend: Python

#21408 fix release notes version for #21392
  docs/notes/2.23.x.md
  docs/notes/2.24.x.md
Labels: category:internal

#21396 upgrade GitHub Actions image used for most CI jobs and remove Python 2.7 CI testing
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  docs/notes/2.24.x.md
  src/python/pants/backend/python/dependency_inference/parse_python_dependencies_test.py
  src/python/pants/backend/python/framework/django/dependency_inference_test.py
  src/python/pants/backend/python/framework/django/detect_apps_test.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
  src/python/pants/backend/python/util_rules/dists_test.py
  src/python/pants/backend/python/util_rules/local_dists_pep660_test.py
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21245 adhoc/shell: allow cache scope to be configured for process executions
  docs/notes/2.24.x.md
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
Labels: category:new feature

#21400 bump default version of pip to support Python 3.13
  docs/notes/2.24.x.md
  src/python/pants/backend/python/subsystems/setup.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:new feature

#21402 upper bounds on s3 urllib3 version to the s3 handler easier to use
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
Labels: category:internal, release-notes:not-required

#21414 Silence macOS 10.15/11 errors for the Pants repo itself
  pants.toml
Labels: category:internal

#21415 Extend deprecation of [export].py_hermetic_scripts to 2.26
  src/python/pants/backend/python/goals/export.py
Labels: category:internal

#21407 diff with previous versions when generating builtin lockfiles
  build-support/bin/generate_builtin_lockfiles.py
Labels: category:internal, release-notes:not-required

#21420 Don't include macOS 12 in "_before_ 12" deprecation check
  src/python/pants/util/osutil.py
Labels: needs-cherrypick, category:internal

#21418 Prepare 2.21.2rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21421 Don't include macOS 12 in "_before_ 12" deprecation check (Cherry-pick of #21420)
  src/python/pants/util/osutil.py
Labels: category:internal

#21410 Track consumption of command-line args in the rust parser.
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/native_options.py
  src/python/pants/option/parser.py
  src/rust/engine/Cargo.lock
  src/rust/engine/options/Cargo.toml
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/id.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/src/externs/options.rs
Labels: needs-cherrypick, category:internal

#21419 Prepare 2.22.1rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21394 let users point a bazooka a their foot wtih SetupKwargs plugins
  docs/notes/2.23.x.md
  src/python/pants/backend/python/util_rules/package_dists.py
Labels: category:plugin api change

#21403 introduce `SubjectPath` to namespace paths between workspace and system
  src/rust/engine/src/context.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/nodes/digest_file.rs
  src/rust/engine/src/nodes/mod.rs
  src/rust/engine/src/nodes/path_metadata.rs
  src/rust/engine/src/nodes/read_link.rs
  src/rust/engine/src/nodes/scandir.rs
Labels: category:internal, release-notes:not-required

#21404 support path metadata lookups of local system paths
  docs/notes/2.24.x.md
  src/python/pants/engine/fs.py
  src/python/pants/engine/fs_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/nodes/mod.rs
  src/rust/engine/src/nodes/path_metadata.rs
Labels: category:plugin api change

#21406 avoid negatively caching path lookups for binary path requests
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/core/util_rules/system_binaries_test.py
Labels: category:bugfix, release-notes:not-required

#21424 Track unconsumed args by positional context.
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/native_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_test.py
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/src/externs/options.rs
Labels: needs-cherrypick, category:internal

#21423 Track consumption of command-line args in the rust parser. (Cherry-pick of #21410)
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/native_options.py
  src/python/pants/option/parser.py
  src/rust/engine/Cargo.lock
  src/rust/engine/options/Cargo.toml
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/id.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#21427 Track unconsumed args by positional context. (cherry-pick of #21424)
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/native_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_test.py
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#21412 Prepare 2.24.0.dev0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21331 upgrade to tonic v0.12.x and hyper v1.0 (and related crates)
  src/python/pants/bin/pants_loader.py
  src/python/pants/engine/internals/native_engine.pyi
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/client/Cargo.toml
  src/rust/engine/client/src/main.rs
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/grpc_util/src/channel.rs
  src/rust/engine/grpc_util/src/hyper_util.rs
  src/rust/engine/grpc_util/src/lib.rs
  src/rust/engine/grpc_util/src/metrics.rs
  src/rust/engine/grpc_util/src/tls.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store_tests.rs
  src/rust/engine/src/downloads.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/testutil/mock/Cargo.toml
  src/rust/engine/testutil/mock/src/cas.rs
  src/rust/engine/testutil/mock/src/execution_server.rs
Labels: category:internal, release-notes:not-required

#21425 Update to Pex 2.19.1
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/notes/2.24.x.md
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:new feature

#21158 upgrade mypy to v1.10.1
  3rdparty/python/mypy-requirements.txt
  3rdparty/python/mypy.lock
  pants-plugins/pants_explorer/server/graphql/query/targets.py
  src/python/pants/backend/go/util_rules/coverage_profile_test.py
  src/python/pants/backend/nfpm/util_rules/sandbox.py
  src/python/pants/backend/python/macros/common_requirements_rule.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/python/util_rules/lockfile_metadata.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/terraform/hcl2_parser.py
  src/python/pants/bsp/protocol.py
  src/python/pants/bsp/protocol_test.py
  src/python/pants/bsp/testutil.py
  src/python/pants/core/goals/multi_tool_goal_helper.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
  src/python/pants/core/util_rules/unowned_dependency_behavior.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/defaults_test.py
  src/python/pants/engine/internals/parametrize_test.py
  src/python/pants/engine/internals/parser.py
  src/python/pants/engine/internals/selectors_test.py
  src/python/pants/engine/target.py
  src/python/pants/engine/unions_test.py
  src/python/pants/option/custom_types.py
  src/python/pants/option/global_options.py
  src/python/pants/option/option_types.py
  src/python/pants/util/memo.py
  src/python/pants/util/meta.py
  src/python/pants/util/pip_requirement.py
  src/python/pants/util/strutil.py
Labels: category:internal, release-notes:not-required

#21430 upgrade `bollard` crate
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal, release-notes:not-required

#21434 upgrade `tonic`, `prost`, and `tower` crate releases
  src/rust/engine/Cargo.lock
Labels: category:internal, release-notes:not-required

#21385 Switch to using the native options parser values
  docs/notes/2.23.x.md
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/help/flag_error_help_printer.py
  src/python/pants/help/help_integration_test.py
  src/python/pants/option/native_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_integration_test.py
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
  src/rust/engine/src/externs/options.rs
Labels: category:user api change

#21433 Fix options parser discrepancy due to repeated evaluation of `.pants.rc` (Cherry-pick of #21118)
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_test.py
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
Labels: category:bugfix, release-notes:not-required

#21422 Rise forth the PBS Provider from the ashes of bitrot
  docs/docs/contributions/development/maintenance-tasks-and-scripts.mdx
  docs/notes/2.24.x.md
  src/python/pants/backend/python/providers/experimental/python_build_standalone/BUILD
  src/python/pants/backend/python/providers/experimental/python_build_standalone/__init__.py
  src/python/pants/backend/python/providers/experimental/python_build_standalone/register.py
  src/python/pants/backend/python/providers/python_build_standalone/BUILD
  src/python/pants/backend/python/providers/python_build_standalone/__init__.py
  src/python/pants/backend/python/providers/python_build_standalone/rules.py
  src/python/pants/backend/python/providers/python_build_standalone/rules_integration_test.py
  src/python/pants/backend/python/providers/python_build_standalone/scripts/BUILD
  src/python/pants/backend/python/providers/python_build_standalone/scripts/__init__.py
  src/python/pants/backend/python/providers/python_build_standalone/scripts/generate_urls.py
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
  src/python/pants/bin/BUILD
Labels: category:new feature

#21290 add new cache scope to cache locally only
  docs/notes/2.24.x.md
  src/python/pants/backend/java/compile/javac.py
  src/python/pants/backend/scala/compile/scalac.py
  src/python/pants/engine/process.py
  src/python/pants/jvm/strip_jar/strip_jar.py
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/src/nodes/mod.rs
Labels: category:performance

#21442 Delay options system switch to 2.24.x.
  docs/notes/2.23.x.md
  docs/notes/2.24.x.md
Labels: category:internal

#21417 Replace macOS 10.15 x86-64 self-hosted runner with 12 GH-hosted
  .github/workflows/clear_self_hosted_persistent_caches.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  docs/notes/2.24.x.md
  src/python/pants_release/generate_github_workflows.py
Labels: category:user api change

#21446 Do not show equals sign in help for short options
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
Labels: category:documentation, release-notes:not-required

#21399 [fix] propagate peek additional_info to output
  docs/notes/2.24.x.md
  src/python/pants/backend/project_info/peek.py
Labels: category:bugfix

#21435 upgrade `tokio` and related crates
  src/rust/engine/Cargo.lock
Labels: category:internal, release-notes:not-required

#21436 upgrade `bytes` crate
  src/rust/engine/Cargo.lock
Labels: category:internal, release-notes:not-required

#21437 upgrade `serde` and related crates
  src/rust/engine/Cargo.lock
Labels: category:internal, release-notes:not-required

#21452 golang: fix exception when coverage enabled and external tests import the base package
  docs/notes/2.24.x.md
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
Labels: needs-cherrypick, backend: Go, category:bugfix, release-notes:not-required

#21453 golang: fix exception when coverage enabled and external tests import the base package (Cherry-pick of #21452)
  docs/notes/2.23.x.md
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
Labels: category:bugfix

#21455 golang: fix exception when coverage enabled and external tests import the base package (Cherry-pick of #21452)
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
Labels: category:bugfix

#21454 golang: fix exception when coverage enabled and external tests import the base package (Cherry-pick of #21452)
  docs/notes/2.22.x.md
  src/python/pants/backend/go/goals/test_test.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
Labels: category:bugfix

#21456 Prepare 2.23.0a1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21457 upgrade `tonic` and friends plus rustls-native-certs to v0.8
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/grpc_util/build.rs
  src/rust/engine/grpc_util/src/tls.rs
  src/rust/engine/protos/build.rs
Labels: category:internal, release-notes:not-required

#21458 upgrade `regex` crate and friends
  src/rust/engine/Cargo.lock
Labels: category:internal, release-notes:not-required
