Repository pantsbuild/pants, pull requests merged in 2024-11, with the labels that each got.

#21599 Don't coerce the option default to a RankedValue.
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/option/parser.py
Labels: category:internal

#21600 Prepare 2.21.2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21602 Prepare 2.24.0.dev3
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21604 Prepare 2.22.1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21609 Add platform_specific_behavior tag to test targets that use mark
  src/python/pants/backend/build_files/fmt/black/BUILD
  src/python/pants/backend/build_files/fmt/ruff/BUILD
  src/python/pants/backend/build_files/fmt/yapf/BUILD
  src/python/pants/backend/sql/lint/sqlfluff/BUILD
Labels: release-notes:not-required

#21551 fix: use cp/mv more resiliently during pbs bootstrap
  src/python/pants/backend/python/providers/python_build_standalone/BUILD
  src/python/pants/backend/python/providers/python_build_standalone/rules.py
  src/python/pants/backend/python/providers/python_build_standalone/rules_integration_test.py
Labels: category:bugfix, backend: Python, release-notes:not-required

#21574 "open" support for experimental-explorer on Linux
  src/python/pants/core/util_rules/system_binaries.py
Labels: release-notes:not-required

#21613 Add new python-build-standalone versions, including 3.13.0
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: release-notes:not-required

#21523 Use the major version of golang at package time
  docs/notes/2.24.x.md
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_test.py
  src/python/pants/backend/go/util_rules/goroot.py
Labels: needs-cherrypick, backend: Go, category:bugfix

#21618 Use the major version of golang at package time (Cherry-pick of #21523)
  docs/notes/2.23.x.md
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_test.py
  src/python/pants/backend/go/util_rules/goroot.py
Labels: category:bugfix

#21617 Use the major version of golang at package time (Cherry-pick of #21523)
  docs/notes/2.22.x.md
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/build_pkg_test.py
  src/python/pants/backend/go/util_rules/goroot.py
Labels: category:bugfix

#21623 Revert "Replace macOS 10.15 x86-64 self-hosted runner with 12 GH-hosted (#21417)"
  .github/workflows/clear_self_hosted_persistent_caches.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: release-notes:not-required

#21610 Mark one test from mostly-non-JS/JVM backends as platform-specific behaviour, test on macOS
  src/python/pants/backend/build_files/fmt/buildifier/BUILD
  src/python/pants/backend/build_files/fmt/buildifier/rules_integration_test.py
  src/python/pants/backend/codegen/protobuf/lint/buf/BUILD
  src/python/pants/backend/codegen/protobuf/lint/buf/lint_rules_integration_test.py
  src/python/pants/backend/cue/goals/BUILD
  src/python/pants/backend/cue/goals/fix_test.py
  src/python/pants/backend/helm/check/kubeconform/BUILD
  src/python/pants/backend/helm/check/kubeconform/deployment_test.py
  src/python/pants/backend/helm/goals/BUILD
  src/python/pants/backend/helm/goals/package_test.py
  src/python/pants/backend/javascript/goals/BUILD
  src/python/pants/backend/javascript/goals/export_test.py
  src/python/pants/backend/javascript/goals/test_integration_test.py
  src/python/pants/backend/makeself/goals/BUILD
  src/python/pants/backend/makeself/goals/package_run_integration_test.py
  src/python/pants/backend/nfpm/BUILD
  src/python/pants/backend/nfpm/rules_integration_test.py
  src/python/pants/backend/project_info/BUILD
  src/python/pants/backend/project_info/count_loc_test.py
  src/python/pants/backend/python/providers/pyenv/BUILD
  src/python/pants/backend/python/providers/pyenv/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pytype/BUILD
  src/python/pants/backend/python/typecheck/pytype/rules_integration_test.py
  src/python/pants/backend/shell/goals/BUILD
  src/python/pants/backend/shell/goals/test_test.py
  src/python/pants/backend/shell/lint/shellcheck/BUILD
  src/python/pants/backend/shell/lint/shellcheck/rules_integration_test.py
  src/python/pants/backend/shell/lint/shfmt/BUILD
  src/python/pants/backend/shell/lint/shfmt/rules_integration_test.py
  src/python/pants/backend/terraform/lint/tfsec/BUILD
  src/python/pants/backend/terraform/lint/tfsec/tfsec_integration_test.py
  src/python/pants/backend/tools/semgrep/BUILD
  src/python/pants/backend/tools/semgrep/rules_integration_test.py
  src/python/pants/backend/tools/taplo/BUILD
  src/python/pants/backend/tools/taplo/rules_integration_test.py
  src/python/pants/backend/tools/trufflehog/BUILD
  src/python/pants/backend/tools/trufflehog/rules_integration_test.py
  src/python/pants/backend/tools/yamllint/BUILD
  src/python/pants/backend/tools/yamllint/rules_integration_test.py
Labels: release-notes:not-required

#21620 Mark one test from hadolint and golangci_lint backends as platform-specific behaviour, test on macOS
  .github/workflows/test.yaml
  src/python/pants/backend/docker/lint/hadolint/BUILD
  src/python/pants/backend/docker/lint/hadolint/rules_integration_test.py
  src/python/pants/backend/go/lint/golangci_lint/BUILD
  src/python/pants/backend/go/lint/golangci_lint/rules_integration_test.py
  src/python/pants_release/generate_github_workflows.py
Labels: release-notes:not-required

#21611 Add annotation to untyped function causing mypy note
  src/python/pants/core/util_rules/external_tool_test.py
Labels: release-notes:not-required

#21628 Test the option value derivation details.
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
Labels: category:internal

#21630 Prepare 2.23.0rc3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21629 Use references to options Sources, instead of cloning.
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#21631 Pass derivation details through from Rust.
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/option/native_options.py
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#21634 Prepare 2.24.0a0
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21633 Make sure FirstPartyHelmDeploymentMapping doesn't get calculated if disabled
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/dependency_inference/deployment_test.py
Labels: needs-cherrypick, category:bugfix, release-notes:not-required

#21635 Make sure FirstPartyHelmDeploymentMapping doesn't get calculated if disabled (Cherry-pick of #21633)
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/dependency_inference/deployment_test.py
Labels: category:bugfix, release-notes:not-required

#21637 Create release notes for the 2.25.x series.
  docs/notes/2.25.x.md
Labels: category:internal

#21577 Turn off the legacy options parser.
  docs/notes/2.25.x.md
  src/python/pants/option/global_options.py
  src/python/pants/option/options.py
  src/python/pants/option/parser.py
Labels: category:internal

#21636 Make sure FirstPartyHelmDeploymentMapping doesn't get calculated if disabled (Cherry-pick of #21633)
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/dependency_inference/deployment_test.py
Labels: category:bugfix, release-notes:not-required

#21640 Delete the legacy parse_args() method
  src/python/pants/help/help_formatter_test.py
  src/python/pants/help/help_info_extracter.py
  src/python/pants/option/parser.py
Labels: category:internal

#21643 Rip out more parts of the legacy parser
  src/python/pants/help/help_formatter_test.py
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_tools_test.py
  src/python/pants/option/options.py
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
Labels: category:internal

#21641 Prepare 2.23.0rc4
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21632 Add information about workunit when failing to backtrack
  src/rust/engine/src/context.rs
  src/rust/engine/workunit_store/src/lib.rs
Labels: diagnostics, release-notes:not-required

#21645 Move option registration validation earlier
  src/python/pants/help/help_formatter_test.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_tools_test.py
  src/python/pants/option/native_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
Labels: category:internal

#21652 Move native options parsing out of the legacy Parser
  src/python/pants/option/options.py
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
Labels: category:internal

#21653 Rename Parser to OptionRegistrar
  src/python/pants/help/help_formatter_test.py
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_tools_test.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/registrar.py
Labels: category:internal

#21662 Test on newer macOS 13, not deprecated macOS 12 (partial cherry-pick of #21655)
  .github/workflows/test.yaml
  src/python/pants/base/exception_sink_test.py
  src/python/pants_release/generate_github_workflows.py
Labels: release-notes:not-required

#21660 update the manylinux wheel glibc version to 2.28 (#21650)
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21670 use `GILProtected` to synchronize access to various `pyclass` types
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
Labels: category:internal, release-notes:not-required

#21661 Prepare 2.25.0.dev0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21666 Port config file validation to Rust.
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/native_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_integration_test.py
  src/rust/engine/Cargo.lock
  src/rust/engine/options/Cargo.toml
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#21667 use explicit setup-python versions over implicit expose- (Cherry-pick of #21568, #21582)
  .github/workflows/cache_comparison.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21664 Test on newer macOS 13, not deprecated macOS 12 (partial cherry-pick of #21655)
  .github/workflows/test.yaml
  src/python/pants/base/exception_sink_test.py
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21665 Allow python protobuf codegen export to coexist with namespace/host package
  docs/notes/2.25.x.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
Labels: needs-cherrypick, category:bugfix, backend: Python

#21642 Fix lockfile generation for shadowed resolves
  docs/notes/2.24.x.md
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/core/goals/generate_lockfiles.py
Labels: category:bugfix, backend: Python

#21672 Copy-edit 2.24's release notes, add some highlights
  docs/notes/2.24.x.md
Labels: needs-cherrypick

#21668 use explicit setup-python versions over implicit expose- (Cherry-pick of #21568, #21582)
  .github/workflows/cache_comparison.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21663 Test on newer macOS 13, not deprecated macOS 12 (partial cherry-pick of #21655)
  .github/workflows/test.yaml
  src/python/pants/base/exception_sink_test.py
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21657 PyO3: upgrade to v0.23.x
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/externs/address.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/nailgun.rs
  src/rust/engine/src/externs/options.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/externs/scheduler.rs
  src/rust/engine/src/externs/stdio.rs
  src/rust/engine/src/externs/target.rs
  src/rust/engine/src/interning.rs
  src/rust/engine/src/intrinsics/dep_inference.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/intrinsics/docker.rs
  src/rust/engine/src/intrinsics/process.rs
  src/rust/engine/src/nodes/snapshot.rs
  src/rust/engine/src/nodes/task.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21674 update PBS generate_urls.py housekeeping script with resolve and options
  3rdparty/python/BUILD
  3rdparty/python/pbs-script-requirements.lock
  3rdparty/python/pbs-script-requirements.txt
  pants.toml
  src/python/pants/backend/python/providers/python_build_standalone/scripts/BUILD
  src/python/pants/backend/python/providers/python_build_standalone/scripts/generate_urls.py
Labels: category:internal, release-notes:not-required

#21681 PyO3: migrate to using `IntoPyObject`
  src/rust/engine/src/externs/address.rs
  src/rust/engine/src/externs/dep_inference.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/externs/options.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/externs/target.rs
  src/rust/engine/src/intrinsics/dep_inference.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/intrinsics/process.rs
  src/rust/engine/src/nodes/snapshot.rs
  src/rust/engine/src/nodes/task.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21683 PyO3: Rename Pants-specific helper methods to remove "bound" from the name
  src/rust/engine/src/externs/engine_aware.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/intrinsics/docker.rs
  src/rust/engine/src/intrinsics/interactive_process.rs
  src/rust/engine/src/nodes/downloaded_file.rs
  src/rust/engine/src/nodes/execute_process.rs
  src/rust/engine/src/nodes/mod.rs
  src/rust/engine/src/nodes/snapshot.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21689 Simplify OptionParser fields.
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#21687 PyO3: introduce `PyComparedBool` type to simplify __richcmp__ methods
  src/rust/engine/src/externs/address.rs
  src/rust/engine/src/externs/dep_inference.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/externs/process.rs
  src/rust/engine/src/externs/target.rs
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21676 Allow python protobuf codegen export to coexist with namespace/host package (Cherry-pick of #21665)
  docs/notes/2.23.x.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
Labels: category:bugfix

#21675 Allow python protobuf codegen export to coexist with namespace/host package (Cherry-pick of #21665)
  docs/notes/2.24.x.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
Labels: category:bugfix

#21699 upgade to Rust v1.83.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/hashing/src/lib.rs
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/src/bounded.rs
  src/rust/engine/protos/src/conversions.rs
  src/rust/engine/rust-toolchain
  src/rust/engine/src/python.rs
Labels: category:internal, release-notes:not-required

#21703 PyO3: upgrade to v0.23.2
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal, release-notes:not-required
