Repository pantsbuild/pants, pull requests merged in 2024-01, with the labels that each got.

#20345 Use `GLOBAL` when required in toml in docs
  build-support/bin/generate_docs.py
Labels: needs-cherrypick, category:internal

#20367 Use `GLOBAL` when required in toml in docs (Cherry-pick of #20345)
  build-support/bin/generate_docs.py
Labels: category:internal

#20338 Move jvm `Coordinate` class to a separate module
  pants-plugins/internal_plugins/test_lockfile_fixtures/lockfile_fixture.py
  src/python/pants/backend/codegen/protobuf/scala/dependency_inference.py
  src/python/pants/backend/codegen/soap/java/dependency_inference.py
  src/python/pants/backend/kotlin/compile/kotlinc.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/kotlin/dependency_inference/rules.py
  src/python/pants/backend/kotlin/test/junit.py
  src/python/pants/backend/openapi/codegen/java/rules.py
  src/python/pants/backend/openapi/util_rules/pom_parser.py
  src/python/pants/backend/openapi/util_rules/pom_parser_test.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/backend/scala/resolve/lockfile.py
  src/python/pants/backend/scala/util_rules/versions.py
  src/python/pants/jvm/dependency_inference/artifact_mapper.py
  src/python/pants/jvm/goals/lockfile_test.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/resolve/common.py
  src/python/pants/jvm/resolve/coordinate.py
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/coursier_fetch_filter_test.py
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
  src/python/pants/jvm/resolve/coursier_fetch_test.py
  src/python/pants/jvm/resolve/jvm_tool.py
  src/python/pants/jvm/resolve/jvm_tool_test.py
  src/python/pants/jvm/shading/rules_integration_test.py
Labels: backend: JVM, category:internal

#20359 upgrade to Rust v1.75.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/client/src/client.rs
  src/rust/engine/dep_inference/src/javascript/tests.rs
  src/rust/engine/dep_inference/src/python/tests.rs
  src/rust/engine/fs/src/directory_tests.rs
  src/rust/engine/fs/src/posixfs_tests.rs
  src/rust/engine/fs/store/benches/store.rs
  src/rust/engine/fs/store/src/snapshot_ops_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/grpc_util/src/channel.rs
  src/rust/engine/process_execution/docker/src/docker_tests.rs
  src/rust/engine/process_execution/pe_nailgun/src/tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/local_tests.rs
  src/rust/engine/process_execution/src/switched.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/byte_store_tests.rs
  src/rust/engine/rust-toolchain
  src/rust/engine/sharded_lmdb/src/tests.rs
  src/rust/engine/workunit_store/src/tests.rs
Labels: category:internal

#20241 Fix: Include transitive dependencies for Terraform
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/dependencies_test.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/dependency_inference_test.py
Labels: needs-cherrypick, category:bugfix, backend: Terraform

#20371 Fix: Include transitive dependencies for Terraform (Cherry-pick of #20241)
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/dependencies_test.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/dependency_inference_test.py
Labels: category:bugfix

#20372 Fix: Include transitive dependencies for Terraform (Cherry-pick of #20241)
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/dependencies_test.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/dependency_inference_test.py
Labels: category:bugfix

#20370 Refactor rust config value conversion.
  src/rust/engine/options/src/config.rs
Labels: category:internal

#20355 fix: in-repo plugin requirements.txt not loading
  src/python/pants/init/options_initializer.py
  tests/python/pants_test/integration/plugin_requirements_integration_test.py
Labels: needs-cherrypick, category:bugfix

#20375 Prepare 2.18.2rc2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20376 Prepare 2.19.0rc4
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20377 Prepare 2.20.0.dev5
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20347 Update to Pex 2.1.155
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:performance

#20379 Parametrize the peg grammar for parsing list-valued options.
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
Labels: category:internal

#20385 Improve the cache nuking recommendation.
  docs/markdown/Using Pants/using-pants-in-ci.md
Labels: category:documentation

#20334 Update the docs on how to profile Pants.
  docs/markdown/Contributions/development/contributions-debugging.md
Labels: category:documentation

#20335 docs: update python test coverage docs
  docs/markdown/Python/python-goals/python-test-goal.md
Labels: category:documentation

#19925 plumb sh-boot through to pex_binary
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/target_types.py
Labels: category:new feature, backend: Python

#20391 Upgrade to PEX 2.1.156
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:performance

#20388 Support bool, float and lists of them in the rust options parser.
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/env_tests.rs
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
Labels: category:internal

#20398 Produce bool parsing error message idiomatically
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/env_tests.rs
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
Labels: category:internal

#20366 Add support for positional arguments in by-name `@rule` calls
  pants-plugins/pants_explorer/server/graphql/query/rules.py
  src/python/pants/engine/internals/engine_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/internals/rule_visitor_test.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/internals/scheduler_test.py
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/rules_test.py
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_printer.py
  src/python/pants/option/subsystem.py
  src/python/pants/testutil/rule_runner.py
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/rule_graph/src/rules.rs
  src/rust/engine/rule_graph/src/tests.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/python.rs
  src/rust/engine/src/scheduler.rs
  src/rust/engine/src/session.rs
  src/rust/engine/src/tasks.rs
Labels: category:plugin api change

#20403 Prepare 2.20.0.dev6
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20404 Rename 'environments' docs file/URL to be simpler
  docs/docs/getting-started/prerequisites.mdx
  docs/docs/python/overview/pex.mdx
  docs/docs/using-pants/environments.mdx
  docs/docs/using-pants/remote-caching-&-execution/index.mdx
  docs/docs/using-pants/remote-caching-&-execution/remote-execution.mdx
  docs/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx
Labels: category:documentation

#20405 Rename 'environments' docs file/URL to be simpler (cherry-pick of #20404)
  docs/docs/getting-started/prerequisites.mdx
  docs/docs/using-pants/environments.mdx
  docs/docs/using-pants/remote-caching-&-execution/index.mdx
  docs/docs/using-pants/remote-caching-&-execution/remote-execution.mdx
  docs/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx
Labels: category:documentation

#20406 Rename 'environments' docs file/URL to be simpler (cherry-pick of #20404)
  docs/docs/getting-started/prerequisites.mdx
  docs/docs/python/overview/pex.mdx
  docs/docs/using-pants/environments.mdx
  docs/docs/using-pants/remote-caching-&-execution/index.mdx
  docs/docs/using-pants/remote-caching-&-execution/remote-execution.mdx
  docs/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx
Labels: category:documentation

#20387 python-protobuf backend now support multiple protoc plugins.
  build-support/bin/generate_builtin_lockfiles.py
  docs/docs/python/integrations/protobuf-and-grpc.mdx
  src/python/pants/backend/codegen/protobuf/python/BUILD
  src/python/pants/backend/codegen/protobuf/python/grpclib.lock
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_module_mapper.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_module_mapper_test.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem_test.py
  src/python/pants/backend/codegen/protobuf/python/rules.py
  src/python/pants/backend/codegen/protobuf/python/rules_integration_test.py
Labels: category:new feature

#20408 Parse dict options in the rust options parser.
  src/python/pants/backend/python/subsystems/setup.py
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
Labels: category:internal

#20310 What's new in 2.19
  src/python/pants/notes/2.19.x.md
Labels: needs-cherrypick, category:documentation

#20409 What's new in 2.19 (Cherry-pick of #20310)
  src/python/pants/notes/2.19.x.md
Labels: category:documentation

#20271 Add jvm_index Option to Coursier Subsystem
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/jdk_rules_test.py
  src/python/pants/jvm/resolve/coursier_setup.py
Labels: backend: JVM, category:new feature

#20240 Add remote_provider = "..." option, replacing scheme-look-ups
  docs/docs/using-pants/remote-caching-&-execution/remote-caching.mdx
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/option/global_options.py
  src/python/pants/option/global_options_test.py
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/remote_tests.rs
  src/rust/engine/fs/store/src/tests.rs
  src/rust/engine/process_execution/remote/src/remote_cache_tests.rs
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/action_cache_tests.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/byte_store_tests.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/action_cache_tests.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store_tests.rs
  src/rust/engine/remote_provider/remote_provider_traits/Cargo.toml
  src/rust/engine/remote_provider/remote_provider_traits/src/lib.rs
  src/rust/engine/remote_provider/src/lib.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
Labels: category:user api change

#20412 Use unambigious full URL when pushing a release-prep PR
  src/python/pants_release/start_release.py
Labels: category:internal

#20416 upgrade PEX to 2.1.159
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:new feature, backend: Python

#20413 Update docker docs for buildx
  docs/docs/docker/index.mdx
  src/python/pants/backend/docker/target_types.py
  src/python/pants/notes/2.19.x.md
Labels: needs-cherrypick, category:documentation

#20396 Prepare 2.18.2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20424 Update docker docs for buildx (Cherry-pick of #20413)
  docs/docs/docker/index.mdx
  src/python/pants/backend/docker/target_types.py
  src/python/pants/notes/2.19.x.md
Labels: category:documentation

#20422 Fix the weird headings of `initial-configuration.mdx`
  docs/docs/getting-started/initial-configuration.mdx
Labels: needs-cherrypick, category:documentation

#20426 Fix the weird headings of `initial-configuration.mdx` (Cherry-pick of #20422)
  docs/docs/getting-started/initial-configuration.mdx
Labels: category:documentation

#20420 Apply latest hand-edits to pantsbuild/pantsbuild.org repo
  docs/docs/contributions/development/internal-architecture.mdx
  docs/docs/go/index.mdx
  docs/docs/helm/index.mdx
  docs/docs/introduction/welcome-to-pants.mdx
  docs/docs/terraform/index.mdx
  docs/docs/using-pants/environments.mdx
  docs/docs/using-pants/key-concepts/goals.mdx
  docs/docs/using-pants/key-concepts/options.mdx
  docs/docs/using-pants/key-concepts/source-roots.mdx
  docs/docs/using-pants/key-concepts/targets-and-build-files.mdx
  docs/docs/using-pants/remote-caching-and-execution/_category_.json
  docs/docs/using-pants/remote-caching-and-execution/index.mdx
  docs/docs/using-pants/remote-caching-and-execution/remote-caching.mdx
  docs/docs/using-pants/remote-caching-and-execution/remote-execution.mdx
  docs/docs/using-pants/using-pants-in-ci.mdx
  docs/docs/using-pants/validating-dependencies.mdx
Labels: category:documentation

#20429 Fix issue with grouping parametrizations on target generators.
  src/python/pants/engine/internals/defaults_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
Labels: needs-cherrypick, category:bugfix

#20433 Fix issue with grouping parametrizations on target generators. (Cherry-pick of #20429)
  src/python/pants/engine/internals/defaults_test.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/graph_test.py
Labels: category:bugfix

#20402 Prepare 2.19.0rc5
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20435 Update code/docs referencing old docs processes
  build-support/bin/BUILD
  build-support/bin/classify_changed_files.py
  build-support/bin/docs_templates/options_scope_reference.md.mustache
  build-support/bin/docs_templates/single_option_reference.md.mustache
  build-support/bin/docs_templates/target_reference.md.mustache
  build-support/bin/generate_docs.py
  build-support/bin/generate_docs_test.py
  build-support/bin/generate_user_list.py
  build-support/bin/readme_api.py
  build-support/bin/user_list_templates/table.html.mustache
  docs/docs/contributions/development/style-guide.mdx
  docs/docs/contributions/releases/release-process.mdx
  src/python/pants/bin/BUILD
  src/python/pants_release/release.py
Labels: needs-cherrypick, category:internal

#20434 Actually call `bin_name` in help string
  src/python/pants/backend/python/lint/pydocstyle/subsystem.py
Labels: needs-cherrypick, category:documentation

#20428 Implement dict and list-of-scalar parsing for options sources.
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/env_tests.rs
  src/rust/engine/options/src/lib.rs
Labels: category:internal

#20436 Trigger docs sync at the end of a release
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: needs-cherrypick, category:internal

#20442 Remove `reversion.py`
  build-support/bin/classify_changed_files.py
  src/python/pants_release/BUILD
  src/python/pants_release/reversion.py
  src/python/pants_release/reversion_test.py
Labels: category:internal

#20444 Fix missing registration for environments rules in pants.core.
  src/python/pants/core/register.py
Labels: category:documentation

#20445 Mention the Scala repl and its current gotchas in the docs
  docs/docs/java-and-scala/index.mdx
Labels: category:documentation

#20446 Add version/local scheme fields to `vcs_version`
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/vcs_versioning.py
Labels: needs-cherrypick, category:new feature

#20448 Prepare 2.20.0.dev7
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20449 Rename tutorials section in the docs
  docs/docs/tutorials-coming-soon/_category_.json
  docs/docs/tutorials/_category_.json
  docs/docs/tutorials/advanced-plugin-concepts.mdx
  docs/docs/tutorials/create-a-new-goal.mdx
  docs/docs/tutorials/testing-plugins.mdx
Labels: category:documentation

#20454 Fix the docs sync trigger CI job.
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#20452 Add a test case for Pants unit testing docs
  docs/docs/writing-plugins/the-rules-api/testing-plugins.mdx
Labels: category:documentation

#20451 Add a test case for Pants integration testing docs
  docs/docs/writing-plugins/the-rules-api/testing-plugins.mdx
Labels: category:documentation

#20443 Extend dependencies goal with output format to support JSON
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/dependencies_test.py
Labels: category:new feature

#20456 Docker: Update hadolint version to fix segmentation fault issue
  src/python/pants/backend/docker/lint/hadolint/subsystem.py
Labels: category:bugfix, backend: Docker

#20453 Extend dependents goal with output format to support JSON
  src/python/pants/backend/project_info/dependents.py
  src/python/pants/backend/project_info/dependents_test.py
Labels: category:new feature

#20459 Don't eagerly merge configs.
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/lib.rs
Labels: category:bugfix

#20461 Prepare 2.19.0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20455 Methods to return dict and scalar lists in OptionParser.
  src/rust/engine/client/src/client_tests.rs
  src/rust/engine/client/src/main.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/pantsd/src/pantsd_testing.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: category:internal

#20303 Terraform lockfiles (take 2)
  docs/docs/terraform/index.mdx
  docs/docs/writing-plugins/common-plugin-tasks/add-a-repl.mdx
  docs/docs/writing-plugins/common-plugin-tasks/custom-python-artifact-kwargs.mdx
  docs/docs/writing-plugins/common-plugin-tasks/index.mdx
  docs/docs/writing-plugins/common-plugin-tasks/plugin-lockfiles.mdx
  docs/docs/writing-plugins/common-plugin-tasks/run-tests.mdx
  src/python/pants/backend/experimental/terraform/register.py
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/dependencies_test.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/dependency_inference_test.py
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/goals/deploy.py
  src/python/pants/backend/terraform/goals/lockfiles.py
  src/python/pants/backend/terraform/goals/lockfiles_test.py
  src/python/pants/backend/terraform/goals/tailor.py
  src/python/pants/backend/terraform/goals/tailor_test.py
  src/python/pants/backend/terraform/target_types.py
  src/python/pants/backend/terraform/testutil.py
Labels: category:new feature, backend: Terraform

#20407 Allow AbstractLintRequest subclasses to disable lint rules
  src/python/pants/core/goals/fix.py
Labels: category:plugin api change

#20468 python: add _typeshed module to the list of unowned dependencies
  src/python/pants/backend/python/dependency_inference/default_unowned_dependencies.py
Labels: category:new feature, backend: Python

#20381 fix: in-repo plugin requirements.txt not loading (Cherry-pick of #20355)
  src/python/pants/init/options_initializer.py
  tests/python/pants_test/integration/plugin_requirements_integration_test.py
Labels: category:bugfix

#20437 Actually call `bin_name` in help string (Cherry-pick of #20434)
  src/python/pants/backend/python/lint/pydocstyle/subsystem.py
Labels: category:documentation

#20439 Update code/docs referencing old docs processes (Cherry-pick of #20435)
  build-support/bin/BUILD
  build-support/bin/classify_changed_files.py
  build-support/bin/docs_templates/options_scope_reference.md.mustache
  build-support/bin/docs_templates/single_option_reference.md.mustache
  build-support/bin/docs_templates/target_reference.md.mustache
  build-support/bin/generate_docs.py
  build-support/bin/generate_docs_test.py
  build-support/bin/generate_user_list.py
  build-support/bin/readme_api.py
  build-support/bin/user_list_templates/table.html.mustache
  docs/docs/contributions/development/style-guide.mdx
  docs/docs/contributions/releases/release-process.mdx
  src/python/pants/bin/BUILD
  src/python/pants_release/release.py
Labels: category:internal

#20470 Add (optional) support for podman.
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/subsystems/docker_options.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_binary_test.py
  src/python/pants/backend/experimental/docker/podman/BUILD
  src/python/pants/backend/experimental/docker/podman/__init__.py
  src/python/pants/backend/experimental/docker/podman/register.py
  src/python/pants/bin/BUILD
Labels: category:new feature

#20471 options: do not ignore .github directory with pants_ignore
  src/python/pants/option/global_options.py
Labels: category:new feature, backend: Python
