Repository pantsbuild/pants, pull requests merged in 2024-07, with the labels that each got.

#21112 Fix RuleRunner to work without BUILD_ROOT file in pytest sandbox
  docs/notes/2.23.x.md
  pants-plugins/pants_explorer/server/graphql/query/conftest.py
  pants-plugins/pants_explorer/server/graphql/query/targets.py
  pants-plugins/pants_explorer/server/graphql/query/targets_test.py
  src/python/pants/backend/project_info/BUILD
  src/python/pants/backend/project_info/dependencies_test.py
  src/python/pants/backend/project_info/dependents_test.py
  src/python/pants/backend/tools/taplo/rules_integration_test.py
  src/python/pants/base/BUILD
  src/python/pants/bsp/testutil.py
  src/python/pants/core/goals/BUILD
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/publish_test.py
  src/python/pants/engine/BUILD
  src/python/pants/engine/fs_test.py
  src/python/pants/engine/internals/BUILD
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/source/filespec_test.py
  src/python/pants/testutil/BUILD
  src/python/pants/testutil/rule_runner.py
  src/python/pants/vcs/git_test.py
  tests/python/pants_test/init/BUILD
  tests/python/pants_test/init/test_util.py
Labels: needs-cherrypick, category:bugfix, external-plugins

#21121 Fix RuleRunner to work without BUILD_ROOT file in pytest sandbox (Cherry-pick of #21112)
  docs/notes/2.22.x.md
  pants-plugins/pants_explorer/server/graphql/query/conftest.py
  pants-plugins/pants_explorer/server/graphql/query/targets.py
  pants-plugins/pants_explorer/server/graphql/query/targets_test.py
  src/python/pants/backend/project_info/BUILD
  src/python/pants/backend/project_info/dependencies_test.py
  src/python/pants/backend/project_info/dependents_test.py
  src/python/pants/backend/tools/taplo/rules_integration_test.py
  src/python/pants/base/BUILD
  src/python/pants/bsp/testutil.py
  src/python/pants/core/goals/BUILD
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/publish_test.py
  src/python/pants/engine/BUILD
  src/python/pants/engine/fs_test.py
  src/python/pants/engine/internals/BUILD
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/specs_rules_test.py
  src/python/pants/source/filespec_test.py
  src/python/pants/testutil/BUILD
  src/python/pants/testutil/rule_runner.py
  src/python/pants/vcs/git_test.py
  tests/python/pants_test/init/BUILD
  tests/python/pants_test/init/test_util.py
Labels: category:bugfix

#21120 Throw an error when generating an empty Python lockfile
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/goals/lockfile_test.py
Labels: category:internal, backend: Python

#21122 Change MyPy docs for third-party type stubs
  docs/docs/python/goals/check.mdx
  docs/notes/2.23.x.md
Labels: category:documentation, backend: Python

#21012 Upgrade default Node.js version from 16.x to 18.x series
  docs/notes/2.23.x.md
  src/python/pants/backend/javascript/goals/jest_resources/package-lock.json
  src/python/pants/backend/javascript/goals/jest_resources/pnpm-lock.yaml
  src/python/pants/backend/javascript/goals/jest_resources/yarn.lock
  src/python/pants/backend/javascript/goals/lockfile_test.py
  src/python/pants/backend/javascript/goals/mocha_resources/package-lock.json
  src/python/pants/backend/javascript/goals/mocha_resources/pnpm-lock.yaml
  src/python/pants/backend/javascript/goals/mocha_resources/yarn.lock
  src/python/pants/backend/javascript/goals/test.py
  src/python/pants/backend/javascript/goals/test_integration_test.py
  src/python/pants/backend/javascript/nodejs_project.py
  src/python/pants/backend/javascript/package/package-lock.json
  src/python/pants/backend/javascript/package/pnpm-lock.yaml
  src/python/pants/backend/javascript/package/rules_integration_test.py
  src/python/pants/backend/javascript/package/rules_test.py
  src/python/pants/backend/javascript/package/yarn.lock
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_test.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool_test.py
  src/python/pants/backend/javascript/subsystems/package-lock.json
  src/python/pants/backend/javascript/subsystems/pnpm-lock.yaml
  src/python/pants/backend/javascript/subsystems/yarn.lock
Labels: category:user api change, backend: JavaScript

#21124 [Call-by-name] cue/debian/makeself/sql migration
  docs/notes/2.23.x.md
  src/python/pants/backend/cue/goals/fix.py
  src/python/pants/backend/cue/goals/lint.py
  src/python/pants/backend/cue/rules.py
  src/python/pants/backend/cue/target_types.py
  src/python/pants/backend/debian/rules.py
  src/python/pants/backend/makeself/goals/package.py
  src/python/pants/backend/makeself/goals/package_run_integration_test.py
  src/python/pants/backend/makeself/goals/run.py
  src/python/pants/backend/makeself/subsystem.py
  src/python/pants/backend/makeself/system_binaries.py
  src/python/pants/backend/sql/lint/sqlfluff/rules.py
  src/python/pants/backend/sql/lint/sqlfluff/skip_field.py
  src/python/pants/backend/sql/lint/sqlfluff/subsystem.py
  src/python/pants/backend/sql/tailor.py
Labels: category:internal

#21127 Prepare 2.23.0.dev3
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21129 Prepare 2.20.3rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21128 Prepare 2.22.0rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21130 Prepare 2.21.1rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20826 Javascript backend - run node package install once per workspace
  docs/notes/2.23.x.md
  src/python/pants/backend/javascript/goals/test_integration_test.py
  src/python/pants/backend/javascript/install_node_package.py
  src/python/pants/backend/javascript/nodejs_project.py
  src/python/pants/backend/javascript/package/package-lock.json
  src/python/pants/backend/javascript/package/pnpm-lock.yaml
  src/python/pants/backend/javascript/package/rules_integration_test.py
  src/python/pants/backend/javascript/package/rules_test.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool_test.py
  src/python/pants/backend/javascript/subsystems/package-lock.json
Labels: bug, category:bugfix, backend: JavaScript

#21123 Preserve Terraform deployment sandboxes
  docs/notes/2.23.x.md
  src/python/pants/backend/terraform/goals/deploy.py
  src/python/pants/engine/process.py
Labels: category:internal

#21147 rename `--export-py-generated-sources` to `--export-py-generated-sources-in-resolve`
  docs/notes/2.22.x.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
Labels: needs-cherrypick, category:internal, release-notes:not-required

#21148 rename `--export-py-generated-sources` to `--export-py-generated-sources-in-resolve` (Cherry-pick of #21147)
  docs/notes/2.22.x.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_test.py
Labels: category:internal

#18057 Fix coverage calculation when `filter` option is used
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: category:bugfix, backend: Python, release-notes:not-required

#21036 Rudimentary export goal support for `node_modules`
  docs/notes/2.23.x.md
  src/python/pants/backend/experimental/javascript/register.py
  src/python/pants/backend/javascript/goals/export.py
  src/python/pants/backend/javascript/goals/export_test.py
  src/python/pants/backend/javascript/nodejs_project_environment.py
  src/python/pants/backend/python/goals/export.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/export_test.py
Labels: category:new feature, backend: JavaScript

#21149 [Call-by-name] semgrep/trufflehog/yamllint migration
  docs/notes/2.23.x.md
  src/python/pants/backend/tools/semgrep/rules.py
  src/python/pants/backend/tools/trufflehog/rules.py
  src/python/pants/backend/tools/yamllint/rules.py
  src/python/pants/goal/migrate_call_by_name.py
  src/python/pants/goal/migrate_call_by_name_integration_test.py
  src/python/pants/goal/migrate_call_by_name_test.py
  src/python/pants/util/cstutil.py
Labels: category:internal

#21141 docs/javascript: Add overview of javascript backend and nodejs configuration
  docs/docs/javascript/_category_.json
  docs/docs/javascript/overview/_category_.json
  docs/docs/javascript/overview/enabling-javascript-support.mdx
  docs/docs/javascript/overview/index.mdx
  docs/docs/javascript/overview/lockfiles.mdx
  docs/docs/javascript/overview/package.mdx
  docs/docs/javascript/overview/workspaces.mdx
Labels: documentation, category:documentation, backend: JavaScript, release-notes:not-required

#21151 Use $(brew --prefix) in docs instead of assuming a certain path
  docs/docs/contributions/development/setting-up-pants.mdx
Labels: category:documentation, release-notes:not-required

#21150 Fix coverage calculation when `filter` option is used (Cherry-pick of #18057)
  src/python/pants/backend/python/goals/coverage_py.py
  src/python/pants/backend/python/goals/coverage_py_integration_test.py
Labels: category:bugfix, release-notes:not-required

#21152 Create [workunit-logger].logdir if it doesn't already exist
  docs/notes/2.23.x.md
  src/python/pants/backend/tools/workunit_logger/rules.py
Labels: category:bugfix

#21159 (JavaScript) Throw a more descriptive error when the package name is missing
  docs/notes/2.23.x.md
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/backend/javascript/package_json_test.py
Labels: category:bugfix, backend: JavaScript

#21118 Fix options parser discrepancy due to repeated evaluation of `.pants.rc`
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_test.py
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
Labels: category:bugfix, release-notes:not-required

#21133 Bump workflow actions for node20
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/public_repos.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21172 Allow unesecure node temporarily for manylinux container builds
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21160 Native dockerfile parser
  docs/notes/2.23.x.md
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser_test.py
  src/python/pants/engine/internals/native_dep_inference.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/intrinsics.py
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/dep_inference/build.rs
  src/rust/engine/dep_inference/src/code.rs
  src/rust/engine/dep_inference/src/dockerfile/copy.rs
  src/rust/engine/dep_inference/src/dockerfile/from.rs
  src/rust/engine/dep_inference/src/dockerfile/mod.rs
  src/rust/engine/dep_inference/src/dockerfile/tests.rs
  src/rust/engine/dep_inference/src/javascript/mod.rs
  src/rust/engine/dep_inference/src/lib.rs
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/intrinsics/dep_inference.rs
  src/rust/engine/src/types.rs
Labels: category:new feature, backend: Docker

#21167 [Call-by-name] build_files migration
  src/python/pants/backend/build_files/fix/deprecations/renamed_fields_rules.py
  src/python/pants/backend/build_files/fix/deprecations/renamed_targets_rules.py
  src/python/pants/backend/build_files/fmt/buildifier/rules.py
Labels: category:internal, release-notes:not-required

#21175 use a template for computing `output_path` for packageable targets
  docs/notes/2.23.x.md
  src/python/pants/backend/javascript/package/rules.py
  src/python/pants/backend/javascript/package/rules_integration_test.py
  src/python/pants/backend/javascript/package/rules_test.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/python/packaging/pyoxidizer/target_types.py
  src/python/pants/core/goals/package.py
  src/python/pants/core/goals/package_test.py
Labels: category:new feature

#21166 Upgrade default Node version from 18.20.3 to 20.15.1
  docs/notes/2.23.x.md
  src/python/pants/backend/javascript/subsystems/nodejs.py
Labels: category:user api change, backend: JavaScript

#21099 Add targets for terraform lockfiles
  docs/docs/terraform/index.mdx
  docs/notes/2.23.x.md
  src/python/pants/backend/experimental/terraform/register.py
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/goals/lockfiles.py
  src/python/pants/backend/terraform/target_types.py
  src/python/pants/backend/terraform/testutil.py
Labels: category:new feature, backend: Terraform

#21076 Helm: warn on missing docker image
  docs/notes/2.23.x.md
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/utils.py
  src/python/pants/backend/helm/check/kubeconform/deployment_test.py
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/dependency_inference/deployment_test.py
  src/python/pants/backend/helm/dependency_inference/subsystem.py
  src/python/pants/backend/helm/goals/deploy_test.py
  src/python/pants/backend/helm/util_rules/post_renderer_test.py
Labels: category:bugfix, backend: Helm

#21171 tests: add experimental-report-test-result-info option to the test goal
  docs/notes/2.23.x.md
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_integration_test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/engine/process.py
Labels: category:new feature

#21181 deprecate `--export-py-hermetic-scripts` in favor of new `--export-py-non-hermetic-scripts-in-resolve` option
  docs/notes/2.23.x.md
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/goals/export_test.py
Labels: category:user api change

#21116 Separate discovery for tfsec config and checks
  docs/docs/writing-plugins/common-subsystem-tasks.mdx
  docs/docs/writing-plugins/the-rules-api/testing-plugins.mdx
  src/python/pants/backend/terraform/lint/tfsec/rules.py
  src/python/pants/backend/terraform/lint/tfsec/tfsec.py
  src/python/pants/backend/terraform/lint/tfsec/tfsec_integration_test.py
Labels: documentation, category:internal, backend: Terraform

#21185 cleanup how adhoc and shell backends process environment variables
  docs/notes/2.23.x.md
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/code_quality_tool.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: category:bugfix

#21186 goals: update update-build-files goal help text
  src/python/pants/core/goals/update_build_files.py
Labels: category:documentation, release-notes:not-required

#21126 Allow customizing semgrep configurations; correct rule matching glob
  docs/notes/2.23.x.md
  src/python/pants/backend/tools/semgrep/rules.py
  src/python/pants/backend/tools/semgrep/rules_integration_test.py
  src/python/pants/backend/tools/semgrep/rules_test.py
  src/python/pants/backend/tools/semgrep/subsystem.py
Labels: category:new feature

#21138 add `path_env_modify` field to `adhoc_tool` and `shell_command` to control how PATH is augmented
  src/python/pants/backend/adhoc/adhoc_tool.py
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: category:new feature, backend: Shell, release-notes:not-required

#21182 update Pex to 2.11.0
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/notes/2.23.x.md
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:internal, backend: Python

#21192 fix string whivch should have been an f-string
  src/python/pants/core/util_rules/environments.py
Labels: needs-cherrypick, category:internal, release-notes:not-required

#21193 fix string whivch should have been an f-string (Cherry-pick of #21192)
  src/python/pants/core/util_rules/environments.py
Labels: category:internal

#21188 Always run setuptools_scm in the local environment
  docs/notes/2.23.x.md
  src/python/pants/backend/python/util_rules/vcs_versioning.py
Labels: category:bugfix

#21155 Allow capturing tfsec output as a report
  docs/notes/2.23.x.md
  src/python/pants/backend/terraform/lint/tfsec/rules.py
  src/python/pants/backend/terraform/lint/tfsec/tfsec.py
  src/python/pants/backend/terraform/lint/tfsec/tfsec_integration_test.py
Labels: category:new feature, backend: Terraform

#21169 Allow both `resource` and `file` targets for `complete_platforms` on Python FaaS
  docs/notes/2.23.x.md
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/BUILD
  src/python/pants/backend/python/util_rules/complete_platform_pex_test.json
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:bugfix, backend: Python

#21196 Prepare 2.23.0.dev4
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21198 Bump workflow actions for node20 (Cherry-pick of #21133)
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/public_repos.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21204 Bump workflow actions for node20 (Cherry-pick of #21133)
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/public_repos.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21203 Bump workflow actions for node20 (Cherry-pick of #21133)
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/public_repos.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21209 Allow unesecure node temporarily for manylinux container builds (Cherry-pick of #21172)
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21197 Prepare 2.22.0rc2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21139 make `pyenv` backend respect patch version constraints
  docs/notes/2.23.x.md
  src/python/pants/backend/python/providers/pyenv/rules.py
  src/python/pants/backend/python/providers/pyenv/rules_integration_test.py
Labels: category:bugfix, backend: Python

#21211 Allow unesecure node temporarily for manylinux container builds (Cherry-pick of #21172)
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21212 Allow unesecure node temporarily for manylinux container builds (Cherry-pick of #21172)
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21200 Prepare 2.20.3rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21199 Prepare 2.21.1rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21142 bump pyenv to 2.4.7
  docs/notes/2.23.x.md
  src/python/pants/backend/python/providers/pyenv/rules.py
  src/python/pants/backend/python/providers/pyenv/rules_integration_test.py
Labels: category:new feature

#21174 Support recursive rule call-by-name.
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/internals/rule_visitor_test.py
  src/python/pants/engine/rules.py
Labels: category:internal

#21213 Fix minor typo in JS docs link
  docs/docs/javascript/overview/package.mdx
Labels: category:documentation, release-notes:not-required

#21216 upgrade to Rust v1.80.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/rust-toolchain
  src/rust/engine/testutil/mock/src/cas.rs
Labels: category:internal

#21218 align table whitespace in docs/.../backends.mdx
  docs/docs/using-pants/key-concepts/backends.mdx
Labels: category:internal, release-notes:not-required

#21135 refactor/javascript: Move package manager decisions to one place
  src/python/pants/backend/javascript/install_node_package.py
  src/python/pants/backend/javascript/nodejs_project.py
  src/python/pants/backend/javascript/nodejs_project_environment.py
  src/python/pants/backend/javascript/nodejs_project_test.py
  src/python/pants/backend/javascript/package_manager.py
  src/python/pants/backend/javascript/run/rules.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool.py
Labels: category:internal, backend: JavaScript, release-notes:not-required

#21220 Fix: attach lockfiles to terraform modules
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/dependency_inference_test.py
  src/python/pants/backend/terraform/goals/lockfiles.py
Labels: category:bugfix, backend: Terraform, release-notes:not-required

#21226 Prepare 2.23.0.dev5
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21232 Distinguish git worktree finding errors.
  src/python/pants/backend/python/util_rules/vcs_versioning.py
  src/python/pants/vcs/git.py
Labels: category:documentation, release-notes:not-required

#21224 Prepare 2.20.3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21227 Prepare 2.21.1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21215 use entire URL string as cache key for download intrinsic rule
  src/python/pants/engine/download_file_integration_test.py
  src/rust/engine/src/nodes/downloaded_file.rs
Labels: needs-cherrypick, category:bugfix, release-notes:not-required

#21238 use entire URL string as cache key for download intrinsic rule (Cherry-pick of #21215)
  src/python/pants/engine/download_file_integration_test.py
  src/rust/engine/src/nodes/downloaded_file.rs
Labels: category:bugfix, release-notes:not-required

#21241 Tighten regex on Simplifier/strip_v2_chroot_path
  src/python/pants/util/strutil.py
  src/python/pants/util/strutil_test.py
Labels: category:bugfix, release-notes:not-required
