Repository pantsbuild/pants, pull requests merged in 2024-04, with the labels that each got.

#20736 Support None option values.
  src/rust/engine/options/src/lib.rs
Labels: category:internal

#20735 Let multiple CLI args update the same dict-valued option in the Rust options parser
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/env_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
  src/rust/engine/options/src/tests.rs
Labels: category:internal

#20738 Support passthough args in the rust args parser
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
Labels: category:internal

#20746 Make all "local dists" PEXes internal-only
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/util_rules/local_dists.py
  src/python/pants/backend/python/util_rules/local_dists_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
Labels: category:performance

#20753 Restore some opentelemetry module mappings (Cherry-pick of #20749)
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:bugfix

#20747 Print reduced `pants test ...` command to rerun, when on CI
  src/python/pants/core/goals/test.py
  src/python/pants/core/goals/test_test.py
Labels: category:new feature

#20755 Add workflow to clear persistent cache dirs on self-hosted runners
  .github/workflows/clear_self_hosted_persistent_caches.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#20756 Use correct GHA workflow syntax in new cache-clearing action, be more resilient
  .github/workflows/clear_self_hosted_persistent_caches.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#20757 Deprecate the implicit_value option registration kwarg.
  src/python/pants/option/parser.py
Labels: category:plugin api change

#20758 Deprecate the implicit_value option registration kwarg. (Cherry-pick of #20757)
  src/python/pants/option/parser.py
Labels: category:plugin api change

#20737 Allow passing arguments to PEX invocation used for `pex_binary`
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/target_types.py
Labels: category:new feature

#20750 Prepare 2.19.2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20754 Prepare 2.20.0rc3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20579 stats: add output format option to save Pants stats as JSON
  src/python/pants/goal/stats_aggregator.py
  src/python/pants/goal/stats_aggregator_integration_test.py
Labels: category:new feature

#20761 Prepare 2.21.0.dev5
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20742 refactor nodes module into submodules by kind of node
  src/rust/engine/src/nodes.rs
  src/rust/engine/src/nodes/digest_file.rs
  src/rust/engine/src/nodes/downloaded_file.rs
  src/rust/engine/src/nodes/execute_process.rs
  src/rust/engine/src/nodes/mod.rs
  src/rust/engine/src/nodes/read_link.rs
  src/rust/engine/src/nodes/root.rs
  src/rust/engine/src/nodes/run_id.rs
  src/rust/engine/src/nodes/scandir.rs
  src/rust/engine/src/nodes/session_values.rs
  src/rust/engine/src/nodes/snapshot.rs
  src/rust/engine/src/nodes/task.rs
Labels: category:internal

#20762 Remove the deprecated implicit_value option kwarg.
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/option/errors.py
  src/python/pants/option/options_test.py
  src/python/pants/option/parser.py
Labels: category:user api change

#20760 Upgrade ijson (3.2.3) and psutil (5.9.8) for arm macOS wheels
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
Labels: category:internal

#20701 Allow plugin authors to attach custom fields to TargetData for pants peek
  docs/docs/writing-plugins/the-target-api/concepts.mdx
  src/python/pants/backend/project_info/peek.py
  src/python/pants/backend/project_info/peek_test.py
Labels: category:new feature

#20730 Make tools exportable
  docs/docs/writing-plugins/common-plugin-tasks/index.mdx
  docs/docs/writing-plugins/common-plugin-tasks/plugin-helpers.mdx
  docs/docs/writing-plugins/common-subsystem-tasks.mdx
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/goals/export_test.py
  src/python/pants/backend/python/goals/lockfile.py
  src/python/pants/backend/python/lint/isort/subsystem.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/core/goals/generate_lockfiles.py
  src/python/pants/core/goals/generate_lockfiles_test.py
  src/python/pants/core/goals/resolves.py
  src/python/pants/jvm/goals/lockfile.py
  src/python/pants/jvm/goals/lockfile_test.py
  src/python/pants/jvm/resolve/jvm_tool.py
Labels: category:new feature

#20775 Prepare 2.21.0.dev6
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20773 Upgrade psutil (5.9.8) for arm macOS wheels (Cherry-pick of #20760)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
Labels: category:internal

#20774 Upgrade psutil (5.9.8) for arm macOS wheels (Cherry-pick of #20760)
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
Labels: category:internal

#20776 Prepare 2.19.3rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20777 Prepare 2.20.0rc4
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20768 Fix issue with explicit dependency when using parametrize groups.
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: needs-cherrypick, category:bugfix

#20714 Call-by-name syntax migration goal
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/rules.py
  src/python/pants/goal/migrate_call_by_name.py
  src/python/pants/goal/migrate_call_by_name_integration_test.py
  src/python/pants/goal/migrate_call_by_name_test.py
  src/python/pants/util/astutil.py
  src/python/pants/util/astutil_test.py
Labels: category:internal

#20641 Add some more default module mappings
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal

#15638 Add documentation-related sources to `helm_chart`
  src/python/pants/backend/helm/target_types.py
  src/python/pants/backend/helm/util_rules/sources_test.py
Labels: category:new feature

#20786 Add python312 runtime to python_google_cloud_function
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/target_types_test.py
Labels: category:new feature

#20782 update Pex to 2.3.1
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:bugfix, backend: Python

#20780 improve plants plugin resolve docs
  docs/docs/writing-plugins/overview.mdx
Labels: category:documentation

#20670 Set --no-pre-install-wheels and PEX_MAX_INSTALL_JOBS for faster builds of internal pexes
  src/python/pants/backend/python/goals/publish_test.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:performance

#20778 Fix issue with explicit dependency when using parametrize groups. (Cherry-pick of #20768)
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: category:bugfix

#20769 Visibility: support `dict` rules same way as for selectors.
  docs/docs/using-pants/validating-dependencies.mdx
  src/python/pants/backend/visibility/rule_types.py
  src/python/pants/backend/visibility/rule_types_test.py
Labels: category:new feature

#20793 Fix the behavior of list removals in the Rust option code.
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
Labels: category:internal

#20763 Add export option: py_hermetic_scripts
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/goals/export_test.py
Labels: category:new feature

#20791 Prepare 2.20.0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20796 Improve exported mutable_virtualenv prompt
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/export_integration_test.py
  src/python/pants/backend/python/goals/export_test.py
Labels: enhancement, category:new feature, backend: Python

#20781 provide a more friendly pointer on unconfigured constraint file
  src/python/pants/backend/python/util_rules/pex_requirements.py
Labels: category:bugfix, backend: Python

#20779 Fix issue with explicit dependency when using parametrize groups. (Cherry-pick of #20768)
  src/python/pants/engine/internals/graph_test.py
  src/python/pants/engine/internals/parametrize.py
Labels: category:bugfix

#20798 Fix direct_url in python PEP660 editable wheels (again)
  src/python/pants/backend/python/util_rules/local_dists_pep660_test.py
  src/python/pants/backend/python/util_rules/package_dists.py
Labels: category:bugfix, backend: Python

#20331 Added an optional `goals` field to the `peek` JSON output
  src/python/pants/backend/project_info/peek.py
  src/python/pants/backend/project_info/peek_integration_test.py
  src/python/pants/backend/project_info/peek_test.py
  src/python/pants/engine/internals/specs_rules.py
Labels: category:new feature, backend: Python

#20784 Replaced pre-commit githook with pre-push
  build-support/bin/install_git_hooks.sh
  build-support/githooks/BUILD
  build-support/githooks/pre-push
  docs/docs/contributions/development/setting-up-pants.mdx
  docs/docs/contributions/development/style-guide.mdx
  docs/docs/contributions/index.mdx
Labels: category:user api change

#20804 re-add missing opentelemetry.util module mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: needs-cherrypick, category:bugfix, backend: Python

#20811 Introduce a FromfileExpander struct
  src/rust/engine/options/src/fromfile.rs
Labels: category:internal

#20800 add some module mappings
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:new feature, backend: Python

#20812 fix Python & NodeJS lockfiles doc
  docs/docs/python/overview/lockfiles.mdx
  src/python/pants/backend/javascript/subsystems/nodejs.py
Labels: category:documentation

#20783 Fixed install_git_hooks.sh does not work if "python" is not found (but python3 exists)
  build-support/bin/install_git_hooks.sh
Labels: category:bugfix

#20814 Plumb a FromfileExpander into option source readers
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/config_tests.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/env_tests.rs
  src/rust/engine/options/src/lib.rs
Labels: category:internal

#20813 Add additional modules to default module mapping
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:new feature, backend: Python

#20815 Use the FromfileExpander to expand @fromfile values.
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/fromfile.rs
  src/rust/engine/options/src/fromfile_tests.rs
Labels: category:internal

#20816 Prepare 2.21.0a0
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#20820 Resolve @fromfile paths relative to the buildroot.
  src/rust/engine/options/src/args_tests.rs
  src/rust/engine/options/src/build_root.rs
  src/rust/engine/options/src/config_tests.rs
  src/rust/engine/options/src/env_tests.rs
  src/rust/engine/options/src/fromfile.rs
  src/rust/engine/options/src/fromfile_tests.rs
  src/rust/engine/options/src/lib.rs
Labels: category:internal

#20824 Upgrade `ruff` to 0.4.x series
  src/python/pants/backend/python/lint/ruff/ruff.lock
  src/python/pants/backend/python/lint/ruff/rules_integration_test.py
Labels: category:internal, backend: Python

#20825 Added a cautionary note to PyOxidizer's docs page
  docs/docs/python/integrations/pyoxidizer.mdx
Labels: needs-cherrypick, category:documentation, backend: Python

#20830 docs: Remove note about abbreviated form
  docs/docs/using-pants/key-concepts/targets-and-build-files.mdx
Labels: needs-cherrypick, category:documentation

#20835 docs: Remove note about abbreviated form (Cherry-pick of #20830)
  docs/docs/using-pants/key-concepts/targets-and-build-files.mdx
Labels: category:documentation

#20833 docs: Remove note about abbreviated form (Cherry-pick of #20830)
  docs/docs/using-pants/key-concepts/targets-and-build-files.mdx
Labels: category:documentation

#20834 docs: Remove note about abbreviated form (Cherry-pick of #20830)
  docs/docs/using-pants/key-concepts/targets-and-build-files.mdx
Labels: category:documentation

#20837 stop using deprecated logging.warn method
  src/python/pants/core/util_rules/config_files.py
  src/python/pants/engine/streaming_workunit_handler.py
Labels: category:bugfix

#20839 Fix Rust option parser escape handling
  src/rust/engine/options/src/parse.rs
  src/rust/engine/options/src/parse_tests.rs
Labels: category:bugfix

#20843 Fix dependencies and dependents to use output file when using json formatting
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/dependencies_test.py
  src/python/pants/backend/project_info/dependents.py
  src/python/pants/backend/project_info/dependents_test.py
Labels: category:bugfix

#20841 OrphanFilepathConfigBehavior.IGNORE should actually ignore orphaned files
  src/python/pants/core/util_rules/config_files.py
Labels: category:bugfix

#20844 Fix: Example config for local filesystem caching
  docs/docs/using-pants/remote-caching-and-execution/remote-caching.mdx
Labels: needs-cherrypick, category:documentation

#20848 Fix: Example config for local filesystem caching (Cherry-pick of #20844)
  docs/docs/using-pants/remote-caching-and-execution/remote-caching.mdx
Labels: category:documentation

#20849 Fix: Example config for local filesystem caching (Cherry-pick of #20844)
  docs/docs/using-pants/remote-caching-and-execution/remote-caching.mdx
Labels: category:documentation

#20851 Add Python 3.13 to the default interpreter universe
  src/python/pants/backend/python/subsystems/setup.py
Labels: category:new feature

#20823 Remove deprecated `pex_binary(platforms=...)` for 2.22, deprecate `resolve_local_platforms`
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex.py
Labels: category:user api change

#20847 Move release notes to docs/notes, don't do wheel builds when changed
  build-support/bin/classify_changed_files.py
  build-support/bin/classify_changed_files_test.py
  docs/README.md
  docs/docs/contributions/releases/release-process.mdx
  docs/docs/using-pants/restricted-internet-access.mdx
  docs/notes/1.0.x.rst
  docs/notes/1.1.x.rst
  docs/notes/1.10.x.rst
  docs/notes/1.11.x.rst
  docs/notes/1.12.x.rst
  docs/notes/1.13.x.rst
  docs/notes/1.14.x.rst
  docs/notes/1.15.x.rst
  docs/notes/1.16.x.rst
  docs/notes/1.17.x.rst
  docs/notes/1.18.x.rst
  docs/notes/1.19.x.rst
  docs/notes/1.2.x.rst
  docs/notes/1.20.x.rst
  docs/notes/1.21.x.rst
  docs/notes/1.22.x.rst
  docs/notes/1.23.x.rst
  docs/notes/1.24.x.rst
  docs/notes/1.25.x.rst
  docs/notes/1.26.x.rst
  docs/notes/1.27.x.rst
  docs/notes/1.28.x.rst
  docs/notes/1.29.x.rst
  docs/notes/1.3.x.rst
  docs/notes/1.30.x.rst
  docs/notes/1.4.x.rst
  docs/notes/1.5.x.rst
  docs/notes/1.6.x.rst
  docs/notes/1.7.x.rst
  docs/notes/1.8.x.rst
  docs/notes/1.9.x.rst
  docs/notes/2.0.x.md
  docs/notes/2.1.x.md
  docs/notes/2.10.x.md
  docs/notes/2.11.x.md
  docs/notes/2.12.x.md
  docs/notes/2.13.x.md
  docs/notes/2.14.x.md
  docs/notes/2.15.x.md
  docs/notes/2.16.x.md
  docs/notes/2.17.x.md
  docs/notes/2.18.x.md
  docs/notes/2.19.x.md
  docs/notes/2.2.x.md
  docs/notes/2.20.x.md
  docs/notes/2.3.x.md
  docs/notes/2.4.x.md
  docs/notes/2.5.x.md
  docs/notes/2.6.x.md
  docs/notes/2.7.x.md
  docs/notes/2.8.x.md
  docs/notes/2.9.x.md
  docs/notes/master.rst
Labels: category:internal

#20789 allow loose format in Google Cloud Functions & AWS Lambda targets
  docs/docs/python/integrations/aws-lambda.mdx
  docs/docs/python/integrations/google-cloud-functions.mdx
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/rules_test.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/faas_test.py
Labels: category:new feature

#20855 Prepare 2.22.0.dev0
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep
