Repository pantsbuild/pants, pull requests merged in 2025-08, with the labels that each got.

#22555 scrape PBS release 20250723 (Cherry-pick of #22549)
  docs/notes/2.28.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal, release-notes:not-required

#22559 update the 2.28.x release notes on main to match the `2.28.x` branch
  docs/notes/2.28.x.md
Labels: category:documentation, release-notes:not-required

#22572 PBS: scrape releases through 20250808
  docs/notes/2.29.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal

#22587 Port remaining `core/goals` code to call-by-name.
  src/python/pants/core/goals/check.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/deploy.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/publish.py
  src/python/pants/core/goals/repl.py
  src/python/pants/core/goals/repl_test.py
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/testutil/rule_runner.py
Labels: release-notes:not-required

#22582 JVM: Fix coursier classifier conflicts
  docs/notes/2.29.x.md
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/coursier_fetch_integration_test.py
Labels: category:bugfix

#22589 Port several JVM-related files to call-by-name.
  src/python/pants/backend/java/goals/check.py
  src/python/pants/backend/java/target_types.py
  src/python/pants/backend/kotlin/compile/kotlinc_plugins.py
  src/python/pants/backend/kotlin/goals/check.py
  src/python/pants/backend/kotlin/target_types.py
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pytype/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/backend/scala/compile/scalac_plugins.py
  src/python/pants/backend/scala/goals/check.py
  src/python/pants/backend/scala/goals/repl.py
  src/python/pants/backend/scala/target_types.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/jvm/bsp/compile.py
  src/python/pants/jvm/bsp/resources.py
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/run.py
  src/python/pants/jvm/run_deploy_jar.py
  src/python/pants/jvm/run_integration_test.py
  src/python/pants/jvm/target_types.py
Labels: release-notes:not-required

#22597 scrape PBS releases through `20250818`
  docs/notes/2.29.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal

#22599 Decouple Subsystem and options bootstrapping.
  pants-plugins/pants_explorer/server/graphql/query/conftest.py
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/build_graph/build_configuration.py
  src/python/pants/core/register.py
  src/python/pants/core/target_types.py
  src/python/pants/core/target_types_test.py
  src/python/pants/core/util_rules/misc.py
  src/python/pants/engine/goal.py
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/options_parsing.py
  src/python/pants/engine/internals/remote_cache_integration_test.py
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/internals/scheduler_test_base.py
  src/python/pants/engine/rules.py
  src/python/pants/engine/rules_test.py
  src/python/pants/engine/target.py
  src/python/pants/engine/target_test.py
  src/python/pants/help/help_info_extracter.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/init/engine_initializer.py
  src/python/pants/init/options_initializer.py
  src/python/pants/option/bootstrap_options.py
  src/python/pants/option/global_options.py
  src/python/pants/option/global_options_test.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_diff.py
  src/python/pants/option/options_diff_test.py
  src/python/pants/option/scope.py
  src/python/pants/option/subsystem.py
  src/python/pants/pantsd/pants_daemon.py
  src/python/pants/pantsd/pants_daemon_core.py
  src/python/pants/pantsd/pantsd_integration_test.py
  src/python/pants/pantsd/service/store_gc_service.py
  src/python/pants/testutil/option_util.py
  src/python/pants/testutil/rule_runner.py
Labels: release-notes:not-required

#22601 Fix release script to handle wheel filenames correctly.
  src/python/pants_release/release.py
Labels: release-notes:not-required
