Repository pantsbuild/pants, pull requests merged in 2025-03, with the labels that each got.

#22025 update release notes for 2.25 release (Cherry-pick of #22021)
  docs/notes/2.25.x.md
Labels: category:internal, release-notes:not-required

#22023 upgrade `packaging` to v24.2
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/notes/2.26.x.md
  src/python/pants/backend/python/util_rules/lockfile_diff.py
Labels: category:internal

#22028 PBS: scrape release 20250212
  docs/notes/2.25.x.md
  docs/notes/2.26.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: needs-cherrypick, category:internal

#22029 PBS: scrape release 20250212 (Cherry-pick of #22028)
  docs/notes/2.25.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal, release-notes:not-required

#22031 migrate `pkg_resources.resource_string` usages to `importlib.resources`
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/jvm/jar_tool/jar_tool.py
  src/python/pants/jvm/strip_jar/strip_jar.py
Labels: category:internal, release-notes:not-required

#22032 Re-locked more JS dependencies
  src/python/pants/backend/javascript/package/package-lock.json
  src/python/pants/backend/javascript/package/pnpm-lock.yaml
  src/python/pants/backend/javascript/package/rules_integration_test.py
  src/python/pants/backend/javascript/package/yarn.lock
  testprojects/src/ts/hello_react_ts/package-lock.json
  testprojects/src/ts/hello_react_ts/package.json
Labels: category:internal, backend: JavaScript, release-notes:not-required

#22037 fix CI "build wheels" step for rustup no longer installing default toolchain
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: needs-cherrypick, category:internal, release-notes:not-required

#22038 fix CI "build wheels" step for rustup no longer installing default toolchain (Cherry-pick of #22037)
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#22039 fix CI "build wheels" step for rustup no longer installing default toolchain (Cherry-pick of #22037)
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#22035 Prepare 2.25.0rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22040 docs: fix note about explicit kubectl contexts in k8s backend
  docs/docs/kubernetes/index.mdx
Labels: release-notes:not-required

#22043 migrate another `pkg_resources` usage
  src/python/pants/backend/openapi/sample/resources.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:internal, release-notes:not-required

#22045 migrate from `pkg_resources` to `importlib.metadata` in help extractor
  src/python/pants/help/help_info_extracter.py
Labels: category:internal, release-notes:not-required

#22046 update mention of entry points API in help text
  src/python/pants/backend/python/target_types.py
Labels: category:internal, release-notes:not-required

#22033 migrate to `packaging` requirements parsing from deprecated `pkg_resources`
  docs/notes/2.26.x.md
  src/python/pants/backend/openapi/codegen/python/generate.py
  src/python/pants/backend/python/dependency_inference/module_mapper.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/run_python_requirement.py
  src/python/pants/backend/python/macros/common_requirements_rule.py
  src/python/pants/backend/python/subsystems/python_tool_base.py
  src/python/pants/backend/python/util_rules/interpreter_constraints.py
  src/python/pants/backend/python/util_rules/interpreter_constraints_test.py
  src/python/pants/backend/python/util_rules/package_dists.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_test_utils.py
  src/python/pants/util/pip_requirement.py
  src/python/pants/util/pip_requirement_test.py
  src/python/pants/util/requirements.py
Labels: category:internal

#22051 update `pants peek` docs with latest outputs
  docs/docs/using-pants/project-introspection.mdx
Labels: needs-cherrypick, category:internal, release-notes:not-required

#22052 update `pants peek` docs with latest outputs (Cherry-pick of #22051)
  docs/docs/using-pants/project-introspection.mdx
Labels: category:internal, release-notes:not-required

#22053 update `pants peek` docs with latest outputs (Cherry-pick of #22051)
  docs/docs/using-pants/project-introspection.mdx
Labels: category:internal, release-notes:not-required

#22055 2.25.x: add note about updating pantsbuild/actions/init-pants for py3.11 support (Cherry-pick of #22054)
  docs/notes/2.25.x.md
Labels: category:documentation, release-notes:not-required

#22041 fix: js/ts dependency inference with file suffix
  docs/notes/2.26.x.md
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/javascript/dependency_inference/rules_test.py
  src/python/pants/backend/typescript/dependency_inference/rules_test.py
Labels: needs-cherrypick, category:bugfix

#22056 fix: js/ts dependency inference with file suffix (Cherry-pick of #22041)
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/javascript/dependency_inference/rules_test.py
  src/python/pants/backend/typescript/dependency_inference/rules_test.py
Labels: category:bugfix, release-notes:not-required

#22060 Fix incorrect path in error message.
  src/rust/engine/fs/store/src/lib.rs
Labels: needs-cherrypick, release-notes:not-required

#22050 handle Python concatenated strings in Rust dependency inference parser
  docs/notes/2.26.x.md
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: needs-cherrypick, category:internal

#22061 Fix incorrect path in error message. (Cherry-pick of #22060)
  src/rust/engine/fs/store/src/lib.rs
Labels: release-notes:not-required

#22063 handle Python concatenated strings in Rust dependency inference parser (Cherry-pick of #22050)
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: category:internal, release-notes:not-required

#22062 handle Python concatenated strings in Rust dependency inference parser (Cherry-pick of #22050)
  src/rust/engine/dep_inference/src/python/mod.rs
  src/rust/engine/dep_inference/src/python/tests.rs
Labels: category:internal, release-notes:not-required

#22048 remove use of `pkg_resources` in `external_tool` rules
  src/python/pants/core/util_rules/external_tool.py
Labels: category:internal, release-notes:not-required

#22047 delete some namespace package declarations
  testprojects/pants-plugins/src/python/test_pants_plugin/__init__.py
  testprojects/pants-plugins/src/python/workunit_logger/__init__.py
Labels: category:internal, release-notes:not-required

#22068 Prepare 2.25.0rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22069 remove reference to pkg_resources in a comment in a test
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:internal, release-notes:not-required

#22070 Add logging to rule-graph construction for basic performance tracing
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rule_graph/src/lib.rs
Labels: release-notes:not-required

#22076 Refactor children out into a separate crate.
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/children/Cargo.toml
  src/rust/engine/process_execution/children/src/lib.rs
  src/rust/engine/process_execution/src/lib.rs
Labels: release-notes:not-required

#22078 PBS: scrape 20250311 release
  docs/notes/2.26.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: needs-cherrypick, category:internal

#22079 PBS: scrape 20250311 release (Cherry-pick of #22078)
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal, release-notes:not-required

#22084 update 2.25.x release notes for PBS cherry pick
  docs/notes/2.25.x.md
Labels: needs-cherrypick, category:internal

#22087 update 2.25.x release notes for PBS cherry pick (Cherry-pick of #22084)
  docs/notes/2.25.x.md
Labels: category:internal, release-notes:not-required

#22088 Upgrade the clap CLI parsing crate to 4.5
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/fs/brfs/Cargo.toml
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/fs_util/Cargo.toml
  src/rust/engine/fs/fs_util/src/main.rs
  src/rust/engine/process_executor/src/main.rs
  src/rust/engine/testutil/local_cas/src/main.rs
  src/rust/engine/testutil/local_execution_server/src/main.rs
Labels: release-notes:not-required

#22093 Refactor the rust cli options used for creating a Store.
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/store/Cargo.toml
  src/rust/engine/fs/store/src/cli_options.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/grpc_util/src/tls.rs
  src/rust/engine/process_executor/src/main.rs
Labels: release-notes:not-required

#22100 Prepare 2.25.0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22091 Support local path "replace" in go.mod
  docs/notes/2.26.x.md
  src/python/pants/backend/go/util_rules/third_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg_test.py
Labels: needs-cherrypick, category:bugfix

#21980 Add --preserve-pip-download-log flag
  docs/notes/2.26.x.md
  src/python/pants/backend/python/goals/lockfile.py
Labels: category:new feature

#22109 fix: remote cache ResourceExhausted
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store.rs
Labels: release-notes:not-required

#22114 Prepare 2.26.0.dev9
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22105 Support local path "replace" in go.mod (Cherry-pick of #22091)
  src/python/pants/backend/go/util_rules/third_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg_test.py
Labels: category:bugfix, release-notes:not-required

#22106 Support local path "replace" in go.mod (Cherry-pick of #22091)
  src/python/pants/backend/go/util_rules/third_party_pkg.py
  src/python/pants/backend/go/util_rules/third_party_pkg_test.py
Labels: category:bugfix, release-notes:not-required

#22049 upgrade `debugby` and `pydevd-pycharm` distributions
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
Labels: category:internal, release-notes:not-required

#22115 Prepare 2.26.0a0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22119 Update RunsOn AMI.
  .github/runs-on.yml
Labels: release-notes:not-required

#22112 Mypy cache no longer shared between resolves
  docs/notes/2.26.x.md
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
Labels: needs-cherrypick

#22130 Mypy cache no longer shared between resolves (Cherry-pick of #22112)
  docs/notes/2.26.x.md
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
Labels: release-notes:not-required

#22126 Prepare 2.27.0.dev0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22118 Fix crash when base image is referenced by digest
  docs/notes/2.26.x.md
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: needs-cherrypick

#22136 Refer to Python 3.11, not 3.9, in plugin docs
  docs/docs/contributions/development/setting-up-pants.mdx
  docs/docs/writing-plugins/overview.mdx
Labels: needs-cherrypick, release-notes:not-required

#22137 Delete the very-unsupported manual installation instructions
  docs/docs/getting-started/installing-pants.mdx
  docs/docs/getting-started/manual-installation.mdx
  docs/docs/getting-started/prerequisites.mdx
Labels: release-notes:not-required

#22144 Refer to Python 3.11, not 3.9, in plugin docs (Cherry-pick of #22136)
  docs/docs/contributions/development/setting-up-pants.mdx
  docs/docs/writing-plugins/overview.mdx
Labels: release-notes:not-required

#22143 Refer to Python 3.11, not 3.9, in plugin docs (Cherry-pick of #22136)
  docs/docs/contributions/development/setting-up-pants.mdx
  docs/docs/writing-plugins/overview.mdx
Labels: release-notes:not-required

#22142 Fix crash when base image is referenced by digest (Cherry-pick of #22118)
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: release-notes:not-required

#22141 Fix crash when base image is referenced by digest (Cherry-pick of #22118)
  docs/notes/2.26.x.md
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
Labels: release-notes:not-required

#22094 Fixed various small VSCode dev container issues
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/onCreateCommand.sh
  .devcontainer/postCreateCommand.sh
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
  src/python/pants/backend/go/util_rules/cgo_test.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/rust/lint/rustfmt/BUILD
  src/python/pants/backend/rust/lint/rustfmt/rules_integration_test.py
  src/python/pants/backend/rust/util_rules/toolchains.py
  src/python/pants/testutil/skip_utils.py
Labels: release-notes:not-required

#22132 Prepare 2.24.3rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22131 Prepare 2.26.0a1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22134 Prepare 2.25.1rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep
