Repository pantsbuild/pants, pull requests merged in 2025-02, with the labels that each got.

#21878 Add extra buildInputs needed to use nix-shell on mac.
  shell.nix
Labels: release-notes:not-required

#21902 upgrade to Rust v1.84.1
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/rust-toolchain
Labels: category:internal, release-notes:not-required

#21901 A test to prove that @fromfile invalidation works now.
  docs/docs/using-pants/key-concepts/options.mdx
  src/python/pants/init/options_initializer.py
  src/python/pants/option/options_integration_test.py
Labels: release-notes:not-required

#21894 constrain importlib-metadata versions in twine lockfile
  docs/notes/2.25.x.md
  src/python/pants/backend/python/subsystems/twine.lock
  src/python/pants/backend/python/subsystems/twine.py
Labels: needs-cherrypick

#21899 Prepare 2.23.2rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21898 Prepare 2.25.0.dev6
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21905 constrain importlib-metadata versions in twine lockfile (Cherry-pick of #21894)
  src/python/pants/backend/python/subsystems/twine.lock
  src/python/pants/backend/python/subsystems/twine.py
Labels: release-notes:not-required

#21909 Prepare 2.24.1rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21865 Turn nailgun initialization message down to debug
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
Labels: release-notes:not-required

#21915 update python module mapping for `opentelemetry-proto`
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal, release-notes:not-required

#21912 enable streaming of integration test output
  docs/docs/writing-plugins/the-rules-api/testing-plugins.mdx
  docs/notes/2.25.x.md
  src/python/pants/testutil/pants_integration_test.py
Labels: category:internal

#21917 Prepare 2.24.1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21892 Surface stages in Dockerfiles which do not have tags
  docs/notes/2.25.x.md
  src/python/pants/backend/docker/subsystems/dockerfile_parser_test.py
  src/python/pants/backend/docker/subsystems/dockerfile_wrapper_script.py
  src/rust/engine/dep_inference/src/dockerfile/mod.rs
  src/rust/engine/dep_inference/src/dockerfile/tests.rs
  src/rust/engine/src/intrinsics/dep_inference.rs
Labels: category:bugfix, backend: Docker

#21914 fix: error message for PATH with relative path
  src/rust/engine/src/intrinsics/digests.rs
Labels: needs-cherrypick, category:internal, release-notes:not-required

#21916 warn instead of erroring out on almost certainly unintended PATH pref…
  docs/notes/2.25.x.md
  src/python/pants/core/util_rules/system_binaries.py
Labels: needs-cherrypick

#21923 warn instead of erroring out on almost certainly unintended PATH pref… (Cherry-pick of #21916)
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:bugfix, release-notes:not-required

#21922 fix: error message for PATH with relative path (Cherry-pick of #21914)
  src/rust/engine/src/intrinsics/digests.rs
Labels: category:internal, category:bugfix, release-notes:not-required

#21924 Prepare 2.24.2rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21931 scrape PBS release 20250205
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: needs-cherrypick, category:internal, release-notes:not-required

#21932 scrape PBS release 20250205 (Cherry-pick of #21931)
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal, release-notes:not-required

#21929 Prepare 2.26.0.dev0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21940 misc 2.25 release notes copyedits and sorting (Cherry-pick of #21934)
  docs/notes/2.25.x.md
Labels: release-notes:not-required

#21942 Set _PYTHON_HOST_PLATFORM when building wheels in CI
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants/BUILD
  src/python/pants_release/generate_github_workflows.py
  src/python/pants_release/release.py
Labels: needs-cherrypick, release-notes:not-required

#21944 Set _PYTHON_HOST_PLATFORM when building wheels in CI (Cherry-pick of #21942)
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants/BUILD
  src/python/pants_release/generate_github_workflows.py
  src/python/pants_release/release.py
Labels: release-notes:not-required

#21945 Prepare 2.26.0.dev1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21943 Move CLI flag extraction into ArgSplitter
  docs/notes/2.25.x.md
  src/python/pants/option/errors.py
  src/python/pants/option/options_test.py
  src/rust/engine/options/src/arg_splitter.rs
  src/rust/engine/options/src/arg_splitter_tests.rs
  src/rust/engine/options/src/flags.rs
  src/rust/engine/options/src/flags_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/scope.rs
  src/rust/engine/options/src/scope_tests.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/src/externs/options.rs
Labels: needs-cherrypick

#21950 Move CLI flag extraction into ArgSplitter (Cherry-pick of #21943)
  docs/notes/2.25.x.md
  src/python/pants/option/errors.py
  src/python/pants/option/options_test.py
  src/rust/engine/options/src/arg_splitter.rs
  src/rust/engine/options/src/arg_splitter_tests.rs
  src/rust/engine/options/src/flags.rs
  src/rust/engine/options/src/flags_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/scope.rs
  src/rust/engine/options/src/scope_tests.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/src/externs/options.rs
Labels: release-notes:not-required

#21949 Prepare 2.25.0a1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21951 Temporary fix for spurious errors on negative specs.
  src/python/pants/option/options.py
Labels: release-notes:not-required

#21952 Prepare 2.24.2rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21961 Prepare 2.26.0.dev2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21962 Prepare 2.24.2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21957 support debug mode for `experimental_test_shell_command` target type
  docs/notes/2.26.x.md
  src/python/pants/backend/shell/goals/test.py
  src/python/pants/backend/shell/goals/test_test.py
Labels: category:new feature

#21953 add GitHub artifact attestations for releases
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21965 Prepare 2.26.0.dev3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21966 fix the release process
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21967 Prepare 2.26.0.dev4
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21968 set `contents: write` to allow release creation
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21969 Prepare 2.26.0.dev5
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21972 back port attestation workflow to 2.25.x
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21971 use a more common spelling of "inferable"
  src/python/pants/backend/helm/dependency_inference/subsystem.py
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/core/util_rules/unowned_dependency_behavior.py
  src/python/pants/version.py
Labels: release-notes:not-required

#21978 remove temporary `continue-on-error` configs in release workflow
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21992 upgrade to Rust v1.85.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/rust-toolchain
Labels: category:internal, release-notes:not-required

#21989 Installing cargo-audit as per the Github instructions
  .github/workflows/audit.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#21993 Prepare 2.26.0.dev6
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21988 Dependabot | Removed Stu and added several other default reviewers
  .github/dependabot.yml
Labels: category:internal, release-notes:not-required

#21996 [Call-by-name] Shell backend
  docs/notes/2.26.x.md
  src/python/pants/backend/shell/dependency_inference.py
  src/python/pants/backend/shell/goals/tailor.py
  src/python/pants/backend/shell/goals/test.py
  src/python/pants/backend/shell/lint/shellcheck/rules.py
  src/python/pants/backend/shell/lint/shfmt/rules.py
  src/python/pants/backend/shell/shunit2_test_runner.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
Labels: category:internal

#21994 feat(ghac): Bump opendal to support ghac v2
  docs/notes/2.25.x.md
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/remote_provider/remote_provider_opendal/src/action_cache_tests.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/lib.rs
Labels: needs-cherrypick

#21997 feat(ghac): Bump opendal to support ghac v2 (Cherry-pick of #21994)
  docs/notes/2.25.x.md
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/remote_provider/remote_provider_opendal/src/action_cache_tests.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/lib.rs
Labels: release-notes:not-required

#21999 [Call-by-name] Several experimental Python backends
  docs/notes/2.26.x.md
  pants.toml
  src/python/pants/backend/python/framework/stevedore/python_target_dependencies.py
  src/python/pants/backend/python/framework/stevedore/rules.py
  src/python/pants/backend/python/lint/add_trailing_comma/rules.py
  src/python/pants/backend/python/lint/ruff/check/rules.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/python/typecheck/pyright/rules.py
  src/python/pants/backend/python/typecheck/pytype/pytype.lock
  src/python/pants/backend/python/typecheck/pytype/rules.py
  src/python/pants/backend/python/typecheck/pytype/rules_integration_test.py
  src/python/pants/backend/python/typecheck/pytype/subsystem.py
Labels: category:internal

#22004 [Call-by-name] Migrated most of python linters
  docs/notes/2.26.x.md
  src/python/pants/backend/python/lint/autoflake/rules.py
  src/python/pants/backend/python/lint/bandit/rules.py
  src/python/pants/backend/python/lint/black/rules.py
  src/python/pants/backend/python/lint/docformatter/rules.py
  src/python/pants/backend/python/lint/flake8/rules.py
  src/python/pants/backend/python/lint/flake8/subsystem.py
  src/python/pants/backend/python/lint/isort/rules.py
  src/python/pants/backend/python/lint/pydocstyle/rules.py
  src/python/pants/backend/python/lint/pyupgrade/rules.py
  src/python/pants/backend/python/lint/yapf/rules.py
  src/python/pants/goal/migrate_call_by_name.py
Labels: category:internal

#22003 shell: support `runnable_dependencies` for `experimental_test_shell_command`
  docs/notes/2.26.x.md
  src/python/pants/backend/shell/goals/test_test.py
  src/python/pants/backend/shell/target_types.py
Labels: category:new feature

#22006 [Call-by-name] Rust, Visibility, Tools backends
  docs/notes/2.26.x.md
  src/python/pants/backend/rust/goals/tailor.py
  src/python/pants/backend/rust/lint/rustfmt/rules.py
  src/python/pants/backend/rust/util_rules/toolchains.py
  src/python/pants/backend/tools/preamble/rules.py
  src/python/pants/backend/tools/taplo/rules.py
  src/python/pants/backend/visibility/lint.py
  src/python/pants/backend/visibility/rules.py
Labels: category:internal

#22002 shell: support extra output files in `experimental_test_shell_command`
  docs/notes/2.26.x.md
  src/python/pants/backend/shell/goals/test.py
  src/python/pants/backend/shell/goals/test_test.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/core/goals/test.py
Labels: category:new feature

#22005 Allow there to be no Django apps.
  docs/notes/2.26.x.md
  src/python/pants/backend/python/framework/django/detect_apps.py
Labels: category:bugfix

#22007 [Call-by-name] Migrated django framework
  docs/notes/2.26.x.md
  src/python/pants/backend/python/framework/django/dependency_inference.py
  src/python/pants/backend/python/framework/django/detect_apps.py
Labels: category:internal

#22015 remove explicit uses of lazy_static
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/dep_inference/src/dockerfile/mod.rs
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/fs/src/gitignore.rs
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/grpc_util/Cargo.toml
  src/rust/engine/grpc_util/src/lib.rs
  src/rust/engine/logging/Cargo.toml
  src/rust/engine/logging/src/logger.rs
  src/rust/engine/options/Cargo.toml
  src/rust/engine/options/src/arg_splitter.rs
  src/rust/engine/options/src/cli_alias.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/process_execution/Cargo.toml
  src/rust/engine/process_execution/pe_nailgun/Cargo.toml
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/engine/process_execution/src/bounded.rs
  src/rust/engine/src/externs/address.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/mod.rs
Labels: release-notes:not-required

#22017 [Call-by-name] Migrated go lint
  docs/notes/2.26.x.md
  src/python/pants/backend/go/lint/gofmt/rules.py
  src/python/pants/backend/go/lint/golangci_lint/rules.py
  src/python/pants/backend/go/lint/vet/rules.py
Labels: category:internal

#22018 Prepare 2.25.0a2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22020 Prepare 2.26.0.dev7
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22022 fix a typo in the release notes
  docs/notes/2.26.x.md
Labels: category:internal

#22021 update release notes for 2.25 release
  docs/notes/2.25.x.md
Labels: needs-cherrypick, category:internal, release-notes:not-required
