Repository pantsbuild/pants, pull requests merged in 2025-10, with the labels that each got.

#22732 Go dependency download and analysis performance fix (Cherry-pick of #22726)
  src/python/pants/backend/go/util_rules/third_party_pkg.py
Labels: category:bugfix, release-notes:not-required

#22730 Go dependency download and analysis performance fix (Cherry-pick of #22726)
  src/python/pants/backend/go/util_rules/third_party_pkg.py
Labels: category:bugfix, release-notes:not-required

#22733 Fix issues in call-by-name docs
  docs/docs/writing-plugins/the-rules-api/concepts.mdx
  docs/docs/writing-plugins/the-rules-api/rules-and-the-target-api.mdx
Labels: release-notes:not-required

#22728 Prepare 2.30.0.dev2
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22729 Prepare 2.29.0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22718 use upstream rust-cache action
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: release-notes:not-required

#22735 re-sync generated github workflows
  .github/workflows/test.yaml
Labels: release-notes:not-required

#22736 Fix an inappropriate argument to concurrently() (cherry-pick of #22712)
  src/python/pants/engine/internals/selectors.py
  src/python/pants/engine/internals/selectors_test.py
  src/python/pants/jvm/goals/lockfile.py
Labels: release-notes:not-required
