Repository pantsbuild/pants, pull requests merged in 2025-05, with the labels that each got.

#22227 Prepare 2.27.0.dev3
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22218 Initialise terraform in the same invocation as subsequent commands
  docs/notes/2.27.x.md
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/dependencies_test.py
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/goals/deploy.py
  src/python/pants/backend/terraform/goals/lockfiles.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/backend/terraform/testutil.py
  src/python/pants/backend/terraform/tool.py
Labels: backend: Terraform

#22231 docs: fix typo in regards to resolves_to_no_binary
  docs/docs/python/overview/third-party-dependencies.mdx
Labels: release-notes:not-required

#22226 Prepare 2.26.0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22230 Unit and integration tests for the sandboxer.
  src/rust/engine/Cargo.toml
  src/rust/engine/process_execution/sandboxer/src/lib.rs
  src/rust/engine/process_execution/sandboxer/src/test_util.rs
  src/rust/engine/process_execution/sandboxer/src/tests.rs
  src/rust/engine/process_execution/sandboxer/tests/integration_test.rs
Labels: release-notes:not-required

#22238 revert to pip 25.0 for lockfile generation
  3rdparty/python/user_reqs.lock
  pants.toml
Labels: release-notes:not-required

#21780 Add Trivy security scanner
  docs/docs/docker/index.mdx
  docs/docs/helm/index.mdx
  docs/docs/helm/kubeconform.mdx
  docs/docs/terraform/index.mdx
  docs/docs/writing-plugins/common-plugin-tasks/add-a-linter.mdx
  docs/docs/writing-plugins/common-subsystem-tasks.mdx
  docs/notes/2.27.x.md
  src/python/pants/backend/docker/lint/trivy/BUILD
  src/python/pants/backend/docker/lint/trivy/__init__.py
  src/python/pants/backend/docker/lint/trivy/rules.py
  src/python/pants/backend/docker/lint/trivy/trivy_integration_test.py
  src/python/pants/backend/experimental/docker/lint/trivy/__init__.py
  src/python/pants/backend/experimental/docker/lint/trivy/register.py
  src/python/pants/backend/experimental/helm/lint/__init__.py
  src/python/pants/backend/experimental/helm/lint/trivy/BUILD
  src/python/pants/backend/experimental/helm/lint/trivy/__init__.py
  src/python/pants/backend/experimental/helm/lint/trivy/register.py
  src/python/pants/backend/experimental/terraform/lint/trivy/__init__.py
  src/python/pants/backend/experimental/terraform/lint/trivy/register.py
  src/python/pants/backend/helm/lint/__init__.py
  src/python/pants/backend/helm/lint/trivy/BUILD
  src/python/pants/backend/helm/lint/trivy/__init__.py
  src/python/pants/backend/helm/lint/trivy/rules.py
  src/python/pants/backend/helm/lint/trivy/trivy_integration_test.py
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/goals/deploy.py
  src/python/pants/backend/terraform/lint/trivy/BUILD
  src/python/pants/backend/terraform/lint/trivy/__init__.py
  src/python/pants/backend/terraform/lint/trivy/rules.py
  src/python/pants/backend/terraform/lint/trivy/trivy_integration_test.py
  src/python/pants/backend/terraform/testutil.py
  src/python/pants/backend/tools/trivy/BUILD
  src/python/pants/backend/tools/trivy/__init__.py
  src/python/pants/backend/tools/trivy/rules.py
  src/python/pants/backend/tools/trivy/subsystem.py
  src/python/pants/backend/tools/trivy/testutil.py
Labels: category:new feature, backend: Docker, backend: Helm, backend: Terraform

#22245 fix up some whitespace issues in field help docs
  src/python/pants/backend/adhoc/target_types.py
Labels: category:documentation, release-notes:not-required

#22252 [Call-by-name] Migrated JS Prettier
  src/python/pants/backend/javascript/lint/prettier/rules.py
Labels: category:internal, backend: JavaScript, release-notes:not-required

#22253 [Call-by-name] migrate `pants.backend.url_handlers.s3` backend
  src/python/pants/backend/url_handlers/s3/register.py
Labels: category:internal, release-notes:not-required

#22256 [Call-by-name] migrate `pants.backend.experimental.codegen.avro.java` backend
  src/python/pants/backend/codegen/avro/java/rules.py
  src/python/pants/backend/codegen/avro/tailor.py
Labels: category:internal, release-notes:not-required

#22257 [Call-by-name] migrate `pants.backend.experimental.kotlin` backend
  src/python/pants/backend/kotlin/compile/kotlinc.py
  src/python/pants/backend/kotlin/compile/kotlinc_plugins.py
  src/python/pants/backend/kotlin/dependency_inference/kotlin_parser.py
  src/python/pants/backend/kotlin/dependency_inference/rules.py
  src/python/pants/backend/kotlin/dependency_inference/symbol_mapper.py
  src/python/pants/backend/kotlin/goals/check.py
  src/python/pants/backend/kotlin/goals/tailor.py
  src/python/pants/backend/kotlin/test/junit.py
Labels: category:internal, release-notes:not-required

#22258 Prepare 2.27.0a0
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22259 Create blank release notes for the 2.28.x release series.
  docs/notes/2.28.x.md
Labels: release-notes:not-required

#22261 [Call-by-name] migrate `pants.backend.experimental.codegen.protobuf.go` backend
  src/python/pants/backend/codegen/protobuf/go/rules.py
Labels: category:internal, release-notes:not-required

#22264 [Call-by-name] migrate `pants.backend.experimental.codegen.python_format_string.k8s` backend
  src/python/pants/backend/codegen/python_format_string/k8s/rules.py
Labels: category:internal, release-notes:not-required

#22263 fix remote cache integration test to wait for CAS/AC to settle
  src/python/pants/engine/internals/native_engine.pyi
  src/rust/engine/src/externs/testutil.rs
  src/rust/engine/testutil/mock/src/cas.rs
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: category:internal, release-notes:not-required

#22255 [Call-by-name] migrate `pants.backend.experimental.codegen.protobuf.scala` backend
  src/python/pants/backend/codegen/protobuf/scala/dependency_inference.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
Labels: category:internal, release-notes:not-required

#22260 [Call-by-name] Migrated `pants.backend.python.lint.pylint`
  src/python/pants/backend/python/lint/pylint/rules.py
  src/python/pants/backend/python/lint/pylint/subsystem.py
Labels: category:internal, backend: Python, release-notes:not-required

#22266 [Call-by-name] Migrated `pants.backend.python.typecheck.mypy`
  src/python/pants/backend/python/typecheck/mypy/mypyc.py
  src/python/pants/backend/python/typecheck/mypy/rules.py
  src/python/pants/backend/python/typecheck/mypy/subsystem.py
Labels: category:internal, backend: Python, release-notes:not-required

#22262 [Call-by-name] Manually migrated the common ruff code
  src/python/pants/backend/python/lint/ruff/common.py
Labels: category:internal, backend: Python, release-notes:not-required

#22249 [Call-by-name] Migrate pyenv & pyenv.custom_install provider backends
  src/python/pants/backend/python/providers/pyenv/custom_install/rules.py
  src/python/pants/backend/python/providers/pyenv/rules.py
Labels: release-notes:not-required

#22270 [Call-by-name] migrate Thrift codegen backends
  src/python/pants/backend/codegen/thrift/apache/java/rules.py
  src/python/pants/backend/codegen/thrift/jvm_symbol_mapper.py
  src/python/pants/backend/codegen/thrift/scrooge/java/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/rules.py
  src/python/pants/backend/codegen/thrift/scrooge/scala/rules.py
Labels: category:internal, release-notes:not-required

#22274 [Call-by-name] Migrate python_build_standalone provider backend
  src/python/pants/backend/python/providers/python_build_standalone/rules.py
Labels: release-notes:not-required

#22268 [Call-by-name] migrate OpenAPI backends
  src/python/pants/backend/openapi/codegen/java/rules.py
  src/python/pants/backend/openapi/codegen/python/generate.py
  src/python/pants/backend/openapi/codegen/python/package_mapper.py
  src/python/pants/backend/openapi/dependency_inference.py
  src/python/pants/backend/openapi/goals/tailor.py
  src/python/pants/backend/openapi/lint/openapi_format/rules.py
  src/python/pants/backend/openapi/lint/spectral/rules.py
  src/python/pants/backend/openapi/util_rules/generator_process.py
  src/python/pants/backend/openapi/util_rules/openapi_bundle.py
  src/python/pants/backend/openapi/util_rules/pom_parser.py
Labels: category:internal, release-notes:not-required

#22265 [Call-by-name] migrate Terraform backends
  src/python/pants/backend/terraform/dependencies.py
  src/python/pants/backend/terraform/dependency_inference.py
  src/python/pants/backend/terraform/goals/check.py
  src/python/pants/backend/terraform/goals/deploy.py
  src/python/pants/backend/terraform/goals/lockfiles.py
  src/python/pants/backend/terraform/goals/tailor.py
  src/python/pants/backend/terraform/lint/tffmt/tffmt.py
  src/python/pants/backend/terraform/lint/tfsec/rules.py
  src/python/pants/backend/terraform/tool.py
Labels: category:internal, release-notes:not-required

#22272 [Call-by-name] migrate `pants.backend.google_cloud_function.python` backend
  src/python/pants/backend/google_cloud_function/python/rules.py
Labels: category:internal, release-notes:not-required

#22271 [Call-by-name] migrate BSP backends
  src/python/pants/backend/java/bsp/rules.py
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/bsp/util_rules/compile.py
  src/python/pants/bsp/util_rules/resources.py
  src/python/pants/bsp/util_rules/targets.py
Labels: category:internal, release-notes:not-required

#22276 [Call-by-name] migrate `src/python/pants/jvm/resolve`
  src/python/pants/jvm/resolve/coursier_fetch.py
  src/python/pants/jvm/resolve/coursier_setup.py
  src/python/pants/jvm/resolve/jvm_tool.py
Labels: category:internal, release-notes:not-required

#22278 [Call-by-name] Migrated `pants.backend.python.mixed_interpreter_constraints`
  src/python/pants/backend/project_info/dependents.py
  src/python/pants/backend/python/mixed_interpreter_constraints/py_constraints.py
Labels: category:internal, backend: Python, release-notes:not-required

#22277 [Call-by-name] migrate `src/python/pants/jvm/test`
  src/python/pants/jvm/test/junit.py
Labels: category:internal, release-notes:not-required

#22281 [Call-by-name] Migrated `pants.backend.project_info`
  src/python/pants/backend/project_info/count_loc.py
  src/python/pants/backend/project_info/dependencies.py
  src/python/pants/backend/project_info/dependents.py
  src/python/pants/backend/project_info/filedeps.py
  src/python/pants/backend/project_info/list_targets.py
  src/python/pants/backend/project_info/paths.py
  src/python/pants/backend/project_info/peek.py
  src/python/pants/backend/project_info/regex_lint.py
Labels: category:internal, release-notes:not-required

#22282 [Call-by-name] Migrate pants.backend.experimental.*.debug_goals
  src/python/pants/backend/java/goals/debug_goals.py
  src/python/pants/backend/scala/goals/debug_goals.py
Labels: release-notes:not-required

#22285 [Call-by-name] Migrated `pants.backend.experimental.typescript`
  src/python/pants/backend/typescript/dependency_inference/rules.py
Labels: category:internal, backend: JavaScript, release-notes:not-required

#22279 [call-by-name] migrate pants.backend.experimental.go.debug_goals
  src/python/pants/backend/go/goals/debug_goals.py
Labels: backend: Go, category:internal, release-notes:not-required

#22286 skip remote cache integration test
  tests/python/pants_test/integration/remote_cache_integration_test.py
Labels: category:internal, release-notes:not-required

#22290 [Call-by-name] migrate Java backends
  src/python/pants/backend/java/compile/javac.py
  src/python/pants/backend/java/dependency_inference/java_parser.py
  src/python/pants/backend/java/dependency_inference/rules.py
  src/python/pants/backend/java/dependency_inference/symbol_mapper.py
  src/python/pants/backend/java/goals/check.py
  src/python/pants/backend/java/goals/tailor.py
Labels: category:internal, release-notes:not-required

#22289 [Call-by-name] migrate Scala backends
  src/python/pants/backend/scala/compile/scalac.py
  src/python/pants/backend/scala/compile/scalac_plugins.py
  src/python/pants/backend/scala/dependency_inference/rules.py
  src/python/pants/backend/scala/dependency_inference/scala_parser.py
  src/python/pants/backend/scala/dependency_inference/symbol_mapper.py
  src/python/pants/backend/scala/goals/check.py
  src/python/pants/backend/scala/goals/repl.py
  src/python/pants/backend/scala/goals/tailor.py
  src/python/pants/backend/scala/lint/scalafix/rules.py
  src/python/pants/backend/scala/resolve/artifact.py
  src/python/pants/backend/scala/resolve/lockfile.py
  src/python/pants/backend/scala/test/scalatest.py
Labels: category:internal, release-notes:not-required

#22291 [Call-by-name] Migrated pants.backend.python (part 2)
  src/python/pants/backend/python/goals/export.py
  src/python/pants/backend/python/goals/publish.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/goals/repl.py
  src/python/pants/backend/python/goals/run_helper.py
  src/python/pants/backend/python/goals/run_pex_binary.py
  src/python/pants/backend/python/goals/run_python_requirement.py
  src/python/pants/backend/python/goals/run_python_source.py
  src/python/pants/backend/python/goals/tailor.py
Labels: category:internal, backend: Python, release-notes:not-required

#22288 [Call-by-name] migrate docker backends
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/backend/docker/goals/publish.py
  src/python/pants/backend/docker/goals/run_image.py
  src/python/pants/backend/docker/goals/tailor.py
  src/python/pants/backend/docker/lint/hadolint/rules.py
  src/python/pants/backend/docker/lint/trivy/rules.py
  src/python/pants/backend/docker/subsystems/dockerfile_parser.py
  src/python/pants/backend/docker/util_rules/dependencies.py
  src/python/pants/backend/docker/util_rules/docker_binary.py
  src/python/pants/backend/docker/util_rules/docker_binary_test.py
  src/python/pants/backend/docker/util_rules/docker_build_context.py
  src/python/pants/backend/docker/util_rules/docker_build_env.py
Labels: release-notes:not-required

#22275 Prepare 2.28.0.dev0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22293 [Call-by-name] Migrated `pants.backend.python` (part 4)
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
  src/python/pants/backend/python/util_rules/pex_requirements.py
  src/python/pants/backend/python/util_rules/pex_venv.py
Labels: category:internal, backend: Python, release-notes:not-required

#22292 [Call-by-name] `Migrated pants.backend.python` (part 3)
  src/python/pants/backend/python/util_rules/ancestor_files.py
  src/python/pants/backend/python/util_rules/dists.py
  src/python/pants/backend/python/util_rules/entry_points.py
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/local_dists.py
  src/python/pants/backend/python/util_rules/local_dists_pep660.py
  src/python/pants/backend/python/util_rules/lockfile_diff.py
  src/python/pants/backend/python/util_rules/package_dists.py
  src/python/pants/backend/python/util_rules/partition.py
  src/python/pants/backend/python/util_rules/python_sources.py
  src/python/pants/backend/python/util_rules/vcs_versioning.py
Labels: category:internal, backend: Python, release-notes:not-required

#22287 [Call-by-name] migrate core system binaries rules
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:internal, release-notes:not-required

#22296 [Call-by-name] Migrated `pants.backend.experimental.javascript`
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/javascript/goals/export.py
  src/python/pants/backend/javascript/goals/lockfile.py
  src/python/pants/backend/javascript/goals/test.py
  src/python/pants/backend/javascript/goals/test_test.py
  src/python/pants/backend/javascript/install_node_package.py
  src/python/pants/backend/javascript/nodejs_project.py
  src/python/pants/backend/javascript/nodejs_project_environment.py
  src/python/pants/backend/javascript/package/rules.py
  src/python/pants/backend/javascript/package_json.py
  src/python/pants/backend/javascript/resolve.py
  src/python/pants/backend/javascript/run/rules.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_test.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool.py
Labels: category:internal, backend: JavaScript, release-notes:not-required

#22283 [Call-by-name] migrate src/python/pants/backend/go/util_rules
  src/python/pants/backend/go/go_sources/load_go_binary.py
  src/python/pants/backend/go/util_rules/assembly.py
  src/python/pants/backend/go/util_rules/binary.py
  src/python/pants/backend/go/util_rules/build_opts.py
  src/python/pants/backend/go/util_rules/build_pkg.py
  src/python/pants/backend/go/util_rules/cgo_binaries.py
Labels: backend: Go, category:internal, release-notes:not-required

#22297 Fix bug in mock get resolution.
  src/python/pants/testutil/rule_runner.py
Labels: release-notes:not-required

#22269 [Call-by-name] migrate Helm backends
  src/python/pants/backend/helm/check/kubeconform/chart.py
  src/python/pants/backend/helm/check/kubeconform/common.py
  src/python/pants/backend/helm/check/kubeconform/deployment.py
  src/python/pants/backend/helm/dependency_inference/chart.py
  src/python/pants/backend/helm/dependency_inference/deployment.py
  src/python/pants/backend/helm/dependency_inference/unittest.py
  src/python/pants/backend/helm/goals/deploy.py
  src/python/pants/backend/helm/goals/lint.py
  src/python/pants/backend/helm/goals/package.py
  src/python/pants/backend/helm/goals/publish.py
  src/python/pants/backend/helm/goals/tailor.py
  src/python/pants/backend/helm/lint/trivy/rules.py
  src/python/pants/backend/helm/resolve/artifacts.py
  src/python/pants/backend/helm/resolve/fetch.py
  src/python/pants/backend/helm/subsystems/k8s_parser.py
  src/python/pants/backend/helm/subsystems/post_renderer.py
  src/python/pants/backend/helm/test/unittest.py
  src/python/pants/backend/helm/util_rules/chart.py
  src/python/pants/backend/helm/util_rules/chart_metadata.py
  src/python/pants/backend/helm/util_rules/post_renderer.py
  src/python/pants/backend/helm/util_rules/renderer.py
  src/python/pants/backend/helm/util_rules/sources.py
  src/python/pants/backend/helm/util_rules/tool.py
Labels: category:internal, release-notes:not-required

#22300 [Call-by-name] migrate `src/python/pants/jvm/package`
  src/python/pants/jvm/package/deploy_jar.py
  src/python/pants/jvm/package/war.py
Labels: category:internal, release-notes:not-required

#22302 [Call-by-name] migrate `src/python/pants/jvm/jar_tool/jar_tool.py`
  src/python/pants/jvm/jar_tool/jar_tool.py
Labels: category:internal, release-notes:not-required

#22303 [Call-by-name] migrate `src/python/pants/vcs::`
  src/python/pants/vcs/changed.py
Labels: category:internal, release-notes:not-required

#22304 [Call-by-name] Migrated remaining `pants.backend.python` that weren't cyclic deps or unions
  src/python/pants/backend/python/dependency_inference/rules.py
  src/python/pants/backend/python/target_types_rules.py
  src/python/pants/backend/python/util_rules/entry_points.py
  src/python/pants/backend/python/util_rules/package_dists.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/python/util_rules/pex_from_targets.py
Labels: category:internal, backend: Python, release-notes:not-required

#22305 [Call-by-name] migrate `src/python/pants/jvm/resources.py`
  src/python/pants/jvm/resources.py
Labels: category:internal, release-notes:not-required

#22310 [Call-by-name] migrate `src/python/pants/core/util_rules/archive.py`
  src/python/pants/core/util_rules/archive.py
Labels: category:internal, release-notes:not-required

#22311 [Call-by-name] migrate `src/python/pants/core/util_rules/stripped_source_files.py`
  src/python/pants/core/util_rules/stripped_source_files.py
Labels: category:internal, release-notes:not-required

#22308 [Call-by-name] migrate `src/python/pants/core/goals/update_build_files.py`
  src/python/pants/core/goals/update_build_files.py
Labels: category:internal, release-notes:not-required

#22307 [Call-by-name] migrate `src/python/pants/jvm/strip_jar::`
  src/python/pants/jvm/strip_jar/strip_jar.py
Labels: category:internal, release-notes:not-required

#22309 [Call-by-name] migrate `src/python/pants/vcs/git_test.py`
  src/python/pants/vcs/git_test.py
Labels: category:internal, release-notes:not-required

#22313 [Call-by-name] migrate tests in `src/python/pants/core/goals`
  src/python/pants/core/goals/deploy_test.py
  src/python/pants/core/goals/export_integration_test.py
  src/python/pants/core/goals/fix_test.py
  src/python/pants/core/goals/generate_snapshots_test.py
  src/python/pants/core/goals/package_test.py
  src/python/pants/core/goals/repl_test.py
  src/python/pants/core/goals/tailor_test.py
Labels: category:internal, release-notes:not-required

#22312 [Call-by-name] migrate `src/python/pants/core/util_rules/environments.py`
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
Labels: category:internal, release-notes:not-required

#22318 [Call-by-name] migrate `src/python/pants/jvm/shading::`
  src/python/pants/jvm/shading/rules.py
Labels: category:internal, release-notes:not-required

#22319 [Call-by-name] migrate `src/python/pants/core/goals/tailor.py`
  src/python/pants/core/goals/tailor.py
Labels: category:internal, release-notes:not-required

#22316 upgrade to Rust v1.87.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/dep_inference/src/javascript/tests.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/options/src/arg_splitter_tests.rs
  src/rust/engine/options/src/fromfile_tests.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/process_execution/children/src/lib.rs
  src/rust/engine/process_execution/sandboxer/src/tests.rs
  src/rust/engine/process_execution/sandboxer/tests/integration_test.rs
  src/rust/engine/process_execution/src/tests.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store.rs
  src/rust/engine/rust-toolchain
  src/rust/engine/src/downloads.rs
  src/rust/engine/src/python.rs
  src/rust/engine/testutil/mock/src/cas_service.rs
  src/rust/engine/workunit_store/src/lib.rs
Labels: category:internal, release-notes:not-required

#22322 Update to newer RunsOn AMI.
  .github/runs-on.yml
Labels: release-notes:not-required

#22321 Simplify rule mock validation.
  src/python/pants/backend/docker/goals/package_image_test.py
  src/python/pants/core/goals/check_test.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/test_test.py
  src/python/pants/engine/internals/selectors.py
  src/python/pants/testutil/rule_runner.py
Labels: release-notes:not-required

#22306 [Call-by-name] migrate src/python/pants/backend/go/util_rules
  src/python/pants/backend/go/target_type_rules.py
  src/python/pants/backend/go/util_rules/build_pkg_target.py
  src/python/pants/backend/go/util_rules/build_pkg_target_test.py
  src/python/pants/backend/go/util_rules/vendor.py
Labels: release-notes:not-required

#22317 fix: Inherit required field for JS goals in typescript target
  docs/notes/2.28.x.md
  src/python/pants/backend/typescript/target_types.py
Labels: backend: JavaScript

#22323 Prepare 2.28.0.dev1
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22325 [Call-by-name] migrate `src/python/pants/core/goals/deploy.py`
  src/python/pants/core/goals/deploy.py
Labels: category:internal, release-notes:not-required

#22326 [Call-by-name] migrate `src/python/pants/core/subsystems/python_bootstrap.py`
  src/python/pants/core/subsystems/python_bootstrap.py
Labels: category:internal, release-notes:not-required

#22330 [Call-by-name] migrate `src/python/pants/core/util_rules/subprocess_environment.py`
  src/python/pants/core/util_rules/subprocess_environment.py
Labels: category:internal, release-notes:not-required

#22328 [Call-by-name] migrate `src/python/pants/engine/download_file.py`
  src/python/pants/engine/download_file.py
  src/python/pants/engine/download_file_integration_test.py
Labels: category:internal, release-notes:not-required

#22329 [Call-by-name] migrate `src/python/pants/engine/desktop.py`
  src/python/pants/engine/desktop.py
Labels: category:internal, release-notes:not-required

#22331 [Call-by-name] migrate `src/python/pants/core/util_rules/wrap_source.py`
  src/python/pants/core/util_rules/wrap_source.py
Labels: category:internal, release-notes:not-required

#22327 Reduce dependencies on PythonDistributionFieldSet.
  src/python/pants/backend/python/goals/package_dists.py
  src/python/pants/backend/python/goals/package_pex_binary_integration_test.py
  src/python/pants/backend/python/util_rules/local_dists_pep660.py
  src/python/pants/backend/python/util_rules/package_dists.py
  src/python/pants/backend/python/util_rules/package_dists_test.py
Labels: release-notes:not-required

#22335 PBS: scrape release 20250517
  docs/notes/2.28.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal

#22333 [Call-by-name] migrate `src/python/pants/core/util_rules/partitions.py`
  src/python/pants/core/util_rules/partitions.py
Labels: category:internal, release-notes:not-required

#22336 [Call-by-name] migrate various files in `src/python/pants/jvm`
  src/python/pants/jvm/classpath.py
  src/python/pants/jvm/compile.py
  src/python/pants/jvm/dependency_inference/symbol_mapper.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/jvm/run.py
  src/python/pants/jvm/run_deploy_jar.py
  src/python/pants/jvm/testutil.py
  src/python/pants/jvm/util_rules.py
Labels: category:internal, release-notes:not-required

#22337 [Call-by-name] migrate remainder of k8s backend
  src/python/pants/backend/k8s/goals/deploy.py
Labels: category:internal, release-notes:not-required

#22339 [Call-by-name] migrate `src/python/pants/engine/internals/engine_benchmarks_test.py`
  src/python/pants/engine/internals/engine_benchmarks_test.py
Labels: category:internal, release-notes:not-required

#22338 [Call-by-name] migrate `src/python/pants/engine/internals/specs_rules.py`
  src/python/pants/engine/internals/specs_rules.py
Labels: category:internal, release-notes:not-required

#22340 [Call-by-name] migrate `src/python/pants/source/source_root.py`
  src/python/pants/source/source_root.py
  src/python/pants/source/source_root_test.py
Labels: category:internal, release-notes:not-required

#22341 [Call-by-name] migrate `src/python/pants/engine/internals/platform_rules.py`
  src/python/pants/engine/internals/platform_rules.py
  src/python/pants/engine/internals/platform_rules_test.py
Labels: category:internal, release-notes:not-required

#22344 [Call-by-name] migrate test file in nfpm backend
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
Labels: category:internal, release-notes:not-required

#22345 [Call-by-name] migrate core/util_rules/external_tool and core/goals/fix_test
  src/python/pants/core/goals/fix_test.py
  src/python/pants/core/util_rules/external_tool.py
Labels: category:internal, release-notes:not-required

#22342 [Call-by-name] migrate `src/python/pants/backend/codegen/export_codegen_goal_test.py`
  src/python/pants/backend/codegen/export_codegen_goal_test.py
Labels: category:internal, release-notes:not-required

#22343 [Call-by-name] migrate publish goal (except unions)
  src/python/pants/core/goals/publish.py
Labels: category:internal, release-notes:not-required

#22346 [Call-by-name] migrate `src/python/pants/engine/fs_test.py`
  src/python/pants/engine/fs_test.py
Labels: category:internal, release-notes:not-required

#22347 [Call-by-name] migrate remaining "easy" call site in Helm backend
  src/python/pants/backend/helm/util_rules/post_renderer.py
Labels: category:internal, release-notes:not-required

#22350 [Call-by-name] migrate `src/python/pants/engine/internals/graph_test.py`
  src/python/pants/engine/internals/graph_test.py
Labels: category:internal, release-notes:not-required

#22351 [Call-by-name] migrate core package goal (except for a union)
  src/python/pants/core/goals/package.py
Labels: category:internal, release-notes:not-required

#22349 [Call-by-name] migrate core export goal (except for unions)
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/export_test.py
Labels: category:internal, release-notes:not-required

#22355 ensure error when duplicate declared targets exist in same directory
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: needs-cherrypick, category:bugfix, release-notes:not-required

#22357 ensure error when duplicate declared targets exist in same directory (Cherry-pick of #22355)
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: category:bugfix, release-notes:not-required

#22356 ensure error when duplicate declared targets exist in same directory (Cherry-pick of #22355)
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
Labels: category:bugfix, release-notes:not-required

#22352 refactor environments-related target types and subsystem to avoid import cycle
  src/python/pants/backend/adhoc/adhoc_tool_test.py
  src/python/pants/backend/adhoc/target_types.py
  src/python/pants/backend/awslambda/python/rules.py
  src/python/pants/backend/awslambda/python/target_types.py
  src/python/pants/backend/codegen/thrift/apache/rules.py
  src/python/pants/backend/docker/util_rules/docker_build_context_test.py
  src/python/pants/backend/go/goals/package_binary.py
  src/python/pants/backend/go/target_types.py
  src/python/pants/backend/go/util_rules/go_bootstrap.py
  src/python/pants/backend/go/util_rules/goroot.py
  src/python/pants/backend/google_cloud_function/python/rules.py
  src/python/pants/backend/google_cloud_function/python/target_types.py
  src/python/pants/backend/javascript/run/rules.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/python/goals/package_pex_binary.py
  src/python/pants/backend/python/packaging/pyoxidizer/rules.py
  src/python/pants/backend/python/packaging/pyoxidizer/target_types.py
  src/python/pants/backend/python/subsystems/pytest.py
  src/python/pants/backend/python/target_types.py
  src/python/pants/backend/python/util_rules/pex.py
  src/python/pants/backend/shell/goals/test.py
  src/python/pants/backend/shell/target_types.py
  src/python/pants/backend/shell/util_rules/shell_command.py
  src/python/pants/backend/shell/util_rules/shell_command_test.py
  src/python/pants/build_graph/build_configuration.py
  src/python/pants/core/environments/BUILD
  src/python/pants/core/environments/__init__.py
  src/python/pants/core/environments/subsystems.py
  src/python/pants/core/environments/target_types.py
  src/python/pants/core/goals/export_test.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/goals/run_test.py
  src/python/pants/core/register.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/subsystems/python_bootstrap_test.py
  src/python/pants/core/util_rules/adhoc_binaries.py
  src/python/pants/core/util_rules/adhoc_binaries_test.py
  src/python/pants/core/util_rules/asdf.py
  src/python/pants/core/util_rules/asdf_test.py
  src/python/pants/core/util_rules/environments.py
  src/python/pants/core/util_rules/environments_test.py
  src/python/pants/core/util_rules/search_paths.py
  src/python/pants/core/util_rules/search_paths_test.py
  src/python/pants/core/util_rules/system_binaries.py
  src/python/pants/engine/internals/platform_rules.py
  src/python/pants/engine/internals/platform_rules_test.py
  src/python/pants/engine/process_test.py
  src/python/pants/jvm/jdk_rules.py
  src/python/pants/option/subsystem.py
Labels: category:internal, release-notes:not-required

#22365 Prepare 2.25.2rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22366 Prepare 2.26.1rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22367 Prepare 2.27.0rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22361 upgrade to PyO3 v0.24.2
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/externs/address.rs
  src/rust/engine/src/externs/fs.rs
  src/rust/engine/src/intrinsics/dep_inference.rs
  src/rust/engine/src/nodes/execute_process.rs
Labels: category:internal, release-notes:not-required

#22369 upgrade to PyO3 v0.25.0
  docs/notes/2.28.x.md
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/src/externs/mod.rs
Labels: category:internal
