Repository pantsbuild/pants, pull requests merged in 2025-06, with the labels that each got.

#22374 Prepare 2.28.0.dev2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22364 fix: Remove "duplicate" rule call and parse tsconfig extends correctly
  docs/notes/2.28.x.md
  src/python/pants/backend/experimental/typescript/register.py
  src/python/pants/backend/javascript/dependency_inference/rules.py
  src/python/pants/backend/typescript/dependency_inference/BUILD
  src/python/pants/backend/typescript/dependency_inference/__init__.py
  src/python/pants/backend/typescript/dependency_inference/rules.py
  src/python/pants/backend/typescript/dependency_inference/rules_test.py
  src/python/pants/backend/typescript/tsconfig.py
  src/python/pants/backend/typescript/tsconfig_test.py
Labels: category:bugfix, backend: JavaScript

#22363 feat: Support TSX grammar, allowing inferring type imports in typescript
  docs/notes/2.28.x.md
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/dep_inference/Cargo.toml
  src/rust/engine/dep_inference/build.rs
  src/rust/engine/dep_inference/src/javascript/mod.rs
  src/rust/engine/dep_inference/src/javascript/tests.rs
Labels: category:new feature, backend: JavaScript

#22379 PBS: scrape releases `20250529` and `20250604`
  docs/notes/2.28.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal

#22385 Prepare 2.26.1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22387 better document the target filter syntax
  docs/docs/using-pants/advanced-target-selection.mdx
  src/python/pants/backend/project_info/filter_targets.py
Labels: needs-cherrypick, category:documentation, release-notes:not-required

#22395 mypy: upgrade to v1.15.0
  3rdparty/python/mypy-requirements.txt
  3rdparty/python/mypy.lock
  src/python/pants/backend/docker/goals/package_image.py
  src/python/pants/core/util_rules/archive_test.py
  src/python/pants/testutil/rule_runner.py
  src/python/pants/vcs/git.py
Labels: category:internal, release-notes:not-required

#22409 Migrate most of graph.py to call-by-name
  src/python/pants/engine/internals/graph.py
  src/python/pants/engine/internals/specs_rules.py
Labels: release-notes:not-required

#22408 add missing backends to releases
  src/python/pants/bin/BUILD
Labels: category:bugfix, release-notes:not-required

#22406 add missing backends to releases
  src/python/pants/backend/codegen/python_format_string/target_types.py
  src/python/pants/backend/experimental/codegen/python_format_string/BUILD
  src/python/pants/backend/experimental/codegen/python_format_string/k8s/BUILD
  src/python/pants/backend/experimental/codegen/python_format_string/register.py
  src/python/pants/backend/experimental/docker/lint/trivy/BUILD
  src/python/pants/backend/experimental/terraform/lint/trivy/BUILD
  src/python/pants/backend/k8s/target_types.py
  src/python/pants/bin/BUILD
Labels: needs-cherrypick, category:bugfix, release-notes:not-required

#22405 scrape PBS release `20250610` (Cherry pick of #22402)
  docs/notes/2.27.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal

#22381 pex: upgrade to v2.40.1
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/notes/2.28.x.md
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: category:internal

#22413 Prepare 2.27.0rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22414 configure `protoc` to generate Python type stubs directly
  docs/notes/2.28.x.md
  src/python/pants/backend/codegen/protobuf/python/python_protobuf_subsystem.py
  src/python/pants/backend/codegen/protobuf/python/rules.py
  src/python/pants/backend/codegen/protobuf/python/rules_integration_test.py
  src/python/pants/backend/python/typecheck/mypy/rules_integration_test.py
Labels: category:new feature

#22417 Prepare 2.28.0.dev4
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22389 Support using different binary name to package with NodeJSTool
  docs/notes/2.28.x.md
  src/python/pants/backend/javascript/package_manager.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool.py
  src/python/pants/backend/javascript/subsystems/nodejs_tool_test.py
  src/python/pants/backend/openapi/lint/spectral/subsystem.py
Labels: category:new feature

#22430 Update 2.27.x release notes in anticipation of the 2.27.0 release.
  docs/notes/2.27.x.md
Labels: needs-cherrypick, release-notes:not-required

#22434 Delay experimental_test_shell_command deprecated alias removal to 2.30
  src/python/pants/backend/shell/target_types.py
Labels: release-notes:not-required

#22429 Prepare 2.27.0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22439 Move most of the remaining tests from `tests/` to `src/`.
  src/python/pants/base/exception_sink_integration_test.py
  src/python/pants/engine/BUILD
  src/python/pants/engine/native_engine_logging_integration_test.py
  src/python/pants/engine/streaming_workunit_handler_integration_test.py
  src/python/pants/init/BUILD
  src/python/pants/init/extension_loader_test.py
  src/python/pants/init/logging_test.py
  src/python/pants/init/options_initializer_test.py
  src/python/pants/init/plugin_resolver_test.py
  src/python/pants/init/util_test.py
  src/python/pants/pantsd/BUILD
  src/python/pants/pantsd/lock_test.py
  src/python/pants/pantsd/pants_daemon_core_test.py
  src/python/pants/pantsd/pantsd_integration_test.py
  src/python/pants/pantsd/pantsd_integration_test_base.py
  src/python/pants/pantsd/process_manager_test.py
  src/python/pants/pantsd/service/pants_service_test.py
  src/python/pants/util/requirements_test.py
  tests/python/pants_test/init/BUILD
  tests/python/pants_test/init/__init__.py
  tests/python/pants_test/integration/goal_rule_integration_test.py
  tests/python/pants_test/logging/BUILD
  tests/python/pants_test/logging/__init__.py
  tests/python/pants_test/pantsd/BUILD
  tests/python/pants_test/pantsd/__init__.py
  tests/python/pants_test/pantsd/service/BUILD
  tests/python/pants_test/pantsd/service/__init__.py
  tests/python/pants_test/pantsd/stderr
  tests/python/pants_test/util/BUILD
Labels: release-notes:not-required
