Repository pantsbuild/pants, pull requests merged in 2025-07, with the labels that each got.

#22432 Prepare 2.25.3rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22433 Prepare 2.28.0a0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22426 chore: add node_build_script to javascript target_types
  docs/notes/2.29.x.md
  src/python/pants/backend/javascript/package_json.py
Labels: category:bugfix, backend: JavaScript

#22449 Prepare 2.25.3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22450 Prepare 2.26.2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22457 Prepare 2.29.0.dev0
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22467 Fix a lacuna in the tailor unit test.
  src/python/pants/core/goals/tailor_test.py
Labels: release-notes:not-required

#22469 add more module mappings for `grpcio` including type stubs
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: needs-cherrypick, category:internal, release-notes:not-required

#22470 Mention call-by-name migration with real-world numbers in 2.28 release notes
  docs/notes/2.28.x.md
Labels: needs-cherrypick

#22476 Mention call-by-name migration with real-world numbers in 2.28 release notes (Cherry-pick of #22470)
  docs/notes/2.28.x.md
Labels: release-notes:not-required

#22481 rust: upgrade to v1.88.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/client/src/client.rs
  src/rust/engine/concrete_time/src/lib.rs
  src/rust/engine/dep_inference/src/dockerfile/from.rs
  src/rust/engine/dep_inference/src/python/tests.rs
  src/rust/engine/fs/brfs/src/main.rs
  src/rust/engine/fs/brfs/src/syscall_tests.rs
  src/rust/engine/fs/brfs/src/tests.rs
  src/rust/engine/fs/src/glob_matching.rs
  src/rust/engine/fs/store/benches/store.rs
  src/rust/engine/fs/store/src/cli_options.rs
  src/rust/engine/fs/store/src/lib.rs
  src/rust/engine/fs/store/src/local.rs
  src/rust/engine/grpc_util/src/channel.rs
  src/rust/engine/grpc_util/src/tls.rs
  src/rust/engine/logging/src/logger.rs
  src/rust/engine/nailgun/src/server.rs
  src/rust/engine/options/src/arg_splitter_tests.rs
  src/rust/engine/options/src/cli_alias.rs
  src/rust/engine/options/src/cli_alias_tests.rs
  src/rust/engine/options/src/config.rs
  src/rust/engine/options/src/fromfile_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/parse_tests.rs
  src/rust/engine/process_execution/children/src/lib.rs
  src/rust/engine/process_execution/docker/src/docker.rs
  src/rust/engine/process_execution/docker/src/docker_tests.rs
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/sandboxer/src/lib.rs
  src/rust/engine/process_execution/src/cache.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/remote_provider/remote_provider_opendal/src/lib.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store.rs
  src/rust/engine/remote_provider/remote_provider_reapi/src/byte_store_tests.rs
  src/rust/engine/rule_graph/src/builder.rs
  src/rust/engine/rule_graph/src/lib.rs
  src/rust/engine/rust-toolchain
  src/rust/engine/sharded_lmdb/src/lib.rs
  src/rust/engine/src/context.rs
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/externs/options.rs
  src/rust/engine/src/externs/target.rs
  src/rust/engine/src/intrinsics/digests.rs
  src/rust/engine/src/intrinsics/interactive_process.rs
  src/rust/engine/src/nodes/execute_process.rs
  src/rust/engine/src/nodes/mod.rs
  src/rust/engine/src/python.rs
  src/rust/engine/src/session.rs
  src/rust/engine/src/tasks.rs
  src/rust/engine/stdio/src/lib.rs
  src/rust/engine/task_executor/src/lib.rs
  src/rust/engine/watch/src/lib.rs
  src/rust/engine/workunit_store/src/lib.rs
Labels: category:internal, release-notes:not-required

#22482 Fix polymorphic call-by-name
  src/python/pants/core/goals/generate_snapshots.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/engine/internals/scheduler.py
  src/python/pants/engine/internals/scheduler_test.py
  src/rust/engine/src/externs/interface.rs
  src/rust/engine/src/nodes/task.rs
  src/rust/engine/src/tasks.rs
Labels: release-notes:not-required

#22474 add more module mappings for `grpcio` including type stubs (Cherry-pick of #22469)
  src/python/pants/backend/python/dependency_inference/default_module_mapping.py
Labels: category:internal, release-notes:not-required

#22468 Port more core files to call-by-name.
  src/python/pants/core/goals/run.py
  src/python/pants/core/goals/tailor.py
  src/python/pants/core/goals/update_build_files.py
  src/python/pants/core/goals/update_build_files_test.py
  src/python/pants/core/util_rules/adhoc_process_support.py
Labels: release-notes:not-required

#22485 Port more core files to call-by-name.
  src/python/pants/core/target_types.py
  src/python/pants/core/util_rules/asdf.py
Labels: release-notes:not-required

#22494 PBS: scrape `SHA256SUMS` file for hashes instead of `.sha256` files
  3rdparty/python/pbs-script-requirements.lock
  3rdparty/python/pbs-script-requirements.txt
  src/python/pants/backend/python/providers/python_build_standalone/scripts/generate_urls.py
Labels: category:internal, release-notes:not-required

#22498 rust: upgrade `itertools` crate to v0.14.0
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/fs/src/directory.rs
Labels: category:internal, release-notes:not-required

#22508 Prepare 2.29.0.dev1
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22516 Convert most of the core lint/fix/fmt Gets to call-by-name
  src/python/pants/backend/scala/lint/scalafix/rules.py
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_test.py
Labels: release-notes:not-required

#22515 Use pipes and avoid wrapping in generated CI yaml, for easier human introspection
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/public_repos.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: release-notes:not-required

#22513 send work unit telemetry in CI to Honeycomb
  .github/workflows/cache_comparison.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  pants.ci.toml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#22522 make sure to prooperly disable honeycomb spans in github forks
  .github/workflows/cache_comparison.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal, release-notes:not-required

#22523 [docs] Add guidance on using buildx kubernetes drivers for docker images
  docs/docs/docker/index.mdx
Labels: needs-cherrypick, release-notes:not-required

#22524 log a link to Honeycomb UI for traces
  pants.ci.toml
Labels: category:internal, release-notes:not-required

#22537 Prepare 2.29.0.dev2
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22538 Prepare 2.28.0rc0
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22544 Attempt to ensure that sandboxer socket path is short.
  docs/notes/2.28.x.md
  src/rust/process_execution/sandboxer/src/lib.rs
Labels: needs-cherrypick

#22545 Use the sandboxer in our own CI.
  pants.ci.toml
Labels: release-notes:not-required

#22546 Attempt to ensure that sandboxer socket path is short. (Cherry-pick of #22544)
  docs/notes/2.28.x.md
  src/rust/engine/process_execution/sandboxer/src/lib.rs
Labels: release-notes:not-required

#22549 scrape PBS release 20250723
  docs/notes/2.29.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: needs-cherrypick, category:internal

#22541 Migrate remaining lint/fix/fmt to call-by-name.
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/lint.py
  src/python/pants/core/goals/lint_goal.py
  src/python/pants/core/goals/lint_test.py
  src/python/pants/core/register.py
  src/rust/engine/src/nodes/task.rs
Labels: release-notes:not-required
