Repository pantsbuild/pants, pull requests merged in 2025-04, with the labels that each got.

#22155 Prepare 2.25.1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22154 Prepare 2.24.3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22162 Replace deprecated importlib.resources.read_binary with (files() / …).read_bytes()
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: needs-cherrypick, release-notes:not-required

#22165 Replace deprecated importlib.resources.read_binary with (files() / …).read_bytes() (Cherry-pick of #22162)
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: release-notes:not-required

#22164 Replace deprecated importlib.resources.read_binary with (files() / …).read_bytes() (Cherry-pick of #22162)
  src/python/pants/backend/python/util_rules/faas.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
Labels: release-notes:not-required

#22157 Include all commits in GH release summary
  src/python/pants_release/changelog.py
Labels: release-notes:not-required

#22163 Copy-edit and find highlights in 2.26 release notes
  docs/notes/2.26.x.md
Labels: needs-cherrypick

#22171 Copy-edit and find highlights in 2.26 release notes (Cherry-pick of #22163)
  docs/notes/2.26.x.md
Labels: release-notes:not-required

#22177 upgrade to Rust v1.86.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/fs/src/directory.rs
  src/rust/engine/fs/src/lib.rs
  src/rust/engine/graph/src/entry.rs
  src/rust/engine/graph/src/lib.rs
  src/rust/engine/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/engine/process_execution/remote/src/remote.rs
  src/rust/engine/process_execution/src/bounded.rs
  src/rust/engine/process_execution/src/fork_exec.rs
  src/rust/engine/rust-toolchain
  src/rust/engine/sharded_lmdb/src/lib.rs
  src/rust/engine/testutil/mock/src/execution_server.rs
  src/rust/engine/ui/src/instance/prodash.rs
  src/rust/engine/watch/src/lib.rs
Labels: category:internal, release-notes:not-required

#22096 Don't run a full CI on devcontainer changes
  .github/workflows/test.yaml
  build-support/bin/classify_changed_files.py
  build-support/bin/classify_changed_files_test.py
  src/python/pants_release/generate_github_workflows.py
Labels: release-notes:not-required

#22188 Prepare 2.27.0.dev2
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22187 perf: immutable digest for shell dependency inference
  docs/notes/2.27.x.md
  src/python/pants/backend/shell/dependency_inference.py
Labels: release-notes:not-required

#22193 Update Cargo.lock to latest deps versions.
  src/rust/engine/Cargo.lock
  src/rust/engine/dep_inference/src/javascript/mod.rs
Labels: release-notes:not-required

#22194 Initial code for the sandboxer service
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
  src/rust/engine/fs/store/src/cli_options.rs
  src/rust/engine/process_execution/sandboxer/Cargo.toml
  src/rust/engine/process_execution/sandboxer/src/lib.rs
  src/rust/engine/protos/build.rs
  src/rust/engine/protos/protos/pants/sandboxer.proto
  src/rust/engine/protos/src/lib.rs
Labels: release-notes:not-required

#22205 Function to convert a StoreCliOpt into cli option strings.
  src/rust/engine/fs/store/src/cli_options.rs
  src/rust/engine/fs/store/src/cli_options_tests.rs
  src/rust/engine/fs/store/src/lib.rs
Labels: release-notes:not-required

#22206 Sandboxer server and client binaries.
  src/rust/engine/process_execution/sandboxer/Cargo.toml
  src/rust/engine/process_execution/sandboxer/bin/client.rs
  src/rust/engine/process_execution/sandboxer/bin/server.rs
  src/rust/engine/process_execution/sandboxer/src/lib.rs
Labels: release-notes:not-required

#22217 Reorder the args of the environment_vars_subset rule.
  src/python/pants/backend/codegen/thrift/apache/rules.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/rust/util_rules/toolchains.py
  src/python/pants/engine/internals/platform_rules.py
Labels: release-notes:not-required

#22214 Prepare 2.26.0rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22210 Sandboxer process management
  src/rust/engine/process_execution/children/src/lib.rs
  src/rust/engine/process_execution/sandboxer/src/lib.rs
Labels: release-notes:not-required
