Repository pantsbuild/pants, pull requests merged in 2025-09, with the labels that each got.

#22606 Prepare 2.29.0.dev5
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22605 A GH action to automate periodic creation of a new RunsOn AMI
  .github/workflows/build_runson_ami.yaml
  build-support/packer/runson/runson.pkr.hcl
Labels: release-notes:not-required

#22609 Fix the RunsOn AMI building action.
  .github/workflows/build_runson_ami.yaml
Labels: release-notes:not-required

#22620 Port streaming_workunit_handler.py to call-by-name
  src/python/pants/engine/streaming_workunit_handler.py
Labels: release-notes:not-required

#22619 Refactor `environment_vars_subset` to its own file in core
  src/python/pants/backend/cc/util_rules/toolchain.py
  src/python/pants/backend/codegen/protobuf/scala/rules.py
  src/python/pants/backend/codegen/thrift/apache/rules.py
  src/python/pants/backend/docker/goals/publish.py
  src/python/pants/backend/docker/goals/run_image.py
  src/python/pants/backend/docker/util_rules/docker_build_env.py
  src/python/pants/backend/go/goals/generate.py
  src/python/pants/backend/go/goals/test.py
  src/python/pants/backend/go/util_rules/cgo.py
  src/python/pants/backend/go/util_rules/sdk.py
  src/python/pants/backend/helm/check/kubeconform/common.py
  src/python/pants/backend/helm/util_rules/tool.py
  src/python/pants/backend/javascript/goals/test.py
  src/python/pants/backend/javascript/nodejs_project_environment.py
  src/python/pants/backend/javascript/package/rules.py
  src/python/pants/backend/javascript/run/rules.py
  src/python/pants/backend/javascript/subsystems/nodejs.py
  src/python/pants/backend/javascript/subsystems/nodejs_test.py
  src/python/pants/backend/k8s/goals/deploy.py
  src/python/pants/backend/python/goals/publish.py
  src/python/pants/backend/python/goals/pytest_runner.py
  src/python/pants/backend/python/providers/pyenv/rules.py
  src/python/pants/backend/python/util_rules/package_dists.py
  src/python/pants/backend/rust/util_rules/toolchains.py
  src/python/pants/backend/scala/test/scalatest.py
  src/python/pants/backend/terraform/tool.py
  src/python/pants/backend/tools/trivy/rules.py
  src/python/pants/backend/url_handlers/s3/register.py
  src/python/pants/core/goals/export.py
  src/python/pants/core/goals/test.py
  src/python/pants/core/register.py
  src/python/pants/core/subsystems/python_bootstrap.py
  src/python/pants/core/util_rules/adhoc_process_support.py
  src/python/pants/core/util_rules/asdf.py
  src/python/pants/core/util_rules/env_vars.py
  src/python/pants/core/util_rules/subprocess_environment.py
  src/python/pants/engine/internals/build_files.py
  src/python/pants/engine/internals/build_files_test.py
  src/python/pants/engine/internals/platform_rules.py
  src/python/pants/engine/internals/platform_rules_test.py
  src/python/pants/jvm/test/junit.py
  src/python/pants/option/subsystem.py
Labels: release-notes:not-required

#22627 Switch several tests from mock gets to mock calls.
  src/python/pants/backend/awslambda/python/rules_test.py
  src/python/pants/backend/javascript/subsystems/nodejs_test.py
  src/python/pants/backend/python/goals/coverage_py_test.py
  src/python/pants/backend/python/subsystems/python_tool_base_test.py
  src/python/pants/backend/python/util_rules/pex_from_targets_test.py
  src/python/pants/backend/python/util_rules/pex_test.py
  src/python/pants/backend/python/util_rules/pex_venv_test.py
Labels: release-notes:not-required

#22649 Port core/environments to call-by-name.
  src/python/pants/core/environments/rules.py
  src/python/pants/core/environments/rules_test.py
Labels: release-notes:not-required

#22650 Port remaining JVM-related files to call-by-name
  src/python/pants/backend/scala/bsp/rules.py
  src/python/pants/backend/scala/goals/check.py
  src/python/pants/bsp/util_rules/compile.py
  src/python/pants/bsp/util_rules/resources.py
  src/python/pants/bsp/util_rules/targets.py
Labels: release-notes:not-required

#22646 release notes: startup benchmark results
  docs/notes/2.29.x.md
Labels: needs-cherrypick

#22661 A call_by_type pytest marker.
  pants.toml
  pyproject.toml
  src/python/pants/engine/internals/rule_visitor_test.py
  src/python/pants/engine/internals/selectors_test.py
  src/python/pants/goal/migrate_call_by_name_integration_test.py
Labels: release-notes:not-required

#22667 Port engine tests to call-by-name.
  src/python/pants/engine/internals/scheduler_test.py
  src/python/pants/engine/rules_test.py
  src/python/pants/testutil/rule_runner.py
Labels: release-notes:not-required

#22670 Optionally panic if a Get is used.
  src/python/pants/engine/internals/rule_visitor.py
  src/python/pants/engine/internals/selectors_test.py
  src/rust/engine/src/externs/mod.rs
Labels: release-notes:not-required

#22674 migrate `grpc_util` crate to 2024 Edition
  src/rust/grpc_util/Cargo.toml
  src/rust/grpc_util/src/lib.rs
Labels: category:internal, release-notes:not-required

#22675 migrate `dep_inference` crate to Rust 2024 Edition
  src/rust/dep_inference/Cargo.toml
  src/rust/dep_inference/src/javascript/mod.rs
  src/rust/dep_inference/src/python/mod.rs
Labels: category:internal, release-notes:not-required

#22677 migrate the `process_execution` crates to Rust 2024 Edition
  src/rust/process_execution/Cargo.toml
  src/rust/process_execution/children/Cargo.toml
  src/rust/process_execution/docker/Cargo.toml
  src/rust/process_execution/pe_nailgun/Cargo.toml
  src/rust/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/process_execution/remote/Cargo.toml
  src/rust/process_execution/sandboxer/Cargo.toml
  src/rust/process_execution/src/lib.rs
  src/rust/process_execution/src/local.rs
Labels: category:internal, release-notes:not-required

#22678 migrate the`graph` crate to Rust 2024 Edition
  src/rust/graph/Cargo.toml
  src/rust/graph/src/entry.rs
  src/rust/graph/src/lib.rs
Labels: category:internal, release-notes:not-required

#22683 migrate `fs` crates to Rust 2024 Edition
  src/rust/fs/Cargo.toml
  src/rust/fs/brfs/Cargo.toml
  src/rust/fs/fs_util/Cargo.toml
  src/rust/fs/src/directory.rs
  src/rust/fs/store/Cargo.toml
  src/rust/fs/store/src/cli_options.rs
Labels: category:internal, release-notes:not-required

#22680 migrate `options` crate to Rust 2024 Edition
  src/rust/options/Cargo.toml
  src/rust/options/src/cli_alias.rs
  src/rust/options/src/config.rs
  src/rust/options/src/lib.rs
  src/rust/options/src/parse.rs
Labels: category:internal, release-notes:not-required

#22684 migrate various crates to Rust 2024 Edition
  src/rust/address/Cargo.toml
  src/rust/cache/Cargo.toml
  src/rust/client/Cargo.toml
  src/rust/client/src/client.rs
  src/rust/concrete_time/Cargo.toml
  src/rust/hashing/Cargo.toml
  src/rust/logging/Cargo.toml
Labels: category:internal, release-notes:not-required

#22686 migrate most remaining crates to Rust 2024 Edition
  src/rust/engine/src/session.rs
  src/rust/nailgun/Cargo.toml
  src/rust/pantsd/Cargo.toml
  src/rust/process_executor/Cargo.toml
  src/rust/protos/Cargo.toml
  src/rust/protos/src/verification.rs
  src/rust/sharded_lmdb/Cargo.toml
  src/rust/stdio/Cargo.toml
  src/rust/testutil/Cargo.toml
  src/rust/testutil/local_cas/Cargo.toml
  src/rust/testutil/local_execution_server/Cargo.toml
  src/rust/testutil/mock/Cargo.toml
  src/rust/tryfuture/Cargo.toml
  src/rust/ui/Cargo.toml
  src/rust/ui/src/instance/indicatif.rs
  src/rust/ui/src/instance/prodash.rs
  src/rust/watch/Cargo.toml
  src/rust/workunit_store/Cargo.toml
  src/rust/workunit_store/src/lib.rs
Labels: category:internal, release-notes:not-required

#22689 Get rid of SchedulerTestBase.
  src/python/pants/engine/internals/engine_test.py
  src/python/pants/engine/internals/scheduler_test_base.py
Labels: release-notes:not-required

#22673 Prepare 2.30.0.dev1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22672 Prepare 2.29.0rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#22688 migrate `task_executor` crate to Rust 2024 Edition
  src/rust/fs/src/lib.rs
  src/rust/fs/store/src/local.rs
  src/rust/nailgun/src/server.rs
  src/rust/process_execution/docker/src/docker.rs
  src/rust/process_execution/pe_nailgun/src/nailgun_pool.rs
  src/rust/process_execution/src/local.rs
  src/rust/sharded_lmdb/src/lib.rs
  src/rust/task_executor/Cargo.toml
  src/rust/task_executor/src/lib.rs
  src/rust/ui/src/instance/prodash.rs
  src/rust/watch/src/lib.rs
Labels: category:internal, release-notes:not-required

#22705 skip mysteriously broken rustfmt test
  src/python/pants/backend/rust/lint/rustfmt/BUILD
Labels: release-notes:not-required

#22698 PBS: scrape release metadata through 20250918
  docs/notes/2.30.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal

#22707 Rewrite "writing plugins" docs to use call-by-name.
  docs/docs/writing-plugins/common-plugin-tasks/add-a-formatter.mdx
  docs/docs/writing-plugins/common-plugin-tasks/add-a-linter.mdx
  docs/docs/writing-plugins/common-plugin-tasks/add-a-repl.mdx
  docs/docs/writing-plugins/common-plugin-tasks/add-codegen.mdx
  docs/docs/writing-plugins/common-plugin-tasks/custom-python-artifact-kwargs.mdx
  docs/docs/writing-plugins/common-plugin-tasks/plugin-lockfiles.mdx
  docs/docs/writing-plugins/common-plugin-tasks/run-tests.mdx
Labels: release-notes:not-required

#22708 Rewrite a last few docs to use call-by-name.
  docs/docs/contributions/development/internal-architecture.mdx
  docs/docs/writing-plugins/common-plugin-tasks/plugin-upgrade-guide.mdx
  src/rust/rule_graph/README.md
Labels: release-notes:not-required
