Repository pantsbuild/pants, pull requests merged in 2025-01, with the labels that each got.

#21806 nfpm(bugfix): handle package targets w/ output_path
  src/python/pants/backend/nfpm/field_sets.py
  src/python/pants/backend/nfpm/util_rules/generate_config.py
  src/python/pants/backend/nfpm/util_rules/generate_config_test.py
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
Labels: release-notes:not-required

#21807 nfpm: Improve field doc rendering on website
  src/python/pants/backend/nfpm/fields/all.py
  src/python/pants/backend/nfpm/fields/apk.py
  src/python/pants/backend/nfpm/fields/archlinux.py
  src/python/pants/backend/nfpm/fields/contents.py
  src/python/pants/backend/nfpm/fields/deb.py
  src/python/pants/backend/nfpm/fields/rpm.py
Labels: release-notes:not-required

#21809 nfpm(bugfix): handle package targets w/ output_path (Cherry-pick of #21806)
  src/python/pants/backend/nfpm/field_sets.py
  src/python/pants/backend/nfpm/util_rules/generate_config.py
  src/python/pants/backend/nfpm/util_rules/generate_config_test.py
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
Labels: category:bugfix, release-notes:not-required

#21808 nfpm(bugfix): handle package targets w/ output_path (Cherry-pick of #21806)
  src/python/pants/backend/nfpm/field_sets.py
  src/python/pants/backend/nfpm/util_rules/generate_config.py
  src/python/pants/backend/nfpm/util_rules/generate_config_test.py
  src/python/pants/backend/nfpm/util_rules/sandbox_test.py
Labels: category:bugfix, release-notes:not-required

#21810 substitute `{chroot}` marker in environment variables for remote execution
  docs/notes/2.25.x.md
  src/rust/engine/process_execution/remote/src/remote_tests.rs
  src/rust/engine/process_execution/src/lib.rs
  src/rust/engine/process_execution/src/tests.rs
Labels: category:new feature

#21811 Remove unnecessary logic from ArgSplitter
  src/python/pants/bin/local_pants_runner.py
  src/python/pants/option/arg_splitter.py
  src/python/pants/option/arg_splitter_test.py
  src/python/pants/option/options.py
Labels: category:internal

#21812 Remove cruft from the ArgSplitter.
  src/python/pants/option/arg_splitter.py
  src/python/pants/option/arg_splitter_test.py
Labels: category:internal

#20548 Add script to identify backends not part of the pants distribution.
  build-support/bin/check_orphaned_plugins.py
Labels: category:internal

#21820 fix flaky failure in `export_integration_test.py` (Cherry-pick of #21756)
  src/python/pants/backend/python/goals/export_integration_test.py
Labels: category:internal

#21821 fix flaky failure in `export_integration_test.py` (Cherry-pick of #21756)
  src/python/pants/backend/python/goals/export_integration_test.py
Labels: category:internal

#20985 Log infinite symlink offender
  src/rust/engine/Cargo.lock
  src/rust/engine/fs/Cargo.toml
  src/rust/engine/fs/src/directory.rs
Labels: category:documentation, release-notes:not-required

#21817 Prepare 2.25.0.dev4
  CONTRIBUTORS.md
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21818 Prepare 2.24.0rc1
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21819 Prepare 2.23.2rc0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21814 Reimplement the ArgSplitter in Rust.
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/arg_splitter.py
  src/rust/engine/options/src/arg_splitter.rs
  src/rust/engine/options/src/arg_splitter_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#21824 Integrate the new Rust ArgSplitter.
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/arg_splitter.py
  src/python/pants/option/arg_splitter_test.py
Labels: category:internal

#21827 A new RunsOn AMI
  .github/runs-on.yml
Labels: category:internal

#21828 scrape PBS 20250106 release
  docs/notes/2.25.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal

#21825 Move the Rust Scope code to its own file.
  src/rust/engine/options/src/args.rs
  src/rust/engine/options/src/cli_alias.rs
  src/rust/engine/options/src/env.rs
  src/rust/engine/options/src/id.rs
  src/rust/engine/options/src/id_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/scope.rs
  src/rust/engine/options/src/scope_tests.rs
Labels: category:internal

#21834 Pass GoalInfo through to the Rust ArgSplitter.
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/goal/auxiliary_goal.py
  src/python/pants/goal/builtin_goal.py
  src/python/pants/goal/help.py
  src/python/pants/option/arg_splitter.py
  src/rust/engine/options/src/arg_splitter.rs
  src/rust/engine/options/src/arg_splitter_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/scope.rs
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#21832 Packer config for building the RunsOn AMI.
  build-support/packer/runson/runson.pkr.hcl
  docs/docs/contributions/releases/github-actions-linux-aarch64-runners.mdx
Labels: category:internal

#21841 Move most of the remaining ArgSplitter logic to Rust.
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/arg_splitter.py
  src/rust/engine/options/src/arg_splitter.rs
  src/rust/engine/options/src/arg_splitter_tests.rs
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#21706 Fix: Creating ZIP archives with no file extension (Cherry-pick of #21694)
  src/python/pants/core/util_rules/archive.py
  src/python/pants/core/util_rules/archive_test.py
  src/python/pants/core/util_rules/system_binaries.py
Labels: category:bugfix, release-notes:not-required

#21843 upgrade to Rust v1.84.0
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  src/rust/engine/dep_inference/src/javascript/mod.rs
  src/rust/engine/process_execution/src/local.rs
  src/rust/engine/rust-toolchain
Labels: category:internal, release-notes:not-required

#21846 pex: upgrade to v2.29.0
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/notes/2.25.x.md
  src/python/pants/backend/python/util_rules/pex_cli.py
Labels: category:internal

#21847 upgrade tokio to v1.43.0
  src/rust/engine/Cargo.lock
Labels: category:internal, release-notes:not-required

#21826 refactor: devcontainer scripts
  .devcontainer/devcontainer.json
  .devcontainer/postCreateCommand.sh
  .devcontainer/postStartCommand.sh
Labels: category:internal

#21848 PyO3: upgrade to v0.23.4
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal, release-notes:not-required

#21854 bump some test timeouts
  src/python/pants/backend/build_files/fmt/black/BUILD
  src/python/pants/backend/build_files/fmt/yapf/BUILD
Labels: category:internal, release-notes:not-required

#21614 golang: allow downloads during instalation of gRPC protobuf plugins
  docs/notes/2.25.x.md
  src/python/pants/backend/codegen/protobuf/go/rules.py
Labels: needs-cherrypick, category:bugfix

#21857 golang: allow downloads during instalation of gRPC protobuf plugins (Cherry-pick of #21614)
  src/python/pants/backend/codegen/protobuf/go/rules.py
Labels: category:bugfix, release-notes:not-required

#21856 golang: allow downloads during instalation of gRPC protobuf plugins (Cherry-pick of #21614)
  src/python/pants/backend/codegen/protobuf/go/rules.py
Labels: category:bugfix, release-notes:not-required

#21855 scrape 20250115 PBS release
  docs/notes/2.25.x.md
  src/python/pants/backend/python/providers/python_build_standalone/versions_info.json
Labels: category:internal

#21734 Enable proto3 optional to enable engine builds for Ubuntu 22.04
  src/rust/engine/protos/build.rs
Labels: category:internal

#21860 Delete the Python ArgSplitter.
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/goal/completion.py
  src/python/pants/goal/run_tracker_test.py
  src/python/pants/help/help_formatter_test.py
  src/python/pants/help/help_info_extracter_test.py
  src/python/pants/help/help_tools_test.py
  src/python/pants/option/arg_splitter.py
  src/python/pants/option/arg_splitter_test.py
  src/python/pants/option/native_options.py
  src/python/pants/option/options.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_test.py
  src/rust/engine/client/src/client_tests.rs
  src/rust/engine/client/src/main.rs
  src/rust/engine/options/src/arg_splitter.rs
  src/rust/engine/options/src/arg_splitter_tests.rs
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/pantsd/src/pantsd_testing.rs
  src/rust/engine/src/externs/options.rs
  src/rust/engine/src/externs/pantsd.rs
Labels: category:internal

#21862 Prepare 2.24.0rc2
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21849 Fix issue where pants run only working when package.json at root
  docs/notes/2.25.x.md
  src/python/pants/backend/javascript/run/rules.py
  src/python/pants/backend/javascript/run/rules_test.py
Labels: category:bugfix

#21867 always use an explicit ubuntu image
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/public_repos.yaml
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: needs-cherrypick, release-notes:not-required

#21864 Interlink/explain differences with lint, fmt and fix goals
  docs/docs/python/goals/fmt.mdx
  docs/docs/python/overview/linters-and-formatters.mdx
  src/python/pants/core/goals/fix.py
  src/python/pants/core/goals/fmt.py
  src/python/pants/core/goals/lint.py
Labels: release-notes:not-required

#21868 always use an explicit ubuntu image (Cherry-pick of #21867)
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/public_repos.yaml
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: release-notes:not-required

#21869 always use an explicit ubuntu image (Cherry-pick of #21867)
  .github/workflows/audit.yaml
  .github/workflows/cache_comparison.yaml
  .github/workflows/public_repos.yaml
  .github/workflows/release.yaml
  src/python/pants_release/generate_github_workflows.py
Labels: category:internal

#21870 Prepare 2.24.0rc3
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21872 Reimplement the pants_bin_name functionality in Rust.
  src/python/pants/backend/python/util_rules/pex_requirements_test.py
  src/python/pants/engine/internals/native_engine.pyi
  src/python/pants/option/option_types_test.py
  src/python/pants/option/options_bootstrapper.py
  src/python/pants/option/options_bootstrapper_test.py
  src/python/pants/pantsd/pants_daemon_client.py
  src/python/pants/util/docutil.py
  src/rust/engine/options/src/lib.rs
  src/rust/engine/options/src/tests.rs
  src/rust/engine/src/externs/options.rs
Labels: category:internal

#21874 upgrade the `indicatif` crate to v0.17.9
  src/rust/engine/Cargo.lock
  src/rust/engine/Cargo.toml
Labels: category:internal, release-notes:not-required

#21875 Prepare 2.25.0.dev5
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21805 Fix concurrency issue of Terraform provider cache
  docs/notes/2.25.x.md
  src/python/pants/backend/terraform/goals/deploy_test.py
  src/python/pants/backend/terraform/tool.py
Labels: category:bugfix, backend: Terraform

#21879 Prepare 2.24.0
  src/python/pants/VERSION
Labels: category:internal, automation:release-prep

#21881 fix link format in aarch64 runner instructions
  docs/docs/contributions/releases/github-actions-linux-aarch64-runners.mdx
Labels: release-notes:not-required

#21882 docs: s/mac/linux/ for aarch64 links
  docs/docs/contributions/releases/index.mdx
Labels: needs-cherrypick, release-notes:not-required

#21890 docs: s/mac/linux/ for aarch64 links (Cherry-pick of #21882)
  docs/docs/contributions/releases/index.mdx
Labels: category:internal, release-notes:not-required

#21891 docs: s/mac/linux/ for aarch64 links (Cherry-pick of #21882)
  docs/docs/contributions/releases/index.mdx
Labels: release-notes:not-required

#21877 pex: upgrade to v2.32.0
  3rdparty/python/requirements.txt
  3rdparty/python/user_reqs.lock
  docs/notes/2.25.x.md
  src/python/pants/backend/python/util_rules/pex_cli.py
  src/python/pants/backend/python/util_rules/pex_test.py
Labels: category:internal

#21889 Fix concurrency issue of Terraform provider cache (Cherry-pick of #21805)
  src/python/pants/backend/terraform/goals/deploy_test.py
  src/python/pants/backend/terraform/tool.py
Labels: category:bugfix, release-notes:not-required

#21692 Update yaml globs for Helm to support common chart structures
  docs/notes/2.25.x.md
  src/python/pants/backend/helm/target_types.py
Labels: needs-cherrypick, category:bugfix, backend: Helm
